### ISSUE TITLE
create packages with fpm

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#10]
See: https://www.reddit.com/r/golang/comments/5l3i9b/deliver_go_binaries_as_fast_and_easy_as_possible/dbsrx16/

**Comment by ryanbreed** [comment]
yeah, only thought on using fpm vs scaffolding some rpm spec templates is that fpm would add a whole other language runtime dependency to the mix. stealing it's brainjuice for packaging and just calling rpmtools directly would eliminate the need for keeping yet another ruby runtime around (which i don't particularly mind). another example would be [pleaserun](https://github.com/jordansissel/pleaserun), which could also generate systemd units, rc.d scripts, etc, but requires a ruby runtime to make it work.

**Comment by dz0ny** [comment]
https://github.com/dz0ny/cdeb :) Needs a bit of work, currently only naive approach is supported (via data directory)

**Comment by sairam** [comment]
Adding link to [fpm](https://github.com/jordansissel/fpm) directly instead of redirecting through reddit link

**Comment by jspc** [comment]
@sairam I think the reddit link is to give context for the issue

**Comment by caarlos0** [comment]
For everyone interested, please check #109 =D
