### ISSUE TITLE
"git is currently in a dirty state" error message lacks information to debug the problem

### ISSUE THREAD

**Issue by twpayne** [goreleaser/goreleaser#1005]
**Describe the bug**

`goreleaser` builds for [my project](https://github.com/twpayne/chezmoi) are failing with the error message:

```
   • releasing using goreleaser 0.104.3...
   • loading config file       file=.goreleaser.yaml
   • RUNNING BEFORE HOOKS
      • running go mod download
   • GETTING AND VALIDATING GIT STATE
      • releasing v1.4.2, commit 6e5813cb91d4daca0efbc4297969a9819824e342
   ⨯ release failed after 1.90s error=git is currently in a dirty state:
 M go.mod
 M go.sum
```

I am unable to reproduce this problem on my own machine, and the error message from `goreleaser` is insufficient to know where the problem lies.

**To Reproduce**

Not easily reproducible, see https://travis-ci.org/twpayne/chezmoi/builds/519012274 for example output.

**Expected behavior**

`goreleaser` prints enough information to debug where the problem is occurring. Specifically, `go releaser` should emit a full `git diff` not just a `git status`.

**Environment (please complete the following information):**

- OS: Linux
- OS version: Whatever travis-ci.org is running right now
- GoReleaser Version: 0.104.3

**Additional context**

None, but please just say if you need any more info.

**Comment by caarlos0** [comment]
something is changing your dependencies on the CI.

The message shows the changed files: `go.mod` and `go.sum`.

You can probably run `go mod tidy` locally, commit `go.sum` and `go.mod` and it should be fine.

Either that or you are using `go get` on CI, which is changing the  `go.{mod,sum}` files...

**Comment by twpayne** [comment]
I agree, something is changing my dependencies.

I've run `go mod tidy` locally, and nothing changes.

I run `go get` three times in `.travis.yml`:

https://github.com/twpayne/chezmoi/blob/master/.travis.yml#L19-L21

But this is all to install linters and tools, they don't (shouldn't?) affect the output binary.

If `goreleaser` told me where the differences were, I'd have more info to debug the problem :)

**Comment by caarlos0** [comment]
```
   ⨯ release failed after 1.90s error=git is currently in a dirty state:
 M go.mod
 M go.sum
```

it shows the files... you mean.. show the diff too?



> But this is all to install linters and tools, they don't (shouldn't?) affect the output binary.

I agree they shouldn't, but they do, unfortunately... that's why I try to install all linters with the binaries and etc..

I **guess** you can so something like `GO111MODULE=off go get blah` but I'm not sure...

**Comment by twpayne** [comment]
> it shows the files... you mean.. show the diff too?

Yes, please. This will help me debug the problem.

**Comment by caarlos0** [comment]
ok, but yeah, pretty sure its the `go get`s...

**Comment by twpayne** [comment]
OK, so what's the right fix here?

`goreleaser` runs (and is awesome) when I tag a new version, but I need `go get` to install the various linters for every pull request. If I remove the `go get`s then then I can't run the linters on every PR.

It's a known problem with Go modules that `go.mod`/`go.sum` get modified if you run `go get` in your project's directory, and that the workaround is to install tools from a temporary directory with a temporary `go.mod` file.

I'm not sure what the right solution is here.

**Comment by caarlos0** [comment]
> I **guess** you can so something like `GO111MODULE=off go get blah` but I'm not sure...

have you tried this?

**Comment by caarlos0** [comment]
```

~/Code/goreleaser/goreleaser master
❯ GO111MODULE=off go get golang.org/x/tools/cmd/cover

~/Code/goreleaser/goreleaser master
❯ gs
## master...origin/master

~/Code/goreleaser/goreleaser master
❯
```

works here...

**Comment by twpayne** [comment]
Trying: https://github.com/twpayne/chezmoi/commit/315d1e6fc82800a7db6f2659805a0a1777ff4cff.

Build in progress: https://travis-ci.org/twpayne/chezmoi/builds/519046241

Thanks for being super-responsive! Much appreciated :)

**Comment by twpayne** [comment]
Arg `s/GOMODULE=off/GO111MODULE=off/`, retrying...

**Comment by caarlos0** [comment]
was about to say just that haha

**Comment by twpayne** [comment]
Oh pantsicles, the build passed but Travis didn't detect that I moved the tag, so I've created a new tag. Retrying...

**Comment by twpayne** [comment]
Yay! That pretty much worked. I still have one error to fix, but it's unrelated to this issue:

```
   ⨯ release failed after 333.67s error=Snapcraft Packages: failed to publish artifacts: failed to push dist/chezmoi_1.4.2_linux_ppc64.snap package: Preparing to push 'chezmoi_1.4.2_linux_ppc64.snap'.
After pushing, an attempt will be made to release to 'stable'
Pushing 'chezmoi_1.4.2_linux_ppc64.snap' [===============================] 100%
Processing...|                                                                 
Error while processing...
The store was unable to accept this snap.
  - architectures: Invalid architecture specified in the manifest: ppc64.
```

(there's also a weird mis-match between building version 1.4.2 when the tagged version is 1.4.3, but this is for me to investigate first).

Thanks again for being super responsive - and I think that the original request in this issue (print the output of `git diff`, not just the output of `git status`) still holds.

**Comment by twpayne** [comment]
Let's keep this open for now. I'll see if I can come up with a PR.

**Comment by dtitov** [comment]
I'm not sure if it will help anyone, but I've got the same issue. The problem was in the position of `go 1.14` line in my `go.mod` file. I had it like that:
```
module <module name>

require (
	github.com/buger/jsonparser v0.0.0-20191204142016-1a29609e0929
          ...
	github.com/jessevdk/go-flags v1.4.0
)

go 1.14
```

Then I moved it above the `require` block:

```
module <module name>

go 1.14

require (
	github.com/buger/jsonparser v0.0.0-20191204142016-1a29609e0929
          ...
	github.com/jessevdk/go-flags v1.4.0
)
```

And the build was fixed.

So, I guess, the modification you are talking about, is that `go get...` actually moves this line up automatically, but I'm not sure :) At least it seemed to be a case for me.
