### ISSUE TITLE
snapcraft: enable/disable uploading snaps by architecture

### ISSUE THREAD

**Issue by twpayne** [goreleaser/goreleaser#1006]
I'm trying to use Goreleaser's Snapcraft support to create and publish snaps of [`chezmoi`](https://github.com/twpayne/chezmoi). `chezmoi` is already using Goreleaser to build binaries and packages for several architectures, including `ppc64`, `ppc64le`, and `arm`.

The `ppc64`, `ppc64le`, and `arm` architectures are rejected as being invalid by `snapcraft.io`, for example:

```
  ⨯ release failed after 313.86s error=Snapcraft Packages: failed to publish artifacts: failed to push dist/chezmoi_1.4.2_linux_arm.snap package: Preparing to push 'chezmoi_1.4.2_linux_arm.snap'.
After pushing, an attempt will be made to release to 'stable'
Pushing 'chezmoi_1.4.2_linux_arm.snap' [=================================] 100%
Processing...|                                                                 
Error while processing...
The store was unable to accept this snap.
  - architectures: Invalid architecture specified in the manifest: arm.
```
([link to full build log](https://travis-ci.org/twpayne/chezmoi/builds/519783456))

There's a [discussion about this on the Snapcraft forum](https://forum.snapcraft.io/t/invalid-architecture-specified-in-the-manifest-ppc64/10904).

As far as I can tell:

* The `snapcraft.replacements` in `.gorealeaser.yaml` allows you to rename architectures, but not disable uploading them completely.
* Snapcraft does not support `ppc64` or `arm` (#683).
* Snapcraft claims to support `ppc64le` but is still rejecting the snap built by Goreleaser.
* The only existing way to disable the uploading of the snaps for the unsupported architectures is to remove them completely from `.goreleaser.yaml`, but this then means that binaries and packages also won't get built.

The feature request is therefore: "please can we have a way to disable the  creation and upload of snaps for specific architectures". Many thanks!

**Comment by caarlos0** [comment]
this shall be fixed once we have multiple archives... unfortunately I'm not able to invest much time on it lately :/

**Comment by twpayne** [comment]
Thanks for the quick response and clear status report :)

**Comment by twpayne** [comment]
For what it's worth, my short term plan is to run Goreleaser twice with two different configs: one with all the architectures to build packages etc. and a second one to build snaps with the problematic architectures disabled.

**Comment by caarlos0** [comment]
hey!

I think now this can be workaround by using the multiple archives thing... 

So, probably you going to have 2 builds, one with id `default` and another with `no_snapcraft` or whatever, and 2 archive configs as well, one for each.

finally, on snap config, you only add the archive id of the archives you want to publish...

that should do the trick :) 

can you try?

**Comment by twpayne** [comment]
This seems to work very nicely. Thank you very much!

**Comment by caarlos0** [comment]
awesome!


thanks
