### ISSUE TITLE
Support releasing WASM builds

### ISSUE THREAD

**Issue by tliron** [goreleaser/goreleaser#1017]
Right now the `GOARCH=wasm GOOS=js ` combination is ignored by GoReleaser, but it would be nice if we could also release `.wasm` files packaged and ready to use.

**Comment by caarlos0** [comment]
good idea, thanks! :D

**Comment by caarlos0** [comment]
not stale

**Comment by robdefeo** [comment]
This would be a really useful feature for us to be able to create .wasm releases.

**Comment by tliron** [comment]
Could you explain how to use this feature?

**Comment by tliron** [comment]
Nevermind, I figured it out. For the matrix it's: goos = js, goarch = wasm.

I just tested it and it seems to work. Thanks! I imagine this should also come with a fix to the documentation, too?

**Comment by tliron** [comment]
By the way, for completion: to test a WASM build, you can run this:
```
"$(go env GOROOT)/misc/wasm/go_js_wasm_exec" [my WASM]
```
You need Node.js installed for this to work!

**Comment by caarlos0** [comment]
can you open a PR changing docs? (and maybe adding this run wasm thing?)

thanks!
