### ISSUE TITLE
Goreleaser binary from homebrew does not ouput version info

### ISSUE THREAD

**Issue by saipranav** [goreleaser/goreleaser#1019]
**Describe the bug**

I used to download goreleaser directly from releases page. This time, installed goreleaser using homebrew but the version information was missing

**To Reproduce**

Install goreleaser using homebrew:

```sh
brew install goreleaser

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Downloading https://homebrew.bintray.com/bottles/goreleaser-0.106.0.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/5d/5d6f51436a6e961ff317416da0857f034d1b5829151d74f42f63c7d826602bdf?__gda__=exp=1558052261~hmac=ef6d9a0
######################################################################## 100.0%
==> Pouring goreleaser-0.106.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/goreleaser/0.106.0: 5 files, 20.0MB
```

```sh
goreleaser --version

0.106.0, commit none, built at unknown
```

**Expected behavior**

I then installed by downloading directly from releases page

```sh
goreleaser --version

0.106.0, commit b8f590126537beb8f269f424bb63f8326f469152, built at 2019-04-17T12:44:58Z
```

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin C02W39H9HTD6 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
- GoReleaser Version: 0.106.0

**Additional context**
Hey, thanks for every contributor for this awesome tool and its amazing to see how passionate the maintainers are!

**Comment by caarlos0** [comment]
Hey!

I'll see what I can do, this is not the formula generated by goreleaser itself, which is contained in the goreleaser tap...

thanks for pointing this out though!

cheers

**Comment by caarlos0** [comment]
fixed on https://github.com/Homebrew/homebrew-core/pull/40045
