### ISSUE TITLE
Customization in bintray upload: file filters

### ISSUE THREAD

**Issue by apoorvam** [goreleaser/goreleaser#1029]
Firstly, a great library!

I wanted to upload my packages to Bintray and referred this [documentation](https://goreleaser.com/customization/#Bintray). I want to selectively upload files of particular type only out of all the things generated by goreleaser. Is there an option to customize this?

**Comment by caarlos0** [comment]
have you checked http put docs?

https://goreleaser.com/customization/#HTTP%20Put

you should be able to filter artifacts by id (which is kind of new in goreleaser, so make sure you're on latest).

**Comment by apoorvam** [comment]
Checked it. Are IDs of artifacts same as the filename of artifact? If not, where are they assigned?

**Comment by caarlos0** [comment]
no, several artifacts have an `id` field (check archives for instance), so the id filter will filter for all artifacts with that given id...

**Comment by apoorvam** [comment]
I used `id` with put, but it has no support for .OS and .Arch information. But I would need this info which is part of my target url.

**Comment by caarlos0** [comment]
hmm, can you provide the full `.goreleaser.yaml` of what you're trying to do? just to make sure I understood it correctly...

**Comment by apoorvam** [comment]
[Here](https://github.com/leopardslab/dunner/blob/deb-package/.goreleaser.yml) is my goreleaser.yaml file.

* We currently generate binaries, rpm, deb from goreleaser
* Now we want to push deb packages to bintray and rpm packages to separate bintray repo. 

I gave different ids for each of rpm and deb, so i can use it in http put. However, http put url also needs os type, arch type and version info. All of it is not available in `archive` mode and only available in binary mode.

**Comment by caarlos0** [comment]
hmm, got it, this is indeed lacking, and, unfortunately, not too easy to add. 

I'll try to work on it over the next days, but can't promise anything.

**Comment by caarlos0** [comment]
maybe if you could filter by arch on nfpm this would be doable too, you could create several nfpm configs (one for each arch) with different ids and several http put configs too, but still lacking things :(

**Comment by apoorvam** [comment]
Yes, looks like that's way to do it with goreleaser for now. Otherwise, will try to write a script for this task. 

Thanks!

**Comment by apoorvam** [comment]
Since, travis does not have support `rpmbuild >= 4.13`, how is goreleaser released for rpm builds? I tried this, but latest version available with travis is 4.11.

**Comment by apoorvam** [comment]
I think it is an older version. GoReleaser docs mention >=4.13 is required. I just tried installing goreleaser rpm build with alien:
```
$ alien -i goreleaser_amd64.rpm
error: goreleaser_amd64.rpm: not an rpm package (or package manifest)
Error executing "LANG=C rpm -qp --queryformat %{NAME} 'goreleaser_amd64.rpm'":  at /usr/share/perl5/Alien/Package.pm line 489.
```

**Comment by caarlos0** [comment]
uh, guess no one uses our RPMs then :(

**Comment by apoorvam** [comment]
Did you verify it? Just to double check.

**Comment by caarlos0** [comment]
https://travis-ci.org/goreleaser/goreleaser/builds/538774888#L501

yeah, rpm 4.11 😭 

I'm pretty sure this was working at some point, maybe they downgraded it for some reason

**Comment by apoorvam** [comment]
I am not sure when they will upgrade though: https://travis-ci.community/t/ubuntu-18-04-1-lts-bionic-beaver/1270/8
Need to find an alternate option for rpm build now.

**Comment by caarlos0** [comment]
weird indeed...

btw, the filter thing is working right?

for the rpm thing I opened #1033 

so if only the rpm is a problem we can close this issue.

(sorry for the late response btw)
