### ISSUE TITLE
GoReleaser RPMs are not working

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#1033]
I think it is an older version. GoReleaser docs mention >=4.13 is required. I just tried installing goreleaser rpm build with alien:
```
$ alien -i goreleaser_amd64.rpm
error: goreleaser_amd64.rpm: not an rpm package (or package manifest)
Error executing "LANG=C rpm -qp --queryformat %{NAME} 'goreleaser_amd64.rpm'":  at /usr/share/perl5/Alien/Package.pm line 489.
```

_Originally posted by @apoorvam in https://github.com/goreleaser/goreleaser/issues/1029#issuecomment-496962038_

**Comment by caarlos0** [comment]
I just tried this on fedora and it works:

```sh
$ docker run --rm -it fedora bash
# rpm -ivh https://github.com/goreleaser/goreleaser/releases/download/v0.111.0/goreleaser_amd64.rpm
# goreleaser --version
```

and it works... which distro were you using  @apoorvam?

**Comment by apoorvam** [comment]
@caarlos0  I tried this on ubuntu using `v0.111.0` goreleaser rpm from github releases.

**Comment by caarlos0** [comment]
> @caarlos0 I tried this on ubuntu using `v0.111.0` goreleaser rpm from github releases.

hmm, why not using the deb on ubuntu?

idk what needs to be done in order for it to work with alien...

rpms do work though...

**Comment by apoorvam** [comment]
Yes it worked on fedora. I was trying on ubuntu earlier. 

Did using xenial distro give rpmbuild 4.12? Does it help?

**Comment by caarlos0** [comment]
no, rpmbuild 4.11 :(

**Comment by apoorvam** [comment]
@caarlos0 Can you try the same now with v0.112.0 release on fedora? It dint work for me.

```
$ rpm -ivh https://github.com/goreleaser/goreleaser/releases/download/v0.112.0/goreleaser_amd64.deb 
error: goreleaser_amd64.rpm: not an rpm package (or package manifest):
```

**Comment by caarlos0** [comment]
indeed seems to be broken 🤔 

will investigate

**Comment by caarlos0** [comment]
built it locally, seems to work, I would guess something related to the xenial update... will roll it back and verify

**Comment by caarlos0** [comment]
yeap, that was it.

no idea why though...

**Comment by apoorvam** [comment]
I think there is some other issue. Its working fine if i build locally for me too. When you download the file as `curl -O  https://github.com/goreleaser/goreleaser/releases/download/v0.112.0/goreleaser_amd64.rpm` the file size is only 4kb, which is incorrect. I dont know where its getting corrupted. Its happening with my project too. Do see the same? @caarlos0

**Comment by caarlos0** [comment]
@apoorvam size seems about right here https://github.com/goreleaser/goreleaser/releases/tag/v0.112.0

I think its something related to rpmbuild version, not sure what though.

**Comment by caarlos0** [comment]
need to re-check this after the latest changes on nfpm.

**Comment by caarlos0** [comment]
this seems to be fixed.

closing.
