### ISSUE TITLE
Add support for setting server-side encryption on S3 objects

### ISSUE THREAD

**Issue by rafaelmagu** [goreleaser/goreleaser#1045]
**Is your feature request related to a problem? Please describe.**
We recently turned on KMS-based server-side encryption requirements for all buckets in our organization, and started running into issues with goreleaser getting "Access Denied" errors when trying to upload a release into our private bucket.

**Describe the solution you'd like**
I'd like to see support for specifying `aws:kms` or `AES256` encryption on uploaded objects. (akin to `aws s3 cp --sse aws:kms local_object s3://bucket/remote_key`)

**Describe alternatives you've considered**
The other option is to not let GoReleaser upload to S3, and instead use `aws s3 ...` ourselves (in CI).

**Comment by caarlos0** [comment]
this is resolved on the #1056 right?

**Comment by rafaelmagu** [comment]
@caarlos0 Almost 100% covered, except for AES256 encryption which doesn't appear to be covered on that PR.

**Comment by rafaelmagu** [comment]
Safe to close it, though. (I'm still using that branch on my fork to get AES)

**Comment by caarlos0** [comment]
awesome, I think I didn't added docs for it though... feel like opening a PR for that?

BTW: it is released on latest
