### ISSUE TITLE
Latest release has broken install.goreleaser.com

### ISSUE THREAD

**Issue by LarsOL** [goreleaser/goreleaser#1050]
**Describe the bug**

It seems the latest release has broken some scripts on install.goreleaser.com. The issue seems to be a lack of BINARY variable in the script and stops with exit code 1
From https://github.com/golangci/golangci-lint/issues/575

**To Reproduce**
Tried multiple projects from https://install.goreleaser.com/projects/ some projects successfully install
But these fail: 
gometalinter
github.com/client9/misspell
golangci-lint
kaihendry/lk2

**Environment (please complete the following information):**

- OS: mac, alpine for CI
- OS version:  Darwin Kernel Version 18.6.0
- GoReleaser Version: N/A

**Additional context**
It seems golangci-lint hasn't changed their `.goreleaser.yml` in 5 months

**Comment by ldez** [comment]
The root issue https://github.com/goreleaser/godownloader/issues/118

**Comment by caarlos0** [comment]
sorry about this :(

**Comment by caarlos0** [comment]
it is fixed now... there is a new issue on godownload to improve tests there.

thanks for reporting this!
