### ISSUE TITLE
write manifest for release artifacts

### ISSUE THREAD

**Issue by michaelw** [goreleaser/goreleaser#1051]
**Is your feature request related to a problem? Please describe.**
I want to defer uploading artifacts, but now find myself having to keep track of which files in ./dist/ should be uploaded (e.g., CHANGELOG.md, checksums.txt, *.zip *.tar.*), and which not (build directories).  checksums.txt is almost that, but does not include CHANGELOG.md, etc.

**Describe the solution you'd like**
write a manifest file which includes all artifacts that goreleaser is going to upload

**Describe alternatives you've considered**
Add option `--resume-publish`, which, given only the ./dist/ directory, publishes all files.  This invocation should not attempt to build files (because the source tree might not be available anymore, or dependencies are not installed, etc.).

**Comment by caarlos0** [comment]
that's an interesting idea, I remember we discussed this in the past... its not that simple though, we rely on the git repo info and a bunch of other stuff... so, at least for now, I rather not do this.

thanks for the suggestion anyway, and thanks for using goreleaser! :)
