### ISSUE TITLE
linuxbrew: support arm

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#1052]
Continue #927 adding ARM support.

**Comment by caarlos0** [comment]
Derek add label: pinned

**Comment by alexellis** [comment]
Nice to see Derek in action on goreleaser.

You can also run `/add label: pinned` and `/set milestone: v1.0.0`

We also just added "predefined message" support https://github.com/alexellis/derek/blob/master/USER_GUIDE.md#add-predefined-message

**Comment by caarlos0** [comment]
oh cool :D
