### ISSUE TITLE
Homebrew Versions

### ISSUE THREAD

**Issue by lswith** [goreleaser/goreleaser#1058]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I would like to downgrade a homebrew formula from a tap.
`brew install <tap/tool>@<version>` should work but doesn't.

**Describe the solution you'd like**
https://discourse.brew.sh/t/how-do-i-add-multiple-versions-to-a-formula-on-github/910/10
> Ah, figured it out. For people who stumble on this:
> 
> For each version:
> 
> Create a formula named myFormula@version.rb.
> Inside, ensure that the class name is myFormulaATversion
> For example, myFormula@1.0.0.rb should contain class myFormulaAT100 < Formula.
>
> Then, in the root of your Homebrew repository, create a folder called Aliases. In here, create a symlink with the name of your formula to the current latest version.
> 
> For example, Aliases/myFormula would be a symlink to ../myFormula@1.0.0.rb.

**Describe alternatives you've considered**
There aren't any other than manually checking out the specific homebrew-formula directly.

**Comment by caarlos0** [comment]
this does not work even on homebrew core... the `@1.0.0` seems pretty hacky.

you can checkout the file on the commit you want and install it, eg: https://mobile.twitter.com/caarlos0/status/1132005719555870720

Following the ["yes is forever" rule](https://twitter.com/solomonstre/status/715277134978113536), I rather not do this - or at least not right now.

Thanks for the issue either way.
