### ISSUE TITLE
Allow failed snapcraft release

### ISSUE THREAD

**Issue by jesseduffield** [goreleaser/goreleaser#1066]
**Is your feature request related to a problem? Please describe.**
Because releasing a snap fails if you have one in the review pipeline already, the entire goreleaser release will fail.

**Describe the solution you'd like**
To specify that you are okay with the snap release failing for that reason. I don't mind if my other releases are a version ahead of my snap release.

**Describe alternatives you've considered**
none

**Additional context**
I'm working on lazydocker right now and am awaiting a manual review from the snapcraft peeps

**Comment by caarlos0** [comment]
can you provide the error message that happens on those cases?

what we do is to simply call the snap binary, so, on any error we'll abort the pipeline... only way I can think to handle this is to see what's in the error message and acting accordingly...

**Comment by jesseduffield** [comment]
here you go

```
      • SNAPCRAFT PACKAGES
         • pushing snap              snap=lazydocker_0.5.3_Linux_armv6.snap
         • pushing snap              snap=lazydocker_0.5.3_Linux_arm64.snap
         • pushing snap              snap=lazydocker_0.5.3_Linux_x86.snap
         • pushing snap              snap=lazydocker_0.5.3_Linux_armv7.snap
         • pushing snap              snap=lazydocker_0.5.3_Linux_x86_64.snap
   ⨯ release failed after 46.82s error=Snapcraft Packages: failed to publish artifacts: failed to push dist/lazydocker_0.5.3_Linux_armv6.snap package: Preparing to push 'lazydocker_0.5.3_Linux_armv6.snap'.
After pushing, an attempt will be made to release to 'stable'
Pushing 'lazydocker_0.5.3_Linux_armv6.snap' [============================] 100%

Processing...|                                                                 

Error while processing...
The store was unable to accept this snap.
  - Waiting for previous upload(s) to complete their review process. If you want to prioritize this last one, go to the other upload(s) page in https://dashboard.snapcraft.io/ and click on the 'Reject and remove from review queue' button.

Exited with code 1
```

**Comment by caarlos0** [comment]
@jesseduffield can you check #1070 ?

**Comment by caarlos0** [comment]
maybe @dawidd6 can take a look too?

**Comment by dawidd6** [comment]
@caarlos0 how can we test this, without making an actual release?

**Comment by caarlos0** [comment]
you can clone the repo, change the branch and `go build` (using go mods et al), check [CONTRIBUTING.md](https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md) for more info

**Comment by dawidd6** [comment]
I meant, how can I test the feature. But I see it is merged now, so I guess it was tested already :+1: .

**Comment by caarlos0** [comment]
yeah but if you have some time to do so as well, please do :D
