### ISSUE TITLE
goreleaser without build step

### ISSUE THREAD

**Issue by bbernhard** [goreleaser/goreleaser#1071]
This might be a stupid question, but is it possible to use goreleaser without the build step? 

I've stumbled accross this project, as I have multiple projects for which I want to create a new release on a regular basis. Most of the projects are dockerized - i.e there exists a `Dockerfile` which contains all the necessary dependencies and compiles the go application during the build step. 

As everything is already done within the Dockerfile, I do not need an additional build step. So what I would need is just the "release functionality" of goreleaser. 

Everything I tried to so far ended in an error similar to this one here: https://github.com/goreleaser/goreleaser/issues/694

Is that somehow possible to accomplish?

**Comment by caarlos0** [comment]
Hey

Can't think on any way of doing that, no :(

sorry about that
