### ISSUE TITLE
Add `bottle :unneeded` to the generated homebrew formula

### ISSUE THREAD

**Issue by jakeswenson** [goreleaser/goreleaser#1078]
## Describe the bug

I am using [chezmoi](https://github.com/twpayne/chezmoi) which uses GoReleaser to build it's brew formula. Currently my install is failing with:
```bash
> brew upgrade chezmoi                                                                                                             
==> Upgrading 1 outdated package:
twpayne/taps/chezmoi 1.5.9 -> 1.6.0
==> Upgrading twpayne/taps/chezmoi
Error: The following formula
  chezmoi
cannot be installed as binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install
```

brew thinks that it need to build the formula from source (but that's not the case since GoReleaser is taking care of it)

## To Reproduce

1. have GoReleaser build a binary and package it into a homebrew formula
2. try and install that formula without command line tools installed (or currently on a mac os public beta while brew is not supported since it can't detect the installed command line tools)

3. **FAILS TO INSTALL because brew thinks it's building from source***

## Expected behavior

Since the binary is already built the the formula should just install with no issues.

## Environment

- OS: mac
- OS version: `Darwin machine 19.0.0 Darwin Kernel Version 19.0.0: Thu Jun 27 20:18:24 PDT 2019; root:xnu-6153.0.13.131.3~1/RELEASE_X86_64 x86_64`
- GoReleaser Version: [from chezmoi](https://github.com/twpayne/chezmoi/blob/master/.goreleaser.yaml#L129)

## Additional context
`bottle :unneeded` solves this problem because it signals to homebrew that it is a binary formula

here is an example from hadoop: https://github.com/Homebrew/homebrew-core/blob/master/Formula/hadoop.rb#L7

There may be a better way to fix this, i am by no means a homebrew expert.

**Comment by caarlos0** [comment]
weird that never happened before... new behavior maybe?

anyway thanks for reporting!
