### ISSUE TITLE
Docker build order

### ISSUE THREAD

**Issue by tdmanv** [goreleaser/goreleaser#1097]
**Is your feature request related to a problem? Please describe.**
I build multiple docker containers. One of them is used as the FROM field for others

**Describe the solution you'd like**
If `--parallelism=1`, then build the docker images in the order specified in the yaml. This will let me choose the order of images.

**Describe alternatives you've considered**
I could potentially build the base image in a prehook, but I'd prefer to use the existing docker support.

**Additional context**
This is the project: https://github.com/kanisterio/kanister/blob/master/.goreleaser.yml#L42

**Comment by caarlos0** [comment]
this was fixed on #1100 

closing.
