### ISSUE TITLE
Gitea release support

### ISSUE THREAD

**Issue by dtluna** [goreleaser/goreleaser#1106]
**Is your feature request related to a problem? Please describe.**
I want to upload the build artifacts to my [Gitea](https://gitea.io/) instance, but currently only GitHub and gitlab.com are supported.

**Describe the solution you'd like**
I want to be able to specify [my Gitea instance](https://git.dtluna.net/) as the destination for uploading artifacts in `release` section.

**Comment by mavogel** [comment]
Sounds good. It has an client/sdk: https://gitea.com/gitea/go-sdk . We'll take a look at it quite soon.

**Comment by dtluna** [comment]
@mavogel I've decided to try and implement this myself. PR incoming!

**Comment by caarlos0** [comment]
@dtluna I would suggest to wait a bit until #1084 is merged

**Comment by dtluna** [comment]
@caarlos0 sure

**Comment by mavogel** [comment]
@dtluna as #1084 is merged into master, feel free to branch from there now :) feel free to ask if you need any help. Happy coding :)

**Comment by dtluna** [comment]
@mavogel Thanks, let's see what happens now!
