### ISSUE TITLE
'file name too long' when using '.' as 'extra_files'

### ISSUE THREAD

**Issue by raxod502** [goreleaser/goreleaser#1117]
**Describe the bug**

I have an existing application which builds Docker images for deployment. I want to use goreleaser to push those Docker images to Docker Hub with appropriate versioned tags. Building those images requires the entire project, not just a single binary. I thought I could do this by adding `.` in the `extra_files` directive under `dockers`. Unfortunately, it seems that goreleaser attempts to first copy everything in `extra_files` under `dist` (why not use an actual temporary directory?), and since `dist` is inside the project directory we get a recursive copy:

```
   • DOCKER IMAGES
   ⨯ release failed after 19.09s error=failed to link extra file '.': link dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/Dockerfile dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/Dockerfile: file name too long
```

I thought that adding `dist` to `.dockerignore` might fix the problem, but no dice as it seems the problem stems from goreleaser and not Docker.

**To Reproduce**

```yaml
dockers:
  - binaries: []
    extra_files:
      - .
    image_templates:
      - test
    skip_push: true
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

I should be able to build my Docker images the same way that `docker build .` works.

**Environment (please complete the following information):**

- OS: macOS 10.14.6
- OS version: Darwin hostname 18.7.0 Darwin Kernel Version 18.7.0
- GoReleaser Version: 0.114.1 (36b190490f7b1716c9edb9ce96f243397b97abf3)

**Comment by caarlos0** [comment]
A way to fix this would be to change the `dist` default from `./dist` to a new temp folder... 🤔

not sure what it would break though 🤔

**Comment by caarlos0** [comment]
I think for this the only way would be to check if the extra file is `.` or `./dist` and error early... or leave as is...
