### ISSUE TITLE
Checksum upload to github broken with new archive spec

### ISSUE THREAD

**Issue by issmirnov** [goreleaser/goreleaser#1123]
**Describe the bug**
After following the notice at https://goreleaser.com/deprecations/#archive, uploading releases to Github fails due to an empty checksum file.

**To Reproduce**

1. Clone any repo (I used https://github.com/issmirnov/zap). 
2. Update archive format to follow the new spec.
3. Try to perform a release (see [my travis conf](https://github.com/issmirnov/zap/blob/master/.travis.yml#L51)) 

**Expected behavior**
Releases work as normal.

**What actually happens**

The project checksum file is created, but has empty contents. As a result, the github release fails with error code:

```
creating or updating release repo=issmirnov/zap tag=v1.2.0
         • release updated           url=https://github.com/issmirnov/zap/releases/tag/v1.2.0
         • uploading to release      file=dist/zap_1.2.0_checksums.txt name=zap_1.2.0_checksums.txt
release failed after 55.04s error=GitHub/GitLab Releases: failed to publish artifacts: failed to upload zap_1.2.0_checksums.txt after 10 retries: POST https://uploads.github.com/repos/issmirnov/zap/releases/19514345/assets?name=zap_1.2.0_checksums.txt: 400 Bad Content-Length:  []
```

**Environment (please complete the following information):**

- OS: MacOS Mojave, and Ubuntu 18.04, as well as Travis
- GoReleaser Version: 0.116.0

**Additional context**
- https://travis-ci.org/issmirnov/zap/jobs/576304024
- https://github.com/issmirnov/zap/blob/master/.travis.yml#L51
- https://github.com/issmirnov/zap/blob/master/goreleaser.yml
- https://goreleaser.com/deprecations/#archive
- https://goreleaser.com/checksum/

**Comment by mavogel** [comment]
Hi @issmirnov, 
does this error also happen when you run the releasing locally? AFAICS in your [commit](https://github.com/issmirnov/zap/commit/c4d3b90f5605bcc5ac5616382891bee45e9b31b3), you removed the following section
```
checksum:	archives:
  name_template: '{{ .ProjectName }}_checksums.txt'
```

so it should assume the default `"{{ .ProjectName }}_{{ .Version }}_checksums.txt"` and I cannot reproduce it being empty.

Would you mind running the script with the debug flag as follows
`curl -sL https://git.io/goreleaser | bash -s -- --debug` to get more information.

**Comment by mavogel** [comment]
ping @issmirnov

**Comment by issmirnov** [comment]
Apologies for delay, was behind on email.

Well. This is odd. I ran the full command as provided above, and of _course_ it works. I was all excited to get you guys some logs and dive into this, but it ran flawlessly this time around. I'm guessing it's probably either a stale version on my end, or some other PEBCAK error. I'll update my mainline repo and see if I can generate a release with travis, then close this out.

**Comment by issmirnov** [comment]
Neat! This is great. Looks like it works completely fine. I have no idea what I did wrong last time, but I'm fairly certain it was an error on my part. Thanks for following up on this!

https://travis-ci.org/issmirnov/zap/jobs/585340174

![image](https://user-images.githubusercontent.com/5771615/64929071-af98fe00-d7e6-11e9-804a-7f9d08dc1053.png)
