### ISSUE TITLE
Use GoReleaser programmatically 

### ISSUE THREAD

**Issue by sirikon** [goreleaser/goreleaser#1129]
When a project uses goreleaser, it has two installation options: The pipe-to-bash script that automatically downloads the latest version and runs it, or manual installation with a .deb/.rpm package.

GoReleaser is completely focused on Go development, so, there's an opportunity to improve this.

I'll put [Mage](https://github.com/magefile/mage) as example here: In Mage you have the option to use pre-built binaries, to install and build it with go's toolchain, **or** use the called "Zero Install Option" described here: https://magefile.org/zeroinstall/ .

Using the zero install option, Go Modules will detect mage itself as a dependency (and `go mod tidy` won't remove it), so we can get track of an exact version of mage, like any other dependency. The advantages are:

- You stick with the mage version you **know** works with your project.
- `go get` downloads all the dependencies, including mage, which is your build tool.
- Completely cross-platform workflow.

It eases up both development and CI/CD, because all you need to do to get everything is `go get`, there's no need for extra scripts just for CI/CD to download the dependency and install it.

**An ideal solution:**
Having GoReleaser features available as simple importable packages in Go would be really cool, because we could use it within Mage without running shell scripts, for example.

**A minimal solution:**
Doing what Mage actually does: The [project's main entry point](https://github.com/magefile/mage/blob/master/main.go) just calls an [exported Main function from another internal package](https://github.com/magefile/mage/blob/master/mage/main.go#L90), this way anyone can call the exported Main() function, making "Zero Install Option" possible.

Thank you so much in advance for the cool project, your efforts, and your time.

**Comment by caarlos0** [comment]
Following the ["yes is forever" rule](https://twitter.com/solomonstre/status/715277134978113536), I rather not do this - or at least not right now.

Thanks for the suggestion either way.

**Comment by sirikon** [comment]
@caarlos0 No problem! Thanks for considering it :)
