### ISSUE TITLE
Additional notes in Release (including builtin ChangeLog generation)

### ISSUE THREAD

**Issue by prologic** [goreleaser/goreleaser#1131]
I apologize in advance as this has some up in various ways before (_see related issues_). However what I'd like is to keep the existing change log generation that is on by default **but** also have the ability to add additional notes specific that _that_ release.

My understanding from reading the [docs](https://goreleaser.com/customization/#Release) is that specifying `--release-notes` will entirely skip this process (_will still generate the changelog; but will not upload it to the Github Release page_).

I'd like both:

- Generated Changelog
- Additional Notes

Does this sound reasonable? :)

**Comment by caarlos0** [comment]
Maybe a `--release-notes-footer` or something like that?

**Comment by prologic** [comment]
If we go down that idea... Why don't we add a `--release-notes-header` as well? I personally (_albeit hand crafted manually_) tend to write my important notes for a release above the change log but otherwise yeah I can't think of another way to do this!

**Comment by caarlos0** [comment]
keep

**Comment by jnovikov** [comment]
Can take it

**Comment by jnovikov** [comment]
Created PR:
https://github.com/goreleaser/goreleaser/pull/1212

**Comment by caarlos0** [comment]
should be fixed by #1212
