### ISSUE TITLE
Make pull requests to homebrew

### ISSUE THREAD

**Issue by dawidd6** [goreleaser/goreleaser#1139]
**Is your feature request related to a problem? Please describe.**
I think it would be nice to make automated pull requests to `homebrew-core` on new releases. It could be an additional option alongside own tap.

**Describe the solution you'd like**
1. Fork `homebrew-core` if needed.
2. Check if Formula exists in `homebrew-core`. If not then create a PR adding new Formula and proceed to last step.
3. Check if a PR updating to latest version already exists, is created by proper user and is not merged, if so then change title and (force) push commit bumping version and proceed to last step.
4. Make a PR updating to latest version, like `brew bump-formula-pr` does.
5. Subscribe to PR and exit.

**Describe alternatives you've considered**
Own tap.

**Additional context**
...

**Comment by caarlos0** [comment]
Following the ["yes is forever" rule](https://twitter.com/solomonstre/status/715277134978113536), I rather not do this - or at least not right now.

Thanks for the suggestion either way. Maybe in the future :)

**Comment by dawidd6** [comment]
Sure thing, thanks for taking a look at the proposal anyway :)
