### ISSUE TITLE
'go install ./...' fails building golang.org/x/xerrors - 

### ISSUE THREAD

**Issue by dmitris** [goreleaser/goreleaser#1143]
Building `gorelease` from source fails wih go1.13:
```
$ go install -v ./...
golang.org/x/xerrors
# golang.org/x/xerrors
/home/dmitris/go/pkg/mod/golang.org/x/xerrors@v0.0.0-20190410155217-1f06c39b4373/adaptor_go1_13.go:16:14: undefined: errors.Frame
/home/dmitris/go/pkg/mod/golang.org/x/xerrors@v0.0.0-20190410155217-1f06c39b4373/format_go1_13.go:12:18: undefined: errors.Formatter
```

**Environment (please complete the following information):**

- OS: linux, mac
- OS version: Linux kernel 3.10.0-1062, Mac 10.14.6

**Additional context**
Upgrading `gocloud.dev` from `v0.15.0` to `v0.17.0` fixes the build failure - will raise a PR.

**Comment by caarlos0** [comment]
should be fixed on https://github.com/goreleaser/goreleaser/pull/1135
