### ISSUE TITLE
Can't build with go 1.13 due to old gitea version

### ISSUE THREAD

**Issue by natefinch** [goreleaser/goreleaser#1145]
**Describe the bug**

For some reason, go 1.13 complains about an invalid gitea version, but go 1.12 doesn't.  I think if you upgrade the version of gitea, it'll work.  This is true for master and at least the last couple releases.

**To Reproduce**

`go get` with 1.13 or 1.12.

**Comment by caarlos0** [comment]
this should be working on latest 🤔

**Comment by tliron** [comment]
The issue is closed, but I am still getting the error:
```
> go version
go version go1.13.1 linux/amd64
> go get -u github.com/goreleaser/goreleaser
go get: github.com/goreleaser/goreleaser@v0.118.2 requires
	code.gitea.io/gitea@v1.10.0-dev.0.20190711052757-a0820e09fbf7 requires
	github.com/go-macaron/cors@v0.0.0-20190309005821-6fd6a9bfe14e9: invalid pseudo-version: revision is longer than canonical (6fd6a9bfe14e)
```
