### ISSUE TITLE
Can't combine brew and multiple goarm versions

### ISSUE THREAD

**Issue by SimonBarendse** [goreleaser/goreleaser#1148]
**Describe the bug**

When building multiple `goarm` versions and releasing on brew, an error is returned:
```
homebrew tap formula: failed to publish artifacts: one tap can handle only 1 linux and 1 macos archive
```

**To Reproduce**
We encounter this issue when releasing with [this `.goreleaser.yml`](https://github.com/secrethub/secrethub-cli/blob/v0.28.0/.goreleaser.yml). I expect anything using brew and having multiple goarm versions returns this error.

**Expected behavior**
I'd expect either one of these things:
1. Nothing is added to the brew formula for ARM architectures (as was the case in goreleaser `v0.117` and earlier).
2. An entry is added to the brew formula for each of the goarm versions and the formula determines which to use.

**Environment**
GoReleaser Version: `v0.118.0` (works as expected in `v0.117.2`)

**Additional context**
The error first occurs after #1140

The error is returned [here](https://github.com/goreleaser/goreleaser/blob/v0.118.0/internal/pipe/brew/brew.go#L278)

**Comment by SimonBarendse** [comment]
I can't add it anymore, but this should be tagged [![](https://i.imgur.com/JflcH01.png)](../labels/bug)

**Comment by mavogel** [comment]
Thanks for pointing out @SimonBarendse. We will keep track of the issue in #1146
