### ISSUE TITLE
Native GitHub Action

### ISSUE THREAD

**Issue by crazy-max** [goreleaser/goreleaser#1149]
Hi @caarlos0,

Looking at [this commit](https://github.com/goreleaser/goreleaser/commit/2e3a007161c30bcccc185fa0b7fb27d12a7eabbd#diff-23142b842285416ea0f34aa9497f0e19), I have created a native [GitHub Action for GoReleaser](https://github.com/crazy-max/ghaction-goreleaser) using the [typescript-action](https://github.com/actions/typescript-action) template to fix this issue.

This [works](https://github.com/crazy-max/ghaction-goreleaser/blob/master/.github/workflows/test.yaml) and builds on all [virtual environments](https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments-and-hardware-resources) supported by GitHub Actions. A "real world" example is [available](https://github.com/crazy-max/travis-wait-enhanced/blob/master/.github/workflows/build.yml) if you want to take a look.

If you are willing to add a note in your documentation, feel free to do it or I can open a PR.

Keep it up on this project guys!

**Comment by gavincabbage** [comment]
@crazy-max Somewhat off topic question: Have you had any success using goreleaser's signing feature under GitHub Actions? Struggling to get it working myself and haven't been able to find a working example anywhere.

**Comment by crazy-max** [comment]
@gavincabbage Never tried. Do you have a link to your failed workflow?

**Comment by caarlos0** [comment]
I think that the current action (which is just the docker image) already works... doesn't it?

**Comment by gavincabbage** [comment]
@crazy-max I opened #1156 with relevant links so as to avoid polluting this issue further - if you have the time to take a look I would appreciate it. Surely doing something silly but have spun my wheels getting signing to work for a few days now.

**Comment by crazy-max** [comment]
@caarlos0 Like you said, GitHub Actions override the `WORKDIR` instruction if you use Docker actions so only projects based on modules will work. That's why I have created this typescript action to be linked as close as possible to the virtual environment. We also benefit from the [software pre-installed](https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions) on those environments.

@gavincabbage Ok let's talk about this at #1156

**Comment by caarlos0** [comment]
maybe move it to goreleaser org then? would you be open to that? I can add you to the org and you can maintain it still... just so its official :)

**Comment by crazy-max** [comment]
@caarlos0 Yeah sure!

**Comment by caarlos0** [comment]
done, feel free to move the repo and open a PR changing the docs 🚀 

thanks for the contribution 🙏

**Comment by crazy-max** [comment]
@caarlos0 You're welcome 🙂 I will check with GitHub staff to change [marketplace item ref](https://github.com/marketplace/actions/goreleaser-action) before moving as I don't know if it's feasable (redirect or not). Maybe fork to this org. Keep you in touch!

**Comment by caarlos0** [comment]
awesome, thanks!

**Comment by crazy-max** [comment]
@caarlos0 Ok I can delist the item on the Marketplace, then transfer the repo. This will allow current users who use this action to take advantage of [repo redirection](https://help.github.com/en/articles/transferring-a-repository#whats-transferred-with-a-repository). There should therefore be no issue at all 🚀

Afer that, I think I'll use [godownloader README](https://github.com/goreleaser/godownloader/blob/master/README.md) to get the same layout and I'll also create a PR to update the current [documentation](https://goreleaser.com/actions/). Is that all right with you?

**Comment by caarlos0** [comment]
> Afer that, I think I'll use [godownloader README](https://github.com/goreleaser/godownloader/blob/master/README.md) to get the same layout and I'll also create a PR to update the current [documentation](https://goreleaser.com/actions/). Is that all right?

sounds great, yeah! :D 

thanks 🚀

**Comment by crazy-max** [comment]
@caarlos0 Repo has been [transfered](https://github.com/goreleaser/ghaction-goreleaser). Can you create a "GitHub Action" team for example and give me admin rights on it to edit settings? Thanks!

**Comment by caarlos0** [comment]
@crazy-max done! :D

**Comment by crazy-max** [comment]
@caarlos0 Ok everything looks fine :)

* https://github.com/marketplace/actions/goreleaser-action
* https://github.com/goreleaser/goreleaser-action
* [Tested](https://github.com/crazy-max/travis-wait-enhanced/runs/240065650#step:6:8) on side project

I close this issue ad will create a PR to update documentation.

**Comment by caarlos0** [comment]
Awesome!

Is it possible to name `https://github.com/marketplace/actions/goreleaser-action` to only `https://github.com/marketplace/actions/goreleaser`?

And `https://github.com/goreleaser/goreleaser-action` to only `https://github.com/goreleaser/action`? WDYT?

**Comment by crazy-max** [comment]
@caarlos0 No that's not possible unfortunately. Strange as it may be, an article name on the marketplace should not duplicate a user or organization name on GitHub.

**Comment by caarlos0** [comment]
> No that's not possible unfortunately. Strange as it may be, an article name on the marketplace should not duplicate a user or organization name on GitHub.

oh, ok :) 

> Yes we can rename it that way but as I saw that there was `godownloader`, I wanted to differentiate this repo.

yeah, makes sense. Let's leave as is then! :) 

---

awesome, thanks for the work @crazy-max 🚀

**Comment by crazy-max** [comment]
> awesome, thanks for the work @crazy-max 🚀 

@caarlos0 You're welcome and thanks A LOT for GoReleaser, it's a great piece of software!
