### ISSUE TITLE
Help requested configuring artifact signing under GitHub Actions

### ISSUE THREAD

**Issue by gavincabbage** [goreleaser/goreleaser#1156]
Creating a separate issue to continue discussion with @crazy-max from #1149.

I've configured goreleaser under GitHub actions on my project [here](https://github.com/gavincabbage/chiv). I was able to run successful test releases without signing enabled (which I deleted, because they were tests) but am unable to successfully release with signing enabled.

My release workflow is [here](https://github.com/gavincabbage/chiv/blob/master/.github/workflows/release.yml) and my goreleaser configuration is [here](https://github.com/gavincabbage/chiv/blob/master/.goreleaser.yml). 

When I push a tag the release workflow fails with the following error during the signing step:

```
release failed after 78.74s error=sign: gpg failed with ""
```

An example of a failure, with goreleaser's debugging enabled, can be found [here](https://github.com/gavincabbage/chiv/runs/234123006).

The key is configured as a GitHub secret, and imports correctly in the step prior to running goreleaser. The configuration also runs successfully on a system with the same key imported when I run `goreleaser release --skip-publish`. The key does not have a passphrase (I started with one but decided tackle the simpler case first).

I've tried more permutations of configuration than I can possibly list over the past few days, but will give any suggestion a shot. Any ideas on getting a useful error out of `gpg` would also be appreciated.

**Comment by gavincabbage** [comment]
@crazy-max I was able to add signing functionality by forking your goreleaser action. I'll clean that up and get a PR opened over there.

**Comment by crazy-max** [comment]
@gavincabbage Nice!
