### ISSUE TITLE
Automatic tagging

### ISSUE THREAD

**Issue by jorinvo** [goreleaser/goreleaser#117]
At least two people I talked to mentioned that they wish `goreleaser` would automatically create a tag for them.

I guess there are quiet a few people out there not running GoReleaser on CI.
When running it manually, it would be definitely nice if running `goreleaser` would take a version number or something and create the tag for you.
I wish we can support this use case too.

Maybe we can add a command-line argument like `-tag string`.
When you set it the specified tag will be created for you.

For the "create a new tag" scenario we would also not run into the problem we had with #72 
because we don't need to switch branches since the current state is exactly what will end up in the tagged version.
Creation of a new tag should be only allowed with a clean Git state though.

In addition these checks the [np](https://github.com/sindresorhus/np) tool (for node.js) does could also ne useful for us:
> - Ensures you are publishing from the `master` branch
> - Ensures the working directory is clean and that there are no unpulled changes
> - Reinstalls dependencies to ensure your project works with the latest dependency tree
> - Runs the tests

**Comment by caarlos0** [comment]
In those cases, isn't it easy for people who use it this way to create a function or something like this:

```sh
goreleaser() {
  git tag "$1"
  git push origin master
  goreleaser
}
```

About the validations:

- Ensures you are publishing from the master branch

Already implemented

- Ensures the working directory is clean and that there are no unpulled changes

Already implemented

- Reinstalls dependencies to ensure your project works with the latest dependency tree

in the CI, that would not make much sense...

- Runs the tests

in the CI, that would not make much sense...


Maybe we should split our main in 2: one for running locally and another for CI?

Either way, I believe that making goreleaser do all those things is not very UNIX-like, since the idea of Unix is to have small that do a single thing...

**Comment by jorinvo** [comment]
I knew about the "clean working directory" check but haven't seen that we also ensure being on master. Nice :)

Reinstalling dependencies and running tests are IMHO things we can not do reliably since there is no standard way to do those in Go.
I guess, since CI already covers those it's not a big issue though.

You are right that tag creation is something you can do in just a few lines (2 lines) but I guess for many people the reason they get excited about GoReleaser is that they can throw away their custom shell scripts and instead just run `goreleaser`.
If implementing this simple feature would allow more people to get rid of their custom releasing scripts, I think, it might be worth including it.

I am all for simple tools focusing on one task only. 
With GoReleaser I see this task being the releasing of Go projects.
In my opinion the creation of a tag still fits into the scope of the `goreleaser` tool.
For everyone running the `goreleaser` command manually this is a step they have to do for every release.

**Comment by sagikazarmark** [comment]
I am not really sure either this adds that much benefits. Clearly adds some extra responsibility over "building and deploying" (this is what goreleaser actually does), which IMO makes the scope less obvious.

As @caarlos0 point, this can simply be solved by a user script. However, I don't think it's a good practice to give the control from the user to goreleaser: manually tagging a release is a clear indication of the user intent, doing some automagic is never a good idea, and as such, should not be encouraged by goreleaser. My 2 cents, not saying you are doing it wrong.

**Comment by caarlos0** [comment]
Yeah, I'll think about this for a while.

**Comment by jorinvo** [comment]
Sure, I also haven't thought this through all the way yet.
I just wanted to share the feedback I got from others and hope we find a good solution for it.

Maybe the right solution could also be to be more clear about this in the documentation and show new users a simple way to accomplish this with a line of shell script.

**Comment by caarlos0** [comment]
I gave this a lot of thought, and I still think that it's better to not add this feature.

Of course, it would be easy and maybe useful for some people, but then it would also kind of make sense to add auto-tagging, dependency check, build, testing and whole ton of other stuff that are not part of the main use case of GoReleaser as I idealized it: 

- I tag (either via command line or github itself)
- the CI runs the build (guaranteeing all that should be guaranteed)
- the CI calls GoReleaser, which releases to whichever providers are defined in the config

That being said, I'll close this issue for now. If you have a different opinion on this, let me know.

Cheers

**Comment by jorinvo** [comment]
@caarlos0, sure :) As I mentioned I only wanted to discuss this with you since the issue came up a couple of times.
I guess the docs are already clear enough and include an example on how to create a tag. New users should be able to figure this out.

**Comment by caarlos0** [comment]
@jorinvo sure, in case docs aren't enough, we can fix that later =D
