### ISSUE TITLE
Add support for Docker pre push hook

### ISSUE THREAD

**Issue by danielpacak** [goreleaser/goreleaser#1189]
GoReleaser has great support for building and publishing Docker images. I'm using it for example in this project https://github.com/aquasecurity/harbor-scanner-trivy . There is one missing hook though where I could scan my Docker image for vulnerabilities before I push it to a Docker registry, e.g. DockerHub. The only solution I have now is to do post publish scan and then remove or rebuild a vulnerable image manually. Preferably I'd like GoReleaser to not push to a registry when the pre push hook fails.

If we introduced a pre push hook, I could execute a scanning script. If its exit code is not equal to 0 we do not execute the Docker push command.

<img width="1099" alt="goreleaser_docker_pre_push_hook" src="https://user-images.githubusercontent.com/1322923/66568194-3f716400-eb69-11e9-9497-71ac6fad71d2.png">

Alternatively the scanning for vulnerabilities (or any other pre push checks) can be done manually before actually triggering a release process. Anyway I'm wondering wdyt about supporting such feature?

**Comment by caarlos0** [comment]
sounds good... what would be the idea, call the hook for each image built passing it as an arg?

**Comment by danielpacak** [comment]
Yup, we need to pass somehow a valid Docker image reference to the hook. In my example it would look like `aquasec/harbor-scanner-trivy:0.1.0-alpha.1`.

I'm just wondering how do we handle it if there're multiple image templates configured in a single docker build. Doesn't make sense to scan them all as they refer to the same image ID / digest.

**Comment by caarlos0** [comment]
yeah, but maybe other kinds of hooks would want to? 🤔

**Comment by danielpacak** [comment]
Good point. I haven't seen the code, but I assume that you pass all image templates to the docker push command. If that's the case the pre push hooks should accept them as well. In case of vulns scanning, the script might decide to skip all but the first arg.

**Comment by caarlos0** [comment]
yeah, I think that makes sense.
