### ISSUE TITLE
Pass through custom arguments

### ISSUE THREAD

**Issue by clementgng** [goreleaser/goreleaser#1194]
**Is your feature request related to a problem? Please describe.**
I want to be able to pass command line arguments for goreleaser into .goreleaser.yml

Say I have a goreleaser.yml file with the following content:
sometextgoeshere:{{.testarg}}

**Describe the solution you'd like**
goreleaser --rm-dist --testarg testval
and then from here we . can pass testval into the YML

**Describe alternatives you've considered**
Tried to use shell script to replace a string with a value, however, this won't work as .goreleaser.yml has been changed and have to re-tag. Therefore, putting git in a dirty state and have to re-tag.. Which makes it impossible to use shell script to do this.

**Additional context**
I tried finding if anybody encountered this issue or wanted to do this on the internet and could . not find anything

**Comment by caarlos0** [comment]
I'm inclined to not do this, as the config is already pretty complex... I'm afraid it will get even more complex...

you can already do things like that with `envsubst` (from pkg `gettext`) and environment variables...

All that being said, following the ["yes is forever" rule](https://twitter.com/solomonstre/status/715277134978113536), I rather not do this - or at least not right now.

Thanks for the suggestion either way.
