### ISSUE TITLE
Provide script for easy install

### ISSUE THREAD

**Issue by karuppiah7890** [goreleaser/goreleaser#1197]
**Is your feature request related to a problem? Please describe.**
It's not exactly straight forward to install goreleaser and use it in GitLab CI. I wouldn't opt for this - https://goreleaser.com/ci/#gitlab-ci

**Describe the solution you'd like**
A solution that allows me to use goreleaser in my GitLab Ci with a simple config such as this:

```
release-job:
  image: some-image
  stage: publish
  only:
    - tags
  script:
    - goreleaser release
```

But currently the image `goreleaser/goreleaser` cannot be used in the image field as it has an entrypoint, so gitlab errors with the error 

```
goreleaser: error: unexpected sh, try --help
```

Currently I use the below script to install goreleaser and then run it using the gitlab ci config I mentioned. 

```
#!/bin/sh

set -ex

package_name="goreleaser/goreleaser"

get_latest_release() {
  curl "https://api.github.com/repos/$package_name/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
}

latest_version=$(get_latest_release)
echo $latest_version

echo "Installing goreleaser${latest_version}"
wget "https://github.com/goreleaser/goreleaser/releases/download/$latest_version/goreleaser_Linux_arm64.tar.gz"

tar -xvzf goreleaser_Linux_arm64.tar.gz
mv goreleaser /usr/local/bin/

echo "goreleaser has been installed:"
goreleaser version
```

Some pros of providing script:
1. Install goreleaser in any docker image easily

Alternative solution ideas:
I would expect a script to install goreleaser or provide an image that doesn't have an entrypoint. This will make the user experience better

**Comment by karuppiah7890** [comment]
I just found this - https://install.goreleaser.com/ which has this listed

```
curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
```

This would have been easy to be find if it was mentioned in the docs section over here - https://goreleaser.com/install/ . I would be willing to raise a PR for the same! Including changing the GitLab CI config too, as current config looks a bit complex and unnecessary, where just an install and run would work without the need of docker

**Comment by caarlos0** [comment]
hey, feel free to, yeah... I thought it was there already 🤣 

regarding gitlab ci, check also the travis config, there is another script which downloads and run goreleaser in a single step...

thanks for digging this up! 🚀

**Comment by karuppiah7890** [comment]
Raised PR on how to use shell script for installation

**Comment by caarlos0** [comment]
Thanks!
