### ISSUE TITLE
How to do if I got multi file main.go and utils.go

### ISSUE THREAD

**Issue by codeskyblue** [goreleaser/goreleaser#121]
```
--.
  |- main.go
  `- utils.go
```

the goreleaser will only build `main.go` which will cause build error.

How can I do with goreleaser to do build `go build .`

How to write the right `goreleaser.yml` file?

**Comment by caarlos0** [comment]
Check the [build customization](https://github.com/goreleaser/goreleaser#build-customization) section in readme...

**Comment by caarlos0** [comment]
I'm not sure I understand what the question is... what is the problem regarding have a main and a utils go files...

**Comment by caarlos0** [comment]
ping @codeskyblue

**Comment by codeskyblue** [comment]
already updated the description

**Comment by caarlos0** [comment]
```yml
build:
  main: .
```

I guess this should work...

Can you try it?

**Comment by codeskyblue** [comment]
I will try today, should this be default setting

**Comment by codeskyblue** [comment]
it works

**Comment by caarlos0** [comment]
The default is `main.go`, as stated in the readme. Maybe we can change that though...
