### ISSUE TITLE
goreleaser fails because of alphabetical tag sort

### ISSUE THREAD

**Issue by jpninanjohn** [goreleaser/goreleaser#1211]
**Describe the bug**

If there are old tags that start with the letter 'y' or 'z', goreleaser will fail with this error. 
```
release failed after 0.10s error=git tag y-tag was not made against commit <latest-commit>
```
goreleaser enforces semver, so normally all newer tags will start with the letter 'v' or with a number. Thus it will always be alphabetically sorted below those tags. 

Further more if we have tags like v0.0.1 and then 0.0.2(without the 'v' in the tag), alphabetically v0.0.1 will be first. Both are valid semvers

**To Reproduce**

Create a tag starting with letter 'y' or 'z'. In latter commits, create tags with semver. Run `goreleaser release`.

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin Ninan-2.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
- GoReleaser Version: 0.120.1

Additional Notes:

This is becaue of the addition of `-c versionsort.suffix=- tag -l --sort=-v:refname` in the process of finding latest tag.

**Comment by caarlos0** [comment]
revert: https://github.com/goreleaser/goreleaser/commit/449ed95bbe73fb88159e061352fcc786987d7d7d

already pushed another tag, should be "fixed" in a few.

**Comment by caarlos0** [comment]
thanks for reporting 👍

**Comment by andriisoldatenko** [comment]
Is “v1.2.3” a semantic version?
No, “v1.2.3” is not a semantic version. However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number. Abbreviating “version” as “v” is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case “v1.2.3” is a tag name and the semantic version is “1.2.3”.
🤔

**Comment by jpninanjohn** [comment]
Not sure if `v` is required for a valid semver or not. But goreleaser considers both as valid.

**Comment by caarlos0** [comment]
FWIW: goreleaser itself tags with the `v` prefix

**Comment by andriisoldatenko** [comment]
Okey, what can be solution?

I would rather we standardize on no “v” than handle edge cases. In other words if we handle v1.1.1 then maybe we have to handle v.1.1.1 or version-1.1.1 or other non-semver things. Thoughts?

right now goreleaser doesn't work with valid sem versions...

**Comment by caarlos0** [comment]
the original issue was related to multiple tags on the same commit, right?

maybe we can try to sort the tags after we have the list?

afaik git tags does not have a "standard" order, so this is a problem long coming...

a few months ago I tried to implement it with go-git, and hit against the tag ordering wall as well...

**Comment by andriisoldatenko** [comment]
```
git -c versionsort.suffix=- tag -l --sort=v:refname --points-at | head
0.0.2
v0.0.1
test_gorel git:(master)
```

**Comment by andriisoldatenko** [comment]
```
git -c versionsort.suffix=- tag -l --sort=v:refname --points-at | head
0.10.1-rc.6
```
seems wroks, my change + few modifications.

**Comment by andriisoldatenko** [comment]
but such case won't work (via `git -c versionsort.suffix=- tag -l --sort=v:refname --points-at`):
```
0.0.2
v0.0.1
v0.0.3
```

**Comment by andriisoldatenko** [comment]
@caarlos0 i think we need to continue your idea with go-git + rewrite something like it https://github.com/FichteFoll/pysemver in go?!

**Comment by caarlos0** [comment]
probably, yes.. something like it.

one idea would be to get the whole tag list and compare using semver, but it would be tricky to handle things like:

- v1.0.0
- v1.1.0-beta.1
- v1.0.1
- v1.1.0-beta.2
- v1.0.2
- v1.1.0

I'm not sure how to handle that, not sure how goreleaser handles it today (multiple versions evolving together, in this case, probably `v1.0.x` would be on `master` and `v1.1.x` would be on branch `v1.1` or something)... anyway, just something to have in mind

**Comment by andriisoldatenko** [comment]
@caarlos0 what do you think if we do like this:
get all tags using git tag + apply logic with sorting using https://github.com/blang/semver/blob/1a9109f8c4a1d669a78442f567dfe8eedf982793/semver_test.go#L33-L40?

**Comment by caarlos0** [comment]
yeah that's more or less the idea, we already have a semver lib as a dep, also supports comparing:

https://github.com/Masterminds/semver/blob/master/collection_test.go#L9

**Comment by andriisoldatenko** [comment]
if you are OK i'll prepare new PR.

**Comment by caarlos0** [comment]
FWIW, using go-git, something like this seems to work:

```go
package main

import (
	"log"
	"sort"

	"github.com/Masterminds/semver/v3"
	"gopkg.in/src-d/go-git.v4"
	"gopkg.in/src-d/go-git.v4/plumbing"
)

func main() {
	r, err := git.PlainOpen(".")
	if err != nil {
		log.Fatalln(err)
	}
	tagrefs, err := r.Tags()
	if err != nil {
		log.Fatalln(err)
	}
	var tags []*semver.Version
	if err := tagrefs.ForEach(func(t *plumbing.Reference) error {
		sv, err := semver.NewVersion(t.Name().Short())
		tags = append(tags, sv)
		return err
	}); err != nil {
		log.Fatalln(err)
	}
	sort.Sort(semver.Collection(tags))
	log.Println(tags)
}
```

**Comment by jpninanjohn** [comment]
Why not a simple sort by date for tags?

`git tag --sort=-creatordate`

I am not sure of any scenario where a later semver tag would have an older date than a previous semver tag. This is of course an assumption.

**Comment by caarlos0** [comment]
That'll get the date of the commit I think, so if 2 tags are made against the same commit, both will have the same date...

**Comment by jpninanjohn** [comment]
If there are multiple tags for a single commit, what is the expected behavior? I tried the same tags that was in issue #1163. I get in this order when I tag the same commit with these tags

```
0.10.1-rc.5
0.10.1-rc.4
0.10.1-rc.3
```

Think after sorting by date it sorts alphabetically(not sure).

**Comment by andriisoldatenko** [comment]
@jpninanjohn try something like this:
```
0.10.1
0.10.1-rc.5
0.10.1-rc.4
0.10.1-rc.3
0.10.2
0.10.2-rc.1
0.10.2-rc.2
```

**Comment by andriisoldatenko** [comment]
`git tag --sort=-creatordate` returns: 
```
0.10.1-rc.6
0.10.1
0.10.1-rc.5
0.10.1-rc.4
0.10.1-rc.3
```

**Comment by jpninanjohn** [comment]
Is this conversation continued somewhere else? Any status on the fix?

**Comment by caarlos0** [comment]
no. not yet.

I would say to do this with go-git so we get rid of the git dependency as well

**Comment by dirien** [comment]
I run today in this point. I get all the time this message:

> git tag v0.1.14-alpha.1718287534+734820a2 was not made against commit
