### ISSUE TITLE
Add list of contributors / external contributors since the last release to the release notes

### ISSUE THREAD

**Issue by mirogta** [goreleaser/goreleaser#1219]
**Is your feature request related to a problem? Please describe.**
I'd like to give praise to external contributors in release notes.

**Describe the solution you'd like**
Generated release notes would have a list of contributors.
Custom release notes would have an option to append the list of external contributors to the end (with some default formatting).

**Describe alternatives you've considered**
I've looked at https://github.com/buchanae/github-release-note
But I'd like this feature built-in in goreleaser in order to prevent additional dependencies and also make it available to everyone who are already using goreleaser.

**Additional context**
* https://github.com/weaveworks/eksctl/issues/1451

**Comment by caarlos0** [comment]
you can add the list of contributors to a custom release notes files and use it via the flag when releasing...

**Comment by caarlos0** [comment]
maybe we could add it to https://github.com/goreleaser/chglog though

cc/ @djgilcrease , thoughts?

**Comment by mirogta** [comment]
> you can add the list of contributors to a custom release notes files and use it via the flag when releasing...

Cool - how about just external contributors? I've updated this in the issue title to make it more specific.

**Comment by djgilcrease** [comment]
That would make sense as a feature in chglog

**Comment by mirogta** [comment]
Wasn't aware of `chglog` - can it return only data since the last release?

Or would `chglog` provide the functionality to get the list of external contributors and `goreleaser` would use it to filter it out with only those since the last release?

**Comment by mirogta** [comment]
Sounds good :) goreleaser then could filter out the list with new contributors and exclude "internal" contributors, i.e. those in a specified github group for the specific project.

**Comment by caarlos0** [comment]
opened an issue to work in the integration: https://github.com/goreleaser/goreleaser/issues/1245
