### ISSUE TITLE
Support custom endpoint for blob providers

### ISSUE THREAD

**Issue by jonfriesen** [goreleaser/goreleaser#1223]
**Is your feature request related to a problem? Please describe.**
Blobs don't support custom endpoints (the deprecated s3 support does) for s3 compliant providers like DigitalOcean and Minio

**Describe the solution you'd like**
Add an endpoint property to the config.Blob to override the providers default endpoint

**Describe alternatives you've considered**
Using deprecated s3 support, adding another step in ci/cd to copy the created packages over

**Additional context**
I'm using an CI/CD environment where I would like to keep the endpoint in an environment variable or the goreleaser configuration if possible.

**Comment by caarlos0** [comment]
I was looking into the code, it seems to me that passing the URL in the `bucket` field will solve it. Just need to remove the `s3://` prefix.

Can you verify @jonfriesen ?

**Comment by caarlos0** [comment]
@jonfriesen I think #1253 will fix this :)

**Comment by jonfriesen** [comment]
Looks like it will! Thanks @caarlos0  :raised_hands:
