### ISSUE TITLE
GitLab releases changelog don't have links to commit sha

### ISSUE THREAD

**Issue by karuppiah7890** [goreleaser/goreleaser#1225]
**Describe the bug**

The changelog in GitLab release doesn't have links to the commit sha similar to how it's present in GitHub release changelog

**To Reproduce**

config file - https://gitlab.com/karuppiah7890/dummy-golang-project/blob/0.2.0/.goreleaser.yml
Demo Releases page: https://gitlab.com/karuppiah7890/dummy-golang-project/-/releases

Screenshot:
<img width="1205" alt="Screen Shot 2019-11-01 at 9 21 32 AM" src="https://user-images.githubusercontent.com/12808424/68001181-11270600-fc89-11e9-93a5-ed7854e1bf5b.png">

**Expected behavior**

I expect the release changelog to have links to commit sha like this : 

<img width="1183" alt="Screen Shot 2019-11-01 at 9 21 44 AM" src="https://user-images.githubusercontent.com/12808424/68001193-17b57d80-fc89-11e9-93b9-8f2d24eb7799.png">

**Environment (please complete the following information):**

- OS: linux
- OS version: Linux 92899c273413 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux
- GoReleaser Version: 
version: 0.120.4
commit: 576156b03c9429fc66ded230ae34a8c2ac2c28ea
built at: 2019-10-30T23:54:55Z
built by: goreleaser
- GitLab version: public GitLab

**Comment by caarlos0** [comment]
github also does not have, the changelog is the same.

github although linkifies commit hashes, and gitlab seems like it doesnt...

**Comment by karuppiah7890** [comment]
Ah. Didn't realize that. True. Even in my issue details, GitHub converted goreleaser commit sha to a link. Hmm. I'll see if it's possible to explicitly do this, or else close the issue 🙈😅

**Comment by karuppiah7890** [comment]
Looks like GitLab too has the feature to detect commit shas of the project and show them as links

<img width="1282" alt="Screen Shot 2019-11-08 at 1 21 05 PM" src="https://user-images.githubusercontent.com/12808424/68459178-a77b9e80-022a-11ea-9a04-8bde8b1f2c2e.png">

Should I just close the issue? Or do you think it's worth it to explicitly put link like (public gitlab) `https://gitlab.com/${user/org}/${project}/commit/${commit-sha}`. Looks like it's just markdown

**Comment by karuppiah7890** [comment]
@caarlos0 ^

**Comment by caarlos0** [comment]
I think we can close it!

Thanks for reporting it 🙏
