### ISSUE TITLE
tar ball does not have project name when releasing

### ISSUE THREAD

**Issue by karuppiah7890** [goreleaser/goreleaser#1226]
**Describe the bug**
The tar balls and checksums don't have project name in them

Logs:
https://gitlab.com/karuppiah7890/dummy-golang-project/-/jobs/339096812

See these parts of the logs -
```
archive=dist/_0.2.0_darwin_amd64.tar.gz
```

```
file=dist/_0.2.0_checksums.txt name=_0.2.0_checksums.txt
file=dist/_0.2.0_darwin_amd64.tar.gz name=_0.2.0_darwin_amd64.tar.gz
```

**To Reproduce**

config file - https://gitlab.com/karuppiah7890/dummy-golang-project/blob/0.2.0/.goreleaser.yml
Demo Releases page: https://gitlab.com/karuppiah7890/dummy-golang-project/-/releases 

You can see how the releases page shows tar balls with no names

Screenshot:
<img width="1205" alt="Screen Shot 2019-11-01 at 9 21 32 AM" src="https://user-images.githubusercontent.com/12808424/68001181-11270600-fc89-11e9-93a5-ed7854e1bf5b.png">

**Expected behavior**

Name project to be present in the tar balls

**Environment (please complete the following information):**

- OS: linux
- OS version: Linux 92899c273413 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux
- GoReleaser Version: 
version: 0.120.4
commit: 576156b03c9429fc66ded230ae34a8c2ac2c28ea
built at: 2019-10-30T23:54:55Z
built by: goreleaser
- GitLab version: public GitLab

**Additional context**
All pipelines:
https://gitlab.com/karuppiah7890/dummy-golang-project/pipelines

Actual release:
https://gitlab.com/karuppiah7890/dummy-golang-project/-/jobs/339096812

Dry run (skip publish) has proper project name in the tar ball:
https://gitlab.com/karuppiah7890/dummy-golang-project/-/jobs/339096810

When adding project name to the goreleaser config, things works

config file https://gitlab.com/karuppiah7890/dummy-golang-project/blob/master/.goreleaser.yml
job - https://gitlab.com/karuppiah7890/dummy-golang-project/-/jobs/339142174

<img width="775" alt="Screen Shot 2019-11-01 at 10 37 37 AM" src="https://user-images.githubusercontent.com/12808424/68003512-b7780900-fc93-11e9-8b72-a3973df7e18f.png">

**Comment by caarlos0** [comment]
https://gitlab.com/karuppiah7890/dummy-golang-project/ is a 404 for me.

anyway, probably goreleaser is not being able to guess the project name based on the git remote url.

you can add `project_name: blah` to your config -> https://goreleaser.com/project/

OR

you have some sort of typo on your archive name template, might as well check that

**Comment by karuppiah7890** [comment]
Oops, sorry. I made it public now

**Comment by karuppiah7890** [comment]
And yes, I added a `project_name` and it worked. I mentioned that in the additional context. Actually goreleaser is able to detect the project name as - Dry run (skip publish) has proper project name in the tar ball. Do check the links now 😄

**Comment by karuppiah7890** [comment]
I think there's some tiny bug out there. I tried to debug, didn't dig too much. My friends (first time oss contributors) might work on it. Or else I might check it out again 😄

**Comment by caarlos0** [comment]
can you paste the output of `git remote -v`? that might help :)

**Comment by karuppiah7890** [comment]
Does it matter? 🤔 I mean, I would expect skip publish to do the same as actual release. And the former works

**Comment by karuppiah7890** [comment]
I'll debug and come up with a reason :)

**Comment by karuppiah7890** [comment]
I'll try to look into this soon
