### ISSUE TITLE
adding semantic versiniong flags 

### ISSUE THREAD

**Issue by mrturkmen06** [goreleaser/goreleaser#1230]
**Is your feature request related to a problem? Please describe.**
Not sure if it is related to a problem or not, however I think, it would be nice to have flags to provide. 

**Describe the solution you'd like**

When we run `goreleaser` it releases from latest tag, but having some optional flags like
 
`goreleaser  patch`
`goreleaser  minor`
`goreleaser   major` 

would be nice, so in this case we do not need to generate tag before hand (manually). Let's say we are in branch `v2.3.5` and we have made developments on that branch, when we ran `goreleaser patch`, new tag (v2.3.5) & branch (v2.3.6) could be  created and pushed to origin automatically.  Besides releasing v2.3.5 tag on Github. 

Do you think that it would be useful ?

**Comment by caarlos0** [comment]
This seems out of the scope of goreleaser. If you want, I have another tool that does this: https://github.com/caarlos0/svu

["Yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion either way.

**Comment by hazcod** [comment]
FYI there is https://github.com/go-semantic-release/semantic-release
