### ISSUE TITLE
Pass contents of gcloud credentials file in env variable

### ISSUE THREAD

**Issue by Piccirello** [goreleaser/goreleaser#1234]
**Is your feature request related to a problem? Please describe.**
Goreleaser blobs support reading google credentials from the path specified by env variable `GOOGLE_APPLICATION_CREDENTIALS`. I store the json contents of the credentials file directly in my environment, rather than on the filesystem. So in order to use the credentials with goreleaser blobs, I must first write them to the filesystem in a `before` hook.

**Describe the solution you'd like**
I'd like it if goreleaser supported reading the credentials directly out of the environment, rather than just reading the file path out of the environment. This could use a different env variable, like `GOOGLE_APPLICATION_CREDENTIALS_CONTENTS`.

**Describe alternatives you've considered**
An alternate solution is providing a way to specify `after` hooks so that I can clean up the credentials file after the build (but before goreleaser exits). This would make the problem less noticeable by removing the credentials artifact.

**Comment by caarlos0** [comment]
FWIW, you could:

```
GOOGLE_APPLICATION_CREDENTIALS="<(echo $creds)" goreleaser --rm-dist
```

as a workaround...

Also, I think this is not handled by goreleaser itself, but by google's lib I'm afraid. I think it tries to get the config from the default places: environment variable, ~/.gcloud, and so on, so I'm not sure we can do exactly what you want..

**Comment by Piccirello** [comment]
That completely solved my issue! And I learned a bit about process substitution. Thanks for the help.

I did have to make one minor adjustment to the placement of the quotes:

```sh
GOOGLE_APPLICATION_CREDENTIALS=<(echo "$creds") goreleaser --rm-dist
```

**Comment by caarlos0** [comment]
oh yeah, my bad on the quotes thing!

Glad to help! 

Cheers
