### ISSUE TITLE
Customize go binary used to build 

### ISSUE THREAD

**Issue by natefinch** [goreleaser/goreleaser#1235]
I want to be able to build with a specific version of go, not just whatever version exists as "go" on the current system. 

**Describe the solution you'd like**
Add a GoBinaryPath (or some such) configuration option in the yaml.  This would allow you to choose one of the downloadable go binaries (like go1.13.4) and then you always know you're building with the version of Go you support (and fail if it doesn't exist).  This is a way to "pin" the go version you're building with, even if developers have different versions of go on their system.

**Describe alternatives you've considered**
A shell alias can work if you're working in a shell context, but I want to be able to do this within a magefile, so that's not really a solution for me.

This is mostly because we currently do releases from dev machines, clearly if this were being run in CI/CD, we'd just make sure the right version of Go is installed there.

**Comment by caarlos0** [comment]
This is interesting, depending on how we do this, it would allow to build and ship the same thing with different go versions as well... 

is that something people usually do? I can't think of an usecase for that...

BTW, you can add custom envs to the build, maybe add a custom PATH there would solve the issue?

**Comment by natefinch** [comment]
I'm not sure why anyone would release multiple binaries built with different versions of go. This is mostly an insurance policy to make sure your code is built with the version of go you expect it to be and not just whatever version happens to exist on the machine labelled "go".  

I think this is mostly only useful for people running goreleaser on their personal machine and not through CI where they should be able to specifically set what version of Go exists.

**Comment by craigfurman** [comment]
This would also help goreleaser docker image users. At the moment, goreleaser will use whatever go version is built into the image: https://github.com/goreleaser/goreleaser/blob/master/Dockerfile#L1

**Comment by caarlos0** [comment]
I'm not sure how the api should look like, but I agree we can add something related to this.

open to ideas.

**Comment by natefinch** [comment]
I think just a configuration value that has the name of the go binary you want to use.  It'll then use that name in place of "go" when running commands that would otherwise use the "go" command. Probably most of the time it would be something in your PATH, but there's nothing saying someone couldn't choose a relative path if they wanted.   That's what I do in Mage.

GoBinary: "go1.12.3" // defaults to "go"

**Comment by caarlos0** [comment]
SGTM @natefinch 

---

sorry for the late response, lost the notification somehow

**Comment by arlaneenalra** [comment]
Did anything ever come of this? I can see a very simple set of changes in https://github.com/goreleaser/goreleaser/blob/37b2f42b9325012fd0a8373d4e4f9fb6c4bc58f1/internal/builders/golang/build.go#L72 and https://github.com/goreleaser/goreleaser/blob/37b2f42b9325012fd0a8373d4e4f9fb6c4bc58f1/pkg/config/config.go#L184

which should make this extremely simple to support.

As an aside to that, it doesn't look like an alternative builder (i.e. something that just calls a build command..) would be all that difficult to include either ..

**Comment by caarlos0** [comment]
this is fixed on #1775
