### ISSUE TITLE
Homebrew release is coupled with github release

### ISSUE THREAD

**Issue by combor** [goreleaser/goreleaser#1237]
Hi guys,

Do I understand this correctly that if the github release is disabled than homebrew tap is not gonna be pushed also?

https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/brew/brew.go#L169

We have another switch to controll if the homebrew tap is pushed there: https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/brew/brew.go#L162

So maybe the github release and homebrew tap shouldn't be coupled?

My use case is that I'm not releasing to github but would like to push the tap only.

**Comment by caarlos0** [comment]
the homebrew tap needs a release to somewhere (github or gitlab) to work, because it uses those urls to download the artifacts.

that's why one depends on the other.

right now I don't have planned on adding support to other "backends". 

That being said, closing this :)

**Comment by combor** [comment]
But I don't need it to publish anywhere, I just need it to generate the brew tap only, this was definitely possible several releases back and was changed in this commit: https://github.com/goreleaser/goreleaser/commit/2da118a296a0dd8cb5d9c591abbaad845b15c900. It stopped working when I updated goreleasrer.

**Comment by caarlos0** [comment]
understood, makes sense, definitely a bug then

thanks for reporting :)

**Comment by caarlos0** [comment]
@combor please check #1252 :)

**Comment by lumaxis** [comment]
@caarlos0 Unfortunately, I think this was broken again by #1374 😕

**Comment by caarlos0** [comment]
hey @lumaxis, do you have a reproducible so I can take a look?

**Comment by lumaxis** [comment]
Sure!

1. Clone https://github.com/cli/cli
2. Run `goreleaser release --snapshot` or `goreleaser release --np-publish`
3. Observe that no Homebrew Formula is produced in `dist/`

**Comment by caarlos0** [comment]
will take a look, thanks @lumaxis 🙏

**Comment by caarlos0** [comment]
check https://github.com/goreleaser/goreleaser/pull/1425

**Comment by lumaxis** [comment]
Nice! Looks good from what I can tell.
And thanks for the quick fix 🙂
