### ISSUE TITLE
Integrate chglog with goreleaser

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#1245]
Use https://github.com/goreleaser/chglog to generate the changelog.

**Comment by jgustie** [comment]
Possibly unrelated, but in addition to chglog integration, would any changes support more generic process based generation?

While the process substitution approach works in general, it won't work when using the GitHub Action (in theory substitution could be implemented in the Toolkit `exec` or in the GoReleaser Action itself, but it seems like just baking it into the GoReleaser configuration would be a safer long term approach).

**Comment by lucacome** [comment]
Not sure if it's entirely relevant. 
I see that "standalone" `NFPM` supports the changelog but it looks like it's not an accepted parameter when using the `NPFM` "module (?)" in goreleaser. Am I missing something?

**Comment by caarlos0** [comment]
you are correct @lucacome

**Comment by lucacome** [comment]
I was looking at the code to see if I can help. 
Are you thinking about having a general approach to use chglog everywhere and not just in nfpm?
Specifically for nfpm, I was also trying to understand if it's more work than just be able to read the config option `changelog` and pass it to nfpm since it's already supported there 🤔

**Comment by lucacome** [comment]
Any updates on this?

**Comment by caarlos0** [comment]
I think the idea would be to replace our current changelog generation with it... not just on nfpm, but everywhere..

**Comment by caarlos0** [comment]
at this point this is likely not worth it anymore, as we have integration with github's changelog and several improvements in our own.

chglog is still useful for deb/rpms/etc

that said, closing

**Comment by lucacome** [comment]
Maybe a way to pass the changelog from GitHub to nfpm would be a nice addition 🙂

**Comment by lucacome** [comment]
Right now if I want to build deb packages with goreleaser, for example, there's not a way to pass down the changelog that is generated in goreleaser to nfpm to have in the package, if I'm not mistaken.

**Comment by caarlos0** [comment]
problem is that, AFAIK, the changelog needs to be in a specific format (yaml from chglog)... maybe @djgilcrease has some input on it?
