### ISSUE TITLE
v0.123.2 fails to build when installed with go get in a Go module

### ISSUE THREAD

**Issue by leighmcculloch** [goreleaser/goreleaser#1259]
**Describe the bug**

When `go get`ing version `v0.123.2` the following build error is seen.

```
# github.com/goreleaser/nfpm/rpm
../../go/pkg/mod/github.com/goreleaser/nfpm@v1.1.7-0.20191121174834-686a4e3cee7e/rpm/rpm.go:109:3: unknown field 'Summary' in struct literal of type rpmpack.RPMMetaData
```

**To Reproduce**

Version `v0.123.2` is currently the latest tagged version in the Git repository and so the `@latest` in the commands below is referring to that version.

```
$ mkdir test
$ cd test
$ go mod init test
$ go get github.com/goreleaser/goreleaser@latest
# github.com/goreleaser/nfpm/rpm
../../go/pkg/mod/github.com/goreleaser/nfpm@v1.1.7-0.20191121174834-686a4e3cee7e/rpm/rpm.go:109:3: unknown field 'Summary' in struct literal of type rpmpack.RPMMetaData
```

**Expected behavior**

Successful install.

**Environment (please complete the following information):**

- OS: `Linux`
- OS version: `Linux devenv-0 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux`
- GoReleaser Version `v0.123.2`

**Additional context**

Installing goreleaser without being in a Go module succeeds.

**Comment by caarlos0** [comment]
you need to run `go mod tidy`, seems like `go get` does not respect the `replace` declared on `go.mod`....

**Comment by caarlos0** [comment]
anyway, fix just got out on the dep, replace not needed anymore, fixed on master :)

**Comment by leighmcculloch** [comment]
As far as I understand the `replace` directive is only intended for use with local development. It's ignored outside of that. 🎉 Yay fix. Thanks! And thanks for building a very useful tool!
