### ISSUE TITLE
Missing region information when configuring blobs with an s3 provider

### ISSUE THREAD

**Issue by gabistoenescu** [goreleaser/goreleaser#1278]
**Describe the bug**

Configuring **_blobs_**  with the _s3_ provider does not seem to work because of missing AWS region information.

If a _region_ key is added to  the s3 config block, for example _region: us-east-1_ then you receive the error message - "field region not found in type config.Blob". This seems to be due to the fact the config.Blob struct does not have a field named "region".

If a _region_ key is not added to the s3 config block, expecting some default behavior, then you receive the error message - "error=Blob: failed to publish artifacts: failed to close Bucket writer: blob  (code=Unknown): MissingRegion: could not find region configuration"

**To Reproduce**

Configure an _s3_ upload using _blobs_.

**Expected behavior**

Upload to s3 should work by using the _s3_ provider with the _blobs_ customization as specified in the deprecation notice "https://goreleaser.com/deprecations#s3"

**Environment (please complete the following information):**

- OS: macOS 
- OS version: Catalina 10.15.2
- GoReleaser Version 0.123.3...

**Comment by caarlos0** [comment]
fixed, thanks for reporting :)

**Comment by gabistoenescu** [comment]
Great, thank you for the prompt response.

**Comment by marclop** [comment]
@caarlos0 when's the next bug-fix release coming?

**Comment by caarlos0** [comment]
> @caarlos0 when's the next bug-fix release coming?

when I have some time to be around... probably early 2020 :)
