### ISSUE TITLE
Allow overrides for build > flags (why? -buildmode=pie not available for windows)

### ISSUE THREAD

**Issue by panchoh** [goreleaser/goreleaser#1283]
Hi, folks!

I have a problem:

If I set the build flag `-buildmode=pie` *and* the target list contains `windows`, the run will fail, because `-buildmode=pie` is *not yet* available¹ for `windows`. 

¹: https://go-review.googlesource.com/c/go/+/203602/

Go 1.15 will hopefully support it.  So this will become a non-issue by then.

**RFC**: What about adding an appropiate `override` entry for `build` or `build/flags` ?

Workaround (of sorts): having two distinct `.goreleaser.yml` files, one for `windows`, other for the rest of the platforms.  But I guess this is not going to play well with GitHub Actions, when a release is published.

Do you have any suggestions as to how to accomplish what I need?

Thanks for the superb work, fellas.

**Comment by caarlos0** [comment]
You can add multiple builds, one just for windows without the buildmode flag, and another for the others with it.

Does that work for your case?

**Comment by panchoh** [comment]
> You can add multiple builds, one just for windows without the buildmode flag, and another for the others with it.
> 
> Does that work for your case?

I think it might.  Haven't tested it, thought.

Thanks.

**Comment by caarlos0** [comment]
np, sorry for the late response, I somehow lost the issue here... :/

**Comment by panchoh** [comment]
> np, sorry for the late response, I somehow lost the issue here... :/

Ah, not to worry! And thanks a bunch for `goreleaser`!!!
