### ISSUE TITLE
Add support for GOMIPS

### ISSUE THREAD

**Issue by rs** [goreleaser/goreleaser#1287]
The GOMIPS env is used to generate hard/soft float and mips revisions. It would be nice to be able to build variants with different values of this env in the same way as `goarm`.

**Comment by caarlos0** [comment]
hey @rs, can you check #1288?

**Comment by rs** [comment]
With both soft and hardfloat I get the following error:

```
   ⨯ release failed after 12.70s error=failed to add /Users/rs/Development/nextdns/dist/nextdns_linux_mips_softfloat/nextdns -> nextdns to the archive: file nextdns already exists in the archive
```
