### ISSUE TITLE
post-hook for modifying built binaries

### ISSUE THREAD

**Issue by titpetric** [goreleaser/goreleaser#13]
Some projects package resources into binaries with the form of a zip file. Most trivially, this is done like this:

~~~
echo file.zip >> binary
zip -A binary
~~~

I digress about specifics, but the point is that packages like [go.rice](https://github.com/GeertJohan/go.rice) and others add this binary/zip data into executables built by go. The packaging/embedding of them differs a bit, alas some post hook would be nice if one wants to follow the docs.

**Comment by caarlos0** [comment]
Seems like a valid suggestion. Thanks!

**Comment by bep** [comment]
I have not looked closely if this is already covered, but I guess this could also be used for a custom naming scheme. I'm looking at this to use with Hugo, and we have made up some names to make it easier for the users to understand (i386 => 32-bit etc.).

**Comment by caarlos0** [comment]
@bep some custom naming is available since [v0.2.9](https://github.com/goreleaser/releaser/releases/tag/v0.2.9), but not yet what you're asking.

I'll think in a way of doing what you're asking, probably something like:

```yml
archive:
  translations:
    linux: Linux
    i386: 32bit
    # etc
```

Not sure about the `translations` as name nor about the syntax itself... but seems like an ok way of doing this...

what do you think?

**Comment by bep** [comment]
>what do you think?

"translations" is not a very good term -- maybe just "replacements", but I agree in general: As list of old/new replacement pairs.

**Comment by caarlos0** [comment]
@bep version 0.3.0 supports the replacements as discussed. :)

**Comment by titpetric** [comment]
Guys, you slightly highjacked my original feature request. how about the OP? :)

**Comment by caarlos0** [comment]
@titpetric the post and pre-build hook are still a valid feature I guess..

**Comment by jorinvo** [comment]
What do you think about adding a `before` and `after` option to the `build` section?
Each of them would be a string which is evaluated as shell input. 
This way you could do some small one-line logic or you could call another executable for more complicated tasks.

**Comment by caarlos0** [comment]
Yes, I was thinking about doing just that 😀

**Comment by caarlos0** [comment]
Hey @titpetric , can you check if #101 would solve the problem for you?

Suggestions are welcome btw :D

**Comment by caarlos0** [comment]
mistaken ref closed the issue, reopened

**Comment by titpetric** [comment]
Thanks, I think it will do nicely :)
