### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by antonmedv** [goreleaser/goreleaser#1308]
Got ERR_SSL_PROTOCOL_ERROR.

**Comment by caarlos0** [comment]
seems fine here 🤔

also none of my monitoring reported it...

will close, but let me know if you still can't access it.

thans

**Comment by antonmedv** [comment]
Yes, still can’t access website. Maybe it’s due to I’m located in Russia. 

Maybe docs can be duplicated some there else?

**Comment by caarlos0** [comment]
hmm, weird, maybe it is yeah

I'll rework the site at some point, meanwhile, you can still read the docs [here](https://github.com/goreleaser/goreleaser/tree/master/www/content)
