### ISSUE TITLE
Publish to https://chocolatey.org/

### ISSUE THREAD

**Issue by codeskyblue** [goreleaser/goreleaser#131]
for windows quick install

**Comment by caarlos0** [comment]
I din't use Windows in a very long time, and never used cholatey.

Would you like to implement this feature?

**Comment by lox** [comment]
I'd be interested in contributing this feature as it's something I need. Anyone have any pointers on the best way to build windows packages for golang binaries?

**Comment by lox** [comment]
This looks relevant: https://github.com/mh-cbon/go-msi

**Comment by caarlos0** [comment]
> I'd be interested in contributing this feature as it's something I need. Anyone have any pointers on the best way to build windows packages for golang binaries?

@lox sorry, totally forgot to reply you here.

I don't know how chocolatey works, but assuming it looks like homebrew, you can duplicate the brew pipe and change the implementation...

Other than that I can happily guide you through specific questions you may have during the process 👍

**Comment by codeskyblue** [comment]
Find a project which use appveyor to publish to chocolatey.org
https://github.com/gabrielrobert/xavtool
