### ISSUE TITLE
Request for support termux

### ISSUE THREAD

**Issue by flw-cn** [goreleaser/goreleaser#1310]
**Is your feature request related to a problem? Please describe.**
I want to publish a termux package for my project, I have been able to do it manually, but I don't know how to integrate this action into goreleaser. The problem is that the release was not generated before calling goreleaser, so I couldn't package it. But after calling goreleaser, the GitHub release has been generated, so I have no time to put the termux package with it.

**Describe the solution you'd like**
I want a function like homebrew that can perform termux packaging or any other way. Executing termux packaging itself is not complicated, it only needs to be done after go build is completed and before GitHub release is executed. Can refer here:
https://github.com/termux/termux-create-package

**Describe alternatives you've considered**
I haven't found an alternative or workaround for the time being. I'm struggling with the documentation of goreleaser to find it. Please let me know if anyone knows how to do it.

**Additional context**
No more.

Thank you!

**Comment by caarlos0** [comment]
This seems very specific, and not many people need this I would guess.

You may need to call it manually after goreleaser runs

**Comment by caarlos0** [comment]
["Yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion either way.

**Comment by flw-cn** [comment]
Thanks, I got it.
