### ISSUE TITLE
Allow specifying which tag to build

### ISSUE THREAD

**Issue by nc-wittj** [goreleaser/goreleaser#1311]
**Is your feature request related to a problem? Please describe.**
We currently have our CLI inside a monorepo with the server. Our deploy process creates tags associated with the environment (eg. `prod-timestamp`). We are using semantic version tags for releasing the CLI. 
We've run into issues where the commit has already been tagged with the environment. Tagging the commit with a semantic version (eg. `v0.3.2`) causes GitHub Actions to run goreleaser. However, goreleaser picks the environment tag and fails because it's not a semantic version.
It looks like this issue has been raised before: #1163.

**Describe the solution you'd like**
A few options are:
- Allow setting which tag to build using an environment variable, like `GORELEASER_TAG`.
- Allow specifying a custom [`getTag()`](https://github.com/goreleaser/goreleaser/blob/449ed95bbe73fb88159e061352fcc786987d7d7d/internal/pipe/git/git.go#L124-L126) command. 
  - Then we could use `git describe --tags --match "v*" --abbrev=0` to pick the semantic version tag.
- Swapping to `git describe --tags --match "v*" --abbrev=0` to pick the tag. 
  - However, that would break users who don't prefix with `v`. 
    - Though maybe there could be an environment variable or setting to enable that mode, (eg. `GORELEASER_ENABLE_V_SEMVAR=true`? 🤷‍♂)
    - Or if `git describe --tags --match "v*" --abbrev=0` doesn't yield a tag, we fallback to the current command.
      - However, that wouldn't work if someone started using `v*` tags, but later dropped the prefix.

**Describe alternatives you've considered**
We currently have a bash script to loop through all the local tags and delete them until it reaches one that matches `v*`. While that works, it feels a bit hacky.

**Additional context**
I'm willing to help implement this if there's interest.

**Comment by aeneasr** [comment]
I just wanted to do open the exact same issue as we're experiencing exactly the same problem.

**Comment by nc-wittj** [comment]
Thank you, @aeneasr and @caarlos0! Nice work! 🎉
