### ISSUE TITLE
docs: add concept and configuration pages

### ISSUE THREAD

**Issue by zeisss** [goreleaser/goreleaser#1315]
**Is your feature request related to a problem? Please describe.**

As a new team member I joined my colleague on a Go project where we use `goreleaser`. Looking at the docs at goreleaser.com I am unable to understand in detail what this tool does and how to configure it.

**Describe the solution you'd like**

I am mainly missing two things from the docs:

1) something like a CONCEPT page where the workflow / idea / concept of goreleaser is described. First we fire before-hooks, then we build, then we package and sign ...
2) Explain the configuration file. Even with an existing config file I feel unable to modify things because I have no way to lookup what is supported and what each value expects.

**Describe alternatives you've considered**

* Reading the code - if this is expected to use goreleaser please do it as part of your guides/docs

**Comment by mislav** [comment]
There used to be a whole lot more on this page: https://goreleaser.com/customization/

It was the most useful documentation resource. Now it's basically empty. I think there was some bug with website generation.

**Comment by zeisss** [comment]
In the meantime I found various documents in the `www/content/` folder of this repo - they seem to be hidden via the metadata. I guess it is on purpose.

**Comment by ahmetb** [comment]
@mislav I've hit this and reported #1318 . Right now a significant portion of the Goreleaser documentation is not accessible. https://goreleaser.com/customization/ is empty.

**Comment by ahmetb** [comment]
If you're missing the old content, you can find the pages listed at  https://goreleaser.com/sitemap.xml until it is restored.

**Comment by caarlos0** [comment]
I think this is a dupe of #1318 


sorry I haven't seen this before.

**Comment by zeisss** [comment]
I haven't checked every page, but afaict there is is still an explanation of the general concept of goreleaser missing. What I have learned in the last days, is that there are modules/compoents(?) that can produce Artifacts and you can reference earlier artifacts in later modules (e.g. the build artifacts in the blob step).

IMO this should be explained somewhere, maybe with a link of the order?

**Comment by caarlos0** [comment]
hmm, yeah, I think that makes sense... 🤔
