### ISSUE TITLE
docs: Most of the documentation is inaccessible

### ISSUE THREAD

**Issue by ahmetb** [goreleaser/goreleaser#1318]
Hi, right now the website doesn't have anything (that I can find of) that links to some very important pages like:

- https://goreleaser.com/build/
- https://goreleaser.com/archive/
- https://goreleaser.com/templates/
- ...

I think all these were on 1 page before, but now they're spread out to separate pages. But I can't quite find these linked any of the pages on the sidebar?

> ![image](https://user-images.githubusercontent.com/159209/73329831-d09d4100-4213-11ea-9d87-8a1fa85facad.png)

**Comment by ahmetb** [comment]
Looking at http://web.archive.org/web/20190524130200/https://goreleaser.com/customization/ I can tell that everything under Customization ToC is now inaccessible in my experience:

![image](https://user-images.githubusercontent.com/159209/73330062-81a3db80-4214-11ea-816c-681acb7438de.png)

**Comment by caarlos0** [comment]
Thanks for reporting @ahmetb, sorry for the issue


the build is installing always the latest hugo, and we got a version with this problem: https://github.com/gohugoio/hugo/issues/6805

rebuilding to fix it, thanks!

**Comment by caarlos0** [comment]
TODO:

- [ ] fix Hugo's version on build time

**Comment by ahmetb** [comment]
Thanks for quick fix. As a Hugo user, I HIGHLY recommend pinning to a Hugo version and sticking to it as long as you can. I've been broken by Hugo several times, and  until it's v1.0 I would just pin the version.

**Comment by caarlos0** [comment]
Yeah I've been wanting to it for a long time... just never got to do actually do it 😂

ass beaten, will do it it today 🙏

**Comment by caarlos0** [comment]
done, thanks again @ahmetb! 🙏
