### ISSUE TITLE
Skip upload to GitHub

### ISSUE THREAD

**Issue by titpetric** [goreleaser/goreleaser#132]
I would like to build the binaries only, because either:

1. I'm not publishing them to GitHub but some other service (or may not even be using Git),
2. I'm separating build/release stages to run some tests/whatever before doing a release

Currently there are two requirements from goreleaser, in regards to this:

- we MUST set `release/repo` in yaml (or have a git repository available where we are running),
- we MUST set GITHUB_TOKEN

I'd like to skip both however. Ideally I would like to make these steps configurable with something like:

~~~
goreleaser build
goreleaser deploy
~~~

The first one would just build the required binaries/run pre/post hooks, the second one would push whatever is available in the dist/ folder (and could be replaced with something else, like `rsync`, or other service).

**Comment by jorinvo** [comment]
With the new syntax (https://github.com/goreleaser/goreleaser/issues/110#issuecomment-279025617) we should allow something like:

```yaml
release:
  disabled: true
```

I also think it would be helpful to add `build` and `deploy` sub commands as you suggested.
Maybe we can move this part to a separate issue?

**Comment by titpetric** [comment]
@jorinvo done, also recreated the PR just to verify Travis is building it. 👍

**Comment by titpetric** [comment]
@jorinvo any chance of merging this in? I'm wrinting a [12FA book](https://leanpub.com/12fa-docker-golang) and would love to include goreleaser in it.

**Comment by jorinvo** [comment]
@titpetric have to discuss this in #134 :)

**Comment by caarlos0** [comment]
check #136
