### ISSUE TITLE
Question: Is it possible to update arbitrary files to release?

### ISSUE THREAD

**Issue by ahmetb** [goreleaser/goreleaser#1320]
According to https://goreleaser.com/release/, it appears like only "archives" that can be referred to with their "id"s can be uploaded to release.

However, I have several extra files that I produce (such as `${artifact}.sig`) files that I'm trying to upload as well.

It doesn't appear like there's an option for this? (Something like `additional_files:` that matches to things added to `dist/` would be immensely helpful.)

If this doesn't exist and is a feature request, please label it as such –I wasn't sure.

**Comment by caarlos0** [comment]
if the `.sig` file was generated with goreleaser, it should be uploaded automatically 🤔

docs are a little misleading there, should be `artifact` instead of `archive`...

**Comment by ahmetb** [comment]
I think my main point is: is it possible to upload arbitrary files in dist/ as part of the release as well?

I upload some items that aren’t archive files (.yaml files etc that I create and copy to dist/).

**Comment by caarlos0** [comment]
> I think my main point is: is it possible to upload arbitrary files in dist/ as part of the release as well?

right now it isnt, but a lot of people ask for it, so maybe we can just add it :)
