### ISSUE TITLE
Ad hoc overrides for goos/goarch for local development

### ISSUE THREAD

**Issue by ahmetb** [goreleaser/goreleaser#1323]
**Problem**

We're trying to migrate a bunch off build/release scripts written in bash in an open source project ([krew](https://sigs.k8s.io/krew)) to GoReleaser.

We currently have a collection of bash scripts of the stages GoReleaser does:

- `hack/make-binaries.sh`: use gox to build all supported binaries
- `hack/make-binary.sh`: just compile local os/arch (using `gox -osarch`)
- `hack/make-checksums.sh`: create signature files
- `hack/make-release-artifacts.sh`: create archives (.tar.gz/zip)

However we're unable to move (due to several reasons).

For this issue specifically, we can't achieve what does `hack/make-binary.sh` which is building only for a particular os/arch.

Goreleaser doesn't seem to have support for overriding os/arch list with a CLI option or env variable that we can use in our local development.

If a developer doesn't have a beefy machine, waiting for Goreleaser to compile for 10 platforms + sign + archive takes far longer than doing just 1 `go build`.

**Describe the solution you'd like**

`goreleaser --snpashot --osarch="darwin/amd64" --skip-archive --skip-sign`

**Describe alternatives you've considered**

Considered doing `go build` for `hack/make-binary.sh` but we don't want to duplicate the build command (`-ldflags` etc). It's not ideal.

**Comment by caarlos0** [comment]
maybe we could add a new command, eg, `goreleaser build` that does only the build?

what do you think?

**Comment by ahmetb** [comment]
Might unnecessarily increase maintenance surface and cause duplication in test efforts etc. that’s why skipping some stages made more sense to me.

**Comment by caarlos0** [comment]
its actually less effort to do the build thing I think...

but I don't like the build name... need to find a name to indicate its just a local build for testing.. 🤔

**Comment by caarlos0** [comment]
maybe `goreleaser dev-build` 🤔

**Comment by ahmetb** [comment]
Yeah something like that would be super interesting for stuff like GitHub CI workflows, where I am not interested in building all cross-platform binaries. I could just say `goreleaser dev-build` to test if the Go code compiles.

**Comment by caarlos0** [comment]
on https://github.com/goreleaser/goreleaser/pull/2179 we added the --single-target flag which covers this as well.

Closing, thanks!
