### ISSUE TITLE
Option to skip arbitrary stages

### ISSUE THREAD

**Issue by ahmetb** [goreleaser/goreleaser#1324]
**Is your feature request related to a problem? Please describe.**
I have a use case where I sometimes want to run `goreleaser` locally for dev purposes. For that case, I need to skip as many cases as I can to increase local iteration speed.

**Describe the solution you'd like**

Right now we have

        --skip-publish            Skips publishing artifacts
        --skip-sign               Skips signing the artifacts
        --skip-validate           Skips several sanity checks

but stuff such as `--skip-archive`, `--skip-checksum` are missing.

Maybe goreleaser should have those? Or maybe a generic flag like:

     --skip=PHASE[,PHASE[,PHASE...]]
     --skip=archive,checksum,sign,release,before

**Describe alternatives you've considered**

Maybe goreleaser isn't created for local iteration, but given the amount of configuration I'm supplying (-ldflags and build options etc) I'd love to use goreleaser locally as well to build binaries to run.

**Additional context**
N/A

**Comment by caarlos0** [comment]
is only building the binary a viable option?

if it is, I'm in for that because it would be easier to test build settings and etc...

skipping arbitrary stages would be a bigger thing, maybe for v2... we don't even have "stages" (but I think we should), just "pipe" implementations...

**Comment by zbindenren** [comment]
I think only building option would already be great.

**Comment by caarlos0** [comment]
maybe with #1436 this becomes easier (or at least some of it)

**Comment by ahmetb** [comment]
SGTM. I'm still interested in something like `--skip-archive` as I've noticed a significant portion of time is spent doing non-local builds and archiving stuff in my low-CPU build system.

**Comment by kevinjqiu** [comment]
Definitely a worthy feature.  My current workaround is to have a `.goreleaser/` folder that stores dev.yaml and prod.yaml config files in a way that's similar to "profiles".  The dev profile contains only the OS/Arch combination of my local dev machine.

**Comment by caarlos0** [comment]
There is now a `goreleaser build` command. Does that solve your problem @ahmetb ?

**Comment by ahmetb** [comment]
@caarlos0 That's great! `goreleaser build` almost solves my problems –but unfortunately it validates "git is currently in a dirty state" (which isn't really useful for testing). 

Most of the time I need a "local binary" is to run integration tests etc on it. So I need to do something like:

    hack/make-local-binary.sh  <--- would be replaced by `goreleaser build`
    hack/run-integration-tests.sh

As you can imagine, while iterating locally, I'd almost always have a dirty git state, and having that as a build requirement is probably a dealbreaker to use this.

**Comment by ahmetb** [comment]
Actually it seems I can do `goreleaser build --skip-validate --rm-dist` so that's nice. I was expecting this would also do #1323 (i.e. only build for my local goos/goarch), other than that, I guess this does the job.

**Comment by caarlos0** [comment]
still need to add the local-goos only thing... probably something like `--goos` and `--goarch` flags on goreleaser build

or maybe `--local-platform`... really not sure... any ideas welcome :)

**Comment by ahmetb** [comment]
I'd recommend considering `build` command to be entirely for local development, so, it should imply skipping all stages except `build` and skips other GOOS/GOARCHes.

**Comment by fubarhouse** [comment]
Just my 2c - I'm trialing a workflow which injects a version number into a variable in the source code - I need this small change and I need to get around a `dirty` git state - it would be good to keep all validation in place except for the one expected change.
