### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by antonmedv** [goreleaser/goreleaser#1330]
Add this sparkline to README.md 💗
[![Sparkline](https://stars.medv.io/goreleaser/goreleaser.svg)](https://stars.medv.io/goreleaser/goreleaser)

```markdown
[![Sparkline](https://stars.medv.io/goreleaser/goreleaser.svg)](https://stars.medv.io/goreleaser/goreleaser)
```

**Comment by caarlos0** [comment]
we already have a graph for that...

thanks though :)
