### ISSUE TITLE
github/gitlab/gitea token default files not honored

### ISSUE THREAD

**Issue by julian7** [goreleaser/goreleaser#1348]
**Describe the bug**

Github token is not honored when no tokens configured, no envfiles set, but default `~/.config/goreleaser/github_token` exists. Gitlab, and gitea tokens have the same issue.

**To Reproduce**

* don't set `GITHUB_TOKEN` env.var,
* don't set `env_files.github_token` in `.goreleaser.yml`,
* place a valid github token to `~/.config/goreleaser/github_token` file.

**Expected behavior**

Token should be picked up from the default file.

**Additional context**

It seems like there is an easy fix, to place `defaults.Pipe{}` above `env.Pipe{}` in [internal/pipeline/pipeline.go](/goreleaser/goreleaser/blob/master/internal/pipeline/pipeline.go#L43).

**Comment by julian7** [comment]
Bump?

**Comment by caarlos0** [comment]
should be fixed #1389
