### ISSUE TITLE
Add helper commands

### ISSUE THREAD

**Issue by titpetric** [goreleaser/goreleaser#135]
Hello,

it would be helpful to add helper commands, that execute only part of the build/release processes. For example:

```
gorelease build
gorelease deploy/push github
gorelease deploy/push brew
```

I'm thinking about it mainly from the perspective that sometimes I want only to make a build (but not a deploy), and that there should be some familiarity to git for example (git status, git push,...).

**Comment by jorinvo** [comment]
Since a release can be different things than a `git push` in the future, I think it would be best to stick th the same naming as in the configuration file:
`goreleaser build` and `goreleaser release`.

What do you thinkg @caarlos0 ?

**Comment by caarlos0** [comment]
check #136
