### ISSUE TITLE
Question about uploading JUST binaries (not archives)

### ISSUE THREAD

**Issue by DarthHater** [goreleaser/goreleaser#1361]
Hi there!

Love this tool, and I'm having fun playing with it thus far.

We have a project that has been uploading binaries directly to GitHub (for ease of downloading them and installing, etc...). Goreleaser seems to upload an archive no matter what. Is there a way to have it just upload the binaries? Am I missing the point (totally could be).

Thanks a ton!

**Comment by caarlos0** [comment]
you can set archive.format to `binary`: https://goreleaser.com/archive/

**Comment by DarthHater** [comment]
Thank you!!!
