### ISSUE TITLE
Documentation to include simple multiple binary example

### ISSUE THREAD

**Issue by tuck1s** [goreleaser/goreleaser#1370]
My project has separate command-line tools in `cmd/tool1/tool1.go` and `cmd/tool2/tool2/go` etc, which I think is pretty common.

It took me a while, and a lot of searching  to find that each separate `builds` clause needs its own distinct "id". The default seems to be picked up from the main folder name (or github repo?).

It would be great to have a "multiple binaries" example  in the sections listed on https://goreleaser.com/.

Great tool, by the way!

**Comment by tuck1s** [comment]
Here's what I ended up with: https://github.com/tuck1s/sparkypmtatracking/blob/master/.goreleaser.yml

**Comment by caarlos0** [comment]
nice, feel free to open a PR if you wish, otherwise eventually I will (but idk when)
