### ISSUE TITLE
Go 1.14 supports freebsd/arm64 but is not built

### ISSUE THREAD

**Issue by rs** [goreleaser/goreleaser#1376]
Go 1.14 added support for freebsd/arm64 architecture. Goreleaser with this version of Go does not build this variant.

**Comment by caarlos0** [comment]
we don't distribute the freebsdamd64 no, but goreleaser should be able to build it if you want.

not sure which case you are talking about

**Comment by rs** [comment]
The latter. I just updated my project with Go 1.14 but goreleaser does not generate freebsd/arm64.

**Comment by caarlos0** [comment]
Did you add it to the targets ? By default it builds only Linux, Darwin and Windows 386 and amd64

**Comment by rs** [comment]
Yes: https://github.com/nextdns/nextdns/blob/master/.goreleaser.yml

**Comment by caarlos0** [comment]
I just tested here and it works as expected:

```
   • BUILDING BINARIES
      • building                  binary=/Users/carlos/Code/goreleaser/goreleaser/dist/goreleaser_freebsd_amd64/goreleaser

```

**Comment by caarlos0** [comment]
its on your app's release even: 
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/245435/75909033-055f7200-5e2a-11ea-93d2-8c9e1a434433.png">

**Comment by rs** [comment]
That's amd64, not arm64.

**Comment by caarlos0** [comment]
issue title says `amd64` 😆

**Comment by rs** [comment]
Oops, not anymore :)

**Comment by caarlos0** [comment]
haha, ok, pr incoming
