### ISSUE TITLE
Support docker images for several go versions

### ISSUE THREAD

**Issue by craigfurman** [goreleaser/goreleaser#1383]
Currently, goreleaser uses the go version it finds on `$PATH` to build projects. For users of the docker image, this couples the go version they're building with to goreleaser versions.

These could be decoupled by goreleaser shipping multiple docker images for each version, for some versions of go. Some examples of what the tags could look like:

* v0.128
* v0.128.0-go1.14
* v0.128-go-1.13.8
* v0.128.0-go-1.13

I don't really have an opinion on how many minor versions of go to support per goreleaser version, but 2 or 3 could be reasonable.

Functionality-wise, https://github.com/goreleaser/goreleaser/issues/1235 would solve the same problem as this. An extension of that issue could also allow for multiple versions of go to be used to build binaries, which this issue doesn't address. I'm not personally interested in that, only being able to pin the go version used and decouple that from goreleaser versions.

Do you reckon this, or the config option described in https://github.com/goreleaser/goreleaser/issues/1235, (or neither?) are things you'd be interested in PRs for?

**Comment by caarlos0** [comment]
I really don't feel like maintaining all this... you can always use an older version of goreleaser, or build your own docker image with everything you need.

["Yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, for now, this is a no.

Thanks fo the suggestion though.

**Comment by craigfurman** [comment]
Sure, that's totally understandable. I think I'll go with building my own goreleaser docker images for now. Thanks! 👍
