### ISSUE TITLE
Release notes update behaviour

### ISSUE THREAD

**Issue by estahn** [goreleaser/goreleaser#1384]
**Is your feature request related to a problem? Please describe.**

I'm using semantic-release (Example: https://github.com/hipages/php-fpm_exporter/blob/91410fbe43d76525681c176cecfb888535bfa67d/.github/workflows/test.yml#L75-L97 and #910) to generate the tag and release notes. After the tag is created goreleaser runs and generates the artifacts. Unfortunately, it doesn't update the release notes which includes the changelog and the docker-pull information.

**Describe the solution you'd like**

I would like to define the behaviour of how the release is updated, e.g. `overwrite`, `append`, `prefix`. 

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by estahn** [comment]
Waiting on feedback.

**Comment by caarlos0** [comment]
can't you create just the tag with semantic-release?

**Comment by caarlos0** [comment]
FWIW: https://github.com/caarlos0/svu

**Comment by caarlos0** [comment]
Need to decide on https://github.com/goreleaser/goreleaser/issues/1830 first..

**Comment by caarlos0** [comment]
finally happening #2702
