### ISSUE TITLE
No public-read ACL for blob/s3 artifacts

### ISSUE THREAD

**Issue by kszarek** [goreleaser/goreleaser#1387]
**Describe the bug**

I'm unable to set the `acl: public-read` and I cannot find any option to set it for blob/s3 provider.

```
Downloading https://s3-eu-west-1.amazonaws.com/...
#=#=#
curl: (22) The requested URL returned error: 403 Forbidden
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "name"
```

**To Reproduce**

```yaml
blobs:
    provider: s3
    region: eu-west-1
    bucket: bucket-name
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.
```
goreleaser check

   • loading config file       file=.goreleaser.yml
   • checking config:
      • LOADING ENVIRONMENT VARIABLES
      • SNAPSHOTING
      • GITHUB/GITLAB/GITEA RELEASES
      • PROJECT NAME
      • BUILDING BINARIES
      • ARCHIVES
      • LINUX PACKAGES WITH NFPM
      • SNAPCRAFT PACKAGES
      • CALCULATING CHECKSUMS
      • SIGNING ARTIFACTS
      • DOCKER IMAGES
      • ARTIFACTORY
      • BLOB
      • HOMEBREW TAP FORMULA
      • SCOOP MANIFEST
   • config is valid
```
**Expected behavior**

Because of missing public-read ACL for the packages we cannot download it from the S3 bucket over the curl.

**Environment (please complete the following information):**

- OS: [e.g. mac, linux] mac
- OS version: [uname -a] catalina
- GoReleaser Version [goreleaser --version]
```
version: 0.128.0
commit: 5efb690d1c3eae0605ff4a3a6cd65f470b1c96e9
built by: homebrew
```
- GitLab version (if using a private hosted one) n/a

**Additional context**
Add any other context about the problem here. Full output log with debug on
is probably a helpful thing to add here.

**Comment by kszarek** [comment]
ok, I've found that the current version is not supporting it.
```
ACLs
There is no common way to set ACLs across all bucket providers, so, go-cloud does not support it yet.
```

**Comment by caarlos0** [comment]
Yes, you'll need to set it on the bucket directly. :)
