### ISSUE TITLE
GitHub Discussions

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#1393]
I'm talking with with github support to enable the new Discussion feature on the org. It look like this: https://github.com/zeit/next.js/discussions

My idea is to then point all conversations that happen on Slack to Discussions, which should make things a bit more organized - and would also be easier to turn conversations into issues.

I think slack is good for general conversations, but I don't really like it for support, as same questions appear often and its painful to link things to each other...

Anyway, what do you think?

cc/ @lalloni @client9 @caarlos0 @joemiller @elopio @mgrachev @jorinvo @jspc @djgilcrease @crazy @mavogel @carinebecker

**Comment by lalloni** [comment]
I think it makes total sense.

**Comment by caarlos0** [comment]
enabled: https://github.com/goreleaser/goreleaser/discussions

**Comment by caarlos0** [comment]
Fixed issue templates:

![image](https://user-images.githubusercontent.com/245435/76868412-a47e6380-6845-11ea-9be0-710e3a45b44d.png)

**Comment by caarlos0** [comment]
announced on slack

**Comment by caarlos0** [comment]
changed docs

**Comment by caarlos0** [comment]
well, thats it, if you have any feedback let me know!

in the worst case, its not hard to revert to slack.

cheers!
