### ISSUE TITLE
nfpm: can't use release field in file_name_template

### ISSUE THREAD

**Issue by davewongillies** [goreleaser/goreleaser#1395]
**Describe the bug**

Recently https://github.com/goreleaser/goreleaser/pull/1363 was merged in to allow setting of the `release` field for an RPM.

The usual convention when building RPMs is to have the release number in the filename. I don't seem to be able to reference the `release` field for the `file_name_template`

**To Reproduce**

```
---
nfpms:
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Release }}-{{ .Arch }}"
```

Running `goreleaser release` ends with the following error:

```
   ⨯ release failed after 2.85s error=template: tmpl:1:37: executing "tmpl" at <.Release>: map has no entry for key "Release"
```

I also tried:
```
---
nfpms:
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Nfpms.Release }}-{{ .Arch }}"
```

Which errors out with:

```
   ⨯ release failed after 2.92s error=template: tmpl:1:43: executing "tmpl" at <.Nfpms.Release>: map has no entry for key "Nfpms"
```

**Expected behavior**

I should be able to use the `release` field in `file_name_template`

**Environment (please complete the following information):**

- OS: linux
- OS version: `Linux redacted-wrkstn 4.15.0-74-generic #83~16.04.1-Ubuntu SMP Wed Dec 18 04:56:23 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- GoReleaser Version
```version: 0.129.0
commit: 529cfca87d49cd93cdd7f8abd6eea6489c7cbd2e
built at: 2020-03-17T12:22:52Z
built by: goreleaser```

- GitLab version (if using a private hosted one)

**Additional context**
Add any other context about the problem here. Full output log with debug on
is probably a helpful thing to add here.

**Comment by caarlos0** [comment]
this was never available nor documented to be available... will implement it though...
