### ISSUE TITLE
CGo (via docker) with snap is possible

### ISSUE THREAD

**Issue by neilotoole** [goreleaser/goreleaser#1402]
See https://github.com/neilotoole/xcgo

Also see [neilotoole/sqlitr](https://github.com/neilotoole/sqlitr) for an example of publishing to all of the (major) `goreleaser` targets.

I hope not to maintain this project going forward. `goreleaser` seems the right team to maintain it. Although I firmly believe there should be an  officially-maintained `golang` /  `CGo` builder  image going forward.

`snap` makes that really hard tbf. Y'know, Ubuntu. But it's possible.

**Comment by caarlos0** [comment]
yeah, its possible, but I also don't want to maintain it.

there are also licensing issues, check https://github.com/goreleaser/goreleaser/issues/708 for details.

closing for now.
