### ISSUE TITLE
go get broken with code.gitea.io/sdk/gitea v0.11.0

### ISSUE THREAD

**Issue by tliron** [goreleaser/goreleaser#1405]
**Describe the bug**

Trying to install goreleaser via "go get" fails at the moment because sdk/gitea introduced a breaking change in v0.11.1. Reverting to v0.11.0 works.

**To Reproduce**

```
go get github.com/goreleaser/goreleaser
```
The error:
```
go/pkg/mod/github.com/goreleaser/goreleaser@v0.130.0/internal/client/gitea.go:94:40: not enough arguments in call to c.client.ListReleases
```

**Comment by caarlos0** [comment]
please follow the instructions in the docs: https://goreleaser.com/install/

thanks for the issue anyway :)

**Comment by tliron** [comment]
Of course, I know how to install it from the distribution ... I mostly use "go get" to potentially help the devs. :)

But if you don't consider it a bug, then it's not a bug!

**Comment by caarlos0** [comment]
I think its a bug on go get, which is not following go.sum... nothing I can do about it though :(

if the idea was to always use the latest dep of everything... go mods would not be needed hehe

**Comment by caarlos0** [comment]
btw in the end of the link I sent before, there is the guide on how to install from source...

you can also check https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md

hope it helps 🙏

**Comment by tliron** [comment]
As far as I know, go.sum is not used to check versions, go.mod is. I see that you are using a git commit number on go.mod rather than a version for gitea, not sure if that's the reason.

Totally by the way I notice that you are using yam.v2 instead of yaml.v3. :) Shouldn't make a difference but you might want to go for the latest API.

**Comment by 6543** [comment]
... it was taggged wrong -  now the right sha is tagged to v0.11.1 but somehow go get -u dont realice the new sha for the gat :/

**Comment by 6543** [comment]
when v0.12.0 is release it will have breaking changes ... but then I will send a pull myself to you :)

**Comment by 6543** [comment]
if the retag dont work the next day's a v0.11.2 will follow

**Comment by tliron** [comment]
Thanks @caarlos0 ! This project is amazing, I am just trying to be helpful.

**Comment by 6543** [comment]
@tliron @caarlos0 -> #1412

**Comment by caarlos0** [comment]
thanks @tliron @6543 


@6543 I think go mods cache the tags...

**Comment by 6543** [comment]
migration:  #1546
