### ISSUE TITLE
panic in the end of publishing in github

### ISSUE THREAD

**Issue by betorvs** [goreleaser/goreleaser#1410]
**Describe the bug**

I used goreleaser for a long time to create my releases in https://github.com/betorvs/sensu-opsgenie-handler with travis-ci. But in my last release in the end it produces a panic error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf3e8ce]
goroutine 1 [running]:
github.com/kamilsk/retry/v4.(*result).Error(0xc0003da260, 0x0, 0x0)
	<autogenerated>:1 +0x2e
github.com/pkg/errors.(*withMessage).Error(0xc0003da280, 0x0, 0x0)
	/Users/carlos/Code/Go/pkg/mod/github.com/pkg/errors@v0.9.1/errors.go:244 +0x37
github.com/pkg/errors.(*withMessage).Error(0xc0003db780, 0x0, 0x0)
	/Users/carlos/Code/Go/pkg/mod/github.com/pkg/errors@v0.9.1/errors.go:244 +0x37
github.com/apex/log.(*Entry).WithError(0xc0003ebba0, 0x159e220, 0xc0003db7e0, 0x0)
	/Users/carlos/Code/Go/pkg/mod/github.com/apex/log@v1.1.1/entry.go:55 +0x49
github.com/apex/log.(*Logger).WithError(0x1e4dbe0, 0x159e220, 0xc0003db7e0, 0x0)
	/Users/carlos/Code/Go/pkg/mod/github.com/apex/log@v1.1.1/logger.go:79 +0x9f
github.com/apex/log.WithError(...)
	/Users/carlos/Code/Go/pkg/mod/github.com/apex/log@v1.1.1/pkg.go:43
main.main()
	/Users/carlos/Code/goreleaser/goreleaser/main.go:116 +0x1c76
Script failed with status 2
```

More details in https://travis-ci.org/github/betorvs/sensu-opsgenie-handler/builds/669138311

**To Reproduce**

https://github.com/betorvs/sensu-opsgenie-handler/blob/master/.goreleaser.yml

In my travis-ci configuration I have my GITHUB_TOKEN configured.

> Make sure your config file is valid by running

```
$ goreleaser check -f .goreleaser.yml 

   • loading config file       file=.goreleaser.yml
   • checking config: 
      • LOADING ENVIRONMENT VARIABLES
      • SNAPSHOTING      
      • GITHUB/GITLAB/GITEA RELEASES
      • PROJECT NAME     
      • BUILDING BINARIES
      • ARCHIVES         
      • LINUX PACKAGES WITH NFPM
      • SNAPCRAFT PACKAGES
      • CALCULATING CHECKSUMS
      • SIGNING ARTIFACTS
      • DOCKER IMAGES    
      • ARTIFACTORY      
      • S3               
      • BLOB             
      • HOMEBREW TAP FORMULA
         • optimistically guessing `brew[0].installs`, double check
      • SCOOP MANIFEST   
   • config is valid  
```

**Expected behavior**

Finish without error.

**Environment (please complete the following information):**

Please check travis ci output. 

**Additional context**
Add any other context about the problem here. Full output log with debug on
is probably a helpful thing to add here.

**Comment by william20111** [comment]
Same this morning, pinned to v0.129 to fix for now.

**Comment by bitsf** [comment]
same with v0.130

**Comment by vs4vijay** [comment]
Same, Its happening for me as well. I am using GitHub Actions...

Version:
```
version: 0.129.0
commit: 529cfca87d49cd93cdd7f8abd6eea6489c7cbd2e
built at: 2020-03-17T12:19:39Z
built by: goreleaser
```

Go Version: 1.14

**Comment by caarlos0** [comment]
thanks, working on a fix...

**Comment by caarlos0** [comment]
fixed in 7661587a9e7be869131a6e50a77685169c8222f6

tag v0.130.2

thanks everyone 🙏

**Comment by vs4vijay** [comment]
Thanks, what was the issue? #Curious

**Comment by caarlos0** [comment]
I added a "do not retry upload if the error is artifact already exists" to github client, but end up wrapping a possibly nil error which caused the nil pointer deference.

basically https://github.com/goreleaser/goreleaser/commit/7661587a9e7be869131a6e50a77685169c8222f6 fixes it
