### ISSUE TITLE
Add flag to provide custom repo/git-remote to publish the release on

### ISSUE THREAD

**Issue by erwinvaneyk** [goreleaser/goreleaser#1432]
**Is your feature request related to a problem? Please describe.**
I have a project which has multiple upstreams/github repositories. Right now goreleaser always tries to publish on the repo that is in the `origin` remote

**Describe the solution you'd like**
Ideally I would like a flag `--remote=alternativeRemote` or `--repo=myOrg/alternativeRepo` that will make goreleaser publish the release to that repository.

**Describe alternatives you've considered**
It is a small quality-of-life improvement that right now can be fixed by manually altering your git-remotes, so I can understand if this is beyond the scope of this project. 

**Additional context**
```
version: 0.131.1
commit: dec22cf0c8a6464390ea26b42086d242e396ecda
built at: 2020-04-03T02:30:00Z
built by: goreleaser
```

**Comment by caarlos0** [comment]
I think the release customization solves this already:

```yaml
release:
  github:
    owner: user
    name: repo
```

https://goreleaser.com/customization/#Release

have you tried that?
