### ISSUE TITLE
refactor main.go

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#1436]
main.go is already a pretty much untestable mess, we should probably refactor it.

Now that we have multiple commands, maybe using spf13/cobra makes more sense as well.

**Comment by jftuga** [comment]
What advantages of cobra do you see vs kingpin?  Kingpin supports multiple commands.  I'm not partial to one or the other.

**Comment by caarlos0** [comment]
I think the end code is better organized and also a bit easier to write tests to... 

also this influences me a bit towards that https://github.com/alecthomas/kingpin#contributions-only 

and the fact that most large/complex cmds use cobra as well...
