### ISSUE TITLE
Expose more snap configuration in SnapraftAppMetadata

### ISSUE THREAD

**Issue by neoaggelos** [goreleaser/goreleaser#1452]
**Is your feature request related to a problem? Please describe.**

Initial context: https://github.com/TheThingsNetwork/lorawan-stack/pull/2361#issuecomment-614973823

```
env MYVAR=$OTHER_ENV_VAR executable
```

I would assume being able to override the command is useful in other scenarios as well. This is something well supported by Snapcraft, so `goreleaser` should not block using it.

**Describe the solution you'd like**

Add `Command`, `Environ` and more fields in `SnapcraftAppMetadata`. Most can simply then be passed to the `snap.yaml` file.

It should be simple enough to have that support, and possibly falling back to defaults where needed. 

**Describe alternatives you've considered**

**Additional context**

**Comment by caarlos0** [comment]
our current snap implementation is a bit hacky IMHO... I'm not sure how to add it.

If you can work on a PR it would be awesome though 🙏

**Comment by neoaggelos** [comment]
I can try to take on some of these. I am mostly interested in setting the environment, the command, and possibly adding a few more files (e.g. wrapper scripts) on the resulting snap.

**Comment by eberkund** [comment]
Personally I find it easier not to use goreleaser for producing snap packages. One thing I have encountered though is getting the correct version string inside my snapcrafy.yaml file.

It would be nice if goreleaser had a command which would just return the version string (as retrieved from Git), such as 0.3.5-next.

**Comment by caarlos0** [comment]
@eberkund maybe this helps: https://github.com/caarlos0/svu

**Comment by eberkund** [comment]
> @eberkund maybe this helps: https://github.com/caarlos0/svu

Thanks for sharing this looks similar to what I need. But it doesn't seem to work exactly the same way as goreleaser which adds a "-next" suffix to the version number of  "dirty" releases.

**Comment by caarlos0** [comment]
> Thanks for sharing this looks similar to what I need. But it doesn't seem to work exactly the same way as goreleaser which adds a "-next" suffix to the version number of "dirty" releases.

yeah, this is done in the `snapshot` part of goreleaser probably (assuming your snapshot template is something like `{{.Version}}-next`.

You could use `echo "$(svu current)-next"` to get something similar...

**Comment by neoaggelos** [comment]
Closing this one since #1553 has been merged.
