### ISSUE TITLE
Add support for templated Release notes, footer and header

### ISSUE THREAD

**Issue by ccremer** [goreleaser/goreleaser#1453]
**Is your feature request related to a problem? Please describe.**
The default release text with Changelog and Docker images is nice. Also the option to custom release headers and footers. But it is too static. In my case I not only want to provide links on how to `docker pull` a certain image, but also provide instructions to install a Helm chart with a specific just-released image version. e.g.
`goreleaser release --release-footer=.github/release-footer.md`
```
## Helm Chart

Documentation: https://ccremer.github.io/charts/kubernetes-zfs-provisioner/

helm repo add ccremer https://ccremer.github.io/charts
helm install ccremer/zfs-kubernetes-provisioner --set image.tag=<release-tag>
```

**Describe the solution you'd like**
The release footer should be parsed with Go template and inject sensible variables, e.g. Version:
`goreleaser release --release-footer=.github/release-footer.gotmpl`
```
## Helm Chart

Documentation: https://ccremer.github.io/charts/kubernetes-zfs-provisioner/

helm repo add ccremer https://ccremer.github.io/charts
helm install ccremer/zfs-kubernetes-provisioner --set image.tag=v{{ .Version }}
```

**Describe alternatives you've considered**
* Right now, I have to either set a placeholder which the user has to replace: <release-tag>
* Or manually edit the release notes after releasing to update the placeholder

**Additional context**
Packaging and releasing Helm Charts is out of scope for goreleaser, there are plenty other tools for that. However, there are cases where the plain binary or docker image release as a package option is insufficient and the image is meant to be installed on Kubernetes together with other artifacts, hence the links/instructions to Helm Chart.

**Comment by caarlos0** [comment]
yeah feel free to open a PR on that :)

**Comment by ccremer** [comment]
Wait, this has been implemented? Cool! Thanks a ton 👍 
what kind of properties are available for templating? Is it that list: https://goreleaser.com/customization/templates/ ?

**Comment by caarlos0** [comment]
Yeah, should be the first table ther :)
