### ISSUE TITLE
Test releases before publishing them

### ISSUE THREAD

**Issue by aeneasr** [goreleaser/goreleaser#1454]
**Is your feature request related to a problem? Please describe.**

[We](https://github.com/ory) use goreleaser for all our projects. Unfortunately, it happens from time to time that we forget to e.g. introduce a before hook (such as packr2) or do some other stupid (human) error that causes a release to fail.

It is currently not possible to test the release (e.g. executing a shell command) before it is being published (e.g. uploaded to Docker Hub).

**Describe the solution you'd like**

I would like to be able to define one or more steps that make it possible to test a release before it is being uploaded, e.g.:

```
before_publish:
  hooks:
    - echo foo
    - echo bar
    - exit 1
```

**Describe alternatives you've considered**

The only alternative would be to pause and resume a release, e.g. by doing

```
goreleaser checkpoint prepare # basically goreleaser release without publishing
goreleaser checkpoint resume ...
```

**Comment by caarlos0** [comment]
its an interesting idea... 

have you considered grepping things on the config (e.g. `grep packer .goreleaser.yaml || exit 1`)?

another idea:

```
goreleaser --skip-publish --rm-dist
# run your tests
goreleaser --rm-dist # build should be fast because of caching et al
```

**Comment by aeneasr** [comment]
My problem is that we cross-compile for many platforms which takes like 15 or 20 minutes in the CI. Maybe it takes so long because we're using the `-a` flag but since that's used in all the docs I assumed it's a good idea?

All I really need is to check the linux/amd64 binary since that's the CI os and also what Docker uses.

I think saving the overhead would be preferable and I also think that a test stage would be pretty cool. Tools like Skaffold for example also have this test stage before deploy and it seems like it would be easy to implement as the code (with before hooks) more or less exists already :)

**Comment by ryancurrah** [comment]
We are currently not using goreleaser for publishing because of this. We need to test especially docker artifacts before publishing.

**Comment by caarlos0** [comment]
> We are currently not using goreleaser for publishing because of this. We need to test especially docker artifacts before publishing.

`goreleaser --rm-dist --skip-validate --skip-publish` should allow you to test the docker images manually if that helps...

**Comment by ryancurrah** [comment]
Yep we are doing that, but then we would have to rebuild everything. Would be great if there was a publish subcommand to save on rebuilding.

**Comment by ghostsquad** [comment]
Being able to decouple the build from publish would be one way to add prepublish steps. I also like the idea of before/after hooks

**Comment by caarlos0** [comment]
`goreleaser build` was added a couple of weeks/months ago... which might help.

we also have an issue for a proper "test" workflow:  #2355 

that being said, will close this. Please reopen if you think it's needed. Thanks!
