### ISSUE TITLE
Support for upx

### ISSUE THREAD

**Issue by schollz** [goreleaser/goreleaser#146]
I've been [using `upx --brute` to reduce the size of my binaries](https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/) by 40%. 

I'd like to use goreleaser in my releasing pipeline, but I found the post hook does not run at the right time to add `upx`.

I was wondering, would you be interested in specifically adding a flag for automatically running `upx` after building in goreleaser? If so, I can work on a PR.

**Comment by jorinvo** [comment]
Hi @schollz, the post hook exists to do exactly this kind of optimizations.
Could you give some details why it is the wrong time to add upx?

Would be nicer if we can make the hooks usable enough to support this instead of including this specific tool in GoReleaser itself.

**Comment by schollz** [comment]
Agreed. Maybe you can help diagnose the problem with my hooks?

When my post hooks is just
```yaml
  hooks:
    post: upx --brute dist/cowyo_Linux_x86_64/program
```
it works. But since I want to run `upx` on every binary, I opted to put it in a script (`script.sh`):

```bash
upx --brute dist/cowyo_Windows_x86_64/program.exe
upx --brute dist/cowyo_Linux_x86_64/program
```
and change the hook to
```yaml
  hooks:
    post: ./script.sh
```

However, in this case it never runs the hook and the output of goreleaser is just

```
$ goreleaser --skip-release
Setting defaults
Building binaries
 -> Building dist/cowyo_Windows_x86_64/program.exe
 -> Building dist/cowyo_Linux_x86_64/program
```

There is no other output and I can tell by the size of the binaries that `upx` has not been run.

Thanks for your help!

**Comment by caarlos0** [comment]
hmm, seems like a bug to me.

I'll look into it.

**Comment by caarlos0** [comment]
Adding it this way seems to work:

```yml
build:
  hooks:
    post: /bin/sh script.sh
```

My `script.sh` looks like:

```sh
#!/bin/bash
set -ex
upx dist/goreleaser*/goreleaser*
```

The problem is that it runs for all builds, instead of running one time only. I'll fix that.

**Comment by schollz** [comment]
Awesome @caarlos0, thats great!

Would it be possible to also add more output for when when the hooks are run? Maybe just something like

```
Setting defaults
Building binaries
 -> Building dist/cowyo_Windows_x86_64/program.exe
 -> Building dist/cowyo_Linux_x86_64/program
Running post hooks
 -> '/bin/sh script.sh'
```

`upx` is very slow, so it would be nice to know that it is actually running.

**Comment by caarlos0** [comment]
I added it in #148
