### ISSUE TITLE
Allow skipping post build hooks

### ISSUE THREAD

**Issue by radeksimko** [goreleaser/goreleaser#1469]
**Is your feature request related to a problem? Please describe.**

I would like to use GoReleaser also in a CI pipeline, so I can test release-ability. Since GoReleaser has all the build flags and build targets it looks very tempting to use the skip flags and use it to just test whether everything compiles.

```
goreleaser release --rm-dist --snapshot --skip-publish --skip-sign
```

Post build hooks can however contain logic which is either unnecessary (upx compression) or even undesirable (code signing) to run in such context and there's currently no way to avoid running them.

**Describe the solution you'd like**

Introduce `--skip-post-build-hooks` flag which will skip execution of post build hooks.

I appreciate there's already many `--skip-...` flags, so I'm open to alternative ideas that could avoid polluting the endless list of flags.

**Describe alternatives you've considered**

Passing an ENV variable to goreleaser in a CI build and adding `if` conditional to `.goreleaser.yml`.

**Comment by caarlos0** [comment]
I get the idea and it makes sense... I'm also not sure about more `--skip` flags... 
There is also #1446 which I guess would also imply skipping this?

I'm thinking maybe add a new sub command, `goreleaser build`, which only builds things, and then add `--skip-post-build-hooks` or something like that...

wdyt?

**Comment by radeksimko** [comment]
Yeah, `build` subcommand sounds like a good idea. 👍

#1446 doesn't seem to be skipping build hooks at this point, but the explained use case is the same as I described here, so I maybe the subcommand is generally a better solution for this and it should be skipping post hooks by default. Then users still have the choice of running `release` with all the skip flags if they want to run them.

I'm not sure about pre-build hooks in this hypothetical subcommand, but assuming people use it for building website assets, it may be something they will want to run as part of CI check.
