### ISSUE TITLE
GoReleaser is causing CGO issues

### ISSUE THREAD

**Issue by kushthedude** [goreleaser/goreleaser#1478]
**Describe the bug**

We have been using GoReleaser for a while in our project. There have been no issues in the past, but recently GoReleaser has been broke for a few releases.
We have `CGO_Enabled=0` in our env , which causes issues with windows_amd64 build with error log-:
```sh
  ⨯ release failed after 164.57s error=failed to build for windows_amd64: # github.com/valyala/gozstd
60
##[error]/Users/runner/go/pkg/mod/github.com/valyala/gozstd@v1.5.0/stream.go:14:48: undefined: DefaultCompressionLevel
61
##[error]/Users/runner/go/pkg/mod/github.com/valyala/gozstd@v1.5.0/stream.go:31:59: undefined: CDict
62
##[error]/Users/runner/go/pkg/mod/github.com/valyala/gozstd@v1.5.0/stream.go:35:64: undefined: CDict
63
##[error]/Users/runner/go/pkg/mod/github.com/valyala/gozstd@v1.5.0/stream.go:47:20: undefined: Writer
64
##[error]/Users/runner/go/pkg/mod/github.com/valyala/gozstd@v1.5.0/stream.go:56:22: undefined: NewWriterLevel
65
##[error]/Users/runner/go/pkg/mod/github.com/valyala/gozstd@v1.5.0/stream.go:101:61: undefined: DDict
66
##[error]/Users/runner/go/pkg/mod/github.com/valyala/gozstd@v1.5.0/stream.go:110:6: undefined: Reader
67
##[error]/Users/runner/go/pkg/mod/github.com/valyala/gozstd@v1.5.0/stream.go:117:8: undefined: NewReader
68

69
##[error]The process '/Users/runner/runners/2.169.1/work/_temp/aa16b586-7efc-4c57-afa8-2fe09f274c97/goreleaser' failed with exit code 1
```
Complete logs can be found here -: https://github.com/layer5io/meshery/runs/624665499 .

After investigating into this, we came to know that `gozstd` requires `CGO_Enabled=1` for env as given here https://github.com/valyala/gozstd#how-to-cross-compile-gozstd . 

But when we change `CGO_Enabled=1` in our config file, releaser faild for freebsd_386 with logs -:
```sh
  ⨯ release failed after 201.24s error=failed to build for freebsd_386: # runtime/cgo
60
##[error]gcc_freebsd_386.c:39:2: error: implicit declaration of function 'SIGFILLSET' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
61
##[error]gcc_freebsd_386.c:39:13: error: variable 'ign' is uninitialized when used here [-Werror,-Wuninitialized]
62
##[error]gcc_freebsd_386.c:34:14: note: initialize the variable 'ign' to silence this warning
63

64
##[error]The process '/Users/runner/runners/2.169.1/work/_temp/974550c8-7a24-4bb0-8f2c-554fd1241f72/goreleaser' failed with exit code 1
```
Complete logs over here : https://github.com/layer5io/meshery/pull/914/checks?check_run_id=624870891

**To Reproduce**

GoReleaser Config File :- https://github.com/layer5io/meshery/blob/master/.goreleaser.yml

**Expected behavior**

GoReleaser should build the release without any issues.

**Additional context**

Please let us know a solution for this.

**Comment by kushthedude** [comment]
cc : @caarlos0

**Comment by caarlos0** [comment]
this is not a problem in goreleaser, if you `GOOS=freebsd go build` it will fail too.

also note that in the link you shared there are instructions to use another compile (`CC=arm-linux-gnueabi-gcc`) which seems you are not following.
