### ISSUE TITLE
Support brew post_install script

### ISSUE THREAD

**Issue by Piccirello** [goreleaser/goreleaser#1487]
**Is your feature request related to a problem? Please describe.**
After `brew install`, I want my application to set a configuration variable so it knows it was installed through brew. This will allow me to provide a simple update mechanism within my app.

**Describe the solution you'd like**
I'd like goreleaser to support brew `post_install` in addition to the existing `install` and `test` directives.

**Describe alternatives you've considered**

I can call `brew ls --versions $NAME` and check the exit code to see if my application is installed via brew. This is admittedly working well for my use case.

**Additional context**
None

**Comment by caarlos0** [comment]
check #1790

**Comment by Piccirello** [comment]
Thank you @caarlos0!
