### ISSUE TITLE
Support homebrew `--devel` seamlessly

### ISSUE THREAD

**Issue by JonasPf** [goreleaser/goreleaser#1488]
**Is your feature request related to a problem? Please describe.**

I do release-candidate releases. It would be nice if people could install them using homebrew.

```
brew install [...] --devel
```

This is currently already sort-of doable using the `custom_block` directive but it would be nicer if this happened automatically based on the `release.prerelease` directive.

**Describe the solution you'd like**

If a prerelease is detected (based on `release.prerelease`) the brew pipeline should **not** update the main portion of the formula. Instead it should add a `devel` section as described here: https://docs.brew.sh/Formula-Cookbook#devel. The rest of the formula should not change (i.e. it should still point to the previous stable version).

**Describe alternatives you've considered**

If the location of the build artifacts is already known, one can do a normal release and add the pre-release artifacts using the `custom_block` directive. This is tricky because it means:

1. the artifacts need to get created upfront
2. need to convince goreleaser to re-publish the brew formula for the latest stable version with the new pre-release version without re-publishing the stable version (there are flags to disable things, not sure if they are enough)

**Comment by caarlos0** [comment]
Its deprecated on homebrew core: https://discourse.brew.sh/t/why-is-devel-block-deprecated/8011/2

Head blocks will not be supported (check https://github.com/goreleaser/goreleaser/issues/1772), so, closing this as well.

Thanks for opening the issue anyway! Cheers!
