### ISSUE TITLE
Disable building archives

### ISSUE THREAD

**Issue by ryancurrah** [goreleaser/goreleaser#1490]
**Is your feature request related to a problem? Please describe.**
We do not want to build archives.

**Describe the solution you'd like**
```yaml
archives:
  disable: true
```

**Describe alternatives you've considered**

**Additional context**

**Comment by caarlos0** [comment]
you can use `format: binary` for that:

```yaml
archives:
- format: binary
```

**Comment by ryancurrah** [comment]
Thank you @caarlos0!
