### ISSUE TITLE
Wrong Windows artifact names

### ISSUE THREAD

**Issue by andreynering** [goreleaser/goreleaser#1500]
Hey there!

I think I just found a bug while using Goreleaser on [testfixtures](https://github.com/go-testfixtures/testfixtures) through [this GitHub Action](https://github.com/go-testfixtures/testfixtures/blob/master/.github/workflows/release.yml).

I just released and noticed that the artifact file names for Windows kept `.exe` in it:

<img width="753" alt="Screen Shot 2020-05-10 at 17 22 54" src="https://user-images.githubusercontent.com/7011819/81509705-09ed4e80-92e3-11ea-967e-40f50cdea58e.png">

That didn't happen about 14 days ago when I published the previous release.

**Comment by joemiller** [comment]
I just noticed this issue too. It's present in the golangci-lint repo. The latest v1.27.0 (2020/05/13) release has this extra ".exe" in the zip file name, which causes the 1-liner install script to fail with a 404:

```console
$ curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -x -s -- -b "$HOME/bin"

...
curl -w '%{http_code}' -sL -o /tmp/tmp.XnAWGBJW3g/golangci-lint-1.27.0-windows-amd64.zip https://github.com/golangci/golangci-lint/releases/download/v1.27.0/golangci-lint-1.27.0-windows-amd64.zip
+ code=404
+ '[' 404 '!=' 200 ']'
+ log_debug 'http_download_curl received HTTP status 404'
```

The previous release v1.26.0 (2020/05/01) has the correct zip file name.

I haven't bisected through the commit history yet to see if I can figure out where this change happened yet, but I figured this extra information may help the investigation.

![image](https://user-images.githubusercontent.com/377603/82600586-f9e73180-9b62-11ea-8a0d-bc550e1b63c9.png)

![image](https://user-images.githubusercontent.com/377603/82600608-02d80300-9b63-11ea-9be9-1bcdc3a1d395.png)

**Comment by andreynering** [comment]
The file name inside the `*_checksums.txt` file is also wrong. AFAIK this affects GoDownloader, and require us to also edit that file and not only the artifact name on GitHub.

**Comment by caarlos0** [comment]
likely caused by 705ab90e4f612fdb186e8354b5e1997d543bb0a9

**Comment by caarlos0** [comment]
@andreynering probably because of your name template:

https://github.com/go-testfixtures/testfixtures/blob/master/.goreleaser.yml#L18

it should probably use `{{ .ProjectName }}` instead of `{{ .Binary }}`. It was working before, but it probably shouldn't...
anyway, will revert back to previous the behavior.

**Comment by caarlos0** [comment]
can you try https://github.com/goreleaser/goreleaser/pull/1539 ?

**Comment by laverya** [comment]
> it should probably use {{ .ProjectName }} instead of {{ .Binary }}. It was working before, but it probably shouldn't...

That only works until your project builds multiple binaries, I'm afraid...

**Comment by caarlos0** [comment]
> That only works until your project builds multiple binaries, I'm afraid...

if you have multiple binaries in the same archive, `{{ .Binary }}` won't work either I think 🤔 (or at least would be wrong)

If you have one archive for each build, then yes, it makes sense, but then you can also hardcode the binary name...

**Comment by laverya** [comment]
> but then you can also hardcode the binary name...

You know, that sounds like a much better idea than what we're doing now. Thanks!

**Comment by andreynering** [comment]
A bit late to the party, but thanks for the fix @caarlos0!
