### ISSUE TITLE
Add some notification after release

### ISSUE THREAD

**Issue by wesleimp** [goreleaser/goreleaser#1517]
I'm not sure how valuable is it, but I think that would be nice to have some notification after release. For example, slack, discord or someting like that.

**Comment by radeksimko** [comment]
Not to oppose your suggestion, but unless you want to report on certain stages of the release (like compilation of binaries, creation of archives, publishing of Homebrew formula, ...) I think this can already be done outside of GoReleaser by integrating notification into whatever CI you use as the next step after executing GoReleaser, I think?

e.g. there is GitHub Action https://github.com/marketplace/actions/slack-notify and I suppose other CIs will have similar integrations?

**Comment by wesleimp** [comment]
@radeksimko sure, you are right, thanks!
