### ISSUE TITLE
Support brew dependency types 

### ISSUE THREAD

**Issue by xenithorb** [goreleaser/goreleaser#1524]
**Is your feature request related to a problem? Please describe.**

Goreleaser doesn't support brew dependency types other than hard dependencies.
Brew also supports types: `:optional`, `:recommended` that could be useful

**Describe the solution you'd like**

The following dependency
```yaml
dependencies:
  - dep1
```
Is currently rendered as: 
```ruby
depends_on "dep1"
```
Inputting a ruby hash requires a yaml block:
```yaml
dependencies:
  - |-
    dep1 => :recommended
```
And is rendered as (not valid ruby):
```ruby
depends_on ""dep1" => :recommended"
```
 **There should be a way to configure and output and render the valid code**:
```ruby
depends_on "dep1" => :recommended
```

**Additional context**

Maybe the list of dependencies could accept a list of hashes with a `type` attribute
```yaml
dependencies:
  - name: dep1
    type: recommended
  - name: dep2
    type: optional
```
outputs
```ruby
depends_on "dep1" => :recommended
depends_on "dep2" => :optional 
```

**Comment by mgrachev** [comment]
I’d like to take it
