### ISSUE TITLE
Consistent versioning for snapshots

### ISSUE THREAD

**Issue by radeksimko** [goreleaser/goreleaser#1532]
**Is your feature request related to a problem? Please describe.**

I'm unsure if this is bug or a feature, but I noticed that for `--snapshot` archives the `.Version` format is different to the standard non-snapshot releases.

```
v0.2.0-SNAPSHOT-906c368
```
vs
```
0.2.0
```

I admit version formatting may not be a huge deal for snapshot builds as they're far less likely to be distributed widely, but it seems inconsistent nonetheless. Relatedly [`.Version` description in docs](https://goreleaser.com/customization/templates/) claims the `v` prefix is stripped, which doesn't apply to the snapshot mode.

This can be an issue if such snapshot versions need to be compared to the "clean" versions in semver or any other sense.

**Describe the solution you'd like**

I think the least disruptive change here could be introducing the following new variables:

 - `.IsSnapshot` (bool)
 - `.RawVersion` (string) - always returning the same format as `.Version` in non-snapshot mode

Then default `ldflags` can be retained for compatibility, but allow more flexible configuration, e.g.

```yml
ldflags:
      - '-s -w -X "version={{ .RawVersion }}" -X "prerelease={{ if .IsSnapshot }}dev{{ end }}"'
```

**Describe alternatives you've considered**

I found `RawVersion` can be done with a just a little verbose construct, but I couldn't find a way to identify snapshot builds.

```yml
ldflags:
      - '-s -w -X "version={{printf "%s.%s.%s" . Major .Minor .Patch }}" -X "prerelease="'
```

**Comment by caarlos0** [comment]
> I admit version formatting may not be a huge deal for snapshot builds as they're far less likely to be distributed widely, but it seems inconsistent nonetheless. Relatedly [`.Version` description in docs](https://goreleaser.com/customization/templates/) claims the `v` prefix is stripped, which doesn't apply to the snapshot mode.

I think this is a bug 🤔



> I think the least disruptive change here could be introducing the following new variables:
> 
>     * `.IsSnapshot` (bool)
> 
>     * `.RawVersion` (string) - always returning the same format as `.Version` in non-snapshot mode
> 
> 
> Then default `ldflags` can be retained for compatibility, but allow more flexible configuration, e.g.

This sounds good to me.

--- 

On a side note, I also started some work adding `inc` functions which I though may be useful, but closed the PR due to lack of feedback... maybe it would help in your case too?  https://github.com/goreleaser/goreleaser/pull/1457
