### ISSUE TITLE
Ability to run uploads on snapshot

### ISSUE THREAD

**Issue by jaxxstorm** [goreleaser/goreleaser#1538]
**Is your feature request related to a problem? Please describe.**
When I'm testing my goreleaser configuration for a project, I have to do the following:

- generate the config
- test some config locally
- then test it in CI

In order to actually do the test in CI, i _have_ to create a tag which then might publish and artifact or upload that artifact to an s3 bucket or whichever other release configs you have.

This is pretty painful during the initial iterations and means lots of mistakes are made

**Describe the solution you'd like**

It would be great if we could have a flag that goes with the `--snapshot` flag, something like `--publish` which allows you to test this configuration and uploads the artifacts to wherever, without adding the latest release tag in Github

**Describe alternatives you've considered**
We could optionally use the new `goreleaser build` mechanism and do the uploads manually, but it defeats the object of using goreleaser :)

**Additional context**
These builds could be used by `homebrew` for its `devel` channel as well

**Comment by caarlos0** [comment]
similar to https://github.com/goreleaser/goreleaser/discussions/1534 maybe?

**Comment by jaxxstorm** [comment]
Yes, similar. Feel free to fold this issue into that one

**Comment by caarlos0** [comment]
this is now available with the `--nightly` flag on goreleaser-pro.

closing

**Comment by sriio** [comment]
@caarlos0 Any chance to get it on oss version ?

**Comment by caarlos0** [comment]
not for now, no.
