### ISSUE TITLE
do not link files on docker pipe

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#1544]
some docker pipe tests are failing with things like:

```
link testdata/Dockerfile /tmp/dockertest011168116/dist/goreleaserdocker212266563/Dockerfile: invalid cross-device link
```

seems to be related to some change in github actions, as goreleaser's code didn't change anything related to this lately.

PS: the docker pipe do some hard links indeed, maybe we should change that to copy instead as it already caused other problems in the past?

PPS: golang does not have a stdlib copy function, maybe use something like, more details https://github.com/goreleaser/goreleaser/pull/355 and https://github.com/golang/go/issues/8868

**Comment by caarlos0** [comment]
refs https://github.com/goreleaser/goreleaser/pull/1545

**Comment by till** [comment]
I just ran into issues with the docker build, and then learned about `extra_files` (which worked! :tada:).

Do you think it's even necessary to setup a build directory and copy/link files into a temporary directory? I can see advantages for everything, but it seems in order to avoid that the image contains unnecessary/unwanted files, `.dockerignore` is more suitable.

**Comment by caarlos0** [comment]
the problem is not dockerignore itself, we do the temp dir thing because, otherwise, the dockerfile would have to `COPY dist/foo_linux_amd64/binary /etc`... and today its just `COPY binary /etc`, which works outside goreleaser as well (`go build . && docker build .`)... 

the linking thing is hacky, ideally we should copy the needed files...

**Comment by till** [comment]
@caarlos0 thanks, I see the reasoning! 👍 

And yeah, maybe a copy is better or less weird on different systems.

**Comment by till** [comment]
Do you have a preference as to what to use:

 - `io.Copy()`,
 - `ioutil.ReadFile()` and `ioutil.WriteFile()`
 - `os.Read()` and `os.Write()`

I am hoping all of them are cross platform? 😂

**Comment by caarlos0** [comment]
`io.Copy` copies from a reader to a writer, we still need to create the target file, and there is where the problems happen... 

check https://github.com/golang/go/issues/8868 and specially Rob Pike's comments on https://go-review.googlesource.com/c/go/+/1591

**Comment by caarlos0** [comment]
(but IMHO we don't need a perfect 100% correct on all platforms in existence copy file, my plan was to copy the one from that CL 🤣)

**Comment by caarlos0** [comment]
Will ignore this for now, as the problem was on github actions and it is working as is for quite some time...

**Comment by caarlos0** [comment]
FWIW: next release will copy the files instead of hard-linking them
