### ISSUE TITLE
`goreleaser init` interactive mode

### ISSUE THREAD

**Issue by kevinjqiu** [goreleaser/goreleaser#1548]
**Is your feature request related to a problem? Please describe.**

The default config is good but it does not guide users through what integrations are possible. I found myself often just copying a .goreleaser.yml file from a previous project.

**Describe the solution you'd like**

A step by step guide that helps users generate a goreleaser config file based on their project needs, e.g.,
- the name of the project
- arch/os combinations to build
- does the project require a docker build
- does the project release its binary on gitlab/github?
- what kind of OS package needs to be build? rpm/deb/brew?
- etc

**Describe alternatives you've considered**

Copy existing config files

**Additional context**

**Comment by caarlos0** [comment]
since no one else showed interest for this, will close as wont-fix, at least for now.
