### ISSUE TITLE
Real world example for authenticated custom publisher with curl or wget

### ISSUE THREAD

**Issue by Obsecurus** [goreleaser/goreleaser#1549]
I’m struggling to get goreleaser to push .deb files to packagecloud.io. I don’t believe the HTTP upload will work because package cloud requires POST to an endpoint with the distribution ID which is their own lookup table. However, I tried to do this with a raw curl command but couldn’t get the authentication to work properly.  

It would be very helpful if the documentation provided a real world example of using custom publisher with curl or wget or even the packagecloud CLI if someone has experience with this.

**Comment by caarlos0** [comment]
I think it autocloses the wrong issue 🤔

**Comment by Obsecurus** [comment]
So I realized my primary issue was the injection of environment variables in the `cmd` section of `publishers`. I instead added my curl command into a script called pkgcloud_push.sh and then just set the `env` section under publishers to be compliant with upload for simplicity.

**pkgcloud_push.sh**
```
#! /bin/bash
repo_owner=$1
repo_name=$2
abs_path=$3
distro_id=$4

curl -s -X POST "https://${API_TOKEN}:@packagecloud.io/api/v1/repos/${repo_owner}/${repo_name}/packages.json" -F "package[distro_version_id]=${distro_id}" -F "package[package_file]=@${abs_path}"
```

**.goreleaser.yml publisher section**
```
env:
      - API_TOKEN={{ .Env.UPLOAD_PACKAGECLOUD_SECRET }}
```

**Comment by caarlos0** [comment]
@Obsecurus nice to see you figured it out!

mind adding that as an example to the docs?

**Comment by tomcruise81** [comment]
I was able to upload to an internally hosted Nexus repository via something like:
```yaml
publishers:
- name: nexus
  cmd: >-
    curl -k -u "{{ .Env.NEXUS_USERNAME }}:{{ .Env.NEXUS_PASSWORD }}"
    -X POST
    -H "Accept: application/json"
    -H "Content-Type: multipart/form-data"
    "https://nexuspro.somehost.com/service/rest/v1/components?repository=go-raw-autopub"
    -F "raw.directory={{ tolower .Env.PROJECT_KEY }}/{{ tolower .ProjectName }}/{{ .Version }}"
    -F "raw.asset1=@{{ .ArtifactName }};type=application/gzip"
    -F "raw.asset1.filename={{ .ArtifactName }}"
  dir: "{{ dir .ArtifactPath }}"
```

Seemed to work just fine.

**Comment by caarlos0** [comment]
Thanks @tomcruise81 , added to docs :)
