### ISSUE TITLE
Add command line arguments

### ISSUE THREAD

**Issue by titpetric** [goreleaser/goreleaser#155]
Hello,

There is one thing lacking from the documentation/README, is it possible to specify the location of the goreleaser.yml with some command line flag? I'd +1 this under features if it doesn't exist yet.

Can work on a PR in the next days if need be.

Best,
Tit

**Comment by titpetric** [comment]
Suggestions:

* `-f [config]` - use custom yml config file location
* `--ignore-changes` - ignore any local git changes (current behavior is `git diff` and exit),

I will add more options as I find a need for them :). As I'm trying to just build the binary in the first place it would be good if this succeds regardless of the state of the git repository. People build software also in development, and why not use the same build method, and then use resulting binaries to create docker images, etc. :) I'll check if there's some setting in the yml config that enables this, but instinct tells me there isn't.

**Comment by caarlos0** [comment]
Hi!

- `-f` is actually `-c`: https://github.com/goreleaser/goreleaser/blob/master/main.go#L31
- `--ignore-changes` can be replaced with `--nr`, which  skips most parts of the process

**Comment by titpetric** [comment]
So, documentation issue. Can the flags be listed with --help or -h, -?, other?

**Comment by caarlos0** [comment]
They are:

```
~
❯ brew install goreleaser/tap/goreleaser
==> Installing goreleaser from goreleaser/tap
==> Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.8.7/goreleaser_Darwin_x86_64.tar.gz
==> Downloading from https://github-cloud.s3.amazonaws.com/releases/77071454/bd321472-1077-11e7-9871-37834a1003b2.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Cr
######################################################################## 100.0%
🍺  /usr/local/Cellar/goreleaser/0.8.7: 5 files, 6.8MB, built in 8 seconds

~ 12s
❯ goreleaser -h
NAME:
   goreleaser - Deliver Go binaries as fast and easily as possible

USAGE:
   goreleaser [global options] command [command options] [arguments...]

VERSION:
   0.8.7

COMMANDS:
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --config FILE, -c FILE                            Load configuration from FILE (default: "goreleaser.yml")
   --build-only, --skip-release, --no-release, --nr  Skip all the release processes and run only the build and packaging steps
   --help, -h                                        show help
   --version, -v                                     print the version

~
❯
```

**Comment by caarlos0** [comment]
`f` for config file alias added on v0.8.8
