### ISSUE TITLE
Add MacPorts support

### ISSUE THREAD

**Issue by b4nst** [goreleaser/goreleaser#1556]
**Is your feature request related to a problem? Please describe.**
Currently there is no specific configuration for MacPorts

**Describe the solution you'd like**
A way to create and publish a Portfile, in the same way as the Homebrew formula

**Describe alternatives you've considered**
Create and upload Portfile with custom scripts.

**Comment by caarlos0** [comment]
Since no one weighted in, I'm assuming not many people want this...

that being said, ["yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion either way.
