### ISSUE TITLE
Generate git tag by commit history using Conversational commits

### ISSUE THREAD

**Issue by tdakkota** [goreleaser/goreleaser#1558]
**Is your feature request related to a problem? Please describe.**
Now user tags release manually.

**Describe the solution you'd like**
But `goreleaser` can use commit history to count version automatically. 
If commits between last tag and `HEAD` contain commit which message contain `fix:` then increase patch version.
If they contain commit which message contain `feat:` then increase minor version.
If they contain commit which message contain `BREAKING CHANGE:` or contains `!` after after the _type_/_scope_ then increase major version.

**Describe alternatives you've considered**
Just continue use manual tagging.  

**Additional context**
Conventional Commits description
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by caarlos0** [comment]
["Yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

There are plenty of other tools that do this already, and if you're looking for a simple one made in go, you can check https://github.com/caarlos0/svu for example.

Thanks for the suggestion either way.
