### ISSUE TITLE
Docker image with cross compilation for OSX, windows, linux

### ISSUE THREAD

**Issue by doodlesbykumbi** [goreleaser/goreleaser#1585]
**Is your feature request related to a problem? Please describe.**

I usually have to create a special cross-compilation image with Goreleaser for automated builds. 
Here's an example https://github.com/cyberark/secretless-broker/blob/master/bin/Dockerfile.releaser. As part of a release I include builds for a variety of targets (e.g. linux amd64, darwin amd64 etc.). 

Without a cross compilation image, I have to have my builds running in separate executors or potentially run some builds locally. This is all a lot more cumbersome than leveraging a linux image that has cross-compilation capabilities (e.g. https://hub.docker.com/r/dockercore/golang-cross/)

**Describe the solution you'd like**

goreleaser currently maintains image tags for the normal goreleaser and gorelease with cgo `v0.137` and `v0.137-cgo`. It would be amazing if the same would be done for an image with cross compilation capabilities. I've provided an example above. That would mean an additional tag for `v0.137` perhaps called `v0.137-crossgo`.

**Describe alternatives you've considered**

I considered maintaining the images myself. This likely means no-one else gets to benefit from this, in part because of discoverability since I'm a random. It also means I have to keep track of goreleaser releases to keep things up to date, which I suspect would be better done here.

**Additional context**

N/A

**Comment by caarlos0** [comment]
this was added to [docs](https://goreleaser.com/cookbooks/cgo-and-crosscompiling), so I'll close this.

Thanks!
