### ISSUE TITLE
Build Only Some IDs

### ISSUE THREAD

**Issue by felicianotech** [goreleaser/goreleaser#1598]
I'd like the ability to build (and optionally release) only some IDs. On a service like CircleCI that offers Linux, macOS, and Windows, I'd want to run GoReleaser 1 time on each to take advantage of native platform compiling due to some CGO needs. Right now I don't have an easy way to do this.

I can see my need solved two ways:

1. Allow GoReleaser a CLI flag to choose which config file to read. This way we can have `.goreleaser.yml` as the default, but I can additional files such as `.goreleaser.windows.yml` or something like that.
2. Another method would be a flag to pass in an ID to specifically build (or not build). With this method, I'd have the normal GoReleaser config file and can pass a CLI flag on each platform to only build that platform.

**Comment by caarlos0** [comment]
>     1. Allow GoReleaser a CLI flag to choose which config file to read. This way we can have `.goreleaser.yml` as the default, but I can additional files such as `.goreleaser.windows.yml` or something like that.

this is already possible.

`goreleaser release --help` should give you all the options.

---

closing

**Comment by felicianotech** [comment]
:disappointed:  Not sure how I missed that. Thank you.
