### ISSUE TITLE
Ambiguous import in 0.138.0 

### ISSUE THREAD

**Issue by jthurman42** [goreleaser/goreleaser#1606]
**Describe the bug**

Multiple projects that we maintain import goreleaser as a tool to easily make it available within the CI/CD pipeline.  After updating to 0.138.0 in [newrelic/newrelic-client-go](https://github.com/newrelic/newrelic-client-go), and then importing newrelic-client-go into [newrelic/newrelic-cli](https://github.com/newrelic/newrelic-cli), we get an ambiguous import issue.

*Note:* This appears to be a common issue with importing `github.com/Azure/go-autorest` as we've seen this in other projects.

Looks like the goreleaser/goreleaser#1599 PR introduced the changing go-autorest changes when updating `gocloud.dev`

**Expected behavior**

Clean import of `github.com/goreleaser/goreleaser` across multiple projects.

**Additional context**

`go mod why github.com/Azure/go-autorest/autorest`:

```
github.com/newrelic/newrelic-cli imports
	github.com/goreleaser/goreleaser imports
	github.com/goreleaser/goreleaser/cmd imports
	github.com/goreleaser/goreleaser/internal/pipe/defaults imports
	github.com/goreleaser/goreleaser/pkg/defaults imports
	github.com/goreleaser/goreleaser/internal/pipe/blob imports
	gocloud.dev/secrets/azurekeyvault imports
	github.com/Azure/azure-sdk-for-go/services/keyvault/v7.0/keyvault imports
	github.com/Azure/go-autorest/tracing: ambiguous import: found package github.com/Azure/go-autorest/tracing in multiple modules:
	github.com/Azure/go-autorest v12.0.0+incompatible (/Users/jthurman/Source/go/pkg/mod/github.com/!azure/go-autorest@v12.0.0+incompatible/tracing)
	github.com/Azure/go-autorest/tracing v0.5.0 (/Users/jthurman/Source/go/pkg/mod/github.com/!azure/go-autorest/tracing@v0.5.0)
```

**Comment by jthurman42** [comment]
There is a longer output for the import issue here: newrelic/newrelic-cli#311

**Comment by caarlos0** [comment]
Tried here:

```
mkdir test && cd $_
go mod init github.com/caarlos0/test
go get -u github.com/goreleaser/goreleaser
```

the problem seems to be with go mods while updating, it tries to keep `github.com/Azure/azure-amqp-common-go/v3` and `github.com/Azure/azure-amqp-common-go/v2` on the `go.sum` file (at least for some time), which causes it to break.

I was able to fix it by removing the goreleaser dep, running `go mod tidy` and then adding it back.

**Comment by caarlos0** [comment]
Will leave this issue open for a while as it may happen to more people...

**Comment by caarlos0** [comment]
also refs https://github.com/google/go-cloud/pull/2799

**Comment by caarlos0** [comment]
Will close as no one else had this issue and its fixed on newrelic's repo (https://github.com/newrelic/newrelic-client-go/pull/356)
