### ISSUE TITLE
releaser to brew as a develop version

### ISSUE THREAD

**Issue by codeskyblue** [goreleaser/goreleaser#161]
Now, publish need to make a tag. What if some one want to install the develop version? What should I do?

**Comment by caarlos0** [comment]
you mean, download and compiling the master branch on the users machine?

**Comment by codeskyblue** [comment]
I mean compile master branch on travis

**Comment by caarlos0** [comment]
hmm, As far as I have seen out there, dev versions of formulaes usually are compiled in the users machine. The recipe have to define dependencies versions and all that... do you have an example of formula that works in the way you want? just so we can see how hard it is to implement it....
