### ISSUE TITLE
Upload checksums for binaries produced

### ISSUE THREAD

**Issue by esiqveland** [goreleaser/goreleaser#162]
It would be nice if `gorelease` would also publish signatures or checksums, of the binaries produced.

**Comment by caarlos0** [comment]
Nice suggestion! Would be glad to see a PR with that =D

**Comment by esiqveland** [comment]
I think this should be two features then. One for checksums (easy) and one for signatures (harder, requires config).

After having a look around it should be possible to make checksums as a pipe, and then either upload checksum files as artifacts or include the checksums in the release description text. Or ideally both.

I think checksums should be done first as it is easier to implement and gives much of the value.

What do you think about that?

**Comment by esiqveland** [comment]
I have two suggestions for this. One is checksumming the bundled archives, and one is checksumming each file produces, and including this checksum inside the archive. I think I like the first approach better as it lets you check the archive before unpacking it, which might not even work if the archive is corrupt.

This means I am scrapping this approach.
Getting the checksums to be uploaded during the release phase is a bit trickier and doesn't really work with how the release pipe is coded now, as it tries to guess the final path of each file to upload using a fixed format.

On another note, I found this TODO: https://github.com/goreleaser/goreleaser/blob/master/pipeline/release/release.go#L58

Such a list of files to upload would be very helpful for this feature.

**Comment by caarlos0** [comment]
@esiqveland yeah, the first approach seems to make more sense to me.

Just need to be careful to not breadk th ability to run goreleaser multiple times, as dicussed in #49.
It should be simple, just append to file and the second time goreleaser is ran it should update the checksums file, which will then contain the checksums for all the binaries produced...

**Comment by caarlos0** [comment]
I just fixed that TODO. Moving to the Checksumming now

**Comment by esiqveland** [comment]
Alright, you can see my suggestion here:
https://github.com/goreleaser/goreleaser/pull/169
