### ISSUE TITLE
Deletes existing release notes on Gitea

### ISSUE THREAD

**Issue by ViRb3** [goreleaser/goreleaser#1624]
I have a project set up with Gitea where I first run semantic-release to create a tag and make a release with the release notes, and then run goreleaser on that tag to build and upload the artifacts. In my `.goreleaser.yml`, I have the following setting:
```yml
changelog:
  skip: true
```
However, when the artifacts are uploaded, the original release notes are still deleted, and the result is just empty release notes.

**Comment by caarlos0** [comment]
changelog.skip skips the changelog text only, there is no way to disable editing the release body.

in your case you probably don't have any docker images as well, if you had, the release body would not be empty (would have the image list instead).

So, not really a bug, but maybe the docs could be better. Will work on that.

Thanks!
