### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#163]
I get the "curl" variant, but it should really say something about how to install the binary locally in the quick start.

**Comment by caarlos0** [comment]
On OSX, you can `brew install goreleaser/tap/goreleaser`, on other platforms a `go get` should work...

**Comment by bep** [comment]
`go get` does not work as there are dependency management involved.

**Comment by bep** [comment]
But it isn't that important.

**Comment by caarlos0** [comment]
@bep indeed... I guess the contributing.md guide covers that though...
