### ISSUE TITLE
ability to add fields to templates

### ISSUE THREAD

**Issue by rbonthond** [goreleaser/goreleaser#1639]
it would be nice if we could add custom fields to the name templates, so they can be referenced later

```
templates:
  foo: bar

project_name: acme-{{.foo}}
```

**Comment by caarlos0** [comment]
you can use environment variables for that:

```yaml
project_name: 'acme-{{ .Env.FOO }}'
```

other than that, I don't really see the point in having this... can you share your usecase?

**Comment by rbonthond** [comment]
using enviroment variables would work. I have a lot of duplicated names etc between various declarations in gorelease.yml that could be centralized via these custom template fields. By using custom template fields instead of environment variables everything is contained inside the goreleaser.yml without having to depend on the correct shell setup.

**Comment by caarlos0** [comment]
repeating some names is not a problem IMHO, at least the configuration is clear...

if really want complex templating, you can use something like jsonnet as well (given that its json output should be also a valid yaml)... 

that being said, ["yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion either way.

**Comment by rbonthond** [comment]
ok thank you.
