### ISSUE TITLE
Log build hook stdout

### ISSUE THREAD

**Issue by radeksimko** [goreleaser/goreleaser#1646]
**Is your feature request related to a problem? Please describe.**

If a pre or post build hook is taking longer to finish it would be helpful to see the progress and understand what is it doing.

**Describe the solution you'd like**

Log output the same way as output from publishers is logged:

https://github.com/goreleaser/goreleaser/blob/2522771bd05e67e8a110196e2c575b9fa4511183/internal/exec/exec.go#L68-L69

**Additional context**

stdout is only displayed alongside stderr on error at the moment:

https://github.com/goreleaser/goreleaser/blob/2522771bd05e67e8a110196e2c575b9fa4511183/internal/pipe/build/build.go#L204-L218

**Comment by caarlos0** [comment]
Sounds good!
