### ISSUE TITLE
Upload signatures for binaries produced

### ISSUE THREAD

**Issue by esiqveland** [goreleaser/goreleaser#166]
Create and upload signatures for the binaries (or all files) produced.

This will probably involve some kind of config for signing key or method, like PGP for creating the signatures.

**Comment by caarlos0** [comment]
hi @esiqveland , I don't remember seeing a project with this kind of thing... can you point some, so I can see how they do it?

**Comment by esiqveland** [comment]
I was trying to think of the same thing, and I know I have seen it before, but I couldn't come up with any good examples!

I know some publish signatures for their artifacts in the java (maven) eco-system, as well as most linux distributions publish signatures for their packages so they can be verified before installing.

I'll see if I can come up with something better.

**Comment by caarlos0** [comment]
Yeah, I kind of remember have seeing something like that somewhere, don't remember where though 😆

**Comment by esiqveland** [comment]
Some examples:

Maven Plugin: http://maven.apache.org/plugins/maven-gpg-plugin/

Debian: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

Didn't have more time to look further into it right now!

**Comment by caarlos0** [comment]
hmm, so, basically, call `gpg --armor --detach-sign` for each artifact and upload the `artifact.asc` file...

**Comment by esiqveland** [comment]
Yes, so if it is gpg based, one would probably have to configure the key id to sign with.
This should be your gpg publish key id.

I think there is a lib for go that could do this signing, so it doesn't have to depend on gpg executable.

**Comment by blacktop** [comment]
https://keybase.io would integrate nicely

**Comment by esiqveland** [comment]
I believe https://godoc.org/golang.org/x/crypto/openpgp would serve this nicely.

**Comment by magiconair** [comment]
FWIW, I'm signing the checksum file with GPG for https://github.com/fabiolb/fabio. I'm looking into using goreleaser now since it's super useful but that's missing. I can work around this though until the feature is there.
