### ISSUE TITLE
Add "restart-condition" support to Snapcraft builds

### ISSUE THREAD

**Issue by ameshkov** [goreleaser/goreleaser#1664]
**Is your feature request related to a problem? Please describe.**
Snaps support it: https://snapcraft.io/docs/snapcraft-yaml-reference

`apps.<app-name>.restart-condition`
Condition to restart the daemon under.

However, we cannot set it using goreleaser.

**Describe the solution you'd like**
Add support for this field.

**Describe alternatives you've considered**
Building snaps manually.

**Comment by caarlos0** [comment]
can you check if #1837 does what you need?

**Comment by ameshkov** [comment]
Yes, thank you

**Comment by caarlos0** [comment]
merged, thanks!
