### ISSUE TITLE
Support for nix flakes (investigating)

### ISSUE THREAD

**Issue by blaggacao** [goreleaser/goreleaser#1681]
- goreleaser is a powerful trend setter.
- many go packages are still not available to the nix package manager

Although it's trivial to package go modules (or packages), factoring open source dynamics into the equation, it is _even more trivial_ for goreleaser to enable - currently only -  github or gitlab repos to become a discoverable and nix-installable `flake`.

All that's needed is to commit two files to the root of the repository upon a release:
- `flake.nix`
- `flake.lock` (done automatically by `nix build`) -> later updates `nix flake update` (but almost never needed or even desirable - sic!)
```nix
{

    description = "Kubernetes object analysis with recommendations for improved reliability and security";

    inputs.flake-utils.url = "github:numtide/flake-utils";

    outputs = { self, nixpkgs, flake-utils }:
        flake-utils.lib.eachDefaultSystem (system:
            let pkgs = import nixpkgs { inherit system; }; in
            rec {
                packages.kube-score = pkgs.buildGoModule {
                    name = "kube-score";
                    src = self;
                    vendorSha256 = "sha256-COY4AonAvJhH+io6Z7I9CsK1pnsK/Yi248QMkVPK6u0=";
                };
                defaultPackage = packages.kube-score;
                apps.kube-score = flake-utils.lib.mkApp { drv = packages.kube-score; };
                defaultApp = apps.kube-score;
            }
        );
}
```

In the details is the autogenerated lockfile, since a typical go package would only ever have the `buildGoModule` input requirement, this might change once in five years. 
<details>

```json
{
  "nodes": {
    "flake-utils": {
      "locked": {
        "lastModified": 1594123299,
        "narHash": "sha256-zxjtMmOV93pIVG242RpEXu14w/13XYDo3ygMoRIJg4c=",
        "owner": "numtide",
        "repo": "flake-utils",
        "rev": "590d6d1badea1956a31480a0cba1d8d029cf45d3",
        "type": "github"
      },
      "original": {
        "owner": "numtide",
        "repo": "flake-utils",
        "type": "github"
      }
    },
    "nixpkgs": {
      "locked": {
        "lastModified": 1595039835,
        "narHash": "sha256-yt9utM5EEjfz0sEip6c0HHY0f0YCfUjQbWOMhrVgSmo=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "0ae51edb29dc6aa5f86c1e3686047032818af089",
        "type": "github"
      },
      "original": {
        "id": "nixpkgs",
        "type": "indirect"
      }
    },
    "root": {
      "inputs": {
        "flake-utils": "flake-utils",
        "nixpkgs": "nixpkgs"
      }
    }
  },
  "root": "root",
  "version": 7
}
```
</details>

***The only tricky thing for `goreleaser` is to update the `vendorSha256` hash: every time the (virtual) vendored folder (by go modules) presents changes a new hash need be calculated and replaced in there.***

I hope this is doable and in the interest of goreleaser to support releases for the majority of platforms within the go ecosystem.

Compared to #957 - you have to think unorthodoxically about the term "release". The caller tags the release on the github revision directly (ever since a flake.nix + flake.lock was present): `nix shell github:zegl/kube-score/v1.7.2`.

So let's hurry up, it's coming anyway :stuck_out_tongue_winking_eye:

**Comment by blaggacao** [comment]
It really boils down to updating this `vendorSha256` once those two files a present. Go packages are slightly different, but neither too much.

**Comment by blaggacao** [comment]
How to deal with such thing?
https://github.com/zegl/kube-score/commit/38fef1ec7188ea126b755f621bdcaf45c3a8f88a#diff-0c20a60747c8ad538c1ad4fa249a1a9fR7-R10

**Comment by blaggacao** [comment]
@caarlos0 I'd like to make opinions from the nix community members discoverable to you: https://discourse.nixos.org/t/lets-nudge-for-goreleaser-nix-flakes-support/8186

(Please don't get offended by the rethorically provocative title ;-)

The geberal opinion is: it might be a bit early, still, since nix flakes are still experimental.

On the other hand using github and gitlab as decentralized registry + widespread adoption (the intention behind this issue) would make this the most up to date package distribution system yet to be seen (one essentially can tag any git commit / fork / branch just naturally).

If you prefer to avoid long running issues, let's close this. However, I'd like to invite you to explore this concept (which is praised by knowledgable people I respect) and familiarize with thenparadigm shift of.software distribution and if goreleaser could be a valid vehicle into the go ecosystem:

A lot of go tools are command line tools: with nix companies (such as allegedly shoppify - judging by some job offer thread in the nix community) can prepare 100% reproducible shell environments and distribute them safely for their developpers (think of it as _the end of life of setup instructions_). Beeing able to access a wide variety of go packages by shifting the gravitational center of software distribution with regard to nix on a shared middle ground would help this promising nix' use case prosper.

(And make the software world a better place.)

**Comment by caarlos0** [comment]
So, if I get this right, your idea would be to use goreleaser to generate nix flakes, which if the user install, would compile the binary on their machine. Is that correct?

If so, seems like the reverse of what we try to do with goreleaser: always ship the binaries. Can a flake install a precompiled binary? Also, can I generate the lock file and etc without installing nix (in pure Go)?

> The general opinion is: it might be a bit early, since nix flakes are still experimental.

I tend to not add experimental things into goreleaser (e.g. docker manifest stuff)...

**Comment by blaggacao** [comment]
> So, if I get this right, your idea would be to use goreleaser to generate nix flakes, which if the user install, would compile the binary on their machine. Is that correct?

That is the first step. It is correct.

> If so, seems like the reverse of what we try to do with goreleaser: always ship the binaries. Can a flake install a precompiled binary? 

Yes. Flake maintains zone local caches. In other words the typical use case is that it is once decentrally built within a zone and then zone-locally distributed through a build cache.

In conclusion, it has two facets. At source it is about distributing build instructions. At target it is about consuming binaries.

> Also, can I generate the lock file and etc without installing nix (in pure Go)?

I don't think thats currently possible. But since you asked I'd like to query @ecolstra opinion on that as the intelectual patron of flakes and creator of nix.

> I tend to not add experimental things into goreleaser (e.g. docker manifest stuff)...

Concluding this issue, I would agree that it's too early. Still, I appreciate your mind share and awareness. As flakes ripen, the nix community has a vested interest in acquiring support from releaser tools.

**Comment by caarlos0** [comment]
> Yes. Flake _can_ maintain zone local caches. In other words the typical use case is that it is once decentrally built within a zone and then zone-locally distributed through a build cache.
> 
> In conclusion, it has two facets. At source it is about distributing build instructions. At target it is about consuming binaries.

this seems like what we have today with Brew core vs taps: we generate taps (that use the binary goreleaser compiles), but we don't do anything about brew core (which compiles the binary from source and caches it).

not sure if that's a valid parallel, but if it is, maybe its not worth adding to goreleaser.

GoReleaser doesn't know anything about the projects deps, for example, it assumes they are available (otherwise `go build` actually handles it), but it doesn't do anything with `vendor` folders, `go.mod`, and etc...

**Comment by blaggacao** [comment]
I see your point. I think your perspective as a packaging-multiplier actor and my perspective as an end consumer of "releases" combined, is valuable feedback to the evolution of flakes.

It is still a young concept, and I hope this discussion is one marginal brick informing the future evolution of flakes better.

Since you offload the _how_ of the build to _a_ tooling (`go` in this case), flakes would have to provide an offloading mechanism as well.

If I look at it from that angle, we should conceive a `flake-gen` that supports different language frameworks, with `go` among them and that also provides go bindings for your consumption.

If that is what we need, then we now have clarity at the very least. ;-) Thank you!

**Comment by caarlos0** [comment]
> If I look at it from that angle, we should conceive a `flake-gen` that supports different language frameworks, with `go` among them and that also provides go bindings for your consumption.

that seems like a good idea... I know the brew-core team has some sort of automation as well, not for generating formulas, but for updating them automatically when new releases are out... and it seems to work OK (at least looking as an outsider).

Thanks :)

**Comment by caarlos0** [comment]
For now, closing as 'wont fix'.

**Comment by caarlos0** [comment]
fwiw, we are investigating this again in #3537
