### ISSUE TITLE
Add different files to archives based on OS

### ISSUE THREAD

**Issue by jaxxstorm** [goreleaser/goreleaser#1708]
**Is your feature request related to a problem? Please describe.**
I'm building a project which I need to add some scripts to the archive when it's built. The files are different depending on the OS, for example, for Linux builds I need to add `do-some-stuff.sh` and for Windows builds I need that to be `do-some-stuff.cmd`

Currently, the files added to the archive are global.

**Describe the solution you'd like**
Ideally I'd like to be able to specify the extra files added based on the OS

**Describe alternatives you've considered**
Could this be achieved with hooks, maybe?

**Comment by caarlos0** [comment]
you can define multiple archives, one for each os, with their specific hooks.

its a bit repetitive but its clear and should work I think 🤔

**Comment by jaxxstorm** [comment]
@caarlos0 how do you specify an archive per-os? I couldn't see a way to specify the `GOOS` in the archive struct:
https://github.com/goreleaser/goreleaser/blob/master/pkg/config/config.go#L261-L270

Only the build ID. Would I need a specific build id for each OS in that case?

**Comment by caarlos0** [comment]
> Only the build ID. Would I need a specific build id for each OS in that case?

yes...

**Comment by caarlos0** [comment]
Closing as the multiple builds/archives probably fixed it.
