### ISSUE TITLE
Run before pipe after semver pipe

### ISSUE THREAD

**Issue by ryancurrah** [goreleaser/goreleaser#1710]
**Is your feature request related to a problem? Please describe.**
When using the global hook/before pipe I need to be able to echo the version to a file but that information is not available yet because the semver pipe runs after the before pipe.

**Describe the solution you'd like**
Change the ordering of the pipes so that git and semver template variables are available to the before pipe.

**Additional context**
https://github.com/goreleaser/goreleaser/blob/master/internal/pipeline/pipeline.go#L40-L43

**Comment by caarlos0** [comment]
fixed in #1711

**Comment by ryancurrah** [comment]
Thank you!
