### ISSUE TITLE
HTTP uploads extra files (or custom archives)

### ISSUE THREAD

**Issue by abeMedia** [goreleaser/goreleaser#1716]
Right now I'm using build hooks to build MSI files for Windows and DMG files for Mac. This all works great, however the resulting files cannot be uploaded using GoReleaser's `uploads` feature so I'm using curl commands in another hook.
It would be really great if we could specify an `extra_files` property for HTTP uploads, just like we do for `blobs` and `releases`.

Another (probably more versatile) solution would be to allow custom archives. This could work very similar to signing in that we have a `cmd` property for the command that builds it and a `name_template` field for the resulting name. This would allow specifying the `id` of that archive in any further build step, treating the outputted file just like any other archive.

**Comment by caarlos0** [comment]
since the time of the issue, [custom publishers](https://goreleaser.com/customization/publishers/) were introduced... maybe you can solve this problem with it?
