### ISSUE TITLE
Do not overwrite latest docker tag with older release

### ISSUE THREAD

**Issue by FUSAKLA** [goreleaser/goreleaser#1723]
**Is your feature request related to a problem? Please describe.**
Hi, not sure if feature request or bug but when using the `latest` tag in docker build and releasing for example newer patch version of older minor release but newer minor release has already been released, the `latest` docker tag will get overwrited by older minor version. Same for tag with only major version will get overwrited by older version. 

**Describe the solution you'd like**
Extend the `skip_push: auto`  to compare with already present tags in the repo and if newer is present, skip it's release. Also it would be necessary to have this option for each imate tag template. 

**Describe alternatives you've considered**
Maybe some name template function or templating would be also possilbe to use?

**Comment by caarlos0** [comment]
> Extend the `skip_push: auto` to compare with already present tags in the repo and if newer is present, skip it's release. Also it would be necessary to have this option for each imate tag template.

I don't see a way of doing this without being registry-specific with APIs et al... or loop through tags and `pull` them to see if they exist... if so, I think its not something we should do.

**Comment by FUSAKLA** [comment]
I did not mean searching through the container registry tags but in the git repository. 
Or some other way to tell that this is not the "latest" version so not to overwrite it.

**Comment by caarlos0** [comment]
We can't be sure that a tag that exists on the git repo exists on docker repo as well... the user might change configs and etc...

**Comment by FUSAKLA** [comment]
Ok, so this is out of scope of goreleaser? f so I'd suggest removing the example with releasing only major version tag or at least add warning about this behavior. 

Or can you think of any other solution? I'd be glad for any idea, right now I can't think of a way how to avoid this behavior.

**Comment by caarlos0** [comment]
> Ok, so this is out of scope of goreleaser?

IMHO, yes.


> f so I'd suggest removing the example with releasing only major version tag or at least add warning about this behavior.

can you open a PR to the docs improving this?

> Or can you think of any other solution? I'd be glad for any idea, right now I can't think of a way how to avoid this behavior.

no idea...

**Comment by caarlos0** [comment]
closing as this will not be implemented on goreleaser.
