### ISSUE TITLE
Customizable version

### ISSUE THREAD

**Issue by robvadai** [goreleaser/goreleaser#1751]
We include a build number in our semantic versions making it 4 digits instead of 3.

Example: our app is on version 1.2.3
- the first time we build it we release it as tag 1.2.3.0
- if there are no code changes but the CI tool is triggered a build, tag 1.2.3.1 is produced
- subsequent builds will get the last number automatically increased

**Describe the solution you'd like**
I'd like to have a parameter in the `.goreleaser.yml` file to customise the version (Git tag) format

**Describe alternatives you've considered**
Goreleaser will simply fail if a Git tag is not on a x.y.z format so there are no alternatives really

**Comment by caarlos0** [comment]
The version is get from git, however, you could use `{{ .Version }}.{{ .Env.INC }}` in the templates and then manually `export INC=$(something)` before running goreleaser.

Check `dist/config.yaml` to see all templates you might want to change.
