### ISSUE TITLE
Add support for homebrew HEAD installations

### ISSUE THREAD

**Issue by nesl247** [goreleaser/goreleaser#1772]
**Is your feature request related to a problem? Please describe.**
Add support for `brew install --HEAD $formula`. This allows users to install the version from master.

**Additional context**
https://docs.brew.sh/Formula-Cookbook#unstable-versions-head

**Comment by mgrachev** [comment]
I'd like to do it if nobody minds 🙂

**Comment by caarlos0** [comment]
please go ahead
