### ISSUE TITLE
Prevent archive creation if platform isn't supported

### ISSUE THREAD

**Issue by travisgroth** [goreleaser/goreleaser#1780]
**Is your feature request related to a problem? Please describe.**

We currently have two builds (`app` and `app-cli`), and one of them(`app`) supports only a subset of platforms.  Currently the `app` archive is configured to contain both builds, and the `app-cli` archive contains just the cli build.  The problem we're seeing is that the `app` archive is generated containing only the `app-cli` binary for platforms where `app` is not built.  This leads to some user confusion as there are archives which appear to be missing a binary.

**Describe the solution you'd like**

There's two ways that jump out at me to help with this:

1. Add a goos/goarch parameter to the archives pipe so that it is only attempted for certain targets.  This would work just like the build options.
2. Have a way to tell the archives pipe to skip if binaries for all builds aren't found

There's probably additional permutations of those that would work.  Something like (1) seems more natural to me.

**Describe alternatives you've considered**
We could redo our approach to packaging, but I thought maybe this feature would be useful for others.

**Additional context**
N/A

**Comment by caarlos0** [comment]
I think its probably better to fail if there are different binary counts for each target, forcing the user to specify the archives in those cases... 🤔

**Comment by dlemel8** [comment]
Hey @caarlos0 , can you guide me a bit how to resolve this? 
I want to do this.
Thanks.

**Comment by caarlos0** [comment]
On code itself I don't know yet... I'll need to take a deeper look...

**Comment by caarlos0** [comment]
was easier to do than to explain, done on #1841
