### ISSUE TITLE
GitHub Container Registry

### ISSUE THREAD

**Issue by hazcod** [goreleaser/goreleaser#1783]
**Is your feature request related to a problem? Please describe.**
Hosting Docker containers should be done now on the GitHub Container Registry instead of GitHub Packages since it supports the full spec. (pulling images by digest etc..)

https://github.blog/2020-09-01-introducing-github-container-registry/

**Describe the solution you'd like**
https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images

**Comment by radeksimko** [comment]
Given that it's the config which defines the registry URL, do you mind expanding on what more needs to be done in GoReleaser to support this?

**Comment by hazcod** [comment]
Good point @radeksimko , I suppose only https://github.com/goreleaser/goreleaser/blob/bc940a90529ac9f6cf42c41081ae14a6534dcf2d/scripts/entrypoint.sh#L19

**Comment by caarlos0** [comment]
FWIW, if you use our github action or run the goreleaser binary directly, you should already be able to use ghcr without any issues... 

PR #1784 adds ghcr.io login to the docker image as well.

**Comment by caarlos0** [comment]
done on #1784
