### ISSUE TITLE
Alternative builders?

### ISSUE THREAD

**Issue by arlaneenalra** [goreleaser/goreleaser#1787]
Feature Request:

Is there any appetite for adding non-go builders to goreleaser?  I've noted that there is code in https://github.com/goreleaser/goreleaser/blob/master/pkg/build/build.go#L17-L27 that looks like it is designed to support other potential builders, though there is only a golang implementation.

**Describe the solution you'd like**

What I'm looking for is the addition of a builder that can call a generic build command, be it make or some other form of shell script. That produces a known output. It would be possible to implement this by pull code from the existing golang implementation into a common package and adding new implementations for just a few of the methods.

**Describe alternatives you've considered**

I looked at https://medium.com/@jondot/shipping-rust-binaries-with-goreleaser-d5aa42a46be0 but it seems to require several hoops that seem largely unnecessary and easily circumvented with a few modifications that appear to have already been planed. (Or at least thought of at one point.)

**Additional context**
This could easily provide and alternative to a feature I had asked about (https://github.com/goreleaser/nfpm/issues/203 work account vs personal.) a while back. 

I'm willing to take a shot at the actual implementation should there be any interest.

**Comment by caarlos0** [comment]
Yes, there was an idea to add multiple builders, but everything on goreleaser was made with go in mind, so its way more complicated than it looks.

To be honest, I don't think this will happen anytime soon.

There a are a few issues about this already, you may get more context from them if you want, but for now, I'll close this one as well.

Thanks for the suggestion anyway.
