### ISSUE TITLE
Have you considered making goreleaser support openwrt Linux's ipk package?

### ISSUE THREAD

**Issue by IoTServ** [goreleaser/goreleaser#1788]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
[OpenWRT](https://openwrt.org) use [.IPK](https://downloads.openwrt.org/snapshots/packages/x86_64/packages/) package.
Have you considered making goreleaser support openwrt Linux's ipk package?
**Additional context**

**Comment by caarlos0** [comment]
There are a lot of formats we don't support, so for now we are focusing on the most common ones only, and, since ["yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), I rather not do this right now.

Thanks for the suggestion either way.
