### ISSUE TITLE
Version is empty on --nr flag

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#179]
Latest version, built from source.

**Comment by caarlos0** [comment]
yep, --nr skip a lot of things, including the git pipe, which discovers the version.


Check https://github.com/goreleaser/goreleaser/pull/136

I personally don't even like the `--nr` flag :P

**Comment by bep** [comment]
Well, it is handy while testing your release process.

**Comment by caarlos0** [comment]
Yeah, the problem is that `--nr` is supposed to generate dev build, so maybe there isn't even a tag or the current branch is dirty, in which case it would break.

Also, it can be ran against a folder which isn't even a git repo.

**Comment by bep** [comment]
Maybe another flag, then -- but I don't see who will use goreleaser for "dev builds" (whatever that is).

**Comment by caarlos0** [comment]
@bep, I didn't even wanted to add that flag in the first place.

I guess I'll improve this a little, maybe add a `--validate=false` option and each pipe can deal with it as they wish, will make the code better probably too.

**Comment by caarlos0** [comment]
please check #182 and let me know what you think...

**Comment by bep** [comment]
Yea, that makes more sense.
