### ISSUE TITLE
Add changelog output options [Prepend, Override, Append, Skip]

### ISSUE THREAD

**Issue by MarvinJWendt** [goreleaser/goreleaser#1791]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is that the release notes won't be updated if there's already something in it.

**Describe the solution you'd like**
There could be an option in the configuration to either override, prepend or append the changelog (or don't show it at all), if there's already text in the release notes.

In my case I would like to override the notes, as another action writes a changelog to it, but I would like to use the changelog made by goreleaser.

**Comment by caarlos0** [comment]
refs #1830 

I think this can be done, but I'm not sure where this option should go (hence #1830)...

**Comment by caarlos0** [comment]
Duplicates #1384
