### ISSUE TITLE
Default value for env variables

### ISSUE THREAD

**Issue by 0xjac** [goreleaser/goreleaser#1795]
**Is your feature request related to a problem? Please describe.**
If I define an environment variable in the `env` section. It cannot be overridden and itself overrides an existing value.
I have the following config:
```yaml
snapshot:
  name_template: "{{.Tag}}-{{.Env.SNAPSHOT_NAME}}-{{.ShortCommit}}"
```
In our CI we define `SNAPSHOT_NAME=staging` or `SNAPSHOT_NAME=prerelease`.
When working locally, a dev will have to call `SNAPSHOT_NAME="dev" goreleaser build --snapshot`

**Describe the solution you'd like**
I would like the option to define a default value for an `env` variable in the config file. Something like:

```yaml
defaults:
  - SNAPSHOT_NAME="dev"
```
such that:
- when calling `goreleaser build --snapshot`, `SNAPSHOT_NAME` resolves to `dev`
- when calling `SNAPSHOT_NAME="custom" goreleaser build --snapshot`, `SNAPSHOT_NAME` resolves to `custom`

**Describe alternatives you've considered**
I tried playing with the template and defining:
```yaml
name_template: "{{.Tag}}-{{if .Env.SNAPSHOT_NAME}}{{.}}{{else}}dev{{end}}-{{.ShortCommit}}"
```
But that doesn't work since the template has the [option `missingkey=error`](https://github.com/goreleaser/goreleaser/blob/a92774f602331c53cd6b2c3c3ec8ec9058a26a7f/internal/tmpl/tmpl.go#L161) Bash substitutions for default variables (`${SNAPSHOT_NAME:=default}`) are also ignored

**Additional context**
None

**Comment by caarlos0** [comment]
GoReleaser's envs are already a bit messy, IMHO this should be handled by the caller, not by goreleaser.

GoReleaser is not a CI, its meant to be run as a step in it.

cc/ @radeksimko I remember that discussion we had somewhere about envs et al... I'm starting to think we should remove the root `env` and leave only the per-step env. Global envs would need to be passed by the caller (e.g. `FOO=bar goreleaser`), which IMHO makes more sense and then we don't need to handle security of those things (like that other issue in which someone wanted to commit secrets to the root `env`). WDYT?

**Comment by caarlos0** [comment]
check #1831

**Comment by radeksimko** [comment]
> IMHO this should be handled by the caller, not by goreleaser.

I agree.

I'll comment on #1831 there.

**Comment by 0xjac** [comment]
> IMHO this should be handled by the caller, not by goreleaser.

Maybe I wasn't clear. When running on the CI, the variable is correctly set by the caller.

However if testing/building locally, the build fails because the environment variable is not defined. Defining a default/fallback avoid the pain of running the command without the envvar, let goreleaser fail, then run it a second time with the envvar.

It is also important for reproducible builds. One can clone the source and reproduce a build correctly without having to check the CI for some value. (On the other hand the CI can change a value for specific builds, such as for testing.)

**Comment by caarlos0** [comment]
the root env section now accepts templates, which means you can do the defaulting with them.

added tests & docs for it, so, closing this issue.

thanks!
