### ISSUE TITLE
Support referencing directly the Gitlab project ID in a hosted gitlab deployment to allow releases on nested subgroups

### ISSUE THREAD

**Issue by mattiarossi** [goreleaser/goreleaser#1799]
Hosted Gitlab instances (all levels, CE and Enterprise) support organising repositories in a group/subgroup hierarchy.

Subgroups are accessible through the standard Interface as:
https://gitlab.mycompany.com/Group/SubgroupLvl1/SubgroupLvl2/myproject

Unfortunately, there's no direct way to access a repo residing under a nested subgroup with a single API cal, E.G, calling the API with
https://gitlab.mycompany.com/api/v4/projects/Group/SubgroupLvl1/SubgroupLvl2/myproject will give a 404 error, so the current version of ocireleaser does not support it

The current approach suggested by the Gitlab devs for accessing a project nested under subgroups is to use the API to walk the group/subgroup tree to the leaf, get the project internal ID, and use that when accessing the api/v4/projects/ REST endpoint
This would require adding some logic to the gitlab release config to indicate we're using a subgroup and it would require to implement the tree walk in order to get to the project id

A workaround that does not require modifications to the current config would be to use the project id directly as in:

```
release:
  # Name has to be configured with the project's GITLAB ID
  gitlab:
    owner: ""
    name: 62
```
This 'almost works' straight away, but the current logic for building the API url assumes the "owner" field will always have a value and adds an additional (urlencoded) slash to the path, that causes the actual API call to fail:

Goreleaser error:
```
  ⨯ release failed after 12.05s error=github/gitlab/gitea releases: failed to publish artifacts: GET https://gitlab.mycompany.com/api/v4/projects//62/releases/v1.0: 404 {message: 404 Project Not Found}
```

Gitlab API logs:
```
{"time":"2020-09-08T08:33:48.811Z","severity":"INFO","duration_s":0.05479,"db_duration_s":0.01603,"view_duration_s":0.03876,"status":404,"method":"GET","path":"/api/v4/projects/%2F62/releases/v1.0","params":[],"host":"gitlab.mycompany.com","remote_ip":"XXXXXXXX, 127.0.0.1","ua":"go-gitlab","route":"/api/:version/projects/:id/releases/:tag_name","user_id":25,"username":"gitlab-ci-gorelease","queue_duration_s":0.017381,"redis_calls":1,"redis_duration_s":0.00033,"redis_read_bytes":163,"redis_write_bytes":35,"redis_cache_calls":1,"redis_cache_duration_s":0.00033,"redis_cache_read_bytes":163,"redis_cache_write_bytes":35,"correlation_id":"cSVp6WeCAe2","meta.user":"gitlab-ci-gorelease","meta.caller_id":"/api/:version/projects/:id/releases/:tag_name"}
```

My proposal is to allow an empty owner field in the configuration file, and change the API url composing logic to ignore the field when it's empty, e.g:

in Gitlab.go, line 200, change
```
projectID := ctx.Config.Release.GitLab.Owner + "/" + ctx.Config.Release.GitLab.Name
```

to 
```
projectID := ctx.Config.Release.GitLab.Name
if (ctx.Config.Release.GitLab.Owner != ""){
  projectID = ctx.Config.Release.GitLab.Owner + "/" + projectID
}
```

If needed, I would be able to provide a pull request
```

**Comment by thynquest** [comment]
Hello there 
Any news about this feature  #1801  ? I have the same problem with my hosted gitlab instance
thank you for your help

**Comment by thynquest** [comment]
Btw the same problem appears on the `Upload` method in gitlab.go line 286
`projectID := ctx.Config.Release.GitLab.Owner + "/" + ctx.Config.Release.GitLab.Name`

**Comment by caarlos0** [comment]
the only news we have are on the referenced PR: https://github.com/goreleaser/goreleaser/pull/1801

**Comment by 56KBs** [comment]
I believe this has been resolved in GitLab - I have tested the `/projects` api when using a nested subgroup in the form `group/subgroup1/subgroup2/myproject`, this functions as expected when it is URL encoded. Tested on version 13.7.3 of GitLab

**Comment by caarlos0** [comment]
ok, will close then.

cc/ @mavogel
