### ISSUE TITLE
support releasing to private krew (kubectl plugins) index

### ISSUE THREAD

**Issue by joemiller** [goreleaser/goreleaser#1819]
**Describe the solution you'd like**

As my ❤️  for goreleaser knows no end, I would like to be able to use it to automate the release of kubectl plugins to a private [krew](https://github.com/kubernetes-sigs/krew) index. Support for private indexes was [announced recently](https://krew.sigs.k8s.io/docs/user-guide/custom-indexes/).

Krew indexes are git repos with a format described [here](https://github.com/kubernetes-sigs/krew/blob/6b66d78e4f5d335dc83e34b02730efebf81916a3/site/content/docs/developer-guide/custom-indexes.md). TL;DR - a krew index is a git repo with a `./plugins` directory containing yaml files describing the available plugins.

The yaml format shares a lot of similarities with homebrew Formula.rb files - name, version, uri to release artifacts, checksums on those artifacts. Having a tool such as goreleaser that can automate the updating of these files would allow for a fully automated release pipeline for krew. (example PR to the public krew index: https://github.com/kubernetes-sigs/krew-index/pull/814/files)

It would be fantastic if goreleaser could update krew plugin yaml files as part of a release pipeline.

**Describe alternatives you've considered**

For now our favored method for distributing private kubectl plugins is to use brew because goreleaser can fully automate this release pipeline. This covers macOS users. Direct support for krew indexes would open up more platforms and simplify the packaging and release process. We can support linux users through rpm and deb packages but that requires additional CI/CD steps to push the packages to a repo.

I am possibly interested enough to try to implement support myself as a way to become more familiar with the goreleaser code base, tho I would love some feedback and if you would consider supporting this feature some direction on how best it might be implemented.

**Comment by caarlos0** [comment]
I think it would be nice to add a new pipe that does this, yes. 

Thanks for the suggestion, and feel free to work on it if you want 🙏

**Comment by caarlos0** [comment]
I don't think this will be added in goreleaser natively. You can probably get around it using [custom publishers](https://goreleaser.com/customization/publishers/) though.

Closing for now.
