### ISSUE TITLE
port new nfpm options into goreleaser

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#1829]
gorelaser is behind nfpm in options, mostly regarding signing packages.

we need to port and document them.

**Comment by jonathanlloyd** [comment]
Hey! I've started having a go at this in #1849
I've only done the deb config to start with to check with you that I'm headed in the right direction.
If so, I'll take a look at adding rpm and apk as well

Happy Hacktoberfest! :jack_o_lantern:
