### ISSUE TITLE
Add hook to insert custom release notes

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#183]
First, great job on this!

I'm in the process of automating the semi-manual release process of Hugo with Goreleaser. None of the points mentioned below are blockers in that regard, and I think these are connected enough to warrant keeping them in this single issue.

* Release notes are very important for Hugo. A release may contain 200 commits, and while the commit log is nice and all, it doesn't make sense to put it in the changelog as-is. So we create our own release notes, semi-manually, and that is fine. **But there is currently no hook in Goreleaser to insert this.**
* The release notes are part of the release. I.e. they should be in a file in the released source/tag. **The release notes in Goreleaser are created after the tag is created and not part of the distribution.**
* Goreleaser creates a release on GitHub and publishes it. I wish there were an option to create a draft, so it could be possible to polish the release notes by hand etc. before releasing it to the world.

In the bullets above, I would hope to get from Goreleaser, in prioritized order:

1) Hook to insert custom release notes.
2) A flag to publish release as GitHub draft.

I understand the you have to make some priorities here, but I suggest that you for 1.0 at least think about any future changes that may come in this department. I think you underestimate the value of the release notes.

But again, the above are no blockers for me. This is thousands times better than what I had (I'm not even sure if the latest Hugo is available via Brew yet, and our build process is incredibly spread out) -- and once I get it up and running, I may have a look doing some contribution for the Chocolatey integration (Windows) and maybe also Snapcraft.

**Comment by caarlos0** [comment]
@bep Hi, I agree, the release notes are not optimal. 

Just so I can fully understand, what exactly would the hook do?

Is the hook an executable (like https://github.com/skywinder/github-changelog-generator)? Or is it a text file with what you want as changelog already written down?

Thanks

**Comment by bep** [comment]
>Just so I can fully understand, what exactly would the hook do?

I have not thought too hard about it, but in its simplest form, I guess a prepared text file would be nice enough (aka `goreleaser --release-notes=/mypath/release-notes-v1.01.txt`. My main motivation is to not have to re-invent the "update GitHub release"  part. I can understand you want to keep the "created by @goreleaser" part, and that is fine -- just append that at the end.

**Comment by caarlos0** [comment]
@bep nice, so, quite easy to implement. Will see if I can do that throughout the day :)



> I can understand you want to keep the "created by @goreleaser" part, and that is fine

😄

**Comment by caarlos0** [comment]
@bep check #184 :)

**Comment by caarlos0** [comment]
@bep released https://github.com/goreleaser/goreleaser/tree/v0.11.0

**Comment by caarlos0** [comment]
About the draft option, I think it should be a config, not a flag. 
I think people will always want to release drafts, check them, and then promote or discard them (at least that is what I would do). 

What do you think, @bep?

**Comment by bep** [comment]
>About the draft option, I think it should be a config, not a flag.

Yes, for a given repository I think it will be always draft/direct publish. I assume that `goreleaser` will typically release without any user intervention, but projects with less frequent releases, Hugo being one example, typically would like to do some QA/spell checking etc. before they release.

**Comment by caarlos0** [comment]
One question: what should happen in the brew pipe when the release is a draft?

**Comment by caarlos0** [comment]
check #185 =)

**Comment by caarlos0** [comment]
Will continue on #212
