### ISSUE TITLE
Request to Add Hacktoberfest Topic to repository

### ISSUE THREAD

**Issue by m4ver1k** [goreleaser/goreleaser#1833]
Hello,

I noticed few of the issues are marked with `Hacktoberfest` label. Even I discovered an interesting issue and started working on it, following open issues labelled with Hacktoberfest.

Because of an influx of spam PRs the organisers have made few changes to the rules, and only repositories with topic `hacktoberfest` is considered. 

Please find more details [here](https://hacktoberfest.digitalocean.com/hacktoberfest-update).

I request to kindly opt-in and add `hacktoberfest` topic to this repository.

**Comment by caarlos0** [comment]
Done, thanks for the reminder 🚀
