### ISSUE TITLE
upload files with version goreleaser-0.143.0-28230b6.deb

### ISSUE THREAD

**Issue by soloturn** [goreleaser/goreleaser#1844]
linux package repositories contain packges which bear the versoin in their filename. which can be like goreleaser-0.143.0-1.deb, or goreleaser-0.143.0-28230b6.deb.

please support it in two fashions:

1. allow to create such filenames
2. in case something fails in the middle, allow to overwrite the files, even with different version. e.g. one build is goreleaser-0.143.0-1.deb, the next is goreleaser-0.143.0-2.deb. goreleaser-0.143.0-2.deb should overwrite.

**Comment by caarlos0** [comment]
you name the file using `file_name_template`, which solves item 1.

item 2 is not something we are going to add, as goreleaser has no knowledge of previous builds. You can simulate the incremental thing by using environment variables in the name template though.
