### ISSUE TITLE
Support Go submodule tags

### ISSUE THREAD

**Issue by sagikazarmark** [goreleaser/goreleaser#1848]
**Is your feature request related to a problem? Please describe.**
Go allows you to place multiple Go modules in a single repository and version them individually. For example, a protobuf API might be placed in a separate module for consumers (so that they don't have to pull in the entire application) and tagged as `api/v1.0.0`.

Similarly, binaries could be placed in separate modules as well. Such modules might be tagged as `cmd/mybinary/v1.0.0`. This is actually the case with the code generator for grpc-go: https://github.com/grpc/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.0.0

Unfortunately, Goreleaser is unable to detect those tags at the moment.

**Describe the solution you'd like**
Add support for repositories managing multiple modules. There are several approaches that could work, but probably the easiest is to be able to parse/map git tags to actual tags.

In our case, `cmd/mybinary/v1.0.0` should become `v1.0.0`

**Describe alternatives you've considered**
Since Goreleaser can create more than one "build" pipeline, this would probably have to be configurable on a build to build basis.

Alternatively (and as a limitation) Go submodules might have to receive their own `.goreleaser.yml` config.

**Comment by caarlos0** [comment]
refs https://github.com/goreleaser/goreleaser/pull/723

Assuming you'll have one `.goreleaser.yml` for each "thing" you want to release (e.g. each cmd), we could add a config like:

```yaml
git:
  tagPrefix: cmd/mybinary/
```

The only problem remaining would be the git log... we don't know which commits affect each artifacts... (unless we parse everything but it seems way too much of an effort)... so I don't know if we show all logs between the last tag with a given prefix or just disable the changelog all together when tag prefix is set 🤔

wdyt?

**Comment by sagikazarmark** [comment]
Personally, I don't use the changelog feature, so it would be an acceptable limitation from my point of view. 😄 

Alternatively, I wouldn't mind specifying the tag itself somehow. Most CIs will give you that information when the CI run is triggered by a tag event. (Actually, I tried `GORELEASER_CURRENT_TAG=`, but obviously didn't work)

**Comment by mavogel** [comment]
The case of goreleaser supporting monoprepos is becoming relevant for me as well. Can we have a discussion/exchange soon @caarlos0 how would be the best way to support this? Happy to contribute :)

**Comment by caarlos0** [comment]
> he case of goreleaser supporting monoprepos is becoming relevant for me as well. Can we have a discussion/exchange soon @caarlos0 how would be the best way to support this?

sure, idk how to handle it yet as well... but lets discuss for sure :)

**Comment by caarlos0** [comment]
Monorepo support was just released as [pro](https://goreleaser.com/pro/) feature.

Althought its not exactly the same thing as the original issue, I think it fills the gap.

Feel free to take a look and let me know what you think, reopen if needed.
