### ISSUE TITLE
Support option to allow archive with different binary count for a given platform

### ISSUE THREAD

**Issue by ChrisRx** [goreleaser/goreleaser#1855]
**Describe the bug**

A change in behavior was introduced recently (in #1841, proposed as a solution to #1780), that causes goreleaser to error when the count of binaries does not match for each platform within an archive.  In situations where this is expressly desired, there is no way to circumvent this check.

**To Reproduce**

Steps to reproduce the behavior can be found in the following goreleaser config:

https://github.com/criticalstack/crit/blob/a8ec49adbc86e953b6e89634a01cd9873c29d102/.goreleaser.yml

where two binaries are defined within a build and the `goarch` is different between the two binaries.  Here the second binary does not specify additional architectures, causing the count of binaries per platform to be different.

**Expected behavior**

As a user of goreleaser I want the option to disable this check when it is expressly not wanted/needed.  In situations like with this project:  https://github.com/criticalstack/crit there are two binaries in a given archive, one a Kubernetes bootstrapping tool, the other binary a [kind-like](https://kind.sigs.k8s.io/) container-in-container tool only for testing/local development.  The bootstrapping tool can run on multiple architectures like arm64, while the testing tool does not at this time.  It is nice with installer scripts like [this](https://github.com/criticalstack/crit/blob/main/scripts/install.sh) to simply install the contents of a given archive if it is supported (which also omits them when they are not).

**Comment by ChrisRx** [comment]
I see this issue #1853 is reporting the same change in behavior.  I appreciate the position of goreleaser to reduce downstream user confusion, however, this is not something that I feel like applies in all cases and would be greatly appreciated by myself to have some way of ignoring this check.  Any help you can provide again is greatly appreciated!

**Comment by caarlos0** [comment]
plz check #1856

**Comment by ChrisRx** [comment]
@caarlos0 everything worked for me locally using that flag you added.

Also thank you so much for looking at this so quickly, this was an amazing experience!

**Comment by caarlos0** [comment]
releasing v0.145.0...
