### ISSUE TITLE
Add option to include/import external config file or otherwise share configuration

### ISSUE THREAD

**Issue by paultyng** [goreleaser/goreleaser#1857]
**Is your feature request related to a problem? Please describe.**
We manage a lot of releases and it would be nice to just have a single external file that all of those releases include and/or reference instead of having to update all the repositories for a change.

**Describe the solution you'd like**
We could add a new top level key for including or importing an external file or something along these lines:

```yaml
include: github.com/my-org/goreleaser-config/config.yml
```

We could use a package like [go-getter](https://github.com/hashicorp/go-getter) or something else that allows for different types of sources (s3, git, github, https, etc).

**Describe alternatives you've considered**
Instead of this, we could run tooling to merge multiple YAML's together prior to executing goreleaser.

**Comment by caarlos0** [comment]
This was just released as [pro](https://goreleaser.com/pro/) feature.

Thanks for the issue :)

**Comment by paultyng** [comment]
I saw, very cool, thanks! Will definitely look at pro if/when I need it.
