### ISSUE TITLE
Conflict between two deb packages because they install same file in same path

### ISSUE THREAD

**Issue by jportasa** [goreleaser/goreleaser#1887]
**Is your feature request related to a problem? Please describe.**
I have 2 not related deb packages created by goreleaser v0.145 that install same file in same path, so when I install the second one, dpkg installer something like “there is a conflict with this file, installation aborted”.:

Error installing the 2nd package:
`"Unpacking nri-redis (1.6.0) ...", "dpkg: error processing archive /var/cache/apt/archives/nri-redis_1.6.0_amd64.deb (--unpack):", " trying to overwrite '/etc/newrelic-infra/integrations.d/redis-config.yml.sample', which is also in package newrelic-infra-integrations 1.2.0-1"`

**Describe the solution you'd like**
 in NFPM of .goreleaser add a  section called "Replacements"

FPM allows to use the Replacement parameter to allow "overwrite" files from other packages https://linux.die.net/man/5/deb-control

**Comment by caarlos0** [comment]
check  #1888
