### ISSUE TITLE
Use docker as alternative builder

### ISSUE THREAD

**Issue by itaysk** [goreleaser/goreleaser#1890]
**Is your feature request related to a problem? Please describe.**
Use a docker build to produce the artifact that goreleaser will end up releasing (instead of letting goreleaser build it).

My current project already has 3 ways to build the binary: 1) makefile 2) docker build 3) goreleaser. There are legitimate reasons why I need each tool. I would prefer to be able to *layer* those tools on top of each-other: 1) makefile builds the artifact 2) docker runs makefile in a reproducible container 3) goreleaser runs the dockerfile which runs makefile to get the artifact to release. This way I benefit from the strengths of each tools, and each user can choose at which layer they want to interact (some prefer to make build, some prefer to docker build, goreleaser should be used only for releasing but use the exact same process to build).

**Describe the solution you'd like**
Add an option to configure goreleaser to use a dockerfile to build the artifact instead of the built-in go builder
I've seen that the so called "builder" is written in a pluggable way, that today there's the golang implementation but I think it should be straightforward to add another kind of builder by implementing the interface and adding a new config section to the yaml.

**Describe alternatives you've considered**
Today I make build/docker build for local development/tests and use goreleaser for releasing. Besides having to maintain the build config in multiple locations, I have to maintain a special dockerfile for goreleaser, which doesn't copy from builder stage, instead copies the goreleaser build, just to make sure everyone get's the same binary.

**Additional context**
when considering thise feature request, please consider projects with complex build configurations (like complex cgo projects) where the makefile is the better way to maintain the build configuration.

Also consider that this can open the door for other languages to use goreleaser.

I could work on this if you can provide minimal guidance

**Comment by caarlos0** [comment]
Sorry, this is very unlikely to happen on v0/v1, as it would basically be a rewrite of the build step.

Closing for now, will keep in mind for v2.

Thanks!
