### ISSUE TITLE
Skip build

### ISSUE THREAD

**Issue by itaysk** [goreleaser/goreleaser#1891]
**Is your feature request related to a problem? Please describe.**
In order to support more flexibility in the build phase, an easy solution would be to skip the build via goreleaser, and find the artifact in place. this would allow me for example to build using make but still benefit from goreleaser for releasing.

**Describe the solution you'd like**
option to skip the build phase. the artifacts can be found by adhering to a naming convention, or yaml configuration.

**Describe alternatives you've considered**

**Additional context**
may be a workaround to https://github.com/goreleaser/goreleaser/issues/1890

**Comment by itaysk** [comment]
This is already supported, my bad I missed it

**Comment by itaysk** [comment]
upon further reading I see that 1) the build pipe still requires to clear the dist even if build is skipped and 2) docker step (for example) is expecting to find the binary in the `Artifacts` list which can't be manually populated.
Is there a way to use the skip build flag and give subsequent flags a pre-build binary? if not, then that was the motivation behind this enhancement suggestion

**Comment by caarlos0** [comment]
> then that was the motivation behind this enhancement suggestion

release libraries, e.g. https://github.com/goreleaser/fileglob/blob/main/.goreleaser.yml

But no, its not possible to do what you want... and probably will never be.

You can call `goreleaser build` in your makefile instead... (which only builds the binaries), there are issues to support building only the target arch, but its not implemented yet.

**Comment by itaysk** [comment]
> then that was the motivation behind this enhancement suggestion
I meant the motivation for me to open this issue :)

calling `goreleaser build` in my makefile is the opposite of what I wanted to do. Since building my go project is more involved, I prefer to build it from make. 

Anyway, thanks for confirming this will not be happening

**Comment by caarlos0** [comment]
> Since building my go project is more involved, I prefer to build it from make.

ok.

> Anyway, thanks for confirming this will not be happening

no problem :)

**Comment by nkierpiec** [comment]
@caarlos0 Sorry to resurrect a closed issue here but when you say:
> But no, its not possible to do what you want... and probably will never be.

Do you mean it won't be possible to do a `--skip-build` when releasing a project? I have a multi phase use case where we  build and later in the lifecycle we want to release but not rebuild the project. Currently, the only way I can see to do that is by providing the `skip: true` within the config but I don't necessarily want to keep multiple configs around to have that one value be set to true and then false in another.
