### ISSUE TITLE
Releasing to a Linux-only Homebrew formula

### ISSUE THREAD

**Issue by nikolay** [goreleaser/goreleaser#1893]
**Describe the bug**

```
$ brew readall
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/muesli/homebrew-tap/deckmaster.rb
formulae require at least a URL
```

The formula is generated with GoReleaser and does not target macOS. In such case, at least `depends_on :linux` should be added, but, regardless, it does not work due to the fact that macOS requires a `url` property, which is not defined on macOS.

**To Reproduce**

https://github.com/muesli/deckmaster/blob/master/.goreleaser.yml

**Expected behavior**

The generated formula should have `depends_on :linux` and handle gracefully when the tap, which may have formulas available on macOS, too, errors out due to unset `url` property.

**Environment (please complete the following information):**

- OS: mac
- OS version: macOS 11.0.1 Big Sur
- GoReleaser Version 0.146.0

**Comment by caarlos0** [comment]
can you check #1900?
