### ISSUE TITLE
Update brew template to support Arm for Mac

### ISSUE THREAD

**Issue by rothgar** [goreleaser/goreleaser#1903]
**Is your feature request related to a problem? Please describe.**
It would be nice if the brew template supported a check for Arm architecture on Mac

**Describe the solution you'd like**
Update the template (and possibly other necessary files) to support Arm on Mac
https://github.com/goreleaser/goreleaser/blob/b4f154d81f09ffb73da8c90bbd7f26fba5feac75/internal/pipe/brew/template.go#L44-L50

**Describe alternatives you've considered**
Manually creating a template would be an option but I didn't see that option documented.

**Additional context**
There are a lot of formula that don't support arm installs right now. Tracking in Homebrew/brew#7857

**Comment by caarlos0** [comment]
darwin arm64 is not supported by Go yet... so I would say we probably need to wait until go 1.16? 🤔

**Comment by rothgar** [comment]
Based on golang/go#38485 it looks like it'll be official Feb 1st

**Comment by caarlos0** [comment]
handled in #1952

**Comment by caarlos0** [comment]
@rothgar also plz feel free to take a look/test #1956
