### ISSUE TITLE
Artifactory: Add possibility to upload to different targets for different package types (deb,rpm,zip)

### ISSUE THREAD

**Issue by zbindenren** [goreleaser/goreleaser#1913]
**Is your feature request related to a problem? Please describe.**
I am opening this issue because of: https://github.com/goreleaser/goreleaser/discussions/1713

Currently we build with goreleaser the following artifacts:

* zip
* dep
* rpm

If I configure goreleaer to upload artifacts to artifactory, all artifacts go to the same target. Right now it is not possible to upload different artifacts to different artifactory targets.

**Describe the solution you'd like**
It should be possible to define different targets for different package types.

**Describe alternatives you've considered**
As metioned https://github.com/goreleaser/goreleaser/discussions/1713 in I tried with templates, but was not able to achieve this.

**Comment by stuart-warren** [comment]
I've kind of done it with custom publishers
https://github.com/bottlerocketlabs/localpod/blob/v0.0.15/.goreleaser.yml#L37-L60

**Comment by zbindenren** [comment]
Me too. I think we can close this issue.

**Comment by caarlos0** [comment]
How do you feel about publishing it in the [cookbooks](https://goreleaser.com/cookbooks/) section of the docs? Would be nice I think...
