### ISSUE TITLE
Open ghcr.io goreleaser image!

### ISSUE THREAD

**Issue by angelbarrera92** [goreleaser/goreleaser#1938]
**Describe the bug**
I can see that there are multiple destinations to the goreleaser container image: Dockerhub and ghcr.io. With the new dockerhub rate limits, someone can face a limit hit error while downloading. This is why I'm trying to use the ghcr.io alternative.

But, I can not download the container image from `ghcr.io/goreleaser/goreleaser`. It seems to be private. Should it?

**To Reproduce**

Just run from a clean instance `docker pull ghcr.io/goreleaser/goreleaser:latest-amd64`

**Expected behavior**

I expect to download it as I do from Dockerhub

**Additional context**

Follow this guide to make it public: https://docs.github.com/en/free-pro-team@latest/packages/guides/configuring-access-control-and-visibility-for-container-images#configuring-visibility-of-container-images-for-an-organization

**Comment by caarlos0** [comment]
Oh, my bad... should be public now! Thanks for reporting 🙏

**Comment by angelbarrera92** [comment]
Now it works! Thanks @caarlos0 !
