### ISSUE TITLE
monorepo: relax tag name constraints to better support monorepos

### ISSUE THREAD

**Issue by tmc** [goreleaser/goreleaser#1948]
Using goreleaser is tough in a repository that has multiple streams of releases coming from it. Requiring that the tags confirm strictly to semver semantics means that all parts of a repository tree are then sharing the same version tags.

Ideally if a repository had multiple subtrees from which releases were generated, say, /beef and /chicken, then tagging chicken-2.1.0 would enable a goreleaser-based release pipeline for that particular subtree. This would allow concurrent but separate tagging, building, and releasing from different parts of tree.

This would expand how useful this tool is for organizations that don't follow a 1:1 repo to artifact relationship.

**Comment by tmc** [comment]
Further, allowing filtering the changelog down to a particular subtree's commits would further enable the above use case.

**Comment by caarlos0** [comment]
This was just released as [pro](https://goreleaser.com/pro/) feature.

Thanks for the issue :)
