### ISSUE TITLE
Add build to Chocolatey.org

### ISSUE THREAD

**Issue by danstis** [goreleaser/goreleaser#1963]
As I gorelease user running windows, 
I would like to see the latest windows build pushed to the chocolatey.org package feed,
so I am able to install automatically using chocolatey.

While it is possible for me to create a chocolatey task to enable this, it is best included in the release pipeline of this project to the package is always up to date.

**Comment by caarlos0** [comment]
We only support scoop for now (https://github.com/goreleaser/scoop-bucket), I have no idea how to make it work on chocolatey and don't have a windows machine to test any of that.

If someone wants to contribute this, and its not too cumbersome, I think we might include it though.

**Comment by caarlos0** [comment]
this depends on https://github.com/goreleaser/goreleaser/issues/1295, which I don't know when (or if) will happen.

Closing this one and leaving the former as an umbrella
