### ISSUE TITLE
New `contents:` syntax incorrect for symlink (or: incorrect docs?)

### ISSUE THREAD

**Issue by binwiederhier** [goreleaser/goreleaser#1982]
**Describe the bug / steps to reproduce**

It seems that the new "contents:" syntax is a little odd for symlinks, and either the docs or the code is wrong:

According to [the nfpm docs](https://goreleaser.com/customization/nfpm/), `dst` is the real location and `src` is the link name, so this is equivalent to `ln -s /usr/bin/pcopy /usr/bin/pcp`:

```
      - src: /usr/bin/pcp # link name
        dst: /usr/bin/pcopy # real location
        type: "symlink"
```

However, with this^ setting, the .deb file is incorrect:

```
$ dpkg -c *.deb          ...
-rwxrwxr-x 0/0         7176192 2020-12-30 09:33 ./usr/bin/pcopy
...
l--------- 0/0               0 2020-12-29 12:37 ./usr/bin/pcopy -> /usr/bin/pcp
l--------- 0/0               0 2020-12-29 12:37 ./usr/bin/pcopy -> /usr/bin/ppaste
```

Attempting to install this is not pretty:

```sudo dpkg -i *.deb
Selecting previously unselected package pcopy.
(Reading database ... 297141 files and directories currently installed.)
Preparing to unpack pcopy_v0.4.1-next_amd64.deb ...
Unpacking pcopy (0.4.1~next) ...
dpkg: error processing archive pcopy_v0.4.1-next_amd64.deb (--install):
 unable to open '/usr/bin/pcopy.dpkg-new': No such file or directory
Errors were encountered while processing:
 pcopy_v0.4.1-next_amd64.deb
```

I am experiencing that `dst` is in fact treated as the link name and `src` is the real location, so this is actually working:

```
      - src: /usr/bin/pcopy
        dst: /usr/bin/pcp
        type: symlink
```

Here's a concrete example (this works, but does not match the docs): https://github.com/binwiederhier/pcopy/commit/54493a3ad005b83b2542c68d7871958434fb7f14

**Expected behavior**

I'd expect either the docs or the code to be correct. In the src/dst semantics I think the way it is DOCUMENTED (dst = real locataion, src = link name) makes the most sense, since it corresponds to what `dpkg -c` and `ls -al` will output:

```
l--------- 0/0               0 2020-12-30 09:36 ./usr/bin/pcp -> /usr/bin/pcopy
l--------- 0/0               0 2020-12-30 09:36 ./usr/bin/ppaste -> /usr/bin/pcopy
```

**Environment (please complete the following information):**

- OS: Linux
- OS version: Ubuntu 18.04
- GoReleaser Version 0.150.1

**Comment by caarlos0** [comment]
Yup, docs are wrong. Will fix. Thanks for spotting this :)

**Comment by caarlos0** [comment]
> makes the most sense, since it corresponds to what `dpkg -c` and `ls -al` will output

dunno, in my head the way it is makes more sense because `ln -s $src $dst`... so, fixed the docs only.

Thanks again for spotting this :)

**Comment by caarlos0** [comment]
cc/ @djgilcrease fyi
