### ISSUE TITLE
Cannot add build artifacts due to "git dirty" error

### ISSUE THREAD

**Issue by andig** [goreleaser/goreleaser#2009]
**Is your feature request related to a problem? Please describe.**
I'm creating image files during build that I want to add as release assets. The image files are big (1GB) hence I don't want to add them to git. Goreleaser prevents that since git is then "dirty".

**Describe the solution you'd like**
Allow dirty git when releasing. Alternatively: allow to add files to a previously created release (at that time in clean state).

**Describe alternatives you've considered**
Don't use goreleaser.

**Additional context**
Example build: https://github.com/andig/evcc/runs/1676940286?check_suite_focus=true

    • releasing...     
    • loading config file       file=.goreleaser.yml
    • loading environment variables
    • getting and validating git state
        • releasing 0.40, commit 89bd868764dca5c4f8376713405a9ce6d07d48fe
    ⨯ release failed after 0.03s error=git is currently in a dirty state, please check in your pipeline what can be changing the following files:
    M go.mod
    M go.sum
    ?? evcc_0.40.image
    ?? evcc_0.40.image.gz
    ?? evcc_0.40.rootfs
    ?? evcc_0.40.rootfs.gz

**Comment by caarlos0** [comment]
You should add those files to gitignore, and go.mod/go.sum are out of sync as well, should probably `go mod tidy` and commit.

You can use `--skip-validate` to skip these (and other validations).
