### ISSUE TITLE
Bug: Using `sort:` writes different Changelog even if stdout shows the correct one.

### ISSUE THREAD

**Issue by gabyx** [goreleaser/goreleaser#2010]
Using the following:
```
changelog:
  sort: asc
```

Using `sort:` shows extracting the correct `changelog` on stdout with `--verbose`, but the written `CHANGELOG.md` is something else completely. If `sort:` is deleted, the correct extracted changelog gets written.

```
goreleaser release --debug --skip-publish --rm-dist
```

Go to the folder where: https://github.com/gabyx/githooks/blob/feature/go-refactoring/githooks/.goreleaser.yaml

Reproduce in this folder:
```
goreleaser release --debug --skip-publish --rm-dist
```

> Make sure your config file is valid by running
Its valid.

**Expected behavior**

The changelog as show on stdout with `--debug` should be written to the file.

**Environment (please complete the following information):**

- OS: linux
- OS version: 5.4.0-60-generic #67-Ubuntu
- GoReleaser 
  - goreleaser version 0.154.0
  -  commit: e8ea231122dc98ec2315eff2df2defc5191764d6
  - built at: 2021-01-07T19:21:12Z
  -  built by: goreleaser

**Comment by gabyx** [comment]
I tested (is `sort:asc` a lexical sort over the commit subject lines??

Output:
```
      • git result                stderr= stdout=0b7344f test 5 :anchor:
0f33eec test 4 :anchor:
cb3fb5e test 3 :anchor:
d0e3069 test 2 :anchor:
0491da0 test :anchor:
```

CHANGELOG.md
```markdown
## Changelog

d0e3069 test 2 :anchor:
cb3fb5e test 3 :anchor:
0f33eec test 4 :anchor:
0b7344f test 5 :anchor:
0491da0 test :anchor:

```

**Comment by caarlos0** [comment]
it sorts by the the first line of the commit message, not chronological.

seems to me it is working as intended.

**Comment by caarlos0** [comment]
(missclick)

**Comment by gabyx** [comment]
Aha, so thats the behavior. But I am really wondering when you really want this? Why you it string sorted, instead of chronological?
I thought `asc/desc` is just if the chronological order is reversed...

**Comment by caarlos0** [comment]
> But I am really wondering when you really want this?

if you use conventional commits, for instance, to get them "grouped"...

**Comment by gabyx** [comment]
Conventional commits? :-)?

**Comment by caarlos0** [comment]
yup, https://www.conventionalcommits.org
