### ISSUE TITLE
Auto-Detection of Build Parallelism

### ISSUE THREAD

**Issue by bflad** [goreleaser/goreleaser#2013]
**Is your feature request related to a problem? Please describe.**

Build environments can vary in the available hardware. Choosing a default `parallelism` value of `4` can be problematic in environments which are constrained to lower compute resources, such as hosted CI/CD systems. For example, hosted GitHub Actions runners only have 2 cores. When large projects attempt to build with concurrency above the available resources, there is compute resource contention that cause builds to take longer than necessary with context switching and it can also lead to other issues such as overrunning memory resources that are proportional to the compute resources.

**Describe the solution you'd like**

Adjust the `parallelism` default to `0` or `-1`, which performs auto detection based on `runtime.NumCPU()`. Any configured value above `0`, will override any auto detection and set the value as configured. This is behavior of other build tooling, such as `gox`.

If this type of solution is acceptable, happy to submit a pull request.

**Describe alternatives you've considered**

Unfortunately, GitHub Actions does not seem to provide a quick workflow configuration reference that contains the CPU/core count, so hardcoded `--parallelism 2` for now.

**Additional context**

* https://github.com/hashicorp/terraform-provider-aws/pull/17067
* https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources
* https://pkg.go.dev/runtime#NumCPU
* https://github.com/mitchellh/gox

**Comment by caarlos0** [comment]
Yeah, that makes sense...
