### ISSUE TITLE
add support for asdf

### ISSUE THREAD

**Issue by jfreeland** [goreleaser/goreleaser#2025]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I only just learned about goreleaser because a project I wanted to use uses it, https://github.com/pulumi/kubespy.

I had just created an asdf-kubespy repo, https://github.com/jfreeland/asdf-kubespy, and added it to asdf, https://github.com/asdf-vm/asdf-plugins/pull/352.  asdf has a couple nice use cases where homebrew isn't an ideal fit.  I wonder if there would be any value in goreleaser automatically managing asdf plugins for users?  🤷‍♂️

Maybe too complicated, maybe not necessary, maybe out of scope.  Just a thought.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by caarlos0** [comment]
As far as I understand, asdaf plugins are written once and you don't need to update on every release, correct?

If so, rather keep it outside of goreleaser's scope (which is already very big).

Closing for now.
