### ISSUE TITLE
Docs does not warn about the danger of using Personal Access Tokens in a CI/DI

### ISSUE THREAD

**Issue by AnomalRoil** [goreleaser/goreleaser#2026]
**Describe the bug**

According to [goreleaser's doc](https://goreleaser.com/ci/actions/#limitation), one is supposed to use a custom Access Token to publish taps to Homebrew:
> If you need to push the homebrew tap to another repository, you must therefore create a custom [Personal Access Token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) with repo permissions and [add it as a secret in the repository](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets). 

However it does not say how these tokens are supposed to be generated, linking to the generic Github documentation.

Notice that using a own Personal Access Token in a CI/DI is a **really bad idea** because these tokens are granting access to **all the repo** of the user who created it. 
This is not something individual contributors in a repo/organization usually want to do as it would expose all of their repo to any "malicious" CI/DI job. 

The current documentation is encouraging people to do it without any warning or caveats.

**To Reproduce**

See documentation here: https://goreleaser.com/ci/actions/#limitation
and here: https://goreleaser.com/environment/#api-tokens where it even has a direct link to one's own settings: https://github.com/settings/tokens/new

**Expected behavior**
Proper warning and caveats about what it entails to give `repo` access to a **Personal** Access Token that is meant to be used on a CI/DI.

**Additional context**
I'll open a discussion about security and how one is supposed to do things securely.

**Comment by caarlos0** [comment]
Yeah, I think this can be clarified indeed. If you have some specifics in mind, feel free to open a PR :)

**Comment by caarlos0** [comment]
added a link to the docs as well.
