### ISSUE TITLE
Gitea upload to own instance by config `url`.

### ISSUE THREAD

**Issue by gabyx** [goreleaser/goreleaser#2036]
So far it does not seem possible to upload to an own hosted gitrea instance at a differen url to `gitea.com`

**Describe the solution you'd like**
Provide an `url` which is the base URL to the gitea server

**Describe alternatives you've considered**
HTTP upload? Not sure if that works with Gitea ...

**Comment by caarlos0** [comment]
duplicated of https://github.com/goreleaser/goreleaser/discussions/2023
