### ISSUE TITLE
support mips64le architecture

### ISSUE THREAD

**Issue by duchuanLX** [goreleaser/goreleaser#2047]
**Is your feature request related to a problem? Please describe.**
support mips64le ，need release go project on mips64le architecture

**Describe the solution you'd like**
make test
use golang -race，but mips64le does not support this golang feature now.
Can I submit a PR that supports mips64le pr?

**Describe alternatives you've considered**

Can I block the race option?

**Additional context**

![image](https://user-images.githubusercontent.com/59048253/106859993-b49c6d00-66bb-11eb-91b5-77f08542b9b8.png)

@caarlos0
@jorinvo

**Comment by caarlos0** [comment]
`mips64le` is already supported by goreleaser... I don't get what is the problem you're having...


https://github.com/goreleaser/goreleaser/blob/master/internal/builders/golang/targets.go#L197

**Comment by duchuanLX** [comment]
> `mips64le` is already supported by goreleaser... I don't get what is the problem you're having...
> 
> https://github.com/goreleaser/goreleaser/blob/master/internal/builders/golang/targets.go#L197

I did not find the mips64le branch here
https://github.com/goreleaser/goreleaser/releases

**Comment by caarlos0** [comment]
Ah got it. But then I don't get what -race has to do with which arches we release to... 🤔

**Comment by duchuanLX** [comment]
> Ah got it. But then I don't get what -race has to do with which arches we release to... 🤔
~~~make test
# Run all the tests
test:
	LC_ALL=C go test $(TEST_OPTIONS) -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt $(SOURCE_FILES) -run $(TEST_PATTERN) -timeout=5m
.PHONY: test

Your CI should support golang cross-compilation, I think it should support the race option, sorry.
What do I need to do before you can agree to join the mips64le architecture, and I hope to maintain the architecture for a long time.thanks。

**Comment by caarlos0** [comment]
We don't test against the other arches either, mostly because it doesn't matter as we don't do anything specific for one or another...

**Comment by caarlos0** [comment]
> What do I need to do before you can agree to join the mips64le architecture, and I hope to maintain the architecture for a long time.thanks。

I don't get this... what do you mean maintain the architecture? And not sure what you mean by joining it either...

**Comment by caarlos0** [comment]
and isn't mips64le used only in things like routers? I don't see why you would need to run goreleaser from a router 🤔

**Comment by duchuanLX** [comment]
> > What do I need to do before you can agree to join the mips64le architecture, and I hope to maintain the architecture for a long time.thanks。
> 
> I don't get this... what do you mean maintain the architecture? And not sure what you mean by joining it either...

----
https://github.com/goreleaser/goreleaser/releases

i found amd64、arm64、armv6 multi-architecture，i want generate mips64le rpm and deb package。
goreleaser_amd64.apk
goreleaser_amd64.deb
goreleaser_amd64.rpm
...

**Comment by caarlos0** [comment]
`mips64le` is, as far as I understand, used mostly in embedded systems (like routers), which doesn't seem to me that goreleaser is very useful there, as you would normally compile on either a CI or a more powerful machine.

That being said, and judging by [your history of opening issues just for that on several projects](https://github.com/search?p=1&q=author%3AduchuanLX&type=Issues) (which seems rather suspicious tbh), and also taking into account that it would be another platform for us to officially support once we add it... I rather not add this right now.

You can still git clone and compile it if you want.

**Comment by duchuanLX** [comment]
> `mips64le` is, as far as I understand, used mostly in embedded systems (like routers), which doesn't seem to me that goreleaser is very useful there, as you would normally compile on either a CI or a more powerful machine.
> 
> That being said, and judging by [your history of opening issues just for that on several projects](https://github.com/search?p=1&q=author%3AduchuanLX&type=Issues) (which seems rather suspicious tbh), and also taking into account that it would be another platform for us to officially support once we add it... I rather not add this right now.
> 
> You can still git clone and compile it if you want.

The mips64le architecture is currently used in desktop operating systems and server operating systems. We really need this CI tool to support the cloud-native 400 open source project test environment, so we need the goreleaser package to officially output mips architecture packages.
We are indeed promoting the mips64le architecture to be better maintained in the community, and we ensure that there are fixed staff to participate in every project we submit.
We need more communities to support what we do, better promote mips64le, and let each community give users an extra cpu architecture choice.

We need your help please.

**Comment by caarlos0** [comment]
You don't need to run goreleaser on mips64le to generate builds for mips64le. 

Besides, we can't possibly support all goos/goarch combinations that exist as we simply don't have the time nor the resources to do so.

Keep in mind that this is an open source project, maintained by people on their **free time** under a MIT license.
