### ISSUE TITLE
The first release should contain all changes

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#207]
So given a new repository:

* Make lots of commits.
* Tag `v1.0.0` 
* Run `goreleaser`

It doesn't find a previous tag (which is natural), and only lists changes from the previous commit (i.e. 1 change).

**Comment by bep** [comment]
The obvious workaround is to create some inital eary `v0.0.1` tag.

**Comment by caarlos0** [comment]
@bep check #208
