### ISSUE TITLE
Override the file permissions inside the generated release tar archives

### ISSUE THREAD

**Issue by rgl** [goreleaser/goreleaser#2075]
**Is your feature request related to a problem? Please describe.**

[While cross-compiling](https://github.com/rgl/packer-provisioner-windows-update/blob/master/.goreleaser.yml) (compile in windows to run in linux/macos) the file permissions inside the release tar archive endup with incorrect permissions `rw-rw-rw-` instead of, e.g., `rwxr-xr-x`.

This is problematic for files that should be executable, like the `packer-provisioner-windows-update` file inside the [release tar archive](https://github.com/rgl/packer-provisioner-windows-update/releases/download/v0.11.0/packer-provisioner-windows-update_0.11.0_linux_amd64.tar.gz) that should be executable.

**Describe the solution you'd like**

A way to set the file permissions (e.g. something like [mtree](https://www.freebsd.org/cgi/man.cgi?mtree(8)) or something like [gitattributes](https://git-scm.com/docs/gitattributes)).

**Describe alternatives you've considered**

Doing the build in a native machine (non cross-compilation) is cumbersome.

**Additional context**

This is related to https://github.com/goreleaser/goreleaser/issues/717.

**Comment by caarlos0** [comment]
we can also copy the way we do permissions on nfpm...

**Comment by caarlos0** [comment]
will be handled together in https://github.com/goreleaser/goreleaser/issues/1638
