### ISSUE TITLE
replace directive breaks go install/go get for Go 1.16

### ISSUE THREAD

**Issue by jaredallard** [goreleaser/goreleaser#2080]
**Describe the bug**

Unable to use `go install` or `go get` with Go 1.16 to download goreleaser. This breaks tools, such as [gobin](https://github.com/myitcv/gobin).

**To Reproduce**

To reproduce, install Go 1.16 and run `go install github.com/goreleaser/goreleaser@v0.155.2`:

```
go install github.com/goreleaser/goreleaser@v0.155.2: github.com/goreleaser/goreleaser@v0.155.2
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module
```

When using `gobin` (`go get`) `gobin -run github.com/goreleaser/goreleaser@v0.155.2`:

```
failed to run go list -find -json github.com/goreleaser/goreleaser: exit status 1
go: github.com/mattn/go-shellwords@v1.0.10 (replaced by github.com/caarlos0/go-shellwords@v1.0.11): missing go.sum entry; to add it:
        go mod download github.com/mattn/go-shellwords
```

**Expected behavior**

`go install` would successfully build goreleaser.

**Environment (please complete the following information):**

- OS: Ubuntu 20.04 (WSL2)
- OS version: Linux DESKTOP-94VHCO4 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- GoReleaser Version v0.155.2

**Additional context**

This appears to be due to the replace directive for go-shellwords. It's [stated that permanent replacements (forks) should use new import paths and not a `replace`](https://github.com/golang/go/issues/30354#issuecomment-466479708) and it seems Go tooling is now enforcing that belief in Go 1.16

**Comment by jaredallard** [comment]
I'm happy to open PRs on both of these repos to remove the need for `replace`, if that's wanted. Just wanted to make sure I'm not doing something unwanted.

**Comment by caarlos0** [comment]
The replaces are needed. Our forks are temporary while we wait for them to be merged upstream.

FWIW: [the recommend install ways](https://goreleaser.com/install/).

**Comment by jaredallard** [comment]
Totally agree here, the fork is needed. I'm just wondering if we can potentially change the import path in the fork until it's been merged 😃

**Comment by caarlos0** [comment]
yeah, that PR seems pretty much dead... feel free to open PRs :)

**Comment by caarlos0** [comment]
fixed on master.
