### ISSUE TITLE
fix go.sum before running goreleaser

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#2088]
for some reason the process changes go.mod, even though its tidied, which breaks goreleaser later

this happens on both goreleaser and nfpm

**Comment by jasonmccallister** [comment]
I noticed the same thing today and it was after upgrading `go.mod` from `1.15` to `1.16`. My `.goreleaser.yml` had the before hook to run the the following:

```
before:
  hooks:
    - go mod download
    - go test -v ./...
```

Removing that locally did not modify the `go.mod` but still breaking on the Github Action.

**Comment by caarlos0** [comment]
FWIW this is something we'll fix on goreleaser CI pipeline and it doesn't affect goreleaser users...

related:

- https://blog.golang.org/go116-module-changes
- https://github.com/golang/go/issues/43994
