### ISSUE TITLE
Version should strip leading "v"

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#210]
See https://github.com/spf13/hugo/releases/tag/v0.20.3

I did not notice this until I tried to upgrade a site ... That we now have a "v" in the filename:

hugo_v0.20.3_Linux-64bit.tar.gz

I assume this is a bug in Goreleaser, or you should at least provide a way to remove that from the tag.

**Comment by caarlos0** [comment]
Bug. Once upon a time the `.Version` was the tag name, but it was later changed, and this behavior is probably not optimal since then.

I'll add a `.Tag` atribute to the name template, should fix the issue.
