### ISSUE TITLE
Changelog only shows one commit on each release

### ISSUE THREAD

**Issue by lukasmalkmus** [goreleaser/goreleaser#2133]
**Describe the bug**

The changelog generated for the release section of a GitHub repository just lists the most recent commit. However, comparing two tags clearly shows that there are more commits.

**To Reproduce**

Just using the configuration for changelog as suggested in the docs.

```yaml
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
```

**Expected behavior**

Expected every commit after the previous tag to show up in the changelog.

**Environment (please complete the following information):**

- OS: linux (ubuntu-latest on GitHub Actions)
- OS version: -
- GoReleaser Version: 0.160.0

**Additional context**

We are enforcing a linear history.

Demo:

Just one change listed: https://github.com/axiomhq/cli/releases/tag/v0.1.13 but multiple commits can be seen when comparing to the previous tag: https://github.com/axiomhq/cli/compare/v0.1.12...v0.1.13.

Run of the GitHub GoReleaser Action can be seen here: https://github.com/axiomhq/cli/runs/2160213338#step:6:1.

**Comment by caarlos0** [comment]
you need to properly setup the checkout action, check [docs](https://goreleaser.com/ci/actions/).

**Comment by lukasmalkmus** [comment]
Oh wow. Simple as that. Appreciate your work and the fast response!

Thanks :)
