### ISSUE TITLE
Should we fail on a shallow clone?

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#2134]
Every now and then people get confused because their release only have a single commit in the changelog, which is usually related to a shallow clone...

maybe we could check if `.git/shallow` exist and fail early? or maybe just warn about it?

cc/ @goreleaser/everyone wdyt?

**Comment by mgrachev** [comment]
I'd just warn about it.

**Comment by joemiller** [comment]
This definitely bit me on my first time using GitHub Actions since this was not an issue with CircleCI.

+1 to warning.

+1 to failing but how about only if `--snapshot` is not set. I currently setup a 'release-test' job in most of my CI implementations now so that I can add confidence that the goreleaser build will succeed upon master/main merge. I don't need a full clone for these tests.

**Comment by caarlos0** [comment]
> +1 to failing but how about only if `--snapshot` is not set. I currently setup a 'release-test' job in most of my CI implementations now so that I can add confidence that the goreleaser build will succeed upon master/main merge. I don't need a full clone for these tests.

yeah, `--snapshot` implies `--skip-validate` which should skip this check as well I think...

**Comment by caarlos0** [comment]
PR: https://github.com/goreleaser/goreleaser/pull/2135

**Comment by vandot** [comment]
I just saw that goreleaser from now on fails on shallow clone :'(
Problem is that github `actions/checkout` has shallow clone as [default](https://github.com/actions/checkout/blob/c952173edf28a2bd22e1a4926590c1ac39630461/src/input-helper.ts#L85)
We are setting our own release notes and commit history doesn't mean a lot, is it possible to have a flag and allow shallow clones?

**Comment by caarlos0** [comment]
> We are setting our own release notes and commit history doesn't mean a lot, is it possible to have a flag and allow shallow clones?

`--skip-validate` skips it, amongst other things.

This now fails because every now and then we get issues about "changelog is not working"...

**Comment by caarlos0** [comment]
PS: our [docs](https://goreleaser.com/ci/actions/) instruct to fix the shallow clone thing, which is probably what you'll want to do.

**Comment by vandot** [comment]
> `--skip-validate` skips it, amongst other things.
As you said it skips also other stuff
Yes docs clearly warns you, but also warning could be other way around `if you want to have full/correct changelog use fetch-depth: 0` :)
I am not against it only I have too many projects to update :D
Thanks :+1:

**Comment by caarlos0** [comment]
on latest patch I reverted it to be a warning only, so you should be fine :)
