### ISSUE TITLE
add documentation for brew post_install script

### ISSUE THREAD

**Issue by leonwright** [goreleaser/goreleaser#2137]
**Is your feature request related to a problem? Please describe.**
There is no documentation for the post_install script added in the PR for #1487

**Describe the solution you'd like**
Add clear documentation for the post_install script implementation.

**Describe alternatives you've considered**
N/A.

**Additional context**
Link for pull request: https://github.com/goreleaser/goreleaser/pull/1790

**Comment by leonwright** [comment]
PR: #2138

**Comment by caarlos0** [comment]
thanks for the issue and pr @leonwright!

closing as fixed.
