### ISSUE TITLE
Refusing to run against a shallow clone, please make sure to clone the whole tree

### ISSUE THREAD

**Issue by codemodify** [goreleaser/goreleaser#2141]
This is the log, this used to work until today

Run goreleaser/goreleaser-action@v1
✅ GoReleaser version found: v0.161.0
⬇️ Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.161.0/goreleaser_Linux_x86_64.tar.gz...
📦 Extracting GoReleaser...
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/cdfd7db3-d50e-4229-9078-d37e38a80069 -f /home/runner/work/_temp/0fad2f4c-5715-4aa8-9524-3619938a5ebb
✅ v1.7.23 tag found for commit 'f3326ab'
🏃 Running GoReleaser...
/opt/hostedtoolcache/goreleaser-action/0.161.0/x64/goreleaser release --rm-dist --config=./helper-files/.goreleaser.yml
   • releasing...     
   • loading config file       file=./helper-files/.goreleaser.yml
   • loading go mod information
   • loading environment variables
   • getting and validating git state
      • releasing v1.7.23, commit f3326abd0ceac5fe7c7ff04d39b66bda5f23e115
   ⨯ release failed after 0.60s error=refusing to run against a shallow clone, please make sure to clone the whole tree
Error: The process '/opt/hostedtoolcache/goreleaser-action/0.161.0/x64/goreleaser' failed with exit code 1

what is off, how to fix

**Comment by caarlos0** [comment]
yes, you need to add `fetch-depth: 0` to your clone step.

check https://goreleaser.com/ci/actions/
