### ISSUE TITLE
got dynamically linked binary

### ISSUE THREAD

**Issue by mnacharov** [goreleaser/goreleaser#2142]
**Describe the bug**

Recently I switched our CI to docker image(goreleaser/goreleaser:v0.161.1) from running binary(https://git.io/goreleaser)

After that binaries for linux starts to build dynamically linked, and on end devices this causes this error
```
$  ~/myctl 
bash: /home/m.nacharov/myctl: No such file or directory
$ strace ~/myctl 
execve("/home/m.nacharov/myctl", ["/home/m.nacharov/myctl"], [/* 31 vars */]) = -1 ENOENT (No such file or directory)
write(2, "strace: exec: No such file or di"..., 40strace: exec: No such file or directory
) = 40
exit_group(1)                           = ?
+++ exited with 1 +++
$ file ~/myctl 
/home/m.nacharov/myctl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, stripped
```

We fixed this by setting `CGO_ENABLED=0` in `.goreleaser.yaml`

**To Reproduce**

Any project without `CGO_ENABLED=0` in goreleaser config file with platform specific imports.

I've created minimal example here: https://gitlab.com/m.nacharov/goreleaser-example

**Expected behavior**

I highly recommend putting some warning in the goreleaser build log when a release includes dynamically linked binaries.

**Environment (please complete the following information):**

- OS: linux
- OS version: Linux runner-pxzvflda-project-410-concurrent-0 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 GNU/Linux
- GoReleaser Version v0.161.1
- GitLab version 12.9.4-ee

**Comment by caarlos0** [comment]
It was always like this by default... if you want to static link you need to set CGO_ENABLED=0 

Not sure how changing to docker from binary changes anything as its the same goreleaser binary 🤔 

IMHO, shouldn't warning, as sometimes its what the user wants/needs.

**Comment by mnacharov** [comment]
I understand that this happened because CGO enabled by default.

And I see that default config file `.goreleaser.yaml` already disables this logic with `env: CGO_ENABLED=0`

I just think that when you use public docker image to build a binary it's quite odd to get binary dynamically linked.

**Comment by caarlos0** [comment]
the built binary is the same wether you use it on a docker image or not...

this is a critical default and it won't be changed, sorry.

thanks for the suggestion though :)
