### ISSUE TITLE
Building Go v1 apps without go mod

### ISSUE THREAD

**Issue by suntong** [goreleaser/goreleaser#2149]
**Describe the bug**

Opening a bug as per https://github.com/goreleaser/goreleaser/discussions/2148

**To Reproduce**

- duplicate from goreleaser/example
- then changed it to without go mod like this -- suntong/example@2a57053

**Expected behavior**

It still builds.

**Comment by caarlos0** [comment]
should be fixed by https://github.com/goreleaser/goreleaser/pull/2129

note that it still won't work on go 1.16, as `go build` refuses to run now if its not a module.

**Comment by suntong** [comment]
Hmm... I skimmed through the changed and think there shouldn't be anything on my side that need to change so I triggered a new build. 

But my new build failed, and on looking at it closely, I realized that my line

        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2

Is using the latest release, not the latest tag. 

How to change that to use the latest tag please? thx

**Comment by caarlos0** [comment]
the fix is not released yet

**Comment by caarlos0** [comment]
will be released on v0.162.0

**Comment by suntong** [comment]
hmm, I'm getting this:

1
Run goreleaser/goreleaser-action@v2
10
✅ GoReleaser version found: v0.162.0
11
⬇️ Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.162.0/goreleaser_Linux_x86_64.tar.gz...
12
📦 Extracting GoReleaser...
13
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/1c821f88-351d-416e-8709-0cabe169935d -f /home/runner/work/_temp/e3244d3a-bc19-4041-be4f-19a25378cbc5
14
✅ GoReleaser installed successfully
15
✅ v1.1.2 tag found for commit '2a57053'
16
🏃 Running GoReleaser...
17
/opt/hostedtoolcache/goreleaser-action/0.162.0/x64/goreleaser release --rm-dist
18
   • releasing...     
19
   • loading config file       file=.goreleaser.yaml
20
   • loading environment variables
21
   • getting and validating git state
22
      • releasing v1.1.2, commit 2a57053ad1d29aaacc64bad7d7a33bf9db2e140e
23
   • parsing tag      
24
   • running before hooks
25
   • setting defaults 
26
      • snapshotting     
27
      • github/gitlab/gitea releases
28
      • project name     
29
      • loading go mod information
30
      • building binaries
31
         • DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
32
      • creating source archive
33
      • archives         
34
      • linux packages   
35
      • snapcraft packages
36
      • calculating checksums
37
      • signing artifacts
38
      • docker images    
39
      • artifactory      
40
      • blobs            
41
      • homebrew tap formula
42
      • scoop manifests  
43
      • milestones       
44
   • snapshotting     
45
      • pipe skipped              error=not a snapshot
46
   • checking ./dist  
47
   • loading go mod information
48
   ⨯ release failed after 0.05s error=failed to get module path: exit status 1: go list -m: not using modules
49

50
Error: The process '/opt/hostedtoolcache/goreleaser-action/0.162.0/x64/goreleaser' failed with exit code 1

It _is_ using `v0.162.0`, but still failed to get module path. 

Please double check. thx.

**Comment by caarlos0** [comment]
fixed by 93a67149
