### ISSUE TITLE
Proposal: goreleaser init

### ISSUE THREAD

**Issue by lucapette** [goreleaser/goreleaser#215]
I'm setting up goreleaser for a small project today and I thought it would be nice to have a small command that speeds up the setup. Something along the line of:

```sh
$ goreleaser init # or --init. I have no particular preferences
goreleaser.yml created. Please edit accordingly to your needs.
```

It could be as simple as creating a stub or we could try to guess some sensible defaults (not sure how easy is that). If you like the idea, I can give it a try in the coming days.

Thank you one more time for this awesome project, I find myself using it for _all_ my Go projects nowadays.

**Comment by jorinvo** [comment]
We had this idea before. See #47. Back then we thought having sensible defaults can replace the need for a `goreleaser.yml` file.
There have been many new features added since then and now it seems like no project will use GoReleaser relying solely on the defaults.

I would welcome a simple *init* script that creates a configuration file with common options and some helpful comments.
What are your thoughts on this @caarlos0?

**Comment by lucapette** [comment]
Thank you for your answer @jorinvo and sorry! For some reason I couldn't find the existing discussion despite searching. 

I'd be more than happy with a skeleton with good comments. I think it would still be a better user experience than copying the config from the README.

**Comment by caarlos0** [comment]
I think it's a good idea now!

**Comment by jorinvo** [comment]
@lucapette If you like, you can give it a try then! 
I think simply adding a `goreleaser.yml` file would be enough. No need for any interactive options at this point :)

**Comment by bep** [comment]
It would also be good if that same sample config would be sent into an integration test of sorts, so we could have some guarantee that it is correct.

**Comment by caarlos0** [comment]
Yes, I thought about creating a sample file and a fake repo, and let it run every time the CI runs... but I didn't find a good way of validating it (without writing a lot of code at least)...

**Comment by lucapette** [comment]
I will have some time tomorrow and I'll give it a try. Any preference on `goreleaser --init` `goreleaser init`? Maybe the former is a bit easier to implement.

As for the test, I think it may be simple enough to assert the output is a valid `goreleaser.yml` file with some default properties. I would love to do it at acceptance level with a fake repo but, as @caarlos0 says, it may be hard without having some infrastructure for that kind of testing already in place. What I'm thinking now is that we could have a separate issue to discuss an acceptance test suite and aim to get it in for the next major version. What do you think?

**Comment by bep** [comment]
>goreleaser init

Definetively. It should be its own subcommand, it only vaguely related to the main command -- and the implementation would look funky.

**Comment by caarlos0** [comment]
+1 on `goreleaser init`.

**Comment by caarlos0** [comment]
> What I'm thinking now is that we could have a separate issue to discuss an acceptance test suite and aim to get it in for the next major version. What do you think?

Yep, #217 🍻

**Comment by caarlos0** [comment]
Validated everything, seems ok!

```
git diff 72530e7f486f4328dfd48424ebef8b8f15a36e8d..master -- config/config.go
```

properties are all right.

Will close this and release.

**Comment by caarlos0** [comment]
Just realized I forget to add docs...

**Comment by caarlos0** [comment]
v0.15.0 is out!

**Comment by caarlos0** [comment]
added goreleaser init to docs!

Thanks all!
