### ISSUE TITLE
ability to announce to twitter

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#2150]
Would be nice to be able to automatically announce releases to twitter, usually do it manually... having it automated would be neat.

**Comment by leonwright** [comment]
Hmm.. Sounds like something I'd love to work on! I'll get on it.

**Comment by leonwright** [comment]
@caarlos0 do you have a recommendation on where to put the logic for this feature in keeping with your current structure?

**Comment by caarlos0** [comment]
I would probably create an announcer interface (like the current publisher one for example) and a Twitter implementation 🤔

We could then call all the announcers in the end of the release...

**Comment by leonwright** [comment]
Alright, thanks for the help!

**Comment by leonwright** [comment]
@caarlos0 Hi, I have completed a basic implementation of this. Below is an example of the config that will need to be added for this to work. Could you please test this and let me know if this functionality is what you expected before I go ahead and clean up and submit a final pull request?
