### ISSUE TITLE
Add end-to-end tests

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#217]
The idea is to add an acceptance tests.

The idea was vaguely discussed in #215.

**Comment by bep** [comment]
I don't think I would name it "acceptance", as that indicates some kind of third-party (customer) approval. (integration test, end-to-end test ...)

**Comment by caarlos0** [comment]
goreleaser already releases itself and run several things on CI, I think we can skip this for now.

if it ever comes to be an issue, we can prioritize this.
