### ISSUE TITLE
Scoop buckets occasionally use `arm` for 64 bit targets

### ISSUE THREAD

**Issue by twpayne** [goreleaser/goreleaser#2171]
**Describe the bug**

For the last few weeks, goreleaser sometimes uses a Windows `arm` build as the 64 bit binary when generating the Scoop JSON. For example, [the Scoop JSON generated by goreleaser for chezmoi](https://github.com/twpayne/scoop-bucket/blob/master/chezmoi.json) contains:

```json
        "64bit": {
            "url": "https://github.com/twpayne/chezmoi/releases/download/v2.0.10/chezmoi_2.0.10_windows_arm.zip",
            "bin": [
                "chezmoi.exe"
            ],
            "hash": "ddf9395bef424c7ce53198dbe0c7e58597b4652d78cec4173c85473cdd5db217"
        }
```

Note the `windows_arm` in the URL. It should use the `windows_amd64` build.

Strangely, the architecture has switched back and forth between `amd64` and `arm`:

Release date |  64bit arch | Link |
| - | - | - |
Thu Apr 15 13:04:07 2021 +0200 | `arm` | https://github.com/twpayne/scoop-bucket/commit/054a071699c2bcce7fd976fe2f002dd37e3d4d5b#diff-88818b508acf0fe9fdba33f140b4c4186a58f0489b1e830256e897fa56dd4113L12 |
Sun Apr 4 21:27:12 2021 +0200 | `amd64` | https://github.com/twpayne/scoop-bucket/commit/3cd73e2a3361eb9834f4a264fc9094cbaa286ec8#diff-88818b508acf0fe9fdba33f140b4c4186a58f0489b1e830256e897fa56dd4113L12 |
Sun Apr 4 00:41:19 2021 +0200 | `arm` | https://github.com/twpayne/scoop-bucket/commit/94d436b35f8b6264e1a1cb5bf9ee5779e689dd6f#diff-88818b508acf0fe9fdba33f140b4c4186a58f0489b1e830256e897fa56dd4113L12 |
All previous | `amd64` | https://github.com/twpayne/scoop-bucket/commit/3635351cfa31e974024f4fada50eaa719e834a67#diff-88818b508acf0fe9fdba33f140b4c4186a58f0489b1e830256e897fa56dd4113L12 |

**To Reproduce**

I can only reproduce this by doing a release. Is there a way to see the generated Scoop JSON without actually doing a release?

This is [my goreleaser config file](https://github.com/twpayne/chezmoi/blob/master/.goreleaser.yaml).

**Expected behavior**

The Windows `amd64` binary is always used in the Scoop bucket, never the `arm` one.

**Environment (please complete the following information):**

- OS: Linux
- OS version: Linux groovy 5.8.0-48-generic #54-Ubuntu SMP Fri Mar 19 14:25:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- GoReleaser Version 0.162.0

**Additional context**

I suspect that this was caused by #2144, the timing matches.

Refs https://github.com/twpayne/chezmoi/issues/1164. cc @Tyrubias

**Comment by caarlos0** [comment]
Thanks @twpayne!
