### ISSUE TITLE
Will try to create a GitHub discussion even if discussion_category_name is not set

### ISSUE THREAD

**Issue by tliron** [goreleaser/goreleaser#2181]
An example of the error:
```
release failed after 14.47s error=github/gitlab/gitea releases: failed to publish artifacts: PATCH https://api.github.com/repos/tliron/puccini/releases/41794427: 404 Discussion could not be created. Make sure you passed a valid category name. []
```

**Comment by trenton42** [comment]
Just saw this as well. Looks like this is the culprit:
https://github.com/goreleaser/goreleaser/blob/b44f8b5781738cb05ad795bbcffc05c64a491c68/internal/client/github.go#L147

It passes an empty string instead of `nil`, which Github doesn't like.

**Comment by caarlos0** [comment]
thanks for pointing it out, totally missed this..
