### ISSUE TITLE
artifactory upload fails if package name contains hyphen

### ISSUE THREAD

**Issue by kplimack** [goreleaser/goreleaser#2185]
**Describe the bug**

Artifactory expects an environment variable containing the password or API key. This was added in https://github.com/goreleaser/goreleaser/pull/429

The environment variable which it expects is `ARTIFACTORY_<pkg-name>_SECRET`.  When the package name has a hyphen `-` in it, it is no longer a valid shell variable.

```
• pipe skipped              error=artifactory section 'go-mygoapp' is not configured properly
 (environment variable 'ARTIFACTORY_GO-MYGOAPP_SECRET' is required when 'username' is set)
```

**Expected behavior**
I expect that `goreleaser` will normalize the package name so that a valid environment variable name is produced.  Perhaps replacing hyphens with underscores or double-underscores, would suffice.

**Comment by caarlos0** [comment]
what was the issue?
