### ISSUE TITLE
Custom release notes should not be parsed as a Go template

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#2196]
Ref. https://github.com/goreleaser/goreleaser/blob/5866b9cb637859bfc530da78d9bd5a0b411e170c/internal/pipe/changelog/changelog.go#L39

I have had a couple of Hugo releases fail on me recently because I have put some Hugo template code as examples in the release notes, which uses template funcs that does not exist in Goreleaser => fail.

I'm not sure why you need to treat these as a Go template?

**Comment by caarlos0** [comment]
Yes, sounds like something we should not do indeed.

Thanks for reporting!

**Comment by caarlos0** [comment]
This was added on purpose on https://github.com/goreleaser/goreleaser/issues/1453

Maybe you'll need to escape those examples? 

e.g.
 
```
{{`{{ .Blah }}`}}
```

**Comment by bep** [comment]
>Maybe you'll need to escape those examples?

I have no idea how that would work; these are Go template examples inside code fenced block in Markdown, so they need to ... look like Go templates.

The only current workaround that I see is to create a parser that replaces these blocks with placeholders that I then somehow ... Nevermind, it would probably be easier to ... fork Goreleaser :-{

I would say that #1453 was a pretty breaking change and I could think of plenty of ways to handle that smoother without these unexpected side effects, ref. the CLI docs:

```bash
 --release-notes string    Load custom release notes from a markdown file
```

**Comment by caarlos0** [comment]
yeah, makes sense... 

probably revert that and move to another flag (e.g. `--release-notes-template`)

**Comment by caarlos0** [comment]
cc/ @ccremer as you are the author of the other PR...

**Comment by ccremer** [comment]
> probably revert that and move to another flag (e.g. `--release-notes-template`)

making a dedicated flag sounds good to me.

**Comment by caarlos0** [comment]
Mind testing/checking https://github.com/goreleaser/goreleaser/pull/2242 ?

**Comment by caarlos0** [comment]
thanks @bep and @ccremer 🤘
