### ISSUE TITLE
custom publishers should preserve env vars

### ISSUE THREAD

**Issue by meier-christoph** [goreleaser/goreleaser#2201]
**Is your feature request related to a problem? Please describe.**

Custom publishers is a nice feature and I totally get why you didn't copy env vars but it should at least have an option to so.

As it is now, in my case at least, I need to set PATH, TMP, LOCALAPPDATA and some more and to make it worse .Env.PATH != .Env.Path and since I need to run this on both windows and linux ... well its a mess.

**Describe the solution you'd like**

A simple flag which, if is set, preserves existing env vars for custom publishers. Leave it off by default for backwards compatibility.

**Comment by caarlos0** [comment]
seems easy enough, but maybe would be even better to keep the "expected" envs by default (PATH, TMP, HOME, etc?)

cc/ @radeksimko thoughts?

**Comment by radeksimko** [comment]
Yeah, that sounds reasonable. We could pass through the following:

- `HOME`
- `USER`
- `USERPROFILE`
- `TMPDIR`
- `TMP`
- `TEMP`
- `PATH`

which at AFAIK corresponds to some basic common operations within Go stdlib; across Windows and Unix - at least that's what we did some time ago in another project: https://github.com/hashicorp/terraform-ls/blob/bc69f994136d741deb627f68b57479bb70c6eb9e/internal/terraform/exec/exec.go#L24-L32

I wouldn't oppose _strongly_ an introduction of some sort of opt-in inheritance, but if the above pass-through list can solve most of the problems then I'd be much happier.

**Comment by caarlos0** [comment]
> I wouldn't oppose _strongly_ an introduction of some sort of opt-in inheritance, but if the above pass-through list can solve most of the problems then I'd be much happier.

yeah, that sounds like the best option for me as well
