### ISSUE TITLE
brew should create the dist/formula.rb file when --skip-publish is set

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#2203]
This broke something for me. It no longer generates the formulas in the dist folder for me be debug the configuration 😭

_Originally posted by @kreempuff in https://github.com/goreleaser/goreleaser/issues/2193#issuecomment-833001315_

**Comment by kreempuff** [comment]
Thanks for filing the issue for me!

**Comment by kreempuff** [comment]
@frankywahl can you elaborate more on the issue you faced in #2193. It broke debugging formulas for me and I wan to take a stab at fixing it

**Comment by frankywahl** [comment]
@kreempuff Sure. I would run `release --rm-dist --skip-publish --snapshot`  and would see the following

<details><summary> Sample output</summary>

```
# ... 

 • publishing
      • blobs
      • http upload
      • custom publisher
      • artifactory
      • docker images
         • pipe skipped              error=publishing is disabled
      • docker manifests
         • pipe skipped              error=publishing is disabled
      • snapcraft packages
         • pipe skipped              error=publishing is disabled
      • github/gitlab/gitea releases
         • pipe skipped              error=publishing is disabled
      • homebrew tap formula
   ⨯ release failed after 57.40s error=homebrew tap formula: failed to publish artifacts: no linux/macos archives found
make: *** [local_release] Error 1
```
</details>

Note the status code would also be `2` so would fail along a CICD

**Comment by kreempuff** [comment]
@frankywahl do you mind sharing your goreleaser config or a similar enough sample?

**Comment by frankywahl** [comment]
@kreempuff https://gist.github.com/frankywahl/13de504e5f6f68124232ef2e624038b6 I believe outlines it. I run it with `make`, but it assumes you have `docker` installed.

**Comment by kreempuff** [comment]
Thanks for looking into this!
