### ISSUE TITLE
Support for not-tag-based releases/snapshots

### ISSUE THREAD

**Issue by zerok** [goreleaser/goreleaser#222]
Hi :)

Related to #68 would it perhaps make sense to also support something like snapshot releases? I'm currently working on a project where I don't yet have any tags but would still love to use goreleaser for some test-builds.

Would it perhaps make sense to support something like a "SNAPSHOT-{commit-sha}" version if no tag can be found or explicitly passing a version as commandline argument?

**Comment by caarlos0** [comment]
Hi @zerok , you want to build a release to test locally?

If so, try `--skip-validate --skip-publish`

**Comment by zerok** [comment]
@caarlos0 : Pretty much, yes :) Sadly, I've already tried these options before opening this ticket:

```
$ goreleaser --skip-validate --skip-publish
Running goreleaser v0.14.0
Setting defaults
Getting and validating git state
fatal: No names found, cannot describe anything.
```

It might be an issue with `git describe` having changed its behaviour as this is also the output of running `git describe --tags` (which exits with status code 128).

**Comment by caarlos0** [comment]
hmm.. yeah, maybe we should allow it to fail when `--skip-validate` is set..

**Comment by zerok** [comment]
@caarlos0 would you mind if I try creating a PR for that? Would like to help with code :)

**Comment by caarlos0** [comment]
@zerok sure, go ahead =D

**Comment by zerok** [comment]
@caarlos0 Thank you :D I will try to get something done either by tomorrow or by Monday :)

**Comment by jorinvo** [comment]
@zerok Just keep in mind that skipping the test which checks if Git is currently using a tag as branch, will not fix the problem this check is trying to prevent:
Without this check you get the source from which ever branch is checked out locally but the version used by GoReleaser will be named like the latest tag available.
To prevent this, we could - as you suggested - set the version to something like `"SNAPSHOT-{commit-sha}"` when `getInfo` fails (https://github.com/goreleaser/goreleaser/blob/master/pipeline/git/git.go#L108).

**Comment by zerok** [comment]
That's pretty much what I'm aiming for right now 😊

**Comment by caarlos0** [comment]
Done on v0.16.0!

Thanks @zerok and @jorinvo =)

**Comment by zerok** [comment]
Thank you, @jorinvo , @lucapette , and @caarlos0, for reviewing the code and merging 😃
