### ISSUE TITLE
Install goreleaser githhub action failed with v0.166.1

### ISSUE THREAD

**Issue by Nexucis** [goreleaser/goreleaser#2258]
**Describe the bug**

I'm using the github action to install goreleaser, and since the last version (v0.166.1) it doesn't work anymore. See below the screen:

![image](https://user-images.githubusercontent.com/4548045/119688238-1984fa00-be48-11eb-9f42-d4d5d6a70988.png)

* link to the complete log of the job: https://github.com/perses/perses/runs/2676574189?check_suite_focus=true

* link to the github action : https://github.com/perses/perses/blob/93a0c7961d682e78a691f83c51561257eb21afaa/.github/workflows/build.yaml#L53

It works with the previous version (v0.165.0)

Is there a thing to change in the configuration of the github action ?

**Comment by danielcooperxyz** [comment]
Looks like the latest version has no assets that can be downloaded, so the script fails as the expected tar file is not received.

**Comment by dariusbakunas** [comment]
Was able to get around it by setting `version: 0.166.0` in github workflow file

**Comment by danielcooperxyz** [comment]
Looks like you can pin the version using the bash script with the following

    curl -sL https://git.io/goreleaser | VERSION=v0.166.0 bash

**Comment by caarlos0** [comment]
Should be good now, thanks for reporting :)

**Comment by Nexucis** [comment]
so cool. It works now, thank you so much !
