### ISSUE TITLE
Introducing godownloader - the inverse of goreleaser.

### ISSUE THREAD

**Issue by client9** [goreleaser/goreleaser#227]
Hi,  not sure where to post this, so apologies if this isn't the right spot.

I love goreleaser and will be using it for a few tools I have.   But I got tired of writing crappy shell scripts to figure how to download a particular item off GitHub releases, so I wrote a program to write crappy shell scripts for me.

https://github.com/client9/godownloader

`godownloader` reads the `goreleaser.yaml file` and generates a shell script that will download the latest or particular version of a goreleaser binary.  It takes into account all the replacements and over-rides.

I'm happy to donate this into the goreleaser project after I get this a touch more organized.  I just saw the https://github.com/goreleaser/get repo and has a bunch of good tricks I should re-use.

Comments welcome here or over at https://github.com/client9/godownloader

thanks again for such a great project!

n

(this might be useful in end-to-end tests as well)

**Comment by caarlos0** [comment]
Love it!

If want to donate, I'll be happy to accept and add you to the org =D

**Comment by client9** [comment]
fantastic... "it's better, together"   I'll attempt to change ownership to the goreleaser and see what happens.

**Comment by client9** [comment]
Hi @caarlos0 I don't have permission to transfer it to "goreleaser", so I would just make a new repo goreleaser/godownloader  and add me as contributor, and I'll just copy it over manually.  It's like 3 or 4 files so no problem.

**Comment by caarlos0** [comment]
let me add you to the org, then you can try again...

1m

**Comment by caarlos0** [comment]
@client9 you can accept the invite at https://github.com/goreleaser =)

**Comment by client9** [comment]
I'm in.

It's transfered.

and accepted a pull request to godownloader already!

closing -- thanks all!
