### ISSUE TITLE
Latest release 0.166.2 broke homebrew upgrade on arm Mac M1

### ISSUE THREAD

**Issue by abtris** [goreleaser/goreleaser#2270]
**Describe the bug**

Latest release 0.166.2 broke homebrew upgrade on Arm Mac M1

**To Reproduce**

```
$ brew update && brew upgrade

==> Upgrading 1 outdated package:
goreleaser/tap/goreleaser 0.166.1 -> 0.166.2
==> Upgrading goreleaser/tap/goreleaser 0.166.1 -> 0.166.2
goreleaser: The x86_64 architecture is required for this software.
Error: goreleaser: An unsatisfied requirement failed this build.
```

**Expected behavior**

Upgrade done as usually. 

**Environment (please complete the following information):**

- OS: mac
- OS version: 11.4 - arm64

**Comment by caarlos0** [comment]
oh, thanks for reporting @abtris 

fixed on master, will release soon
