### ISSUE TITLE
Support globbing for "archive: > files:"

### ISSUE THREAD

**Issue by dogancelik** [goreleaser/goreleaser#229]
`archive: > files:` setting should support globbing.
It only supports including files in root folder.

* If you do `public/`, it only creates the folder, **no files inside.**
* If you do `public/*`, it should only add immediate (only root) files of `public/` → **errors.**
* If you do `public/**`, it should add all files inside *public* folder → **errors.**

```
$ goreleaser --skip-validate --skip-publish
Running goreleaser 0.17.3
Setting defaults
Getting and validating git state
 -> Skipped validations because --skip-validate is set
Loading environment variables
 -> GITHUB_TOKEN not validated because publishing has been disabled
Building binaries
 -> Building dist\seps_windows_amd64\seps.exe
 -> Building dist\seps_linux_amd64\seps
 -> Building dist\seps_mac_amd64\seps
Creating archives
 -> Creating dist\seps_mac_amd64.tar.gz
 -> Creating dist\seps_linux_amd64.tar.gz
 -> Creating dist\seps_windows_amd64.zip
open public/**: The filename, directory name, or volume label syntax is incorrect.
```

Goreleaser version: `0.17.3, commit 2af8d94f94b9e67134787e63c042943084f12b0d, built at 2017-05-10T13:51:16Z`

**Comment by caarlos0** [comment]
can you check #231?

**Comment by caarlos0** [comment]
Done on v0.18.0
