### ISSUE TITLE
failed to publish scoop manifest with sub directory

### ISSUE THREAD

**Issue by meier-christoph** [goreleaser/goreleaser#2310]
**Describe the bug**

```
scoop manifests: failed to publish artifacts: failed to write scoop manifest: open dist/bucket/my-app.json: no such file or directory
```

I think there is a missing mkdir here:
https://github.com/goreleaser/goreleaser/blob/v0.171.0/internal/pipe/scoop/scoop.go#L113

**To Reproduce**

```yaml
scoop:
  name: bucket/my-app
```

**Expected behavior**

You should be able to use sub folders e.g. bucket in the scoop repository.

**Environment (please complete the following information):**

- OS: [e.g. mac, linux] linux
- OS version: [uname -a]
- GoReleaser Version [goreleaser --version] 0.171.0
- GitLab version (if using a private hosted one)

**Comment by caarlos0** [comment]
probably we need to add a `folder` option as we have on homebrew...
