### ISSUE TITLE
builds.main value does not seem to go through name template engine

### ISSUE THREAD

**Issue by maguro** [goreleaser/goreleaser#2321]
**Describe the bug**

The value of `builds.main` does not seem to go through the name template engine.  If I add a variable in the value, it is not substituted.

**To Reproduce**

```yaml
builds:
  - id: default
    main: "./cmd/{{ .ProjectName }}"
```

I get the error

```console
   ⨯ release failed after 0.19s error=couldn't find main file: stat cmd/{{ .ProjectName }}: no such file or directory
```

**Expected behavior**

For project name `foo` I expect the value of `builds.main` to be `./cmd/foo`

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`
- GoReleaser Version 
```
goreleaser version 0.172.1-pro
commit: 649857125304556465a68ed7927a812ec29282c9
built at: 2021-06-27T15:25:04Z
built by: goreleaser
````

**Comment by caarlos0** [comment]
not a bug, nowhere it says it is templateable, so this is more of a feature request.
