### ISSUE TITLE
checksum file formating is slightly off compared to standard linux tools

### ISSUE THREAD

**Issue by client9** [goreleaser/goreleaser#233]
Hi,

As part of https://github.com/goreleaser/godownloader/issues/5  I'm processing / parsing the checksum file that is generated.

It appears " the standard" is  HASH-TWOSPACES-FILENAME (one space as delimiter, one other space indicating something else.. it could be a '*' or '?' but no one seems to use them).

goreleaser is doing HASH-TAB-FILENAME  which sha256sum and all it variations do not like.  sha256sum -c barfs when  this is passed in.  I've tested macOS, busy box and gnu implementations.  All do not like it.

I do not know anything about windows, so no idea.

Any idea why tab is used?

Not a huge deal as I can hack around this via regular unix CLI tools.

If you want me to fix I can submit a PR (trivial).

n

**Comment by caarlos0** [comment]
@client9 no particular reason. PR is welcome :D

**Comment by caarlos0** [comment]
I'll fix this right away

**Comment by client9** [comment]
rock
