### ISSUE TITLE
Consider issuing warning or log message  if no goreleaser.yml file found

### ISSUE THREAD

**Issue by client9** [goreleaser/goreleaser#235]
I have no numbers to support this, but I suspect "most repos use a gorelease.yml file if they use goreleaser"

Consider issuing a warning if `goreleaser.yml` is not found, and/or a verbose mode that says where it's getting the config from

I was confused since I named my file `.goreleaser.yml` (with dot) by mistake.

not a big deal but might help the next person.

**Comment by caarlos0** [comment]
Makes sense!

**Comment by caarlos0** [comment]
releasing v0.18.1
