### ISSUE TITLE
[Bug]: go install command is wrong

### ISSUE THREAD

**Issue by szuecs** [goreleaser/goreleaser#2352]
### What happened?

https://goreleaser.com/install/#go-install says to use:
```
% go install github.com/goreleaser/goreleaser
go install: version is required when current directory is not in a module
        Try 'go install github.com/goreleaser/goreleaser@latest' to install the latest version
```

You need to add `@latest`
```
go install github.com/goreleaser/goreleaser@latest
```

### How can we reproduce this?

Use https://goreleaser.com/install/#go-install to run the command with a recent go installation.

### goreleaser version

```bash
does not apply
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
Thanks!
