### ISSUE TITLE
[Bug]: files are moved to a subdir with the same name

### ISSUE THREAD

**Issue by ldez** [goreleaser/goreleaser#2366]
### What happened?

In the binary packages of the new version (v0.174.0) the license and the readme are placed into sub-directory with the same name of the file.

https://github.com/goreleaser/goreleaser/releases/tag/v0.174.0

```
.
├── completions
│   └── *
│       └── completions
│           ├── goreleaser.bash
│           ├── goreleaser.fish
│           └── goreleaser.zsh
├── goreleaser
├── LICENSE.md
│   └── LICENSE.md
└── README.md
    └── README.md
```

### How can we reproduce this?

Download the archives:

https://github.com/goreleaser/goreleaser/releases/download/v0.174.0/goreleaser_Linux_x86_64.tar.gz

### goreleaser version

```bash
v0.174.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

https://aur.archlinux.org/packages/goreleaser-bin/#comment-818959

**Comment by caarlos0** [comment]
oh, good catch, thanks!
