### ISSUE TITLE
[Bug]: go-releaser-action fails to extract goreleaser v0.174.0 on windows

### ISSUE THREAD

**Issue by NoamDolovichWS** [goreleaser/goreleaser#2367]
### What happened?

Starting from version v0.174.0, the goreleaser-action no longer works for us (we expect it to run successfully without errors).
The following exception is thrown:
```
✅ GoReleaser version found: v0.174.0
⬇️ Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.174.0/goreleaser_Windows_x86_64.zip...
📦 Extracting GoReleaser...
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.ZipFile } catch { } ; try { [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\3c96db25-4e6f-4fac-9ded-ad1cefc6381c', 'D:\a\_temp\7165d2d5-8443-4472-b08f-7829ff58a74c', $true) } catch { if (($_.Exception.GetType().FullName -eq 'System.Management.Automation.MethodException') -or ($_.Exception.GetType().FullName -eq 'System.Management.Automation.RuntimeException') ){ Expand-Archive -LiteralPath 'D:\a\_temp\3c96db25-4e6f-4fac-9ded-ad1cefc6381c' -DestinationPath 'D:\a\_temp\7165d2d5-8443-4472-b08f-7829ff58a74c' -Force } else { throw $_ } } ;"
Exception: Exception calling "ExtractToDirectory" with "3" argument(s): "The filename, directory name, or volume label syntax is incorrect. : 'D:\a\_temp\7165d2d5-8443-4472-b08f-7829ff58a74c\completions\*\completions'"
Error: The process 'C:\Program Files\PowerShell\7\pwsh.exe' failed with exit code 1
```

It appears that the problematic path is  'D:\a\_temp\7165d2d5-8443-4472-b08f-7829ff58a74c\completions\*\completions'. After taking a look at the goreleaser_Windows_x86_64.zip file for version v0.174.0, it appears that the internal directory structure has changed:

Previously, it looked like this:
```
.
├── completions
│   └── *
│       └── completions
│           ├── goreleaser.bash
│           ├── goreleaser.fish
│           └── goreleaser.zsh
├── goreleaser.exe
├── LICENSE.md
│   └── LICENSE.md
└── README.md
    └── README.md

5 directories, 6 files
```

And now it looks like this:
```
.
├── completions
│   ├── goreleaser.bash
│   ├── goreleaser.fish
│   └── goreleaser.zsh
├── goreleaser.exe
├── LICENSE.md
└── README.md

1 directory, 6 files
```

I'm assuming that the "*" in the path is what's causing the issue, as this is an illegal character for Windows file names.

### How can we reproduce this?

The issue can be reproduced by running the `goreleaser` workflow located here:
https://github.com/NoamDolovichWS/GoReleaserReproduce

In addition, an example run with the success/failures can be accessed here:
https://github.com/NoamDolovichWS/GoReleaserReproduce/actions/runs/1067204591

### goreleaser version

```bash
goreleaser version 0.174.0
commit: 1dd2ad1ae6c509c01bb598e1698686ac2ae6557c
built at: 2021-07-25T00:32:04Z
built by: goreleaser
module version: v0.174.0, checksum: h1:Tb/0IO9PuFPLjuh97aSLbDlAL8HMKWS2rvyo8oN1FxE=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I've reproduced this issue with goreleaser-action, but I believe this may impact other environments and usages as well.

**Comment by caarlos0** [comment]
duplicates #2366

fix already being built
