### ISSUE TITLE
[Bug]: On the Release page, the GitLab/GitHub content is the wrong way round

### ISSUE THREAD

**Issue by wywywywy** [goreleaser/goreleaser#2370]
### What happened?

On the Release page of the documentation, the GitHub section shows code for GitLab.  The GitLab section shows code for GitHub.

### How can we reproduce this?

https://goreleaser.com/customization/release/

https://github.com/goreleaser/goreleaser/blob/master/www/docs/customization/release.md

### goreleaser version

```bash
Latest deployed as of 2021-07-26
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
sorry, I don't see it... which part of the code specifically? For me it looks correct 🤔

**Comment by caarlos0** [comment]
oh, just saw it
thanks for reporting
