### ISSUE TITLE
[Bug]: Scoop pipeline does not write out .json file with --skip-publish

### ISSUE THREAD

**Issue by jonaslu** [goreleaser/goreleaser#2374]
### What happened?

When having a valid scoop config in the .gorelease.yml and running `goreleaser release --skip-publish` it should write the <project>.json file to the dist/ folder but not publish it. This is how the homebrew pipeline works and should be consistent with the --skip-publish flag according to the docs (user is resposible for publishing the produced files).

### How can we reproduce this?

Run `goreleaser release --skip-publish` in the goreleaser (this repo:s) top folder. A goreleaser.json is not written to the dist/ folder.

### goreleaser version

```bash
goreleaser version dev
module version: v0.174.1, checksum: h1:els5gB5csBDQbgx0zVoIaEAKWGebc8Lu1kUH4yibMzs=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

It's a simple deletion of three lines on https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/scoop/scoop.go#L37 - I'd be happy to submit a fix if this is a valid error

**Comment by caarlos0** [comment]
It's not that simple actually... you can dig into the `brew` pipe code to see how it works there...

**Comment by jonaslu** [comment]
Sorry, that might have come off as snarky. Didn't mean to. From here they look very similar, but maybe I'm missing the greater context. On line https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/scoop/scoop.go#L121 there is another check if `ctx.SkipPublish` which might be redundant since the one on like 37 already returns if `ctx.SkipPublish` is true. This is also how the brew-pipeline works as far as I can tell - assemble data, write file, return if `ctx.SkipPublish`.

But is it a valid bug? Should the scoop pipeline write out the manifest.json file with the `--skip-publish` flag or not?

**Comment by caarlos0** [comment]
> Sorry, that might have come off as snarky.

don't worry, didn't sound like it :) 



> ut is it a valid bug? Should the scoop pipeline write out the manifest.json file with the `--skip-publish` flag or not?

I think it should yeah. Valid bug.

> This is also how the brew-pipeline works as far as I can tell - assemble data, write file, return if `ctx.SkipPublish`.

indeed, you are right... I confused things because this was different at some point. Yeah, feel free to shoot a PR removing that check. Bonus points if there is a test for it as well 🙏

Thanks for looking into this 🤘

**Comment by jonaslu** [comment]
PR created. Didn't see a good way of using test-tables, since all tests need to write out a manifest.json file to a dist/ folder - and relying on different project names might be confusing
