### ISSUE TITLE
homebrew/scoop/gofish: allow to customize the branch

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#2388]
currently it always goes to the default branch... we should allow to customize that for cases in which the default branch is protected.

see https://github.com/goreleaser/goreleaser/discussions/2387

**Comment by siddhant-deepsource** [comment]
Hey @caarlos0,

I would like to help out to fix this. Would need some help and guidance as to how should I approach this. We can maybe create a new field `branch` which the users can specify in the `goreleaser` config. It can default to `master` or `main` (whichever is currently followed).

If the user sets this branch, we can commit to this branch instead. We  might have to handle the case in which the set branch by user doesn't exist. What do you think? Looking forward to your views about this. Thanks 🙂

**Comment by caarlos0** [comment]
my idea was:

- add a `branch` field which defaults to empty  - which clients will handle as default branch if I recall correctly
- if the branch is set, check if it exists, create it in case it doesn't
- commit the file on the given branch

that should probably be handled in the [client package](https://github.com/goreleaser/goreleaser/tree/master/internal/client)

**Comment by siddhant-deepsource** [comment]
@caarlos0 Neat, should we also create pull request from the set branch to the default branch?

**Comment by caarlos0** [comment]
we might, but then we should do it for both gitlab, github and gitea

**Comment by caarlos0** [comment]
this is merged, will be released on next. 

Closing

thanks everyone!
