### ISSUE TITLE
[Bug]: `.VERSION` is wrong in `--snapshot` mode.

### ISSUE THREAD

**Issue by cimnine** [goreleaser/goreleaser#2415]
### What happened?

The template variable `{{ .Version }}` behaves differently when Goreleaser is invoked regularly vs. when it is invoked with `--snapshot`:

- In regular mode it strips the `v` from the tag, i.e. if the tag is `v1.2.3`, then `.Version` becomes `1.2.3`.
- But in snapshot mode, this does not happen. So if the most recent tag is `v1.2.3`, then `.Version` becomes `v1.2.3-snapshot`.

We use `.Version` in `docker.image_templates` as follows:

```yaml
dockers:
- image_templates:
  - "docker.io/foo/bar:v{{ .Version }}"
```

When we do a regular release, the image that is built becomes `docker.io/foo/bar:v1.2.3`. But when we build a snapshot, then the image that is built becomes `docker.io/foo/bar:vv1.2.3-snapshot`, which is unexpected.

#### Prepare

```bash
git clone https://github.com/cimnine/goreleaser-bug.git reproduce
cd reproduce
```

#### Correct Version

```bash
$ goreleaser release --skip-publish --rm-dist
[…]
   • docker images
      • building docker image     image=docker.io/foo/bar:v1.0.1
[…]
```

#### Incorrect Version

```bash
$ goreleaser release --skip-publish --rm-dist --snapshot
[…]
   • docker images
      • building docker image     image=docker.io/foo/bar:vv1.0.2-next
[…]
```

### goreleaser version

```bash
goreleaser version 0.175.0
commit: 5e006eb236284c29143341e48c2f692826865d47
built by: homebrew

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
you can tweak that by changing `snapshot.name_template`: https://goreleaser.com/customization/snapshots/

probably you have the v prefix there.

**Comment by cimnine** [comment]
Indeed, our `snapshot.name_template` was set to `"{{ .Tag }}-snapshot` instead of `{{ .Version }}-snapshot`. Thanks!

**Comment by cimnine** [comment]
I just checked and to confirm: It is the default behaviour that `snapshot.name_template` is set to `"{{ incpatch .Tag }}-next"`. Maybe that should be adjusted to `"{{ incpatch .Version }}-next"`?

**Comment by caarlos0** [comment]
yeah, I think it makes sense, can you open a pr?

**Comment by cimnine** [comment]
> yeah, I think it makes sense, can you open a pr?

Sure, see https://github.com/goreleaser/goreleaser/pull/2417.
