### ISSUE TITLE
[Bug]: Go mod tidy hook fails to fetch dependency

### ISSUE THREAD

**Issue by tommyalatalo** [goreleaser/goreleaser#2418]
### What happened?

Goreleaser fails to fetch a go module dependency when running a `before` hook with simply `go mod tidy` in a Gitlab CI pipeline, output below. It seems that the url encoding might be wrong as the url is `github.com/PuerkitoBio/goquery@v1.7.1` but the job ends up fetching `https://pkg.go.dev/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod` which in a browser ends up at an error page with the message `"github.com/!puerkito!bio/goquery/v1.7.1.mod" is not a valid import path`.

Removing go.mod and go.sum and the running `go mod init bliss` and `go mod tidy` work fine locally, which is why this seems suspicious.

```
task: goreleaser release --skip-publish --skip-validate --rm-dist --release-notes <(git-chglog $(svu current))
   • releasing...     
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • building...               commit=6130a03abd20c8c15b7e73e69ec2546225124967 latest tag=v0.0.0
      • pipe skipped              error=validation is disabled
   • parsing tag      
   • running before hooks
      • running                   hook=go mod tidy
   ⨯ release failed after 5.23s error=hook failed: go mod tidy: exit status 1; output: go: github.com/PuerkitoBio/goquery@v1.7.1: reading https://pkg.go.dev/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod: 400 Bad Request
go: downloading github.com/influxdata/influxdb1-client v0.0.0-20200827194710-b269163b24ab
go: downloading github.com/PuerkitoBio/goquery v1.7.1
go: downloading github.com/go-redis/redis/v8 v8.11.3
go: downloading golang.org/x/text v0.3.7
go: downloading go.uber.org/zap v1.19.0
go: downloading github.com/stretchr/testify v1.7.0
go: downloading github.com/alicebob/miniredis v2.5.0+incompatible
go: downloading github.com/tommyalatalo/surf v1.0.2
go: downloading github.com/prometheus/client_golang v1.11.0
go: downloading github.com/gregdel/pushover v1.1.0
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/spf13/viper v1.8.1
go: downloading github.com/spf13/cobra v1.2.1
go: downloading github.com/testcontainers/testcontainers-go v0.11.1
go: downloading github.com/alicebob/miniredis/v2 v2.15.1
go: downloading github.com/elliotchance/redismock/v8 v8.6.2
go: downloading github.com/lithammer/fuzzysearch v1.1.2
go: downloading github.com/leekchan/accounting v1.0.0
go: github.com/PuerkitoBio/goquery@v1.7.1: reading https://pkg.go.dev/github.com/%21puerkito%21bio/goquery/@v/v1.7.1.mod: 400 Bad Request
```

### How can we reproduce this?

Check my [gitlab project branch](https://gitlab.com/altosys/bliss/-/tree/add-walts-comic-shop) for the code which fails the ci job, see the [pipeline job](https://gitlab.com/altosys/bliss/-/jobs/1522813214#L96) for the output.

### goreleaser version

```bash
docker container goreleaser/goreleaser:v0.175.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
goreleaser does not do anything with go.mod files et al, it will literally just run `go mod tidy`, if that's failing, its something else...

**Comment by tommyalatalo** [comment]
For future reference if anyone passes by this issue, the problem was having `GOPROXY=https://pkg.go.dev`, changing this to `GOPROXY=https://goproxy.io` or disabling `GOPROXY` entirely fixes it.
