### ISSUE TITLE
Git repository as release target

### ISSUE THREAD

**Issue by suntong** [goreleaser/goreleaser#242]
So far goreleaser creates & put release executables into  GitHub release, right? 

- Can it also [create .rpm packages (besides .deb) as well like this](https://github.com/mh-cbon/go-github-release/)? 
- It'd be nice to [put the .deb or .rpm packages into repositories as well like this](https://github.com/mh-cbon/go-github-release/).
- and moreover, it is even better that [different tools can go into a central repository](https://github.com/mh-cbon/go-github-release/issues/6). E.g., if I have 10 different tools/packages, they'd better be within one central repository, instead of spreading over 10 different ones. 

Thanks

**Comment by jorinvo** [comment]
> Can it also create .rpm packages (besides .deb) as well like this?

Yes, via fpm: https://github.com/goreleaser/goreleaser#fpm-build-customization

> It'd be nice to put the .deb or .rpm packages into repositories as well like this.

.deb and .rpm files are added, as you can see here https://github.com/goreleaser/goreleaser/releases/tag/v0.20.0

> and moreover, it is even better that different tools can go into a central repository. E.g., if I have 10 different tools/packages, they'd better be within one central repository, instead of spreading over 10 different ones.

Please have a look at this discussion: https://github.com/goreleaser/goreleaser/issues/49

**Comment by suntong** [comment]
That https://github.com/goreleaser/goreleaser/issues/49 talks about putting multiple binaries from the same package into a repo, right? 

I'm talking about putting binaries from different projects into one central repo. Slightly, but different.

**Comment by jorinvo** [comment]
@suntong a sorry, I got that wrong.
You mean instead of releasing to GitHub Releases you would like to release the files to a Git repository?

**Comment by suntong** [comment]
Yeah, almost -- It'd be nicer to [put the .deb (or .rpm) packages into repositories like this to GH page](https://github.com/mh-cbon/go-github-release/), so anyone who like to use any of the tools I'm building, they just need to add my PPA _only once_, and the rest are just _as normal as_ `apt-get`.

**Comment by jorinvo** [comment]
Ok, if you can not only specify the repository but also the branch, then it would work?

We could add Git repositories as release targets, the same way we plan for Gitlab and others.
We could borrow from the Homebrew releasing logic, since this also just uploads files to a repository.

**Comment by suntong** [comment]
Yeah, @mh-cbon was able to successfully generate one, and I did a comparison once between it and my PPA, and it looks good.

**Comment by jorinvo** [comment]
I will save this issue as a feature request for Git repository as a release target.
Not sure when we will get around to implement this though.
If you are interested, you are welcome to send a pull request.

**Comment by suntong** [comment]
Alright, I'll talk with @mh-cbon, and if he is not interested, I'll see what I can do...

**Comment by suntong** [comment]
I don't have any knowledge on goreleaser, so let me first document how @mh-cbon did it, the whole process of building a `gh-pages` repository, which seems pretty straightforward. 

- After [creating .deb package in the `before_deploy` step](https://github.com/mh-cbon/emd/blob/master/.travis.yml#L43), 
- [In the `after_deploy` step of .travis.yml](https://github.com/mh-cbon/emd/blob/master/.travis.yml#L48), [invoke mh-cbon/go-bin-deb/setup-repository.sh](https://github.com/mh-cbon/go-bin-deb/blob/master/setup-repository.sh).
- which in turn [get and execute github.com/mh-cbon/go-bin-deb/go-bin-deb-utils](https://github.com/mh-cbon/go-bin-deb/blob/master/setup-repository.sh#L11)
- The [go-bin-deb-utils](https://github.com/mh-cbon/go-bin-deb/tree/master/go-bin-deb-utils) is just a normal tool written in Go with MIT license. Just its usage is still unclear to me, even after I've read the README. 

So, question to all goreleaser authors and contributors, would you like to fork https://github.com/mh-cbon/go-bin-deb into/under https://github.com/goreleaser/ first? Would you like to keep it original name? This the watershed decision before I can move any further.

**Comment by suntong** [comment]
Hi @solvingJ, Saw your recent discussion on [go-github-release](https://github.com/mh-cbon/go-github-release) issues 10. Would you consider to contribute into this instead, please? I'm sad to see talented people working on their own islands instead of collaborating with the more popular ones.

**Comment by solvingJ** [comment]
@suntong Welcome to OSS :)  I know what you mean about the sprawl of talent being an inefficient use of dev time on the whole, however it's a very complex situation.  These two projects demonstrate it well actually. 

These projects have very different priorities and have different visions (different enough to warrant separation).  For example, I am not a Go developer, so this project doesn't apply to me at all.  Surprisingly, mh-cbon's was created in such a way that it generically applies to packaging regardless of the language.  This project also leverages FPM, which is a dependency with a fair amount of complexity associated.  mh-cbon's strategy was to write new lightweight standalone wrappers for each package format (deb/rpm/msi) providing a consistent .json configuration convention, and then provide the middleware to call the native packagers.  Also, mh-cbon's other utilities help in various areas of the whole release pipeline, again as independent, optional, lightweight tools. 

Finally a last thought: in contrast to most single-developer OSS projects which I would not condone using, mh-cbon's collection of projects are all incredibly well thought-out, mature, documented, and portable.  They're even published to the respective package managers.  If it were not so robust, I would also look for other solutions. 

Good luck.

**Comment by solvingJ** [comment]
Also, FYI, Bintray provides free hosting of OSS .deb and .rpm binaries in their native repository format. Not many people seem to know about it yet. I don't know if this project supports it, or has considered it, but it might be preferable to publishing to GitHub-releases OR trying to hack a travis account into a deb/rpm repo.  I've mentioned it to mh-cbon as well as I think it should be the default destination for these types of packages.

**Comment by caarlos0** [comment]
@solvingJ yep, we have a issue to support bintray: #15

**Comment by caarlos0** [comment]
Either way, I do not agree with the strategy of deploying artifacts to a git repo.

GitHub already has the releases section for this, and the git repo should ideally only contain code, no binaries at all, because the size of the repo will grow like hell and no one deserves to download a 2gigs repo to open a simple pull requests.

Moreover, I think that supporting bintray, gitlab releases and other provides delivers more value than this issue particularly. I agree that some people may use it this way, but I think more people want to use bintray, for example.

About people working together, this is open source, anyone can contribute, fork and do whatever, and as @solvingJ said, seems like both projects have different views/strategies.  I always thought in a goreleaser as an easy-to-use tool that could be customized to some extend, but the focus always was and will probably always be simplicity of usage and solving ~80% of the cases in a simple way. I think we are not there yet (that's why we aren't 1.0 stable yet), but we are getting closer every day.

I appreciate the contributions and opinions, don't get me wrong, please.

Thanks :)
