### ISSUE TITLE
Support gofish rigs similar to homebrew taps

### ISSUE THREAD

**Issue by stuart-warren** [goreleaser/goreleaser#2420]
**Is your feature request related to a problem? Please describe.**

Homebrew can suck sometimes and isn't really cross platform

**Describe the solution you'd like**

Goreleaser already supports homebrew taps and could fairly easily support gofish rigs

[gofish](https://gofi.sh/) is a package manager similar to homebrew but uses lua rather than ruby to describe packages

[rig](https://gofi.sh/#:~:text=fishworks/fish-food-,Rig,-A%20git%20repository) is the gofish analogue of a homebrew tap

[fish-food](https://github.com/fishworks/fish-food) is the default rig for gofish

**Describe alternatives you've considered**

using homebrew on linux doesn't always work so well

using other package manager for custom packages requires running/maintaining/paying for a package repository when all I need is to download a binary from github/gitlab releases in a nicer way than using curl/tar/sha256sum/chmod etc

**Additional context**

**Comment by caarlos0** [comment]
seems like something worth taking a look indeed.

**Comment by caarlos0** [comment]
done in #2509
