### ISSUE TITLE
add information about GitLab Enterprise or private hosted to the Gitlab page within the Continious Integration section

### ISSUE THREAD

**Issue by developer-guy** [goreleaser/goreleaser#2427]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem. 

**Describe the solution you'd like**
There is a very detailed guide about using GoReleaser with Gitlab, which you can see from [here](https://goreleaser.com/ci/gitlab/#gitlab-ci). But there is also another page for using it with private or enterprise Gitlab, which you can see from [here](https://goreleaser.com/scm/gitlab/#gitlab). My suggestion is that we can add `gitlab_urls` information to the [Gitlab GoReleaser doc]((https://goreleaser.com/ci/gitlab/#gitlab-ci)). I would also update the [example repository](https://gitlab.com/goreleaser/example) for Gitlab and GoReleaser integration.

**Describe alternatives you've considered**

**Additional context**

**Comment by developer-guy** [comment]
WDYT @caarlos0? The thing that I want to do is giving a reference from [here](https://goreleaser.com/ci/gitlab/) to [here](https://goreleaser.com/scm/gitlab/).

**Comment by caarlos0** [comment]
sorry, missed this issue... yeah, the docs are not as clear as they should... feel free to open prs for what you think would make it better 🙏

many thanks again for the contributions 🖤
