### ISSUE TITLE
add LinkedIn as a new GoReleaser Announce #2425 

### ISSUE THREAD

**Issue by Dentrax** [goreleaser/goreleaser#2428]
Is your feature request related to a problem? Please describe.
It is not related to a problem, it is a new feature.

Describe the solution you'd like
We (w/ @developer-guy) would like to add another integration (LinkedIn in this case) to the GoReleaser Announce feature.

See [Share API](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/share-api?tabs=http) for more information.

Similar to https://github.com/goreleaser/goreleaser/issues/2425

**Comment by caarlos0** [comment]
happy to review a pr :)
