### ISSUE TITLE
Naked releases to GitHub (raw binary, no tar, no zip)

### ISSUE THREAD

**Issue by client9** [goreleaser/goreleaser#243]
I've seen a few places do this 

https://github.com/mvdan/sh/releases

They just upload raw binaries, no tar, no zip.

Not urgent, low priority.  But nice to support, so that people could switch to goreleaser and keep their existing formats.

**Comment by jorinvo** [comment]
```yaml
archive:
  skip: true
```

Would that work?

**Comment by client9** [comment]
let me look here

**Comment by tj** [comment]
👍 this would be great, I usually just shove bins up as well, great tool though nice work!

**Comment by caarlos0** [comment]
@tj this is WIP on #257, will try to release it in 2 days :)

**Comment by caarlos0** [comment]
@tj it is out, not yet working homebrew and fpm though. Working on that part :)

**Comment by tj** [comment]
awesome, works! the brew stuff sounds awesome, I've never bothered with brew, definitely will now haha

**Comment by caarlos0** [comment]
I created new issues to deal with the things that are not working with binary releases right now.

Will close this since the initial thing is done :D
