### ISSUE TITLE
Improve signature in default changelog template

### ISSUE THREAD

**Issue by client9** [goreleaser/goreleaser#245]
The default signature includes:

```
Automated with @goreleaser
Built with go version go1.8.1 linux/amd64
```

Ok, but I don't know what `@goreleaser` is.  I checked twitter :-)  Maybe change to https://goreleaser.github.io ?

**Comment by client9** [comment]
ha.  I didn't notice @goreleaser was a link!  The GitHub style seems to be different on this page.

Ok this isn't as important now.

**Comment by jorinvo** [comment]
So we should get https://twitter.com/goreleaser to catch all the other that get confused by this 😉

**Comment by client9** [comment]
There are a number of tickets to deploy to  BitBucket, BinTray, etc...   If this happens then "@goreleaser" pointing to GitHub won't make sense.   Not urgent

twitter... good idea.

**Comment by caarlos0** [comment]
@client9 yeah, I'll create an account.

**Comment by caarlos0** [comment]
Done: https://twitter.com/GoReleaser

**Comment by jorinvo** [comment]
![screen shot 2017-05-29 at 22 39 15](https://cloud.githubusercontent.com/assets/738978/26561568/c063fa44-44bf-11e7-857c-64b4d2d8a7db.png)

**Comment by caarlos0** [comment]
Weird.

**Comment by jorinvo** [comment]
Maybe need to confirm mail or something?

**Comment by caarlos0** [comment]
Need to confirm by phone for some reason. And of course, it won't work...

![image](https://cloud.githubusercontent.com/assets/245435/26561690/af306970-4496-11e7-80c8-e6e417a02089.png)

**Comment by caarlos0** [comment]
![image](https://cloud.githubusercontent.com/assets/245435/26561705/d140b024-4496-11e7-8737-9fb6e71cba25.png)

**Comment by jorinvo** [comment]
Maybe it works in a different browser.

**Comment by caarlos0** [comment]
![image](https://cloud.githubusercontent.com/assets/245435/26561775/5fb98628-4497-11e7-9290-1f544fca65af.png)


i really hate twitter login et al.

**Comment by jorinvo** [comment]
Maybe we don't need a Twitter account 😉

**Comment by client9** [comment]
Oh dear.  If you need a USA phone number let me know.
