### ISSUE TITLE
[Bug]: shell install failure due to 404

### ISSUE THREAD

**Issue by Psykar** [goreleaser/goreleaser#2453]
### What happened?

curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh

Tries to download

https://github.com/goreleaser/goreleaser/releases/download/v0.177.0/goreleaser_checksums.txt

Which 404s.

Looks like v0.177.0 renamed this file to 
https://github.com/goreleaser/goreleaser/releases/download/v0.177.0/checksums.txt

Therefore the install script needs updating to this new path.

### How can we reproduce this?

curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh

### goreleaser version

```bash
v0.177.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Psykar** [comment]
Can't see this shell script anywhere in the repo or I'd fix it myself.

`CHECKSUM=${PROJECT_NAME}_checksums.txt`
becomes
`CHECKSUM=checksums.txt`

**Comment by Al-Pragliola** [comment]
temporary fix: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sed -e 's|${PROJECT_NAME}_checksums.txt|checksums.txt|' | sh

**Comment by ldez** [comment]
Related to https://github.com/goreleaser/goreleaser/commit/c100de32a3b63668c469d2c95acefafaf107584a

**Comment by caarlos0** [comment]
sorry, forgot about that script!

thanks for the issue and pr!

**Comment by henrikno** [comment]
Just wanted to note that the fix made downloading older releases (v0.176.0 and older) with the script fail because it can't find the checksums.txt. Bumping the version fixes it of course, but wanted to mention it since it broke our CI for a minute since it was pinning the version but not the script.
