### ISSUE TITLE
add thanks to PR responsible message to near the commit message while generating CHANGELOG

### ISSUE THREAD

**Issue by developer-guy** [goreleaser/goreleaser#2454]
Would it be nice to add the "thanks to @<responsible of the commit/PR>" message to near the commit message ?
For example:

instead of this one
```shell
5e906b2 chore(deps): bump github.com/caarlos0/env/v6 from 6.6.2 to 6.7.0 (#2444)
```

this one would be nice
```shell
5e906b2 chore(deps): bump github.com/caarlos0/env/v6 from 6.6.2 to 6.7.0 (#2444) Thanks to @caarlos0 
```

WDYT @Dentrax @caarlos0 ?

**Comment by caarlos0** [comment]
that would be awesome indeed...

we have to integrate https://github.com/goreleaser/chglog into goreleaser some day, so we may probably implement this there directly.

cc/ @djgilcrease wdyt?

**Comment by developer-guy** [comment]
I'm closing this issue too, we discussed the reason in the related PRs comments.
