### ISSUE TITLE
Contributor Over Time for goreleaser

### ISSUE THREAD

**Issue by juzhiyuan** [goreleaser/goreleaser#2459]
**Is your feature request related to a problem? Please describe.**
No, it's more like a Community adviser.

**Describe the solution you'd like**

Hi, here is the contributor over time according to https://www.apiseven.com/en/contributor-graph?chart=contributorOverTime&repo=goreleaser/goreleaser

![](https://contributor-overtime-api.apiseven.com/contributors-svg?chart=contributorOverTime&repo=goreleaser/goreleaser)

Not sure if we could put this on our website or README.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by caarlos0** [comment]
it looks nice, thanks for sharing.

will keep an eye on it, but will not add to the readme rn, its already a bit too cluttered.
