### ISSUE TITLE
[Bug]: Uploading release artefacts broken after repository has been moved from personal to org account

### ISSUE THREAD

**Issue by andig** [goreleaser/goreleaser#2469]
### What happened?

After transferring repo from github personal account (`andig`) to org (`evcc-io`), releasing is broken as it seems to address the old personal repo:

```
  • releasing...     
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • building...               commit=dbc09b49edf9febc01e5c67d7e3cd568df5a91ad latest tag=0.63
      ...
   • archives         
      • creating                  archive=release/evcc_0.63_macOS_amd64.tar.gz
      • creating                  archive=release/evcc_0.63_windows_amd64.zip
      • creating                  archive=release/evcc_0.63_macOS_arm64.tar.gz
      • creating                  archive=release/evcc_0.63_windows_armv6.zip
      • creating                  archive=release/evcc_0.63_linux_armv6.tar.gz
      • creating                  archive=release/evcc_0.63_linux_amd64.tar.gz
      • creating                  archive=release/evcc_0.63_linux_arm64.tar.gz
   • creating source archive
   • linux packages   
   • snapcraft packages
   • calculating checksums
      • checksumming              file=evcc_0.63_linux_amd64.tar.gz
      • checksumming              file=evcc_0.63_windows_armv6.zip
      • checksumming              file=evcc_0.63_macOS_arm64.tar.gz
      • checksumming              file=evcc_0.63_linux_armv6.tar.gz
      • checksumming              file=evcc_0.63_linux_arm64.tar.gz
      • checksumming              file=evcc_0.63_windows_amd64.zip
      • checksumming              file=evcc_0.63_macOS_amd64.tar.gz
   • signing artifacts
   • docker images    
   • publishing       
      • blobs            
      • http upload      
      • custom publisher 
      • artifactory      
      • docker images    
      • docker manifests 
      • snapcraft packages
      • github/gitlab/gitea releases
         • creating or updating release repo=andig/evcc tag=0.63
         • release updated           url=https://github.com/evcc-io/evcc/releases/tag/0.63
         • uploading to release      file=evcc_0.63.rootfs.gz name=evcc_0.63.rootfs.gz
         • uploading to release      file=release/evcc_0.63_linux_armv6.tar.gz name=evcc_0.63_linux_armv6.tar.gz
         • failed to upload artifact, will retry artifact=evcc_0.63_linux_armv6.tar.gz error=Post "https://uploads.github.com/repos/andig/evcc/releases/49211286/assets?name=evcc_0.63_linux_armv6.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 3; REFUSED_STREAM] after Request.Body was written; define Request.GetBody to avoid this error try=1
```

What seems wrong is this line as it points to the personal repo instead of the `evcc-io` repo:

         • creating or updating release repo=andig/evcc tag=0.63

### How can we reproduce this?

Release log: https://github.com/evcc-io/evcc/runs/3546901801?check_suite_focus=true

See https://github.com/evcc-io/evcc/blob/master/.github/workflows/build.yml for `build.yml`

### goreleaser version

```bash
Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.177.0/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/c9d798f4-3cfd-4164-bf58-edd1e575b6eb -f /home/runner/work/_temp/60d55b83-8d0d-4517-8a14-32f74368ca90
GoReleaser latest installed successfully
0.63 tag found for commit 'dbc09b4'
/opt/hostedtoolcache/goreleaser-action/0.177.0/x64/goreleaser release --rm-dist
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andig** [comment]
I have a github ticket open too (https://support.github.com/ticket/personal/0/1302086), but I'm suspecting the cause with goreleaser.

**Comment by andig** [comment]
I can reproduce this behaviour locally:

    • docker images
    • publishing
        • blobs
        • http upload
        • custom publisher
        • artifactory
        • docker images
        • docker manifests
        • snapcraft packages
        • github/gitlab/gitea releases
            • creating or updating release repo=andig/evcc tag=0.63
            • release updated           url=
    ⨯ release failed after 10.67s error=github/gitlab/gitea releases: failed to publish artifacts: POST https://api.github.com/repos/andig/evcc/releases: 401 Bad credentials []

    ❯ git remote -v
    origin	https://github.com/evcc-io/evcc (fetch)
    origin	https://github.com/evcc-io/evcc (push)

Why does goreleaser try to upload to https://api.github.com/repos/andig/evcc/releases?

**Comment by caarlos0** [comment]
> Why does goreleaser try to upload to https://api.github.com/repos/andig/evcc/releases?

From `git remote -v`

I see you closed the issue, did you find the cause/solution?

**Comment by andig** [comment]
Yes. The `goreleaser.yaml` still had the old org name which I didn't realize as I search/replaced for andig/evcc and didn't notice the separate org setting.

Sorry for the noise.
