### ISSUE TITLE
Allow to specify the git remote name

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#2484]
### Discussed in https://github.com/goreleaser/goreleaser/discussions/2401

<div type='discussions-op-text'>

<sup>Originally posted by **misitebao** August 14, 2021</sup>
I want to know how to specify the name of the remote github warehouse in the configuration file. The default is origin, but if my warehouse is set to another name, the packaging will fail!</div>

---

right now it defaults to origin on `internal/git/config.go`, maybe we should allow to customize that?

**Comment by developer-guy** [comment]
We would love to do that with @dentrax @erkanzileli if you let us do this @caarlos0 🙋🏻‍♂️🤝

**Comment by caarlos0** [comment]
sure, go ahead :)

**Comment by caarlos0** [comment]
should be fixed by https://github.com/goreleaser/goreleaser/pull/2486
