### ISSUE TITLE
v0.20.1 breaks goreleaser

### ISSUE THREAD

**Issue by nicpottier** [goreleaser/goreleaser#249]
Kinda meta, but v0.20.1 seems to break the standard way of grabbing go-releaser and running it since there's no tar.gz binaries built for various platforms.

Travis yelps:
```
$ test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
tar: This does not look like a tar archive
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Pretty sure this is due to the bad v0.20.1 build containing no binaries.

Might be nice to be able to pin to a single release in our build scripts so breaks in goreleaser don't blow up everybody's deployment pipelines?

**Comment by caarlos0** [comment]
weid, will check

**Comment by caarlos0** [comment]
hmm, weird, dep seems to have screw up something:

```
2.46s$ test -n "$TRAVIS_TAG" && go run main.go
Running goreleaser dev
Setting defaults
Getting and validating git state
git is currently in a dirty state:
 M Gopkg.lock
exit status 1
```

**Comment by nicpottier** [comment]
See we can set $VERSION to get around this for anybody running into it, just set your travis VERSION env variable to: `v0.20.0`. (may be nice to have a prefix like `GORELEASER_VERSION` here)

**Comment by caarlos0** [comment]
@nicpottier yeah, you can set it like this:

```
curl -sL http://git.io/goreleaser | VERSION=v0.20.0 bash
```

this will only be valid for that line in this case. Don't need to prefix it with `GORELEASER_` IMHO...

anyways, I removed the broken tag while I fix the issue.

**Comment by caarlos0** [comment]
Done!

v0.20.1 should be good now!
