### ISSUE TITLE
Allow dirty commits without disabling other validation

### ISSUE THREAD

**Issue by vandmo** [goreleaser/goreleaser#2500]
**Is your feature request related to a problem? Please describe.**
I am generating a buildinfo.go file which makes GoReleaser complain that my repository is dirty.
I know that is possible to pass the information using ldflags, but I find it easier and cleaner to generate a file instead.
I can also see other scenarios where code will be generated as well.

**Describe the solution you'd like**
Being able to allow dirty commits without disabling other validation. Being able to specify which files or folders that are allowed to be dirty would be nice.

**Describe alternatives you've considered**
Current solution: Making a "fake" commit. but don't really like it since the release is based on an existing actual commit.
Considered solution: Disabling validation completely.

**Comment by caarlos0** [comment]
skip validate only skips the git dirty check and allows ([for now](https://goreleaser.com/deprecations/#skipping-semver-validations)) a non-semver version, so its basically the requested behavior already...

**Comment by vandmo** [comment]
I am actually mostly interested in not missing out on any new validation added in the future.

**Comment by caarlos0** [comment]
will keep it in mind if we add more stuff into `--skip-validate`. If/when that happens, will add an specific flag for each validation to skip.

As of #2503 `--skip-validate` now skips only the git checks if they fail.

Closing for now.

Thanks!
