### ISSUE TITLE
sub directory inside the archive

### ISSUE THREAD

**Issue by ripienaar** [goreleaser/goreleaser#251]
It's most common in open source that `project-1.2.3.tar.gz` would extract into `project-1.2.3/` rather than just into `.`.

Extracting into `.` is surprising and dangerous you might well extract over peoples files by accident.

Can you please add a option to do the same? If off-by-default then a flag in the yaml file to activate this behaviour would be great.

This is quite a long standing standard and it's quite surprising now to see anything still not doing it.  See for example point 6.1 in http://ftp.icm.edu.pl/packages/linux-tsx-11/docs/HOWTO/Software-Release-Practice-HOWTO and indeed the downloadable tarballs github makes

thanks!

**Comment by client9** [comment]
we would need to specify a directory format that could be customized.. probably another template format like name.
