### ISSUE TITLE
[Bug]: loading go mod information fails when invoked outside `go.mod` directory

### ISSUE THREAD

**Issue by miquella** [goreleaser/goreleaser#2526]
### What happened?

We have a repository layout something akin to:
- `.goreleaser.yml`
- `module1/go.mod`
- `module1/cmd/cmd1/…`
- `module2/go.mod`
- `module2/cmd/cmd2/…`

The Goreleaser config then looks something like:
```yaml
builds:
- dir: module1
  main: ./cmd/cmd1

- dir: module2
  main: ./cmd/cmd2
```

However, when running `goreleaser release`, an error is reported at the `gomod` step:
```plaintext
…
   • loading go mod information
      • pipe skipped              error=not a go module
…
```

At a cursory glance through the code, it appears that the `go list -m` call is being made without the correct directory being specified, so the `go.mod` file isn't being found. Quickly shuffling things around so that `goreleaser` is run from a directory beneath the `go.mod` seems to confirm this.

_Note: it seems that this could quite possibly mean that incorrect Go module information is being recorded, depending on whether another `go.mod` is present in the hierarchy between the invocation point and the build directory._

### How can we reproduce this?

As outlined above, I believe all that is necessary is for the `goreleaser` invocation to happen above the `go.mod` path (in our case, the `go.mod` paths, since there are multiple).

Unfortunately, I don't have a public repo available that reproduces this issue.

### goreleaser version

```bash
goreleaser version 0.164.0
commit: d822baf11f7773f6c02eeaf7e187157b335935b3
built at: 2021-04-22T13:58:58Z
built by: goreleaser
module version: v0.164.0, checksum: h1:w0zTtZSg9exA+eUoaFuZiJ5UuHaMom/TgXQvySAEJiY=

# also tested with:
goreleaser version 0.180.2
commit: c90f1085f255d0af0b055160bfff5ee40f47af79
built at: 2021-09-27T13:14:04Z
built by: goreleaser
module version: v0.180.2, checksum: h1:X2iEmihUul2EVEgmS9pcEjSv3ssaRpS0NtwirHWQW14=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I considered looking into how to make the change myself, however, I was unsure how (and whether it would be appropriate) to link the build pipe and gomod pipe together so that the correct directory could be used for each.

**Comment by caarlos0** [comment]
fixed on https://github.com/goreleaser/goreleaser-pro/releases/tag/v0.180.3-pro
