### ISSUE TITLE
[Feature Request]: add google/ko as brand new builder engine for building and pushing container images

### ISSUE THREAD

**Issue by developer-guy** [goreleaser/goreleaser#2556]
**Describe the solution you'd like**

ko[^1] is a simple, fast container image builder for Go applications.

It's ideal for use cases where your image contains a single Go application without any/many dependencies on the OS base image (e.g., no cgo, no OS package dependencies).

**Additional context**
[^1]: https://github.com/google/ko

cc: @dentrax @erkanzileli @imjasonh

**Comment by imjasonh** [comment]
The `ko` codebase has made some changes recently to make it more easily consumable as a library by other Go programs, mainly to support Skaffold (see https://github.com/google/ko/pull/348). This should also help goreleaser embed its logic, if it wanted to.

Happy to help however I can!

**Comment by pmareke** [comment]
@developer-guy @imjasonh maybe a can help here. The idea is replace `Docker` using `ko` right?

**Comment by shibumi** [comment]
I would love to see this in goreleaser as well

**Comment by caarlos0** [comment]
we can discuss this  in the next (and first) goreleaser community call

https://github.com/goreleaser/community/pull/2/files

**Comment by Dentrax** [comment]
Friendly ping here. 🤞

**Comment by caarlos0** [comment]
yep, we need to discuss this.

My understanding is: we should probably use ko as a lib.

We don't need to build the binaries again, we already have them. We just need to craft the manifest.

I did start looking into ko's source code, but I'm not sure there's an "easy api" for this. Would be nice to collaborate with folks over there to get this done.

On GoReleaser side, we should probably just add another pipe, as it won't share most of the docker settings... something like:

```yaml
manifests:
   - names:
     - imgname1
     - imgname2
     - etc
     baseImage: scratch
     id: default
     arches: [] # maybe?
```

at least, that's what I had in the back of my mind.

Happy to hear your ideas.

**Comment by bwagner5** [comment]
I think that format mostly makes sense to me for mvp. 

I'd assume baseImage could also take an "auto" value or maybe just unspecified default to use distroless since that is ko's default and is kind of nice to have the CA bundles in an otherwise scratch container.

It may also be interesting to have some sort of local mode integration. For example, generally ko uses the `KO_DOCKER_REPO=gcr.io/my-project` to upload to a Container Registry. To publish an image locally, you'd set that to `ko.local`.   

Another parameter would be the cosign repo. By default ko stores the sboms in the same repo as the container image, but this is configurable via `COSIGN_REPOSITORY=gcr.io/my-project/sboms`

**Comment by caarlos0** [comment]
ah that makes sense @bwagner5 , thanks for sharing.

What we need to figure out now is how to use KO as a library instead of a binary, so we can avoid building the binaries again...

**Comment by imjasonh** [comment]
> ah that makes sense @bwagner5 , thanks for sharing.
> 
> What we need to figure out now is how to use KO as a library instead of a binary, so we can avoid building the binaries again...

I'd be happy to help here in any way. 

The main entrypoints are [`pkg/build.NewGo`](https://pkg.go.dev/github.com/google/ko/pkg/build#NewGo) which takes options to configure how to build an image from source, and [`pkg/publish.NewDefault`](https://pkg.go.dev/github.com/google/ko/pkg/publish#NewDefault) which takes options to configure how to publish that image. There are also publishers to [write that image to the local Docker daemon](https://pkg.go.dev/github.com/google/ko/pkg/publish#NewDaemon), for instance.

There's some examples of this being [used in the Terraform Provider](https://github.com/chainguard-dev/terraform-provider-ko/blob/main/internal/provider/resource_ko_image.go#L180) and in [this toy repo that demonstrates using ko as a library](https://github.com/imjasonh/miniko).

**Comment by developer-guy** [comment]
It seems that there are no reasons that we can't start working on this 🥳

**Comment by caarlos0** [comment]
nice, thanks for sharing @imjasonh !

Is there a good/supported/preferred way to provide the go binary "already built"?

**Comment by imjasonh** [comment]
> nice, thanks for sharing @imjasonh !
> 
> 
> 
> Is there a good/supported/preferred way to provide the go binary "already built"? 

There isn't. ko makes some assumptions about how the binary will be built, and other stuff that will be done at the same time, so there isn't a mode for pre-built binaries.

Because of the go build cache, if the binary was already built the expected way then building it again will be very fast.

**Comment by caarlos0** [comment]
hmm, that's too bad, seems a bit of a waste of time/energy to rebuild everything...

at that point, I also don't see much of the point of integrating goreleaser and ko, seems like one could just run the goreleaser and then ko and get the same results, no?

**Comment by caarlos0** [comment]
fwiw started a discussion about it in our discord https://discord.com/channels/890434333251362866/1033744622121394247

**Comment by bwagner5** [comment]
I think there's still value in having goreleaser support ko. One of the reasons I really like goreleaser is because it helps to keep your release process defined in one file without needing a script or workflow to run everything, which has the nice benefit of the locally reproducible builds.

**Comment by caarlos0** [comment]
@bwagner5 we discussed a bit on discord, and yes, I agree - aka, I changed my mind :D 

so, we're going to proceed with this. @developer-guy is working on a pr already, which I need to review 🙈
