### ISSUE TITLE
[Bug]: Cannot install by shell script on Mac  Os

### ISSUE THREAD

**Issue by michaljurecko** [goreleaser/goreleaser#2575]
### What happened?

Goreleaser cannot be installed on Mac Os 11 by
https://goreleaser.com/install/#shell-script

### How can we reproduce this?

```
curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh -s -- -d -b $(go env GOPATH)/bin
```

### goreleaser version

```bash
>= v0.182.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Problem is in the asset name in the release:

`v0.181.1`:
![image](https://user-images.githubusercontent.com/19371734/137195055-81828433-6cdb-49db-9e7d-7d377463f3b3.png)

`v0.182.1`:
![image](https://user-images.githubusercontent.com/19371734/137195139-a48d6821-ffa5-492d-b572-e89812251e15.png)

**Comment by caarlos0** [comment]
it should be working already @emiliza
