### ISSUE TITLE
[Bug]: unable to determine version of go binary (go): fork/exec /usr/local/bin/go: not a directory

### ISSUE THREAD

**Issue by missinglink** [goreleaser/goreleaser#2586]
### What happened?

```
goreleaser release --snapshot --rm-dist
...
unable to determine version of go binary (go): fork/exec /usr/local/bin/go: not a directory
```

### How can we reproduce this?

As a first time user, I accidentally confused `builds.dir` with `builds.main` in my `yaml` file.

Incorrectly setting `builds.dir` to a file path (rather than a directory path) results in a confusing error message:

> unable to determine version of go binary (go): fork/exec /usr/local/bin/go: not a directory

this was difficult to track down and fix (I assumed there was something wrong with my go installation, but there wasn't).

### goreleaser version

```bash
goreleaser --version
goreleaser version dev
module version: v0.182.1, checksum: h1:cKRlHfbMxejiyMCNACsl82slFXEW+k9RggADv6/Akqg=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

The 'bug' here is more about catching incorrect configuration, I would suggest a very basic `fileInfo.IsDir()` check before setting `cmd.Dir`, setting this to a non-directory path has unintended side effects and the resulting error message doesn't accurately describe the problem.

https://github.com/goreleaser/goreleaser/blob/6f219c2c3878f8108675b40214e0c7e27116e1a6/internal/builders/buildtarget/targets.go#L146-L158

**Comment by caarlos0** [comment]
feel free to give it a try @pmareke

**Comment by pmareke** [comment]
Done! Thanks @missinglink for you explanation!
