### ISSUE TITLE
[Proposal] krew support

### ISSUE THREAD

**Issue by dirien** [goreleaser/goreleaser#2598]
I wanted to preflight the idea of supporting krew in goreleaser.

So i could imagine some scenarios:

1.) Create krew file for your own index -> https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes. This would be similar to our brew / gofish

2.) Create the .krew.yaml file for the krew-release-bot -> https://github.com/rajatjindal/krew-release-bot

With 2. you need to first manually create a PR in the krew-index repo. Then the krew-release-bot, when added to the github action, will pick up any further changes.

What are your thoughts?

**Comment by caarlos0** [comment]
I would say to go ahead with 1.

for reference, there is also #1819, but I now think this would be nice to have natively...

**Comment by caarlos0** [comment]
check #2639
