### ISSUE TITLE
[Bug]: Docker images and custom release notes file don't seem to mix

### ISSUE THREAD

**Issue by miniscruff** [goreleaser/goreleaser#2601]
### What happened?

Created a new release for Changie which writes its own release notes file and passes it to goreleaser. In the latest release I also added docker releases and the body of the release only has the docker image details and not the contents of the release notes file.

I edited the release so below is what the output was versus what I expected.

Output was:
```


## Docker images

- `docker pull ghcr.io/miniscruff/changie:v1`
- `docker pull ghcr.io/miniscruff/changie:v1.1`
- `docker pull ghcr.io/miniscruff/changie:v1.1.0`
```

Expected: ( release note file should be above docker images )
```
## v1.1.0 - 2021-10-24
### Added
* [#166](https://github.com/miniscruff/changie/issues/166) Option to use environment variable for config path
* [#166](https://github.com/miniscruff/changie/issues/166) Try and load .changie.yml if .changie.yaml fails

## Docker images

- `docker pull ghcr.io/miniscruff/changie:v1`
- `docker pull ghcr.io/miniscruff/changie:v1.1`
- `docker pull ghcr.io/miniscruff/changie:v1.1.0`
```

I did have some issues with my build so this could be something I messed up on but the params seem right and I didn't get any errors.

### How can we reproduce this?

My run: https://github.com/miniscruff/changie/runs/3991143359?check_suite_focus=true
Repo: https://github.com/miniscruff/changie/

My guess at steps would be:
Using a config that has changelog: skip and docker images defined, pass --release-notes to goreleaser release.
`/opt/hostedtoolcache/goreleaser-action/0.183.0/x64/goreleaser --rm-dist --release-notes=changes/v1.1.0.md --skip-validate`

### goreleaser version

```bash
using the latest goreleaser action ( dependabot auto updates for me )
v0.183.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by miniscruff** [comment]
Would like to reopen this issue as I just released another version and my release notes are completely empty this time. I have debug mode enabled but can't seem to find anything out of the ordinary. 

Here is the build: https://github.com/miniscruff/changie/runs/4977241697?check_suite_focus=true
Here is the release: https://github.com/miniscruff/changie/releases/tag/v1.3.0
My only guess would be to quote the path from
`--release-notes=.changes/v1.3.0.md` to `--release-notes=".changes/v1.3.0.md"`

**Comment by caarlos0** [comment]
hmm, should probably add more logs... it seems like it should have worked...

**Comment by miniscruff** [comment]
I will create a small demo project mimicking the same setup to see if I can reproduce it with a smaller repo ( and one i don't mind releasing for no reason at all ). Since I don't release my project too often any suggestions will be hard to go through with resolving.

**Comment by caarlos0** [comment]
sounds like a plan!

**Comment by miniscruff** [comment]
Ok setup a much smaller project with a more minimal setup hopefully and the issue seems to happen again. Here is that project and build https://github.com/miniscruff/gekko/runs/4994509579?check_suite_focus=true, ( it is just a dumb little echo CLI ). One more maybe hint, the release description isn't 100% empty, there is an empty line. So maybe something failed to read or write but got one line in there? Not sure.

**Comment by caarlos0** [comment]
pretty sure this behavior was never changed... at least not intentionally... that skip actually skips the whole changelog thing, not only the generation

if you set a changelog via flags, it skips the generation already... will make this clear on the docs though

**Comment by miniscruff** [comment]
Ok, the new docs are much more clear, thanks as always.
