### ISSUE TITLE
[Bug]: documentation and command differ

### ISSUE THREAD

**Issue by pgundlach** [goreleaser/goreleaser#2610]
### What happened?

Page https://goreleaser.com/cmd/goreleaser_jsonschema/ mentions this:

outputs goreleaser's JSON schema

    goreleaser jsonschema [flags]

but running  `goreleaser jsonschema` I get:
     ⨯ command failed            error=unknown command "jsonschema" for "goreleaser release"

### How can we reproduce this?

Run `goreleaser jsonschema`

### goreleaser version

```bash
goreleaser --version
goreleaser version 0.183.0
commit: be6199f08167cc85b0b16cefc02d8106237853b1
built by: homebrew

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
oh, the version with this was not released yet... should be this weekend

**Comment by caarlos0** [comment]
that's a long issue of ours: not having versioned docs... but so far it hasn't been too big of a problem...

**Comment by caarlos0** [comment]
closing as it will be fixed on next release. thanks for the issue!
