### ISSUE TITLE
[Bug]: Difficult to search in documentation

### ISSUE THREAD

**Issue by pgundlach** [goreleaser/goreleaser#2616]
### What happened?

I go to the main page at 

https://goreleaser.com/

and type in the word `archives` in to the search box. I get a message ”No matching documents“.

I'd expect to see the page https://goreleaser.com/customization/archive/ and perhaps others in the search since this word is contained in that page.

### How can we reproduce this?

See above

### goreleaser version

```bash
Current webpage
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Not sure if this is fixable. Just to let you know.

**Comment by caarlos0** [comment]
Thanks, for some reason mkdocs was not indexing properly pages that use frontmatter. Changed it all to regular markdown and it seems to work better now.

Thanks for letting me know :)

**Comment by pgundlach** [comment]
Thank you very much for fixing that and thank you for the awesome tool!
