### ISSUE TITLE
Add support for replacements in builds section

### ISSUE THREAD

**Issue by tricky42** [goreleaser/goreleaser#2617]
**Is your feature request related to a problem? Please describe.**
I wanted to add sbom generation to the Ory Kratos projects which uses goreleaser. The goal is to create a SBOM file with the same name as the release archive. In the Kratos `.goreleaser.yml` file several `replacements` get defined: https://github.com/ory/kratos/blob/bf80e9614b048a3d846615b2eb2ca61ac7703800/.goreleaser.yml#L168

SBOM generation gets integrated via a hook in the `builds` section. 
```
    hooks:
      post:
        - cmd: cyclonedx-gomod app -licenses -json -output "./dist/{{ .ProjectName }}_{{ .Version }}_{{ .Target }}.bom.json"
```
As `replacements` are not supported in the `builds` section there is no "good" way to define the filename in the hook definition correctly.

**Describe the solution you'd like**
Either add support for replacements in the `builds` sections or add support for the definition of global replacements.

**Describe alternatives you've considered**
1. use {{ if }} statements e.g. {{ if eq .Env.GOOS "darwin" }}macos{{end}}
2. add mapping to release section
```
extra_files:
- src: foo_1.2.3_darwin_amd64.bom.json
  dst: foo_1.2.3_macos_amd64.bom.json
```

**Additional context**

**Comment by caarlos0** [comment]
we already have an issue to add BOM support to goreleaser... build-level replacements is unlikely to happen, so, closing this...

#2597
