### ISSUE TITLE
Transfer of ownership for Azure Devops Extension

### ISSUE THREAD

**Issue by dirien** [goreleaser/goreleaser#2621]
Hi,

i would like to transfer the ownership of the GoReleaser Azure Devops Extension https://github.com/dirien/goreleaser-azure-devops-extension to the goreleaser organization. 

If its okay, this would mean you need to create an Azure DeveOps Marketplace Entry and we need to change some of the properties in the json files:

https://github.com/dirien/goreleaser-azure-devops-extension/blob/5fe4ec048bde815eb8dc5226d7c6c09455fe2f39/vss-extension.json#L3-L6

Currently my private test marketplace entry looks like this:

![image](https://user-images.githubusercontent.com/38325136/139755795-326e0712-45af-4bd9-a721-5324697a5e5f.png)

And i tested it with a matrix build on mac, linux and windows agent.
![image](https://user-images.githubusercontent.com/38325136/139757722-c9fe6733-3152-4d3b-8b30-89b5b45b0582.png)

Hope you like it. There are some limitations, i tried to write down in the marketplace.md. Nothing serious, it is just different on ADO.

Looking for feedback.

**Comment by caarlos0** [comment]
It sounds good to me. I can add you as a contributor in the org with write access to it so you can manage that as well, wdyt?

**Comment by dirien** [comment]
@caarlos0, sounds perect. You let know:

- when i can transfer the codebase
- how we create the marketplace entry (maybe creating a user with yor info-mail?)

**Comment by caarlos0** [comment]
@dirien invited you to the org, you should be able to transfer the repo at any time... worst case it'll ask me to "accept it", which is fine :) 

Once we done that, we can work on next steps, maybe we can discuss the details on discord/slack as well :)

**Comment by dirien** [comment]
Done -> https://github.com/goreleaser/goreleaser-azure-devops-extension
