### ISSUE TITLE
[Bug]: announce: ensure correctness of the GitURL

### ISSUE THREAD

**Issue by Dentrax** [goreleaser/goreleaser#2625]
### What happened?

If the repo is cloned via `SSH`, `.GitURL` will be the SSH URL, which will be consumed by `announce` pipe and send a notification to target. Eventually there will be an SSL URL instead of HTTP URL. [^1] [^2]

[^1]: https://github.com/goreleaser/goreleaser/issues/2622#issuecomment-958358917
[^2]: https://github.com/goreleaser/goreleaser/pull/2623#pullrequestreview-795989193

### How can we reproduce this?

1. Clone the repo using `ssh`
2. Set an announce on the template
3. `.GitURL` eventually will be SSH URL instead of HTTPS

### goreleaser version

47d0e827436f3c2ed8caac9d7f508b2a862c0e00

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Some solutions to tackle this problem:
* We can mention that the `.GitURL` may not be an HTTP URL on the `template.md`. 
* Converting SSH URL to HTTPS URL in the announce stage?
* Separating to `.GitHTTPSURL` and `.GitSSHURL`?

cc: @developer-guy @erkanzileli

**Comment by developer-guy** [comment]
@caarlos0 can you please assign it to us, we can work on it, greetings 🙋🏻‍♂️🙏

**Comment by caarlos0** [comment]
> * Converting SSH URL to HTTPS URL in the announce stage?

not sure we can safely do that... 


> * We can mention that the .GitURL may not be an HTTP URL on the template.md.
> * Separating to `.GitHTTPSURL` and `.GitSSHURL`?

probably both, and only set `GitHTTPURL` if the URL is a HTTP one (we can parse it with `url.Parse`)
