### ISSUE TITLE
Proposal: Rename master to main

### ISSUE THREAD

**Issue by dirien** [goreleaser/goreleaser#2645]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like to preflight with the goreleaser community the idea to rename the `master` branch to `main` and ask @caarlos0 if if will be a huge technical change?

**Describe alternatives you've considered**
Stay with `master`

**Additional context**
[Inclusion Starts at the Codebase](https://medium.com/idealo-tech-blog/inclusive-language-in-tech-82b19b34b7cf)

**Comment by caarlos0** [comment]
I have no idea what the side effects are... if anyone has done it on other go projects, I would love to hear they process and if/what went wrong...

**Comment by bflad** [comment]
GitHub does a lot for you automatically when renaming the default branch -- you can find more details here: https://github.com/github/renaming

At my employer, we have renamed a large amount of Go module repositories without issue.

**Comment by caarlos0** [comment]
similar issues:

- https://github.com/kubernetes/enhancements/issues/2853
- https://github.com/kubernetes-sigs/promo-tools/issues/424

Seems like we need only to rename the branch via the github ui, fix the CI jobs et al filtering for master, and, finally, existing clones need to change to the new branch...

Seems like not much of a big deal

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes

**Comment by caarlos0** [comment]
We can also do it on the other active projects!

**Comment by caarlos0** [comment]
to update locally:

```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by caarlos0** [comment]
note: had to rename on codecov as well...

**Comment by caarlos0** [comment]
done!

**Comment by dirien** [comment]
Many thanks @caarlos0 !
