### ISSUE TITLE
support passing environments to "signs"

### ISSUE THREAD

**Issue by Dentrax** [goreleaser/goreleaser#2657]
This is a follow-up issue for the https://github.com/google/ko/issues/491, dropping here so we don't forget!

---

**Is your feature request related to a problem? Please describe.**
Currently, we don't have the support for passing `env` variables to [signing pipeline](https://goreleaser.com/customization/sign/).

**Describe the solution you'd like**
Add a `KV` support for the `signs` [config structure](https://github.com/goreleaser/goreleaser/blob/9af17a49adde674d73c429daec7775d6156495a0/pkg/config/config.go#L590-L600). The [default value](https://github.com/goreleaser/goreleaser/blob/9af17a49adde674d73c429daec7775d6156495a0/internal/pipe/sign/sign.go#L31) should be set to _empty_.

```yaml
signs:
  env:
    - FOO: 1
    - BAR: "string"
    - BAZ: true
```

**Describe alternatives you've considered**

`-`

**Additional context**
I'm not sure whether we should look up the OS environment using the [expand()](https://github.com/goreleaser/goreleaser/blob/9af17a49adde674d73c429daec7775d6156495a0/internal/pipe/sign/sign.go#L194-L198) function. And not sure how logic should work here in case there is `$COSIGN_EXPERIMENTAL` in the environment. Would it be a bad practice to look at the _real_ OS environment instead of creating new `env` for _each_ pipe we want to set some envs laterly?

cc: @developer-guy @erkanzileli

**Comment by caarlos0** [comment]
> Would it be a bad practice to look at the _real_ OS environment instead of creating new `env` for _each_ pipe we want to set some envs laterly?

the idea is to avoid passing envs you don't want to 3rd party command lines...

e.g. you might want COSIGN_EXPERIMENTAL set at one point but not on another (you can have multiple sign entries), or you might just make sure that your `cmd` does not see the secrets you don't want it to see...

**Comment by dirien** [comment]
Looking forward for this!

**Comment by caarlos0** [comment]
I'll tackle this as well

**Comment by caarlos0** [comment]
check https://github.com/goreleaser/goreleaser/pull/2662
