### ISSUE TITLE
[Bug]: Darwin based install failed

### ISSUE THREAD

**Issue by butuzov** [goreleaser/goreleaser#2658]
### What happened?

have run command to install goreleaser from the makefile I used before. 

```
curl -fsSL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh |  sh -s -- -b bin
```

for in response:
```
goreleaser/goreleaser crit uname_arch_check 'x86_64' got converted to 'all' which is not a GOARCH value.  Please file bug report at https://github.com/client9/shlib
```

### How can we reproduce this?

```
curl -fsSL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh |  sh -s -- -b bin
```

### goreleaser version

```bash
Since v0.182.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Issue since #2572

**Comment by caarlos0** [comment]
hey, that's not a valid instalation method anymore

**Comment by butuzov** [comment]
don't want to duplicate issues but go install @latest also fails now

```
../../../.gvm/pkgsets/go1.17/global/pkg/mod/github.com/goreleaser/goreleaser@v0.184.0/internal/pipe/reddit/reddit.go:10:2: github.com/vartanbeno/go-reddit/v2@v2.0.0: verifying module: checksum mismatch
        downloaded: h1:vjb+mY2GwC00uKeXdM+efhzEJoScc0oQfP5CZrE2R28=
        sum.golang.org: h1:fxYMqx5lhbmJ3yYRN1nnQC/gecRB3xpUS2BbG7GLpsk=
```

**Comment by caarlos0** [comment]
painn, I just can't reproduce that :| 

whats in your `go env GOPROXY`?
