### ISSUE TITLE
[Bug]: Global after hooks do not work in goreleaser-pro

### ISSUE THREAD

**Issue by aeneasr** [goreleaser/goreleaser#2660]
### What happened?

Goreleaser global hooks do not [work as documented](https://goreleaser.com/customization/hooks/).

### How can we reproduce this?

Create a file `foo.yml`

```yml
after:
  hooks:
    - cmd: npm i
      dir: docs
```

Run goreleaser check:

```
goreleaser check --config foo.yml
   • running goreleaser v0.184.0-pro
   • loading config file       file=foo.yml
   ⨯ command failed            error=failed to load config: yaml: unmarshal errors:
  line 2: field hooks not found in type config.After
```

### goreleaser version

```bash
% goreleaser --version
goreleaser version 0.184.0-pro
commit: 59ac6fbe4ab0b870cd837a82f308b73af6691767
built at: 2021-11-01T13:07:10Z
built by: goreleaser

https://goreleaser.com/pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
oh, my bad, typo in the yaml config...

will release a fix soon.

in the meantime:

```yaml
after:
  after: # 🙈
    - your hooks
```

**Comment by caarlos0** [comment]
Thanks for reporting @aeneasr! 💙

**Comment by aeneasr** [comment]
That was quick, thank you! :)
