### ISSUE TITLE
CHANGELOG categories 🙏 

### ISSUE THREAD

**Issue by blacktop** [goreleaser/goreleaser#2669]
I think it would be cool to sort the commits in the CHANGELOG by type.

I've taking to using your style of `labeling` my commits with `feat:` or `fix:` etc etc and I think it'd be cool for goreleaser to auto create Markdown sections based on how I am labeling my commits for example:

- fix: bug in parser
- feat: one word... 🌈 rainbows!
- chore: updated deps
- chore: reorg of file parser folders

Would make:

---

### Features

 - `COMMIT` one word... 🌈 rainbows! (userid)
 
 ### Fixes
 
 - `COMMIT` bug in parser (userid)
 
 ### Minor Fixes
 
 - `COMMIT` updated deps (userid)
 - `COMMIT` reorg of file parser folders (userid)
 
 ---

Also I really like the Native Github API CHANGELOG, but just as a summary.  So you could have both and it would end with a:

### Summary

Full Changelog: v1.0.11...v1.0.12

### Contributors

AVATARs

**Comment by aalmiray** [comment]
FYI https://www.conventionalcommits.org/en/v1.0.0/

**Comment by dirien** [comment]
uhh i like this, @caarlos0 can i take this one?

**Comment by caarlos0** [comment]
sure @dirien !


the only thing I would say here is to make this work only with "our own" changelog (i.e. not github-native), as it would break goreleaser if they change their format..

**Comment by dirien** [comment]
ok!

**Comment by dirien** [comment]
hi @blacktop and @caarlos0, created a first suggestion https://github.com/goreleaser/goreleaser/pull/2670 looking for your feedback :)

**Comment by blacktop** [comment]
I was able to add a `github` style changelog summary to my current CHANGELOG with the following:

```yaml
release:
  footer: |
    ### Summary
    **Full Changelog**: https://github.com/blacktop/ipsw/compare/{{ .Env.CUR_VERSION }}...{{ .Env.NEXT_VERSION }}
```

I set the env vars in my Makefile using:

```
CUR_VERSION=$(shell svu current)
NEXT_VERSION=$(shell svu patch)
```

@caarlos0 I see you have `{{ incpatch .Version }}`, would it be possible to add `{{ decpatch .Version }}` ? 🙏

**Comment by caarlos0** [comment]
you could use `{{ .Tag }}` for the current version, we could add previous version as a field too... we know that info anyway :)

**Comment by blacktop** [comment]
> you could use `{{ .Tag }}` for the current version, we could add previous version as a field too... we know that info anyway :)
> 
> wip impl: #2683

Awesome!!! ❤️

**Comment by dirien** [comment]
Hi @blacktop, I love your recipe github sytle changelog!

Would you mind, if you or i add this to the cookbook section https://goreleaser.com/cookbooks/contributing/ so it does not get lost?

**Comment by blacktop** [comment]
> Hi @blacktop, I love your recipe github sytle changelog!
> 
> Would you mind, if you or i add this to the cookbook section https://goreleaser.com/cookbooks/contributing/ so it does not get lost?

Thank you! You can add it, although, we might want to wait for @caarlos0 's #2683 to merge as it will make is SUPER easy to do?

**Comment by caarlos0** [comment]
> Thank you! You can add it, although, we might want to wait for @caarlos0 's #2683 to merge as it will make is SUPER easy to do?

yeah, will finish it up now :)

**Comment by caarlos0** [comment]
OK, #2683 ready to be reviewed :)
