### ISSUE TITLE
Support GitHub's automatically generated release notes

### ISSUE THREAD

**Issue by rustycl0ck** [goreleaser/goreleaser#2671]
**Is your feature request related to a problem? Please describe.**
Github now allows to automatically generate release notes for releases. I would like to use this feature. - https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

**Describe the solution you'd like**
An option to automatically add the release notes generated by github, while creating a release. Basically, set `generate_release_notes` to `true` in the API call when creating a release - https://docs.github.com/en/rest/reference/repos#create-a-release

**Describe alternatives you've considered**
Current workaround is to first generate the release notes and fetch them using the API - https://docs.github.com/en/rest/reference/repos#generate-release-notes-content-for-a-release. Parse the response and save the content to a file. This file can then be passed to `goreleaser` with `--release-notes myfile.md` parameter.
This adds many additional steps in the CI. Would be great if this could be supported natively by `goreleaser`.

**Comment by caarlos0** [comment]
this is already implemented https://goreleaser.com/customization/changelog/

github-native on the changelog settings does the trick :)

**Comment by rustycl0ck** [comment]
Ah sorry, I overlooked that in the config file. Thank you!
