### ISSUE TITLE
Add Hooks to UniversalBinary builder

### ISSUE THREAD

**Issue by patdowney** [goreleaser/goreleaser#2679]
**Is your feature request related to a problem? Please describe.**
I would like to build and sign (using `gon`) a universal binary. The current documentation for signing using `gon` is to use post build hooks to execute `gon` (https://goreleaser.com/customization/sign/#with-gon). The `universal_binaries` builder doesn't support `hooks`

**Describe the solution you'd like**
I would like the ability so sign MacOS Universal Binaries using the documented mechanism for calling out to `gon`

**Describe alternatives you've considered**
I'm not familiar enough with the ecosystem / processes around this kind of thing to know what the art of the possible is whilst still fitting in with goreleaser

**Comment by patdowney** [comment]
wow quick work, nice one!

**Comment by caarlos0** [comment]
thanks @wesleimp for working on it 🙏
