### ISSUE TITLE
Allow output template changes for single-target mode

### ISSUE THREAD

**Issue by SuperQ** [goreleaser/goreleaser#2685]
**Is your feature request related to a problem? Please describe.**

For `--single-target` builds where the user wants to just get a binary output, it would be nice to be able to override the `dist` and `name_template`. This way our project can have a simple `make build` that outputs a `./project_name` binary.

**Describe the solution you'd like**

A configuration option like this:

```yaml
single_target:
  destination: './'
  name_template: "{{ .Binary }}"
```

**Describe alternatives you've considered**

We could have a post-build script that moves the `dist/binary_name` into the local dir, but I think it would be cleaner if the single-target mode moved the built binary into place.

**Additional context**

This would help with the transition away from [the Prometheus promu builder](https://github.com/prometheus/promu).

**Comment by SuperQ** [comment]
@caarlos0 Not sure how involved this would be. Or if it would be better to build the binary directly to the target location, or build and mv.

**Comment by caarlos0** [comment]
I need to take a look, but I was thinking that maybe when using `--single-target` we could build to `.` by default (or move after built automatically) and also name the binary as `go build` would... 🤔

OR, accept a `-o` flag like `go build` does...

**Comment by caarlos0** [comment]
what do you think about #2701 @SuperQ ?
