### ISSUE TITLE
Horizontal sharding of builds

### ISSUE THREAD

**Issue by roidelapluie** [goreleaser/goreleaser#2686]
**Is your feature request related to a problem? Please describe.**

`--parallelism` is limited in parallelism for one machine. In CI, it is sometimes easy to pop more machines in parallel that a big machine.

**Describe the solution you'd like**

Introducing `--parallelism-thread` to shard the builds by parallelism thread.  `--parallelism 6 --parallelism-thread 1` would run builds 3,4,5.

**Describe alternatives you've considered**

using `--id` but it would require to read and understand the goreleaser file.

**Additional context**

This would help with the transition away from [the Prometheus promu builder](https://github.com/prometheus/promu).

promu supports this:

```
      --parallelism=1            How many builds to run in parallel
      --parallelism-thread=-1    Index of the parallel build
```

it is used with CircleCI's variables: `--parallelism $CIRCLE_NODE_TOTAL --parallelism-thread $CIRCLE_NODE_INDEX`

**Comment by roidelapluie** [comment]
Note: Not sure if goreleaser can split the build - release pattern

**Comment by caarlos0** [comment]
hey @roidelapluie 

this is something I've been wanting to work on for a while, right now it can't join the outputs back together and continue the release process from there... at least not without being very hacky about it.

That said, this is definitely something to work on, but its more likely to come next year only

**Comment by caarlos0** [comment]
what is kind of possible now is to have one config just for the builds, then you can run each build somewhere, copy their dist folders somewhere else, and have another config that uses the prebuilt builder to import these builds and proceed with the release.

just writing that is already cumbersome though, making all that work is probably even more cumbersome.

I've been thinking on ways to make this work in a better way, still haven't got anywhere... so I'll keep thinking. Just wanted to update the you'all :) 

refs https://github.com/goreleaser/goreleaser/issues/2320
