### ISSUE TITLE
[Bug]: cross compilation fails

### ISSUE THREAD

**Issue by omerlewitz** [goreleaser/goreleaser#2687]
### What happened?

I'm trying to release my project in both `linux` and `windwos` machines without success.

I have tried to explicitly define the `-CC` to few options but non of them worked in both machines.

Pre installed packages:

  sudo apt-get install build-essential
  sudo apt-get install gcc-multilib g++-multilib
  sudo apt-get install gcc-mingw-w64

In the project i'm using `c` code which uses these `flags` in order to selective compilation

    //#cgo windows CFLAGS: "-IC:/Program Files/OpenSSL-Win64/include"
    //#cgo windows LDFLAGS: "-LC:/Program Files/OpenSSL-Win64/lib" -llibcrypto
    //#cgo linux LDFLAGS: -lssl -lcrypto
    //#cgo CFLAGS: -Wno-deprecated-declarations

running GoRelaser locally on `windows` machine will result this error.
 

      ⨯ release failed after 24.28s error=failed to build for windows_arm64: exit status 2: # runtime/cgo
    gcc_arm64.S: Assembler messages:
    gcc_arm64.S:28: Error: no such instruction: `stp x29,x30,[sp,'
    gcc_arm64.S:32: Error: too many memory references for `mov'
    gcc_arm64.S:34: Error: no such instruction: `stp x19,x20,[sp,'
    gcc_arm64.S:37: Error: no such instruction: `stp x21,x22,[sp,'
    gcc_arm64.S:40: Error: no such instruction: `stp x23,x24,[sp,'
    gcc_arm64.S:43: Error: no such instruction: `stp x25,x26,[sp,'
    gcc_arm64.S:46: Error: no such instruction: `stp x27,x28,[sp,'
    gcc_arm64.S:50: Error: too many memory references for `mov'
    gcc_arm64.S:51: Error: too many memory references for `mov'
    gcc_arm64.S:52: Error: too many memory references for `mov'
    gcc_arm64.S:54: Error: no such instruction: `blr x20'
    gcc_arm64.S:55: Error: no such instruction: `blr x19'
    gcc_arm64.S:57: Error: no such instruction: `ldp x27,x28,[sp,'
    gcc_arm64.S:60: Error: no such instruction: `ldp x25,x26,[sp,'
    gcc_arm64.S:63: Error: no such instruction: `ldp x23,x24,[sp,'
    gcc_arm64.S:66: Error: no such instruction: `ldp x21,x22,[sp,'
    gcc_arm64.S:69: Error: no such instruction: `ldp x19,x20,[sp,'
    gcc_arm64.S:72: Error: no such instruction: `ldp x29,x30,[sp],'
    
        ⨯ release failed after 24.28s error=failed to build for windows_arm64: exit status 2: # runtime/cgo
    gcc_arm64.S: Assembler messages:
    gcc_arm64.S:28: Error: no such instruction: `stp x29,x30,[sp,'
    gcc_arm64.S:32: Error: too many memory references for `mov'
    gcc_arm64.S:34: Error: no such instruction: `stp x19,x20,[sp,'
    gcc_arm64.S:37: Error: no such instruction: `stp x21,x22,[sp,'
    gcc_arm64.S:40: Error: no such instruction: `stp x23,x24,[sp,'
    gcc_arm64.S:43: Error: no such instruction: `stp x25,x26,[sp,'
    gcc_arm64.S:46: Error: no such instruction: `stp x27,x28,[sp,'
    gcc_arm64.S:50: Error: too many memory references for `mov'
    gcc_arm64.S:51: Error: too many memory references for `mov'
    gcc_arm64.S:52: Error: too many memory references for `mov'
    gcc_arm64.S:54: Error: no such instruction: `blr x20'
    gcc_arm64.S:55: Error: no such instruction: `blr x19'
    gcc_arm64.S:57: Error: no such instruction: `ldp x27,x28,[sp,'
    gcc_arm64.S:60: Error: no such instruction: `ldp x25,x26,[sp,'
    gcc_arm64.S:63: Error: no such instruction: `ldp x23,x24,[sp,'
    gcc_arm64.S:66: Error: no such instruction: `ldp x21,x22,[sp,'
    gcc_arm64.S:69: Error: no such instruction: `ldp x19,x20,[sp,'
    gcc_arm64.S:72: Error: no such instruction: `ldp x29,x30,[sp],'

running GoReleaser locally on `ubuntu` machine will result 

    gcc: error: unrecognized command line option ‘-mthreads’; did you mean ‘-pthread’?

GoReleaser:

    # This is an example .goreleaser.yml file with some sensible defaults.
    # Make sure to check the documentation at https://goreleaser.com
    before:
      hooks:
        # You may remove this if you don't use go modules.
        - go mod tidy
        # you may remove this if you don't need go generate
        - go generate ./...
    builds:
      - env:
          - CGO_ENABLED=1
        goos:
          - linux
          - windows
    archives:
      - replacements:
          linux: Linux
          windows: Windows
          386: i386
          amd64: x86_64
    checksum:
      name_template: 'checksums.txt'
    snapshot:
      name_template: "{{ incpatch .Version }}-next"
    changelog:
      sort: asc
      filters:
        exclude:
          - '^docs:'
          - '^test:'

### How can we reproduce this?

clone the repo https://github.com/omerlewitz/terraform-provider-ravendb

### goreleaser version

```bash
goreleaser version dev
module version: v1.0.0,
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
We don't magically make CGO builds work (it seems its not even legal 😥), as stated in our docs: https://goreleaser.com/limitations/cgo/

There are links to stuff you do to make it work on that page, although its not something we actively support.

Closing...
