### ISSUE TITLE
Include or download cosign CLI when required

### ISSUE THREAD

**Issue by datosh** [goreleaser/goreleaser#2690]
**Is your feature request related to a problem? Please describe.**
I am using the goreleaser/goreleaser Docker image to build my application. Now, I want to include container & binary blob signing using cosign, but the required CLI is not available in the image. (unless I missed something?)

I could go ahead and maintain my own image, where I extend goreleaser image with cosign CLI, but I image many people would want to use cosign, e.g. in their containerized pipeline, and everyone maintaining their own extended copy doesn't seem like a great solution.

**Describe the solution you'd like**
From user perspective it would great to have all required binaries that goreleaser supports be available in the image, but I recognize that this might blow up the image size, and not all users will require all binaries.

**Describe alternatives you've considered**
goreleaser could download cosign CLI, if signing is enabled in config. It should be as easy as `go install github.com/sigstore/cosign/cmd/cosign@latest`, but without proper caching (volumes) this will take quite a while.

In order not to pollute the main docker image, additional tags could be used that extend the main image, e.g.
- goreleaser/goreleaser:v1.2.3-cosign
- goreleaser/goreleaser:v1.2.3-all-deps

**Additional context**
What do you think? I'd be open to support the implementation of any of the paths!

**Comment by caarlos0** [comment]
It will be on the next version thanks to @cpanato :) 

https://github.com/goreleaser/goreleaser/blob/main/Dockerfile#L14

closing as already fixed.
