### ISSUE TITLE
Is there a way to run goreleaser without git repo?

### ISSUE THREAD

**Issue by damnever** [goreleaser/goreleaser#270]
Error message:
```
failed reading repo from git: exit status 1:
```

I cannot find out solution from README.

**Comment by caarlos0** [comment]
@damnever `--skip-validate` should do it...

**Comment by damnever** [comment]
```
➜  goreleaser --skip-validate --debug
   • running goreleaser 0.21.3
   • SETTING DEFAULTS
failed reading repo from git: exit status 1:
```

**Comment by caarlos0** [comment]
hmm, so you'll need to fill up all the defaults that are provided via git.

try `goreleaser init` and fill things up according to the readme...

but anyway, goreleaser was not made to be used without a git repo... so I don't know if it will work as expected..

**Comment by damnever** [comment]
I make it worked, but `goreleaser init` also failed reading repo from git, is there any plan to make it work without git repo?

**Comment by caarlos0** [comment]
Not right now, but, I'm curious, what is the use case? Are you using another SCM?

**Comment by damnever** [comment]
If I have a project in development and I do not have a git repo currently, `goreleaser` won't work.

**Comment by caarlos0** [comment]
Hmm, got it.

I usually create a repo right away... 

Anyway, the `init` command should probably ignore this kind of errors and just leave the field empty I guess...

**Comment by caarlos0** [comment]
not stale

**Comment by caarlos0** [comment]
release --snapshot still needs git, will improve this as well
