### ISSUE TITLE
[proposal] do not automatically list docker images on release notes

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#2707]
In the beginning, GoReleaser didn't had customization options regarding the release notes - like footer and header. 

That's one of the reasons why we always listed the docker images in the release notes.

Now, we have those options and it would be easy to add them as a footer.

The reason I propose this is that, if you want to add something to the footer that is related to the changelog, it will actually be after the docker images list, which is a bit weird.

Also, some people might not want to list docker images at all, or list them without the `docker pull` part, or something else.

I think not automatically adding them would be a good move long-term.

But that's just what I think, and I would love to hear your thoughts as well :) cc/ @goreleaser/goreleaser

**Comment by kbudde** [comment]
@caarlos0 it would be nice to have some documentation on how to add the docker images to the footer back again. For everybody relying on them.

**Comment by caarlos0** [comment]
You can basically set the footer to something like:

```
## Docker Images

- `myuser/myimg:{{ .Version }}`
- `otherregistry.foo/user/img:{{ .Version }}`
```
