### ISSUE TITLE
HTTP Announcer

### ISSUE THREAD

**Issue by ghostsquad** [goreleaser/goreleaser#2711]
**Is your feature request related to a problem? Please describe.**
If I had a custom service that accepted an HTTP request, I'd like to be able to send an "announcement" by sending an arbitrary HTTP request to a service I own.

**Describe the solution you'd like**
Support to send an http request as part of the "announcement" step.

**Describe alternatives you've considered**
A custom publisher perhaps? But announcing is a step _after_ publishing.

**Additional context**
n/a

**Comment by dirien** [comment]
@caarlos0, I like the idea of a generic Webhook with a the message in the Post Body.

It should support Auth (via Header) too.

I would like to implement this.

**Comment by Dentrax** [comment]
+1, I liked the idea! A bit advanced for goreleaser but dropping [falcosidekick's generic HTTP client](https://github.com/falcosecurity/falcosidekick/blob/master/outputs/client.go) here anyway, maybe it can help us.

**Comment by caarlos0** [comment]
go for it @dirien !

cool link @Dentrax !
