### ISSUE TITLE
Custom Announcers

### ISSUE THREAD

**Issue by ghostsquad** [goreleaser/goreleaser#2712]
**Is your feature request related to a problem? Please describe.**
XYZ is not currently supported by goreleaser as an announcement method

**Describe the solution you'd like**
Support custom announcers similar to custom publishers

**Describe alternatives you've considered**
A custom publisher perhaps? But announcing is a step _after_ publishing.

**Additional context**
n/a

**Comment by caarlos0** [comment]
fixed sometime ago, we now have the webhook announcer, which should be enough

https://goreleaser.com/customization/announce/webhook/
