### ISSUE TITLE
use keyless approach while signing and verifying GoReleaser checksums.txt file

### ISSUE THREAD

**Issue by developer-guy** [goreleaser/goreleaser#2713]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem. 

**Describe the solution you'd like**
A similar approach has been taken in cosign project[^1], thanks to @cpanato. Now, we can use this approach while signing and verifying the checksums.txt file of the GoReleaser.

Also thanks to @cpanato, he already prepared a repository[^2] to show people how they can keyless approach with GoReleaser.

**Describe alternatives you've considered**

* We should remove both `cosign.key` and `cosign.pub` files.
* We should enable cosign's experimental mode by providing the `COSIGN_EXPERIMENTAL` environment variable.
* We should output the certificate while signing the blob, and upload this certificate to the releases.
* We can use this certificate while verifying the `checksums.txt.sig` file.

**Additional context**

[^1]: https://github.com/sigstore/cosign/pull/1111
[^2]: https://github.com/caarlos0-graveyard/gorel-keyless

cc: @caarlos0 @dirien @Dentrax

**Comment by developer-guy** [comment]
similar projects that try to achieve the same thing:

* https://github.com/google/ko/issues/491

**Comment by caarlos0** [comment]
pushed what I had laying around on my stash here... cc/ @developer-guy
