### ISSUE TITLE
[Bug]: ARMv6 should be armhf and ARMv5 should be armel

### ISSUE THREAD

**Issue by vincentbernat** [goreleaser/goreleaser#2721]
### What happened?

Since GoReleaser v1.0.0, armhf is mapped to armv7 while armel is mapped to armv6. However, Raspbian, a derivative of Debian still used today, considers armhf to be armv6. Therefore, the Debian packages generated by GoReleaser does not work and users get "Illegal instruction" errors.

### How can we reproduce this?

We are using this configuration file: https://github.com/nextdns/nextdns/blob/master/.goreleaser.yml

I am a bit lost at what exactly GoReleaser does because GoReleaser seems to get `armhf.deb` and `armel.deb`, while we get `armv6.deb` and `armv7.deb`. I don't know if there is an easy way to check the real EABI of the DEB files from GoReleaser as `file` says `ARM, EABI5 version 1` whatever it is for ARMv6 or ARMv7.

See https://github.com/nextdns/nextdns/pull/626 and https://github.com/nextdns/nextdns/pull/624#issuecomment-984784505.

### goreleaser version

```bash
1.1.0 fails: https://github.com/nextdns/nextdns/runs/4396570024?check_suite_focus=true
1.0.0 fails too: https://github.com/nextdns/nextdns/runs/4258994552?check_suite_focus=true
0.182.0 is OK: https://github.com/nextdns/nextdns/runs/4400025574?check_suite_focus=true
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
GoReleaser get those names because of https://github.com/goreleaser/goreleaser/blob/main/.goreleaser.yaml#L170 

Shouldn't arm7 be armhf?

Those arches come from here: https://github.com/goreleaser/nfpm/blob/main/deb/deb.go#L36-L45

**Comment by caarlos0** [comment]
> Shouldn't arm7 be armhf?

yeah, its wrong, arm7 is armhf, arm6 is armel, no idea what arm5 is supposed to be

**Comment by caarlos0** [comment]
> what arm7 is supposed to be

seems like also armhf...

**Comment by vincentbernat** [comment]
For Debian, armhf is arm7 while for Raspbian, armh is arm6, so better use arm6→armhf and arm5→armel.

**Comment by caarlos0** [comment]
see https://github.com/goreleaser/nfpm/pull/412
