### ISSUE TITLE
Release description from the Git tag message

### ISSUE THREAD

**Issue by dolmen** [goreleaser/goreleaser#2726]
**Is your feature request related to a problem? Please describe.**

I don't want a changelog produced from Git commit messages because they are only for maintainers, not for end users.

When I prepare a release I do a Git tag with a commit message that contains the changelog defined by the maintainer:
```
git tag -a $version
```
I would like to use the content of that message which is attached to the Git tag as the description of the release.

**Describe the solution you'd like**
Some settings in `release` settings that allow me to tell that I want the release description to be extracted from the Git tag.

Or let me call a command that will produce the text of the release notes.

**Comment by caarlos0** [comment]
check #2730 

please check if in your repo if 

```sh
git tag -l --format='%(contents:subject)' YOUR_TAG_HERE
```

yields the expected results :)

**Comment by dolmen** [comment]
@caarlos0 Well, I need the full message:

```
git tag -l --format='%(contents)' MY_TAG_HERE
```

**Comment by caarlos0** [comment]
✅
