### ISSUE TITLE
[Bug]: GitLab documentation should advice project scoped tokens

### ISSUE THREAD

**Issue by dolmen** [goreleaser/goreleaser#2738]
### What happened?

The [documentation](https://goreleaser.com/scm/gitlab/#api-token) says to create a GitLab personal token.

> GoReleaser requires an API token with the api scope selected to deploy the artifacts to GitLab. You can create one [here](https://gitlab.com/-/profile/personal_access_tokens).

But this creates a token which has too much power.
In GitLab it is now possible to create token which have only the project scope.

GitLab CI now even exposes a `$CI_JOB_TOKEN` variable that _may_ already have all the credentials needed.
https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html

### How can we reproduce this?

https://goreleaser.com/scm/gitlab/#api-token

### goreleaser version

```bash
Irrelevant.
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
Can you open a PR documenting that? I have little experience with gitlab.

The file to edit are:
- https://github.com/goreleaser/goreleaser/blob/main/www/docs/ci/gitlab.md
- https://github.com/goreleaser/goreleaser/blob/main/www/docs/scm/gitlab.md

thanks!

**Comment by dolmen** [comment]
I am currently experimenting with `$CI_JOB_TOKEN` (because this means that we would not have to manually create a token) which is supposed to have [API access since GitLab 1.14](https://about.gitlab.com/releases/2021/10/22/gitlab-14-4-released/#improve-security-of-cijobtoken-with-bots-and-more).

Unfortunately, no success on GitLab 1.14.1 so far (error 401 when attempting to publish a release with `GITLAB_TOKEN="$CI_JOB_TOKEN" goreleaser release --rm-dist`).

**Comment by gwvandesteeg** [comment]
After some trial and error:

You can use either a Group or Project Access token as long as they are at the Maintainer role level and have the API scope permission.

**Comment by caarlos0** [comment]
nice, @gwvandesteeg , do you mind documenting this in one of these files?

- https://github.com/goreleaser/goreleaser/blob/main/www/docs/ci/gitlab.md
- https://github.com/goreleaser/goreleaser/blob/main/www/docs/scm/gitlab.md

thanks
