### ISSUE TITLE
Add GitLab 'release-cli' tool in goreleaser Docker image

### ISSUE THREAD

**Issue by dolmen** [goreleaser/goreleaser#2742]
**Is your feature request related to a problem? Please describe.**

In a GitLab CI job I would like to use `goreleaser` for build, but use GitLab CI [`release` settings](https://docs.gitlab.com/ee/ci/yaml/#release) (which needs GitLab' [`release-cli`](https://gitlab.com/gitlab-org/release-cli/-/tree/master/docs) tool) for publishing the release.

**Describe the solution you'd like**
Add [`release-cli`](https://gitlab.com/gitlab-org/release-cli/-/tree/master/docs) in the `goreleaser` Docker image.

**Describe alternatives you've considered**

**Additional context**

**Comment by caarlos0** [comment]
I'm sorry, rather not. The image is already very big, don't want to bloat it too much.

If you need custom tools, you can always `FROM goreleaser` and build from there...

thanks for the suggestion though...
