### ISSUE TITLE
Consider configuration file to be `.goreleaser.yml` instead of `goreleaser.yml`

### ISSUE THREAD

**Issue by vromero** [goreleaser/goreleaser#275]
This may or may not make sense in the go state-of-the-art, but it might help to unclutter the project root folders to have the configuration file default name as `.goreleaser.yml` instead of `goreleaser.yml` as:

- in unix it would be hidden, just like .travis.yaml, .gitignore and other not strictly code files
- in github it would be grouped (by ordering) with the rest of the not strictly code files instead of with the doc or code.

**Comment by caarlos0** [comment]
yes, i've been thinking about it too...

right now it's possible via the `--file` flag, but we should make it work by default, I agree...

**Comment by vromero** [comment]
Yes but there are some inconveniences, as I can't pass `--file`  in : `curl -sL https://git.io/goreleaser | bash --file .goreleaser.yml`

Thanks

**Comment by caarlos0** [comment]
@vromero the syntax should be: 

```bash
curl -sL https://git.io/goreleaser | bash -s -- --file .goreleaser.yml
```

**Comment by vromero** [comment]
Interestingly the homebrew part won't work complaning about homebre not configured. Renaming the file back to `goreleaser.yml` and removing `-s -- --file .goreleaser.yml` fix the problem.

**Comment by caarlos0** [comment]
@vromero which homebrew part?

**Comment by vromero** [comment]
The creation of the formula:

```
   • CREATING HOMEBREW FORMULA
   • skipped because brew section is not configured
```

**Comment by caarlos0** [comment]
@vromero you need to set the `github` property. Check https://github.com/goreleaser/goreleaser#homebrew-tap-customization

**Comment by vromero** [comment]
I did, the only thing I different between a working run and a non working one is:

- *Non working*:  `.goreleaser.yml` and `--file in : curl -sL https://git.io/goreleaser | bash --file .goreleaser.yml` 
- *Working*:  `goreleaser.yml`

It might be a environmental, but happened to me twice before I believed that it was happening.
I see you have a PR, I'll be happy to test when it is merged I'll let you know.

**Comment by caarlos0** [comment]
that's weird...

anyway, the feature tu support `.goreleaser.yml` natively is in the oven 👍

**Comment by caarlos0** [comment]
it's out, v0.24.0, enjoy!
