### ISSUE TITLE
[Bug]: failed build: exit status 2: too many errors

### ISSUE THREAD

**Issue by richmailYT** [goreleaser/goreleaser#2756]
### What happened?

I ran `goreleaser release --snapshot --rm-dist` and recived error
`too many errors` 

I exspected it to run without error and give me exacutables for all platforms

here is the full error log

```
 • releasing...     
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • ignoring errors because this is a snapshot error=git doesn't contain any tags. Either add a tag or use --snapshot
      • building...               commit=612b8b672e8ddadc077b08cfea5dbcadb350f9ea latest tag=v0.0.0
      • pipe skipped              error=disabled during snapshot mode
   • parsing tag      
   • running before hooks
      • running                   hook=go mod tidy
      • running                   hook=go generate ./...
   • setting defaults 
      • snapshotting     
      • scm releases     
      • project name     
      • loading go mod information
      • building binaries
      • universal binaries
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • signing docker images
      • docker images    
      • docker manifests 
      • artifactory      
      • blobs            
      • homebrew tap formula
      • krew plugin manifest
      • gofish fish food cookbook
      • scoop manifests  
      • discord          
      • reddit           
      • slack            
      • teams            
      • twitter          
      • smtp             
      • mattermost       
      • milestones       
      • linkedin         
      • telegram         
   • snapshotting     
      • building snapshot...      version=0.0.1-next
   • checking distribution directory
      • --rm-dist is set, cleaning it up
   • loading go mod information
   • writing effective config file
      • writing                   config=dist/config.yaml
   • building binaries
      • building                  binary=/Users/richmail/Document/VSCode/GO/src/test/dist/Golang-AutoClicker_darwin_arm64/Golang-AutoClicker
      • building                  binary=/Users/richmail/Document/VSCode/GO/src/test/dist/Golang-AutoClicker_linux_arm64/Golang-AutoClicker
      • building                  binary=/Users/richmail/Document/VSCode/GO/src/test/dist/Golang-AutoClicker_linux_amd64/Golang-AutoClicker
      • building                  binary=/Users/richmail/Document/VSCode/GO/src/test/dist/Golang-AutoClicker_windows_arm64/Golang-AutoClicker.exe
      • building                  binary=/Users/richmail/Document/VSCode/GO/src/test/dist/Golang-AutoClicker_darwin_amd64/Golang-AutoClicker
      • building                  binary=/Users/richmail/Document/VSCode/GO/src/test/dist/Golang-AutoClicker_windows_386/Golang-AutoClicker.exe
      • building                  binary=/Users/richmail/Document/VSCode/GO/src/test/dist/Golang-AutoClicker_windows_amd64/Golang-AutoClicker.exe
      • building                  binary=/Users/richmail/Document/VSCode/GO/src/test/dist/Golang-AutoClicker_linux_386/Golang-AutoClicker
   ⨯ release failed after 0.80s error=failed to build for darwin_amd64: exit status 2: # github.com/go-vgo/robotgo
../../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.9/hook.go:30:24: undefined: hook.Event
../../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.9/hook.go:31:9: undefined: hook.Start
../../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.9/hook.go:36:2: undefined: hook.End
../../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.9/hook.go:42:19: undefined: hook.Event
../../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.9/hook.go:43:9: undefined: hook.Start
../../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.9/hook.go:58:31: undefined: hook.Event
../../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.9/hook.go:63:64: undefined: hook.Event
../../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.9/img.go:92:40: undefined: Bitmap
../../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.9/img.go:107:38: undefined: Bitmap
../../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.9/img.go:137:20: undefined: Bitmap
../../../../../go/pkg/mod/github.com/go-vgo/robotgo@v0.100.9/hook.go:43:9: too many errors
```

### How can we reproduce this?

https://github.com/richmailYT/Golang-AutoClicker

You're going to have to run `go mod init github.com/richmailYT/Golang-AutoClicker` and `go get github.com/go-vgo/robotgo` to get everything working. The `.goreleaser.yml` is in the repo

### goreleaser version

```bash
goreleaser version 1.1.0
commit: af4a8642bddb171914ee932bfb5768f102c3516f
built at: 2021-11-28T23:41:04Z
built by: goreleaser
module version: v1.1.0, checksum: h1:YySqqYTX9kxRU0e/fGQrhivXk8/zD4iUOlL7h0I2gBk=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Golang 1.17.5, MacOS Catalina 10.15.7

one more thing: I read GoReleaser as Gore-leaser. I find that funny. Do you?

**Comment by caarlos0** [comment]
not a bug, its something in your program that is failing to compile.

**Comment by richmailYT** [comment]
Whats failing to compile? `go build` works fine

**Comment by caarlos0** [comment]
my guess is that go-vgo/robotgo uses CGO, so `go build` in your local machine will work. You config probably specifies `CGO_ENABLED=0`, and if you run `CGO_ENABLED=0 go build` it likely fails.

you can see the exact go build command being used running `goreleaser release` with the `--debug` flag.



> one more thing: I read GoReleaser as Gore-leaser. I find that funny. Do you?

- https://carlosbecker.com/posts/goreleaser-lessons-learned/ naming things subtopic
- https://github.com/goreleaser/artwork/blob/master/old/gore_leaser.png 

:)

**Comment by richmailYT** [comment]
setting `CGO_ENABLED` to `1` gives me a different error when compiling
``
   ⨯ release failed after 14.98s error=failed to build for linux_386: exit status 2: # runtime/cgo
linux_syscall.c:67:13: error: implicit declaration of function 'setresgid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:67:13: note: did you mean 'setregid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/unistd.h:593:6: note: 'setregid' declared here
linux_syscall.c:73:13: error: implicit declaration of function 'setresuid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:73:13: note: did you mean 'setreuid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/unistd.h:595:6: note: 'setreuid' declared here
```

runing it again gives me
```
⨯ release failed after 1.99s error=failed to build for darwin_arm64: exit status 2: # runtime/cgo
In file included from _cgo_export.c:3:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:62:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
In file included from _cgo_export.c:3:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:64:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:33:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
In file included from _cgo_export.c:3:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:64:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
note: '__int128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
note: '__int128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
note: '__uint128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
note: '__uint128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
note: '__uint128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
note: '__int128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
note: '__uint128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
note: '__int128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
note: '__uint128_t' declared here
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
note: '__uint128_t' declared here
In file included from _cgo_export.c:3:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:64:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
note: '__uint128_t' declared here
In file included from _cgo_export.c:3:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/wait.h:109:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/signal.h:82:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/signal.h:34:2: error: architecture not supported
In file included from _cgo_export.c:3:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/wait.h:109:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/signal.h:146:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/_mcontext.h:31:2: error: architecture not supported
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by caarlos0** [comment]
Not a goreleaser issue.
