### ISSUE TITLE
[Feature Request]: add base image annotations to container images while building them

### ISSUE THREAD

**Issue by developer-guy** [goreleaser/goreleaser#2765]
**Is your feature request related to a problem? Please describe.**
It's a feature, not related to a problem.

**Describe the solution you'd like**
We've been living for a long time without knowing what my containers are built on, and the problems that they can cause. In more softly, let's say without caring about them as much. An awesome folk whose name is @imjasonh came with a brilliant idea (as always) and woke us up from the dream by attracting our attention to how these base images are actually important. The idea was that: [OCI Base Image Annotations](https://github.com/imjasonh/ImJasonH/tree/main/articles/oci-base-image-annotations#oci-base-image-annotations), which is even better because the idea was accepted by the OCI community that makes this is officially supported. 🥳

So, what we (w/@dentrax) are proposing is that, as the documentation says, there are a bunch of tools that we already have support in GoReleaser are capable of doing this, please [see](https://github.com/imjasonh/ImJasonH/tree/main/articles/oci-base-image-annotations#when-can-i-use-it). So, we can use one of them to accomplish this for free while building container images in GoReleaser.

**Comment by puerco** [comment]
This is pretty @developer-guy @Dentrax I'm doing some tests around this idea too, happy to chat one day :)

**Comment by caarlos0** [comment]
we should totally discuss this in our community meeting :D

**Comment by caarlos0** [comment]
ok, I gave this some though I don't think we'll implement this.

user can do it after the release using crane or docker manifest, perhaps using a [custom publisher](https://goreleaser.com/customization/publishers/). Unless that's too cumbersome/impossible, I'd rather not add it to goreleaser itself.

that said, will close for now, feel free to reopen/ping if you disagree
