### ISSUE TITLE
Extra Files Support with Custom Publishers

### ISSUE THREAD

**Issue by bflad** [goreleaser/goreleaser#2768]
**Is your feature request related to a problem? Please describe.**

Our `.goreleaser.yml` makes use of the `extra_files` configuration of the `release` pipe as well as a custom publisher:

```yaml
publishers:
  - name: example
    checksum: true
    signature: true
    cmd: example upload-file {{ abs .ArtifactPath }}
release:
  extra_files:
    - glob: '{{ .ProjectName }}_manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
```

The extra files are added to the release, but not published using the custom publisher. This appears to be because the release pipe, which adds those artifacts to the internal Context, runs after the custom publishers pipe.

https://github.com/goreleaser/goreleaser/blob/505888f41be5308eb7d5c6fb25df82a1bda4cc1a/internal/exec/exec.go#L105

https://github.com/goreleaser/goreleaser/blob/505888f41be5308eb7d5c6fb25df82a1bda4cc1a/internal/pipe/release/release.go#L134-L148

https://github.com/goreleaser/goreleaser/blob/505888f41be5308eb7d5c6fb25df82a1bda4cc1a/internal/pipe/publish/publish.go#L35-L52

**Describe the solution you'd like**

I'm guessing that we wouldn't want to adjust the pipe ordering that is currently happening, so with that in mind, three mutually exclusive proposals:

1. Changing the logic in checksums to add the extra files to the Context artifacts, similar to how the release pipe currently works. I'm guessing the release pipe would then need to be careful to not add/overwrite duplicates. I'm not sure the other implications of doing this as other pipes may not be expecting these additional UploadableFile artifacts. It also might not be clear that adding that extra files configuration in checksums applies to the rest of the release pipeline.
1. Adding `extra_files` configuration to custom publishers (similar to checksums and release) and handling to the custom publishers pipe execution logic. I'm guessing it would need to mimic the current checksums pipe behavior so these extra files aren't included unexpectedly in other custom publishers and the release pipe.
1. Creating a separate top-level configuration section for "extra files" that tag along through all the pipes (potentially filterable as a new id in other pipes). A new "extra files" pipe that reads this configuration and saves it into the Context should execute before checksums since that is the first extra files usage.

**Describe alternatives you've considered**

Separately calling the custom publisher on the extra files after calling `goreleaser`.

**Additional context**

Please let me know if you would accept any type of contribution here and happy to submit one. Thank you for this excellent project!

**Comment by bflad** [comment]
Took a swing at proposal 2 since it seemed like the lowest hanging and least risky: https://github.com/goreleaser/goreleaser/pull/2770

I will also try to submit proposal 3, although that is much more invasive.

**Comment by bflad** [comment]
Here's a swing at proposal 3: #2771

**Comment by caarlos0** [comment]
hey, just fwiw, will review the PRs et al only in January. v1.2 was the last feature release of the year, only bugfixes for a couple of weeks now :)

**Comment by bradrhod** [comment]
> #2771

The external 2.2.0 version issue with terraform 0.12 still has terraform init broken.  
"Provider "external" v2.2.0 is not compatible with Terraform 0.12.31."
terraform 0.12 will require everyone to pin their versions of external provider and that can be a lot of work.   Hoping this fix, or a different fix can be considered to fix cli version 0.12

**Comment by caarlos0** [comment]
this will be looked on for next release

**Comment by bflad** [comment]
Hi @bradrhod 👋  I'm still waiting on another internal team to make the required fix in the Terraform Registry. This issue will be closed when that is done. If there is no progress made by tomorrow morning, I will cut a new patch release that should not have this issue for Terraform CLI 0.12.
