### ISSUE TITLE
[Bug]: Odd build behavior when build flags are involved

### ISSUE THREAD

**Issue by jonwhitty** [goreleaser/goreleaser#2769]
### What happened?

I have a [sample gist project](https://gist.github.com/jonwhitty/9702684faef14d99029c4698ad8a1e7a) that uses the go [mongodb driver](https://github.com/mongodb/mongo-go-driver) and it uses the [client-side encryption (cse)](https://www.mongodb.com/developer/how-to/field-level-encryption-fle-mongodb-golang/) integration from the driver. The cse support is compiled in if you provide the `-tags cse` build tag.

Under a normal build of the sample project I can simply do `go build -tags cse` and it builds just fine and executes as I would expect. If I build with goreleaser it fails with the error:

```
   ⨯ build failed after 2.32s error=failed to build for darwin_amd64: exit status 2: # go.mongodb.org/mongo-driver/x/mongo/driver
../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.8.1/x/mongo/driver/crypt.go:72:14: undefined: mongocrypt.MongoCrypt
../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.8.1/x/mongo/driver/crypt.go:92:13: undefined: mongocrypt.NewMongoCrypt
../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.8.1/x/mongo/driver/crypt.go:150:11: cannot assign error to err in multiple assignment
../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.8.1/x/mongo/driver/crypt.go:171:11: cannot assign error to err in multiple assignment
../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.8.1/x/mongo/driver/crypt.go:188:68: undefined: mongocrypt.Context
../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.8.1/x/mongo/driver/crypt.go:212:63: undefined: mongocrypt.Context
../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.8.1/x/mongo/driver/crypt.go:231:60: undefined: mongocrypt.Context
../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.8.1/x/mongo/driver/crypt.go:248:61: undefined: mongocrypt.Context
../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.8.1/x/mongo/driver/crypt.go:268:60: undefined: mongocrypt.Context
../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.8.1/x/mongo/driver/crypt.go:283:57: undefined: mongocrypt.KmsContext
../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.8.1/x/mongo/driver/crypt.go:171:11: too many errors
```

### How can we reproduce this?

`go build -tags cse` it builds just fine.

`goreleaser build --rm-dist --snapshot` it fails to build despite the fact that I've provided the `-tags=cse` in the goreleaser specification.

### goreleaser version

```bash
> goreleaser --version
goreleaser version 1.1.0
commit: af4a8642bddb171914ee932bfb5768f102c3516f
built at: 2021-11-28T23:41:04Z
built by: goreleaser
module version: v1.1.0, checksum: h1:YySqqYTX9kxRU0e/fGQrhivXk8/zD4iUOlL7h0I2gBk=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
that seems to be because the mongodb driver uses CGO...

https://goreleaser.com/limitations/cgo/

not a bug.
