### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Khushbukela** [goreleaser/goreleaser#2774]
### What happened?

failed to upload artifact, will retry artifact=sample-go-consumer_Windows_arm64.zip error=POST https://uploads.github.com/repos/khushbukela/sample-go-consumer/releases/55531790/assets?name=sample-go-consumer_Windows_arm64.zip: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] try=1

### How can we reproduce this?

it was working fine earlier. i uninstall and reinstall the goreleaser after this, issue starts

### goreleaser version

```bash
1.1.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
you are running goreleaser release multiple times against the same tag.

Please search before opening issues...

https://github.com/goreleaser/goreleaser/issues?q=already_exists
