### ISSUE TITLE
GitHubPrivateRepositoryDownloadStrategy

### ISSUE THREAD

**Issue by Khushbukela** [goreleaser/goreleaser#2775]
Currently, we can access any repo through git token. and URL supports is https
but do we have support through ssh way access repo? 

In a general way my team also wants to use the same package which I have created. but for that they all have to create github_token so 
having ssh way access will be fine.

**Comment by caarlos0** [comment]
if I understand correctly, you want to install homebrew taps using a SSH key? I don't know if that's possible, pretty sure it isn't. Also, its not related to goreleaser as goreleaser do not generate any download strategies, just the tap itself.

---

in the future, please follow the templates when filling issues.

for questions use https://github.com/goreleaser/goreleaser/discussions

**Comment by Khushbukela** [comment]
Sure @caarlos0 will use the discussion feature. 
wanted to know can we specify URL like this in the brew formula 
`git@github.com:Khushbukela/homebrew-sample.git
`
