### ISSUE TITLE
[Feature Request] open PR instead of git push when my formula is hosted on homebrew-core

### ISSUE THREAD

**Issue by developer-guy** [goreleaser/goreleaser#2777]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
so, let's assume that my project's formula is hosted on homebrew-core, and I want to still continue making new releases of my formula with GoReleaser, how people can do that? Something an option like "open_pr" in the brew section would be useful in such cases. When people specify this option, GoReleaser will open a PR instead of doing a git push.

**Describe alternatives you've considered**

**Additional context**

**Comment by dirien** [comment]
hi @developer-guy, what is the idea behind this extra step?

**Comment by caarlos0** [comment]
Thats a good question... because the recipes in the way goreleaser builds them are not accepted in homebrew core et al, so that's not a valid use case...

**Comment by caarlos0** [comment]
given my previous comment, closing this!
