### ISSUE TITLE
Tar and symlinks

### ISSUE THREAD

**Issue by vromero** [goreleaser/goreleaser#278]
Oftentimes it's necessary to distribute symbolic links withthin a unix distribution.

I'm my case I have an `uberexec` and a number of links to that exec (`commanda`, `commandb`) that would eventually trigger the same behaviour as `uberexec commanda` or `uberexec commandb`.

Due to the considerable size of a Go executable and the complexities of a multibinary project (e.g: Gogland do not support it) multiple binaries might not be an option.

Perhaps It would be advisable to use the [deference flag](http://www.gnu.org/software/tar/manual/html_node/dereference.html) in tar or allow the configuration of the flags in a per type basis.

**Comment by caarlos0** [comment]
Yeah, maybe. We don't actually call GNU tar though, we use the native Go implementation.

I'm sure it's possible to implement this, though...

**Comment by caarlos0** [comment]
I did take a look at that time and couldn't find a way of doing this with go tar package... anyone?
