### ISSUE TITLE
[Bug]: Custom release header doesn't remove built in header

### ISSUE THREAD

**Issue by cdhunt** [goreleaser/goreleaser#2780]
### What happened?

I'm using [`--release-header`](https://github.com/StackExchange/dnscontrol/blob/fix/release/.circleci/config.yml#L129) and a [file](https://github.com/StackExchange/dnscontrol/blob/fix/release/.circleci/header.md) with a single line of text. It produces release notes as I expect, but also still includes the default "What's Changed" text. Can I make goreleaser not generate the "What's Changed" text?

![image](https://user-images.githubusercontent.com/114173/146940753-0be3ad5f-c2c1-4ce5-b9d9-3dd895789fa3.png)

### How can we reproduce this?

Fork https://github.com/StackExchange/dnscontrol/tree/fix/release and run `goreleaser release --rm-dist --release-header .\.circleci\header.md`

### goreleaser version

```bash
goreleaser version 1.1.0
commit: af4a8642bddb171914ee932bfb5768f102c3516f
built at: 2021-11-28T23:41:04Z
built by: goreleaser
module version: v1.1.0, checksum: h1:YySqqYTX9kxRU0e/fGQrhivXk8/zD4iUOlL7h0I2gBk=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
maybe you're looking to replace the whole release notes instead? 

but no, there is no way to remove the title for now, and likely will not be

**Comment by cdhunt** [comment]
I like the notes as generated. I just don't need two headers.
