### ISSUE TITLE
Error in checksum verification

### ISSUE THREAD

**Issue by AyushIITR007** [goreleaser/goreleaser#2788]
### What happened?

I tried downloading goreleaser using https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh file. But I am getting error:

```
RUN curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh:                                      
#7 1.106 goreleaser/goreleaser info checking GitHub for latest tag
#7 2.032 goreleaser/goreleaser info found version: 1.2.2 for v1.2.2/Linux/x86_64
#7 6.158 goreleaser/goreleaser err hash_sha256_verify checksum for '/tmp/tmp.v4son8lWuq/goreleaser_Linux_x86_64.tar.gz' did not verify 4ef68da9014df222c94ccefa02b01fdf96d414c1c775dbee5fadda53cd74ff71
#7 6.158 5847d0acf29a69549e98408b7c55ccb3fb8586b1eb5e61a89ba246079d31b3be vs 4ef68da9014df222c94ccefa02b01fdf96d414c1c775dbee5fadda53cd74ff71
```

### How can we reproduce this?

`RUN curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh`

### goreleaser version

```bash
v1.2.2
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Checksum verification is failing upon installing of goreleaser v1.2.2. 
It appears to be comparing checksum for  goreleaser_Linux_x86_64.tar.gz.sbom in place of  goreleaser_Linux_x86_64.tar.gz.

4ef68da9014df222c94ccefa02b01fdf96d414c1c775dbee5fadda53cd74ff71  goreleaser_Linux_x86_64.tar.gz
5847d0acf29a69549e98408b7c55ccb3fb8586b1eb5e61a89ba246079d31b3be  goreleaser_Linux_x86_64.tar.gz.sbom

These checksum values I found in the checksum.txt for v1.2.2.

**Comment by theganyo** [comment]
+1. Also seeing this.

**Comment by caarlos0** [comment]
last log line says this script is deprecated

refs https://github.com/goreleaser/godownloader/issues/207

**Comment by AyushIITR007** [comment]
Hi, @caarlos0 I tried installing go releaser using 
go install github.com/goreleaser/goreleaser@latest
But it is giving error that:

```
go install github.com/goreleaser/goreleaser@latest: github.com/goreleaser/goreleaser@none updating to
#5 880.4        github.com/goreleaser/goreleaser@v1.2.5 requires
#5 880.4        github.com/vartanbeno/go-reddit/v2@v2.0.1: reading github.com/vartanbeno/go-reddit/go.mod at revision v2.0.1: unknown revision v2.0.1
```

I checked in the github.com/vartanbeno/go-reddit/ the latest version is 2.0.0.
How should I proceed?

**Comment by caarlos0** [comment]
that seems to be an issue on that dep, I think they recreated the tag https://github.com/vartanbeno/go-reddit/issues/26

depending on which gosum db you are using it seems to cause problems... you can also install goreleaser from the binaries

**Comment by caarlos0** [comment]
I changed the version we are using, can you retry the go install bit @AyushIITR007 ?

**Comment by AyushIITR007** [comment]
Hi @caarlos0 I retried the go install but it is again giving the same error.
`go: downloading github.com/goreleaser/goreleaser v1.2.5
go install github.com/goreleaser/goreleaser@v1.2.5: github.com/goreleaser/goreleaser@none updating to
	github.com/goreleaser/goreleaser@v1.2.5 requires
	github.com/vartanbeno/go-reddit/v2@v2.0.1: reading github.com/vartanbeno/go-reddit/go.mod at revision v2.0.1: unknown revision v2.0.1`

**Comment by caarlos0** [comment]
I think you'll need to try `go install github.com/goreleaser/goreleaser@main`
