### ISSUE TITLE
Consider removing "setting defaults" from the output

### ISSUE THREAD

**Issue by ahmetb** [goreleaser/goreleaser#2794]
### Is your feature request related to a problem? Please describe.

The following part of the `goreleaser` output has always left me scratching my head. It shows me all these technologies I have not configured in my `.goreleaser.yml` file and it surely takes more than half of my `goreleaser` output. 

I also don't know the answer to this but: does setting defaults ever fail? If not, this output is probably a lot less useful.

```
   • setting defaults 
      • snapshotting     
      • scm releases     
      • project name     
      • loading go mod information
      • building binaries
      • universal binaries
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • signing docker images
      • cataloging artifacts
      • docker images    
      • docker manifests 
      • artifactory      
      • blobs            
      • homebrew tap formula
      • krew plugin manifest
      • gofish fish food cookbook
      • scoop manifests  
      • discord          
      • reddit           
      • slack            
      • teams            
      • twitter          
      • smtp             
      • mattermost       
      • milestones       
      • linkedin         
      • telegram         
```

### Describe the solution you'd like

If a user is not making use of these build/release options, maybe they should not see what's being configured behind the scenes.

As a user I'm minimally interested in the inner workings of goreleaser, despite this supported release platforms output is good for a education purposes (and even one of the tools I developed are listed, so it's free ad space for sure for my project).

### Describe alternatives you've considered

I've looked at the cmdline options to see if there's a --slim output option that'd just show me "hey, here's the detected tag/commit, here I am compiling, here I am compressing into archives, here I am writing checksums.txt, and it's done" and not much more else. 

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by developer-guy** [comment]
maybe we can make that optional by tying it to a special flag. Would it make sense?

**Comment by ahmetb** [comment]
I think with the arguments provided, I see more reasons to hide it by default than showing it by default (which is often done by -v/--verbose type of flags).

**Comment by developer-guy** [comment]
SGTM

**Comment by developer-guy** [comment]
We have the `Skip()` method to make pipes compliant with an interface, so, we can add verbosity control over there:

https://github.com/goreleaser/goreleaser/blob/df0216d5855e9283d2106fb5acdb0e7b528a56e8/internal/pipe/defaults/defaults.go

**Comment by developer-guy** [comment]
PTAL @caarlos0

**Comment by caarlos0** [comment]
the skip thing would skip the entire thing... I'm up for removing these logs, though, they are not useful anyway
