### ISSUE TITLE
artifacts.json has user read/write permission only

### ISSUE THREAD

**Issue by rpothier** [goreleaser/goreleaser#2800]
### What happened?

When the artifacts are created, most items are create with 644 `-rw-r--r--` permissions, however the new 
artifacts.json file is created with 600 `-rw-------`, which I believe is set [here](https://github.com/goreleaser/goreleaser/blob/main/internal/pipe/artifacts/artifacts.go#L27) 

The problem is if the files are created and another process like Jenkins tries to copy the files is fails
for artifacts.json, but all the other files are copied.

### How can we reproduce this?

I think that artifacts.json is always written as 600
`-rw------- 1 root root    5253 Dec 29 14:48 artifacts.json`
where the other files have 644
`-rw-r--r-- 1 root root     688 Dec 29 14:48 SHA256SUMS.txt`

### goreleaser version

```bash
goreleaser version 1.2.3
commit: 89ece5595a924dc6d3b3f2f1a741e420a209757b
built at: 2021-12-29T19:12:42Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.2.3, checksum: h1:YtE5+XnVXMIYKok+IWptIYphV3iEgJjXDvPLvnu5Bvk=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
Will try to fix and release Thai today... shouldn't have been 0600 🤔

**Comment by rpothier** [comment]
Thanks for the quick response!
