### ISSUE TITLE
Docker pushing: denied: not_found: owner not found

### ISSUE THREAD

**Issue by rafaribe** [goreleaser/goreleaser#2815]
### What happened?

I'm trying to setup a CI pipeline for this open source repository. Still no code yet, just evaluating this tool. 
It all works fine up until the docker image push. 
This only works if I create a tag with `semver`, it won't fail otherwise. 

```publishing       
      • docker images    
         • pushing                   image=ghcr.io/helium-diy/lightweight-dashboard:0.0.4
   ⨯ release failed after 38.20s error=docker images: failed to publish artifacts: failed to push ghcr.io/helium-diy/lightweight-dashboard:0.0.4: exit status 1: The push refers to repository [ghcr.io/helium-diy/lightweight-dashboard]
a247e2708871: Preparing
07d3c46c9599: Preparing
denied: not_found: owner not found

Error: The process '/opt/hostedtoolcache/goreleaser-action/1.2.5/x64/goreleaser' failed with exit code 1
```

### How can we reproduce this?

[Github Workflow](https://github.com/HeliumDIY/lightweight-dashboard/blob/ci/.github/workflows/release.yaml)
[GoReleaser Config](https://github.com/HeliumDIY/lightweight-dashboard/blob/main/.goreleaser.yaml)

### goreleaser version

```bash
`goreleaser/goreleaser-action@v2`
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I've looked at @caarlos0's blog post and example repos, not sure yet what's breaking this. I also tried to override the `entrypoint.sh` with `$DOCKER_REGISTRY`  `$DOCKER_USERNAME` and `$DOCKER_PASSWORD` with no avail.

**Comment by caarlos0** [comment]
`ghcr.io/helium-diy/lightweight-dashboard`

I think its because `helium-diy` is not a valid github username/org.

This has nothing to do with goreleaser, its a ghcr limitation.
