### ISSUE TITLE
apt-get repos use an expired certificate in their chain

### ISSUE THREAD

**Issue by pzduniak** [goreleaser/goreleaser#2827]
### What happened?

I'm running Ubuntu 20.04 in WSL2

```
Ign:18 https://repo.goreleaser.com/apt  Packages
Ign:20 https://repo.goreleaser.com/apt  Translation-en
Err:18 https://repo.goreleaser.com/apt  Packages
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 18.214.196.109 443]
Ign:20 https://repo.goreleaser.com/apt  Translation-en
Fetched 11.2 MB in 5s (2418 kB/s)
Reading package lists... Done
E: Failed to fetch https://repo.goreleaser.com/apt/Packages  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 18.214.196.109 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
```

### How can we reproduce this?

```bash
echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
sudo apt update
sudo apt install goreleaser
```

### goreleaser version

Can't do. I also lied about the GoReleaser check!

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

The best feature of TLS - it randomly breaks your stuff!

**Comment by caarlos0** [comment]
weird... I don't get that error here... can you check if it's still happening?

Our repo is managed by gemfury, so maybe its something on their end

**Comment by caarlos0** [comment]
I guess this is not happening anymore as no one complained about it anymore... so... closing...

**Comment by pzduniak** [comment]
Thanks for investigating anyways, I suppose I hit some cached cert. I confirm that I can't reproduce it anymore.
