### ISSUE TITLE
Enable Publishing SNAPSHOT Builds

### ISSUE THREAD

**Issue by suddendust** [goreleaser/goreleaser#2828]
### Is your feature request related to a problem? Please describe.

We simply want GoReleaser to build a Docker image on every commit push to a PR. This helps us test the Docker image in our staging environment before we actually merge the PR. GoReleaser's `SNAPSHOT` builds do not allow publishing artefacts right now. A [request](https://github.com/goreleaser/goreleaser/issues/727) for this feature was raised earlier but was marked as `wontfix` for the time being.

### Describe the solution you'd like

On every push, GoReleaser should:
- Create a new `SNAPSHOT` image. Even better if we can have images tagged with the commit hash.
- Push this image to the repository.
- It should not do any Github Release. 

So essentially, `--skip-publish` should also let us push to the repository.

### Describe alternatives you've considered

A workaround is to have a separate Github Action to publish the `SNAPSHOT` image GoReleaser just created. 

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
this feature already exists https://goreleaser.com/customization/nightly/

PS: only on goreleaser pro at the moment

**Comment by clementnuss** [comment]
for reference, you can use something like this do publish `SNAPSHOT` build images:

https://github.com/postfinance/hostlookuper/blob/ee8d20b946f4ff433b37de727f8714bd3a29022a/.github/workflows/goreleaser.yaml#L47-L55
