### ISSUE TITLE
Evaluate to add goreleaser container to artifacthub

### ISSUE THREAD

**Issue by dirien** [goreleaser/goreleaser#2830]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

ArtifactHub has a new feature called Container images repositories. 

In this issue, I would like to add gorleaser container to ArtifactHub

https://artifacthub.io/docs/topics/repositories/#container-images-repositories

### Describe alternatives you've considered

-

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dirien** [comment]
@caarlos0, If its okay I would like to evaluate this.

**Comment by caarlos0** [comment]
don't know how that works, feel free to explore ✌️

**Comment by caarlos0** [comment]
is this done @dirien ?

**Comment by dirien** [comment]
@caarlos0, I wait for the next release.

Currently it fails, of the missing labels.
![image](https://user-images.githubusercontent.com/38325136/152743332-4836d0db-eef5-4d43-85ac-4619df2a7616.png)


Btw: You should create an ArtifactHub account, so I can transfer later the ownership to the GoReleaser Orga.

**Comment by caarlos0** [comment]
ah, ok @dirien 

already have one: `caarlos0` 🙏

**Comment by dirien** [comment]
Done :) 

https://artifacthub.io/packages/container/goreleaser/goreleaser
