### ISSUE TITLE
homebrew will not create branch if it does not exist

### ISSUE THREAD

**Issue by ekristen** [goreleaser/goreleaser#2831]
### What happened?

If you specify a branch under the brews sections for the Formula to be pushed to and it does not exist, it just errors out with a 404.

### How can we reproduce this?

Try the homebrew tap feature, set a non-existent branch and run goreleaser

### goreleaser version

```bash
goreleaser version 1.1.0
commit: af4a8642bddb171914ee932bfb5768f102c3516f
built at: 2021-11-28T23:41:04Z
built by: goreleaser
module version: v1.1.0, checksum: h1:YySqqYTX9kxRU0e/fGQrhivXk8/zD4iUOlL7h0I2gBk=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
not a bug, it was never implied it would create the branch, more like a feature request - which is a good one imho

**Comment by ekristen** [comment]
Gotcha. The docs say otherwise. 

> # Optionally a branch can be provided. If the branch does not exist, it
> # will be created. If no branch is listed,

**Comment by caarlos0** [comment]
hmmm wrong docs then :D 

or maybe in the past the github api did it automatically

**Comment by caarlos0** [comment]
will update the docs in the meantime...

**Comment by caarlos0** [comment]
seems like there isn't an API for it anymore 🤔 

https://docs.github.com/en/rest/reference/branches

the go-github lib also does not have a create branch repo https://github.com/google/go-github/blob/master/github/repos.go 

that said, not much we can do here. The docs were updated, at least.

thanks for letting me know of this issue!

cheers
