### ISSUE TITLE
Changelog transform command

### ISSUE THREAD

**Issue by tj** [goreleaser/goreleaser#284]
Hey hey!

I was thinking a clean way to implement changelog massaging without getting into templates would be to simply pass it through stdio of an optional command (shell).

Then something like `changelog: sort | grep -v docs` could group them together and filter some of the less important stuff. 

<img width="707" alt="screen shot 2017-07-04 at 6 29 48 pm" src="https://user-images.githubusercontent.com/25254/27845850-988bac80-60e7-11e7-912e-4601995ea279.png">

**Comment by caarlos0** [comment]
hey @tj 🎉 

hmm, right you can do it with ~~some~~ a lot of hacking:

```
goreleaser --release-notes <(git log --pretty=oneline --abbrev-commit $(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^)..$(git describe --tags --abbrev=0) | sort | grep -v docs)
```

I agree that this is not ideal though. The entire changelog is kind of crappy and very basic right now... I'm thinking about improving it by adding PRs merged, issues closed, contributors and that kind of fluffy stuff... For sure personalization would be in mind for all that =D

I was thinking about doing something like this:

```
changelog: # new pipe yay
  sort:
    by: title / commit / none
    direction: asc / desc
  filter:
    - word1
    - word2
```

This would cover your current request, and we may continue adding new features later.

What do you think?

**Comment by tj** [comment]
hmm yea I wonder where to draw the line, having some things baked in would be convenient. I'd be happy with even just being able to specify --release-notes in the config, then we can chuck that one-liner in there or maybe I'll write a little Go program to organize it a bit

**Comment by tj** [comment]
Actually --release-notes is probably fine! Feel free to close if no one else wants it

**Comment by caarlos0** [comment]
Nice!

FWIW I think hugo has some custom scripts as well, you can check the source or maybe ping <at>bep :P 

I'll leave the issue here for now... will think more about it later :)

**Comment by jorinvo** [comment]
I like the current approach via `--release-notes`. 
By dealing with plain files you are flexible to do unixy things as @caarlos0 showed above, which would be more difficult with a setting in the configuration file.
If we would add changelog options to GoReleaser, it would be hard to decide what should be added and what should be skipped.
I guess in many cases users also like to have a completely custom changelog.

Maybe we can add some examples for different formats to the documentation in the README.
We can start by adding the example from above and later on we can add more examples commands to generate the changelog.

I'm not sure about this, but when running on Travis for only tags, couldn't the above Git command be written as
`git log --pretty=oneline --abbrev-commit $(git describe --tags --abbrev=0)^..HEAD`?

The whole thing would be:
```
goreleaser --release-notes <(git log --pretty=oneline --abbrev-commit $(git describe --tags --abbrev=0)^..HEAD | sort | grep -v docs)
```

**Comment by caarlos0** [comment]
> I'm not sure about this, but when running on Travis for only tags, couldn't the above Git command be written as
> git log --pretty=oneline --abbrev-commit $(git describe --tags --abbrev=0)^..HEAD?

probably yes...

**Comment by caarlos0** [comment]
@jorinvo I agree, but I also think that most what people want to do is remove commits that match some regexp.

I'll try to hack something for this so we can ask around how people like it or not =)

**Comment by caarlos0** [comment]
hey ho folks, check out https://github.com/goreleaser/goreleaser/pull/401 :D

cc/ @tj @jorinvo

**Comment by caarlos0** [comment]
TODO:

- [ ] check for invalid configs
- [ ] add sorting support

@tj any other features you find useful having here? I ask because you have many projects and therefore lots of experience with this (I guess) 🍻

**Comment by tj** [comment]
sorting might be cool too, assuming people stick with prefixes that make sense. That might be too arbitrary though, but I manually sort like https://github.com/apex/up/releases/tag/v0.2.4 so all the `add`s etc are in one spot

**Comment by caarlos0** [comment]
yeah, that makes a lot of sense!

I'll add this feature as well =)

thanks

**Comment by tj** [comment]
dope! Thanks man

**Comment by caarlos0** [comment]
Done 🎉
