### ISSUE TITLE
Feature Request: support GitHub Action Contexts built-in

### ISSUE THREAD

**Issue by developer-guy** [goreleaser/goreleaser#2840]
### Is your feature request related to a problem? Please describe.

GoReleaser has its kind of [templating logic](https://github.com/goreleaser/goreleaser/blob/2c6b51cc652ccf1831d173841f119b551909c06b/internal/tmpl/tmpl.go#L73) and provides a bunch of valuable fields that we can use in our .goreleaseer.yml file, please see [Name Templates](https://goreleaser.com/customization/templates/). Also, Github Actions provides a bunch of proper [contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#about-contexts) for us to use. We can pass one of the parameters within the contexts to GoReleaser via the environment variable. Still, IMO, we can support one of the contexts supported in GitHub Actions in GoReleaser builtin.

cc: @dentrax @dirien 

### Describe the solution you'd like

Once, we complete the implementation people now be able to use GitHub contexts in GoReleaser like the following:

```shell
{{ .GitHub.repository.owner }}'
```
> https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

### Describe alternatives you've considered

We can use Env global name template for it as I mentioned in the feature request description.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
Although its cool, I'm not sure its worth it... 

Doing so would make some configs impossible to run locally and on other CIs as well... so I'm leaning to a no here 🤔

**Comment by caarlos0** [comment]
since that would break outside github actions, and this can be already emulated by passing each needed value as an environment variable, lets leave this out for now.

we can always discuss this again later
