### ISSUE TITLE
ORAS support

### ISSUE THREAD

**Issue by dirien** [goreleaser/goreleaser#2856]
### Is your feature request related to a problem? Please describe.

I would like to add [ORAS](https://oras.land/) support to GoReleaser so we can "publish" the artifacts and any additional metadata to an OCI storage.

### Describe the solution you'd like

Adding native(!) ORAS support to goreleaser

### Describe alternatives you've considered

-

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

If its okay @caarlos0, I would like to implement this.

**Comment by caarlos0** [comment]
Can you describe what you have in mind on how to achieve this? 
Also, what would the advantages to do so be?

**Comment by dirien** [comment]
TBH, its just another medium to archive the binary. Rather then the classic image, which can be executet in a container based CI system or localy.

**Comment by caarlos0** [comment]
lets wait for now, judging by number of stars its very popular right now... 

maybe in the future.
