### ISSUE TITLE
Birise tools

### ISSUE THREAD

**Issue by joeblew99** [goreleaser/goreleaser#287]
Bitrise allows building golang based android and iOS apps.

It is easy for go reader to tap into because it is itself written in golang.

I am on my mobile but you will find it with a little googling.

They also have a full CI that you can run locally or use their cloud. It's super open.

They have a ton of other stuff I use tool like automatic mobile simulator setup and testing.

You can use it for simple golang stuff too.

They have signing utils too.
Also stuff to make the icons for desktop and mobile GUI apps written in golang..

Anyway have a look, and if you have questions I will help with it.

**Comment by jorinvo** [comment]
Thank you.
