### ISSUE TITLE
Create Pull Requests for brew formula update

### ISSUE THREAD

**Issue by mitalipaygude** [goreleaser/goreleaser#2870]
### Is your feature request related to a problem? Please describe.

I used goreleaser for automating my brew formula update, but I did not come across an option to create a pull request for that update. The only thing we can do is directly commit to a given repository.

### Describe the solution you'd like

An additional feature request for be able to create a pull request for brew formula updates so that we can update the formulae in different repositories without having their GITHUB_TOKEN.

### Describe alternatives you've considered

Alternative solutions to creating a pr for brew formula update are via Github Actions.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
happy to accept a PR with this

**Comment by caarlos0** [comment]
seems like there is no API to create a branch, hence, we cannot create pull requests 

https://github.com/goreleaser/goreleaser/issues/2831 

an alternative would be to rewrite this using git directly, but that's not something I'm planing in doing any time soon.

that said, closing this, for now at least


thanks for the suggestion though.
