### ISSUE TITLE
[Pro] Global Hooks do not show stdout/stderr

### ISSUE THREAD

**Issue by aeneasr** [goreleaser/goreleaser#2875]
### What happened?

I am running a bash script aspart of the after hook

```
after:
  hooks:
    - cmd: "bash -c docs.sh"
```

and the script is not doing what it should. It would be easy to identify what is going on but unfortunately goreleaser is not showing the stdout of the command.

### How can we reproduce this?

Create `script.sh`:

```shell
#!/bin/bash

echo "hello world"
```

and config:

```yaml
# ...

before:
  hooks:
    - cmd: "sh ./script.sh"

# ...
```

then

```
goreleaser build --skip-validate
```

The output is then:

```
   • running before hooks
      • running hook              hook=sh ./script.sh
```

and I can not find "hello world" in the output. It is possible with `--debug` to see some output but it is very hard to read due to verbosity of `--debug`.

### goreleaser version

```bash
goreleaser version 1.4.1-pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I think we can add an option, as we did on the signing step, to always output.

Thanks for the suggestion @aeneasr 🙏

**Comment by caarlos0** [comment]
fixed, will be out on next version!

thanks again @aeneasr 🙏

**Comment by torarnv** [comment]
I'm possibly confused here, but when trying this:
```yaml
before:
  hooks:
    - cmd: echo 123
      output: true
```

I'm left with:

```
 • loading config file                              file=.goreleaser.yml
  ⨯ release failed after 0s                  error=yaml: unmarshal errors:
  line 6: cannot unmarshal !!map into string
```

Does this not work for global hooks, only build hooks? Or is my syntax wrong?

**Comment by caarlos0** [comment]
@torarnv it works, but only on goreleaser pro.

https://goreleaser.com/customization/hooks/

**Comment by torarnv** [comment]
Ah, thanks

**Comment by caarlos0** [comment]
maybe, I'll think about it.
