### ISSUE TITLE
Procedure for verification of release files lacks verification of public key

### ISSUE THREAD

**Issue by cardil** [goreleaser/goreleaser#2876]
### What happened?

The procedure for verification of release files lacks verification of public key:

https://github.com/goreleaser/goreleaser/blob/9cc1bb1595fc6ab726595ebbbe7e9611de3949c6/www/docs/install.md#L156-L162

The attacker could easily replace all files, including the public key. Without checking the public key is valid, users can't be sure the downloads are valid. Public key needs to be verified, before being trusted.

Proper procedure should include something like:

> 2. Verify the public key fingerprint by running command:
> ```
> $ base64 -d checksums.txt.pem | openssl x509 -noout -fingerprint
> SHA1 Fingerprint=63:44:7F:5F:EE:A7:D9:14:20:B3:22:9F:40:25:BB:94:5D:8B:03:67
> ```

### How can we reproduce this?

Go to: https://goreleaser.com/install/?h=verify#verifying-the-artifacts

### goreleaser version

```bash
Do not apply
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
Thanks @cardil 

Feel free to PR this if you want, otherwise I'll do it when I have some time :)

**Comment by cardil** [comment]
The question would be: How users can make sure the public key they are downloading is valid? If attacker can replace release files, surly he can also craft a public key, or make changes to the website.

Cosign keyless mode solves this issue by utilizing rektor log.

Gpg public keys can be stored on keys.opengpg.org and search by email, and that gives quite strong signal the key is valid.

**Comment by caarlos0** [comment]
hey, I'm using keyless only...

**Comment by caarlos0** [comment]
this is being fixed in upstream cosign https://github.com/sigstore/cosign/pull/2058

cosign will still be needed to verify the signatures though.

that said, closing
