### ISSUE TITLE
RPM Sign fails since Version 1.2.0

### ISSUE THREAD

**Issue by zbindenren** [goreleaser/goreleaser#2895]
### What happened?

I upgrade go releaser to latest version 1.4.x and RPM signing does not work:

```console
$ rpm -qip dist/create-go-app-0.19.1-1.x86_64.rpm                                                                                                          
error: dist/create-go-app-0.19.1-1.x86_64.rpm: Header RSA signature: BAD (package tag 268: invalid OpenPGP signature)                                                                                                                                       
error: dist/create-go-app-0.19.1-1.x86_64.rpm: not an rpm package (or package manifest) 
```

### How can we reproduce this?

With the command:

```console
goreleaser release --snapshot --rm-dist
```

### goreleaser version

```bash
Not working: 1.2.0-1.4.x

Last working version: 1.1.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
could you provide a reproducible? (minimal possible config/code/etc)

**Comment by zbindenren** [comment]
hi @caarlos0 

yeah I created a project here: https://github.com/zbindenren/gorleaser-sign

How I ran the command is written in the README.

**Comment by caarlos0** [comment]
OK, pinned down the issue to the upgrade of `github.com/ProtonMail/go-crypto v0.0.0-20210512092938-c05353c2d58c // indirect` to `github.com/ProtonMail/go-crypto v0.0.0-20211112122917-428f8eabeeb3 // indirect`.

Will revert this upgrade for now, but, right now I have no idea why it breaks.

**Comment by LeSuisse** [comment]
FYI I took a quick look at this (I encountered the same issue in another project), it appears that recent version of the library sets the critical bit on the issuer subpacket. This does not seems to play well with RPM...

Signature done with a recent version of the library:
```
# off=0 ctb=c2 tag=2 hlen=3 plen=307 new-ctb
:signature packet: algo 1, keyid 03F05554230DD349
	version 4, created 1646377639, md5len 0, sigclass 0x00
	digest algo 8, begin of digest 51 03
	hashed subpkt 2 len 4 (sig created 2022-03-04)
	critical hashed subpkt 16 len 8 (issuer key ID 03F05554230DD349)
	hashed subpkt 33 len 21 (issuer fpr v4 7D5731EFC420F8ECFD2FBB8C03F05554230DD349)
	data: [2048 bits]
```

Signature done with an older version of the library:
```
# off=0 ctb=c2 tag=2 hlen=3 plen=307 new-ctb
:signature packet: algo 1, keyid 03F05554230DD349
	version 4, created 1646379657, md5len 0, sigclass 0x00
	digest algo 8, begin of digest 6c d9
	hashed subpkt 2 len 4 (sig created 2022-03-04)
	hashed subpkt 16 len 8 (issuer key ID 03F05554230DD349)
	hashed subpkt 33 len 21 (issuer fpr v4 7D5731EFC420F8ECFD2FBB8C03F05554230DD349)
	data: [2047 bits]
```
