### ISSUE TITLE
Binary diff support

### ISSUE THREAD

**Issue by tj** [goreleaser/goreleaser#290]
I'm not familiar with the existing formats or pkgs, but @c4milo was suggesting binary diffs for https://github.com/tj/go-update which is would be a really cool addition to tarballs. Would you be into supporting diffs along side the existing options?

**Comment by caarlos0** [comment]
Not sure what you're asking... you want to be able to upload a diff between binaries?

**Comment by tj** [comment]
Yep. Looks like there are quite a few Go packages for it, it's not something I need right now but happy to research and contrib later if the maintainers are interested.

**Comment by jorinvo** [comment]
It sounds like something that would be a good fit for the scope of GoReleaser.
As far as I understand, it would be implemented similar to checksums since it works on the created artifacts/binaries.
I guess it would be a useful feature, but I'm afraid I don't really understand what it's used for. @tj could you please explain a bit more what binary diffs are used for?
Can you use them to only send the changed parts of a binary to users instead of the whole binary? I guess there also needs to be an algorithm on the user-side to stitch together the different binary parts for this kind of updates?

**Comment by caarlos0** [comment]
yeah, it seems useful for applying updates without having to download the entire binary... seems good indeed!

**Comment by tj** [comment]
@jorinvo yep you'd just fetch the patches that are required to upgrade to the latest version. I haven't tried so I'm not sure how effective they'd be, but if ~90% of your project is external packages and stdlib it should be pretty good!

**Comment by caarlos0** [comment]
@tj Assuming that the user runs it often, probably yes...

**Comment by tj** [comment]
haha yea, if it's really outdated probably better off having the updater grab the tarball

**Comment by caarlos0** [comment]
oops, closed the wrong issue.

**Comment by jorinvo** [comment]
I did some more research.
Seems pretty easy to do the diff itself using this package: https://godoc.org/github.com/kr/binarydist
What I am struggling with is what to generate the diff of. 
I was thinking that it probably is reasonable to only generate the diff to the latest version.
Then we still need to do so for all generated binaries. And in the case of archives, I guess we have to still generate a diff of the binary only, not the archive.
Now we need to get the latest version somehow. I guess we can run the *build* pipeline using the previous Git tag to generate the previous binary. 
And in the case that there is no previous tag, I guess the diff is simply the whole binary? Or we have to skip the diff creation in that case.

I would also be willing to give this a try, but I would happy to get some feedback if this sounds reasonable or you can think of another approach @caarlos0, @tj. Thanks!

**Comment by tj** [comment]
FWIW it's probably not really worth implementing, most Go bins are pretty small, but it would be interesting to try

**Comment by jorinvo** [comment]
I would also not mind leaving this waiting until someone has an actual use case they need it for. Personally, I don't think I will encounter a situation where are whole Go binary is too big to ship.

**Comment by caarlos0** [comment]
I agree. Not a common use case I guess
