### ISSUE TITLE
Sign our own apks, deb and rpms

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#2903]
### Is your feature request related to a problem? Please describe.

Currently we don't sign our linux packages. We should.

### Describe the solution you'd like

sign them.

### Describe alternatives you've considered

n/a

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

One possible problem here is that I don't know how gemfury handles signed packages. Will have to look into that.

refs #rpm

**Comment by francislavoie** [comment]
> One possible problem here is that I don't know how gemfury handles signed packages. Will have to look into that.

Unfortunately gemfury doesn't handle signing, although they had it listed as a planned feature. We (Caddy) tried to reach out to them multiple times by email and got radio silence from them...

We moved to CloudSmith for Caddy instead, and they do signing on their end after the upload (we had to upload a subkey so their system would do it).

**Comment by caarlos0** [comment]
so, if I upload a signed deb to gemfury, it just breaks? thats too bad

thanks for letting me know @francislavoie 🙏

Will look into cloudsmith too.

**Comment by francislavoie** [comment]
> so, if I upload a signed deb to gemfury, it just breaks?

From their docs:

https://gemfury.com/help/gemfury-cli/

> At the moment, Gemfury does not support GPG-signed Release file. The `[trusted=yes]` parameter is important to tell APT to trust this repo without a signature. We will update this help page once GPG support is available.

**Comment by caarlos0** [comment]
ah, that's too bad :|

**Comment by caarlos0** [comment]
well, since we basically can't do this rn without a ton of work, closing it for now...
