### ISSUE TITLE
lintian /usr/local errors

### ISSUE THREAD

**Issue by staticdev** [goreleaser/goreleaser#2909]
### What happened?

By default Debian errors on any packages that has folder /usr/local (https://lintian.debian.org/tags/dir-in-usr-local) and especially is something is installed in it (https://lintian.debian.org/tags/file-in-usr-local).

I see that /usr/local/bin happens to be the default for nfpm. The default for Debian packages is to be installed in /usr/bin instead. I though of making a PR for that but not really sure how it affects APK and RPM packages. Maybe change just for DEB?

### How can we reproduce this?

Run lintian on a package done with latest nfpm. You will get something like:

```
% lintian cleancontacts_0.3.0_linux_amd64.deb 
E: cleancontacts: dir-in-usr-local usr/local/bin/
E: cleancontacts: file-in-usr-local usr/local/bin/cleancontacts
W: cleancontacts: file-in-unusual-dir usr/local/bin/cleancontacts
```

### nfpm version

```bash
2.13.0
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
see #2910
