### ISSUE TITLE
Optionally run `go mod vendor` for source archives?

### ISSUE THREAD

**Issue by francislavoie** [goreleaser/goreleaser#2911]
### Is your feature request related to a problem? Please describe.

We were asked on the Caddy project https://github.com/caddyserver/caddy/issues/4573 to provide a source bundle including vendored dependencies, so that builds can be produced without additional downloads.

### Describe the solution you'd like

An optional flag like `vendor: true` in https://goreleaser.com/customization/source/ would be great. It should run `go mod vendor` to produce the `vendor/` dir in the project before zipping up the source.

### Describe alternatives you've considered

It would let us avoid having to write some custom shell script after the release to produce the extra tarball.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
not sure if its possible... we use `git archive` to create the source archive... so, if vendor is gitignored, it won't get picked - AFAIK

not sure if there's a way around this...

**Comment by francislavoie** [comment]
Hmm. We could remove `vendor/` from `.gitignore` on the Caddy repo, I don't think there's any reason for it to be there. But we definitely don't want to commit the vendor to the repo anymore (we did for Caddy v1 and it was a total mess).

https://stackoverflow.com/a/54036395/846934 suggests maybe we can just throw `vendor` in afterwards?

**Comment by caarlos0** [comment]
That's assuming tar, but it could be a myriad of formats.

You could, in theory, remove vendor from the gitignore, and run `go mod vendor` in a global before hook.

The vendor folder will be used to build - which shouldn't be a big deal, and will also be included in the source archive

**Comment by mohammed90** [comment]
The `git archive` command only packs tracked and committed files. So unignoring the `vendor` directory won't help, neither will running `go mod vendor` to create the directory. It can pack extra/untracked files with the flag `--add-file`, but that'll need to be repeated for as many files in the vendor dir.

**Comment by caarlos0** [comment]
> The `git archive` command only packs tracked and committed files. So unignoring the `vendor` directory won't help, neither will running `go mod vendor` to create the directory. It can pack extra/untracked files with the flag `--add-file`, but that'll need to be repeated for as many files in the vendor dir.

ah, indeed

**Comment by caarlos0** [comment]
then, if we do this, we might need to implement the archiving ourselves instead of relying on `git-archive`...

**Comment by mohammed90** [comment]
> then, if we do this, we might need to implement the archiving ourselves instead of relying on `git-archive`...

I think you could still piggy back on `git archive` by performing subsequent operations to append/remove file/dirs using github.com/mholt/archiver/v4, no?

**Comment by caarlos0** [comment]
seems to be in alpha, and at least on readme there is no example on how to add files with specific permissions, correct?

I need to test, but maybe our internal archiving library already works :P

**Comment by caarlos0** [comment]
I think the easiest way would probably be to do the whole git-archive thing on goreleaser itself (using git ls-files et al).

Will try to work on this for next release.

**Comment by caarlos0** [comment]
git archive now has a `--add-file` flag (or had before, and I missed it)

anyway, this makes the impl a lot easier, check #3102

**Comment by francislavoie** [comment]
Sweet, thanks!

Just so I understand, should we use `--add-file vendor` or should we use `--add-file vendor/*`?

**Comment by francislavoie** [comment]
Sorry I'm not sure I follow. Do you mean "yes, use `--add-file vendor`"?

**Comment by mohammed90** [comment]
> Sorry I'm not sure I follow. Do you mean "yes, use `--add-file vendor`"?

The flag is a `git archive` flag. We'll have to add `files:` the config the `.goreleaser.yml`

**Comment by francislavoie** [comment]
My question was more about whether we should use `vendor` or `vendor/*`, I realize we'll be using yaml to configure. But either way, we'll test it out soon. Thanks!

**Comment by caarlos0** [comment]
ah, I believe just `vendor` is enough, but its worth testing first...
