### ISSUE TITLE
Formulas generated by Goreleaser that only install a binary seem to require Xcode

### ISSUE THREAD

**Issue by mieubrisse** [goreleaser/goreleaser#2914]
### What happened?

Our users are consistently showing that they need to have Xcode installed to install [this formula](https://github.com/kurtosis-tech/homebrew-tap/blob/master/kurtosis-cli.rb). One user's Xcode was out of date, and Homebrew wouldn't let him install at all:

```
Error: Your Xcode (11.5) is too outdated.
Please update to Xcode 12.5 (or delete it).
```

I _think_ this started happening after https://github.com/goreleaser/goreleaser/issues/2595 .

### How can we reproduce this?

`brew install kurtosis-tech/tap/kurtosis-cli` without Xcode installed

### goreleaser version

```bash
goreleaser version 0.183.0
commit: be6199f08167cc85b0b16cefc02d8106237853b1
built at: 2021-10-21T00:56:27Z
built by: goreleaser
module version: v0.183.0, checksum: h1:nN//eVCpCzv8cC9YxC4tOOJJAkY0/KUe1j9eewo7WjI=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

That Xcode is required is surprising to me, as the formula just installs binaries from [this repo](https://github.com/kurtosis-tech/kurtosis-cli-release-artifacts/releases) - no source building needed.

**Comment by caarlos0** [comment]
afaik this is a homebrew requiring xcode, not the tap per se

**Comment by dirien** [comment]
Did not encountered this with goreleaser formula generation. As it is "only" the generation of the ruby file for homebrew tap

**Comment by caarlos0** [comment]
yeah, that's most likely a homebrew issue... pretty sure if you `brew install` anything it asks for xcode.

Closing.
