### ISSUE TITLE
Plug-in / hook to generate other artifacts (helm charts) etc

### ISSUE THREAD

**Issue by chainlink** [goreleaser/goreleaser#2918]
### Is your feature request related to a problem? Please describe.

It's currently tricky to coordinate the release of non-go related artifacts (helm charts, etc) along with the go release. Right now, you need to run go releaser to produce the GH release, then manually edit that release to add the additional artifacts. It would be nice if this could be accomplished within goreleaser.

### Describe the solution you'd like

I'd like to be able to generate a helm chart along with my go binaries and ideally have it attached to the GH release. Generalizing a bit, This would consist of two parts:

- a hook or plugin called during the build phase to build the non go artifact
- an "Extra artifacts" section in the release section to be included in the GH release. (perhaps keyed on the ID of the hook called during the build)

To be clear, helm releaser wouldn't be responsible for building these non go artifacts, but instead would call another tool to do that.

### Describe alternatives you've considered

It's definitely possible to run go releaser and then release the chart separately, but it's a pain to have to edit the existing release and add the helm artifact.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dirien** [comment]
Can you not use the hook function from either the build phase (https://goreleaser.com/customization/build/#build-hooks)

or the general hooks fn -> https://goreleaser.com/customization/hooks/

`after hook` is only in the Pro version available, but could be good time to buy the pro version?

**Comment by chainlink** [comment]
Ah nice! Apologies I missed those in your docs 🙈  That should solve the build piece, but what about the idea of additional artifacts on the GH release?

**Comment by caarlos0** [comment]
@chainlink there are options for it as well: https://goreleaser.com/customization/release/

check `extra_files`.

**Comment by dirien** [comment]
@caarlos0 thanks for the refresher on the extra_files tag! I forgot about this one! 👍

**Comment by chainlink** [comment]
Ah! We use `extra_files` in the docker section already, didn't think to look under the `release` section for the same. Next time I will have a closer read of the manual. Thanks for the help!
