### ISSUE TITLE
.TagSubject and .TagContents are using the underlying commit subject/contents instead of the ones from the annotated tag

### ISSUE THREAD

**Issue by Tuxdude** [goreleaser/goreleaser#2919]
### What happened?

`.TagSubject` and `.TagContents` in Release output are using the underlying commit subject/contents instead of the ones from the annotated tag.

[Here is a test repo](https://github.com/Tuxdude/go-scratch-gh/tags) where you can see this bug in action in the release notes generated, with the release for either of tags:
- [v0.3.0](https://github.com/Tuxdude/go-scratch-gh/releases/tag/v0.3.0) or
- [v0.3.1-rc0](https://github.com/Tuxdude/go-scratch-gh/releases/tag/v0.3.1-rc0)

Both have annotated subject and message body, that I have also verified using git as confirmed by these commands:

```
$ git tag -l --format='%(contents)' v0.3.1-rc0
Lot of exciting features in this release.

- Mix of both small and large changes in the same release.
- Improves performance by 5x compared to previous release.
- And more smaller changes to the codebase to improve readability.
```

```
$ git tag -l --format='%(contents:subject)' v0.3.1-rc0
Lot of exciting features in this release.
```

```
$ git tag -l --format='%(contents)' v0.3.0
Thirs release.

Excited to get a third release going for this test package, getting more
impactful changes out there!

That's all folks!
```

```
$ git tag -l --format='%(contents:subject)' v0.3.0
Thirs release.
```

My [`.goreleaser.yml`](https://github.com/Tuxdude/go-scratch-gh/commit/f1583aa39a7ce4fc66380f827add8d87abb9afa0#diff-7326b55c062b0f46fe9e39aace0a25f4515cf206040fb91a6fd2cae839f5e826) contains these sections to include both `.TagSubject` and `.TagContents` in the release notes header for demonstration:

```
release:
  header: |
    ## {{ .TagSubject }}
    {{ .TagContents }}
```

Also, I am using the `goreleaser/goreleaser-action@v2` github action in my workflow to cut releases. The [config](https://github.com/Tuxdude/go-scratch-gh/blob/master/.github/workflows/release.yml) is available here if it makes any difference.

### How can we reproduce this?

1. Create an annotated tag with both a tag subject and a message body.
2. Add the following to the `goreleaser.yml`
3. Invoke `goreleaser` to cut a new release.

```
release:
  header: |
    ## {{ .TagSubject }}
    {{ .TagContents }}
```

### goreleaser version

```bash
v1.5.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tuxdude** [comment]
Another data point from my side. Using `.TagSubject` in a different field in the config, eg. `archives.name_template` works. I do see the tag subject correctly being used in the generated artifact file names.

I am beginning to suspect if this is something specific to my github workflow/action.

**Comment by Tuxdude** [comment]
This seems to be an issue with the github workflow and checkout.

When the workflow is triggered based on a tag push, the checked out repository doesn't seem to contain the tag annotation metadata (although is aware of the tag name itself) only for the latest tag (which also triggered the github event for the workflow) but does contain this data for all prior tags.

I dumped this from the github workflow:

```
for tag in $(git tag -l); do echo -e "\n\n\nTag = $tag\n"; git tag -l --format='%(contents)' $tag; done


Tag = v0.1.0
First release to test how it goes


Tag = v0.2.0
Second release


Tag = v0.3.0
Thirs release.

Excited to get a third release going for this test package, getting more
impactful changes out there!

That's all folks!


Tag = v0.3.1-rc0
Lot of exciting features in this release.

- Mix of both small and large changes in the same release.
- Improves performance by 5x compared to previous release.
- And more smaller changes to the codebase to improve readability.


Tag = v0.4.0
Making a fourth release.

The fourth release is not all different from the third minor release
version, but hey we are moving further which is good!


Tag = v0.4.1
Cutting v0.4.1 for further testing.

Dummy tagging message body.

Let's see if it works this time.


Tag = v0.4.2
Another fresh tag to verify the release.

- Test123
- Foo
- Bar
- Baz


Tag = v0.4.3
Dump tag information in the worfklow.
```

**Comment by Tuxdude** [comment]
Root cause is https://github.com/actions/checkout/issues/290

Adding a github workflow steps which runs `git fetch --force --tags` fixes this.

**Comment by Tuxdude** [comment]
https://github.com/Tuxdude/go-scratch-gh/commit/f31ca61a7ce73b3c84c91f00db70a15646d78855 commit should give an idea for the fix to apply if anybody else runs into this issue.

Just like how setting `fetch-depth: 0` against `actions/checkout@v2` is [documented](https://goreleaser.com/ci/actions/#workflow), I feel it would be a good idea to also document this given that goreleaser does read the metadata of annotated tags in certain scenarios like these.

**Comment by caarlos0** [comment]
oh, cool finding, should definitely document this...
