### ISSUE TITLE
Override the commit author for brew

### ISSUE THREAD

**Issue by gedex** [goreleaser/goreleaser#292]
The commit author is currently hard coded to [goreleaserbot](https://github.com/goreleaser/goreleaser/blob/e8bdba5752e3e3b6a2a9850c64d333e1e4f81be7/internal/client/github.go#L34-L35). Is it possible to override that via `.goreleaser.yml` or maybe just use `ctx.Config.Brew.GitHub.Owner`?

**Comment by caarlos0** [comment]
Is a feature worth adding I guess

**Comment by caarlos0** [comment]
Using `ctx.Config.Brew.GitHub.Owner` won't work, we should use both username and email in order to make it look good.

Maybe use the current logged in user?

**Comment by caarlos0** [comment]
Also: PRs welcome :D
