### ISSUE TITLE
[Feature Request] add flatpak package building support

### ISSUE THREAD

**Issue by rare-magma** [goreleaser/goreleaser#2927]
### Is your feature request related to a problem? Please describe.

Some linux distributions use Flatpaks by default or don't have snap installed.

### Describe the solution you'd like

It would be great if goreleaser supported generating flatpak packages. 
Similar to what is currently done for snaps.

### Describe alternatives you've considered

N/A 
Haven't considered any alternatives

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

https://docs.flatpak.org/en/latest/

**Comment by caarlos0** [comment]
if someone wants to work on it, go ahead... I don't currently have the bandwidth

**Comment by caarlos0** [comment]
since this seems to have gathered no interest, will close it

if you disagree, let me know

**Comment by ottlukas** [comment]
What would be needed to add flatpak support. Can some of the developers give the community some hints / pointers to support flatpak?

**Comment by twpayne** [comment]
Yes, you'd need to write a pipe for Flatpaks.

Note that Flatpaks are focused on GUI applications and are not very convenient for CLI applications. I assume that most applications built with goreleaser are likely to be CLI applications).

**Comment by ottlukas** [comment]
> etbirdio/netbird#1038

Yes in case of https://github.com/netbirdio/netbird/issues/1038 it indeed is most of the part is CLI applications. which is already available without the GUI part. so will need to consult the https://github.com/netbirdio/netbird developers on how to integrate the GUI part. Probably similiar to the Windows GUI client. Thank you very much! :-)

**Comment by twpayne** [comment]
I spent a bit of time looking at Flatpak for chezmoi (a CLI app built with goreleaser) yesterday. The conclusion from the Flatpak developers is that CLI apps are not the target for Flatpak, and you need to bundle anything that your application uses in the Flatpak. See https://github.com/flatpak/flatpak/issues/5999 and https://github.com/twpayne/chezmoi/pull/4168 for discussion.

**Comment by caarlos0** [comment]
yeah, in that sense its pretty similar to snaps I think

i don't particularly like it, tbh

anyway, thanks for sharing the info @twpayne :)

**Comment by twpayne** [comment]
Snaps have the option of [classic confinement](https://snapcraft.io/docs/classic-confinement) which makes them useful for CLIs.

**Comment by caarlos0** [comment]
yep, its what goreleaser uses, although afaik to publish a classic confined snap you need to ask in a forum (or at least that was what I had to do years ago), and then they might approve you or not

**Comment by twpayne** [comment]
Yup, this was exactly my experience too. I had to request classic confinement for my project. Still, the fact that snaps have classic confinement as an available option, whereas Flatpaks have no such option, makes snaps concretely more useful than Flatpaks for many projects.

**Comment by reyamir** [comment]
> since this seems to have gathered no interest, will close it
> 
> if you disagree, let me know

I think Flatpak has become quite popular among Linux users - all my users are asking for a Flatpak package. Could you reconsider supporting it?

**Comment by caarlos0** [comment]
maybe...

**Comment by daegalus** [comment]
I use an Immutable distro, and Flatpak is one of the primary ways I get software installed. I also am a Go Dev and am working on some apps using Wails. I would greatly appreciate a Flatpak release capability so I can package my apps as Flatpaks, one for Dogfooding, but immutable distros are gaining popularity due to things like Bazzite, and it is much easier to work with Flatpaks, and safer, than layering RPM packages.

**Comment by adriens** [comment]
🗞️ [KDE Linux](https://community.kde.org/KDE_Linux) chose flatpak

**Comment by Archisman-Mridha** [comment]
Hm, Flatpak will be nice to have.... will be happy to contribute (under a little bit of guidance, since I'm running a bit less on time to figure everything out by myself)....

**Comment by caarlos0** [comment]
okay,
let's do it

**Comment by caarlos0** [comment]
if anyone has interest in contributing this, i'm happy to help :)

**Comment by daegalus** [comment]
I might have some time next week to take a crack at this

**Comment by caarlos0** [comment]
awesome, let me know how i can help :D

**Comment by daegalus** [comment]
> awesome, let me know how i can help :D

Well, something that you can I guess steer me on is feature set.

GoReleaser's role in a flatpak would be generating the manifests, xml files, and any supporting files. Similar to how it generates a Homebrew Formula or Cask.

The second part is more intricate: build and deploy. There are 2 routes for this. THe standard stuff like uploading a built flatpak package to arbitrary locations, like github releases, external stuff, etc. Stuff goreleaser already does. 

But then there is Flathub. We would need to upload all the supporting files to a different repo, almost a subrepo to the build, and then Flathub takes over. In those cases we have even more options. Generally, if possible the repos for Flathub releases build everything from scratch, including building the application from source (similar ot Homebrew Formulas and Bottles) that then get uploaded to their servers. Another option is you use it more like a Homebrew Cask, where the prebuilt binaries are downloaded and setup inside the flatpak, and then that gets wrapped up in a flatpak and gets uploaded. There is even technically a third option for proprietary closed source stuff, where it gets downloaded into the flatpak on first run, and goes from there.

This is all purely based on the user, but its a lot of avenues. I can add them all, I just want to hear from you on what level of scope and configuration you want to support.

We can leave running your own flatpak repo to the user, as i feel that is out of scope, but the ability to upload to a flatpak repo is also probably needed for those that don't want to go the Flathub route or host their own.

**Comment by caarlos0** [comment]
So, I see at least 2 features: building the flatpack, and publishing them.

I would say we can start with the building part, and then add publishing later.

For building, we'll need to add the artifact types in `artifacts.go`, and a new `Pipe` implementation, similar to the `nfpm` one. For the second feature, we can then decide to either make the pipe also implement `Publisher` or if we make another `Publisher` implementation just for flathub.

If I understand correctly, publishing the artifacts to another repo would be akin to what the cask pipe does, so we could do the same thing. 
Although, looking at, for example, [this pr](https://github.com/flathub/flathub/pull/7595) it seems more like the winget pipe we have - do we have to open a new pr for each version , or just once? If it's just once, then i don't think we need to have it all.


---

PS: sorry if this is a bit incoherent, kinda brain dumping

**Comment by daegalus** [comment]
Ummm, if we construct the flatpak yaml correctly there is an autoupdater that scans all flathub repos and if we have the right settings it will pull the new version and create a pr. Especially if it's a github release. But they have multiple ways of getting new versions.

So it can be a one and done situation.

If you do flathub, you dont need to build, just generate the yamls, supporting files, etc. You only need to build if you plan to release a `.flatpak` file.

**Comment by caarlos0** [comment]
hmmm interesting - i'm assuming most if not all people using flatpacks are using flathub? wdyt?

**Comment by adriens** [comment]
I do

**Comment by daegalus** [comment]
> hmmm interesting - i'm assuming most if not all people using flatpacks are using flathub? wdyt?

Yes, i would say majority use flathub. Its the official repo for the ecosystem.

Fedora runs their own but it grates the community for why they do it.

But there are a few other repos Ive encountered for individual projects, but being on flathub is the goal currently 

Do note, the offering a flatpak file still helps as you need to be approved to get a flathub repo

**Comment by caarlos0** [comment]
lets ship some form of this https://github.com/goreleaser/goreleaser/pull/6448

**Comment by daegalus** [comment]
I apologize for just kind of disappearing, I started a new job at a startup and a lot of my free time kind disappeared while I adjust back to startup work balance. 

The PR looks good and a good first step. Sets the foundation to build on ot add other features or flathub support later on.

**Comment by caarlos0** [comment]
no worried - i disappeared for a bit as well (newborn), so no worries :D 

thanks for the review - and best of luck on the new job 🙏
