### ISSUE TITLE
Unable to Ignore Non-GoModule Vendor Directory

### ISSUE THREAD

**Issue by forestsword** [goreleaser/goreleaser#2975]
### What happened?

I use jsonnet and jsonnet-bundler to bring in dependencies for deployment. This populates the `vendor` directory. There's no way currently to tell goreleaser to ignore it with `-mod=mod` as I can using the go binary directly. I can normally ignore it in builds like

```
builds:
- main: ./cmd/binary
  binary: binary
  goos:
    - linux
  flags:
    - -mod=mod
```

But this does not affect listing of the module here: https://github.com/goreleaser/goreleaser/blob/42258cf4733a9f42b17ad1b47fb7e6e2a10369c0/internal/pipe/gomod/gomod.go#L32

And it fails like

```
   • checking distribution directory
      • --rm-dist is set, cleaning it up
   • loading go mod information
   ⨯ release failed after 0.08s error=failed to get module path: exit status 1: go: inconsistent vendoring in /home/user/git/project:
        github.com/alecthomas/kong@v0.4.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/gocql/gocql@v0.0.0-20220224095938-0eacd3183625: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
```

I would have expected a way to add this in the gomod section: https://goreleaser.com/customization/gomod/

### How can we reproduce this?

Make an empty `vendor` directory in the root of the repository and run goreleaser.

### goreleaser version

```bash
goreleaser version 1.6.3
commit: 42258cf4733a9f42b17ad1b47fb7e6e2a10369c0
built at: 2022-03-12T01:23:19Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.6.3, checksum: h1:LqHfNmaqGoC7OuabK/UeINWyuQaqm/jdotsALhk0zsE=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

As a work around I clean that directory with a before hook, inconvenient but I can live with it.

**Comment by caarlos0** [comment]
good catch, thanks!

**Comment by hktalent** [comment]
@caarlos0 
Can it be forward compatible?
Thank you so much
I also encounter a lot of
https://github.com/GhostTroops/ksubdomain/actions/runs/7074635721/job/19255897806
"
is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
"
But it was correct before that
  go-version: 1.21.4
goreleaser/goreleaser-action@v5

best wishes
