### ISSUE TITLE
Proposal: Removal of buildpack option

### ISSUE THREAD

**Issue by dirien** [goreleaser/goreleaser#2976]
### Is your feature request related to a problem? Please describe.

I wanted to preflight with the community and @caarlos0 the question: Should we remove the support for buildpacks for the container build step?

I tried it, and I dont see any values in this feature. Why?

- The binary gets rebuild again during the buildpack build.
- No ARM support.

What are your thoughts? Should we deprecate the buildpack option?

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
yeah, I think so... this has the same problem as the current proposal for adding ko... rebuilding the binaries et al, I'm not a fan...

IMHO, lets deprecate it, which has a 6-month period, and then remove it

**Comment by dirien** [comment]
I would create the PR for it, what is your process for deprecation?

**Comment by caarlos0** [comment]
nice!

- add it to the list here -> https://github.com/goreleaser/goreleaser/blob/main/www/docs/deprecations.md
- use the `deprecate` api to notice the deprecation on the logs if its being used -> https://pkg.go.dev/github.com/goreleaser/goreleaser@v1.6.3/internal/deprecate#Notice

That's pretty much it :)
