### ISSUE TITLE
slack notifications options

### ISSUE THREAD

**Issue by fredbi** [goreleaser/goreleaser#2986]
### Is your feature request related to a problem? Please describe.

I'd like to announce releases to our slack channels with a cleaner message than just providing a few links.

Unfortunately, only plain text is currently sent by the goreleaser pipeline. Expanding the markdown release notes in the message is not something that renders nicely.

### Describe the solution you'd like

The slack Webhook message supports more fields to instruct slack about the posted content.

The webhook post message allows for more options (https://github.com/slack-go/slack/blob/v0.10.2/webhooks.go#L8) and in particular, we could use text blocks marked as "markdown" to post formatted text.

Ideally, the goreleaser Config for Slack pipeline could just expose the Blocks and Attachment fields, possibly as untyped structures (no need to expose the full details of the slack API) to provide the user some leeway when using slack.

I can easily do a PR for that feature, I we agree on the principle.

### Describe alternatives you've considered

* Just made a link to the notes, but this kind of defeated the purpose of the announcement (with _summarized_ release notes)
* Tried to implement some filter to preprocess markdown and render as "slack-like" plain-text 
* Currently just back-quoting the whole release notes text, so at least the notes are not garbled. 

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Please let me know if you want me to implement this.

**Comment by caarlos0** [comment]
Sounds good @fredbi , go for it! :)

**Comment by fredbi** [comment]
yay! @caarlos0  I'll do that overnight. Hopefully I don't meet too many tweaks with the slack API
