### ISSUE TITLE
Changelog issue, same commits shown.

### ISSUE THREAD

**Issue by peeyushsrj** [goreleaser/goreleaser#300]
I recently released two version. I found that changelog is showing commits from the beginning in succesive release too. 

Screenshots are attached.
![v1 0](https://user-images.githubusercontent.com/5060113/28191418-d3c0d0ba-684d-11e7-8457-13e63028ab40.png)
![v1 1](https://user-images.githubusercontent.com/5060113/28191419-d3c5db1e-684d-11e7-9980-c14a1346cde7.png)

**Comment by caarlos0** [comment]
Could not reproduce.

Maybe you release the first tag via github and the second in your machine, and, for some reason, your local git repo didn't had the reference to v0.1.0?

Can you please paste the output of `git tag` and `git --version`?

**Comment by peeyushsrj** [comment]
Both tags in local machine. 
```
v0.1.0
v0.1.1
```
```
git version 2.7.4
```

But I did have a tag before this. which I deleted on git repo and then local machine.

**Comment by peeyushsrj** [comment]
@caarlos0 Is it fixed?

**Comment by caarlos0** [comment]
@peeyushsrj couldn't reproduce... there are tests guaranteeing this works as expected... I really don't know where to look, everything seems right :/

can you try to cut another release and see if it works?

**Comment by caarlos0** [comment]
The only possible thing I could think is that your git version is a little old...

**Comment by peeyushsrj** [comment]
Fine. I'll do another release, the way I did earlier to check it. Anyway it's lovely tool.

**Comment by caarlos0** [comment]
@peeyushsrj any news?

**Comment by peeyushsrj** [comment]
The setup was messy, could not reproduce! I hope to do that mistake some time in nearby future. For time being issue can be closed. @caarlos0

**Comment by caarlos0** [comment]
@peeyushsrj ok, thanks....

I think it may be an old version of git or something... I was re-implementing the git part with a git library written in Go but it doesn't have all the features we need yet... 

If you see the problem again, please re-open :)

Thanks again!
