### ISSUE TITLE
brew tap uses incorrect sha256 sum

### ISSUE THREAD

**Issue by mitchellh** [goreleaser/goreleaser#3010]
### What happened?

👋 

I am using the `.goreleaser.yml` shown below to upload Gon, and the checksum in the brew file doesn't match. I believe this is because Gon itself is modifying the archive after goreleaser caches the checksum. I'm unsure how to resolve this except by manually changing the pushed formula at the moment.

### How can we reproduce this?

https://github.com/mitchellh/gon

`make release` (obviously add `--snapshot` to the `goreleaser` command)

### goreleaser version

```bash
goreleaser version 1.7.0
commit: 7671dab291483b2733e871abff379d07e74dfc6c
built at: 2022-03-21T00:00:37Z
built by: goreleaser
goos: darwin
goarch: arm64
module version: v1.7.0, checksum: h1:qk+7boeU300OaogAVkjjl+2OLoMfr2e2uZM0cPcacDw=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
will investigate, thanks for the report. 🙏

**Comment by mitchellh** [comment]
Note maybe a separate issue but maybe to pre-empty the possible question: "why don't you use hooks on the build?" The reason is because then the `zip/dmg` artifacts aren't visible to the taps section and the homebrew formula is empty. Maybe thats a PEBCAK problem but it wasn't clear what I should do there either, so I went back to using this approach.

**Comment by caarlos0** [comment]
gotcha, I might have a workaround, we had these issues with other signers too, so there is a way to refresh the checksums, although its hacky: add another sign config for the checksums only (it can do nothing with the checksums fwiw).

in any case, this should be more clear. Will improve it :)
