### ISSUE TITLE
With go 1.18 build is considerably slower with github action

### ISSUE THREAD

**Issue by Nexucis** [goreleaser/goreleaser#3011]
### What happened?

I'm using the github action `goreleaser` to build my project and since I upgraded Go to v1.18 the build is considerably slower and can fail periodically: from ~2min to more than 10min

For example: https://github.com/perses/perses/runs/5741216067?check_suite_focus=true

I tried to just install goreleaser and then use it manually. I tried to download manually the dependencies before. And it has no effect on the build time.

I fallback in a PR to go v1.17 and the build instantly work with the buildtime expected: https://github.com/perses/perses/runs/5751290113?check_suite_focus=true

But when I'm using `goreleaser` on a laptop with Go v1.18 it has the same build time than before (i.e ~2min)

### With go 1.18: 

* Github action runtime:
https://github.com/perses/perses/runs/5741216067?check_suite_focus=true

* Github action config: https://github.com/perses/perses/blob/fe6101c1a15594548b333e30a7c5503852326edb/.github/workflows/build_and_release.yaml#L87-L117

* goreleaser config

https://github.com/perses/perses/blob/fe6101c1a15594548b333e30a7c5503852326edb/.goreleaser.yml

### With go 1.17

* Github action runtime:
https://github.com/perses/perses/runs/5751290113?check_suite_focus=true

Github action and goreleaser config are the same, I just change the Go version.

### goreleaser version

```bash
On my laptop: 


goreleaser --version
goreleaser version 1.7.0
commit: 7671dab291483b2733e871abff379d07e74dfc6c
built at: 2022-03-21T00:00:37Z
built by: goreleaser
goos: darwin
goarch: amd64
module version: v1.7.0, checksum: h1:qk+7boeU300OaogAVkjjl+2OLoMfr2e2uZM0cPcacDw=
```

On github action, it's also the v1.7.0 used
```


### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_

**Comment by caarlos0** [comment]
goreleaser simply calls go build, same params for whichever go version you have.

goreleaser-action simply downloads and run goreleaser.

nothing we can do, maybe its some of your deps, maybe its something on github actions, maybe its go 1.18 itself... in any case, I don't see any actionable from goreleaser itself.

**Comment by Nexucis** [comment]
Just in case, after furthermore investigations, I found that when I'm setting the option `--parallelism` to 1, it's working nicely.
Looks like building multiple architecture in parallel in Go 1.18 doesn't work

**Comment by Nexucis** [comment]
with github action, because locally it's working ....
