### ISSUE TITLE
Add support for embeddding application icons

### ISSUE THREAD

**Issue by devilHorns13** [goreleaser/goreleaser#3020]
### Is your feature request related to a problem? Please describe.

There's no native support in goreleaser to set an application icon

### Describe the solution you'd like

That would be nice if there's native support to set an application icon in a cross-platform fashion.

### Describe alternatives you've considered

[rsrc](https://github.com/akavel/rsrc) & [go-winres](https://github.com/tc-hib/go-winres), both of which are written in Go, are two examples of how to implement this.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
you are probably already able to do that using the options available (build hooks, extra files in archives et al)


unlikely that this gets added in a native fashion...

**Comment by caarlos0** [comment]
closing since no response...
