### ISSUE TITLE
Homebrew: Support for test?

### ISSUE THREAD

**Issue by tisba** [goreleaser/goreleaser#303]
First: Thanks for this great tool! Especially the generation of homebrew formulas is awesome!

I was wondering though if there is currently a way to modify the formular output. We used to have a `test do … end` block (see e.g. https://github.com/stormforger/homebrew-forge/commit/d7edc7bc81678f5735a0984588511c709023ccbd):

```ruby
test do
  system "#{bin}/forge version"
end
```

This enables us to use travis and run `brew test $FORMULAR` (see https://github.com/stormforger/homebrew-forge/blob/master/.travis.yml).

**Comment by caarlos0** [comment]
There is no way of doing it right now, but it is totally doable!

You can open a PR if you want :) If not, I'll do it when I have some free time.

**Comment by tisba** [comment]
I'm quite new to golang, but I'm happy to give it a shot :)

**Comment by tisba** [comment]
Awesome! Thanks! <3
