### ISSUE TITLE
Enable Releasing Compiled Test Binaries

### ISSUE THREAD

**Issue by kalverra** [goreleaser/goreleaser#3037]
### Is your feature request related to a problem? Please describe.

I'd like to release some binaries of my compiled tests, usually achieved with the following command.

`go test -c ./path/to/tests -o binary.name`

I'd love to use goreleaser for this, but it seems to lack this option. I tried using

```yaml
gobinary: "go test -c"
```

with no luck.

### Describe the solution you'd like

Enable an option like 

```yaml
# Have this build compile go tests using `go test -c` instead of using the typical `go build`
# true (default), or false
compile_tests: true
```

### Describe alternatives you've considered

Right now it looks like I'm going to be explicitly compiling these test binaries and using something like [this tool](https://github.com/marketplace/actions/gh-release) to release them.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I think it should work if you add `-c` to the `flags` section in the builds config, can you try that?

**Comment by kalverra** [comment]
@caarlos0 Looks like the same issue

```yaml
builds:
  - id: "smoke-tests"
    binary: smoke.test
    dir: ./suite/smoke
    flags: 
      - -c
```

```
release failed after 0.74s error=build for smoke.test does not contain a main function
```

**Comment by kalverra** [comment]
Also, this is a more niche case, but we tend to use [Ginkgo](https://onsi.github.io/ginkgo/#top) to help write and compile our tests. Ginkgo compiles tests using `ginkgo build ./path/to/tests` so I tried utilizing that as the `gobinary` value. got the same error.

```
release failed after 0.77s error=build for smoke.test does not contain a main function
```

**Comment by caarlos0** [comment]
> release failed after 0.74s error=build for smoke.test does not contain a main function

ahh, I forgot about this 

curious though: what's the use case of releasing test binaries?

**Comment by kalverra** [comment]
We're working on a [testing framework](https://github.com/smartcontractkit/integrations-framework) that includes its own suite of default tests, ones that we'd like other projects to be able to quickly download and utilize without having to clone our  repo.

**Comment by caarlos0** [comment]
Made a quick prototype here, what do you think about options like this?

<img width="420" alt="CleanShot 2022-04-24 at 22 00 14@2x" src="https://user-images.githubusercontent.com/245435/165004855-42934c46-ce52-4e27-a3d3-7581058b74e9.png">
