### ISSUE TITLE
Delay creation of remote tag

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#3044]
### Is your feature request related to a problem? Please describe.

In Hugo, there have been situations where the build fails for some reason and I need to make some adjustments to a script or similar and then try again.

What I do now is:

* Push a release tag to GitHub.
* Run Goreleaser.
* If it fails and I need to change something, I delete the remote tag and try again.

I know I should probably increment a version number, but that is just too much work. I don't mind doing the above, but with the new `gosumdb` validation in place and people running `go install github.com/gohugoio/hugo@v0.97.0` to install Hugo, we now end up with `checksum mismatch` errors that seem to be impossible to get out of.

https://github.com/gohugoio/hugo/issues/9785

### Describe the solution you'd like

I assume that the current workflow 

1. does not require the remote tag to exist when building the binaries/archives
2. does require the remote tag to exist when pushing the release to GitHub

The GitHub release API does allow a non-existing tag to be provided if you also provide the commit hash to be used for the tag (via `target_commitish`).

<img width="514" alt="image" src="https://user-images.githubusercontent.com/394382/163558300-04422962-4bbf-48a7-bcb6-05afe9bf4c54.png">

I'm not sure how feasible the above would be in Goreleaser, but it would be nice to delay the creation of the release tag as long as possible.

### Describe alternatives you've considered

I have looked at the Goreleaser documentation for a way to split the release build in 2: 1) Build archives and 2) Push tag to GitHub 3) Release to Github, but that does not seem to be possible (there is a `--skip-publish` flag, but not a `--just-publish` flag).

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bep** [comment]
OK, looks like #643 covers this, will test. Sorry for the noise.

**Comment by bep** [comment]
OK, that was reverted in #656

**Comment by caarlos0** [comment]
hmm, I would have to look into this, also have no idea if it would work and what would break, I'll ping here once I looked into it :)

**Comment by caarlos0** [comment]
hey!

I just looked into this, it works. Will push again the target_commitish thing.

Thanks!
