### ISSUE TITLE
Wrong paragraph breaks in man page

### ISSUE THREAD

**Issue by clausecker** [goreleaser/goreleaser#3048]
### What happened?

The goreleaser man page has a bunch of errorneous paragraph breaks like this:

```
DESCRIPTION
       GoReleaser is a release automation tool for Go projects.

       Its goal is to simplify the build, release and publish steps while
       providing

       variant customization options for all steps.

       GoReleaser is built for CI tools, you only need to download and execute
       it

       in your build script. Of course, you can also install it locally if you
       wish.

       You can also customize your entire release process through a

       single .goreleaser.yaml file.
```

This is because the [long description](https://github.com/goreleaser/goreleaser/blob/a5d3e7bf4b061d2ea58a4e8a6b3f242844a747fd/cmd/root.go#L57) has hard line breaks but the package you use to generate a man page from that takes any line break to mean a paragraph break.  Please fix the formatting of the man page so it is pleasant to read.

### How can we reproduce this?

Generate a man page with

    goreleaser man >goreleaser.1

and view it with

    man -l goreleaser.1 # linux
    mandoc -a goreleaser.1 # FreeBSD

### goreleaser version

```bash
1.7.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
good catch, thanks!
