### ISSUE TITLE
cannot fetch goreleaser on mac with intel

### ISSUE THREAD

**Issue by kamilsk** [goreleaser/goreleaser#3049]
### What happened?

Cannot update goreleaser on mac with intel (x86 arch) by homebrew.

This is because here it's disappeared: https://github.com/goreleaser/homebrew-tap/commit/f1b67b2c9717daa0bf4dcfca1e0ded747ee1a835

Since 1.8.0 has been released. But as I see goreleaser configuration it's still supported https://github.com/goreleaser/goreleaser/blob/3663ec1b13a6b50e225b95d8ce0db1f63c61c9ab/.goreleaser.yaml#L24

I see nothing in the release note https://github.com/goreleaser/goreleaser/releases/tag/v1.8.0 and also I see binary for x86. So, maybe it happened by mistake?

### How can we reproduce this?

Run `brew install goreleaser/tap/goreleaser` on mac with x86 arch.

### goreleaser version

```bash
1.8.0+
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

```
$ brew upgrade goreleaser/tap/goreleaser
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:273:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:208:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:181:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:181:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:342:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:420:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:633:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:629:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:629:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:308:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:101:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by caarlos0** [comment]
Yep, seems like a bug. Will check asap

**Comment by kamilsk** [comment]
I added example of output as additional context, jfyi

**Comment by kamilsk** [comment]
thanks, @caarlos0 !
