### ISSUE TITLE
release.disabled is not working as it promised

### ISSUE THREAD

**Issue by erkanzileli** [goreleaser/goreleaser#3051]
### What happened?

I wanted to disable publishing binaries to releases. I just only want release notes. I set `release.disabled=true` according to documentation [here](https://goreleaser.com/customization/release/#gitlab). It says

> You can disable this pipe in order to not upload any artifacts.

But it didn't work as expected and I saw the related code [here](https://github.com/goreleaser/goreleaser/blob/main/internal/pipe/release/release.go#L26). Clearly, if you set `release.disabled=true` you can't get any release. 

### How can we reproduce this?

```yaml
release:
    disable: true
```

### goreleaser version

```bash
v1.7.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

CC: @yilmazo

**Comment by caarlos0** [comment]
sorry, I don't quite understand the issue...

What happened, exactly?

**Comment by erkanzileli** [comment]
Sorry for the unclear explanation. We're using the goreleaser on a self-hosted GitLab and one day an error occurred that says the release artifacts(our binaries) were too large. Apparently, there is an artifact limit on the GitLab server but we realized we don't need to publish an artifact to the releases because we already build Container Images but we still need to generate the release and its notes. So we tried to `release.disabled` option according to its documentation which says it stops publishing artifacts but it didn't work as we expected. After using this option, event the release itself is didn't created.

I hope it's clear now. Please ask if you've more questions.

**Comment by caarlos0** [comment]
oh, that's likely a docs bug, it was always intended to skip the whole scm release
