### ISSUE TITLE
scoop publishing stopped working when goarm64 support was added

### ISSUE THREAD

**Issue by tashian** [goreleaser/goreleaser#3055]
### What happened?

We went to deploy a new release of [`step-ca`](https://github.com/smallstep/certificates/) today, and [the Scoop publishing step failed](https://github.com/smallstep/certificates/runs/6084391223?check_suite_focus=true) with the error `scoop requires a windows build and archive`. We have windows builds (386 and 

Our `.goreleaser.yml` hasn't changed since our last release two months ago (which ran GoReleaser v1.5.0), so this feels like a new/breaking issue with GoReleaser.

### How can we reproduce this?

[You can see our `.goreleaser.yml` here](https://github.com/smallstep/certificates/blob/master/.goreleaser.yml)

### goreleaser version

We're using `goreleaser/goreleaser-action@5a54d7e660bda43b405e8463261b3d25631ffe86` with GoReleaser v1.8.2.

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hmmm... since you're specifying the targets directly, no goamd64 is being set... so you might need to add a `_v1` suffix to your amd64 targets.

will also try to add a fix for this, not sure how yet

**Comment by comp500** [comment]
This change also seems to have broken [my Github Actions build](https://github.com/packwiz/packwiz/commit/f008ecec0fb88a952d1a7c568edb598f731101fc) which relies on the output paths (which are different now that they contain a `_v1`). Fairly easy to fix, but it would have been nice to have this functionality be opt-in (particularly as the suggested configuration of the Github Action for goreleaser uses the latest version) or at least mentioned in the changelog.

**Comment by caarlos0** [comment]
> This change also seems to have broken [my Github Actions build](https://github.com/packwiz/packwiz/commit/f008ecec0fb88a952d1a7c568edb598f731101fc) which relies on the output paths (which are different now that they contain a `_v1`). Fairly easy to fix, but it would have been nice to have this functionality be opt-in (particularly as the suggested configuration of the Github Action for goreleaser uses the latest version) or at least mentioned in the changelog.

those paths were never guaranteed not to change. That said, there's also a `dist/artifacts.json` you can parse to get paths and etc.
