### ISSUE TITLE
`goreleaser check` does not report usage of deprecated config options

### ISSUE THREAD

**Issue by Dean-Coakley** [goreleaser/goreleaser#3067]
### What happened?

I ran `goreleaser check` as noted on: https://goreleaser.com/deprecations/

I expected it to report line numbers of my usage of `empty_folders` as I was seeing from my build commands:
```
      • DEPRECATED: 'empty_folders' is deprecated and will be removed in a future version, create content with type 'dir' and directory name as 'dst' instead
```

Actual:
```
$ goreleaser check -f .goreleaser.yml

   • loading config file       file=.goreleaser.yml
   • checking config:
   • config is valid
```

### How can we reproduce this?

Add a config with:
```
nfpms:
- empty_folders:
  - /foo/bar
```

Run `goreleaser check`

### goreleaser version

```bash
goreleaser --version
goreleaser version 1.8.3
commit: 63436392db6ac0557513535fc3ee4223a44810ed
built by: homebrew
goos: darwin
goarch: amd64

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Tried `goreleaser check --debug` too, nothing interesting there.

**Comment by Dean-Coakley** [comment]
Happy to help with a bugfix or docs update if appropriate. :)

**Comment by caarlos0** [comment]
I think that warning comes from nfpm, likely something is not being properly handled in this integration, good catch, thanks!

**Comment by caarlos0** [comment]
things we'll need to do:
- refactor nfpm.validate to be pure (no side effects)
- refactor nfpm.validate to also validate packager specific configs (call packager.validate) 
- set the deprecation noticer in a sync.once, probably

**Comment by caarlos0** [comment]
oh, its worse actually... we only create a `nfpm.Info` later on, and can't really do it cleanly earlier... it might be easier to just re-do the validations again on goreleaser...
