### ISSUE TITLE
Command line flag to vary location of GoReleaser config

### ISSUE THREAD

**Issue by myitcv** [goreleaser/goreleaser#3125]
### Is your feature request related to a problem? Please describe.

In conversations with @caarlos0, we have talked about experimenting with CUE as a source of truth for GoReleaser configuration. Indeed in the context of https://github.com/goreleaser/goreleaser/discussions/3114, we are specifically looking at solving this in CUE initially, to explore the design space.

At the moment, it's not possible to tell GoReleaser where to find its configuration: it appears to be hard-coded to look for `.goreleaser.yml`. 

With CUE as the source of truth, however, this means exporting from CUE to Yaml to a file on disk, a file which only needs to exist temporarily (and is otherwise redundant).

### Describe the solution you'd like

A top-level flag (like `-h`, or `--debug`), say `--config-file` (please 🚲-shed a better name!), that allows us to configure where GoReleaser reads its config from. 

For example:

```
// read GoReleaser config from /tmp/blah
goreleaser --config-file /tmp/blah --snapshot --rm-dist

// read GoReleaser config from stdin
goreleaser --config-file - --snapshot --rm-dist
```

This would then allow us to avoid writing to a `.goreleaser.yml` file (which theoretically has race-conditions associated with it, as well as tidy-up problems) by piping the Yaml configuration directly to `stdin`. 

(We plan to write a `cue cmd` tooling layer task that wraps the call to GoReleaser so we can easily set `stdin`).

### Describe alternatives you've considered

The status quo: writing a temporary `.goreleaser.yml` file to disk, and then handling errors around tidy up.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hmm, maybe the help does not show because its a hacky in the root command, but it should be possible to pass a custom config - check out `goreleaser release --help` 

https://goreleaser.com/cmd/goreleaser_release/

That said, I think currently it does not accept reading from STDIN, so that's something to look into.

**Comment by myitcv** [comment]
> check out `goreleaser release --help`

Ah thanks. I indeed missed that, thanks for pointing it out. That flag should presumably be documented as part of `goreleaser --help`, alongside `--debug`?

> That said, I think currently it does not accept reading from STDIN, so that's something to look into.

Great, thanks

**Comment by caarlos0** [comment]
> Ah thanks. I indeed missed that, thanks for pointing it out. That flag should presumably be documented as part of `goreleaser --help`, alongside `--debug`?

not really, the root command will just default to `goreleaser release`, which is the one you want.

should probably make that more explicit in the help though.
