### ISSUE TITLE
Snapcraft: Failed to publish artifacts DEPRECATED: Use 'push' instead of 'upload'

### ISSUE THREAD

**Issue by atomicptr** [goreleaser/goreleaser#3134]
### What happened?

Hello,

trying to release something using goreleaser, I encounter this error while building the snap: 

```
         • pushing snap              args=[snapcraft upload --release=edge,beta,candidate,stable dist/crab_1.3.1_linux_amd64.snap] snap=crab_1.3.1_linux_amd64.snap
   ⨯ release failed after 59.17s error=snapcraft packages: failed to publish artifacts: failed to push dist/crab_1.3.1_linux_amd64.snap package: exit status 2: DEPRECATED: Use 'push' instead of 'upload'
```

Link to the full build log: https://app.travis-ci.com/github/atomicptr/crab/builds/251201600#L714

At first I assumed for some reason the pipeline is pulling an older version of goreleaser due to this PR https://github.com/goreleaser/goreleaser/pull/2051 being merged ages ago, but this does [not seem to be the case](https://app.travis-ci.com/github/atomicptr/crab/builds/251201600#L548).

But after thinking about it, the deprecation notice says to use "push" instead of "upload" (and goreleaser does in fact use upload), does this mean they reversed that decision again? Although I can't find anything that says so.

### How can we reproduce this?

Repository: https://github.com/atomicptr/crab
CI Build: https://app.travis-ci.com/github/atomicptr/crab/builds/251201600

### goreleaser version

```bash
goreleaser version dev
goos: linux
goarch: amd64
module version: v1.9.1, checksum: h1:YtQg3W9MFYinzRPuWQ1uAV0ikLz49JKBgAnZWsXk7Q4=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
that's weird indeed... will investigate

**Comment by caarlos0** [comment]
<img width="776" alt="CleanShot 2022-05-27 at 09 37 24@2x" src="https://user-images.githubusercontent.com/245435/170700567-37d4120f-0add-462d-90ef-c41b3e8dca31.png">
<img width="733" alt="CleanShot 2022-05-27 at 09 37 47@2x" src="https://user-images.githubusercontent.com/245435/170700607-0e87f214-84fb-49a2-ac46-8611e3df2984.png">

both on snapcraft version 6.1, can you check which version you are using?

**Comment by caarlos0** [comment]
also https://snapcraft.io/docs/deprecation-notices does not state anything about that

**Comment by atomicptr** [comment]
I found the issue, as suspected the snapcraft package provided by Travis via apt is outdated, installing snapd and then snapcraft via snapd solved this. Presumably in the old package upload was deprecated? Thanks for the help either way!

**Comment by caarlos0** [comment]
> resumably in the old package upload was deprecated?

seems like, yes!

glad you figured it out! 🙏
