### ISSUE TITLE
Is there a way to configure fpm to add extra files to a .deb or .rpm package?

### ISSUE THREAD

**Issue by anthonyfok** [goreleaser/goreleaser#314]
A full-fledged Debian package often contains more files than the compiled Go binary and changelog file.  Using hugo as an example, the Debian-maintained package contains the following files:

```
/usr/bin/hugo
/usr/share/bash-completion/completions/hugo
/usr/share/doc/hugo/changelog.Debian.gz
/usr/share/doc/hugo/copyright
/usr/share/man/man1/hugo-benchmark.1.gz
/usr/share/man/man1/hugo-config.1.gz
/usr/share/man/man1/hugo-convert-toJSON.1.gz
/usr/share/man/man1/hugo-convert-toTOML.1.gz
/usr/share/man/man1/hugo-convert-toYAML.1.gz
/usr/share/man/man1/hugo-convert.1.gz
/usr/share/man/man1/hugo-env.1.gz
/usr/share/man/man1/hugo-gen-autocomplete.1.gz
/usr/share/man/man1/hugo-gen-doc.1.gz
/usr/share/man/man1/hugo-gen-man.1.gz
/usr/share/man/man1/hugo-gen.1.gz
/usr/share/man/man1/hugo-import-jekyll.1.gz
/usr/share/man/man1/hugo-import.1.gz
/usr/share/man/man1/hugo-list-drafts.1.gz
/usr/share/man/man1/hugo-list-expired.1.gz
/usr/share/man/man1/hugo-list-future.1.gz
/usr/share/man/man1/hugo-list.1.gz
/usr/share/man/man1/hugo-new-site.1.gz
/usr/share/man/man1/hugo-new-theme.1.gz
/usr/share/man/man1/hugo-new.1.gz
/usr/share/man/man1/hugo-server.1.gz
/usr/share/man/man1/hugo-undraft.1.gz
/usr/share/man/man1/hugo-version.1.gz
/usr/share/man/man1/hugo.1.gz
```

whereas the goreleaser-generated package contains:

```
/usr/local/bin/hugo
/usr/share/doc/hugo/changelog.gz
```

I took a quick look at the documentation and in the source code, but wasn't able to see any settings in goreleaser.yml that would allow me to add those extra files just to the .deb package but not to the tarball.

The man pages and the bash completion script are automatically generated by the `hugo gen` command and do not belong in the tarball, but they would be great to be included in a goreleaser-generated deb and rpm packages as they can be installed in the appropriate directories automatically.

Also, I think it would be great if the fpm section can has its own name_template field.  For example, while hugo_0.25.1_Linux-ARM64.tar.gz makes sense, hugo_0.25.1_Linux-ARM64.deb just looks strange when Debian simply uses hugo_0.25.1-1_arm64.deb.

Many thanks for your kind consideration!

**Comment by anthonyfok** [comment]
Yes, and perhaps the ability to run command snippets during the build, e.g. `hugo gen man` and things like `mkdir`, `mv`, etc.  (hope there is no security concern with running external commands).

Many thanks for your enthusiasm and encouragement!

**Comment by caarlos0** [comment]
@anthonyfok nice!

on the build phase you can already call external commands (see pre and post build hooks).

Maybe we can do the same on fpm...

**Comment by caarlos0** [comment]
I'll split this issue in 2, since there are 2 features here =D

**Comment by lrstanley** [comment]
Looks like most of this should be covered with https://github.com/goreleaser/goreleaser/pull/330 being merged. However, reviewing the FPM docs, it looks like there is another directive which we could take advantage of:

```
--config-files CONFIG_FILES   Mark a file in the package as being a config file. This uses 'conffiles' in debs and %config in rpm. If you have multiple files to mark as configuration files, specify this flag multiple times.  If argument is directory all files inside it will be recursively marked as config files.
```

`--config-files` specifically only supports deb/rpm, and it passes these directly to the build configs of these. The advantages of each being:

* `files` directive
   * Files like manpages or additional documentation
   * Files which are assets to your application
   * Additional binaries
   * On an upgrade of a package from a previous version, the files are replaced or added if they are missing (even if the user changed them/deleted them)
* `--config-files` directive
   * Default configuration files
   * Both deb and rpm have special treatment for these files in that:
      * On an update, generally the user is going to be asked if they want to override the config if the package has an updated version
      * On uninstall, unless the package-specific **purge** is requested, the configuration files stay.

Both of these have advantages, and as such, I believe both should be supported.

The other downside I can see with the current file configuration is if one wants to include files based on a specific architecture, but I'm thinking that at that point, one should manually be creating these themselves.

Are there thoughts to not only support files, but configuration files via the custom fpm directive? Seems like adding the configuration directives should be fairly trivial.

**Comment by caarlos0** [comment]
> Are there thoughts to not only support files, but configuration files via the custom fpm directive?

right now there is not.

I personally don't feel the need for it right now. If you do, I'll be happy to accepts PRs :D

**Comment by caarlos0** [comment]
hey @lrstanley, I tried the `--config-files` thing, but it seems buggy:

```patch

diff --git a/.goreleaser.yml b/.goreleaser.yml
index eee494f..5dd0ba3 100644
--- a/.goreleaser.yml
+++ b/.goreleaser.yml
@@ -4,13 +4,8 @@ builds:
       - CGO_ENABLED=0
     goos:
       - linux
-      - darwin
-      - windows
     goarch:
-      - 386
       - amd64
-      - arm
-      - arm64
 checksum:
   name_template: '{{ .ProjectName }}_checksums.txt'
 changelog:
@@ -50,9 +45,11 @@ fpm:
   maintainer: Carlos Alexandro Becker <root@carlosbecker.com>
   license: MIT
   vendor: GoReleaser
+  config_files:
+    - .goreleaser.yml
   formats:
     - deb
-    - rpm
+      #  - rpm
   dependencies:
     - git
 snapcraft:
@@ -63,4 +60,4 @@ snapcraft:
     wrapped in your favorite CI.
   grade: stable
   confinement: classic
-  
\ No newline at end of file
+
diff --git a/config/config.go b/config/config.go
index 1ba9422..0bdd4b8 100644
--- a/config/config.go
+++ b/config/config.go
@@ -143,6 +143,7 @@ type FPM struct {
 	License      string            `yaml:",omitempty"`
 	Bindir       string            `yaml:",omitempty"`
 	Files        map[string]string `yaml:",omitempty"`
+	ConfigFiles  []string          `yaml:"config_files,omitempty"`
 
 	// Capture all undefined fields and should be empty after loading
 	XXX map[string]interface{} `yaml:",inline"`
diff --git a/pipeline/fpm/fpm.go b/pipeline/fpm/fpm.go
index df0c3e4..41527d4 100644
--- a/pipeline/fpm/fpm.go
+++ b/pipeline/fpm/fpm.go
@@ -102,6 +102,14 @@ func create(ctx *context.Context, format, arch string, binaries []artifact.Artif
 	}
 	log.WithField("file", file).WithField("workdir", dir).Info("creating fpm archive")
 	var options = basicOptions(ctx, dir, format, arch, file)
+	for _, file := range ctx.Config.FPM.ConfigFiles {
+		log.WithField("file", file).Debug("added config file")
+		path, err := filepath.Abs(file)
+		if err != nil {
+			return err
+		}
+		options = append(options, "--config-files", path)
+	}
 
 	for _, binary := range binaries {
 		// This basically tells fpm to put the binary in the bindir, e.g. /usr/local/bin
```

running this:

```console
$ go run main.go --skip-validate --skip-publish --rm-dist
```

I always get this error:

```
{:timestamp=>"2017-12-29T22:50:36.821145-0200", :message=>"Invalid package configuration: Error trying to use '/Users/carlos/Code/Go/src/github.com/goreleaser/goreleaser/.goreleaser.yml' as a config file in the package. Does it exist?", :level=>:error, :file=>"fpm/command.rb", :line=>"502", :method=>"rescue in execute"}
```

the file exists though.

dunno what fpm is trying to do here...

**Comment by lrstanley** [comment]
I believe https://github.com/jordansissel/fpm/issues/1440 (recently merged PR: https://github.com/jordansissel/fpm/pull/1443) may be related. Looks like it's specifically related to config files and **deb** files. Can you confirm if you're running the latest fpm version, and/or if it works with just **rpm**? Not sure exactly how the fpm folks handle fpm releases, in regards to their packages within repos (if they push out updates immediately, or if they wait and bundle for a release). May need to wait until they release another version with the fix, for the issues to be resolved.

**Comment by caarlos0** [comment]
@lrstanley yeah, the last release is from august, I think we'll have to wait for the new release...

**Comment by lrstanley** [comment]
@caarlos0 Waa! Didn't know you started working on nfpm. THIS MAKES ME SO HAPPY. fpm is a huge pain to work with, and have installed on my system. I always wanted to work on an alternative, but always put it on the backburner because the lack of familiarity with how deb/rpm packaging works internally.

:+1:

**Comment by caarlos0** [comment]
> @caarlos0 Waa! Didn't know you started working on nfpm. THIS MAKES ME SO HAPPY. fpm is a huge pain to work with, and have installed on my system. I always wanted to work on an alternative, but always put it on the backburner because the lack of familiarity with how deb/rpm packaging works internally.

yeah, same thing for me... turns out it was not so hard after all.. besides rpm, of course, it still depends on rpmbuild unfortunately...
