### ISSUE TITLE
Binary built with GoReleaser doesn't include vcs info

### ISSUE THREAD

**Issue by lucacome** [goreleaser/goreleaser#3143]
### What happened?

Go 1.18 added version control information in the build ([docs](https://tip.golang.org/doc/go1.18#go-command:~:text=The%20go%20command,the%20same%20repository.)) for example:

```
...
build	vcs=git
build	vcs.revision=3f5bb49edfb41825ac4106854a95e64855190e55
build	vcs.time=2022-06-02T22:57:45Z
build	vcs.modified=true
```
This info is available at runtime (removing the need to inject the info at build time) but this is not available when building with GoReleaser.

### How can we reproduce this?

Build with `go build` in a folder with version control and you can see the info about version control in the binary with `go version -m <binary_name>`.

Build with `goreleaser build` and see that the info is not there

### goreleaser version

```bash
❯ goreleaser --version
goreleaser version 1.9.2
commit: b869ea44b7e211c59d856307a5d308b594030218
built at: 2022-05-27T16:26:29Z
built by: goreleaser
goos: darwin
goarch: amd64
module version: v1.9.2, checksum: h1:ehLhZQ8KgbOvr0jBxhyy2VbekehFD0DJmsvqUz1c8To=

https://goreleaser.com
```
```


### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_

**Comment by caarlos0** [comment]
are you enabling `gomod` in goreleaser config?

here's goreleaser itself:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/245435/171880772-502b3af0-2f37-489e-9203-3b32eaabbf3d.png">

https://goreleaser.com/customization/gomod/

**Comment by lucacome** [comment]
Turns out I was building the `.go` file directly instead of the package, I can now see the vcs info. 

Sorry for the noise, closing.
