### ISSUE TITLE
Skip `docker` step when creating a release

### ISSUE THREAD

**Issue by kylecarbs** [goreleaser/goreleaser#3144]
### Is your feature request related to a problem? Please describe.

I'm trying to use a single `.goreleaser.yaml` file for deploying our development deployment (via a snapshot) and doing public releases. Our `docker` step isn't required for development and takes a long time.

### Describe the solution you'd like

A flag added to skip creating and publishing Docker images. Maybe `--skip-docker`?

### Describe alternatives you've considered

Extending another `.goreleaser.yaml` would work, but I don't want to split our configuration unless absolutely necessary.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kylecarbs** [comment]
We want to build the `nfpm` packages too.

**Comment by kylecarbs** [comment]
I wonder if specifying filters by the top-level key (or whatever the internal implementation is) would suffice. eg. `goreleaser release --filter docker,nfpm`

**Comment by caarlos0** [comment]
> I wonder if specifying filters by the top-level key (or whatever the internal implementation is) would suffice. eg. `goreleaser release --filter docker,nfpm`

that unfortunately is a lot more complex than it looks.

if you want to just build binaries, `docker build` might help.

for other scenarios, adding `--skip-docker` now as well.
