### ISSUE TITLE
`install.goreleaser.com` cannot be resolved

### ISSUE THREAD

**Issue by chenrui333** [goreleaser/goreleaser#3146]
### What happened?

Looks like `install.goreleaser.com` cannot be resolved

```sh
$ curl -I https://install.goreleaser.com
curl: (6) Could not resolve host: install.goreleaser.com
```

### How can we reproduce this?

```sh
$ curl -I https://install.goreleaser.com
curl: (6) Could not resolve host: install.goreleaser.com
```

### goreleaser version

```bash
N/A
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I used to use this domain for installing golangci-lint as below

```
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ./bin v1.39.0
```

**Comment by caarlos0** [comment]
https://goreleaser.com/deprecations/#godownloader

it was deprecated and shut down, please check the link above for instructions.

**Comment by chenrui333** [comment]
I see, thanks!
