### ISSUE TITLE
Do not create duplicate draft release in GitHub

### ISSUE THREAD

**Issue by qsliu2017** [goreleaser/goreleaser#3148]
### Is your feature request related to a problem? Please describe.

Our release workflow is like this:
1. Create a `vx.y.z` branch, then GitHub Actions create a draft release with the name `RELEASE vx.y.z`
2. In the next couple of day, we cherry-pick some bug-fix commit to the release branch as well as fill the content of the release note

The question is a new commit to the release branch will trigger goreleaser again, and create another draft release note (instead of appending to the existing one).

Seems like goreleaser only treat releases with the same tag as the same releases. While the draft release will be assigned a random tag like `untagged-1070a2429328d38d3638`.
 https://github.com/goreleaser/goreleaser/blob/f8e5bdac10a61271aee0ca58427fdb0432b3d10b/internal/client/github.go#L224-L230

### Describe the solution you'd like

Consider treating draft releases with the same name as the same release

### Describe alternatives you've considered

N/A

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qsliu2017** [comment]
@caarlos0 Could you explain why #3073 fail? thanks.

**Comment by caarlos0** [comment]
yes, if you run goreleaser multiple times, reusing the same release (i.e. the draft), it'll fail to upload the artifacts because they already exist.

so, in order to reuse, you'll probably need to delete the release artifacts first.
