### ISSUE TITLE
Add chocolatey support/push for windows binary package

### ISSUE THREAD

**Issue by rfay** [goreleaser/goreleaser#3154]
### Is your feature request related to a problem? Please describe.

I see that goreleaser has scoop support for windows packages, which I haven't used before, but I think chocolatey is more widely used.

Chocolatey is (probably?) the leading package manager for Windows. It's not terribly hard to implement in a release process, and it makes installing and updating as easy as homebrew.

### Describe the solution you'd like

It's not terribly hard to implement, see 
* https://github.com/drud/ddev/blob/37922e831e3d97e3c2760f57785a57b640e5a88e/Makefile#L218-L229 
* https://github.com/drud/ddev/blob/b5422ae17f6e578c6f55c71acc2601ae75d9e78a/.github/workflows/master-build.yml#L264-L269

### Describe alternatives you've considered

I guess I'll try scoop. I thought I was going to need a script to download from the releases page.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I'm integrating goreleaser for [DDEV](https://github.com/drud/ddev), so need to install goreleaser for the Windows build.

DDEV publishes releases to chocolatey among all the other places and people seem to like it. They've never asked for scoop, and choco seems to be the normal choice.

**Comment by caarlos0** [comment]
doesn't chocolatey require MSIs?

**Comment by rfay** [comment]
I guess that's probably right, not sure. We ship an installer, super easy to make with nsis.

**Comment by caarlos0** [comment]
see https://github.com/goreleaser/goreleaser/issues/1295

**Comment by caarlos0** [comment]
should be fixed by #3509

**Comment by rfay** [comment]
Yay! Thanks!
