### ISSUE TITLE
Failing Docker builds (exit status 1: error: dial unix /run/buildkit/buildkitd.sock: connect: no such file or directory)

### ISSUE THREAD

**Issue by calvinbui** [goreleaser/goreleaser#3156]
### What happened?

I've released a new version of my application today via GitHub Actions and have started receiving errors during the docker build.

I have not changed anything in my build since my last release on the 7th of January 2022. I have made a few changes since then but without any luck.

The error appears to occur when building arm64 or armv7, never amd64. 

```
   •docker images
      • building docker image    image=ghcr.io/calvinbui/homer-service-discovery:v1.5.0-arm32v7
      • building docker image    image=ghcr.io/calvinbui/homer-service-discovery:v1.5.0-arm64v8
      • building docker image    image=ghcr.io/calvinbui/homer-service-discovery:v1.5.0-amd64
   ⨯release failed after 70.08serror=docker build failed: failed to build ghcr.io/calvinbui/homer-service-discovery:v1.5.0-arm64v8: exit status 1: error: dial unix /run/buildkit/buildkitd.sock: connect: no such file or directory
error: listing workers for Build: failed to list workers: Unavailable: failed to receive server preface within timeout
Learn more at https://goreleaser.com/errors/docker-build
```

Or

```
   •docker images
      • building docker image    image=ghcr.io/calvinbui/homer-service-discovery:v1.5.0-arm32v7
      • building docker image    image=ghcr.io/calvinbui/homer-service-discovery:v1.5.0-amd64
      • building docker image    image=ghcr.io/calvinbui/homer-service-discovery:v1.5.0-arm64v8
   ⨯release failed after 73.20serror=docker build failed: failed to build ghcr.io/calvinbui/homer-service-discovery:v1.5.0-arm32v7: exit status 1: error: dial unix /run/buildkit/buildkitd.sock: connect: no such file or directory
error: listing workers for Build: failed to list workers: Unavailable: failed to receive server preface within timeout
Learn more at https://goreleaser.com/errors/docker-build

```

### How can we reproduce this?

config: https://github.com/calvinbui/homer-service-discovery/blob/master/.goreleaser.yml

github action: https://github.com/calvinbui/homer-service-discovery/blob/master/.github/workflows/release.yml

failing builds:
- https://github.com/calvinbui/homer-service-discovery/runs/6847921652?check_suite_focus=true
- https://github.com/calvinbui/homer-service-discovery/runs/6847866934?check_suite_focus=true

### goreleaser version

```bash
1.9.2
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
does not seem to be related to goreleaser.

check if docker is really working in your build environment.

**Comment by calvinbui** [comment]
you're right, the issue was with enabling experimental docker features

I removed: 

```
      - name: 🧯 Enable Docker experimental features
        run: |
          echo $'{\n  "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          mkdir -p ~/.docker
          echo $'{\n  "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
          sudo service docker restart
          docker version -f '{{.Client.Experimental}}'
          docker version -f '{{.Server.Experimental}}'
          docker buildx version
```
