### ISSUE TITLE
Output duration for each stage in build

### ISSUE THREAD

**Issue by jsirianni** [goreleaser/goreleaser#3172]
### Is your feature request related to a problem? Please describe.

No problem. 

### Describe the solution you'd like

Goreleaser builds can take a long time when running in CI. Builds, archive, nfpm, docker, etc all add up. It would be nice if each step in the build logged the amount of time it took. For example, my build just took 10 minutes but I am not sure which step consumed the most time. I can make an accurate guess but I do not know for sure.

The total duration is already logged:
```
release succeeded after 633.99s
```

### Describe alternatives you've considered

Manually testing by disabling everything except the stage I want to time.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

This would be a nice to have. Not a big deal.

**Comment by caarlos0** [comment]
this is a good idea indeed, thanks!
