### ISSUE TITLE
Add `publish` / `release` command to publish previously built artifacts

### ISSUE THREAD

**Issue by jsirianni** [goreleaser/goreleaser#3174]
### Is your feature request related to a problem? Please describe.

I would like to test artifacts before they are published without running goreleaser twice (once with --skip-publish and again without).

### Describe the solution you'd like

It would be nice to be able to build all release artifacts (binary, archive, packages, container images) and then publish them in two separate commands.

1. Run `goreleaser release` without actually publishing anything
2. Run some tests (using CI) to ensure nfpm packages and docker images are correct
3. Run `goreleaser publish` to publish the previously built artifacts from step 1 (binaries / archives, packages, docker images, release, etc)

Right now, I do the following.
1. Run `goreleaser release --skip-publish`
2. Test my packages and docker images
3. Run `goreleaser release`

The problem with this workflow is that we don't publish the artifacts that we tested. In theory, the built binaries, packages, and container images **should** be identical.. and maybe they are most of the time but it is best practice to publish what you tested. Additionally, the release takes twice as long because we are doubling our work.

### Describe alternatives you've considered

I could do:

- goreleaser release --skip-release
- run tests
- publish with custom scripts

The problem with the last step is I am sacrafising Goreleaser's release and release notes features, which are awesome. 

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I am following up on what this closed issue seemed to be getting at Following up on https://github.com/goreleaser/goreleaser/issues/1454

**Comment by caarlos0** [comment]
this is something that is planed for goreleaser-pro, but I don't have an estimate for it yet

**Comment by caarlos0** [comment]
in fact, gonna try to hurry that up for next release
