### ISSUE TITLE
Breaking change in name templating behavior

### ISSUE THREAD

**Issue by ahmetb** [goreleaser/goreleaser#3192]
### What happened?

Between goreleaser upgrades, binary/archive names generated from the template in `.goreleaser.yml` have changed.

This behavior seems to have changed between v1.7.0 and v1.8.0 (adjacent tags).

Example diff (left: v1.7.0, right: 1.8.0) – note the `_v1` suffix:

```
binary=dist/kubectx_darwin_amd64/kubectx		      |	binary=dist/kubectx_darwin_amd64_v1/kubectx
binary=dist/kubectx_darwin_arm64/kubectx			binary=dist/kubectx_darwin_arm64/kubectx
binary=dist/kubectx_linux_amd64/kubectx			      |	binary=dist/kubectx_linux_amd64_v1/kubectx
binary=dist/kubectx_linux_arm64/kubectx				binary=dist/kubectx_linux_arm64/kubectx
binary=dist/kubectx_linux_arm_6/kubectx				binary=dist/kubectx_linux_arm_6/kubectx
binary=dist/kubectx_linux_arm_7/kubectx				binary=dist/kubectx_linux_arm_7/kubectx
binary=dist/kubectx_linux_ppc64le/kubectx			binary=dist/kubectx_linux_ppc64le/kubectx
binary=dist/kubectx_linux_s390x/kubectx				binary=dist/kubectx_linux_s390x/kubectx
binary=dist/kubectx_windows_amd64/kubectx.exe		      |	binary=dist/kubectx_windows_amd64_v1/kubectx.exe
```

### How can we reproduce this?

1. `git clone https://github.com/ahmetb/kubectx`
2. `git checkout e5e7f533364c99e7585ce9bdea1835df6b829078` (today's HEAD)
3. `go install github.com/goreleaser/goreleaser@v1.7.0`
4. `goreleaser build --rm-dist --snapshot` 
5. `go install github.com/goreleaser/goreleaser@v1.8.0`
6. `goreleaser build --rm-dist --snapshot`  → note the _v1 suffix added

For posterity, the template that broke between version upgrades: https://github.com/ahmetb/kubectx/blob/master/.goreleaser.yml#L55-L61

The v1.8.0..v1.7.0 diff shows relevant changes https://github.com/goreleaser/goreleaser/compare/v1.8.0..v1.7.0

### goreleaser version

```bash
1.8.0 and up (1.9.2 today)
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

In this case, I am not sure if this _v1 suffix addition is by design or not, or whether it has something to do with my name template.

**Comment by caarlos0** [comment]
not a bug.

see: https://goreleaser.com/customization/build/#a-note-about-folder-names-inside-dist
