### ISSUE TITLE
Add Docker-Image-Building / Push to Dockerhub (like Homebrew)

### ISSUE THREAD

**Issue by andygrunwald** [goreleaser/goreleaser#320]
goreleaser has support for Homebrew (to push new releases, after a release is done).
Docker is also a wide used tool. Maybe this would also make sense to implement a docker build + tag + push to the configured registry?

One disadvantage would be to couple goreleaser to Docker.
Maybe a "Hook"-System would be good. With this people can develop use cases to push releases to different sources. Another use case for this would be a push to [Artifactory](https://www.jfrog.com/open-source/) or AWS S3

**Comment by caarlos0** [comment]
The docker thing should be reasonable easy, basically:

- create a dockerfile from scratch (or assume one is created)
- docker build
- docker push

I think i'll look into that today

**Comment by andygrunwald** [comment]
Yes, exactly.
The thing is more that this is kind of extendable. Because i think a lot of people have different use cases. Another use case could be to push to Artifactory or AWS S3.

I would be happy to review or test such a feature (more general or specific to docker).

**Comment by caarlos0** [comment]
hey @andygrunwald , can you take a look, plz? https://github.com/goreleaser/goreleaser/pull/355

**Comment by caarlos0** [comment]
TODO:

- [ ] templating in the image name (e.g.: user/image:{{.Tag }}_blah)
- [ ] deal with image names when its a snapshot
- [ ] a way to also tag and push latest (eg: latest: true in the config)
- [ ] docs (after the feature is complete)
- [ ] set the docker repository url

**Comment by caarlos0** [comment]
I think this is done!

**Comment by andygrunwald** [comment]
Thanks a lot @caarlos0!
