### ISSUE TITLE
Golang template actions aren't replaced in release.github.owner (environment variables)

### ISSUE THREAD

**Issue by rfay** [goreleaser/goreleaser#3202]
### What happened?

I need to replace `release.github.owner` with a template action (`{{ .Env.GITHUB_REPOSITORY_OWNER}}')`)

See https://github.com/rfay/junk/blob/cdc7e898179ae6857b3ae14e042fac22f613aa2b/.goreleaser.yml#L8

```yaml
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: junk
```

`export GITHUB_REPOSITORY_OWNER=rfay` and then

```
$ goreleaser release --rm-dist
   • by using this software you agree with its EULA, available at https://goreleaser.com/eula
   • running goreleaser v1.9.2-pro
  ...
   • publishing
      • scm releases
         • creating or updating release repo={{ .Env.GITHUB_REPOSITORY_OWNER }}/junk tag=v0.3
         • release updated           url=
   ⨯ release failed after 0.79s error=scm releases: failed to publish artifacts: POST https://api.github.com/repos/%7B%7B%20.Env.GITHUB_REPOSITORY_OWNER%20%7D%7D/junk/releases: 404 Not Found []
```

Note that it's trying to push without replacing the environment variable, so it fails.

This same replacement does in fact work in `brews` and `aurs`.

### How can we reproduce this?

* Check out https://github.com/rfay/junk
* Change the details as necessary to something you have access to
* `export GITHUB_REPOSITORY_OWNER=you
* `goreleaser release --rm-dist`

### goreleaser version

```bash
goreleaser version 1.9.2-pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rfay** [comment]
Is this just missing template replacement in https://github.com/goreleaser/goreleaser/blob/53b1ee07cfeb4895613ad37e39471a546ec71be9/internal/pipe/release/release.go#L92-L93 ?

**Comment by caarlos0** [comment]
> Is this just missing template replacement in
> 
> https://github.com/goreleaser/goreleaser/blob/53b1ee07cfeb4895613ad37e39471a546ec71be9/internal/pipe/release/release.go#L92-L93
> 
> ?

essentially yes

done in https://github.com/goreleaser/goreleaser/pull/3205

**Comment by rfay** [comment]
Nothing like that responsiveness! Thanks!
