### ISSUE TITLE
Allow parallelism with different entries in the `builds` block

### ISSUE THREAD

**Issue by juandiegopalomino** [goreleaser/goreleaser#3209]
### Is your feature request related to a problem? Please describe.

I'm trying to use goreleaser to build my project's binary releases for different oses+archs.  My project uses CGO but thanks to https://github.com/goreleaser/goreleaser-cross, I can build all of them in the same docker container run. The problem is that because I need to pass different envars (e.g. CC, CXX) for each os-arch I have a separate entry on the `builds` block of the goreleaser.yaml. Because of this goreleaser can not run my multiple os-arch builds in parallel like it could if I just had a single builds entry.

### Describe the solution you'd like

Make goreleaser use parrallelism with multiple `builds` entries.

### Describe alternatives you've considered

I can obviously run the build in multiple machines but that is complex for no good reason and makes local build testing suck.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
fixed in #3213
