### ISSUE TITLE
Support --single-target with release

### ISSUE THREAD

**Issue by jsirianni** [goreleaser/goreleaser#3219]
### Is your feature request related to a problem? Please describe.

I run `release` with --skip-publish` in CI so I can test packages and container images with Inspec. In this case, I really only need linux artifacts to be built. 

The `build` command has `--single-target` but it does not build packages or container images.

### Describe the solution you'd like

I would like a mechanism for building binaries, packages, and container images with `--single-target`.

### Describe alternatives you've considered

Generating a .goreleaser file that contains only `linux`, but this feels excessive.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

This ability will speed up CI significantly due to skipping windows and darwin (both of which build for multiple architectures).

**Comment by caarlos0** [comment]
that would be confusing... i.e. what should goreleaser do if someone runs `goreleaser release --single-target --rm-dist`? should it release or not?

seems like it would raise a lot of questions...

I'm not sure what is the best way to handle this tbh... maybe add it to `build`? maybe another subcommand called `package`? 

I'm open to suggestions...

**Comment by caarlos0** [comment]
is this a recurrent thing, something you do on every release? or is it just while working on the config?

if it is the later, I would recommend just commenting stuff out - its what I do ¯\_(ツ)_/¯

**Comment by jsirianni** [comment]
Unfortunately it is run on every pull request. No worries if it is not trivial.

**Comment by superbrothers** [comment]
> In my specific situation, I am running on Linux and want to test the Linux packages and Linux container images without waiting for darwin and windows builds.

I would like this feature as well for the purpose of testing package builds. Currently, it builds on all targets for testing and has slow CI issues.

**Comment by AaronFriel** [comment]
We've found that in order to accelerate our CI and to ensure hermetic testing of builds, we are using a feature produced by @t0yv0, one of our platform engineers, to filter the Goreleaser config to a single target before running release: https://github.com/t0yv0/goreleaser-filter 

In practice, this looks like this in a CI pipeline:

```sh
cat .goreleaser.yml \
            | go run github.com/t0yv0/goreleaser-filter@v0.3.0 -goos ${{ inputs.os }} -goarch ${{ inputs.arch }} \
            | goreleaser release -f - -p 5 --skip-validate --rm-dist --snapshot
```

**Comment by jsirianni** [comment]
This would be a nice feature for us. I am happy to test it out anytime.

**Comment by caarlos0** [comment]
added to goreleaser pro, will be in the next release. https://goreleaser.com/cmd/goreleaser_release/

**Comment by jsirianni** [comment]
@caarlos0 do you know the expected release date?

**Comment by caarlos0** [comment]
Probably early next week 🙏
