### ISSUE TITLE
Name template for snap packages

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#322]
Our "final" pipes all have the option of templating the final name, maybe we should add this feature to snaps as well.

**Comment by caarlos0** [comment]
@elopio is there any kind of name enforcement by snapcraft? tl;dr: is it ok to do this?

**Comment by elopio** [comment]
The file name is not important at all. The `name` field inside the .yaml needs to be `^[a-z0-9][a-z0-9+-]*$`.
