### ISSUE TITLE
github release fails on windows platform

### ISSUE THREAD

**Issue by mplx** [goreleaser/goreleaser#323]
When I'm running `goreleaser` on my ubuntu machine it works fine but on windows platform I've got trouble with file paths. It seems that on windows filenames are prefixed with the `dist\` directory and for upload its duplicated to `dist\dist\` resulting in `path not found` error.

windows7 amd64, go 1.8.3
```
...
   • CALCULATING CHECKSUMS
   • checksumming              file=dist\gosample_0.1.0_linux_amd64.tar.gz
   • checksumming              file=dist\gosample_0.1.0_windows_amd64.zip
   • checksumming              file=dist\gosample_0.1.0_linux_armv6.tar.gz
   • new artifact              artifact=dist\gosample_checksums.txt
   ⨯ release failed            error=open dist\dist\gosample_0.1.0_linux_amd64.tar.gz: The system cannot find the path specified.
```

linux (ubuntu 17.04 zesty), go 1.7.4
```
...
   • CALCULATING CHECKSUMS
   • checksumming              file=gosample_0.1.0_linux_amd64.tar.gz
   • checksumming              file=gosample_0.1.0_windows_amd64.zip
   • checksumming              file=gosample_0.1.0_linux_armv6.tar.gz
   • new artifact              artifact=gosample_checksums.txt
   • RELEASING TO GITHUB
   • creating or updating release repo=mplx/gosample tag=v0.1.0
   • release updated           url=https://github.com/mplx/gosample/releases/tag/v0.1.0
   • uploading to release      file=dist/gosample_checksums.txt name=gosample_checksums.txt
   • uploading to release      file=dist/gosample_0.1.0_linux_amd64.tar.gz name=gosample_0.1.0_linux_amd64.tar.gz
...
```

[Project](https://github.com/mplx/gosample) is identical on both machines, `goreleaser` is run from project home.

My mistake (... `help wanted`) or goreleaser bug?

**Comment by caarlos0** [comment]
seems like a bug... `dist` happens 2 times in windows: `dist\dist`

**Comment by caarlos0** [comment]
@mplx should be fixed on v0.28.1, can you test and let me know, please?

thanks for reporting the bug!

**Comment by mplx** [comment]
tested v0.28.2 - works very well!

thanks for fixing it so fast :)

**Comment by caarlos0** [comment]
thanks for reporting @mplx  :D
