### ISSUE TITLE
`env` override is not applied to build env variables

### ISSUE THREAD

**Issue by borgoat** [goreleaser/goreleaser#3230]
### What happened?

I am attempting to cross-compile a CGO library, and thus have to set the toolchain for selected targets (through `CC` env variable).

When setting env variables in a build override - despite the arch/os matching - the overridden value is not set when actually performing the build.

I can see the build matching the override rule:
```
• overridden build details for linuxarm64        details={[-s -w] [] [-buildmode=c-shared] [] [] [CC=zig cc -target aarch64-linux]}
```

However, when running 

```
$ goreleaser build --debug
```

In the list of environment variables I do not see the overridden value:

```
[...] CGO_ENABLED=1 CC=zig cc GOOS=linux GOARCH=arm64 GOARM= GOMIPS= GOMIPS64= GOAMD64=
```

`CC` in particular is supposed to appear twice, with the default value, plus the overridden one as `CC=zig cc -target aarch64-linux`.

### How can we reproduce this?

The `.goreleaser.yml` where I found the issue:

https://github.com/borgoat/farmfa/blob/ffi/.goreleaser.yml#L13-L42

### goreleaser version

```bash
goreleaser version dev
goos: linux
goarch: amd64
module version: v1.10.1, checksum: h1:NXCiqc4DJAG0y+iXDZKQew+0logeuZhYrCn4KZOrF0o=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

This is related to:

* #3201 
* #3119

**Comment by caarlos0** [comment]
Oh, you're also missing `goamd64: v1` here: https://github.com/borgoat/farmfa/blob/ffi/.goreleaser.yml#L27

**Comment by borgoat** [comment]
> Oh, you're also missing `goamd64: v1` here: https://github.com/borgoat/farmfa/blob/ffi/.goreleaser.yml#L27

Ah that damn GOAMD64 .. I'll never remember about it. I guess I didn't notice cause my build host is also linux/amd64 so the default toolchain won't complain

Thanks for the hint!

**Comment by arbourd** [comment]
This is awesome and works @caarlos0! I'll have a public example for this using GoReleaser cross soon 😁
