### ISSUE TITLE
brew: depends_on should be put before on_macos

### ISSUE THREAD

**Issue by Gearheads** [goreleaser/goreleaser#3236]
### What happened?

I expected the following command to complete successfully:
```
brew style fidelity/tap
```
However, it fails with the following error message:
```
Offenses:

/usr/local/Homebrew/Library/Taps/fidelity/homebrew-tap/Formula/kconnect.rb:48:3: C: [Correctable] depends_on (line 48) should be put before on_macos (line 10)
  depends_on "aws-iam-authenticator"
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense auto-correctable
```
I believe the issue is because within the `formulaTemplate` it lists the `Dependencies` after the `MacOS` and `Linux` packages:
https://github.com/goreleaser/goreleaser/blob/4c477b5cd186d11f096a23352b66045ea2bc7fd9/internal/pipe/brew/template.go#L145-L150

### How can we reproduce this?

This should be easily reproducible by having a formula template, *.rb, with the dependencies `depend_on` following the MacOS and or Linux packages, `on_macos` or `on_linux`.

An example formula can be found here: https://github.com/fidelity/homebrew-tap/blob/master/Formula/kconnect.rb

Error logs might be available here within the Github Action: https://github.com/fidelity/homebrew-tap/runs/7304043925?check_suite_focus=true

### goreleaser version

```bash
% goreleaser --version
goreleaser version 1.9.2
commit: b869ea44b7e211c59d856307a5d308b594030218
built at: 2022-05-27T16:26:29Z
built by: goreleaser
goos: darwin
goarch: amd64
module version: v1.9.2, checksum: h1:ehLhZQ8KgbOvr0jBxhyy2VbekehFD0DJmsvqUz1c8To=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Output for `goreleaser check`:
```
% goreleaser check
   • loading config file       file=.goreleaser.yml
   • checking config: 
   • config is valid 
```
I think this is an easy enough change, and I would be happy to help contribute. Please let me know if I can take on this issue, or if I am mistaken.

We can also see within the Homebrew Formula Cookbook, they appear to have the `Dependencies` defined early on in the formula:
https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#grab-the-url

**Comment by caarlos0** [comment]
check #3274
