### ISSUE TITLE
$ref '/$defs/FileInfo' can not be resolved

### ISSUE THREAD

**Issue by devmattrick** [goreleaser/goreleaser#3238]
### What happened?

In VS Code using the Red Hat YAML Extension, .goreleaser.yml fails to provide any intellisense due to the following error:

```
$ref '/$defs/FileInfo' in 'https://goreleaser.com/static/schema.json' can not be resolved. YAML(768)
```

I believe this is an issue with the schema provided by Goreleaser itself and not with the YAML extension, since I also noticed that this ref was missing.

### How can we reproduce this?

1. Download The Red Hat YAML Extension in VSCode
1. Create or open a project in VSCode
1. Create a .goreleaser.yml file in the project root
1. Notice the error and lack of auto complete and validation in the editor for that file

### goreleaser version

```bash
goreleaser version 1.10.2
commit: de3f381f55c88014b0d0eba91b28923eb1a992ac
built at: 2022-07-08T01:15:51Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.10.2, checksum: h1:MxgA0hDbDbTLep0u3pnu7Uh1Q1p0q60mpb88eApZbgw=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
weird, I got no complaints on neovim with yamlls... will investigate when I have some time

**Comment by quetdn** [comment]
Same issue. Same installation.


VS Code: v1.69.2
Red Hat YAML Extension. v1.9.1

goreleaser version 1.10.2
commit: de3f381f55c88014b0d0eba91b28923eb1a992ac
built at: 2022-07-08T01:15:51Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.10.2, checksum: h1:MxgA0hDbDbTLep0u3pnu7Uh1Q1p0q60mpb88eApZbgw=

**Comment by izcream** [comment]
its happen to me too I dev golang project on wsl2 with vscode it's will hightlight error same this issues


**goreleaser info**
goreleaser version dev
goos: linux
goarch: amd64
module version: v1.10.2, checksum: h1:MxgA0hDbDbTLep0u3pnu7Uh1Q1p0q60mpb88eApZbgw=

**windows info**
Edition	Windows 11 Home
Version	21H2
Installed on	‎2/‎22/‎2022
OS build	22000.778
Experience	Windows Feature Experience Pack 1000.22000.778.0

**wsl2 info**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

**vscode info**
Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by linzeyan** [comment]
Same issue.

goreleaser info
```
goreleaser version 1.10.2
commit: de3f381f55c88014b0d0eba91b28923eb1a992ac
built by: homebrew
goos: darwin
goarch: amd64
```

macOS info
```
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
```

VSCode info
```
1.69.2
3b889b090b5ad5793f524b5d1d39fda662b96a2a
x64
```

**Comment by guiaramos** [comment]
Same issue.Same issue.

goreleaser info
```
goreleaser version 1.10.3
commit: 315935aedc9908b078ae525b33ddb42b2fafcc54
built at: 2022-07-27T12:55:55Z
built by: goreleaser
goos: darwin
goarch: arm64
module version: v1.10.3, checksum: h1:mNSqSgqOwCyJCEmL35aDvGsZaucKF9yQyARxznqCtDM=
```
macOS info
```
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
```
VSCode info
```
Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:39:20.716Z (6 days ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.4.0
```
