### ISSUE TITLE
nfpm bindings should support RPM "Provides" & "Changelog"

### ISSUE THREAD

**Issue by benr** [goreleaser/goreleaser#3259]
### Is your feature request related to a problem? Please describe.

Red Hat certification has specific requirements on the contents of an RPM's "provides" and "changelog".  nfpm supports setting these for the RPM spec but the GoReleaser bindings (https://github.com/goreleaser/goreleaser/blob/fe7e2123bda5a605d34af695588fec57a535f0b3/internal/pipe/nfpm/nfpm.go) do not provide the ability to specify them.  

### Describe the solution you'd like

RPM overrides for both fields should be provided.

### Describe alternatives you've considered

The alternative is to modify the package after GoReleaser has created it, either by creating packages directly with nfpm or using rpmrebuild, both of which add an extra unnecessary step.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
ah, good catch

**Comment by caarlos0** [comment]
just added provides... unfortunately the changelog one will be a bit more complicated, as it currently uses chglog in nfpm.

This is a dependency I've been wanting to trim out for a while now, so I'll look into doing it.
