### ISSUE TITLE
Document snapcraft on readme

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#326]
it is not documented right now.

cc/ @elopio

**Comment by elopio** [comment]
I'm on it.

@caarlos0 we have a blog that's very popular. Would you like to write a post in there talking about goreleaser and how it can now generate snaps? It's this one: https://insights.ubuntu.com/

**Comment by caarlos0** [comment]
@elopio I'll love to do that :D

**Comment by elopio** [comment]
Nice! I think the easiest would be to write it in markdown. But you can send me an email to leo.arias@canonical.com, and I'll put you in contact with our marketing team, who can guide you further on publishing in insights.

**Comment by caarlos0** [comment]
@elopio OK, thanks 👍
