### ISSUE TITLE
HomeBrew Dependencies Version 

### ISSUE THREAD

**Issue by abebars** [goreleaser/goreleaser#3284]
### Is your feature request related to a problem? Please describe.

Currently, There is an option to mark a dependency as Optional but you can specify the version for the dependency. 
It would be great if we can also bake the version in the configuration because it's already supported in the [HomeBrew Formula ](https://docs.brew.sh/Formula-Cookbook#specifying-other-formulae-as-dependencies).

### Describe the solution you'd like

Update the config to have version string as an option

```
type HomebrewDependency struct {
	Name string `yaml:"name,omitempty"`
	Type string `yaml:"type,omitempty"`
        Version string `yaml:"version,omitempty"`
}
```
### Describe alternatives you've considered

There are no other options for that at the moment other than updating the Formula manually https://github.com/goreleaser/goreleaser/discussions/3283

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
how does the ruby syntax look like for when there is both a type and a version?

fwiw, if anyone wants to work on this:

- edit config.go
- edit brew/template.go
- add a test in brew_test.go
- `go test -v ./internal/pipe/brew/... -update`
- commit :)

**Comment by purush7** [comment]
@caarlos0  Can I work on this issue?

**Comment by caarlos0** [comment]
> @caarlos0 Can I work on this issue?

sure think! Thanks
