### ISSUE TITLE
Releases without archive/binary upload

### ISSUE THREAD

**Issue by 56KBs** [goreleaser/goreleaser#3289]
### Is your feature request related to a problem? Please describe.

My Go projects are only consumed via Docker images, so I have no need to attach the archives/binaries to the release.

We use GitLab internally and release frequently, these releases cumulatively use significant disk space for no gain.

### Describe the solution you'd like

I'd like to configure the release to upload no archives/binaries.

### Describe alternatives you've considered

Create an archive containing no data, so the release only uploads that empty archive, to reduce disk usage.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Discussion #3268

**Comment by caarlos0** [comment]
PR already opened in #3282

**Comment by 56KBs** [comment]
Wow thanks, I'd have happily contributed!
