### ISSUE TITLE
garble integration

### ISSUE THREAD

**Issue by batara666** [goreleaser/goreleaser#3305]
### Is your feature request related to a problem? Please describe.

I want the released binary compiled with [garble](https://github.com/burrowers/garble) 

### Describe the solution you'd like

Maybe some custom command replacing "go" from "go build" with "garble"

### Describe alternatives you've considered

not using goreleaser

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
You can already set `build.gobinary` to `garble`, if flags et al are the same as `go build`, it should work
