### ISSUE TITLE
goreleaser.com docs are not versioned, which may lead to confusion

### ISSUE THREAD

**Issue by tvsaru** [goreleaser/goreleaser#3317]
### What happened?

I have a usecase similar to https://github.com/goreleaser/goreleaser/discussions/3268 (found this discussion later). I was following the docs from https://goreleaser.com/customization/release/ 

```yaml
  # Set this to true if you want to disable just the artifact upload to the SCM.
  # If this is true, GoReleaser will still create the release with the changelog, but won't upload anything to it.
  #
  # Defaults to false.
  skip_upload: true
```

And was confused on why the latest release [v1.10.3]( https://github.com/goreleaser/goreleaser/releases/tag/v1.10.3) was giving an error:
```console
> goreleaser release --snapshot --rm-dist
  • starting release...
  • loading config file                              file=.goreleaser.yaml
  ⨯ release failed after 0s                  error=yaml: unmarshal errors:
  line 55: field skip_upload not found in type config.Release
  ```
  
I think the feature #3282 where the `skip_upload` was implemented is slated for v1.11.0. This confusion can be avoided by having a versioned doc. For example https://yamllint.readthedocs.io/en/stable/ vs https://yamllint.readthedocs.io/en/v1.10.0/

### How can we reproduce this?

1. `goreleaser init` to produce `goreleaser.yaml`
2. Edit add a `release.skip_upload: true` entry to the YAML above
3. Run `goreleaser check`

### goreleaser version

```bash
> goreleaser --version
goreleaser version 1.10.3
commit: 315935aedc9908b078ae525b33ddb42b2fafcc54
built at: 2022-07-27T12:55:55Z
built by: goreleaser
goos: darwin
goarch: amd64
module version: v1.10.3, checksum: h1:mNSqSgqOwCyJCEmL35aDvGsZaucKF9yQyARxznqCtDM=

https://goreleaser.com
```

### GoReleaser Check

- [ ] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Awesome tool. Keep up the good work 🤗.

**Comment by tvsaru** [comment]
As a workaround, I did this:

```yaml
  dockers:
    # where actual docker build and pub happens
  release:
  ids:
    - none
    # ^ so as to not include any of the archives
```

**Comment by caarlos0** [comment]
yes, didn't use to be as much as an issue, need to work on that eventually

**Comment by caarlos0** [comment]
a quick workaround would be to deploy only tags, so docs are always up to date with latest...

another idea would be to hack around [this](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning) and deploy last N tags + main, which seems like would be a bit more work...

**Comment by caarlos0** [comment]
played around with https://github.com/jimporter/mike a bit today, it seems to work OK, if deployed to github pages... will also need to hack a 404.html to not break references all over the internet 🤣 

buttttt, if you wanna take a look: https://caarlos0.github.io/goreleaser/

my 404.html hack allows things like https://caarlos0.github.io/goreleaser/customization/checksum/ to work, which is nice, although it does 2 redirects...

we would also have to document, somewhere, how many version we're going to keep, e.g. 5 minors plus all patches of latest 2 minors... 

that would require some manual work on my part (runing `mike delete` or whatever), but seems ok enough.

Another thing to handle is the current static files serving, which will have to be copied to the root folder as well (e.g. scrips, version.json, etc)

thoughts?

**Comment by caarlos0** [comment]
went up with a simpler approach, just commenting the options adding in which version they were added.
