### ISSUE TITLE
Goreleaser fails to parse module tags

### ISSUE THREAD

**Issue by jsirianni** [goreleaser/goreleaser#3370]
### What happened?

The [observiq collector](https://github.com/observIQ/observiq-otel-collector) repo fails to build if the commit we are building is ahead of module tags. For example, we have `v1.8.0` and `exporter/googlecloudexporter/v1.8.0`. When I run a snapshot release build against a working branch, I get the following error:

```bash
goreleaser release --parallelism 4 --skip-validate --skip-publish --skip-sign --rm-dist --snapshot
```
```
  • starting release...
  • loading config file                              file=.goreleaser.yml
  • loading environment variables
  • getting and validating git state
    • building...                                    commit=09a7e302238dce5da27d8ddd601ab3888b8f8a58 latest tag=exporter/googlecloudexporter/v1.8.0
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  ⨯ release failed after 0s                  error=failed to parse tag 'exporter/googlecloudexporter/v1.8.0' as semver: Invalid Semantic Version
```

### How can we reproduce this?

1. Clone https://github.com/observIQ/observiq-otel-collector
2. Checkout main
3. Run `make release-test` or `goreleaser release --parallelism 4 --skip-validate --skip-publish --skip-sign --rm-dist --snapshot`

### goreleaser version

```bash
Latest release binary installed from release page on linux


goreleaser --version
goreleaser version 1.11.2
commit: e31f7806dc0073159cc12dce7605073259105a67
built at: 2022-08-31T01:25:33Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.11.2, checksum: h1:LqKj+63p60dRF3PA15+y+DN9jP6IMrxvyOpZ40YLJ5E=

https://goreleaser.com
```
```


### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

We have other projects that depend on our "sub" modules in this repo, which is why we tag the way we do. In order to move forward with a future release, we will need to delete our module tags or build locally (outside of C I) after removing the local tags.

**Comment by caarlos0** [comment]
Monorepo is a [GoReleaser Pro](https://goreleaser.com/customization/monorepo/) feature.

If that's not what you want, you'd need to manually set `GORELEASER_CURRENT_TAG` and probably `GORELEASER_PREVIOUS_TAG` as well

**Comment by jsirianni** [comment]
Totally forgot about monorepo being a pro feature. Thanks, will consider it.

**Comment by caarlos0** [comment]
You can try for free for 7 days, also since you always help around, ping me in discord/gophers slack and I can get you a discount :)
