### ISSUE TITLE
Also generate AppImage

### ISSUE THREAD

**Issue by probonopd** [goreleaser/goreleaser#338]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by caarlos0** [comment]
@probonopd willing to contribute with a pull a request? 😄

**Comment by probonopd** [comment]
Hi @caarlos0 at the moment I don't have neither the knowledge about Go nor the time to do everything on my own, but I am happy to help if someone works on this and gets stuck on the AppImage-specific aspects.

**Comment by caarlos0** [comment]
Hi @probonopd, me neither, but if anyone wants to do this I'm happy to help :)

**Comment by probonopd** [comment]
Adding activity so that @stale goes away until this is solved.

**Comment by probonopd** [comment]
Adding activity so that @stale goes away until this is solved.

**Comment by caarlos0** [comment]
Following the ["yes is forever" rule](https://twitter.com/solomonstre/status/715277134978113536), I rather not do this - or at least not right now.

Thanks for the suggestion though.

I'll leave the 2.0 milestone and maybe we revisit this in the future.

Cheers!
