### ISSUE TITLE
Go modules download old version of dependencies

### ISSUE THREAD

**Issue by Simaky** [goreleaser/goreleaser#3397]
### What happened?

Hello!
I tried to set up GoReleaser on my GitHub repository, but when I change the lib version (on my go.mod), GoReleaser keed using the old one. Even when it prints in logs that the new version was downloaded, I still get an error that I don't have such a function (it was added in the new lib version).

Locally project builds okay, also when I use goreleaser locally - all is fine. The issue only on GitHub

### How can we reproduce this?

1. Set up GoReleaser on GitHub
2. Make release
3. Update some dependencies in go.mod
4. Make a new release

### goreleaser version

```bash
Latest
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Action: https://github.com/Simaky/Bathyx/actions/runs/3118845353
.goreleaser.yaml: https://github.com/Simaky/Bathyx/blob/master/.goreleaser.yaml
releaser.yml: https://github.com/Simaky/Bathyx/blob/master/.github/workflows/releaser.yml

**Comment by Simaky** [comment]
Logs from GoReleaser:

```
Run goreleaser/goreleaser-action@v2
Downloading https://github.com/goreleaser/goreleaser/releases/download/v1.11.4/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/1c7866dc-5bc9-4[10](https://github.com/Simaky/Bathyx/actions/runs/3118845353/jobs/5058416105#step:6:11)d-9352-b80945235762 -f /home/runner/work/_temp/[11](https://github.com/Simaky/Bathyx/actions/runs/3118845353/jobs/5058416105#step:6:12)a[13](https://github.com/Simaky/Bathyx/actions/runs/3118845353/jobs/5058416105#step:6:14)cd7-9ba0-45d5-813e-f46d24b687dc
GoReleaser latest installed successfully
v1.0.0-beta tag found for commit 'e04ac32'
/opt/hostedtoolcache/goreleaser-action/1.11.4/x64/goreleaser release --rm-dist
  • starting release...
  • loading config file                              file=.goreleaser.yaml
  • loading environment variables
  • getting and validating git state
    • couldn't find any tags before "v1.0.0-beta"
    • building...                                    commit=e04ac32c8ff19307434a03b8a1e1fb94c0f95cc8 latest tag=v1.0.0-beta
  • parsing tag
  • setting defaults
  • checking distribution directory
  • loading go mod information
  • build prerequisites
  • writing effective config file
    • writing                                        config=dist/config.yaml
  • generating changelog
    • writing                                        changelog=dist/CHANGELOG.md
  • building binaries
    • building                                       binary=dist/Bathyx_windows_amd64_v1/Bathyx.exe
    • took: 18s
  ⨯ release failed after 18s                 error=failed to build for windows_amd64_v1: exit status 2: go: downloading github.com/getlantern/systray v1.2.1
go: downloading github.com/Simaky/hid-v2 v1.2.2
go: downloading github.com/getlantern/golog v0.0.0-20190830074920-4ef2e798c2d7
go: downloading golang.org/x/sys v0.0.0-20200515095857-1151b9dac4a9
go: downloading github.com/getlantern/errors v0.0.0-20190325191628-abdb3e3e36f7
go: downloading github.com/getlantern/hidden v0.0.0-20190325191715-f02dbb02be55
go: downloading github.com/getlantern/ops v0.0.0-20190325191751-d70cb0d6f85f
go: downloading github.com/oxtoacart/bpool v0.0.0-20190530202638-03653db5a59c
go: downloading github.com/getlantern/context v0.0.0-20190109183933-c447772a6520
go: downloading github.com/go-stack/stack v1.8.0
go: downloading github.com/getlantern/hex v0.0.0-20190417191902-c6586a6fe0b7
# github.com/Simaky/Bathyx/devices/hyperx
Error: devices/hyperx/cloud_flight_s.go:[14](https://github.com/Simaky/Bathyx/actions/runs/3118845353/jobs/5058416105#step:6:15)3:[21](https://github.com/Simaky/Bathyx/actions/runs/3118845353/jobs/5058416105#step:6:22): device.ReadWithTimeout undefined (type *hid.Device has no field or method ReadWithTimeout)

Error: The process '/opt/hostedtoolcache/goreleaser-action/1.11.4/x64/goreleaser' failed with exit code 1
```

As I see, it downloaded: `downloading github.com/Simaky/hid-v2` **v1.2.2** version
In this repository, I see that function exists, and the local build is successful.
https://github.com/Simaky/hid-v2/blob/v1.2.2/hid_enabled.go#L243

**Comment by caarlos0** [comment]
likely the tag on github.com/Simaky/hid-v2 was recreated, but the previous version was cached by the go mod proxy - and there's nothing you can do about it except tagging it with a new tag.

regardless, this is not a goreleaser issue, as it simply forwards to `go build`, which is what is failing.

**Comment by Simaky** [comment]
@caarlos0 the trouble was that I tried to recreate a new tag, even one that was not used before, like "v1322.42.4"
but anyway go.mod shows that it successfully downloaded this version, but the codebase that it downloaded - is still old.
Also in linter/tests CI all is okay, so only in goreleaser issue exists.

**Comment by caarlos0** [comment]
nope, goreleaser just calls go build:

<img width="1250" alt="CleanShot 2022-09-25 at 10 52 58@2x" src="https://user-images.githubusercontent.com/245435/192147204-f0b7385b-4501-47de-b57b-df56bb2d88ca.png">

maybe your lib uses CGO? if so, you'd need to use a windows runner to build...
