### ISSUE TITLE
Add iOS builds to nFPM deb pkgs

### ISSUE THREAD

**Issue by blacktop** [goreleaser/goreleaser#3410]
### Is your feature request related to a problem? Please describe.

No problem, but there is a community of people that pkg bins/apps for jailbroken phones etc and this would make it much easier for them to include my tools in their distros.

### Describe the solution you'd like

I believe that we could also pkg the GOOS ios GOARCH arm64 builds into deb pkgs if we set the "Architecture: field in the control file to `iphoneos-arm64`". 

Is that possible to add as a config?

### Describe alternatives you've considered

I'm not sure how else to do this?

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I think from a UX point of view you would just add `ios` as a one of the `builds` to be packaged and it would auto set the `iphoneos-arm64` and apologies if you have already implemented this.

**Comment by blacktop** [comment]
I just tested it and all non-linux builds are ignored in the `nfpms` config

**Comment by blacktop** [comment]
@CRKatri ? I assume that it's not testable unless macOS can also install debs?

**Comment by CRKatri** [comment]
You can test packaging them, and the code should be identical to the packaging code used for Linux debs. You obviously can't test running the iOS binaries with GitHub actions, you could probably do something with corellium, but that's very expensive for no real benefit.

**Comment by blacktop** [comment]
@CRKatri I can see where @caarlos0 is testing his debs here - https://github.com/goreleaser/goreleaser/blob/main/Taskfile.yml#L162

Is there a docker image that can approximate the iOS environment at least just for installing debs?

**Comment by CRKatri** [comment]
No. As I said though, as long as the Linux debs work, the ios debs will too.

**Comment by caarlos0** [comment]
if its just setting that arch, you can use nfpm directly... but within goreleaser, no there isn't...

**Comment by Arsen6331** [comment]
> wait... jailbroken iphones can install debs?

Yes, the jailbreaking tools actually install `apt` on them.

> if so... can we run automated tests on github actions? if not, I'd be inclined to not implement this.

You wouldn't be able to test on iOS itself, but as I said, it uses unmodified `apt` just like Debian/Ubuntu, so the current tests should be sufficient, goreleaser would just have to allow setting GOOS to `ios`

**Comment by caarlos0** [comment]
goreleaser allows setting GOOS to ios, not sure if github actions et al build it though (pretty sure they don't without a good amount of modifications), but goreleaser will not package debs for ios.

maybe we could do something like:

```yaml
nfpm:
- id: foo
  package_name: etc
  goos: ios
```

so, `goos` is `linux` by default, but users can specify `ios` as well. Is that the only modification needed?

**Comment by blacktop** [comment]
I believe we would also need to ensure in your nfpm pkg that `ios`/`arm64` would map to:

> Architecture: field in the control file to iphoneos-arm64

**Comment by blacktop** [comment]
I was thinking you could add support for an `ios` build to be added to the `nfpm` `builds` array, but then you'd have to handle/worry about people trying to include other GOOSes etc into the future so I like you suggest of just having `ios` be another option for this small edge case.  👍

**Comment by caarlos0** [comment]
> I believe we would also need to ensure in your nfpm pkg that `ios`/`arm64` would map to:
> 
> > Architecture: field in the control file to iphoneos-arm64

yes, that would be the idea...

**Comment by caarlos0** [comment]
> I was thinking you could add support for an `ios` build to be added to the `nfpm` `builds` array, but then you'd have to handle/worry about people trying to include other GOOSes etc into the future so I like you suggest of just having `ios` be another option for this small edge case. 👍

hmm, that might be even simpler, as the majority of projects don't build for ios anyway... 

will think about it for a bit... having a rough couple of weeks personal life wise, but will see what I can do...

**Comment by blacktop** [comment]
Really appreciate everything you do @caarlos0 ❤️

**Comment by caarlos0** [comment]
check out #3436
