### ISSUE TITLE
Brew tap not accepted in homebrew-core

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#342]
See: https://github.com/Homebrew/homebrew-core/pull/16943

**Comment by caarlos0** [comment]
yeah, rules for getting into the core are different. As they said, you must write a formula that builds your code from source...

this means you have to declare all dependencies and etc in the `.rb` file.

see for example, [termshare recipe](https://github.com/Homebrew/homebrew-core/blob/0cb1e13a226300da453d52eaf7941973eb14988e/Formula/termshare.rb).

as far as I understand, these formulas generate the binaries (they call them bottles or something like that), and when you `brew install` something, the binaries are downloaded and linked.

I'm not sure if generating formulas in the right form for homebrew-core is something we should do right now, as it is way complex than our current form for taps.

what are your thoughts?

**Comment by bep** [comment]
>what are your thoughts?

I think that:

* When you state in your README that you support `brew`, people will expect their binaries to be gettable via `brew install` without additional "taps mumbojumbo". As this is clearly not the case, it should be stated in **bold** text.
*  I agree that building from source requires some additional config, but it is based on a source release. I think a better example would be https://github.com/Homebrew/homebrew-core/blob/e448d9dc0a540a7f1810ea4ed8f6198f45f573d2/Formula/hugo.rb

Note that I know very little about brew, but their documentation is pretty bad, and `goreleaser` didn't do much to help reduce the confusion.

**Comment by caarlos0** [comment]
> When you state in your README that you support brew, people will expect their binaries to be gettable via brew install without additional "taps mumbojumbo". As this is clearly not the case, it should be stated in bold text.

agreed! will fix that.

> I agree that building from source requires some additional config, but it is based on a source release. I think a better example would be Homebrew/homebrew-core:Formula/hugo.rb@e448d9d

indeed it's better, didn't knew we could use `godep` and etc... good to know

> Note that I know very little about brew, but their documentation is pretty bad, and goreleaser didn't do much to help reduce the confusion.

I don't know much either and I agree the docs are not ideal as well as our docs are also not ideal.

**Comment by caarlos0** [comment]
Either way, I believe that, with some config, we might be able to generate valid formulas like this one you shared.

**Comment by bep** [comment]
@caarlos0 yes, but I would not spend too much time on "magic logic"; what would be cool if you could add a "tap template" so project owners could script the "govendor etc. logic" themselves.

**Comment by magiconair** [comment]
As a first step it might be sufficient if you could template a formula. Between releases the formula usually only changes in the checksums. If I could provide a template which goreleaser fills and uploads then I'm mostly there.
