### ISSUE TITLE
Checksum file for each release?

### ISSUE THREAD

**Issue by zerok** [goreleaser/goreleaser#343]
Hi :)

Would it make sense to offer the option to generate one checksum file per archive within the dist folder? My use-case is that I'd like to simply rsync my local dist folder up to out assets server which might already contain other releases that are not available locally. In this case I'd pollute the shared checksums.txt file and potentially remove entries for it by accident.

**Comment by caarlos0** [comment]
make sense!

would the file be named something like `name_of_the_archive_checksums.txt` or is there another name template that's common for this use case?

**Comment by zerok** [comment]
I'm not yet sure if it would even make sense to group them per release and also support multiple algorithms:

```
project_VERSION_darwin_amd64.tar.gz
project_VERSION_windows_amd64.tar.gz
project_VERSION.md5sum
project_VERSION.sha512sum
...
```
