### ISSUE TITLE
Set parse mode for Telegram announcer

### ISSUE THREAD

**Issue by stnokott** [goreleaser/goreleaser#3431]
### Is your feature request related to a problem? Please describe.

I think having the option to use any of the [available formatting options](https://core.telegram.org/bots/api#formatting-options) for sending Telegram messages (MarkdownV2/HTML) would greatly benefit the Telegram announce module.

Currently, there is only plaintext possible with some formatting that Telegram does on its own (e.g. making URLs clickable).

The fix (see below) is really simple, just a single line, and would allow formatting options such as font styling or URL formatting.

### Describe the solution you'd like

This is how a Telegram announcement is currently sent:

https://github.com/goreleaser/goreleaser/blob/11447a8990f8b4c95fc470d1fb83a79ecc1f64cd/internal/pipe/telegram/telegram.go#L48-L49

I would extend this with an additonal line, setting the parse mode in the [MessageConfig](https://pkg.go.dev/github.com/go-telegram-bot-api/telegram-bot-api/v5#MessageConfig) object.
```go
	tm := api.NewMessage(ctx.Config.Announce.Telegram.ChatID, msg)
        tm.ParseMode = "MarkdownV2"
	_, err = bot.Send(tm)
```

### Describe alternatives you've considered

The obvious alternative is to stick with plaintext.
While this is acceptable, having the option to format the announcements is a plus.
Additionally, if you don't want any special formatting, you can simply not use any formatting.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

The solution is focused on simplicity and thus doesn't allow the user to specify the parse mode themselves, e.g. in the `.goreleaser.yaml`.

This raises two potential discussion points:
- Do we invest additonal time to allow configuring the parse mode in the `.goreleaser.yaml` instead of choosing a default parse mode for the user?
- If not, do we set the default parse mode as HTML or MarkdownV2?

I'd raise a PR myself, but first, I'd love to hear what the community thinks about this feature and these questions.

**Comment by caarlos0** [comment]
sounds like a plan, @stnokott, feel free to PR it :)
