### ISSUE TITLE
Support for uploading to Artifactory

### ISSUE THREAD

**Issue by skisulli** [goreleaser/goreleaser#344]
We use [JFrog Artifactory](https://www.jfrog.com/artifactory/) to store all our build artifacts. It would be great if goreleaser could upload to an Artifactroy server and add a link to the binaries in the release notes on GitHub.

This could probably work by just allowing for a generic server destination. In our case, we usually upload to Artifactor by just calling `curl -uUSERNAME:PASSWORD -T FILE "URL"`.

**Comment by andygrunwald** [comment]
I mentioned the Artifactory upload here a well: https://github.com/goreleaser/goreleaser/issues/320

**Comment by skisulli** [comment]
#320 only covers pushing the docker image to Artifactory correct? We have two different uses cases for Artifactory. We use it as our docker image store for most of our applications, but we also use it to store arbitrary binaries. I would love to be able to set an Artifactory endpoint that the binaries pushed to GitHub would get pushed to.

**Comment by andygrunwald** [comment]
@skisulli True. The PR covers only the Docker part.
#320 mention that we want to use the Artifactory part as well.
We use Artifactory the same way like you: For Docker images and single binaries, but true, #320 don't solve the original request (or maybe i was mentioning it wrong).
So, thanks for this ticket. You found a supporter :)

**Comment by andygrunwald** [comment]
@skisulli @caarlos0 I just want to let you know that i am working on this right now (in the evenings an hour here and there).
I have it running version already locally. I need to clean it up, document it, write down my trade offs / decisions and prepare the PR. So i will need a couple of hours for this.
Just to avoid that someone starts working in between.

**Comment by andygrunwald** [comment]
Checkout #429

**Comment by caarlos0** [comment]
Thanks to @andygrunwald , this can finally be closed 🎉
