### ISSUE TITLE
Option to skip actual build/artifact phase for focusing on generating homebrew formula

### ISSUE THREAD

**Issue by musaprg** [goreleaser/goreleaser#3440]
### Is your feature request related to a problem? Please describe.

AFAIK goreleaser cannot skip actual build and artifact phases in the pipeline. I'd like to check and validate generated homebrew formula with `brew audit`, but the build and artifact phases usually take too long, which is redundant for that purpose.

### Describe the solution you'd like

It would be nice to have some option to skip the actual build and create artifacts in the build and artifact phases. We can determine the name of the final artifacts without performing an actual build or artifact process, which means that the goreleaser can generate such files like Homebrew Formula, and `CHANGELOG.md` directly with no redundant phases.

### Describe alternatives you've considered

AFAIK there are no alternatives.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
brew taps dont need to pass audits, adding this feature would be a lot of work for little to no benefit... 

if you want to build faster you can remove some build targets from your config while testing.

All that said, ["yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion either way.
