### ISSUE TITLE
Wrong architecture in .deb when building for arm

### ISSUE THREAD

**Issue by hugoShaka** [goreleaser/goreleaser#345]
The only architectures goreleaser supports when using fpm are x86_64 and i386.
When building for arm architectures the .deb package generated won't be installed by dpkg : 
For example, here I have ARM binaries but the package is flagged for amd64 :
```
# dpkg -i hugo_0.26_Linux-ARM.deb 
dpkg: error processing archive hugo_0.26_Linux-ARM.deb (--install):
 package architecture (amd64) does not match system (armhf)
Errors were encountered while processing:
 hugo_0.26_Linux-ARM.deb
```
Those lines are responsible of the Architecture choice when calling fpm :
https://github.com/goreleaser/goreleaser/blob/42446c807989f83b98f4fa11a41b728eb0b38661/pipeline/fpm/fpm.go#L57-L62

There are many arm architectures and it may be painful to add each one, but could the default architecture be "all" when building deb packages and "noarch" when building rpms ?
It would allow the package to be installed (which may be useful) and as far as the arch is specified in the name template it should not be a problem.

**Comment by caarlos0** [comment]
Thanks for reporting this @hugoShaka !

#346 should fix it :)
