### ISSUE TITLE
region is not templated correctly in blobs: region:

### ISSUE THREAD

**Issue by gerhard** [goreleaser/goreleaser#3460]
### What happened?

Given the following `.goreleaser.yml` excerpt:

```yaml
blobs:
  - provider: s3
    region: "{{ .Env.AWS_REGION }}"
    bucket: "{{ .Env.AWS_BUCKET }}"
```

I was expecting `region` to be templated. It wasn't: https://github.com/gerhard/dagger/actions/runs/3243965037/jobs/5319453856#step:10:612

### How can we reproduce this?

I was running this in a GitHub Action. Here is the config: https://github.com/gerhard/dagger/blob/add-workflow-for-0.3-pre-releases/.github/workflows/release-v0.3.x.yml

This fixed it: https://github.com/gerhard/dagger/commit/592cab43de0945f571fc72d02b27488e3da3308f

If I can try the revert with a pre-release of GoReleaser, I'm up for it.

### goreleaser version

```bash
https://github.com/goreleaser/goreleaser/releases/download/v1.11.5/goreleaser_Linux_x86_64.tar.gz

https://github.com/gerhard/dagger/actions/runs/3243965037/jobs/5319453856#step:10:16
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
docs don't say it is templateable, so this is more of a feature request (a valid one, though :) )

**Comment by gerhard** [comment]
Good point!

I was assuming (wrongly) that all values in `.goreleaser.yml` are templateable.

Thank you for the quick response!

**Comment by caarlos0** [comment]
> I was assuming (wrongly) that all values in `.goreleaser.yml` are templateable.

they are not, although we should definitely do a better job at specifying which ones are.

anyway, pr #3461 should fix this particular case :)

**Comment by caarlos0** [comment]
oh, and thanks for reporting!

**Comment by caarlos0** [comment]
fixed in https://github.com/goreleaser/goreleaser/pull/3461

**Comment by gerhard** [comment]
This is amazing, thank you very much! 👏

Looking forward to using this when `v1.12.0` ships.
