### ISSUE TITLE
Load brew tap dependencies from Brewfile

### ISSUE THREAD

**Issue by jphastings** [goreleaser/goreleaser#3462]
### Is your feature request related to a problem? Please describe.

I keep a `Brewfile` in my repository, so developers of my tool can ensure they have the right dependencies; but I _also_ need to make sure the [dependencies](https://goreleaser.com/customization/homebrew/#:~:text=package%20depends%20on.-,dependencies%3A,-%2D%20name%3A) section of the `.goreleaser.yaml` is in line with this. This has caught me out twice already (breaking my build as soon as its run on a machine other than my own), and I can see it happening again!

<details>
<summary>What I have to do today</summary>

In `.goreleaser.yaml`:
```yaml
brew:
  dependencies:
  - name: thing1
```

In `Brewfile`
```ruby
brew "thing1"
```
</details>

### Describe the solution you'd like

I'd like to be able to specify the name of a Brewfile in the dependencies section array. `goreleaser` would parse (a cut down subset?) of the `Brewfile` syntax, and turn it into dependencies.

In `.goreleaser.yaml`:
```yaml
brew:
  dependencies:
  - brewfile: Brewfile
```

### Describe alternatives you've considered

1. I could write an extra test in my code which parses the `Brewfile`, parses the `.goreleaser.yaml`, and compares the output. (This is broadly the same work as above, and doesn't benefit other goreleaser users)
2. I've set my `Brewfile` up to (instead) use the `.goreleaser.yaml` as its source of truth for the Formulae to install. This works, but it's not intuitive for others contributing:

In `Brewfile`:
```ruby
# This file uses .goreleaser.yaml's homebrew dependencies as its source of truth. Add new dependencies there, not here.
# https://goreleaser.com/customization/homebrew/#:~:text=package%20depends%20on.-,dependencies%3A,-%2D%20name%3A
# This is so that the dependencies in the released Formula are in sync with what's needed to develop

YAML.load_file('.goreleaser.yaml')['brews'].each do |tap|
  tap['dependencies'].each do |dep|
    if dep['version']
      brew "#{dep['name']}@#{dep['version']}"
    else
      brew dep['name']
    end
  end
end
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
sorry, this is not something I'm interested in adding...  

thanks for the suggestion anyway
