### ISSUE TITLE
changelog usage in built embed.FS 

### ISSUE THREAD

**Issue by mkungla** [goreleaser/goreleaser#3484]
### Is your feature request related to a problem? Please describe.

I'm including changelog in built application `embed.FS` so currently I first generate changelog with custom `--config` file and then run actual build with project config.

### Describe the solution you'd like

add optional changelog option to define path to write changelog before package builtd.

e.g.

```yaml
changelog:
  copy_file: ./my/embed/fs/CHANGELOG.md
```

So that build executed after changelog is generated enables package to include `/CHANGELOG.md` into embed.FS

### Describe alternatives you've considered

having separated config to create CHANGELOG.md before running actual build

or if it would be possible

```yaml
before:
  hooks:
    - cp ./dist/CHANGELOG.md ./my/embed/fs/CHANGELOG.md
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
have you tried a pre build hook? https://goreleaser.com/customization/build/?h=hooks

**Comment by caarlos0** [comment]
should be fixable by copying in the build hooks, closing.
