### ISSUE TITLE
Gitea Publish URL contains an extra /

### ISSUE THREAD

**Issue by SamTherapy** [goreleaser/goreleaser#3487]
### What happened?

When following [the documentation](https://goreleaser.com/scm/gitea/#urls), publishing a release to Gitea creates a URL that Gitea cannot parse properly.

This incorrect URL will be published when pushing to a homebrew repository, where trying to install will 404.

### How can we reproduce this?

https://try.gitea.io/goreleaserbugtester9000/GoreleaserTest

```yaml
gitea_urls:
  api: https://try.gitea.io/api/v1/
```

creates an (incorrect) publishing URL at https://try.gitea.io//goreleaserbugtester9000/GoreleaserTest/releases/tag/v0.0.4
Homebrew repo: https://try.gitea.io/goreleaserbugtester9000/homebrew/src/branch/main/GoreleaserTest.rb#L12

while

```yaml
gitea_urls:
  api: https://try.gitea.io/api/v1
```

creates a (correct) publishing URL at https://try.gitea.io/goreleaserbugtester9000/GoreleaserTest/releases/tag/v0.0.5
Homebrew repo: https://try.gitea.io/goreleaserbugtester9000/homebrew/src/branch/main/TestCorrectURL.rb#L12

### goreleaser version

```bash
goreleaser version 1.12.3
commit: e27e6a9e8c66ec5d2bbcafb1c047068bcf250269
built at: 2022-10-20T12:30:56Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.12.3, checksum: h1:sTJXdkGQO9eAP6pwEUazaD6ERJewZ7yzQexWEGPUVg4=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Related Gitea issue: https://github.com/go-gitea/gitea/issues/20462

If this behaviour is intentional, I can make a PR to fix the docs.

**Comment by caarlos0** [comment]
so, we could basically strip any trailing `/` in gitea URL?

**Comment by SamTherapy** [comment]
I think so? I have tried applying the below patch as a naïve fix and both the tests passed and the URL was correct when supplying the .yaml file with the trailing slash.

```diff
diff --git a/internal/pipe/defaults/defaults.go b/internal/pipe/defaults/defaults.go
index 4bdfeb1c..f947e69c 100644
--- a/internal/pipe/defaults/defaults.go
+++ b/internal/pipe/defaults/defaults.go
@@ -36,6 +36,7 @@ func (Pipe) Run(ctx *context.Context) error {
 		}
 
 		ctx.Config.GiteaURLs.Download = strings.ReplaceAll(apiURL, "/api/v1", "")
+		ctx.Config.GiteaURLs.Download = strings.TrimSuffix(apiURL, "/")
 	}
 	for _, defaulter := range defaults.Defaulters {
 		if err := errhandler.Handle(defaulter.Default)(ctx); err != nil {
```

**Comment by caarlos0** [comment]
yeah, looks like a fix.. wanna pr it?

**Comment by SamTherapy** [comment]
Sure. If I have documentation changes, should those be separate?

**Comment by caarlos0** [comment]
> Sure. If I have documentation changes, should those be separate?

nope, same pr is fine :) 

docs are all in the `www` folder
