### ISSUE TITLE
VCS info is not embedded

### ISSUE THREAD

**Issue by capnspacehook** [goreleaser/goreleaser#3491]
### What happened?

I tried to build a binary with goreleaser that included vcs information introduced in Go 1.18. I tried with and without passing `-buildvcs=true` to `builds.flags` to the same effect. I came across #3143 which made me think I was configuring goreleaser incorrectly. However, I inspected the linux amd64 binary of goreleaser v1.12.3 and saw that vcs infomation wasn't embedded there either:

![image](https://user-images.githubusercontent.com/23243104/197422639-fe98b77d-08b2-4a81-a5ec-61cb0148823f.png)

### How can we reproduce this?

Goreleaser config here: https://github.com/capnspacehook/go-project-template/blob/dd31bc20dd52c571fb6a672c304cd0f851367c33/.goreleaser.yml

Goreleaser Actions workflow here: https://github.com/capnspacehook/go-project-template/blob/dd31bc20dd52c571fb6a672c304cd0f851367c33/.github/workflows/release.yml#L35

### goreleaser version

```bash
goreleaser version dev
goos: linux
goarch: amd64
module version: v1.12.3, checksum: h1:sTJXdkGQO9eAP6pwEUazaD6ERJewZ7yzQexWEGPUVg4=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by capnspacehook** [comment]
After more investigation this only seems to happen when `gomod: proxy` is set to true

**Comment by caarlos0** [comment]
afaik that is expected when building from the go mod proxy, maybe docs need to be clearer about it though
