### ISSUE TITLE
Increase build timeout limit

### ISSUE THREAD

**Issue by BitsOfAByte** [goreleaser/goreleaser#3532]
### Is your feature request related to a problem? Please describe.

I typically run UPX as a post-build script, and when doing so in slower environments (like GitHub Actions) I typically run into issues where GoReleaser will fail due to a context timeout.

### Describe the solution you'd like

Some sort of configuration option to increase context timeout to allow for more intensive build steps to go forward as normal. Even without doing some intensive tasks, building a lot of architectures can also typically timeout in a CI environment depending on machine specifications.

### Describe alternatives you've considered

I've tried dropping support for a couple of architectures, but I intended to support as many as possible with this application because it's so easy to do so.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
There is a `--timeout` option https://goreleaser.com/cmd/goreleaser_release/

**Comment by BitsOfAByte** [comment]
My bad, couldn't find it when using the sesrch on the docs! Apologies again
