### ISSUE TITLE
Github Action based podman builds fail (GoReleaser-Pro 1.12.3) mount /var/lib/containers/storage/aufs:/var/lib/containers/storage/aufs, flags: 0x1000: operation not permitted

### ISSUE THREAD

**Issue by karlmutch** [goreleaser/goreleaser#3538]
### What happened?

When running GoReleaser Pro within a github action the container build step fails with an operation not permitted

`
docker images
    • building docker image                          image=************
  ⨯ release failed after 5m12s               error=docker build failed: failed to build ***************: exit status 125: Error: mount /var/lib/containers/storage/aufs:/var/lib/containers/storage/aufs, flags: 0x1000: operation not permitted
`

In reWhen adding an option to modify the appamour options I get the following which as unexpected as it is a valid option for podman ?

`
  • docker images
    • building docker image                          image=********
  ⨯ release failed after 4m25s               error=docker build failed: failed to build ******: exit status 125: Error: unknown flag: --security-opt apparmor
`

### How can we reproduce this?

Use a github action to perform a container build.  CLI based builds on stock ubuntu VM's dont fail.

### goreleaser version

```bash
goreleaser version 1.12.3-pro
commit: 6d21959bff23d986a0c58b0d69b303e6119290e5
built at: 2022-10-20T12:27:42Z
built by: goreleaser
goos: linux
goarch: amd64

https://goreleaser.com/pro
  • by using this software you agree with its EULA, available at https://goreleaser.com/eula
  • running goreleaser v1.12.3-pro
  • loading config file                              file=.goreleaser.yml
  • checking config...
  • config is valid
  • thanks for using goreleaser-pro!
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

The follow article might contain useful context ? https://flavio.castelli.me/2020/09/16/build-multi-architecture-container-images-using-kubernetes/

**Comment by caarlos0** [comment]
goreleaser never runs anything with `--security-opt` flags... and it also does not set up podman up... 

that said, I did find a bug... seems like the path might be getting messed up at times, which - at least for me, caused weird nsenter errors - which I'm pushing a fix right now...

other than that, I usually just install podman with `apt install podman` on github actions... you might want to follow along https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md as well if you want rootless builds, something like this in github actions:

```
      - name: setup-podman
         run: |
           sudo apt-get update
           sudo apt-get install -yq podman moreutils util-linux
           mkdir -p ~/.config/containers/
           sudo rm -rf ~/.local/share/containers/storage/
           echo -e '[engine]\nruntime = "crun"' >~/.config/containers/containers.conf
```

**Comment by caarlos0** [comment]
fix for the PATH issues will be in the next release...
