### ISSUE TITLE
Cannot docker COPY binary with - in the name?

### ISSUE THREAD

**Issue by josvazg** [goreleaser/goreleaser#3545]
### What happened?

Our *Dockerfile* used this COPY command:

```Dockerfile
COPY refs-controller /bin/
```

But we were getting an error like this:
```
#6 ERROR: "/refs-controller" not found: not found
------
 > [2/3] COPY refs-controller /bin/:
------
error: failed to solve: failed to compute cache key: "/refs-controller" not found: not found
```

### How can we reproduce this?

Maybe it happens with any binary that includes a `-` in the name?

We tried this instead:
```Dockerfile
COPY * /bin/
```

And we got this in bin:
```
bin/Dockerfile
bin/refs-controller
```

So basically we knew that `refs-controller` was there.

We end up tricking **goreleaser** with:
```
COPY *controller /bin/
```

### goreleaser version

```bash
goreleaser version dev
goos: linux
goarch: amd64
module version: v1.12.3, checksum: h1:sTJXdkGQO9eAP6pwEUazaD6ERJewZ7yzQexWEGPUVg4=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by josvazg** [comment]
BTW we tried version `1.1.0` and the error was not happening there. We need to use 1.2.x as it is the one the CI pipeline will grab.

**Comment by caarlos0** [comment]
goreleaser simply calls `docker build`, if `copy *` works, and `copy name` doesn't, that seems like a docker bug to me...

**Comment by caarlos0** [comment]
I have no idea... is it possible you have a space or some "invisible" char in the binary name? its the only thing that comes to mind... 

fwiw if this is a bug in goreleaser since v1.3, a lot of people would be having it... even goreleaser itself probably... so, I'm suspicious its something else entirely

**Comment by josvazg** [comment]
uhm I need to double check that weird character theory... but I think I rewrote that name several times.
I will get back here once tested.

**Comment by caarlos0** [comment]
if you have a reproducible repo, I can try here as well..

**Comment by josvazg** [comment]
Reproduced:
https://github.com/josvazg/grfail

Did not need a `-` in the name. Seems it fails in multi-arch.

**Comment by caarlos0** [comment]
ahh, you're missing the `goarm` option... probably this could be better handled though...

if you add `goarm: 6` to line 27 it should work just fine

https://github.com/josvazg/grfail/blob/main/goreleaser.yml#LL26

**Comment by caarlos0** [comment]
see #3552

**Comment by caarlos0** [comment]
probably it worked in the sense that it didn't failed, but the binary was not in the image, just license and other files... maybe you looked into the wrong image later?

**Comment by caarlos0** [comment]
fwiw: now it'll default to 6, so it should be a bit better... thinking about it a bit more now, I'll also add a warning if nothing is matched...
