### ISSUE TITLE
goreleaser init fails

### ISSUE THREAD

**Issue by klauern** [goreleaser/goreleaser#356]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

created a project, initialized a git repository (no remote yet), added some files to it.  Then `goreleaser init` fails:

```
 goreleaser --debug init                  
   ⨯ failed to init project    error=failed reading repo from git: exit status 1:           
```

### Environment

Please paste the output of:

- `go version`
```
go version go1.9 linux/amd64                  
```
- `uname -a`
```
Linux klauer1nick 4.14.0-1-MANJARO #1 SMP PREEMPT Wed Sep 6 06:41:24 UTC 2017 x86_64 GNU/Linux                                                                                          
```
- `go release --debug`
```
goreleaser --debug                       
   • running goreleaser dev                   
   • could not load config, using defaults file=.goreleaser.yml                             
   • parallelism: 4                           
   • SETTING DEFAULTS                         
   ⨯ release failed            error=failed reading repo from git: exit status 1:           
```

**Comment by caarlos0** [comment]
@klauern if the folder a git repository?

**Comment by klauern** [comment]
yes, but it does not have a remote (yet).

**Comment by caarlos0** [comment]
@klauern hmm, that's probably the issue. 

errors should be better, though. 

Thanks for reporting!

**Comment by andygrunwald** [comment]
@caarlos0 I would love to give it a try, if you don't mind.

**Comment by caarlos0** [comment]
I didn't like that implementation... not sure how is the better way to handle this.

**Comment by caarlos0** [comment]
This will still fail, but will have a coherent error message now.

Thanks for reporting!
