### ISSUE TITLE
Go Template Syntax in filenames break goreleaser

### ISSUE THREAD

**Issue by brumhard** [goreleaser/goreleaser#3573]
### What happened?

So we're using goreleaser to release https://github.com/SchwarzIT/go-template.
The repo basically contains a template for new Go projects.
It worked fine a few months ago (latest known working version was v1.10.3). So after a while we wanted to release a new version and the pipeline now fails with version v1.12.3.

The error output is:
```
⨯ release failed after 1m36s               error=failed to apply template _template/api/proto/{{.Base.appName}}/v1/{{.Base.appName}}.proto: template: tmpl:1:27: executing "tmpl" at <.Base.appName>: map has no entry for key "Base"
```
So I guess some templating feature has been released for filenames?

### How can we reproduce this?

```shell
git clone git@github.com:SchwarzIT/go-template.git
cd go-template
goreleaser release --snapshot
```

### goreleaser version

```bash
goreleaser version 1.12.3
built by: nixpkgs
goos: darwin
goarch: arm64

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
```

failed to apply template _template/api/proto/{{.Base.appName}}/v1/{{.Base.appName}}.proto: template: tmpl:1:27: executing "tmpl" at <.Base.appName>: map has no entry for key "Base"

```

I looked into your config and didn't see anything like this, but probably we added templating support to some field that didn't had it before, and now it's breaking for you because that template is not available.

Nothing we can do to fix it, you should probably replace your templates before running goreleaser.

**Comment by brumhard** [comment]
@caarlos0 the problem in this case is that the templates are part of the application and the whole folder with template syntax in the filenames should be embedded into the application to be templated when running the CLI that `go-template` provides. So there's no way that we can replace the templates before running goreleaser.

Would it maybe be possible to add some flag to the config to disable whatever feature that now breaks it for our usecase?
Otherwise I guess we will be stuck with `v1.10.3` forever.

**Comment by caarlos0** [comment]
unfortunately no.. you could probably escape the templates? For instance, using `printf` et al
