### ISSUE TITLE
Windows build by default

### ISSUE THREAD

**Issue by jolheiser** [goreleaser/goreleaser#3579]
### Is your feature request related to a problem? Please describe.

It looks as though Windows hasn't been a default since the beginning 
https://github.com/goreleaser/goreleaser/blob/efff5d5e17f2a9b67e77d8ec0969d5ade670e3ff/config/config.go#L70

Although `goreleaser init` generates a config with windows added, it seems there are users who use the default config in a GH action or similar.

### Describe the solution you'd like

The following line just needs `windows` added to it.

https://github.com/goreleaser/goreleaser/blob/090365bf7814862f00713cd3dde23764e880efa5/internal/builders/golang/build.go#L56

### Describe alternatives you've considered

Sending a PR to every project that uses the default, but this would be simpler and arguably more correct.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
shoud be ok to add it as a default too, I think
