### ISSUE TITLE
Allow templating for env vars within build, and build overrides

### ISSUE THREAD

**Issue by HenryNguyen5** [goreleaser/goreleaser#3580]
### Is your feature request related to a problem? Please describe.

Currently, im using cross-platform builds via `zig`, for an example you can see: https://dev.to/kristoff/zig-makes-go-cross-compilation-just-work-29ho

What ends up happening is that I have a very long `CC` and `CXX` env var that gets mostly reused across builds, but with minor changes per platform. 

Ex. This is what my build script looks like right now:

```sh
macos_compiler_flags=" \
-isysroot$sdk_dir \
-F$sdk_dir$framework_search_path \
-iframeworkwithsysroot$framework_search_path \
-iwithsysroot$include_search_path \
-mmacosx-version-min=11.7.1"

main_ld_flags="-s -w -X 'main.Version=${VERSION-}'"

# We set system-dependent relative paths here so we can store the lib within ./libs
# https://dev.my-gate.net/2021/08/04/understanding-rpath-with-cmake/
mac_ld_flags="$main_ld_flags -r=@executable_path/libs"
linux_ld_flags="$main_ld_flags -r=\$ORIGIN/libs"

build_flags=(-trimpath -buildmode=pie)
cc="zig cc -target"
cxx="zig c++ -target"

export CGO_ENABLED=1

mkdir -p ./dist

export GOOS=darwin
GOARCH=arm64 \
  CC="$cc aarch64-macos $macos_compiler_flags" \
  CCX="$cxx aarch64-macos $macos_compiler_flags" \
  go build "${build_flags[@]}" -ldflags="$mac_ld_flags" -o dist/myprogram-macos-m1 ./cmd

GOARCH=amd64 \
  CC="$cc x86_64-macos $macos_compiler_flags" \
  CCX="$cxx x86_64-macos $macos_compiler_flags" \
  go build "${build_flags[@]}" -ldflags="$mac_ld_flags" -o dist/myprogram-macos-x86_64 ./cmd

export GOOS=linux
GOARCH=arm64 \
  CC="$cc aarch64-linux-gnu" \
  CCX="$cxx aarch64-linux-gnu" \
  go build "${build_flags[@]}" -ldflags="$linux_ld_flags" -o dist/myprogram-linux-aarch64 ./cmd

GOARCH=amd64 \
  CC="$cc x86_64-linux-gnu" \
  CCX="$cxx x86_64-linux-gnu" \
  go build "${build_flags[@]}" -ldflags="$linux_ld_flags" -o dist/myprogram-linux-x86_64 ./cmd
```

I previously found https://github.com/goreleaser/goreleaser/issues/2829#issuecomment-1030697442 which states that it might not be possible, but it was awhile ago, so maybe that situation is better now.

### Describe the solution you'd like

It would be nice to be able to write something like the following:

```sh
builds:
  - main: ./cmd
    ldflags: -X "main.Version={{ .Version }}"
    id: mac
    env:
      - CC=zig cc -v -target {{ if eq .Arch "arm64" }}aarch64{{else}}x86_64{{end}}-macos
      - CCX=zig c++ -v  -target {{ if eq .Arch "arm64" }}aarch64{{else}}x86_64{{end}}-macos
    goarch:
      - arm64
      - amd64
    flags:
      - -trimpath
      - -buildmode=pie
    goos:
      - darwin
```

or/and be able to do the same with env fields within overrides.

Another possible solution would be to expose `CC` and `CXX` as their own specific fields like `ldflags` which supports templating, since they are frequently used for cross platform builds with CGO enabled.

### Describe alternatives you've considered

I considered this: https://github.com/goreleaser/goreleaser/issues/459

But with the amount of flags i am maintaining for `CXX` and `CC`, it would result in a lot of duplication, and I am better off just using shell scripts instead which let me compose the env vars. 

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
refs https://github.com/goreleaser/goreleaser/pull/2583

**Comment by caarlos0** [comment]
hey @HenryNguyen5 , could you give #3592 a try?

**Comment by HenryNguyen5** [comment]
> hey @HenryNguyen5 , could you give #3592 a try?

hey @caarlos0! sorry for the late reply. I'd like to confirm that it looks like it's working with the testing I've been doing so far. Thank you!
