### ISSUE TITLE
support template in the install section for brews 

### ISSUE THREAD

**Issue by cpanato** [goreleaser/goreleaser#3587]
### Is your feature request related to a problem? Please describe.

support the templating in the install section for the `brew` 

we generate binaries in the following format: `binaryName_{{ .Os }}_{{ .Arch }}`

and when creating the brew formula to users to install we would like to rename the binary in the install time to just `binaryName`

so in the brew syntax it is

`bin.install "binaryName_{{ .Os }}_{{ .Arch }}" => "binaryName"`

however when you add this in the gorelreaser config

```
...
brews:
...
  install: |
    bin.install "binaryName_{{ .Os }}_{{ .Arch }}" => "binaryName"
```

we receive an error

```
error=template: tmpl:16:33: executing "tmpl" at <.Os>: map has no entry for key "Os"
```

### Describe the solution you'd like

the install section in the brew should accept template variables

### Describe alternatives you've considered

n/a

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

thank you

**Comment by caarlos0** [comment]
@cpanato please check #3593

**Comment by cpanato** [comment]
@caarlos0 please let me know when you release it :)

**Comment by caarlos0** [comment]
@cpanato probably middle december, I plan to get nightlies for goreleaser oss as well, so you can use those meanwhile if you want
