### ISSUE TITLE
Expose original non-replaced single artifact fields

### ISSUE THREAD

**Issue by Arsen6331** [goreleaser/goreleaser#3588]
### Is your feature request related to a problem? Please describe.

GoReleaser exposes various information for single artifacts via templates, as mentioned in https://goreleaser.com/customization/templates/#single-artifact-extra-fields. I have binaries generated by `xgo` that need to be placed inside an archive. Binaries compiled by `xgo` use the Go naming convention for architectures, so `amd64`, `arm64`, etc.

I also instruct users to choose the correct file to download by using `uname -m`. This means I have to use replacements to make it match that convention (`x86_64`, `aarch64`, etc.).

This makes it impossible to use `{{.Arch}}` to select the correct binary.

### Describe the solution you'd like

I'd like there to be new template fields for non-replaced values, maybe something like `{{.OriginalArch}}`

### Describe alternatives you've considered

I could remove the replacements, but this would make it a lot harder for users to download the correct file for their machine. I could also use a template string with a bunch of if statements to convert it back, but that isn't a very good solution.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I've been thinking more and more about actually dropping the `replacements` in favor of something else, because it is, well, a bit weird.

Anyway, in your case, you can drop the `replacements` thing, and set your `archive.name_template` like this:

```yaml
archives:
  - name_template: >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}
  - 
  - 
  - "{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "linux" }}Linux_{{ .Arch }}"

```

**Comment by caarlos0** [comment]
refs https://github.com/goreleaser/goreleaser/pull/3589
