### ISSUE TITLE
Provide a way to rename files placed in archives

### ISSUE THREAD

**Issue by Arsen6331** [goreleaser/goreleaser#3594]
### Is your feature request related to a problem? Please describe.

I have files that have the name of the OS and architecture that I need placed in an archive, for example, `itgui-linux-amd64`. I'd like them to just be named `itgui`. This is easy to do with nFPM, but impossible with archives.

### Describe the solution you'd like

I'd like there to be a `filename` field that can change the name of the file

For example:

```yaml
files:
  - src: itgui-{{.Os}}-{{.Arch}}
    filename: itgui
```

### Describe alternatives you've considered

No alternatives

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
why are you naming your binaries like that? can you share your config? Its very unlikely you actually need it...

**Comment by Arsen6331** [comment]
I am not. I am using continuous integration to compile a Fyne app via `xgo`, and `xgo` names binaries like that when it compiles them. It uses a bash script that doesn't take any arguments or environment variables to change the names, so there's not much I can do about it.

**Comment by caarlos0** [comment]
then you should probably rename the files before running goreleaser instead...

**Comment by Arsen6331** [comment]
The issue is that there are four binaries for different architectures. I can't name them all `itgui`.

**Comment by caarlos0** [comment]
that's why goreleaser creates folder like `dist/linux_amd64_v1/itgui`.

the thing is: in the context of goreleaser, this feature request does not seem to make much sense, as goreleaser handles the binary name correctly.

there's also better ways to use CGO within goreleaser, check https://goreleaser.com/cookbooks/cgo-and-crosscompiling/?h=cgo

**Comment by caarlos0** [comment]
closing per previous comments...
