### ISSUE TITLE
goreleaser attempt to release an existing tag and fail

### ISSUE THREAD

**Issue by Lyndon-Li** [goreleaser/goreleaser#3609]
### What happened?

Due to the change in [this PR](https://github.com/goreleaser/goreleaser/pull/2377), when there is a pre-release, the command `git tag --points-at HEAD  --sort -version:refname` generates below result, from which goreleaser picks `v1.10.0-rc.2` to create the release. It is expected to pick `v1.10.0`, and `v1.10.0-rc.2` has been released:
```
git tag --points-at HEAD  --sort -version:refname
v1.10.0-rc.2
v1.10.0
```

### How can we reproduce this?

Release one pre-release, for example, `v1.10.0-rc.2`
Don't make any new commit so as to keep the HEAD unchanged
Create a GA release, for example, `v1.10.0`
[Result] The second release fails

### goreleaser version

```bash
1.13.1
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hmm, will see what I can do... as a workaround you can set `GORELEASER_CURRENT_TAG` environment variable to the version you want for this release...

**Comment by Lyndon-Li** [comment]
Thanks, the workaround should work, meanwhile please help to check if this problem can be fixed in any of the new releases.

**Comment by caarlos0** [comment]
it might not be possible to fix.

**Comment by caarlos0** [comment]
explaining: if I revert that commit, it'll break somewhere else... and it seems like git cant sort by multiple fields and does not take the semantic version fields into consideration (it seems).

what we might be able to do is add a config for the sorting, so its the user responsibility. 

But its more of a feature than a bug...

**Comment by Lyndon-Li** [comment]
This command `git tag --points-at HEAD  --sort=v:refname` could return the correct result in this scenario, but not sure if it meets others requirements.

**Comment by caarlos0** [comment]
another idea would be to use `git config --get tag.sort` if set, defaulting to the current behavior... so users could set it per repo... but I guess having it in the yaml is likely better. either way, will look into it tomorrow.
