### ISSUE TITLE
307 Moved Permanently (from a renamed repo)

### ISSUE THREAD

**Issue by tj** [goreleaser/goreleaser#362]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

Releasing after moving a repo to a new org (apex/gh-polls).

### Environment

Please paste the output of:

Using goreleaser version 0.31.1, commit 9882da4b5756308b44ed7a5d7d73fdb2c63cccd4, built at 2017-09-14T23:37:40Z

### Steps to Reproduce

Builds work, however it consistently fails with:

```
   • RELEASING TO GITHUB
   • creating or updating release repo=tj/gh-polls tag=v0.2.1
   • release updated           url=https://github.com/apex/gh-polls/releases/tag/v0.2.1
   • uploading to release      file=dist/gh-polls_0.2.1_linux_amd64.tar.gz name=gh-polls_0.2.1_linux_amd64.tar.gz
   • uploading to release      file=dist/gh-polls_0.2.1_linux_386.tar.gz name=gh-polls_0.2.1_linux_386.tar.gz
   • uploading to release      file=dist/gh-polls_0.2.1_windows_386.tar.gz name=gh-polls_0.2.1_windows_386.tar.gz
   • uploading to release      file=dist/gh-polls_0.2.1_darwin_386.tar.gz name=gh-polls_0.2.1_darwin_386.tar.gz
   • uploading to release      file=dist/gh-polls_0.2.1_windows_amd64.tar.gz name=gh-polls_0.2.1_windows_amd64.tar.gz
   • uploading to release      file=dist/gh-polls_0.2.1_darwin_amd64.tar.gz name=gh-polls_0.2.1_darwin_amd64.tar.gz
   • uploading to release      file=dist/gh-polls_0.2.1_checksums.txt name=gh-polls_0.2.1_checksums.txt
   ⨯ release failed            error=POST https://uploads.github.com/repos/tj/gh-polls/releases/7762741/assets?name=gh-polls_0.2.1_windows_386.tar.gz: 307 Moved Permanently []
```

Looks like it's still trying to POST to tj/gh-polls haha. No rush at all unless you know a quick fix, I'll try and check it out soon, bit of a weird edge-case I doubt many people would hit

**Comment by caarlos0** [comment]
hmmm, I think that if you change your remote url to the new one it should work (or change .goreleaser.yml if you have the repo specified there).

I'll try to take a look at it tonight anyway :D

**Comment by tj** [comment]
ahh right ok that makes sense haha, I didn't actually think of where it gets the url from. I'll try that

**Comment by tj** [comment]
sweet works, thanks man!

**Comment by caarlos0** [comment]
Nice :D
