### ISSUE TITLE
Error publishing to brew tap via workflows

### ISSUE THREAD

**Issue by arlomcwalter** [goreleaser/goreleaser#3620]
### What happened?

The workflow works fine, the formula is updated perfectly in the tap repository. However, using the default `tests` workflow provided by `brew tap-new`, an error causes the workflow to fail based on a `brew style` error. 

### How can we reproduce this?

[Here](https://github.com/arlomcwalter/homebrew-tap/blob/main/.github/workflows/tests.yml) is the workflow and [here](https://github.com/arlomcwalter/homebrew-tap/actions/runs/3616274888/jobs/6094069327#step:7:13) is an example of the failed run (ignore the correctable issues). I found [this](https://github.com/Homebrew/brew/issues/12040) issue on the official brew repo. It seems to suggest using OS.linux? etc instead but since I am using goreleaser, I'm not sure how I can achieve the same thing.

### goreleaser version

```bash
goreleaser version 1.13.1
commit: b0ffc7af05aa391b766e8e26f5ad5ec37c640d6e
built by: homebrew
goos: darwin
goarch: arm64

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
taps are not required to met `brew style`, so we don't particularly care about it.

I did spend some time not long ago (https://github.com/goreleaser/goreleaser/pull/3274) to fix most of the issues, but some of them (clearly) still remain...

**Comment by arlomcwalter** [comment]
thats perfectly reasonable, no worries. just wanted to make sure it wasn't either something i was doing wrong, or something that you were unaware of.
