### ISSUE TITLE
FYI: building Go modules via the proxy can use less code

### ISSUE THREAD

**Issue by mvdan** [goreleaser/goreleaser#3624]
### Is your feature request related to a problem? Please describe.

Right now, per https://goreleaser.com/cookbooks/build-go-modules/ and `gomod_proxy.go`, you roughly do:

* Create a temporary directory
* Drop a templated `main.go` file
* Drop a templated `go.mod` file with `require main_module_path git_tag`
* Copy `go.sum` from the original module
* Run `go mod tidy`
* Run `go build main_package_path`

You could accomplish the same with fewer steps. In particular, you don't need a `main.go` file, and you don't need to have a tidied module either. You could instead do:

* Create a temporary directory
* Run `go mod init test`, or use a template to get the same plain `go.mod` file
* Copy `go.sum` from the original module
* Run `go get main_module_path@git_tag`
* Run `go build main_package_path`

Beyond being one file and step less, this is also more powerful: you can use any VCS reference in `go get module@version`, including git commit hashes, git branch names, etc.

Also note that you don't strictly need to copy `go.sum`; it will still work without that step, and I reckon you don't lose any safety thanks to GOSUMDB. Though I guess you avoid a few network roundtrips if `go.sum` already has most of the hashes needed.

### Describe the solution you'd like

Just suggesting a perhaps slightly better way of implementing builds via the proxy :)

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
fixed in #3698
