### ISSUE TITLE
Failed to build for Scorecard linux_arm_6 build

### ISSUE THREAD

**Issue by laurentsimon** [goreleaser/goreleaser#3641]
### What happened?

We have been using GoReleaser Action for a while. Today we tried to cut a release but it failed: https://github.com/ossf/scorecard/actions/runs/3689942336

I'm not sure if it's a problem on our end or not. Wanted to have your input before digging deeper on our side. The error from the logs look as follows:
```shell
release failed after 9m44s               error=failed to build for linux_arm_6: exit status 2: # github.com/spdx/gordf/rdfloader/xmlreader
Error: /home/runner/go/pkg/mod/github.com/spdx/gordf@v0.0.0-20201111095634-7098f93598fb/rdfloader/xmlreader/xmlreader.go:213:27: WHITESPACE (untyped int constant 4294977024) overflows int

Error: The process '/opt/hostedtoolcache/goreleaser-action/1.13.1/x64/goreleaser' failed with exit code 1
```

### How can we reproduce this?

We used `goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757`.

It pulled:
```
Downloading https://github.com/goreleaser/goreleaser/releases/download/v1.13.1/goreleaser_Linux_x86_64.tar.gz
```

Not sure if this is enough information to reproduce, though.

### goreleaser version

```bash
goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757
https://github.com/goreleaser/goreleaser/releases/download/v1.13.1/goreleaser_Linux_x86_64.tar.gz
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laurentsimon** [comment]
We found the culprit, and it was on our side. Sorry for the noise. Closing.

**Comment by tuananh** [comment]
@laurentsimon how did you fix it?

**Comment by laurentsimon** [comment]
we had a dependency that did not support being built on ARM, due to integer size not being properly declared (`int` vs `int64`). It has nothing to do with goreleaser in the end :-)

**Comment by tuananh** [comment]
> we had a dependency that did not support being built on ARM, due to integer size not being properly declared (`int` vs `int64`). It has nothing to do with goreleaser in the end :-)

Thanks. I just found out the same thing. 

Is there any chance your dependency is gordf ? 😁

**Comment by laurentsimon** [comment]
yes it was!
