### ISSUE TITLE
json schema outdated for chocolatey(s) key

### ISSUE THREAD

**Issue by ixje** [goreleaser/goreleaser#3647]
### What happened?

The documentation mentions a schema that can be used
> `# yaml-language-server: $schema=https://goreleaser.com/static/schema.json`

If this is used in combination with the chocolatey options example from the [docs](https://goreleaser.com/customization/chocolatey/) then it will compain because the schema thinks the key is `chocolatey` not `chocolateys` (with `s`)

### How can we reproduce this?

Use the schema above, copy the chocolately options example (linked above) in `.goreleaser.yaml` see something like this
<img width="905" alt="image" src="https://user-images.githubusercontent.com/6625537/208070061-ce51487c-f04e-4b98-86f5-c6bcf0d30e87.png">

### goreleaser version

```bash
goreleaser version 1.13.1
commit: b0ffc7af05aa391b766e8e26f5ad5ec37c640d6e
built at: 2022-11-29T01:03:51Z
built by: goreleaser
goos: darwin
goarch: amd64
module version: v1.13.1, checksum: h1:9yTCn5UE3+1wNtVB3ybUAwjioLq79UyfGz8D+iPOcRk=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
good catch, thank you!
