### ISSUE TITLE
Scoop publishing is unable to find the windows build to generate the manifest

### ISSUE THREAD

**Issue by sheldonhull** [goreleaser/goreleaser#3648]
### What happened?

Trying to publish a cross-platform build that includes windows binaries to generate a Scoop manifest.

It can't find the windows builds.

```text
scoop requires a windows build and archive
```

### How can we reproduce this?

- [goreleaser config](https://github.com/DelineaXPM/dsv-cli/blob/main/.goreleaser.yaml)

Note that the goos for windows is there, but it's not a single build config.

It's not finding the windows asset for the Scoop manifest.

### goreleaser version

```bash
goreleaser/goreleaser@v1.13.1 (stored in the aqua.yml file in the repo)
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Might be delay till first weeks in jan for response if I don't see it as I'm stepping out for holidays. Will do best to respond but bear with any delay. Cheers.

**Comment by caarlos0** [comment]
that's because your archive format is `binary`, which is not supported in scoop. Error message should be clearer though.
