### ISSUE TITLE
Support for Github Enterprise

### ISSUE THREAD

**Issue by sklevenz** [goreleaser/goreleaser#365]
### Prerequisites

* [ y] Are you running the latest version?
* [ y] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

Goreleaser fails in "RELEASING TO GITHUB" if the github host is not github.com, which is the case for github enterprise. 
 
### Environment

OSX

Please paste the output of:

- `go version`
go version go1.9 darwin/amd64
- `uname -a`
Darwin myhost 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64 i386 iMac17,1 Darwin
- `goreleaser --debug`
  • RELEASING TO GITHUB
   • creating or updating release repo=skl/go-release-test tag=v0.1.0
   • release updated           url=
   ⨯ release failed            error=POST https://api.github.com/repos/d036242/go-release-test/releases: 401 Bad credentials []

### Steps to Reproduce

1. [First Step]
You need github enterprise (e.g. https://github.mycompany.com)
2. [Second Step]
Clone from github enterprise and try to release a repository. 

**Expected behavior:** [What you expected to happen]

It's expected that goreleaser releases to github enterprise.

**Actual behavior:** [What actually happened]

Goreleaser releases to github.com. 

Please take this as feature request. I am going to provide a pull request for this.

**Comment by caarlos0** [comment]
mind to try #361 ?

**Comment by sklevenz** [comment]
Yes. Unfortunately an 3rd url is required for the download in the brew template:

api url:  https://github.mycomp.com/api/v3
upload url: https://github.mycomp.com/api/v3/upload
download url: https://github.mycomp.com

**Comment by sklevenz** [comment]
Release v0.33.0 works wonderful. I think this can be closed now. Great work!

**Comment by caarlos0** [comment]
Nice, thanks for help testing @sklevenz 🎉
