### ISSUE TITLE
Release for specific endpoint

### ISSUE THREAD

**Issue by klautcomputing** [goreleaser/goreleaser#368]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you perform a search to see if this feature was already reported?

### Description

It would be awesome to be able to release for specific endpoint. I released to github already but would like to release the same version to homebrew and docker as well now. And that without having to issue a new tag and have to release again.

**Comment by andygrunwald** [comment]
@klautcomputing Isn't this the `--snapshot` parameter for? Or do i miss understand something here?
