### ISSUE TITLE
[PRO] [Feature request]: Announce: Passing TG Chat ID to config as string 

### ISSUE THREAD

**Issue by amelkikh** [goreleaser/goreleaser#3682]
### Is your feature request related to a problem? Please describe.

Hi!
Trying to pass value to `announce.telegram.chat_id` from env as like `{{ .Env.TELEGRAM_CHAT_ID }}` but got an error on checking config ` cannot unmarshal !!str `{{ .Env...` into int64`

### Describe the solution you'd like

I suggest to change `announce.telegram.chat_id` field type from `int64` to `string` to pass value from env for not share it in code.

### Describe alternatives you've considered

Use go templates with syntax like `{{ .Env.TELEGRAM_CHAT_ID }} | int64` 

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

With respect

**Comment by caarlos0** [comment]
ah, yes, that field is not templateable... will work on it for the next release!

thanks for the suggestion!
