### ISSUE TITLE
Add  feature to not create the release on any SCM in goreleaser release command, but still push docker image to the remote registry

### ISSUE THREAD

**Issue by maokitty** [goreleaser/goreleaser#3705]
### Is your feature request related to a problem? Please describe.

I am using goreleaser to package my program in multiple packages and archives, like nfpm/docker image/archives.  

When I have rewritten my code and want to test it both with binary package and docker image, I can use --snapshot param to generage all of them under dist director, but docker image cannot be sent to my remote registry at the same time and I do not want to release to SCM before test is over.

Here is the solution I found in the doc https://goreleaser.com/customization/release/, the config of disable under release can solve my problem by setting it to true (I am not sure it is a feature or not ... ) but it is not convenient as I should change the value to false after test is over to release them to SCM.

### Describe the solution you'd like

Add another parameter to the goreleaser release command, for example: goreleaser release --skip-scm-publish

### Describe alternatives you've considered

1. goreleaser release --push-docker-only , Developers can choose to push the image to their registry or not.
2. change release.disbale to be a template, so we can change it using the env variable.
3. multi-environment support for Goreleaser?

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I think its fair to make `release.disable` templateable.
