### ISSUE TITLE
Enhance auto update support

### ISSUE THREAD

**Issue by jenskueper** [goreleaser/goreleaser#3707]
### Is your feature request related to a problem? Please describe.

We use goreleaser together with overseer https://github.com/jpillora/overseer to update the binary on the fly. For this to work nicely (not having to download files containing checksums), it would be great if you could add additional tags or checksums to a file.

### Describe the solution you'd like

Most of the file storage support some sort of tagging:

-S3 https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html
- Azure https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-index-how-to?tabs=azure-portal
- GCP https://cloud.google.com/storage/docs/tags-and-labels

and for example AWS also supports checksum calculation: https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/

Would be nice if something like this would be support and configurable via the config.

### Describe alternatives you've considered

-

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
unfortunately this is a rather big endeavor, refs https://github.com/goreleaser/goreleaser/issues/3069

**Comment by jenskueper** [comment]
I solved this for now by doing the upload myself afterward in a second job of the CI pipeline. Used the AWS CLI where you can specify the parameter to generate a checksum.

**Comment by caarlos0** [comment]
ah cool, this issue still referenced at #3069, so hopefully it'll get fixed eventually... when it does, I'll ping here as well (or you can watch said issue)
