### ISSUE TITLE
Example for tagging Docker image including `{{ .Env.GO_VERSION }}` fails

### ISSUE THREAD

**Issue by echoix** [goreleaser/goreleaser#3709]
### What happened?

I'm trying to follow the examples in https://goreleaser.com/customization/docker/, that is the file https://github.com/goreleaser/goreleaser/blob/main/www/docs/customization/docker.md

If I adapt the following section from that page to my repo:
```yaml
    # Templates of the Docker image names.
    image_templates:
    - "myuser/myimage:latest"
    - "myuser/myimage:{{ .Tag }}"
    - "myuser/myimage:{{ .Tag }}-{{ .Env.GO_VERSION }}"
    - "myuser/myimage:v{{ .Major }}"
    - "gcr.io/myuser/myimage:latest"
```

I get the following error, that the env variable doesn't exist.

```
  • docker images
  ⨯ release failed after 1m24s               error=docker build failed: failed to execute image template 'ghcr.io/***/editorconfig-checker:{{ .Tag }}-{{ .Env.GO_VERSION }}': template: tmpl:1:54: executing "tmpl" at <.Env.GO_VERSION>: map has no entry for key "GO_VERSION"
Learn more at https://goreleaser.com/errors/docker-build
```

From the GitHub Actions actions/setup-go@v3, I see that there was a GOVERSION variable set there.

<details><summary>Part of the GitHub actions log output for actions/setup-go@v3</summary>
<p>

```
0s
Run actions/setup-go@v3
  with:
    go-version: >=1.19.5
    cache: true
    check-latest: false
    token: ***
Setup go version spec >=1.19.5
Found in cache @ /opt/hostedtoolcache/go/1.19.5/x64
Added go to the path
Successfully set up Go version >=1.19.5
/opt/hostedtoolcache/go/1.19.5/x64/bin/go env GOMODCACHE
/opt/hostedtoolcache/go/1.19.5/x64/bin/go env GOCACHE
/home/runner/go/pkg/mod
/home/runner/.cache/go-build
Cache is not found
go version go1.19.5 linux/amd64

go env
  GO111MODULE=""
  GOARCH="amd64"
  GOBIN=""
  GOCACHE="/home/runner/.cache/go-build"
  GOENV="/home/runner/.config/go/env"
  GOEXE=""
  GOEXPERIMENT=""
  GOFLAGS=""
  GOHOSTARCH="amd64"
  GOHOSTOS="linux"
  GOINSECURE=""
  GOMODCACHE="/home/runner/go/pkg/mod"
  GONOPROXY=""
  GONOSUMDB=""
  GOOS="linux"
  GOPATH="/home/runner/go"
  GOPRIVATE=""
  GOPROXY="https://proxy.golang.org,direct"
  GOROOT="/opt/hostedtoolcache/go/1.19.5/x64"
  GOSUMDB="sum.golang.org"
  GOTMPDIR=""
  GOTOOLDIR="/opt/hostedtoolcache/go/1.19.5/x64/pkg/tool/linux_amd64"
  GOVCS=""
  GOVERSION="go1.19.5"
  GCCGO="gccgo"
  GOAMD64="v1"
  AR="ar"
  CC="gcc"
  CXX="g++"
  CGO_ENABLED="1"
  GOMOD="/home/runner/work/editorconfig-checker/editorconfig-checker/go.mod"
  GOWORK=""
  CGO_CFLAGS="-g -O2"
  CGO_CPPFLAGS=""
  CGO_CXXFLAGS="-g -O2"
  CGO_FFLAGS="-g -O2"
  CGO_LDFLAGS="-g -O2"
  PKG_CONFIG="pkg-config"
  GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1646328567=/tmp/go-build -gno-record-gcc-switches"
```

</p>
</details>

So I tried using the variable `GOVERSION` (without the `_`) to have something like the following, and it doesn't work either.

```yaml
    # Templates of the Docker image names.
    image_templates:
    - "myuser/myimage:latest"
    - "myuser/myimage:{{ .Tag }}"
    - "myuser/myimage:{{ .Tag }}-{{ .Env.GOVERSION }}"
    - "myuser/myimage:v{{ .Major }}"
    - "gcr.io/myuser/myimage:latest"
```

By removing that offending tag, every other tag works and goreleaser is able to push the images. So it's really that example that is wrong.

I see by git blame that the example in the documentation wasn't recently changed, it's been the same for 4 years.
Are you able to run correctly the example in that documentation page?

### How can we reproduce this?

I'll share the repo, since it's a fork only to try out the CI configuration beforehand.
Commit in the repo (that had a tag): https://github.com/echoix/editorconfig-checker/commit/c944e141363da680b708df5ae89ea0cc5566a5f1
Action run: https://github.com/echoix/editorconfig-checker/actions/runs/3981084548/jobs/6824585649
Logs: [logs_69.zip](https://github.com/goreleaser/goreleaser/files/10475233/logs_69.zip)

### goreleaser version

```bash
gitpod /workspace/editorconfig-checker (dev/goreleaser) $ goreleaser --version 
goreleaser version 1.14.1
commit: 7be70934534b5c9798b6ab1b7b3e5c35df7e8b2e
built at: 2023-01-02T13:53:59Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.14.1, checksum: h1:b+cW4BSDL5Ii32scSX8IoXrnpwHIItXgZyMskBhNK8s=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I'm trying to work on setting up editorconfig-checker with GoReleaser in https://github.com/editorconfig-checker/editorconfig-checker/issues/204, and it's my first time playing with Go. Adding this feature will bump the project to v3, and the goal is to make it maintainable like any modern tool.

**Comment by caarlos0** [comment]
GO_VERSION is not set by goreleaser, its just an example... if you want to use it, you need to set it.

**Comment by echoix** [comment]
> GO_VERSION is not set by goreleaser, its just an example... if you want to use it, you need to set it.

Thanks a lot!
