### ISSUE TITLE
Project name is not evaluated for artifactory uploads

### ISSUE THREAD

**Issue by seb-lie** [goreleaser/goreleaser#3711]
### What happened?

We'd like to have the same `.goreleaser.yml` file for pre-releases and regular releases as they are almost identical. We tried to do this using the project name and the `.Prerelease` template. 

This works fine for most cases (brew formula, binary name..) but we noticed that the upload to an internal artifactory repo has the raw project string (not evaluated) in its path. This is why the brew formula fails. In the below example the upload happened to

```
https://artifacts.my-company.net/homebrew-binaries-local/brew/my_project{{ if .Prerelease }}-beta{{ end }}/1.2.3-beta1/my_project{{ if .Prerelease }}-beta{{ end }}_1.2.3-beta1_macOS_arm64.tar.gz
```
Instead of 

```
https://artifacts.my-company.net/homebrew-binaries-local/brew/my_project-beta/1.2.3-beta1/my_project-beta_1.2.3-beta1_macOS_arm64.tar.gz
```

### How can we reproduce this?

```
# .goreleaser.yml
project_name: my_project{{ if .Prerelease }}-beta{{ end }}

...

brews:
  - url_template: "https://artifacts.my-company.net/homebrew-binaries-local/brew/{{ .ProjectName }}/{{ .Version }}/{{ .ArtifactName }}"
```

### goreleaser version

```bash
goreleaser version 1.14.1
commit: 7be70934534b5c9798b6ab1b7b3e5c35df7e8b2e
built by: homebrew
goos: darwin
goarch: arm64

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
The `project_name` property cannot be templated, that's why it doesn't work.

**Comment by seb-lie** [comment]
Is there another workaround to create pre-releases and releases from the same `.goreleaser.yml` file?

**Comment by caarlos0** [comment]
maybe nightlies do the trick for you? https://goreleaser.com/customization/nightlies/
