### ISSUE TITLE
Scoop Autoupdate support

### ISSUE THREAD

**Issue by Xemdo** [goreleaser/goreleaser#3713]
### Is your feature request related to a problem? Please describe.

There doesn't seem to be support for Scoop's [Autoupdate feature](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#adding-autoupdate-to-a-manifest). The limitation in the code can be seen [here](https://github.com/goreleaser/goreleaser/blob/main/internal/pipe/scoop/scoop.go#L183).

### Describe the solution you'd like

Within the Scoop section of goreleaser.yml, you should be able to include information about autoupdating, which should use the same URLs generated by goreleaser for Scoop downloads.
An optional note should be available as well.

### Describe alternatives you've considered

To get around this currently I've found editing the json file in the Scoop bucket should work, but its not preferred as this has to be manually done every update.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
[this](https://github.com/goreleaser/goreleaser/compare/scoop-autoup?expand=1) is probably not correct, if you're on windows and want to test/PR needed changes, it'll be greatly appreciated.

**Comment by maidul98** [comment]
This will be really useful! Looking forward

**Comment by caarlos0** [comment]
can someone help review #3873?

**Comment by caarlos0** [comment]
according to [the docs](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate), it seems that the autoupdate is used to update the manifest itself, not the app... 

since the manifests are updated by goreleaser on every release anyway, I don't see the point... 🤔 


can you explain what you want to achieve with this feature @maidul98 / @Xemdo ?

**Comment by caarlos0** [comment]
closing as it doesn't seem to make much sense in the context of goreleaser.

**Comment by caarlos0** [comment]
yes, but the autoupdate in scoop only seems to make sense in their core repo? As it doesn't autoupdate the software itself, but rather the manifest when a new release is out... 

at least that's what I understood from reading their docs
