### ISSUE TITLE
Overrides depends fails - should be dependencies

### ISSUE THREAD

**Issue by maraino** [goreleaser/goreleaser#3721]
### What happened?

The last version of GoReleaser (1.14.1) fails if we add an override like this in the nfpms section:

```yaml
nfpms:
  - ...
    overrides:
      deb:
        depends:
          - some-package
```

The message displayed looks like this:

```
  ⨯ release failed after 0s                  error=yaml: unmarshal errors:
  line 127: field depends not found in type config.NFPMOverridables
```

Using `dependencies` instead of `depends` works as expected.

### How can we reproduce this?

Use `depends` as is documented at https://github.com/goreleaser/goreleaser/blob/c747445d0bdf3b6d7024c8d776df7da244e8d9af/www/docs/customization/nfpm.md?plain=1#L239-L252

### goreleaser version

```bash
$ goreleaser -v
goreleaser version 1.14.1
commit: 7be70934534b5c9798b6ab1b7b3e5c35df7e8b2e
built at: 2023-01-02T13:53:59Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.14.1, checksum: h1:b+cW4BSDL5Ii32scSX8IoXrnpwHIItXgZyMskBhNK8s=

https://goreleaser.com
root@42040088c796:/go/src/github.com/smallstep/step-kms-plugin# goreleaser --version
goreleaser version 1.14.1
commit: 7be70934534b5c9798b6ab1b7b3e5c35df7e8b2e
built at: 2023-01-02T13:53:59Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.14.1, checksum: h1:b+cW4BSDL5Ii32scSX8IoXrnpwHIItXgZyMskBhNK8s=

https://goreleaser.com
```

### GoReleaser Check

- [x] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

`goreleaser check` shows the same error, but I cannot submit this without checking that box, it is required:

```console
$ goreleaser check
  • loading config file                              file=.goreleaser.yml
  ⨯ command failed                                   error=yaml: unmarshal errors:
  line 127: field depends not found in type config.NFPMOverridables
  line 130: field depends not found in type config.NFPMOverridables
```

**Comment by caarlos0** [comment]
docs issue, fixed

thanks for noticing 🙏
