### ISSUE TITLE
goreleaser scm 403 error

### ISSUE THREAD

**Issue by ck1828** [goreleaser/goreleaser#3727]
### What happened?

I tried to use gorleeaser to publish releases but it fails at then end:
```
 github/gitlab/gitea releases
         • creating or updating release repo=comp-name/repo-name tag=v0.1.0
         • release updated           url=
   ⨯ release failed after 66.98s error=github/gitlab/gitea releases: failed to publish artifacts: POST https://github.com/repos/company-name/repo-name/releases: 403  []
Error: The process '/opt/hostedtoolcache/goreleaser-action/0.178.0/x64/goreleaser' failed with exit code 1
```

### How can we reproduce this?

I am using go version 1.19

### goreleaser version

```bash
used goreleaser latest and also tried with v0.178.0 and version<1
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
You probably are not setting the GitHub token, or it is invalid.

**Comment by ck1828** [comment]
It is a private repo, does that make any difference? I was able to use the same token from a public repo and use goreleaser it works without any errors. But when I try with this private repo I get this error. The repo doesn't have any LICENSE

**Comment by ck1828** [comment]
I see that the path is invalid in POST
`error=scm releases: failed to publish artifacts: could not release: POST https://github.com/repos/company-name/repo-name/releases: 403 ` 

The correct POST should be 
` https://github.com/company-name/repo-name/releases`
after github.com its getting unnecessarily appending with work repos and cannot POST the artifacts there

**Comment by ck1828** [comment]
can we release only via push to main or through PR also?

**Comment by caarlos0** [comment]
the token needs private repo access.

goreleaser only runs the entire thing against tags, so no, no prs.

please take the time to read through the docs: https://goreleaser.com

**Comment by ck1828** [comment]
I was able to run goreleaser without any errors on PR in another repo using same GITHUB Token

**Comment by caarlos0** [comment]
again, check your token permissions. Working in one repo does not mean it will work in all repos.


this is definitely an usage error.
