### ISSUE TITLE
Hook output is very noisy

### ISSUE THREAD

**Issue by alexjurkiewicz** [goreleaser/goreleaser#3741]
### What happened?

I use a custom hook to sign and notarize a MacOS binary:

```yaml
universal_binaries:
  - replace: true
    hooks:
      post:
        - cmd: script/mac-sign-notarize.sh {{ .Path }}
          output: true
```

I'd like to see output, as it prints information I'd like to see in our automated pipeline, like the notarization ID and request logs. But the output format includes all environment vars, making it:

1. Extremely verbose / hard to read
2. Includes some secret credentials, like AWS access key & session token

Example output:

```
    •   "ticketContents": [                          cmd=[script/mac-sign-notarize.sh dist/lsk-db-connect_darwin_all/lsk-db-connect] env=[PATH=...]
    •     {                                          cmd=[script/mac-sign-notarize.sh dist/lsk-db-connect_darwin_all/lsk-db-connect] env=[PATH=...]
    •       "path": "lsk-db-connect.zip/lsk-db-connect", cmd=[script/mac-sign-notarize.sh dist/lsk-db-connect_darwin_all/lsk-db-connect] env=[PATH=...]
    •       "digestAlgorithm": "SHA-256",            cmd=[script/mac-sign-notarize.sh dist/lsk-db-connect_darwin_all/lsk-db-connect] env=[PATH=...]
[...]
```

Is it possible for this output to not include `env` data unless `--debug` is specified?

### How can we reproduce this?

Set a lot of env vars and run a post-hook for `universal_binaries`

### goreleaser version

```bash
1.15.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
ooof, definitely a bug, thanks for reporting... will take a look

**Comment by alexjurkiewicz** [comment]
thank you! <3
