### ISSUE TITLE
Additional tags configured via `kos` is not getting published/pushed to registry

### ISSUE THREAD

**Issue by kameshsampath** [goreleaser/goreleaser#3744]
### What happened?

When we set the `tags` in `kos` configuration, I expect that all the list of tags are published and pushed to the container registry. Currently only `latest` tag is pushed

### How can we reproduce this?

Run the `goreleaser release --clean` using https://github.com/kameshsampath/go-hello-world/blob/goreleaser-ko/.goreleaser.yaml, you wil notice only `latest` tag being pushed to registry.

### goreleaser version

```bash
goreleaser version dev
goos: darwin
goarch: arm64
module version: v1.15.0, checksum: h1:qyb+u5SFBQgmOPW5peHcUX3GtWZM7n4oeYcXjqD3qD4=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by developer-guy** [comment]
I think we can close this one as we discussed in slack; you seem to define only [latest](https://github.com/kameshsampath/go-hello-world/blob/3467fe250a04c436652ed9bd9ff4d0ab7e19f675/.goreleaser.yaml#L25) tag for your build, due to that, ko only built the latest tag. In the following job, everything worked as we expected:

> _https://github.com/developer-guy/goreleaser-with-ko/actions/runs/4051420931/jobs/6969732420_

**Comment by developer-guy** [comment]
No worries, brother, I'm glad you look for issues like this; let's make GoReleaser better together.

**Comment by caarlos0** [comment]
this can be closed then, right?

**Comment by kameshsampath** [comment]
Yeah I cam closing this, thought I did that ;)
