### ISSUE TITLE
Goreleaser fails to sign RPM packages again on v1.15.0

### ISSUE THREAD

**Issue by ermirizio** [goreleaser/goreleaser#3745]
### What happened?

I have upgraded goreleaser to latest version v1.5.0 and I noticed all RPM check sign is failing across all our repositories.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/35462288/216148433-b18c5dd3-c397-4a92-a7d1-d4aec408a807.png">

### How can we reproduce this?

`goreleaser release --snapshot --rm-dist`

### goreleaser version

```bash
Not working: v1.15.0

Last one working: v1.14.1
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I think this could be related to old issue https://github.com/goreleaser/goreleaser/issues/2895

**Comment by caarlos0** [comment]
caused by https://github.com/goreleaser/nfpm/pull/609

we had a test that was failing for this case, for some reason, this time it didn't... and I thought they fixed the root issue... 

Obviously I was wrong.

Sorry for that, will revert and release a patch version!

**Comment by caarlos0** [comment]
@ermirizio are you using centos, if yes, which version?

**Comment by ermirizio** [comment]
> fwiw, this seems to be an issue in rpm actually
> 
> [rpm-software-management/rpm#2323](https://github.com/rpm-software-management/rpm/issues/2323)
> 
> can you check which version you're using?

Hi @caarlos0 sorry for the delay, we are using RPM binary from the following docker images:

- registry.access.redhat.com/ubi7/ubi ---> RPM 4.11.3
- registry.access.redhat.com/ubi7/ubi ---> RPM 4.14.3

Both of them failing by that time. 
However I can see now that the issue has been fixed by you 👍 . So I'm no longer able to reproduce this issue from my end.
I guess we can close this now?

**Comment by caarlos0** [comment]
Yes, for the time being at least!


Thanks!
