### ISSUE TITLE
Changelog generation blocks nightly builds (Pro)

### ISSUE THREAD

**Issue by ecordell** [goreleaser/goreleaser#3752]
### What happened?

Attempting to use the nightly feature, but the `github-native` changelog generator blocks the nightly build.

```sh
  ⨯ release failed after 8m17s               error=POST https://api.github.com/repos/authzed/spicedb/releases/generate-notes: 400 Missing tag_name parameter []
```

Failed logs here:
https://github.com/authzed/spicedb/actions/runs/4079089666/jobs/7030084300

Since publishing is skipped, I would expect the changelog generation step to be skipped as well, or at least not fail the build.

### How can we reproduce this?

Run a `--nightly` build with:
```
changelog:
  use: "github-native"
  sort: "asc"
```

### goreleaser version

```bash
1.15.1-pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
ah yes, the nightly tag does not exist yet... that's why it happens... I think we could default to `git` when its a nightly build 🤔

**Comment by caarlos0** [comment]
also worth noting: sorting is not supported by `github-native`.

**Comment by caarlos0** [comment]
will be fixed in the next patch release

**Comment by ecordell** [comment]
@caarlos0 I see 1.15.2 is out, but I don't see any commits related to this issue - is it fixed and I just missed it?

**Comment by caarlos0** [comment]
Hey! It's there: https://github.com/goreleaser/goreleaser-pro/releases/tag/v1.15.2-pro

First commit, "fallback to git on nightly"
