### ISSUE TITLE
No longer possible to include artifacts.json in release?

### ISSUE THREAD

**Issue by fiws** [goreleaser/goreleaser#3755]
### What happened?

I was previously including the [artifacts.json in my GitHub releases](https://github.com/minepkg/minepkg/actions/runs/3356135674/jobs/5560964244#step:7:57). 

It seems that the artifacts.json file is [no longer being generated before the release](https://github.com/minepkg/minepkg/actions/runs/3979627865/jobs/6822188801#step:7:72), leading to my publish step failing. This was [changed in v1.13](https://github.com/goreleaser/goreleaser/commit/5eb1e4ad0d41c6ee06db34183689a42e02a77fe0#diff-907bfb94a8c2367197d5b3de95c34ecd5cdab2944988165c644bd985722a3c56)

Is there a way to get the old behaviour back? Can i somehow add the artifacts.json to my release?

### Use case

I'm using the `artifacts.json` in a script, that installs my app. It fetches the latest release from github and parses the json to be able to select the right file to download (correct os and arch). I used to rely on the filename but the [goreleaser docs](https://goreleaser.com/customization/build/#a-note-about-folder-names-inside-dist) motivated me to switch to parsing the artifacts.json.
I don't have to store my own files, or build a big api by just storing the artifacts.json in the github release and parsing that. I also thought it might be nice for 3rd party tools that wanna automate installing my app.

### How can we reproduce this?

It's the default behaviour.

Include this
```
release:
  extra_files:
    - glob: ./dist/artifacts.json
    - glob: ./dist/metadata.json
```

to get a failed build.

### goreleaser version

```bash
goreleaser version dev
goos: linux
goarch: amd64
module version: v1.14.1, checksum: h1:b+cW4BSDL5Ii32scSX8IoXrnpwHIItXgZyMskBhNK8s=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Originally posted on discord: https://discord.com/channels/890434333251362866/1066703728649977925

**Comment by caarlos0** [comment]
its working as intended, this file was never promised to be available to be added to the release.

you can store that file in the github action cache, though, which should help in your particular case.

**Comment by fiws** [comment]
Only workaround i see is to manually amend it to the release. I don't get how caching it would help.

**Comment by caarlos0** [comment]
hmm yes, you're right.. unfortunately that change is needed for other features (in pro only for now), so I can't undo it... 

that said, another possible approach: I don't know which files your script uses, but you can probably get around by specifying the name template of them (e.g. `archives.*.name_template`), so you are not subject to possible default changes, and so you can have the format hardcoded in your scripts and everything should be fine. This is what the goreleaser install script does, btw.

**Comment by caarlos0** [comment]
forgot the links:

- https://github.com/goreleaser/goreleaser/blob/618a3694ad018d3b5d7fa67f8252aef055edbc05/.goreleaser.yaml#L136
- https://github.com/goreleaser/goreleaser/blob/618a3694ad018d3b5d7fa67f8252aef055edbc05/www/docs/static/run
