### ISSUE TITLE
Add Git Commit Message Guidelines to CONTRIBUTING.md

### ISSUE THREAD

**Issue by jorinvo** [goreleaser/goreleaser#377]
I really like this section Hugo has which describes the format to use for commit messages:
https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#git-commit-message-guidelines

This would allow for generating a more useful changelog for the releases.
Would you be interested in adding this? Any specific format perferences?

**Comment by caarlos0** [comment]
@jorinvo Yes!

I was thinking about it some days ago.

I sometimes commit with really bad messages, a way of enforcing this would also be neat...

**Comment by jorinvo** [comment]
@caarlos0 I'm afraid we can't really enforce it. All we can do is having one place and point to it whenever we see a not so nice commit message.

Should we just go with the same conventions as Hugo or do you have any other preferences?

**Comment by caarlos0** [comment]
Maybe using gitcop? https://gitcop.com

**Comment by jorinvo** [comment]
@caarlos0 nice! That looks way better! Can give it a try. I can do the setup if you like.

**Comment by caarlos0** [comment]
Yeah, feel free to do it 🗡 

I saw it here: https://github.com/pagarme/pilot/pull/187#issuecomment-324526348

It's in portuguese, but basically, the action should either be add, remove, refactor, move, bump, update or release, which I think is fine, if agree we can copy it =D

**Comment by jorinvo** [comment]
@caarlos0 I cannot add the webhook. 
Could you add https://hooks.gitcop.com/github
here: https://github.com/goreleaser/goreleaser/settings/hooks/new 
Also need a secret. I'll send it to you in Slack ok?

**Comment by caarlos0** [comment]
@jorinvo ok 🍻

**Comment by jorinvo** [comment]
It is set up. I merged their suggested list with the one you listed above @caarlos0.
Now looks like this:
![screen shot 2017-10-01 at 19 54 26](https://user-images.githubusercontent.com/738978/31057411-8331a9a2-a6e2-11e7-8efe-cae1a6622f25.png)

**Comment by jorinvo** [comment]
I will also add this to CONTRIBUTING.md

**Comment by caarlos0** [comment]
Awesome 🎉
