### ISSUE TITLE
dockers extra_files does not support Windows folders.

### ISSUE THREAD

**Issue by omarhachach** [goreleaser/goreleaser#3776]
### What happened?

When using extra files like this, with a sub-folder:
```YAML
dockers:
  - id: test
    image_templates:
      - "test"
    extra_files:
      - "files/images"
```
It will correctly read and include all files. But it will create a double folder structure. As seen from the debug info:
```
• copying file                  dst=dist\goreleaserdocker2020978553\files\images\ranks src=files\images\files\images\ranks
```
This is due to: 
https://github.com/goreleaser/goreleaser/blob/a3d3ab2058bceb4041087beab0178f1e0ea940b1/internal/gio/copy.go#L30 
Where it removes the extra subdirectory (the `src`) from the `path`. This is a wrong assumption on windows, as it uses backslashes as folder delimiters.
I do not think this is a user error, as it should correctly convert between the two, and so the same config can be used on both Windows and *nix. (Locally and CI for example).
 
Running the above config with `files\images` works as expected on windows. But then the issue just appears on non-Windows machines.

### How can we reproduce this?

See above

### goreleaser version

```bash
goreleaser version dev
goos: windows
goarch: amd64
module version: v1.15.1, checksum: h1:GWI+6mpdyEsGU0rEtKvTA7/10L9JZhkHPh9wqXg7kSk=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

This probably applies to other extra_files fields in other configuration areas. I have not checked it though. Changing the gio package to automatically convert path strings from forward to backslash on windows should fix it everywhere.

Or for a more general solution sanitize all filepaths to use forward slashes, but that seems to be a bigger undertaking.

**Comment by caarlos0** [comment]
I don't have a windows box to test... but we should probably test goreleaser on windows too.

anyway, will PR converting to forward slashes inside `gio.Copy`.

**Comment by caarlos0** [comment]
thanks for bringing this up, btw :)
