### ISSUE TITLE
Automatically update docs

### ISSUE THREAD

**Issue by jorinvo** [goreleaser/goreleaser#378]
I saw that there is a `make static` command. Maybe we can run it on Travis CI, every time we release a new tag and automatically push a commit to the docs repo?

**Comment by caarlos0** [comment]
right now we can't... we are using a "custom" version of static while some changes are not made into the "main" one..

surely can be done later :)

**Comment by jorinvo** [comment]
Ok, didn't know that. Guess it's easier to just wait with this instead of using our fork on Travis.

**Comment by caarlos0** [comment]
probably, will try to help @tj with it during this week to make this happen as earlier as possible :)

**Comment by caarlos0** [comment]
refs https://github.com/apex/static/issues/22

**Comment by caarlos0** [comment]
closed too early

**Comment by caarlos0** [comment]
first fully-automated release: https://travis-ci.org/goreleaser/goreleaser/builds/312190980
