### ISSUE TITLE
pipe: ko: ability to set `.ko.yaml` file path

### ISSUE THREAD

**Issue by Dentrax** [goreleaser/goreleaser#3781]
### Is your feature request related to a problem? Please describe.

`ko` by default preserves `.ko.yaml` file at current directory. Maintaining both of `.ko.yaml` file and `kos:` configs at the same time would be resulting in slight config-drift between current `ko` configs. (Asserting whether both configs are equal is hard, and may different, which I definitely do NOT want to.) So my idea is to respect `.ko.yaml` by setting from goreleaser config.

### Describe the solution you'd like

https://goreleaser.com/customization/ko

Add a new `config: (string)` field. We should NOT preserve `./.ko.yaml` file by default since it would be a breaking change.

If config path is set, other fields still have higher precedence, so we can override the values. 

### Describe alternatives you've considered

`-`

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I'm volunteer to implement this; feel free to assign to me.

**Comment by caarlos0** [comment]
nice, go for it!

**Comment by Dentrax** [comment]
Hey! Yes, I can say this does still make sense to me. I couldn't find much time to get into it. :/

**Comment by caarlos0** [comment]
ight, will keep it open, let me know if you need any help :)

**Comment by caarlos0** [comment]
closing as not enough interest
