### ISSUE TITLE
gpg: signing failed: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by vsubram95** [goreleaser/goreleaser#3782]
### What happened?

i try to sign my artifacts with goreleaser but i faced an issue with step signing artifacts

### How can we reproduce this?

https://github.com/lendi-au/terraform-provider-snyk.
More specifically - https://github.com/lendi-au/terraform-provider-snyk/actions/runs/4169458737/jobs/7217440703 

### goreleaser version

```bash
v1.15.2
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I was able to look at this issue before asking here https://github.com/goreleaser/goreleaser/issues/1966. But is creating a new key is the only solution? It seems wrong. Just want to understand why it failed in the first place(We did not have any code changes)? It would be great help if you can help have a look at it in indentifying the root cause?

**Comment by caarlos0** [comment]
mind sharing what the solution was?
