### ISSUE TITLE
Reports DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for newer Go versions

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [goreleaser/goreleaser#3787]
### What happened?

Tried to build something for darwin/arm64 using Go 1.20

### How can we reproduce this?

Try to build anything for darwin/arm64 using go 1.20

### goreleaser version

```bash
v1.2.5 but the code is obviously broke on `master` too
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

https://github.com/goreleaser/goreleaser/issues/2412 again

These regexps in `targets.go` are very brittle:
```go
	go116re = regexp.MustCompile(`go version go1.1[6-9]`)
	go117re = regexp.MustCompile(`go version go1.1[7-9]`)
```

It'd make more sense to parse these using one of the many semver libraries out there (or even just try and grab the major/minor out of it) and do a numeric comparison I think?

**Comment by caarlos0** [comment]
goreleaser latest is v1.15.2, and those checks were removed on v1.7.0.

**Comment by mgabeler-lee-6rs** [comment]
Argh, I swear I checked the code before submitting this, sorry :(

**Comment by caarlos0** [comment]
no worries :)
