### ISSUE TITLE
scoop depends support

### ISSUE THREAD

**Issue by howieyuen** [goreleaser/goreleaser#3796]
### Is your feature request related to a problem? Please describe.

I'd like to push my project Kusion, which depends on KCLVM. I found `brew` supports this, but scoop not.

### Describe the solution you'd like

add `depends` field like brew does.

scoop dependencies wiki: https://github.com/ScoopInstaller/Scoop/wiki/Dependencies
scoop dependencies example: https://github.com/ScoopInstaller/Main/blob/6c5c36920155f7c577272f599a8b4ad857118b9c/bucket/git-tfs.json#L6

### Describe alternatives you've considered

None

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
check #3797
