### ISSUE TITLE
Improve the "Quick start" documentation to avoid run failure after goreleaser init

### ISSUE THREAD

**Issue by mapkon** [goreleaser/goreleaser#3825]
### Is your feature request related to a problem? Please describe.

The quick start documentation [here](https://goreleaser.com/quick-start/) implies that after running `goreleaser init`, `goreleaser release --snapshot --clean` should succeed.

However, `goreleaser release --snapshot --clean` invocation ends in an error:

```error=couldn't guess project_name, please add it to your config```

This is because the default generated `.goreleaser.yaml` does not have a `project_name` name set in the yaml file. 

Adding the `project_name` makes the run to succeed.

### Describe the solution you'd like

There are two options:

- Add the `project_name` attribute to the generated yaml file when the `goreleaser init` is run
- Add an extra step in the documentation asking the user to set the `project_name` attribute

### Describe alternatives you've considered

I added the `project_name` attribute myself and it worked, but had to dig around for what's possibly wrong since the Quick start does not mention it.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
oof, good find, will fix this right away!

**Comment by mapkon** [comment]
Thank you for the quick turnaround on this. Appreciate it 😍
