### ISSUE TITLE
Custom publishing with archiver type of `binary`

### ISSUE THREAD

**Issue by lrstanley** [goreleaser/goreleaser#3833]
### What happened?

We generate binary-only artifacts using:
```yaml
archives:
  - format: binary
```

Thus, the files on disk would look something like this:
![](https://cdn.liam.sh/share/2023/03/CDViewer_i76Fjfx6gN.png)

We would also like to take advantage of custom publishing to Nexus, where we upload just the binaries, but not archives. However, as stated in the documentation, when using `binary` archive format, these aren't saved on disk with the appropriate name:

> The `name_template` option will not reflect the filenames under the dist folder if the format is `binary`. The template will be applied only where the binaries are uploaded (e.g. GitHub releases).

However, even with no `name_template` (using the default name template), we wouldn't be able to use custom publishing, as the variables accessible under [Custom Publishing](https://goreleaser.com/customization/publishers/#variables) are actually incorrect. For example, `ArtifactName` would show as `terraform-provider-uploader_linux_amd64`, however, on disk, it's still `terraform-provider-uploader` (thus classifying this as a bug).

Normally, the above wouldn't be much of an issue, as we could theoretically just suffix those items with the `Os`, `Arch`, and `Arm` variables as part of the custom publishing logic. However, as the publishing scripts are used for all files, not just binaries, that would lead to checksum and signature files to also have the suffix, which we don't want.

### How can we reproduce this?

The primary portions of the config that are important for reproduction are:

```yaml
# [...]

archives:
  - format: binary

publishers:
- name: nexus
  cmd: >-
    curl -k -u "{{ .Env.NEXUS_USERNAME }}:{{ .Env.NEXUS_PASSWORD }}"
      -X POST
      -H "Accept: application/json"
      -H "Content-Type: multipart/form-data"
      "https://nexus.somedomain.com/service/rest/v1/components?repository=some-local-golang-repo"
      -F "raw.directory={{ .Env.PROJECT }}/{{ .ProjectName }}/{{ .Version }}"
      -F "raw.asset1=@{{ .ArtifactName }};type=application/x-executable"
      -F "raw.asset1.filename={{ .ArtifactName }}"
  dir: "{{ dir .ArtifactPath }}"
```

### goreleaser version

![](https://cdn.liam.sh/share/2023/03/CDViewer_o5Epw0POoo.png)
(pulled from `go install` with `@latest` just a few minutes ago)

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I am not sure what the best approach to solve this is (or if it easily can be?). A few thoughts:

1. Change `The template will be applied only where the binaries are uploaded` to no longer be the case. I assume this has other implications, however, making it not the best option.
2. Change the logic so when publishers are invoked, the `ArtifactName` parameters that are passed in don't use name template if they are of type binary.
3. Add additional variables into the custom publisher that allows users to determine the `type` being passed in. For example, `Signature`, `Checksum`, `Archive`, `Binary`, much like is currently written to the `artifacts.json` file.

**Comment by caarlos0** [comment]
changing that behavior would be a breaking change for someone for sure.

an alternative idea: adding `filepath.Base` as a template function, so you could:

```yaml
# [...]

archives:
  - format: binary

publishers:
- name: nexus
  cmd: >-
    curl -k -u "{{ .Env.NEXUS_USERNAME }}:{{ .Env.NEXUS_PASSWORD }}"
      -X POST
      -H "Accept: application/json"
      -H "Content-Type: multipart/form-data"
      "https://nexus.somedomain.com/service/rest/v1/components?repository=some-local-golang-repo"
      -F "raw.directory={{ .Env.PROJECT }}/{{ .ProjectName }}/{{ .Version }}"
      -F "raw.asset1=@{{ base .ArtifactNamePath }};type=application/x-executable"
      -F "raw.asset1.filename={{ base .ArtifactPath }}"
  dir: "{{ dir .ArtifactPath }}"
```

would that work? wdyt?

**Comment by lrstanley** [comment]
Just tested `base`, and that should work perfectly. Appreciate the quick turnaround!

**Comment by caarlos0** [comment]
Awesome, thanks for reporting 🙏
