### ISSUE TITLE
Goreleaser erroneously skipping darwin/arm64 and windows/arm64 under Go 1.20

### ISSUE THREAD

**Issue by alecthomas** [goreleaser/goreleaser#3835]
### What happened?

I upgraded Go to 1.20 in a project and goreleaser failed to build darwin/arm64 and windows/arm64 artefacts, reporting:

```
      • building binaries
         • DEPRECATED: skipped windows/arm64 build on Go < 1.17 for compatibility, check https://goreleaser.com/deprecations/#builds-for-windowsarm64 for more info.
         • DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
```

[Here's](https://github.com/cashapp/protosync/actions/runs/4329132576/jobs/7559475552) the GHA log.

Downgrading Go to 1.19.5 fixed it. [Here's](https://github.com/cashapp/protosync/actions/runs/4329950959/jobs/7560847294) the working GHA log.

### How can we reproduce this?

Clone v0.5.3 of https://github.com/cashapp/protosync and run `goreleaser release --snapshot --skip-publish --rm-dist` with Go 1.20

### goreleaser version

```bash
goreleaser version 0.184.0
commit: 01fa7a68276f7191773bd1db3ca16140dc71e575
built at: 2021-11-01T12:31:43Z
built by: goreleaser
module version: v0.184.0, checksum: h1:j9tP9sKIVm67TjCEdbinlRxw/Jc06oALg9gEzBt+14o=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
You're using a very old version of goreleaser, please upgrade.

**Comment by alecthomas** [comment]
Aaah, sorry 🤦 - I was still on 0.x and the package installer Hermit won't do a major version upgrade unless explicitly requested, so it wouldn't jump to 1.x.
