### ISSUE TITLE
not working with empty go modules

### ISSUE THREAD

**Issue by mabels** [goreleaser/goreleaser#3836]
### What happened?

I have a very small/simple module with does not have any external references.
I used a working configuration from an other project but this fails:
https://github.com/mabels/expose-oidc/actions/runs/4338117849/jobs/7574578704
```
⨯ release failed after 0s                  error=hook failed: go mod download: exit status 2; output: go: unknown subcommand "mod"
```
then i removed the hook and:
https://github.com/mabels/expose-oidc/actions/runs/4338125182/jobs/7574591210
```
⨯ release failed after 0s                  error=failed to get module path: exit status 2: flag provided but not defined: -m
```
Is the any hope to fix this?

thx

meno

### How can we reproduce this?

use this project:
https://github.com/mabels/expose-oidc

### goreleaser version

```bash
1.15.2
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
It doesn't work because you're using go 1.2.

https://twitter.com/caarlos0/status/1631635896393932801
