### ISSUE TITLE
Allow for pre-release option

### ISSUE THREAD

**Issue by mattstratton** [goreleaser/goreleaser#384]
### Prerequisites

* [x ] Are you running the latest version?
* [x ] Did you perform a search to see if this problem was already reported?

### Description

It's great to have the config flag for `draft`...it would be useful to be also able to set a release as a "prerelease" in github :)

**Comment by jorinvo** [comment]
Good idea @mattstratton! I will add an option `release.prerelease: true`.

**Comment by caarlos0** [comment]
We may also use this in goreleaser itself.

I have in my mental backlog that the script to get the latest version of goreleaser may fail during a release, because the release may be there but the assets aren't uploaded yet...

This would help fix that I guess :)
