### ISSUE TITLE
scoop.sh App Manifest Generation

### ISSUE THREAD

**Issue by Southclaws** [goreleaser/goreleaser#387]
### Prerequisites

* [x] Did you perform a search to see if this suggestion already existed?
* [x] Do you think GoReleaser is awesome?

### Description

Hi! Absolutely loving GoReleaser so far! I actually found the tool from [this blog post](https://medium.com/from-the-couch/adventures-in-go-ba217c29b51d) which talked about cross-platform deployment and installation! Great, just what I needed, it builds .deb and .rpm, does homebrew, everything except... Windows!

So, I took a look at scoop.sh and really like how minimal it is. I think, since GoReleaser already has my GitHub token for the release creation why not allow it to generate a scoop.sh [App Manifest](https://github.com/lukesampson/scoop/wiki/App-Manifests) and push it to a specified [Bucket](https://github.com/lukesampson/scoop/wiki/Buckets)?

I could possibly take a crack at this myself in a few days if the maintainer(s) are busy.

Let me know your thoughts! I did a quick search for scoop.sh in the issues and found #131 but I think scoop.sh is a nice minimal complement to Chocolatey and the implementation would be super simple from what I can see (generate json>push to repo>done!)

**Comment by caarlos0** [comment]
Scoop seems awesome!

I don't have a windows machine to test all that, unfortunately. I can though help/guide you if are willing to work on this :D

**Comment by Southclaws** [comment]
Alright then, since I have a windows machine I'll have a crack at this
tomorrow or Friday hopefully!

**Comment by caarlos0** [comment]
Nice, thanks @Southclaws =D

lemme know if you need anything, you can also join goreleaser on the gophers slack :)

**Comment by Southclaws** [comment]
Working on this in https://github.com/Southclaws/goreleaser

I'm basically copying the Brew pipeline as it's pretty much the same process:

- Generate a file based on yaml loaded into `ctx.Config`
- Push that file to a repo the user has access to

**Comment by Southclaws** [comment]
I'm wondering what's the best way to get the binary URLs from the GitHub release pipeline so I can add those URLs as binary downloads for the scoop manifest: https://github.com/Southclaws/goreleaser/blob/master/pipeline/scoop/scoop.go#L83

**Comment by jorinvo** [comment]
@Southclaws do I understand it correctly, scoop needs an URL directly to a binary?

**Comment by Southclaws** [comment]
Yes, but it works with a zipped binary too. I have an example here: https://github.com/Southclaws/scoops/blob/master/sampctl.json which uses the URL of a GoReleaser release.

`url` and `bin` can also be either strings or arrays of strings.

I guess generating the URL would work, I don't expect GitHub to change the URL structure any time soon. Something like this should work: `https://github.com/{user}/{repo}/releases/download/{version}/{project_name}_{version}_windows_{arch}.tar.gz`

**Comment by jorinvo** [comment]
Yes, that looks good. Maybe you need to also make the format variable since it can also be `zip`. When downloading from that URL you need to make sure to follow redirects. With curl it is `curl -L`, not sure how to do for Windows. All variables you can get from the `Config`. `user` and `repo` can be used from the `release` config. I think it's best if  you generate that url in your pipeline. Can still refactor if we need the same one in other places later. Maybe you should base it on `ctx.Config.GitHubURLs.Upload`.

**Comment by caarlos0** [comment]
@Southclaws you can take a look at the brew template, as it has those situations covered already (as far as I remember)

**Comment by Southclaws** [comment]
I'm picking this up again after a busy few weeks 👍 

Is there any nice way I can smoke-test this without actually triggering releases to a live repo? Like, see the generated files? I noticed there is `--skip-publish` but that completely removes things like brew from the process.

I have an open PR for this too: #427

**Comment by caarlos0** [comment]
@Southclaws `--snapshot` should do the job :)

**Comment by caarlos0** [comment]
or `--skip-validate --skip-publish``

**Comment by Southclaws** [comment]
Thanks!

It's going well so far, it's generating builds! 🎉 

https://github.com/Southclaws/scoops/commits/master/sampctl.json?author=goreleaserbot

**Comment by caarlos0** [comment]
this is done!

thanks @Southclaws !
