### ISSUE TITLE
brew: skip upload on backports

### ISSUE THREAD

**Issue by jzelinskie** [goreleaser/goreleaser#3886]
### Is your feature request related to a problem? Please describe.

Goreleaser only support skipping uploads to brew if the version is a pre-release. Backport releases will overwrite the existing latest stable release.

For example, if v2.0.0 is in the existing Formula, but you need to cut a release for v1.0.1 with a security fix, goreleaser will happily overwrite the Formula v2.0.0 with v1.0.1 because it is more recent.

### Describe the solution you'd like

In addition to the following branch, there could be a conditional to perform a network request to determine if the version being published is older than what is already released:

https://github.com/goreleaser/goreleaser/blob/7229a0dab06076c844a298ab5de6372a0b2971e6/internal/pipe/brew/brew.go#L124-L126

This might not be possible for all scenarios, as I believe Taps are just git repositories -- but in practice, I've never seen one that isn't hosted on GitHub, so GitHub URLs are probably a safe bet.

### Describe alternatives you've considered

- Today, we are avoiding backports or creating builds for them manually.
- #3485 might be a reasonable compromise

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
ability to PR is on main, feel free to test, will be released in the coming days.


will close this one, feel free to reopen/ping if needed :)

**Comment by jzelinskie** [comment]
Hey, sorry to bump this, but what about fury?

**Comment by caarlos0** [comment]
I think fury will keep both versions, although I haven't tested that.

If not, you could create a backports repo and use the `fury.skip` templating to publish to the right one (e.g. something like `{{ with .Major }}false{{ else }}true{{ end }}`)
