### ISSUE TITLE
Draft release is published to brew but not scoop

### ISSUE THREAD

**Issue by sweatybridge** [goreleaser/goreleaser#3887]
### What happened?

We have a [workflow](https://github.com/supabase/cli/blob/main/.goreleaser.yml) where a GitHub draft release is created to upload binaries. Unfortunately with this setup, our package is published inconsistently because the brew pipe is run but the scoop pipe is [skipped](https://github.com/goreleaser/goreleaser/blob/main/internal/pipe/scoop/scoop.go#L142).

It seems like scoop is the only packager that skips draft release. Would it be possible to remove this check for consistency with other packagers?

### How can we reproduce this?

see example https://github.com/supabase/cli/actions/runs/4496168465/jobs/7910578199#step:5:90

### goreleaser version

```bash
latest
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
oh, yes, they should all behave the same... I'll look into why that check was added, not sure which of the 2 behaviors is the correct one...

**Comment by sweatybridge** [comment]
Thank you for the quick turnaround!

**Comment by jkergal** [comment]
Scoop bucket is still 1.40.1... When will it be updated? :/
