### ISSUE TITLE
Add powershell completions to scoops

### ISSUE THREAD

**Issue by nipsarejusttittips** [goreleaser/goreleaser#3906]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

cobra just added powershell completions https://github.com/spf13/cobra/pull/1916

It'd be awesome to package them up into the scoops?

### Describe alternatives you've considered

none so far

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
it seems scoop doesn't support it, unfortunately....

https://github.com/ScoopInstaller/Scoop/issues/3247

**Comment by caarlos0** [comment]
will close this, the issue is open on scoop for 4 years and with no comments...
