### ISSUE TITLE
Release as pre-release first

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#391]
check https://github.com/goreleaser/goreleaser/issues/384#issuecomment-334471245

**Comment by jorinvo** [comment]
To make sure I understood this correctly, we should upload a release as `prerelease` first, then after everything is up, we change uncheck the `prerelease` checkbox manually?

**Comment by caarlos0** [comment]
that was what I was thinking... but let's let the idea mature for a while :)

**Comment by mattstratton** [comment]
To be honest, I'd prefer if this was configurable (if you look at the github release providers in both travis and appveyoer, they let you set it as a flag).

**Comment by mattstratton** [comment]
Oh! I totally misread this issue - you’re talking about this project itself. I just saw the PR that added this functionality. Thanks!

**Comment by caarlos0** [comment]
I think we can keep going as-is. If it turns into a problem we can always change it later.

Closing for now!
