### ISSUE TITLE
Add support for npm

### ISSUE THREAD

**Issue by colm-quinn** [goreleaser/goreleaser#3914]
### Is your feature request related to a problem? Please describe.

We're interesting in releasing some of our GoReleaser packaged binaries through npm, to improve the tooling experience for our frontend developer customers.

### Describe the solution you'd like

Similar to the [Chocolately packages](https://goreleaser.com/customization/chocolatey/) support, we would like to configure Goreleaser to publish directly to npm.

### Describe alternatives you've considered

There is a workaround in https://blog.xendit.engineer/how-we-repurposed-npm-to-publish-and-distribute-our-go-binaries-for-internal-cli-23981b80911b showing how to do this as part of a build chain, but we would prefer a pipeline that was fully driven by GoReleaser.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
this won't install completions, man pages, etc... honestly seems too hacky for me to implement it natively.

that say, you could probably implement this in your pipeline using custom publishers:

https://goreleaser.com/customization/publishers/

e.g.: template files the package.json and postinstall.js, and run `npm etc...` 


all that said, ["yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion though!
