### ISSUE TITLE
Provide ability to update title of release

### ISSUE THREAD

**Issue by mattstratton** [goreleaser/goreleaser#392]
Since I have a multiple-step release process, I would like to have the ability to tell `goreleaser` to not update the description of the release.

To help understand what I'm talking about, here's what's happening - I have builds that run on both travis and appveyor (travis builds my darwin and linux binaries, and appveyor builds the nuget and msi's).

The problem is that first appveyor creates the initial release, using the description I provide. Since appveyor finishes before travis (since I added fpm to it), the description and title of the release changes.

Ideally, what I really want to do is run my cli tool locally to create the release, then push it up to travis/appveyor, etc, which will just deploy the files. I would be content with having the ability to customize both the release description and title in goreleaser, however :)

(I have edited the title of this issue as I think that using the `--release-notes` flag solves for the description issue)

**Comment by jorinvo** [comment]
So maybe it would be enough to provide an option to skip setting any 
release note - `skipnote: true`?

**Comment by mattstratton** [comment]
That would be helpful. I also would like the ablity to control the name of the release, which the gh release providers in both travis and appveyor provide. I like to name my releases `myapp-version-0.1.0` instead of `0.1.0`. Just more flexibility for the end user of `goreleaser`.

(For the record, I'm super into taking a look at these issues myself and submitting some PR's...I'm a big believer in starting the issue and then doing the PR, hence why I filed them)

**Comment by jorinvo** [comment]
@mattstratton you could add a `release.name_template` config field similar to `archive.name_template`.
Would be great if you like to give it a try. Just let us know if you run into any issues!
