### ISSUE TITLE
Changelog: Ignore merge commits by default

### ISSUE THREAD

**Issue by jorinvo** [goreleaser/goreleaser#393]
I think the changelog would look better if we ignore the `Merge pull request ...` commits by default.
I am not sure if we should make this the default for everyone or if we should simply adopt the script we use for GoReleaser itself.
Changing the default for everyone might also be good since the majority of projects use Github to merge pull request.
What are your thoughts on this?

**Comment by caarlos0** [comment]
maybe we should rebase commits instead of merging to avoid that?

**Comment by jorinvo** [comment]
I don't mind the merge commits in the actual commit log. I only think that in the changelog it looks nicer if they are not listed. But we can do it either way.

**Comment by caarlos0** [comment]
@jorinvo check the latest release.

I think we can close this. If someone wants to have those removed, he/she can use the `--release-notes` flag.

We can also deal with this issue in the future in the issue #284.
