### ISSUE TITLE
nfpm extensions not being set

### ISSUE THREAD

**Issue by mbamber** [goreleaser/goreleaser#3933]
### What happened?

When trying to upload artifacts to Artifactory with an `exts` filter, the artifacts generated by nfpm are not being selected as the docs might suggest:

```yaml
    # File extensions to filter for.
    # This might be useful if you have multiple packages with different
    # extensions with the same ID, and need to upload each extension to
    # a different place (e.g. nFPM packages).
    #
    # Since: v1.7
    exts:
    - deb
    - rpm
```

### How can we reproduce this?

Example config snippet
```yaml
...
nfpms:
  -
    description: My package
    formats:
      - deb
...
artifactories:
  -
    name: default
    exts:
      - .deb
...
```

### goreleaser version

```bash
goreleaser version dev
goos: darwin
goarch: amd64
module version: v1.16.2, checksum: h1:usMTxv8JXDNUUmVo0VSTExYBwCmLOuqa1l6hkmE/diA=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

After a quick look at the source, I believe this an issue with the filtering. In particular, I think the `Ext` extra property isn't being set for artifacts generated by nfpm: https://github.com/goreleaser/goreleaser/blob/b36e30a071199b7290b73b3faa0652825c4d88fc/internal/pipe/nfpm/nfpm.go#L442

The attribute is set correctly for artifacts built directly: https://github.com/goreleaser/goreleaser/blob/b36e30a071199b7290b73b3faa0652825c4d88fc/internal/builders/golang/build.go#L149

**Comment by caarlos0** [comment]
ah yeah, your assessment is right... not sure if it got broken after some merge or what, but I think it was there at some point...

Anyway, thanks for reporting, will fix soon.

**Comment by mbamber** [comment]
See #3940 which I think should fix this

**Comment by caarlos0** [comment]
Thank you @mbamber !

**Comment by Romain-Geissler-1A** [comment]
Hi,

I spend some time trying to understand why my uploading task didn't work, and found it's related to `exts` and finally found this ;) It seems the latest fix isn't released, do you know when you will cut the next release ?

Cheers,
Romain

**Comment by caarlos0** [comment]
Hey, probably next week, or earlier next month

**Comment by mbamber** [comment]
I thought this was already out? I'm sure I'm using it 😅

**Comment by Romain-Geissler-1A** [comment]
Ah, I have wrongly checked the history, thanks !
