### ISSUE TITLE
--debug should output the warnings during builds

### ISSUE THREAD

**Issue by stephane-archer** [goreleaser/goreleaser#3934]
### Is your feature request related to a problem? Please describe.

if I set `CGO_CFLAGS=-mmacosx-version-min=10.10` and `CGO_LDFLAGS=-mmacosx-version-min=10.10` from the command line I get the following message:
```
app_darwin.m:18:25: warning: 'UNUserNotificationCenter' is only available on macOS 10.14 or newer [-Wunguarded-availability-new]
```
This helps me see that something wrong happen during the build.

but if I use `goreleaser build --snapshot --clean --debug` I don't see any warning and I can't see that something is wrong.
`--debug` should output the warnings during builds

### Describe the solution you'd like

`--debug` should output the warnings during builds

### Describe alternatives you've considered

I'm not sure

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

nop

**Comment by caarlos0** [comment]
can you test #3939

**Comment by stephane-archer** [comment]
I still have the same issue, Is my version not up-to-date?
```
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.25.1
GitCommit:     6a7a9ba3995728a4bdf7b5fff770d8caeb3d2cc8
GitTreeState:  dirty
BuildDate:     2024-04-04T01:51:35
BuiltBy:       homebrew
GoVersion:     go1.22.2
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/amd64
```
