### ISSUE TITLE
Source archive are not added as an artifact

### ISSUE THREAD

**Issue by maraino** [goreleaser/goreleaser#3937]
### What happened?

In the last version, the following source archive is not added to the list of artifacts because `len(ctx.Config.Source.Files) == 0`:

```yaml
source:
  enabled: true
  rlcp: true
  name_template: "{{ .ProjectName }}_{{ .Version }}"
```

The problem seems to be these lines
https://github.com/goreleaser/goreleaser/blob/ffefd6c4ae257d2e9aeccb5786ba66401cc1bd78/internal/pipe/sourcearchive/source.go#L64-L66

Added in a recent commit https://github.com/goreleaser/goreleaser/commit/0eb3e7975c7a134713c7e377dcb8696cb0294357

Adding a file in the `files` property works properly, the file cannot be present in the archive and needs to be in the .gitignore, if not you will get the dirty git state error.

### How can we reproduce this?

Run `goreleaser release --clean --skip-publish --debug` on a file with a source archive:

You are supposed to see something like this:
```
  • creating source archive
    • creating source archive                        file=foo_0.25.0.tar.gz
    • running git                                    args=[-c log.showSignature=false archive -o dist/foo_0.25.0.tar.gz 1434cdcc350ace025abfd12c13eea25d521cdbc0]
    • git result                                     stderr= stdout=
    • copying file                                   dst=dist/foo_0.25.0.tar.gz.bkp src=dist/foo_0.25.0.tar.gz
    • added new artifact                             name=foo_0.25.0.tar.gz path=dist/foo_0.25.0.tar.gz type=Source
```

And instead, you see:
```
  • creating source archive
    • creating source archive                        file=foo_0.24.0.tar.gz
    • running git                                    args=[-c log.showSignature=false archive -o dist/step-ca_0.24.0.tar.gz 1434cdcc350ace025abfd12c13eea25d521cdbc0]
    • git result                                     stderr= stdout=
```

### goreleaser version

```bash
$ goreleaser --version
goreleaser version 1.17.0
commit: ffefd6c4ae257d2e9aeccb5786ba66401cc1bd78
built by: homebrew
goos: darwin
goarch: amd64

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
that's a big oopsie from my part, fixing, thanks for reporting.
