### ISSUE TITLE
Multi scoop targets

### ISSUE THREAD

**Issue by blacktop** [goreleaser/goreleaser#3941]
### Is your feature request related to a problem? Please describe.

I have a goreleaser config where I'm building/packaging 2 bins a CLI and a DAEMON.  So far scoops are the only one that I think doesn't support the ability to pkg more than 1 bins?

### Describe the solution you'd like

I'd like to have:
```yml
scoop:
  -
   builds: 
```
etc   

### Describe alternatives you've considered

none

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
I think this actually might also be a 🐛 ?

It's causing my CI/CD for windows to fail:
```bash
Running post_install script...
'7zip' (22.01) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running: "C:\Users\runneradmin\scoop\apps\7zip\current\install-context.reg"
Installing 'ipsw' (3.1.312) [64bit] from blacktop bucket
Downloading https://github.com/blacktop/ipsw/releases/download/v3.1.312/ipsw_3.1.312_windows_x86_64_daemon.tar.gz (9.0 MB)...
Checking hash of ipsw_3.1.312_windows_x86_64_daemon.tar.gz ... ok.
Extracting ipsw_3.1.312_windows_x86_64_daemon.tar.gz ... done.
Linking ~\scoop\apps\ipsw\current => ~\scoop\apps\ipsw\3.1.312
Creating shim for 'ipswd'.
'ipsw' (3.1.312) was installed successfully!
ipsw: D:\a\_temp\58c7e595-832b-4a60-8a11-a7aba27929c3.ps1:4
Line |
   4 |  ipsw --help
     |  ~~~~
     | The term 'ipsw' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the
     | spelling of the name, or if a path was included, verify that the path is correct and try again.

Error: Process completed with exit code 1.
```

**Comment by blacktop** [comment]
So it looks like the scoop took the `ipswd` daemon bin instead of the `ipsw` CLI bin? So then after installing w/ `scoop` when I try and use it the bins *(`ipsw` cli`)* not there?

**Comment by caarlos0** [comment]
> So it looks like the scoop took the `ipswd` daemon bin instead of the `ipsw` CLI bin? So then after installing w/ `scoop` when I try and use it the bins _(`ipsw` cli`)_ not there?

https://github.com/blacktop/scoop-bucket/blob/main/ipsw.json#L7


it does look it it's installing ipswd indeed...

---

that said, yes, scoop definitely is lagging in terms of features comparing with the brew pipe for example...

**Comment by caarlos0** [comment]
see #3963
