### ISSUE TITLE
Add binary size log output

### ISSUE THREAD

**Issue by twelvelabs** [goreleaser/goreleaser#3949]
### Is your feature request related to a problem? Please describe.

I use goreleaser to both build and release my projects (it's pretty great, btw ❤️). During development I like to keep an eye on the binary size to watch out for bloat, and I currently always add something like the following to my Makefile:

```
build:
	goreleaser build --clean --snapshot --single-target
	du -h "${BIN_BUILD_PATH}"
```

This works, but has two issues:

- It's not cross platform w/out cluttering the makefile w/ additional complexity.
- The output isn't as pretty as goreleaser's 😞.

### Describe the solution you'd like

I'd like to add something like the following:

```
  • building binaries
    • building                                       binary=dist/myapp_darwin_amd64/myapp size=6.5M
    • building                                       binary=dist/myapp_darwin_arm64/myapp size=6.5M
```

Given [where that line is currently written](https://github.com/goreleaser/goreleaser/blob/9d91b5576a39cb0a4cba879f82c96e9320178143/internal/pipe/build/build.go#L214), I would need to relocate it to happen post-build. If that's not preferable, I could just add a new line post-build like so:

```
  • building binaries
    • building                                       binary=dist/myapp_darwin_amd64/myapp
    • inspecting                                     size=6.5M
    • building                                       binary=dist/myapp_darwin_arm64/myapp
    • inspecting                                     size=6.5M
```

A little noisier, but a simpler addition. Up to you 🤷.

### Describe alternatives you've considered

The `du` line mentioned above.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Thanks again for a wonderful project!

**Comment by caarlos0** [comment]
what about something like this:

```yaml
report_sizes:
  format: json # or text
  output: sizes.json # or log
```

?

**Comment by twelvelabs** [comment]
Ah, good point. Though if you wanted it in a JSON file, I would expect it to be a key in artifacts.json.

How about both: a log line and add it to artifacts.json (w/ no additional config needed)?

**Comment by caarlos0** [comment]
yeah, thought the same thing... will work on that :)

**Comment by caarlos0** [comment]
wdyt? https://github.com/goreleaser/goreleaser/pull/3954
