### ISSUE TITLE
Goreleaser fails in Travis

### ISSUE THREAD

**Issue by bobvanluijt** [goreleaser/goreleaser#397]
Running: `curl -sL http://git.io/goreleaser | bash` in Travis-ci results in:

```
release failed            error=git doesn't contain any tags. Either add a tag or use --snapshot

The command "curl -sL http://git.io/goreleaser | bash" failed and exited with 1 during .
```

https://travis-ci.org/weaviate/weaviate/builds/286194879

Any tips / hints what I'm doing wrong? Goal is to run `goreleaser --rm-dist --snapshot --skip-validate`

Thanks!

**Comment by caarlos0** [comment]
`Either add a tag or use --snapshot`?

**Comment by jorinvo** [comment]
You should probably run GoReleaser only for tags, not every build.
Can do it like this: https://github.com/qvl/ghbackup/blob/master/.travis.yml

**Comment by bobvanluijt** [comment]
Thanks @jorinvo!

Also created this: https://github.com/goreleaser/goreleaser/pull/398

For simple n00bs like myself :-P
