### ISSUE TITLE
Docs for multi-arch container images

### ISSUE THREAD

**Issue by guettli** [goreleaser/goreleaser#3978]
### Is your feature request related to a problem? Please describe.

I am unsure how to build multi-arch container images

### Describe the solution you'd like

I would like to read docs.

I don't trust old blog posts like this:

https://blog.devgenius.io/goreleaser-build-multi-arch-docker-images-8dd9a7903675

### Describe alternatives you've considered

I could follow an old blog post article.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

thank you for goreleaser.

**Comment by caarlos0** [comment]
FWIW the blog post seems to be valid still

**Comment by caarlos0** [comment]
https://goreleaser.com/cookbooks/multi-platform-docker-images/
