### ISSUE TITLE
Generated homebrew formulas that contain `plist_options` trigger warnings on `brew install`

### ISSUE THREAD

**Issue by bbkane** [goreleaser/goreleaser#3990]
### What happened?

Generated Homebrew formulas  from valid .goreleaser.yaml files should not trigger this warning on `brew install` and `brew doctor`:

```
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the bbkane/tap tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/bbkane/homebrew-tap/Formula/grabbit.rb:49
```

### How can we reproduce this?

I'm seeing this in [grabbit](https://github.com/bbkane/grabbit). The generated formula is [here](https://github.com/bbkane/homebrew-tap/blob/91e00744ab969e9cee9858df94113a09f0a4eaf2/Formula/grabbit.rb).

You can see this warning from Homebrew with:

```
brew install bbkane/tap/grabbit
```

It's also reproducible locally with the latest `goreleaser` with the following steps:

```bash
git clone https://github.com/bbkane/grabbit.git
cd grabbit
goreleaser release --snapshot --clean
brew install --build-from-source ./dist/grabbit.rb
```

This notably fails with a bunch of other errors due to it being a snapshot build, but the first `plist_options` one is the one that shows up even from a non-snapshot build.

```bash
$ brew install --build-from-source ./dist/grabbit.rb
Warning: Calling plist_options is deprecated! Use service.require_root instead.
```

### goreleaser version

```bash
$ goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.18.1
GitCommit:     aaa9da33d5e72a0db4c1c815dc746249b78266d2
GitTreeState:  dirty
BuildDate:     2023-05-05T04:26:12
BuiltBy:       homebrew
GoVersion:     go1.20.4
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

GoReleaser has made releasing my little open-source tools so much smoother!! Thank you for making it!!

**Comment by caarlos0** [comment]
`service` is already available as an option.

https://github.com/caarlos0/discord-applemusic-rich-presence/blob/2d78b74f6edea19d26cf20a64742466ee79f8e2d/.goreleaser.yml#L16-L20

will deprecate the plist stuff in goreleaser as well...
