### ISSUE TITLE
mipsle arch doesn't seem to be handled correctly when building .deb packages

### ISSUE THREAD

**Issue by ovidiuvio** [goreleaser/goreleaser#3998]
### What happened?

When trying to install a mipsel package built with goreleaser, I am getting the following:

`dpkg: error processing archive netbird_0.19.0-SNAPSHOT-7597897_linux_mipsle_hardfloat.deb (--install): package architecture (mipslehardfloat) does not match system (mipsel)
`
There is no such architecture called: mipslehardfloat
The value expected here is: `mipsle`

This bug was present in a much older version and has been fixed then, but now the code looks very different.
https://github.com/goreleaser/goreleaser/issues/2125

### How can we reproduce this?

https://github.com/netbirdio/netbird/pull/842#issuecomment-1540715712

### goreleaser version

```bash
1.14.1
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I made the required change to nfpm, and also added a table of the conversions made into the docs: https://nfpm.goreleaser.com/goarch-to-pkg/

feel free to review that, if you see anything else wrong/missing (definitely there are things missing), let me know :)

**Comment by caarlos0** [comment]
will close this once I release nfpm and update its dependency on goreleaser.

**Comment by ovidiuvio** [comment]
Thanks for the quick fix Carlos.
I think you might need to add `mips64` to the arch list as well, though I may be wrong here.

**Comment by caarlos0** [comment]
in which of the packagers?

**Comment by caarlos0** [comment]
nfpm updated here now. closing.
