### ISSUE TITLE
Customize the release tag

### ISSUE THREAD

**Issue by colinking** [goreleaser/goreleaser#4011]
### Is your feature request related to a problem? Please describe.

We are building a CLI hosted in a private monorepo and released via a separate public repo. The tags we use in the private repo don't align with the tags we use in the public repo, but [GoReleaser always uses the current git tag](https://github.com/goreleaser/goreleaser/blob/8eea2ddf153d1758a307ae3bb95c8aa704874742/internal/client/github.go#L270).

We want to tag releases in the monorepo as `cli/vX.Y.Z` that are created on the public repo as `vX.Y.Z`. We use GoReleaser's monorepo `tag_prefix` and everything works, except for the choice of tag on the public repo. This is an issue because GitHub releases using `cli/vX.Y.Z` notation are sorted below those with `vX.Y.Z` so the latest release is not the first shown on the releases page.

### Describe the solution you'd like

Expose a configuration option under `releases`, e.g. `git_tag_template`, which allows us to override the choice of git tag for the release. This should support templates, similar to `name_template`.

### Describe alternatives you've considered

We considered adding a CI step that renames the git tag before starting GoReleaser. For now, we're just manually re-tagging releases to use the correct unprefixed tag.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
that seems like a valid use-case, thanks for sharing. 

Will work on it for the next release :)

**Comment by caarlos0** [comment]
fixed, will be in the next pro release!

**Comment by caarlos0** [comment]
also added a cookbook for it: https://goreleaser.com/cookbooks/private-monorepo-public-release/
