### ISSUE TITLE
git detection for non-top-level goreleaser file failing

### ISSUE THREAD

**Issue by dpastoor** [goreleaser/goreleaser#403]
### Prerequisites

* [x] Are you running the latest version?
* [ ] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

as discussed in https://github.com/goreleaser/goreleaser/commit/529af6fe72a391207ab25ef6ca7676eaf4c45954#commitcomment-25011866 the problem comes when goreleaser is not at a top level directory

### Environment

Please paste the output of:

- `go version`
- `uname -a`
- `goreleaser --debug`

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

Detects in a git repository 

**Actual behavior:** [What actually happened]

Fails to detect in a git repo

**Comment by caarlos0** [comment]
this shall be fixed in v0.34.4
