### ISSUE TITLE
nix TODOs

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#4034]
- [x] #4046
- [x] #4047
- [x] #4048
- [x] #4049
- [x] #4050
- [x] #4224
- [x] #4212
- [x] #4226

**Comment by lionello** [comment]
- [ ] `zip` support; having `format: zip` results in `do not know how to unpack source archive /nix/store/dvl2hd8i63dq4xw76l49l1is6i3yh0nk-blah_0.0.1_darwin_all.zip`

**Comment by lionello** [comment]
I don't think currently there any other formats, since it appears to be limited to zip and tar.gz in `nix.go`. Or `.tgz` perhaps?

**Comment by caarlos0** [comment]
@lionello you're right... anyway, PR incoming :D
