### ISSUE TITLE
nix: compile from source

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#4047]
biggest issues here:

- how to automate getting the hashes? e.g. `nix-prefetch-url https://github.com/goreleaser/goreleaser/archive/v1.18.2.tar.gz` yields a different result than `fetchFromGithub` would, need to investigate, but I think the later does something else before hashing
- how to automate `vendorHash`?

**Comment by caarlos0** [comment]
sure! feel free to take a swing at it :D

**Comment by shubmjagtap** [comment]
fetchFromGithub  & vendorHash , im not able to find these concepts/words/code related to them in documentation of goreleaser nor in  codebase of goreleaser , how can i check how there these two things work ( inorder to automate them ) ?

**Comment by shubmjagtap** [comment]
so do i need to explore code of this https://github.com/NixOS/nix ?

**Comment by caarlos0** [comment]
I don't know how this should work, or if its even possible... so I can't give any pointers. 
I would dig in the source of nix, yes.

**Comment by dezren39** [comment]
i believe you will want to consider using:
- gomod2nix
- nix flakes
related resources:
- https://xeiaso.net/blog/nix-flakes-go-programs/
- https://www.tweag.io/blog/2021-03-04-gomod2nix/

**Comment by caarlos0** [comment]
I've been thinking and its probably not even worth trying to add this to goreleaser, as we also don't do it for homebrew, for example.

**Comment by caarlos0** [comment]
after giving this more thought: we don't do this for other packagers either (brew, etc), so I think it makes sense to not do it for nix, too.

we already gen the pre-compiled nix derivation, and that should be more than enough for most cases... users that need more things can create their own `flake.nix` or any of the other options available.


if anyone disagrees, feel free to comment, for now I'm closing this one.
