### ISSUE TITLE
`release` error=unknown flag: --prepare

### ISSUE THREAD

**Issue by dyladan** [goreleaser/goreleaser#4077]
### What happened?

`goreleaser release --prepare` is returning an error that the `--prepare` flag is unknown.

### How can we reproduce this?

Use `--prepare` flag with `release` subcommand

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    v1.18.2
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.19.1
Compiler:      gc
ModuleSum:     h1:qeNrKKVOHWEs1+/+a6jwASj7g9yg1R4vfLVlo0Beyro=
Platform:      darwin/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) of [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I am trying to run a build without actually releasing it so I can attach it as artifacts to pull requests as a PR preview. If there is another command I should be using please let me know. Seems like #3697 is a similar usecase to what i'm trying to achieve.

**Comment by caarlos0** [comment]
should be in the docs and on `--help`, that flag is pro-only.

will fix the docs later today, thanks for reporting
