### ISSUE TITLE
Add template support for `docker_manifests.skip_push`

### ISSUE THREAD

**Issue by brianstrauch** [goreleaser/goreleaser#4094]
### Is your feature request related to a problem? Please describe.

I'd like to be able to avoid pushing Docker manifests when a dry run environment variable is set.

### Describe the solution you'd like

Adding `docker_manifests.skip_push: "{{ .Env.DRY_RUN }}"` should let me use `DRY_RUN=true goreleaser release` to avoid pushing to DockerHub.

### Describe alternatives you've considered

N/A

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) of [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
done in https://github.com/goreleaser/goreleaser/commit/05d25567f93d0c6f91f8d0b702327588700b0900, just not released yet.
