### ISSUE TITLE
invalid furies.skip template

### ISSUE THREAD

**Issue by brianstrauch** [goreleaser/goreleaser#4096]
### What happened?

Added the following field to `furies:`
```
skip: "{{ .Env.DRY_RUN }}"
```

I got the error `invalid furies.skip template, will skip`. Maybe there isn't support for environment variables, or it can't handle an empty string?

### How can we reproduce this?

Add the field as described above

### goreleaser version

```bash
v1.18.2-pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) of [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hmmm, the log should have the error (fixing rn), but I believe its because that environment variable does not exist...

if that variable is not always set, you might want to do something like:

```yaml
skip: '{{ index .Env "DRY_RUN" }}'
```

I think I'll make that better by having a `envOrDefault` template function, e.g.:

```yaml
skip: '{{ envOrDefault "DRY_RUN" false }}'
```

what do you think?

**Comment by caarlos0** [comment]
for the second idea, see #4097

**Comment by caarlos0** [comment]
the issue you reported is fixed on pro as well, it'll now properly report the template error.


thanks for reporting this 🙏

**Comment by brianstrauch** [comment]
I was thinking `skip: "{{ .Env "DRY_RUN" }}"` would reduce to `skip: ""` and would evaluate to `false` (I would expect everything other than `skip: true` and `skip: "true"` to evaluate to `false`).

`envOrDefault` works for me, though! Thank you!

**Comment by caarlos0** [comment]
it evals to an error, and then we skip to be safe.

potentially not skipping when it should due to a template error (e.g. user misconfiguration) is less harmful than not skipping on error :)

**Comment by caarlos0** [comment]
all done :)
