### ISSUE TITLE
`git is in a dirty state` for git large files in goreleaser/goreleaser docker container

### ISSUE THREAD

**Issue by jonnylangefeld** [goreleaser/goreleaser#4123]
### What happened?

I'm using [`git-lfs`](https://git-lfs.com/) in my repo and locally my repo is in a clean state. I'm running a CI step in the `goreleaser/goreleaser` docker container, which doesn't have `git-lfs` installed. Since the container doesn't have a shell I can't install it in the container.

Does it make sense to add `git-lfs` to the container as it's a common git tool?

### How can we reproduce this?

track a file via `git-lfs`, have the local working tree clean and run gorleaser inside the container via `docker run -v $(pwd):/checkout -w /checkout -e GITHUB_TOKEN goreleaser/goreleaser release`

### goreleaser version

```bash
`v1.18.2`
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) of [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
> Does it make sense to add `git-lfs` to the container as it's a common git tool?

yes, I would think so..

thanks for reporting this :)

**Comment by caarlos0** [comment]
done in daf1c77
