### ISSUE TITLE
Version override without relying on GIT tag

### ISSUE THREAD

**Issue by tj** [goreleaser/goreleaser#413]
Hey!

My use-case is a little strange, but I need to release Up's Pro binaries to my own release storage on S3, so I'm doing:

```
$ goreleaser -p 1 --rm-dist -config .goreleaser.yml --skip-publish
```

But the since I may have `v0.1.0` for the OSS version, and `v0.1.0` in the "pro" branch, they obviously conflict so I can't version. I'm not sure what the best solution would be, maybe to support tag prefixes like `pro-v1.0.0`, or `--version v1.0.0` to specify this at build time.

Any suggestions?

thanks man!

**Comment by caarlos0** [comment]
Hi @tj 

Yeah, I haven't predicted this kind of use case... let me think about this for a while :P

**Comment by tj** [comment]
I'll think on it too hahah. Supporting a prefix miiiight be the simplest, `--skip-publish` is fine for my case, I have a little tool for uploading to my system already so that part isn't a big deal.

Happy to figure out a PR if that sounds reasonable

**Comment by caarlos0** [comment]
@tj yeah, if I understood it right, this seems like the simplest way...

would be awesome if you could provide a patch (you can also "test it in production" in your codebase hehe) 

let me know if you need help with anything :P

**Comment by tj** [comment]
ah weird I think this is a non-issue actually. I think I had an older build of goreleaser which sorted the versions so 0.3.0 would be > 0.1.0-pro and it would error thinking that commit was not v0.3.0. Seems ok now!

**Comment by chnrxn** [comment]
I would also like to have more flexibility on the version number without relying only on a git tag.

Either a tag prefix or a flag would also solve it for me. Any chance of this happening?
