### ISSUE TITLE
Goreleaser will happily compile Go source without main()

### ISSUE THREAD

**Issue by tdewolff** [goreleaser/goreleaser#415]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

`goreleaser` will happily compile a Go directory that has no `main` function. I forgot to add the `main` setting withing `builds`, and took me half-an-hour to figure out why I couldn't execute the binaries. They were object files of course, since there was no `main` function. Is this a feature? Feels to me this should be disallowed.

**Comment by caarlos0** [comment]
goreleaser just calls `go build`, it won't check for anything...

this may be a suggestion to the go team maybe...

**Comment by tdewolff** [comment]
`go build` can be used for generating both executables and object files, but `goreleaser` should only work for executables, otherwise it is meaningless. I think the check should be in `goreleaser`.

**Comment by caarlos0** [comment]
yeah I guess that kind of make sense

**Comment by caarlos0** [comment]
can check #418 please?
