### ISSUE TITLE
v1.19.0 doesn't install via go install

### ISSUE THREAD

**Issue by tresni** [goreleaser/goreleaser#4154]
### What happened?

Attempt to install goreleaser via `go install`, it failed.
```
» go install github.com/goreleaser/goreleaser@latest 
go: downloading github.com/goreleaser/goreleaser v1.19.0
go: github.com/goreleaser/goreleaser@latest (in github.com/goreleaser/goreleaser@v1.19.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

### How can we reproduce this?

Try installing goreleaser via `go install` as shown in the documentation

### goreleaser version

```bash
v1.19.0
```

### GoReleaser Check

- [ ] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iTanken** [comment]
And `go run`:

```shell
go run github.com/goreleaser/goreleaser@latest
go: github.com/goreleaser/goreleaser@latest (in github.com/goreleaser/goreleaser@v1.19.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by wzxjohn** [comment]
According to https://github.com/golang/go/issues/40276 , here is the problem
https://github.com/goreleaser/goreleaser/commit/b4dbf6b64b63785397a572806c516335cdd86086

**Comment by caarlos0** [comment]
Oops, afk now but will fix and re-release soon 

That replace will only affect the schema.json, so is not that bad
