### ISSUE TITLE
Improper formatting of Homebrew formula dependencies

### ISSUE THREAD

**Issue by febbraro** [goreleaser/goreleaser#416]
### Description

When building/deploying my application with multiple homebrew depenedencies, all of the `depends_on` statements are output on the same line. This is an invalid homebrew formula and it will not install.

I believe the problem is on this line in the homebrew template:
https://github.com/goreleaser/goreleaser/blob/master/pipeline/brew/template.go#L34

### Environment

I'm running goreleaser dev (installed via `go get -u github.com/goreleaser/goreleaser`)

### Steps to Reproduce

Here is the relevant brew config section:

```yaml
  dependencies:
    - docker
    - docker-machine
    - docker-compose
    - docker-machine-nfs
    - unison
    - eugenmayer/dockersync/unox
```

**Expected behavior:**

Each dependency on one line

```
  depends_on "docker"
  depends_on "docker-machine"
  depends_on "docker-compose"
  depends_on "docker-machine-nfs"
  depends_on "unison"
  depends_on "eugenmayer/dockersync/unox"
```

**Actual behavior:** [What actually happened]

All dependencies on the same line

`depends_on "docker"depends_on "docker-machine"depends_on "docker-compose"depends_on "docker-machine-nfs"depends_on "unison"depends_on "eugenmayer/dockersync/unox"
`

**Comment by caarlos0** [comment]
oops, thanks for reporting!

**Comment by jorinvo** [comment]
Thanks @febbraro!
@caarlos0 can you have a look in Slack?
