### ISSUE TITLE
allow to template dockerfile contents

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#4166]
refs https://github.com/orgs/goreleaser/discussions/3842#discussioncomment-6376551

**Comment by ryancurrah** [comment]
To add more to this. We have over 300 modules using Go Releaser. Some modules have multiple Go services and right now we use one `Dockerfile` for them all.  We do this by adding an environment variable of `SERVICENAME` which is the name of the binary/service and use a shell to interpolate `/opt/acme/bin/${SERVICENAME}`. We have an initiative to start using a minimal container that is shelless. So now our interpolating of environment variable will no longer work. Meaning we will have to have a `Dockerfille` for each service. If we were able to template the `Dockerfile` we could essentially accomplish the samething, where `${SERVICENAME}` would become a template variable `{{ .Artifacts[0].Binary }}`.

```
FROM docker.acme.com/service-go:22.04 AS base

ARG SERVICENAME
ENV SERVICENAME=${SERVICENAME}

COPY --chown="acme:acme" ${SERVICENAME} /opt/acme/bin/

EXPOSE 8443

ENTRYPOINT exec "/opt/acme/bin/${SERVICENAME}"
```

**Comment by caarlos0** [comment]
that adds a lot of context, thanks for sharing @ryancurrah .

I'll work on this soon 🙏

**Comment by ryancurrah** [comment]
Thank you!
