### ISSUE TITLE
feature request: mod_timestamp for universal_binaries

### ISSUE THREAD

**Issue by tungol** [goreleaser/goreleaser#4167]
### Is your feature request related to a problem? Please describe.

When using universal_binaries, the timestamps are always set to the current time. This causes the `*_Darwin_all.tar.gz` files to differ on otherwise reproducible builds.

### Describe the solution you'd like

It'd be nice if the universal_binaries section supported mod_timestamp like the build section.

### Describe alternatives you've considered

It's currently possible to workaround the issue using a post-hook:

```yaml
  hooks:
    post: touch -d {{ .CommitDate }} {{ .Path }}
```

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tungol** [comment]
I'll mention it here because I think it's goofy enough to not merit filing an issue for, but after sorting that out the only remaining part of goreleaser's output that isn't reproducible is the metadata.json file. I don't see any way to affect the date value that gets put there. 

If there's a trivial way to do that, it might be nice? But given that there's no configuration for it at all right now, I suspect it wouldn't be simple. In which case it's probably just not worth doing.

**Comment by caarlos0** [comment]
hey @tungol, thanks for the suggestions, will plan them for the next release :)
