### ISSUE TITLE
Windows runner: Deb and RPM archives invalid after updating from 1.16.2 to 1.17+

### ISSUE THREAD

**Issue by didil** [goreleaser/goreleaser#4174]
### What happened?

We are using goreleaser to build and package a binary in Github Actions. We use a `windows-latest` runner. After updating from goreleaser to 1.16.2 to 1.17+, the .deb and .rpm archives produced started becoming invalid as the files contain backslashes.
 When examining the .deb archive for example, the `control.tar.gz` subarchive includes files like:
 `.\\control
.\\md5sums
.\\conffiles`
Same for the .rpm archive when listing the content:
`\\usr\\bin\\globalping`

### How can we reproduce this?

https://github.com/jsdelivr/globalping-cli/actions/runs/5500964665

### goreleaser version

```bash
v1.19.2 x64 on windows
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
nfpm with fixes for windows updated in https://github.com/goreleaser/goreleaser/commit/cc18ad5184233998e5e083ff0b00576fcdd651e9

**Comment by caarlos0** [comment]
it should be fixed in main... can you verify? thanks

**Comment by didil** [comment]
@caarlos0 how can we run the goreleaser action against the goreleaser version from master ?

**Comment by didil** [comment]
@jimaek FYI

**Comment by caarlos0** [comment]
> Thanks ! @caarlos0 how can we run the goreleaser github action against the goreleaser version from master ?

I think the easiest way is to `go install` and then run it

**Comment by didil** [comment]
@caarlos0 I just tested building manually on a windows environment using goreleaser from master. The issues seems to be fixed as the .deb / .rpm files built are valid.

**Comment by caarlos0** [comment]
awesome, thank you!
