### ISSUE TITLE
Install syft in Docker image

### ISSUE THREAD

**Issue by osechet** [goreleaser/goreleaser#4176]
### Is your feature request related to a problem? Please describe.

When using the goreleaser Docker image to push images in GitLab CI (as described in https://goreleaser.com/ci/gitlab/#releasing-archives-and-pushing-images), if we want to generate SBOM, syft must be installed in the image. For the moment we use a `before_script` that builds a custom goreleaser image that includes syft. It works but it slowing down the CI.

```
release:
  stage: release
  image: docker:stable
  services:
    - docker:dind
...
  before_script:
    - docker build -f goreleaser.Dockerfile -t goreleaser-with-syft .
  script: |
    # GITLAB_TOKEN is needed to create GitLab releases.
    # DOCKER_* are needed to push Docker images.
    docker run --rm --privileged \
      -v $PWD:/go/src/gitlab.com/YourGitLabUser/YourGitLabRepo \
      -w /go/src/gitlab.com/YourGitLabUser/YourGitLabRepo \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME -e DOCKER_PASSWORD -e DOCKER_REGISTRY  \
      -e GITLAB_TOKEN \
      goreleaser-with-syft release --clean
```

With `gorelease.Dockerfile`:
```
FROM goreleaser/goreleaser:latest

RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
```

### Describe the solution you'd like

Would it be possible to install syft by default in the goreleaser image?

```
...
RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
```

### Describe alternatives you've considered

If you think the default image should not package syft, would it be possible to provide a `goreleaser/goreleaser-with-syft` image?

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
sounds good.
