### ISSUE TITLE
Allow overriding the config file as an option

### ISSUE THREAD

**Issue by aidenkeating** [goreleaser/goreleaser#419]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

Currently all configuration must be defined in a configuration file. It would be great to allow for overrides.

Happy to make these changes myself, just looking for some feedback on the idea.

I could see this override happening in one of two ways:

#### Allow for explicit overrides from the command line

We can specify inline YAML config from the command line (it's basically JSON when one-lined).

For example:
```
goreleaser --extra-config='{ "release": { "prerelease": true } }' 
```

This could be a `StringSliceFlag` flag to ensure the overrides aren't too complex.
```
go releaser --extra-config='{ "release": { "prerelease": true } }' --extra-config='{ "archive": "files": ["LICENCE", "README.md"] }'
```

#### Allow --config to be passed multiple times

Make the config flag a `StringSliceFlag` and merge each config file with the next. Giving precedence to the next one.

For example:
```
# Look for default .goreleaser.yml file and merge with the prerelease. If the default file doesn't exist try to just use the prerelease file.
goreleaser --config="./prerelease-specific-goreleaser.yml"
```

The config flag could also be allowed to accept YAML strings as well as file paths.

```
goreleaser --config="./mycustom-goreleaser.yml" --config='{ "release": { "prerelease": true } }'
```

**Comment by caarlos0** [comment]
I don't have any use case for this, but some people might.

I can agree to this if we can output the actual config file to the dist folder as well - this should help the user to understand what's happening.

Maybe an option to upload the file to the release as well (since it kind of represents the release)?

@aidenkeating I'll work on writing the config file to the dist folder (this should be painless), can you open a PR with the `--extra-config` flag?

**Comment by caarlos0** [comment]
Oh, one more thing I just remembered: `helm`, for example, allows those overrides with `--set` flag:

```
helm install stable/traefik --values ./values.yaml --set dashboard.statistics.recentErrors=10
```

maybe we can use the same approach? I think it is easier to write than the actual JSON - and we get to keep only the yaml format for config...

**Comment by aidenkeating** [comment]
@caarlos0 Thanks for the feedback. The `--set` approach makes sense to me. I'll get a PR up over the next few days.

**Comment by caarlos0** [comment]
nice, I'm already working on the writing the effective config file on #457

**Comment by tcinelli** [comment]
Any news on this?  Thanks and great work.
