### ISSUE TITLE
json schema outdated for chocolatey(s) key

### ISSUE THREAD

**Issue by rami3l** [goreleaser/goreleaser#4194]
### What happened?

When editing the `chocolateys` section in my `.goreleaser.yml`, VSCode gives this error:

```
Property owners is not allowed.
(yaml-schema: Goreleaser)
```

This should not happen since the property is clearly documented here: https://goreleaser.com/customization/chocolatey

### How can we reproduce this?

```yml
# .goreleaser.yml
chocolateys:
  - owners: someone
```

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.19.2
GitCommit:     b95fd394866efeb147769b49a469f88186606177
GitTreeState:  false
BuildDate:     2023-07-07T13:32:08Z
BuiltBy:       goreleaser
GoVersion:     go1.20.5
Compiler:      gc
ModuleSum:     h1:m24wCy0UzBTGO3zqezAxcoA87RBySRRL0dyJjiNfdjQ=
Platform:      windows/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
good catch!

thanks, fixed it!
