### ISSUE TITLE
winget: create a single commit for the PR to microsoft/winget-pkgs

### ISSUE THREAD

**Issue by twpayne** [goreleaser/goreleaser#4198]
### Is your feature request related to a problem? Please describe.

The Winget pipeline creates one commit per file added to the PR to the upstream microsoft/winget-pkgs repo, for example: https://github.com/microsoft/winget-pkgs/pull/112476/commits. All three commits have the same message, which makes it hard to understand exactly what each commit does.

### Describe the solution you'd like

Ideally, goreleaser would create a single commit that contains all three files.

### Describe alternatives you've considered

Alternatively, the commit messages could be updated to be more descriptive, for example:

```
New version: twpayne.chezmoi 2.35.2: add manifest
New version: twpayne.chezmoi 2.35.2: add installer
New version: twpayne.chezmoi 2.35.2: add locale
```

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

The code that needs changing is [here](https://github.com/goreleaser/goreleaser/blob/2a3009757a8996cdcf2a77deb0e5fa413d1f2660/internal/pipe/winget/winget.go#L353-L357).

**Comment by caarlos0** [comment]
see #4199
