### ISSUE TITLE
replace oses and arches by goos and goarch?

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#42]
Seems more brainless... oses and arches may be confusing...

**Comment by medhoover** [comment]
Why not using `os, arch` ?
Even better to support a combined syntax `-osarch linux/amd64`.
Taken from gox syntax https://github.com/mitchellh/gox#usage

**Comment by caarlos0** [comment]
@medhoover because `goos` and `goarch` are clearer..

`os` and `arch` doesn't explicitly tells in what form they should be.

`goos` and `goarch` do...


I like the `gox` syntax (`goos/goarch`). Will think more about it, maybe for version 2...
