### ISSUE TITLE
Cut Homebrew Formulas for each version

### ISSUE THREAD

**Issue by jzelinskie** [goreleaser/goreleaser#4204]
### Is your feature request related to a problem? Please describe.

Some users want to pin particular versions of their software and not always install the latest release.

### Describe the solution you'd like

Homebrew supports creating Formulas with the naming convention `software@1.2.3.rb`.
Ideally, goreleaser would create these Formulas in addition to updating `software.rb` to be the latest release.

### Describe alternatives you've considered

I'm not sure there are alternatives if you want to be able to install specific versions of brew releases.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Fury doesn't have this problem.

**Comment by caarlos0** [comment]
Hey, you can already do this:

```yaml
brews:
- name: foo
  # other options...
- name: 'foo@{{.Version}}'
  # other options...
```

example: 
- https://github.com/caarlos0-graveyard/test/blob/master/.goreleaser.4.yml#L26-L36
- https://github.com/caarlos0-graveyard/test/tree/master/Formula

It might be a little repetitive, but with pro you can set the description, URL, and etc in variables and reuse them.

**Comment by maidul98** [comment]
@caarlos0 are you suggesting to manually add a new tap for each new version we release?

**Comment by caarlos0** [comment]
no, you only need the 2, `{{.Version}}` is templated.

So, on every release it will publish `foo.rb` and `foo@THE_VERSION.rb`

**Comment by maidul98** [comment]
thanks!

**Comment by caarlos0** [comment]
that said, I think it would be nicer to have an option to do this automagically...

maybe `also_publish_versioned_formula: true`, wdyt?

**Comment by jzelinskie** [comment]
> Hey, you can already do this:
> ...

That's fantastic and makes perfect sense in retrospect. However, even with the pro features, it's quite verbose to to duplicate our brew configuration for a single field change: https://github.com/authzed/spicedb/blob/4d263e53fe26249a15e2f1c81b4731f090507431/.goreleaser.yml#L36-L67

Unless I'm missing something, the Vars functionality doesn't help much with this level of verbosity from shared structure. This probably deserves a separate issue, but supporting something like GitHub Action's `matrix` would probably be ideal: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

**Comment by caarlos0** [comment]
yes, agreed. I'm adding a new option on pro to improve this :) 

Thanks for the issue, btw! :D

**Comment by jzelinskie** [comment]
Thanks again for the response -- I'm going to just copypasta our way to victory on this one and then we'll come back and clean up with whatever you build to help the verbosity issue.
