### ISSUE TITLE
internal.pipes.defaults.Run() does not check for Skipped defaulters

### ISSUE THREAD

**Issue by chnrxn** [goreleaser/goreleaser#4208]
### What happened?

The defaults runner does not check whether defaulters should be skipped. This leads to the execution of Defaults() from disabled pipes like `release`.

https://github.com/goreleaser/goreleaser/blob/main/internal/pipe/defaults/defaults.go#L41

### How can we reproduce this?

```
	for _, defaulter := range defaults.Defaulters {
		if err := errhandler.Handle(defaulter.Default)(ctx); err != nil {
			return err
		}
	}
```

### goreleaser version

```bash
goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.19.2
GitCommit:     b95fd394866efeb147769b49a469f88186606177
GitTreeState:  dirty
BuildDate:     2023-07-07T13:32:08
BuiltBy:       homebrew
GoVersion:     go1.20.5
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hmmm good catch, not exactly an issue, but good catch nevertheless

**Comment by caarlos0** [comment]
that's a completely different issue then... 

also gerrit is not officially supported.

**Comment by chnrxn** [comment]
> that's a completely different issue then...
> 
> also gerrit is not officially supported.

I apologise for mentioning non-related information that distracts from the main point. Replace Gerrit with "any other non Github/Gitlab/Gitea" SCM - it doesn't matter.

The relevant point is, the `release` pipe is not needed, and is already disabled in the config, but the SCM URL format is still being enforced through the invocation of a disabled defaulter.

If we can skip invoking disabled defaulters, then all will be good.

**Comment by caarlos0** [comment]
> If we can skip invoking disabled defaulters, then all will be good.

I hate to actually, but, actually, it depends... the SCM URL might be used later as a default for, for example, homebrew taps... 

anyway, I'll look into it.

**Comment by caarlos0** [comment]
This broke other stuff, will have to revisit it for the next release.
