### ISSUE TITLE
Matrix functionality

### ISSUE THREAD

**Issue by skyzyx** [goreleaser/goreleaser#4214]
### Is your feature request related to a problem? Please describe.

(Firstly, this is the world's most amazing tool. Thank you.)

I work for a large enterprise with a highly heterogenous technology landscape. I also maintain our internal Artifactory installation. We have Linux package manager repositories for:

* CentOS 7 (amd64)
* Amazon Linux 2 (amd64)
* Amazon Linux 2023 (amd64, arm64)
* Ubuntu 20.04 LTS (amd64, arm64)
* Ubuntu 22.04 LTS (amd64, arm64)
* Alpine Linux 3.14 (amd64, arm64)
* Alpine Linux 3.15 (amd64, arm64)
* Alpine Linux 3.16 (amd64, arm64)
* Alpine Linux 3.17 (amd64, arm64)
* Alpine Linux 3.18 (amd64, arm64)

As of today, this is all of the non-EOL'd releases of these operating systems. My trouble comes when I do a release and push artifacts into the Linux package manager repositories. I need to deploy to:

* Ubuntu LTS: `focal`, `jammy`
* Alpine Linux: `3.14`, `3.15`, `3.16`, `3.17`, `3.18`
* Some combination of `amd64` and `arm64`.

The package filename is the same, the version is the same, etc. But I'm looking for something like what GitHub Actions has, which is the ability to "loop" over a set of values, and update that one value with each iteration over the loop.

I've been doing this from my laptop with a Bash script. But as I move this the rest of the way into CI, I don't see anything (particularly in the `artifactories:` block) that appears to support this.

### Describe the solution you'd like

I'm looking for something like what GitHub Actions has, which is the ability to "loop" over a set of values ([matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs)), and update that one value with each iteration over the loop.

### Describe alternatives you've considered

Executing a Bash script as a post-hook.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I'll probably start with executing a Bash script as a post-hook to get this done today. But I'd love to upgrade to a built-in solution.

**Comment by caarlos0** [comment]
hmmm, seems reasonable... you need that specifically for the artifactory upload part, correct?

**Comment by caarlos0** [comment]
if that was it, its done, will be in the next pro release. Let me know if you think of more pipes that could use this. :)
