### ISSUE TITLE
Publishing multiple archs under a single tag only

### ISSUE THREAD

**Issue by simplylizz** [goreleaser/goreleaser#4245]
Hello,

I'm wondering, is it possible to publish images for different architectures under a single tag only? I can do this with publishing firstly images with tags like `1.0.0-amd64` & `1.0.0-arm64` and only then both archs under `1.0.0` tag. But I'm trying to avoid publishing of `-<arch>` images.

**Comment by caarlos0** [comment]
@crazy-max do you need any assistance?

**Comment by crazy-max** [comment]
Oh my bad I completely forgot about this as I was on PTO. I will take a look shortly!

**Comment by cprivitere** [comment]
> Oh my bad I completely forgot about this as I was on PTO. I will take a look shortly!

Did you ever get a chance to look at this?

**Comment by kanlac** [comment]
Should this issue be closed? It seems that [`docker_manifest`](https://goreleaser.com/customization/docker_manifest/) has already resolved the issue of multi-platform image publishing.

**Comment by caarlos0** [comment]
yeah, closing!
