### ISSUE TITLE
Inconsistent Version between global hooks and build pipe in a snapshot build

### ISSUE THREAD

**Issue by ThomasK33** [goreleaser/goreleaser#4247]
### What happened?

When running a snapshot build, the version passed as `{{ .Version }}` to the global hooks differs from the one specified in `snapshot.name_template`.

This is due to the snapshot pipe running after the before pipe (https://github.com/goreleaser/goreleaser/blob/4526c5b6813ade905f9658467c3a85aa25bdc9b9/internal/pipeline/pipeline.go#L62-L65), thus the global hooks receive the semver parsed version off the tag, yet not the modified version.

Once one builds a binary with ldflags and passes the version to a variable in the binary, the versions are different.

This can be especially hard to deal with when the before hooks generate version-specific files embedded into the binary.

### How can we reproduce this?

I've created a small repo for this showcase: https://github.com/ThomasK33/goreleaser-snapshot-precedence-repro

### goreleaser version

```bash
❯ goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.20.0
GitCommit:     56c9d09a1b925e2549631c6d180b0a1c2ebfac82
GitTreeState:  false
BuildDate:     2023-08-10T01:23:44Z
BuiltBy:       goreleaser
GoVersion:     go1.21.0
Compiler:      gc
ModuleSum:     h1:wvAbDqQwMX3PWPYc4VIeaWQB2V5HOETvDlyfTrk7NgQ=
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I think this can be fixed by changing

```go
    // run global hooks before build
    before.Pipe{},
    // snapshot version handling
    snapshot.Pipe{},
```

to 

```go
    // snapshot version handling
    snapshot.Pipe{},
    // run global hooks before build
    before.Pipe{},
```

in the [internal/pipeline/pipeline.go](https://github.com/goreleaser/goreleaser/blob/4526c5b6813ade905f9658467c3a85aa25bdc9b9/internal/pipeline/pipeline.go#L62-L65) file.

If that's fine by you, I'd be more than happy to open a PR with that change.

**Comment by caarlos0** [comment]
yes, you're right... and that's also the proper fix I think, will investigate a bit and open the PR if that's really it.

thanks for reporting this 🙏🏻
