### ISSUE TITLE
GITHUB_TOKEN rate limit check resulting in unlimited sleep and eventual job timeout 

### ISSUE THREAD

**Issue by dougsong** [goreleaser/goreleaser#4248]
### What happened?

Not sure why my GITHUB_TOKEN rate limit is 60 in GITHUB Action, In this [PR](https://github.com/goreleaser/goreleaser/pull/4037/files) added GITHUB_TOKEN ratelimit check, sleep when the ratelimit is less than 100, and finally check the ratelimit again. Since my ratelimit is 60 and always less than 100, it will keep sleep during execution.

job link: https://github.com/dougsong/pulumi-volcengine/actions/runs/5863264922/job/15896410408

>  token too close to rate limiting, will sleep for 42m26.849427395s before continuing...

<img width="700" alt="image" src="https://github.com/goreleaser/goreleaser/assets/39510437/edd6d6c2-605b-4f2d-9f01-eee36642be55">

related github discussion: https://github.com/orgs/community/discussions/63763

### How can we reproduce this?

fork https://github.com/dougsong/pulumi-volcengine and add a new release to trigger GitHub Action

### goreleaser version

```bash
'goreleaser/goreleaser-action@v3.0.0' (SHA:68acf3b1adf004ac9c2f0a4259e85c5f66e99bef)
goreleaser v1.20.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
what was the issue?
