### ISSUE TITLE
Only build binaries?

### ISSUE THREAD

**Issue by tisba** [goreleaser/goreleaser#425]
I'm trying to add docker releases for our CLI.

I had some problems with missing certificates and debugging so the minimal dockerfile that you suggest, did not really do the job. My goal is that I want to mainly use goreleaser via travis, but also have the option to do that locally. I did not succeed with static linking the go binary (various reasons).

My current approach is

```docker
FROM golang:alpine

COPY . /go/src/github.com/stormforger/cli
WORKDIR /go/src/github.com/stormforger/cli

ENV binary forge

RUN apk --update add ca-certificates make g++ git \
    && go build \
      -v -o ${binary} \
      -ldflags '-s -w -X github.com/stormforger/cli/buildinfo.version={{.Version}} -X github.com/stormforger/cli/buildinfo.commit={{.Commit}} -X github.com/stormforger/cli/buildinfo.date={{.Date}}' \
      . \
    && cp ./${binary} /go/bin \
    && rm -rf .git \
    && apk del make g++ git

ENTRYPOINT [ "forge" ]
```

Maybe you can see where this is heading. Compiling the binary inside docker works fine. But I don't really want to reimplement goreleaser when it comes to naming the binary, setting ldflags etc.

Is there a way I'm currently not seeing to use goreleaser and tell it just to build `linux/amd64` and skip all other configured goos and goarch combinations? This way I could install goreleaser in docker, run it to produce the binary and then remove it again.

### Environment

Please paste the output of:

- `go version go1.9.2 darwin/amd64`
- `Darwin shakti 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64`
- `goreleaser --debug`

**Comment by caarlos0** [comment]
> I had some problems with missing certificates and debugging so the minimal dockerfile that you suggest, did not really do the job. 

yeah, the scratch image doesn't have any, you can either add them via code or use another base image (like alpine) and make sure the certificates are installed.

```Dockerfile
FROM alpine
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY forge /forge
ENTRYPOINT ["/forge"]
```

this in theory should work.

The reason it works when compiling inside the golang:alpine docker image is that it probably already have the ca-certificates installed.

**Comment by tisba** [comment]
I actually tried that. We run goreleaser on Travis, which runs on Ubuntu Trusty. So coping the binary does not work, unless the binary is statically linked (libc vs libmusl). But the nessessary ldflag options broke the builds for Windows on Travis.

At this time, I just stopped and we ended up doing just:

```Dockerfile
FROM ubuntu:trusty

COPY forge /bin

RUN apt-get -y update && apt-get -y install ca-certificates

ENTRYPOINT [ "forge" ]
```

The initial question I wanted to ask is, if there is a way to invoke goreleaser just to build, e.g. the linux amd64 binary so that can be build inside docker without duplicating all the compile options etc. This way I could use goreleaser for Windows, macOS and Linux and also ship a Docker container.

(Disclaimer: I'm quite new to Golang)

**Comment by caarlos0** [comment]
> I actually tried that. We run goreleaser on Travis, which runs on Ubuntu Trusty. So coping the binary does not work, unless the binary is statically linked (libc vs libmusl). But the nessessary ldflag options broke the builds for Windows on Travis.

I think this is happening because you're building a linux binary from a linux machine, so it is not really cross-compiling.

I always force it by setting `CGO_ENABLED=0`:

https://github.com/goreleaser/goreleaser/blob/master/.goreleaser.yml#L4

**Comment by tisba** [comment]
hmm, I think I also tried `CGO_ENABLED=0`, but I'll give this another try and report back. Thanks!

**Comment by caarlos0** [comment]
I'll close this for now. Let me know if you need more help!

cheers
