### ISSUE TITLE
Github action - error=hook failed: go mod tidy - when code built with Go version 1.21.0 

### ISSUE THREAD

**Issue by AaronSaikovski** [goreleaser/goreleaser#4252]
### What happened?

error when running this github action:

name: goreleaser

on:
  release:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

### How can we reproduce this?

Run goreleaser/goreleaser-action@v4
Downloading https://github.com/goreleaser/goreleaser/releases/download/v1.20.0
/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/2b6a486b-b22c-46b4-9b1c-32268719ab77 -f /home/runner/work/_temp/ed885498-6395-4601-9937-cff9054ea79c
GoReleaser latest installed successfully
/opt/hostedtoolcache/goreleaser-action/1.20.0/x64/goreleaser release --clean
  • starting release...
  • loading config file                              file=.goreleaser.yaml
  • loading environment variables
    • using token from $GITHUB_TOKEN
  • getting and validating git state
    • building...                                    commit=72ebde44e929080a5e8eb52eb9e47387628c09ce latest tag=v1.1.0
  • parsing tag
  • setting defaults
  • running before hooks
    • running                                        hook=go mod tidy
  ⨯ release failed after 0s                  error=hook failed: go mod tidy: exit status 1; output: go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20

### goreleaser version

```bash
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.20.0
GitCommit:     56c9d09a1b925e2549631c6d180b0a1c2ebfac82
GitTreeState:  false
BuildDate:     2023-08-10T01:23:44Z
BuiltBy:       goreleaser
GoVersion:     go1.21.0
Compiler:      gc
ModuleSum:     h1:wvAbDqQwMX3PWPYc4VIeaWQB2V5HOETvDlyfTrk7NgQ=
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
looks like your `go.mod` indicates go 1.21, but your action installed go 1.20.

This is not an issue with goreleaser, it would fail if run it locally with go 1.20 as well.

example:

```console
$ head -n 3 go.mod
module github.com/goreleaser/goreleaser

go 1.21

$ go version
go version go1.20.6 darwin/arm64

$ go mod tidy
go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20

```
