### ISSUE TITLE
Using custom environment variables

### ISSUE THREAD

**Issue by diegobernardes** [goreleaser/goreleaser#426]
### Prerequisites

* [ ] Are you running the latest version?
* [X] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

Don't know if this is possible, but would be nice to use custom environment variables with goreleaser. In my case, my build has alot of ldflags, the built in variables are too limiting.

Or goreleaser should support execute of bash scripts to generate the tags or support external variables that can be processed before run goreleaser.

**Comment by andygrunwald** [comment]
> In my case, my build has alot of ldflags, the built in variables are too limiting.

Can you provide a practical example here? This would help the team to understand the usecase more in detail. Like how does your ldflags look like right now? How do you execute your builds?
Maybe a real life example from your application. Thank you.

**Comment by diegobernardes** [comment]
This is the output of `version` from one of our applications:
```
Version: v2.1.0-15-g7d4262a
Commit: 7d4262a
Build Time: 2017-12-03 12:50 UTC
Go Version: go1.9.2
User: diego.bernardes
CI: 2196
```

During the CI we inject the pipeline number that generated the binary, the user that triggered the build and the go version.

**Comment by caarlos0** [comment]
I think it's a doable feature. Will work on it once I finish #430
