### ISSUE TITLE
Universal binaries post hook is not skipped with --skip-post-hooks

### ISSUE THREAD

**Issue by jamesjwarren** [goreleaser/goreleaser#4278]
### What happened?

Running `goreleaser build --skip-post-hooks` I expected all post hooks to be skipped. However the universal binaries post hook `universal_binaries[].hooks.post` continues to run.

### How can we reproduce this?

I was able to reproduce this using the following minimal config for universal binaries and running the following command:
`goreleaser build --clean --skip-post-hooks --debug`
```
# .goreleaser.yaml
universal_binaries:
  - replace: true
    hooks:
      post: echo "Hello World"
```

### goreleaser version

```bash
GitVersion:    v1.20.0
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.20.4
Compiler:      gc
ModuleSum:     h1:wvAbDqQwMX3PWPYc4VIeaWQB2V5HOETvDlyfTrk7NgQ=
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
good find!

fwiw I'm reworking the skipping stuff in #1891, so I'll do this after that one is merged in 🙏🏻

**Comment by caarlos0** [comment]
wrong pr link though, correct one is #4272
