### ISSUE TITLE
re-request Kaniko Support 

### ISSUE THREAD

**Issue by gannaramu** [goreleaser/goreleaser#4281]
### Is your feature request related to a problem? Please describe.

related to Kaniko Support #2322

### Describe the solution you'd like

requesting Kaniko support to run goreleaser on k8s with clusters with no dockers.

### Describe alternatives you've considered

NA

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
closing this as it does not seem to have a lot of interest, and also because i don't have the time/energy to implement it
