### ISSUE TITLE
sbom: syft reports "unable to open image source" - possibly due to wrong args / starting directory

### ISSUE THREAD

**Issue by UVduane** [goreleaser/goreleaser#4289]
### What happened?

Running `goreleaser release --skip-publish --clean` getting an error out of syft generating SBOM:

```
  ⨯ release failed after 4s                  error=cataloging artifacts: syft failed: exit status 1: 1 error occurred:
        * failed to construct source from user input "dist/gr-minimal-repro_Windows_i386.zip": unable to load image: unable to determine image source
```

My expectation was a successful build and completion of SBOM

----

I was able to get some hints after a good bit of debugging, or at least I think I was.  Using this `dlv` debug script I was able to get the args and env variables being passed to `syft`:

```
transcript dlv.out
break C:/Users/DuaneWaddle/go/src/github.com/goreleaser/goreleaser/internal/pipe/sbom/sbom.go:207
continue
print cmd
continue
exit
```

If I run `syft` manually with (basically) the same arguments it works:

```
PS C:\Users\DuaneWaddle\go\src\github.com\UVDuane\gr-minimal-repro> syft .\dist\gr-minimal-repro_Windows_i386.zip --file sbom.sbom --output spdx-json
 ✔ Indexed file system               C:\Users\DuaneWaddle\AppData\Local\Temp\syft-archive-contents-1710168046   ✔ Cataloged file digests
 ✔ Indexed file system               C:\Users\DuaneWaddle\AppData\Local\Temp\syft-archive-contents-1710168046   ✔ Cataloged file metadata
 ✔ Indexed file system               C:\Users\DuaneWaddle\AppData\Local\Temp\syft-archive-contents-1710168046
 ✔ Cataloged packages              [0 packages]
A newer version of syft is available for download: 0.90.0 (installed version is 0.89.0)
PS C:\Users\DuaneWaddle\go\src\github.com\UVDuane\gr-minimal-repro>
```

But from HERE I (eventually) noticed in the `dlv` output that the `Cmd` being created has a starting directory (`Dir`) of `dist`.  Sure enough, if I run the same `syft` command from inside the `dist` dir, it fails just like under goreleaser.

```
PS C:\Users\DuaneWaddle\go\src\github.com\UVDuane\gr-minimal-repro> cd dist
PS C:\Users\DuaneWaddle\go\src\github.com\UVDuane\gr-minimal-repro\dist> syft .\dist\gr-minimal-repro_Windows_i386.zip --file sbom.sbom --output spdx-json
A newer version of syft is available for download: 0.90.0 (installed version is 0.89.0)
1 error occurred:
        * failed to construct source from user input ".\\dist\\gr-minimal-repro_Windows_i386.zip": unable to load image: unable to determine image source
```

----

After all of this, my assumption is that the path to the artifact when calling `syft` should not include `dist/`. but I am using the most basic defaults for the `sboms` config.

### How can we reproduce this?

Minimal reproduction in https://github.com/UVduane/gr-minimal-repro

### goreleaser version

```bash
PS C:\Users\DuaneWaddle\go\src\github.com\UVDuane\gr-minimal-repro> goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.20.0
GitCommit:     56c9d09a1b925e2549631c6d180b0a1c2ebfac82
GitTreeState:  false
BuildDate:     2023-08-10T01:23:44Z
BuiltBy:       goreleaser
GoVersion:     go1.21.0
Compiler:      gc
ModuleSum:     h1:wvAbDqQwMX3PWPYc4VIeaWQB2V5HOETvDlyfTrk7NgQ=
Platform:      windows/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I have not tried to reproduce on linux, sorry.

**Comment by caarlos0** [comment]
hmm, that's weird, will take a look

thanks for reporting 🙏🏻

**Comment by caarlos0** [comment]
could you, after running goreleaser in that reproducible, share the output of this command:

```
cat dist/artifacts.json | jq '.[] | select(.type == "Archive")'
```

or the entire `dist/artifacts.json` file

**Comment by UVduane** [comment]
See attached file.

[output.txt](https://github.com/goreleaser/goreleaser/files/12599016/output.txt)

**Comment by caarlos0** [comment]
#4301 should fix it 🙏🏻

**Comment by caarlos0** [comment]
thanks for all the info, btw 💜

**Comment by UVduane** [comment]
I will give this branch a try on my windows system, see what happens, let you know
