### ISSUE TITLE
Winget: Add support for specifying dependencies

### ISSUE THREAD

**Issue by StiviiK** [goreleaser/goreleaser#4296]
### Is your feature request related to a problem? Please describe.

Winget manifests support the specification of dependencies (other winget pkgs), it would be nice if goreleaser adds support for specifying them.

More info: https://github.com/microsoft/winget-cli/issues/163

### Describe the solution you'd like

See above.

### Describe alternatives you've considered

Editing the manifests manually before submitting Pull-Request.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
please take a look at #4299
