### ISSUE TITLE
GCS (blobs) cache control

### ISSUE THREAD

**Issue by jsirianni** [goreleaser/goreleaser#4309]
### Is your feature request related to a problem? Please describe.

I have a script that is published to GCS on every release. Goreleaser correctly overwrites the previous script (same file name).

[Google's default Cloud Storage CDN](https://cloud.google.com/storage/docs/caching) caches this file and retains the cached copy for an hour. This causes my file to be eventually consistent. Unfortunately, this could mean that users that use the script twice in a short duration will potentially install different versions of my software.

### Describe the solution you'd like

Allow the `blobs` section to configure GCS object metadata, specically, the `Cache-Control` option.

![Screenshot from 2023-09-19 15-28-26](https://github.com/goreleaser/goreleaser/assets/23043836/aab075d2-9db6-4718-be4b-91037d3221c9)

### Describe alternatives you've considered

Removing the scripts from Goreleaser's configuration and managing them manually in GCS.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
yes, we need to properly handle more options on the blob uploads, pending impl.

if you're curious, here's one attempt: https://github.com/goreleaser/goreleaser/pull/3772

**Comment by caarlos0** [comment]
might be good to solve this here as well: https://github.com/orgs/goreleaser/discussions/4407
