### ISSUE TITLE
Support Google cloud builder CI

### ISSUE THREAD

**Issue by gedw99** [goreleaser/goreleaser#432]
### Prerequisites

* [ ] Are you running the latest version?
* [ ] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Environment

Please paste the output of:

- `go version`
- `uname -a`
- `goreleaser --debug`

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

https://wildfish.com/blog/2017/03/29/google-cloud-container-builder-introduction/

I played with it and it's a concise way to do your CI. It's also alot faster than others.

**Comment by caarlos0** [comment]
in theory you should be able to call goreleaser and it should work... 

I don't know what is the issue here exactly...

**Comment by gedw99** [comment]
None really.
Just more thinking me and others need examples of how to integrate into
different CI and CAN systems.

I can send you the script when done.

You also might be interested in the bitrise golang code for integration
into goreleaser.
It builds mobiles. If you want I can send you that script too.

**Comment by caarlos0** [comment]
@gedw99 understood.

well, feel free to open a PR adding it to the docs if you want to :) other user would probably appreciate :P 

Since there is nothing I can do here, I'll close the issue. Feel free to reopen if needed.
