### ISSUE TITLE
issue template formatting issues

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#4320]
when pasting the output of `goreleaser --version` in the appropriated field, it seems that github always adds an extra code block close after it, which breaks the formatting of the issue.

Investigate and fix 🙏🏻

**Comment by pantuza** [comment]
Hi, does this issue still happens?

I have tried creating a new issue (type bug) on this [page](https://github.com/goreleaser/goreleaser/issues/new?assignees=caarlos0&labels=bug%2Ctriage&projects=&template=bug.yaml). 
Then I fill the field "goreleaser version" with the following output:

```bash
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.21.2
GitCommit:     26fed97a0defe4e73e3094cb903225d5445e5f0d
GitTreeState:  dirty
BuildDate:     2023-09-26T11:20:15
BuiltBy:       homebrew
GoVersion:     go1.21.1
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

And basically nothing as described in this issue happens. No extra code blocks appears. 
May the error be from stale page javascript that is no longer failing?
Can you share if this is still an Open Issue? Or at least how to reproduce the problem?

Thanks in advance, bro.

**Comment by caarlos0** [comment]
just tried to repro it too, didn't happen... maybe github fixed it... 

thanks for the ping, closingg :D
