### ISSUE TITLE
failed to build ... exit status 1: cmd/decode.go:8:2: package log/slog is not in GOROOT

### ISSUE THREAD

**Issue by pete911** [goreleaser/goreleaser#4323]
### What happened?

When building project with goreleaser action, the action fails with the following error:
`failed to build for darwin_arm64: exit status 1: cmd/decode.go:8:2: package log/slog is not in GOROOT (/opt/hostedtoolcache/go/1.20.8/x64/src/log/slog)`

Action downloads latest goreleaser: `Downloading https://github.com/goreleaser/goreleaser/releases/download/v1.21.0`, starts building, but then fails with the above error. It looks like it is still using older go version (1.20.8) from cache.

### How can we reproduce this?

Run github action goreleaser-action@v5 (latest) with latest goreleaser distribution (I tried to set version to v1.21.0 as well, but I got the same error). Project that is being built import slog package - https://go.dev/blog/slog.

### goreleaser version

```bash
v1.21.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
You likely need to adjust the install-go action to use go 1.21


If you go build in your pipeline outside of goreleaser you'll get the same error.
