### ISSUE TITLE
Fails to parse aur private_key

### ISSUE THREAD

**Issue by seriousm4x** [goreleaser/goreleaser#4344]
### What happened?

I'm trying to publish an aur package but goreleaser fails to validate the private_key:

```bash
arch user repositories: git: could not stat private_key: stat $***
***
***
***
: no such file or directory
Error: The process '/opt/upsnap-actions-runner/_work/_tool/goreleaser-action/1.21.2/x64/goreleaser' failed with exit code 1
```

This is my config: https://github.com/seriousm4x/UpSnap/blob/master/backend/.goreleaser.yaml

 I've set `${{ secrets.AUR_KEY }}` to the contents of the private key in my repo and set the env var `AUR_KEY` for goreleaser here: https://github.com/seriousm4x/UpSnap/blob/master/.github/workflows/release.yml#L66 (basically exactly how the goreleaser repo does it). I made sure that there are no whitespaces to the left and right and also tried with and without new line at the end of the key.

I did a little debugging on how goreleaser parses the private key. [Here](https://github.com/goreleaser/goreleaser/blob/fa835ccda87b1ecde34c047f72cd2551b7b51467/internal/client/git.go#L159) it checks if the private key is valid. Not quite sure why, but this check fails, then skips the whole `if err == nil` block and then runs `os.Stat(path)`  while `path` is still the string of the private key.

The error is caused by [this line](https://github.com/goreleaser/goreleaser/blob/fa835ccda87b1ecde34c047f72cd2551b7b51467/internal/client/git.go#L189) in goreleaser. It tries to `os.Stat()` the key contents which fails. 

Here is a complete log of my Github action: https://gist.github.com/seriousm4x/28bb4f0d5e12776aa9ca839ba82dbcf6

### How can we reproduce this?

Pass a privatekey as string to [this function](https://github.com/goreleaser/goreleaser/blob/fa835ccda87b1ecde34c047f72cd2551b7b51467/internal/client/git.go#L152).

I've tested this locally and it only fails when there is whitespace to the left on each line.
Bizarrely it also fails when I use the Github secret which has no whitespace to the left or right.

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.21.2
GitCommit:     26fed97a0defe4e73e3094cb903225d5445e5f0d
GitTreeState:  false
BuildDate:     2023-09-26T11:20:15Z
BuiltBy:       goreleaser
GoVersion:     go1.21.1
Compiler:      gc
ModuleSum:     h1:dgYtIS7aZlQuRMUMLCjDCOs4lWss85Oh60RDSO0rbWU=
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
goreleaser's template syntax doesn't need the `$` prefix, which is why its failing.

https://github.com/seriousm4x/UpSnap/blob/master/backend/.goreleaser.yaml#L66

change this line and you should be good.
