### ISSUE TITLE
Unable to build rpms for c-shared library

### ISSUE THREAD

**Issue by jkroepke** [goreleaser/goreleaser#4346]
### What happened?

I have a repository with an configuration to build an binary and a c-shared library. nfpm is confiured to provide deb/rpm packages.

https://github.com/jkroepke/openvpn-auth-oauth2/tree/v1.8.0-rc.4

I triggered a release using the configuration

https://github.com/jkroepke/openvpn-auth-oauth2/blob/v1.8.0-rc.4/.goreleaser.yaml

and got the error

>   ⨯ release failed after 46s                 error=no linux binaries found for builds [openvpn-auth-oauth2.so]

https://github.com/jkroepke/openvpn-auth-oauth2/actions/runs/6410470783/job/17403879409

Removing the nfpm configuration for the second build gives no error back

### How can we reproduce this?

clone https://github.com/jkroepke/openvpn-auth-oauth2
checkout v1.8.0-rc.4
run github action on tag v1.8.0-rc.4 OR run goreleaser release. (build only works on a linux system)

### goreleaser version

```bash
v1.21.2 (from gh action output)
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

The nfpm configuration for the binary build works fine.

Mentionable is that in .goreleaser I define the name of the binary (https://github.com/jkroepke/openvpn-auth-oauth2/blob/8e9c0830779dfc644f3309bc7c8b54d7801e62fc/.goreleaser.yaml#L13), but since its an c-shared build, the .so suffix is attach to the file. Maybe thats the root cause

**Comment by jkroepke** [comment]
Hi @caarlos0,

with `meta: true`, the linux packages does not contain the binary and the shared library which are build by goreleaser before.

**Comment by caarlos0** [comment]
ah, right, sorry, I misunderstood the problem

**Comment by caarlos0** [comment]
okay, so, basically, we should support adding libraries to nfpm packages too instead of just binaries.

**Comment by caarlos0** [comment]
what you think would be a good api for this?

we have `nfpms[x].bindir` to set the directory in which the binary will go (default `/usr/bin`), should we do the same for shared libraries?

also worth mentioning that we can have headers, c-shared and c-archive, not sure if they usually go to different folders or not.

---

on a side note, this further adds to a point I made previously somewhere: we need to improve all this for v2.

**Comment by jkroepke** [comment]
Your proposal sounds good to me.

Could it be possible to address the c-libaries in content for now and do an overhoul in v2 as you mention?

Otherwise header and lib dir maybe sufficent for now.

**Comment by caarlos0** [comment]
> Could it be possible to address the c-libaries in content for now and do an overhoul in v2 as you mention?

I think it should be possible if you know the path inside `dist`

And I also rather do this "right" for v2. I started a RFC https://github.com/orgs/goreleaser/discussions/4407

**Comment by caarlos0** [comment]
what do you think about #4587?
