### ISSUE TITLE
GoReleaser Pro for Air Gapped Environments License Key Verification

### ISSUE THREAD

**Issue by ryancurrah** [goreleaser/goreleaser#4371]
### Is your feature request related to a problem? Please describe.

Our company is restricting internet access for builds.  

### Describe the solution you'd like

Support for offline license key verification.

### Describe alternatives you've considered

Nothing.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

License key verification URL not working in an air gapped environment: https://api.gumroad.com/v2/licenses/verify

**Comment by caarlos0** [comment]
Its a good idea, I don't have a solution for it though... open to suggestions though.

**Comment by ryancurrah** [comment]
My only thought is a custom license check implementation or maybe gumroad has some guidance for offline key checks.

**Comment by caarlos0** [comment]
> My only thought is a custom license check implementation or maybe gumroad has some guidance for offline key checks.

unfortunately, it seems that only online validation...

One thing I could think off is something that makes an "air gapped key" from a valid key, in some format that contains an expiration date... then the air-gapped keys would be short-lived (1 day or something like that), and you wouldn't be able to gen one without a valid license.

That idea would be hell to maintain if the user (you) had to update it manually, unless we consider that the key generation could access the internet to gen the key, and pass it down to the rest of thing, which is air-gapped... but I never worked with air-gapped CI, so I don't know whats common or not...

**Comment by caarlos0** [comment]
sorry, but I don't think there's much I can do here

please let me know if I can help in any other way
