### ISSUE TITLE
`VERSION=v1.21.2 DISTRIBUTION=pro` does not install pro version

### ISSUE THREAD

**Issue by brianstrauch** [goreleaser/goreleaser#4374]
### What happened?

If `DISTRIBUTION=pro` is provided, I would expect the pro version to be downloaded.

### How can we reproduce this?

Fails:
```
curl -sfL https://goreleaser.com/static/run | VERSION=v1.21.2 DISTRIBUTION=pro bash
```
Succeeds:
```
curl -sfL https://goreleaser.com/static/run | VERSION=v1.21.2-pro DISTRIBUTION=pro bash
```

### goreleaser version

```bash
N/A
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

(Another small nit: `curl -sfL https://goreleaser.com/static/run | VERSION=v1.21.2-pro bash` says "Using the OSS distribution...")

**Comment by caarlos0** [comment]
thanks!

check #4375
