### ISSUE TITLE
Default ldflags are getting removed when custom ldflags are used

### ISSUE THREAD

**Issue by charankamarapu** [goreleaser/goreleaser#4377]
### What happened?

When I add a custom ldflag like below,  the default ldflags like `version` are not getting injected into the binary. 

```
 ldflags:
      - -s -w -X main.Dsn={{.Env.SENTRY_DSN_BINARY}}
```
Is there any work around except adding version also into ldflags?

### How can we reproduce this?

1. Add custom ldflag.
2. access default ldflags like version in the code.

### goreleaser version

```bash
v1.21.2
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
this is expected behavior, you'll need to add the default ldflags you want to keep.
