### ISSUE TITLE
kos don't seem to infer main from build correctly

### ISSUE THREAD

**Issue by eddycharly** [goreleaser/goreleaser#4382]
### What happened?

We tried to use the `kos` section to build images with a main.go in a subfolder of the repo.

We specified `main` in the build and referenced the build from the `kos` section but it doesn't seem to infer the setting.

See https://github.com/kyverno/chainsaw/blob/main/.goreleaser.yaml

### How can we reproduce this?

The config file we use is visible at https://github.com/kyverno/chainsaw/blob/main/.goreleaser.yaml

Failing run logs https://github.com/kyverno/chainsaw/actions/runs/6638453325/job/18034825927

### goreleaser version

```bash
v1.21.2
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I'll take a look when I get some time

**Comment by eddycharly** [comment]
Thanks @caarlos0 

I managed to make it work, using `kos` requires that the `build` is configured in a way that is compatible with the `ko` tool though.

**Comment by eddycharly** [comment]
This config works https://github.com/kyverno/chainsaw/blob/main/.goreleaser.yaml

Notable change is the way `main` is specified in the `build` config https://github.com/kyverno/chainsaw/blob/9b1a85b2da6c064b3582454b462c608e64bc1836/.goreleaser.yaml#L14

**Comment by caarlos0** [comment]
ah, yes, the build goes a step further trying to look for main funcs in the cwd, which I guess ko does not.

Probably we could run this (the `checkMain` func) in the builder `Default` method so it passes down to ko too.

**Comment by eddycharly** [comment]
Looks like ko expects a relative path to a folder, things like `cmd`, `cmd/main.go` or `./cmd/main.go` don't seem work with ko, only `./cmd`.

A more strict validation with a useful message explaining what is wrong would be great.
Or just some words about that in the docs ?

**Comment by caarlos0** [comment]
ah, gotcha, I think probably try to validate it better + docs

**Comment by gabrielcipriano** [comment]
The path must always be relative? or only when used with Ko?

**Comment by eddycharly** [comment]
> In `builds.main` The path must always be relative? or only when used with Ko?

It's a `ko` requirement, I don't think it applies when ko is not used.
