### ISSUE TITLE
`checksum` file unsorted

### ISSUE THREAD

**Issue by mirabilos** [goreleaser/goreleaser#4384]
### What happened?

[checksum files generated by goreleaser](https://github.com/superseriousbusiness/gotosocial/releases/download/v0.12.1/checksums.txt) are unsorted.

They ought to be sorted by filename (i.e. second field), ASCIIbetically.

### How can we reproduce this?

Build a project with multiple files.

### goreleaser version

```bash
I don’t know, I didn’t run it myself, I’m just consuming the results of such builds.
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
weird, I kinda remember this being implemented many years ago, will investigate tomorrow..

thanks for reporting!

**Comment by caarlos0** [comment]
ahh, it is sorting as strings, so, in checksum order instead of filename order...

probably need to provide a custom `less` func and use `sort.Slice` in `checksums.go:139` 🤔
