### ISSUE TITLE
Unable to post release to gitlab.com (401 Unauthorized)

### ISSUE THREAD

**Issue by zwindler** [goreleaser/goreleaser#4387]
### What happened?

Hello,

I'm trying to push releases to gitlab.com and I'm unable to make it work...

```
  • publishing
    • scm releases
      • creating or updating release                 tag=0.0.3 repo=
      • refreshing checksums                         file=tifling_checksums.txt
  ⨯ release failed after 1s                  error=scm releases: failed to publish artifacts: GET https://gitlab.com/api/v4/projects/dt.germain/tifling/releases/0.0.3: 401 {message: 401 Unauthorized}
```

I followed the https://goreleaser.com/scm/gitlab/ page which states that you have to create either a personal token or a project token with api scope

![image](https://github.com/goreleaser/goreleaser/assets/1246797/7485240b-aea9-4469-ad7f-96b084a49e97)
![image](https://github.com/goreleaser/goreleaser/assets/1246797/99e91b75-5ef7-4d57-b982-882c2615ae50)

I've tried both and in each case I get a 401. I also tried to add (in both cases) 

```
gitlab_urls:
  use_package_registry: true
```

My environment file seems to be correctly set since goreleaser reports it in the log

```
  • loading environment variables
  • using token from  /home/dgermain/.config/goreleaser/gitlab_token 
```

I've triple checked the content and recreated tokens many times, to no avail. Am I missing something/doing something wrong?

Thanks

### How can we reproduce this?

https://gitlab.com/dt.germain/tifling/-/tree/0.0.3

### goreleaser version

```bash
goreleaser --version
*  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.21.2
GitCommit:     26fed97a0defe4e73e3094cb903225d5445e5f0d
GitTreeState:  false
BuildDate:     2023-09-26T11:20:15Z
BuiltBy:       goreleaser
GoVersion:     go1.21.1
Compiler:      gc
ModuleSum:     h1:dgYtIS7aZlQuRMUMLCjDCOs4lWss85Oh60RDSO0rbWU=
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
did you check these issues?

- https://github.com/goreleaser/goreleaser/issues/2469
- https://github.com/goreleaser/goreleaser/issues/2356

**Comment by zwindler** [comment]
ok... stupid mistake, sorry for taking your time

I compared my working github config files and found the mistake instantly. The formating was wrong in my gitlab one...

I had added "GITLAB_TOKEN=" and then the token, while it should have been only the token

Again, sorry for the mistake, closing the ticket

**Comment by caarlos0** [comment]
No problem, glad you figured it out 🙏
