### ISSUE TITLE
Config schema invalid

### ISSUE THREAD

**Issue by adrianrudnik** [goreleaser/goreleaser#4402]
### What happened?

I installed Webstorm new and got the default configs, opened up my existing project and my `.golreleaser.yaml` got yellowed hard.

![image](https://github.com/goreleaser/goreleaser/assets/681514/a169e2a9-ba81-4983-a663-e1b9b43bab6a)

Yet adding that field, nets me an error when running the app:

```
line 9: field version not found in type config.Project
```

The schema file at https://goreleaser.com/static/schema.json references `#/$defs/Project`. That leads to

```json
{
  "version": {
    "type": "integer",
    "enum": [
      1
    ],
    "default": 1
}
```

which means 1 is required to be set. As statet in https://json-schema.org/understanding-json-schema/reference/annotations

> The default keyword specifies a default value. This value is not used to fill in missing values during the validation process. Non-validation tools such as documentation generators or form generators may use this value to give hints to users about how to use a value. However, default is typically used to express that if a value is missing, then the value is semantically the same as if the value was present with the default value. The value of default should validate against the schema in which it resides, but that isn't required.

There a several problems with this:

- `default` is not used for validation purposes, so the validator must mark it.
- The application will fail with a `default` value of `1`, the schema defines it as mandatory (either by hand or fallback) but the programm itself will fail currently.
- The default value of the keyword must still work, but `goreleaser check` without it does not fail, but the app fails.

Not sure what happend with the `version` attribute.

### How can we reproduce this?

Not much to reproduce, maybe run it against a validator. They must ignore default values by definition.

### goreleaser version

```bash
GitVersion:    1.21.2
GitCommit:     26fed97a0defe4e73e3094cb903225d5445e5f0d
GitTreeState:  false
BuildDate:     2023-09-26T11:20:15Z
BuiltBy:       goreleaser
GoVersion:     go1.21.1
Compiler:      gc
ModuleSum:     h1:dgYtIS7aZlQuRMUMLCjDCOs4lWss85Oh60RDSO0rbWU=
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
yeah, we should fix the schema so it only runs on tags, main might give wrong information sometimes...
