### ISSUE TITLE
`ko` publishing snapshots 

### ISSUE THREAD

**Issue by abh** [goreleaser/goreleaser#4418]
### Is your feature request related to a problem? Please describe.

It'd be a useful feature to be able to publish a ko builds (they can be published "locally", too) without having to set a tag.

For all the other builds this is possible with `--snapshot`, but `ko` builds don't get run with that setting.

### Describe the solution you'd like

This feature would be useful, for example, for a "nightlies" type build.

### Describe alternatives you've considered

I have a separate ko workflow for this, but I'd like to keep all the builds configured the same (in .goreleaser).

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
for nightlies there is the `nightly` feature: https://goreleaser.com/customization/nightlies/

snapshots on goreleaser are meant to not be published

that said, I need to check if nightlies are supporting KO as of this moment, if not I'll implement it.
