### ISSUE TITLE
`linkedin: could not get profile id: could not find 'id' in result`

### ISSUE THREAD

**Issue by stefanlogue** [goreleaser/goreleaser#4421]
### What happened?

Trying to use the LinkedIn announce feature, I've supplied my access token in my workflow and passed it to the Github Action. The releases all pass, then the announce fails with the error in the title. Am I doing something wrong, or is there any further setup that needs to be done on my side for this to work? The docs for this were pretty lacking

### How can we reproduce this?

https://github.com/stefanlogue/meteor

My public repo that reproduces the issue currently

### goreleaser version

```bash
1.22.1
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hmm, maybe linkedin changed their API 🤔 

cc/ @Dentrax

**Comment by stefanlogue** [comment]
@gabrielcipriano any idea how to get any of these permissions? The dashboard for adding permissions doesn't allow manually adding them (as far as I can see) and you need to do it through the process of adding "Products" to your app, which then add relevant scopes (although this is quite opaque, it doesn't say which scopes will be added for each Product).

It looks like they've made it more difficult to request scopes.

**Comment by gabrielcipriano** [comment]
hey @stefanlogue, I found [this discussion](https://github.com/decioferreira/omniauth-linkedin-oauth2/issues/45#issuecomment-1723116394) and  @caarlos0 is right, they changed their api. They deprecated `/v2/me` in favor of `v2/userinfo`, so new applications will not have old permissions such as `r_liteprofile`.

`v2/userinfo` needs the new permission `profile`

I will open a PR with the needed changes.

**Comment by stefanlogue** [comment]
Thanks for this, all working as expected now!

**Comment by stefanlogue** [comment]
Got another error with this recently:
```
linkedin: could not get profile URN: could not get profile sub: could not find 'sub' in result: %!w(<nil>)
```
Havent't changed anything since it was previously working

**Comment by caarlos0** [comment]
:pain: 

did they change their api again?

PS: I fixed the issue in the error message (the nil error `%w` thing)

**Comment by stefanlogue** [comment]
Is there a way to have the action step still pass after the announce fails? I'd love to continue to test this out on my project but don't want the whole action to fail if this fails as it's not really overly important, the tool is still released on homebrew by this stage

**Comment by caarlos0** [comment]
currently it isn't, but maybe we could add a `allow_failure` or something like that to the config
