### ISSUE TITLE
Pre hook failure should show command output

### ISSUE THREAD

**Issue by jsirianni** [goreleaser/goreleaser#4451]
### Is your feature request related to a problem? Please describe.

We have a pre hook that is faiing for an unknown reason in CI, not reproducible locally.

```
  ⨯ release failed after 2m24s               error=before hook failed: hook failed: failed to run 'make release-licenses': exit status 2
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.22.1-pro/x64/goreleaser' failed with exit code 1
```

### Describe the solution you'd like

It would be nice if the pre hook failure was logged to the terminal.

### Describe alternatives you've considered

Running the command on its own, before running Goreleaser.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
thanks, should be better on `main` 🙏
