### ISSUE TITLE
use commitlint probot instead of gitcop

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#446]
pros:

- gitcop has its config via web interface while commitlint probot is configurable via config files
- commitlint seems more versatile

cons:

- ?

@jorinvo what do you think?

**Comment by caarlos0** [comment]
actually seems like right now the commitlint bot don't read the config files https://github.com/ahmed-taj/commitlint-bot/issues/1

**Comment by ahmed-taj** [comment]
Hey @caarlos0, glad you like commitlint bot.

Yes, it doesn't support custom confrontation yet, I'm working on it, with help of @marionebl the author of commitlint  package

Disclaimer: I didn't use Gitcop but I can see it's a business so I will assume there is an effort to keep the service running 24/7. But for my commitlint bot, I can't afford hosting costs, so it will only be running on a free plan of Heruko (or similar services), I can't promise service availability.

The good news is that the project is open source under MIT, and you can always host your own instance :)

**Comment by caarlos0** [comment]
@jorinvo hello 👋 can you give me permissions on gitcop? I can't edit anything..

I would like to remove the need of a commit body... it is extremely annoying while doing big refactories.

Also the bot is commenting 2 times for every commit...

**Comment by caarlos0** [comment]
> Also the bot is commenting 2 times for every commit...

oh: it was because the webhook was duplicated... just removed one... should be ok now...

**Comment by jorinvo** [comment]
@caarlos0 I disabled the required body. 

The Gitcop interface seems super basic. Can't see any way to add multiple people. If you like, you can setup a new account and I remove mine. But adding two people doesn't seem to work unfortunately :/

**Comment by jorinvo** [comment]
Can also setup commitlint of course. Can see if it does everything we want. Then we can remove Gitcop all together. For me it doesn't really matter since they seem to just do their job, both of them :D

**Comment by caarlos0** [comment]
thanks @jorinvo, commitlint is not configurable yet :/

when they do that, I'll be glad to make the migration, since we can then have the config as code =)

**Comment by caarlos0** [comment]
not stale

**Comment by caarlos0** [comment]
it is not a problem right now, let's ignore this for now
