### ISSUE TITLE
GitLab CI: Documentation and tokens

### ISSUE THREAD

**Issue by ysmilda** [goreleaser/goreleaser#4474]
### What happened?

goreleaser requires both `GITLAB_TOKEN` and `CI_JOB_TOKEN` when used in a GitLab CI with docker releases as described [here](https://goreleaser.com/ci/gitlab/#releasing-archives-and-pushing-images). If the `GITLAB_TOKEN` is set to mirror `CI_JOB_TOKEN` and the `use_job_token` option is set in the `.goreleaser.yaml` it is necessary to pass both variables to the docker container.

What I would have expected to happen is that goreleaser would use the `GITLAB_TOKEN` as if it was the `CI_JOB_TOKEN`. This is what I understood from the documentation at least.

I get why the choice was made for the current method because this enables the use of goreleaser without setting any additional CI variables, however I would update the documentation or fall back on the `GITLAB_TOKEN` as the `CI_JOB_TOKEN` when the `use_job_token` option is set.

With the current implementation of the [useJobToken](https://github.com/goreleaser/goreleaser/blob/main/internal/client/gitlab.go#L500) function I think updating the documentation would the easier route to take.

### How can we reproduce this?

Follow the instructions from [the documentation](https://goreleaser.com/ci/gitlab/#releasing-archives-and-pushing-images) and [the accompanying repository](https://gitlab.com/goreleaser/example) and add releasing to the GitLab package registry. This will fail with:
```bash
error=scm releases: failed to publish artifacts: GET https://localgitlabinstance/api/v4/projects/group/project/releases/v0.2: 401 {message: 401 Unauthorized}
```

### goreleaser version
```
GitVersion:    1.22.1
GitCommit:     52d976beaea9ba8a5b0f09f90f22135b468c33c2
GitTreeState:  false
BuildDate:     2023-11-08T23:40:43Z
BuiltBy:       goreleaser
GoVersion:     go1.21.4
Compiler:      gc
ModuleSum:     h1:7+P9DHpKPmg160mni77AC6x43tch0DKNqULIfrYRyOU=
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
yeah, gitlab is confusing, the docs were not updated after the use_job_token thing (I believe).

Just added it to the example, let me know if you think something more should be added.

Thanks for the issue, and sorry for the delay 🙏
