### ISSUE TITLE
Publishing to winget without archiving

### ISSUE THREAD

**Issue by vedantmgoyal2009** [goreleaser/goreleaser#4494]
### Is your feature request related to a problem? Please describe.

Winget support in GoReleaser fails when `archive: [ format:binary]` is set.

### Describe the solution you'd like

Instead,  GoReleaser should create manifests, with a direct URL to the binary, replacing `InstallerType: zip` with `InstallerType: portable` and omitting NestedInstaller fields.

### Describe alternatives you've considered

N/A

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
can you check #4498?
