### ISSUE TITLE
nix setup does not validate licenses

### ISSUE THREAD

**Issue by till** [goreleaser/goreleaser#4496]
### What happened?

So for private code, I think the best "bet" is to set the license to `unfree`.

But that's only what I found out after the fact — I set it to "proprietary" at first.

I am not sure if there's a better one to use, as I only read through the [licenses.nix](https://github.com/NixOS/nixpkgs/blob/master/lib/licenses.nix) in the nixpkgs repo.

Anyway, having said all this, it would be nice if the pipeline could validate this, or maybe the config should do that? Or, add a little docs page how to distribute private code in form of documentation? Do you have any thoughts on this? I looked at the code, it seems like the license value is passed into the template that's rendered and that's it.

Also, not entirely sure if that's something that can be fixed in code. So a docs thing would work, IMHO? I can try to add something here: https://github.com/goreleaser/goreleaser/blob/c4dafdf55e8f1961ef20420d5d3514c6104046f9/www/docs/customization/nix.md

### How can we reproduce this?

Set license to `proprietary` and watch the nur _fail_ to build:

```
       error: attribute 'proprietary' missing
| 
|        at /Users/till/Documents/workspaces/reponur/pkgs/tool/default.nix:49:15:
| 
|            48|     homepage = "https://example.org/";
|            49|     license = lib.licenses.proprietary;
|              |               ^
|            50|

```

### goreleaser version

```bash
current
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
we could do something like this:

```bash
nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
```

but it'll only work if the files have already been uploaded... so... not very useful, I think.

We might need to replicate the license list into goreleaser to prevent these issues 🤔

**Comment by caarlos0** [comment]
see #4497

**Comment by till** [comment]
Wow, you're fast. I didn't expect anything so soon. 😁 But yeah, the generator seems to make sense. That could work.

**Comment by till** [comment]
🚀 Thank you! Happy holidays!
