### ISSUE TITLE
Setting `wrap_in_directory: true` in archives breaks `aurs` Arch pkgs

### ISSUE THREAD

**Issue by blacktop** [goreleaser/goreleaser#4500]
### What happened?

If you set `wrap_in_directory: true` you also need to add an extra `cd into dir` to the steps of the `package:` fields.

### How can we reproduce this?

Set `wrap_in_directory: true` and create a arch pkgs

### goreleaser version

```bash
❯ goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.22.1
GitCommit:     52d976beaea9ba8a5b0f09f90f22135b468c33c2
GitTreeState:  false
BuildDate:     2023-11-08T23:40:43Z
BuiltBy:       goreleaser
GoVersion:     go1.21.4
Compiler:      gc
ModuleSum:     h1:7+P9DHpKPmg160mni77AC6x43tch0DKNqULIfrYRyOU=
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I guess this really isn't `goreleaser`'s fault, but maybe needs a NOTE in the docs?

Do you know what template vars I should use to tell it what the folder would be to know what folder to `cd` into?  

Maybe I could just change the install steps to be something like:

```yaml
    package: |-
      # bin
      install -Dm755 "*/ipsw" "${pkgdir}/usr/bin/ipsw"
```

?

**Comment by caarlos0** [comment]
hi!

thanks for reporting this, #4502 should do the trick
