### ISSUE TITLE
Release docker image when go new mainline version released

### ISSUE THREAD

**Issue by CoiaPrant233** [goreleaser/goreleaser#4501]
### Is your feature request related to a problem? Please describe.

Release docker image when go new mainline version released

### Describe the solution you'd like

Now latest goreleaser is go v1.21.3, latest is go v1.21.5

I think add a nightly tag without goreleaser version, that ci will auto pull latest nightly image

### Describe alternatives you've considered

Use nightly build

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
yeah, this is a good idea, will work on it, thanks!
