### ISSUE TITLE
Unlicensed indirect dependency

### ISSUE THREAD

**Issue by matthiasr** [goreleaser/goreleaser#4520]
### What happened?

The dependency [sasha-s/go-csync](https://github.com/sasha-s/go-csync), an indirect dependency via [disgo](https://github.com/disgoorg/disgo), introduced in #3320, does not have an open source license. A repository being public is [not enough](https://opensource.guide/legal/#are-public-github-projects-open-source).

This unfortunately means that it cannot be used in open source projects such as this one. Upstream issues: sasha-s/go-csync#4, disgoorg/disgo#329.

### How can we reproduce this?

N/A

### goreleaser version

```bash
1.11.0 and later
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

[FOSSA](https://fossa.com) flags this:

> This package contains unlicensed code, which by default is copyrighted to the original author. You may not use these dependencies without first obtaining a license.

**Comment by caarlos0** [comment]
ouch, thanks for bringing this to my attention!

I'll subscribe to the upstream issue, if they don't solve it I'll probably end up replacing disgo with something else, as we only use the post feature...
