### ISSUE TITLE
Use stdenvNoCC over stdenv in generated nix package

### ISSUE THREAD

**Issue by shyim** [goreleaser/goreleaser#4538]
### Is your feature request related to a problem? Please describe.

Right now the generated nix file is using `stdenv`  and this contains a lot of other dependencies like gcc, awk and so on. We don't need that all as we just download our generated tar file and unpack and may install our shell completions.

### Describe the solution you'd like

Replace current `stdenv` with `stdenvNoCC` or we add a flag to the yaml to enable this.

### Describe alternatives you've considered

override the input, but it's read from pkgs, so it's annoying to do that

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I can work on that, just created an issue to get early feedback before working on it.

**Comment by caarlos0** [comment]
thanks, done on https://github.com/goreleaser/goreleaser/commit/003a8815038db80ebfd5798c741c1c482e607ac9
