### ISSUE TITLE
Add container digest(s) to artifacts.json

### ISSUE THREAD

**Issue by alexlovelltroy** [goreleaser/goreleaser#4545]
### Is your feature request related to a problem? Please describe.

I have a tool that performs build attestation based on the digest of a container.  I'm running it as a stage in my github actions workflow.  If artifacts.json includes the digest, I'll be able to seamlessly go from goreleaser into the subsequent step.

### Describe the solution you'd like

I'd like to see the digest of any containers built via goreleaser to be listed in the artifacts.json and therefore available through the github action for goreleaser for subsequent signature and attestation steps.

### Describe alternatives you've considered

Without the digest available as an artifact of the build, I end up needing to query the container repository for the newest container and using that which isn't ideal.  I also tried doing builds without goreleaser and found that achieving the same outcomes required a lot more effort on my end.  goreleaser is the easy button and I'd prefer to use it.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Any attestation/SBOM/signatures that happen outside of goreleaser core will need the digest easily available as well.

**Comment by caarlos0** [comment]
upon further investigation, they should already be there.

`goreleaser release` will build and push the images, and the digest will be in the `DockerImage` artifact in `dist/artifacts.json`:

```console
$ jq -r '.[] | select(.type=="Published Docker Image") | "\(.name)\t\(.extra.Digest)"' dist/artifacts.json
caarlos0/goreleaser-test-digest:1.0.1   sha256:7de17afe9efc3d7c4b4fe07f09f5ab00a1dda6d898d5e11353e189eae7ead2e3
```
