### ISSUE TITLE
Redesign context package

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#455]
Right now, our `context` package is bloated and is complex. It is starting to "poison" other portions of the code because it was not very well thought.

The most critical part is the `binaries`, `artifacts`, `dockers`, `brews` and etc part.

Most of the packages code is to deal with those things.

- Binaries are supposed to be the artifacts built by `go build`.
- Artifacts is supposed to be anything that should be uploaded to github (or other providers in the future maybe).
- Dockers are docker images.
- Brews are brew taps (this isn't even working as it seems).

The biggest challenge in redesigning this would be to deal with the variable information between types:

### A binary has:

- Name: `goreleaser`, `goreleaser.exe`
- Path: `dist/goreleaser_linux_amd64/goreleaser`
- Platform: linuxamd64, darwinamd64
- Folder: `goreleaser_linux_amd64` (I'm not even sure why this is needed at all)
- BuildName: `goreleaser` - or something like `goreleaser_linux_amd64` when archive type is `binary`

### An artifact has:

- Name: `goreleaser_linux_amd64.deb`
- Path: `dist/goreleaser_linux_amd64.deb`

### A brew has:

- tap: `goreleaser/tap/goreleaser` (naming could be better)

### A docker has:

- image: `goreleaser/goreleaser:v1.2.3`

Suggestions?

---

might ref #453

**Comment by magiconair** [comment]
An artifact can also just be the binary, e.g. `goreleaser_linux_amd64` and you need to take into account that allowing env vars in name templates make the artifact names less predictable since they depend on external variables. (go version in the binary name). This can have implications for downstream pipelines like docker which depend on previously built artifacts. 

The other downstream issue are the checksums which need to reference the artifacts (since that is what the users are downloading) but are currently computed over the binaries.

**Comment by caarlos0** [comment]
so, the build pipe builds the binaries.

i think that after that all other things are artifacts - including the binaries when archive mode is binary. In that case, the archive pipe adds the binaries as artifacts as well (like what happens today).

so we may still have two types of things here:

- *build artifacts*: what came out from the build pipe
- *upload artifacts*: everything else

**Comment by andygrunwald** [comment]
I think it would be quite useful to store information like Platform, OS, Arch and Arm as separate fields in the context per artifact.
In this way the pipelines can use this to offer more possibilities to use templates in configurations and enable custom behaviour.

E.g. the Artifactory pipeline can benefit from it.
