### ISSUE TITLE
Remove `on_macos do` from Homebrew Formula when only macOS binary is built 

### ISSUE THREAD

**Issue by 5ouma** [goreleaser/goreleaser#4561]
### Is your feature request related to a problem? Please describe.

GoReleaser adds the `on_macos do` condition even if there are only binaries for macOS.
Homebrew warns that it might have a section for Linux by `brew readall`.

### Describe the solution you'd like

Generate a Homebrew Formula without `on_macos do` or `on_linux do` when only their binaries are built on `goos`.

```shell
Error: Invalid formula (x86_64_linux):
formulae require at least a URL
```

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
see #4562
