### ISSUE TITLE
Support updating the the Docker overview markdown content

### ISSUE THREAD

**Issue by mvdan** [goreleaser/goreleaser#4608]
### Is your feature request related to a problem? Please describe.

We publish https://github.com/cue-lang/cue to both GitHub and Docker. This works fine, e.g. https://hub.docker.com/r/cuelang/cue/tags, but https://hub.docker.com/r/cuelang/cue is currently empty and is left that way.

### Describe the solution you'd like

Some way to tell goreleaser what markdown content to use as the overview.

I think this should default to the README.md when turned on. Docker Hub's auto-builds from GitHub do this.

One should also be able to configure a different markdown file or string to use instead, e.g. one might want a short markdown document explaining different image tag flavors and what they are for.

### Describe alternatives you've considered

Manually setting the overview markdown on Docker Hub. This is manual, and means that we wouldn't be able to directly maintain the markdown content in our source git repository, which we definitely want to do.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I'm a bit surprised that there isn't already a feature or feature request for this, but I did spend ten minutes trying to find one :)

**Comment by mvdan** [comment]
cc @myitcv

**Comment by mvdan** [comment]
Note that we manually copied over README.md for now :) It's fine and it works, but as we update README.md over time, it will get out of sync.

**Comment by mvdan** [comment]
It might be useful to look at https://github.com/peter-evans/dockerhub-description as well, which I've used in a couple of projects with GitHub as CI but without goreleaser.

**Comment by caarlos0** [comment]
hey @mvdan , just implemented this in the pro version, if you don't have a license yet, let me know and I'll give one to the cue team :)

**Comment by caarlos0** [comment]
FWIW: https://goreleaser.com/customization/dockerhub/
