### ISSUE TITLE
Error loading shared libraries after image is built

### ISSUE THREAD

**Issue by momentmaker** [goreleaser/goreleaser#4609]
### What happened?

We currently are currently using docker to build images but have been using goreleaser to release multi-arch images but it seems like for quite a while it hasn't been working (started about 9 months). I'm not sure we ever got it working.

It seems like goreleaser is building the images correctly but after the images has been built and when one `docker exec` into the container, we are getting this error:

```
❯ docker exec -it 50fcb3186357 /bin/bash
root@50fcb3186357:/home/root# chainlink -version
chainlink: error while loading shared libraries: /Users/momentmaker/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.2.4/internal/api/libwasmvm.aarch64.so: cannot open shared object file: No such file or directory
```

and this is from our CI run:

```
root@fea6e4a489dc:/home/root# chainlink -version
chainlink: error while loading shared libraries: /home/runner/go/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.2.4/internal/api/libwasmvm.aarch64.so: cannot open shared object file: No such file or directory
```

We do have a prehook script that runs to grab the wasmvm package with go which is working fine but it seems like when building it and we also have a posthook script that copies it into the `/libs` folder and it seems to work as well because it's in the container under the path `/usr/local/bin/libs/libwasmvm.aarch64.so`.

But when building the image it's using the go path of the runner whether be the local machine or the GHA container.

We have tried using 3 different versions of `zig` and none of them works.

```
0.10.1
0.11.0
0.12.0-dev.2619+5cf138e51
```

This is the `goreleaser_utils` file.

```
#!/usr/bin/env bash

# get machine / kernel name
_get_platform() {
  uname | tr '[:upper:]' '[:lower:]'
}

# get machine architecture name
# See https://github.com/joschi/asdf-java/blob/aarch64-support/bin/functions#L33
_get_arch() {
  arch="$(uname -m)"
  case "${arch}" in
  x86_64 | amd64) echo "x86_64" ;;
  aarch64 | arm64) echo "arm64" ;;
  *)
    echo "Unknown machine architecture: ${arch}"
    exit 1
    ;;
  esac
}

# get lib wasmvm path
_get_wasmvm_lib_path() {
  local -r platform="$1"
  local -r arch="$2"
  wasmvm_dir=$(go list -json -m all | jq -r '. | select(.Path == "github.com/CosmWasm/wasmvm") | .Dir')
  shared_lib_dir="$wasmvm_dir/internal/api"
  lib_name="libwasmvm"
  if [ "$platform" == "darwin" ]; then
    lib_extension="dylib"
  elif [ "$platform" == "linux" ]; then
    case "${arch}" in
    x86_64 | amd64) lib_extension="x86_64.so" ;;
    aarch64 | arm64) lib_extension="aarch64.so" ;;
    *) echo "Unsupported arch $arch" && exit 1 ;;
    esac
  else
    echo "Unsupported platform $platform"
    exit 1
  fi
  echo "$shared_lib_dir/${lib_name}.$lib_extension"
}

# global goreleaser before hook
# moves native libraries to temp directories used by docker images / archives
before_hook() {
  local -r lib_path=tmp
  # MOVE NATIVE LIBRARIES HERE
  local -r wasmvm_lib_path_linux_amd64=$(_get_wasmvm_lib_path "linux" "amd64")
  local -r wasmvm_lib_path_linux_arm64=$(_get_wasmvm_lib_path "linux" "arm64")
  local -r wasmvm_lib_path_darwin_amd64=$(_get_wasmvm_lib_path "darwin" "amd64")
  local -r wasmvm_lib_path_darwin_arm64=$(_get_wasmvm_lib_path "darwin" "arm64")
  mkdir -p "$lib_path/linux_amd64/libs"
  cp -f "$wasmvm_lib_path_linux_amd64" "$lib_path/linux_amd64/libs"
  mkdir -p "$lib_path/linux_arm64/libs"
  cp -f "$wasmvm_lib_path_linux_arm64" "$lib_path/linux_arm64/libs"
  mkdir -p "$lib_path/darwin_amd64/libs"
  cp -f "$wasmvm_lib_path_darwin_amd64" "$lib_path/darwin_amd64/libs"
  mkdir -p "$lib_path/darwin_arm64/libs"
  cp -f "$wasmvm_lib_path_darwin_arm64" "$lib_path/darwin_arm64/libs"
}

# binary build post hook
# moves native libraries to binary libs directory
build_post_hook() {
  local -r dist_path=$1
  local -r lib_path=$dist_path/libs
  local -r platform=$2
  local -r arch=$3
  # COPY NATIVE LIBRARIES HERE
  local -r wasmvm_lib_path=$(_get_wasmvm_lib_path "$platform" "$arch")
  mkdir -p "$lib_path"
  cp -r "tmp/${platform}_${arch}/"* "$lib_path/"
}

"$@"
```

### How can we reproduce this?

Here is the PR that is being worked on:
https://github.com/smartcontractkit/chainlink/pull/11847/files

You can use this command to build it locally:
`./tools/bin/goreleaser_wrapper release --snapshot --clean --config .goreleaser.develop.yaml`

This is the latest CI run which successfully builds the images:
https://github.com/smartcontractkit/chainlink/actions/runs/7820985842

### goreleaser version

```bash
GitVersion:    1.23.0-pro
GitCommit:     3973205d96767d1f1b0d378584a75697cad58444
GitTreeState:  clean
BuildDate:     2023-12-26T15:04:19Z
BuiltBy:       goreleaser
GoVersion:     go1.21.5
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
> chainlink: error while loading shared libraries: /Users/momentmaker/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.2.4/internal/api/libwasmvm.aarch64.so: cannot open shared object file: No such file or directory

It seems its trying to get the library from the wrong path? Maybe need to set `LDPATH`?

**Comment by caarlos0** [comment]
> This is the latest CI run which successfully builds the images:
> https://github.com/smartcontractkit/chainlink/actions/runs/7820985842

this ran on go 1.21, does the problematic builds use go 1.22? It's the one thing I can think of that changed recently.


GoReleaser does `go build` passing the args, GOOS, GOARCH, etc, and doesn't enforce any mod path or anything like that..

**Comment by momentmaker** [comment]
Thanks for the help @caarlos0!

The image builds fine through the CI but we have an extra file that was downloaded from a func in the prehook script here:

```
_get_wasmvm_lib_path() {
  local -r platform="$1"
  local -r arch="$2"
  wasmvm_dir=$(go list -json -m all | jq -r '. | select(.Path == "github.com/CosmWasm/wasmvm") | .Dir')
  shared_lib_dir="$wasmvm_dir/internal/api"
  lib_name="libwasmvm"
  if [ "$platform" == "darwin" ]; then
    lib_extension="dylib"
  elif [ "$platform" == "linux" ]; then
    case "${arch}" in
    x86_64 | amd64) lib_extension="x86_64.so" ;;
    aarch64 | arm64) lib_extension="aarch64.so" ;;
    *) echo "Unsupported arch $arch" && exit 1 ;;
    esac
  else
    echo "Unsupported platform $platform"
    exit 1
  fi
  echo "$shared_lib_dir/${lib_name}.$lib_extension"
}
```

which is suppose to download the `wasmvm` module get a get a specific file from it and store it as an artifact to be copied to the docker image.

The problem is when we run the binary of the image we had built it's using the gopath of the local machine that's downloading the go module to get that `libwasmvm.aarch64.so` file instead of getting it from the correct path where we specified to copy to: `/usr/local/bin/libs/libwasmvm.aarch64.so`.

Hence we get this error because the file exists in `/usr/local/bin/libs/libwasmvm.aarch64.so`.
```
root@fea6e4a489dc:/home/root# chainlink -version
chainlink: error while loading shared libraries: /home/runner/go/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.2.4/internal/api/libwasmvm.aarch64.so: cannot open shared object file: No such file or directory
```

Appreciate any insight that you may have.

**Comment by caarlos0** [comment]
yes, I noticed that too... this is extra weird, as [`trimpath`](https://github.com/smartcontractkit/chainlink/blob/0e564cdb2b48fa073538a5fd7cb058524722381d/.goreleaser.develop.yaml#L30) should take care of that


although, maybe you need to pass it to `gcflags` and/or `asmflags` too?

**Comment by momentmaker** [comment]
hmm do you mean to set it like this?
```
    # asmflags:
    #   - "all=-trimpath={{ .Env.GOPATH }}"
    # gcflags:
    #   - "all=-trimpath={{ .Env.GOPATH }}"
```
and provide/set the `GOPATH` in the the `goreleaser_wrapper` script?

sorry I'm rather new to `goreleaser` so bear with me. it seems like the dynamic linking of shared library is not a unique problem:
https://stackoverflow.com/questions/14560857/error-while-loading-shared-libraries-libsandbox-so

in the function `_get_wasmvm_lib_path()` that's being used in `prehook` and `posthook` we are calling this:
```
  wasmvm_dir=$(go list -json -m all | jq -r '. | select(.Path == "github.com/CosmWasm/wasmvm") | .Dir')
```
which is what's setting that `GOPATH` but we copying it to a `tmp` lib folder but somehow the dynamic linking is still pointing to the local machine.

thanks for debugging this with me!

**Comment by momentmaker** [comment]
when I'm did this with `ldd` I get this which is the origin of the problem described above

```
root@c1656e97bf12:/home/root# ldd /usr/local/bin/chainlink
	linux-vdso.so.1 (0x0000ffff8e45b000)
	/Users/momentmaker/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.2.4/internal/api/libwasmvm.aarch64.so => not found
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffff888e8000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff88775000)
	libresolv.so.2 => /lib/aarch64-linux-gnu/libresolv.so.2 (0x0000ffff8874f000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffff8e42b000)
```

**Comment by caarlos0** [comment]
what have changed since your last successful image build? 

because this one seems to have it right:

![CleanShot 2024-02-12 at 21 36 42@2x](https://github.com/goreleaser/goreleaser/assets/245435/b12ecc19-3b0c-4a3f-bef9-8a2acc521911)

maybe its something on a zig/go update? 

goreleaser does nothing with ld path or any of that, and the build logic haven't changed since a couple of versions ago, so I doubt the problem is here.

**Comment by momentmaker** [comment]
ahh I think that's from our regular docker build. we have been neglecting using `goreleaser` since last august I think.

but you might be right about issues with either `zig` or `go`.

I'll close this issue for now. thanks for your help!

**Comment by caarlos0** [comment]
yeah, I would try to find the last time it worked, and work up from there... I don't have too much experience with cgo, sorry if I can't offer better help
