### ISSUE TITLE
verifiable build failed when using monorepo feature

### ISSUE THREAD

**Issue by andreaangiolillo** [goreleaser/goreleaser#4615]
### What happened?

Hello 👋 
We are getting the following error when using the [verifiable_builds](https://goreleaser.com/customization/verifiable_builds/) feature with the monorepo tag `mongocli/v1.14.3`.

```bash
⨯ release failed after 3s                  error=failed to proxy module: exit status 1: go: github.com/mongodb/mongodb-atlas-cli@v1.14.3: invalid version: unknown revision v1.14.3
```

The error message shows that goreleaser is using the tag `1.14.3` instead of `mongocli/v1.14.3`

### How can we reproduce this?

- set the [verifiable_builds](https://goreleaser.com/customization/verifiable_builds/) 
- try to release a monorepo tag

### goreleaser version

```bash
v1.17.0-pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hey, thanks for the report, I'll look into it!

**Comment by caarlos0** [comment]
It seems Go won't accept composed tags 🤔 

```
failed to proxy module: exit status 1: go: github.com/caarlos0-graveyard/monorepo/foo@foo/v1.3.1: invalid version: version "foo/v1.3.1" invalid: disallowed version string
```

**Comment by caarlos0** [comment]
maybe releated https://github.com/golang/go/issues/32955

**Comment by andreaangiolillo** [comment]
> maybe related https://github.com/golang/go/issues/32955

it seems related indeed 🤔 Thanks for sharing!

**Comment by caarlos0** [comment]
closing as there's nothing we can do.

subscribed to the referenced issue, if it moves forward I'll update here.

thanks!

**Comment by caarlos0** [comment]
I **think** what I need to do here is drop the `foo/` from the tag name, e.g.:


```sh
$ go get github.com/caarlos0-graveyard/monorepo/foo@v1.3.1
go: downloading github.com/caarlos0-graveyard/monorepo/foo v1.3.1
go: added github.com/caarlos0-graveyard/monorepo/foo v1.3.1
```

will fix this in goreleaser pro as well

**Comment by caarlos0** [comment]
ah ok, here's how it works:

if the tag has a prefix, the prefix should also be the module name, e.g.:

```
go get github.com/mongodb/mongodb-atlas-cli/atlascli@v1.14.3
```

this would download the submodule `atlascli` in the tag `atlascli/v1.14.3`.

that said, it seems goreleaser is doing the "right thing" already, but go doesn't support this particular use case (tag prefix does not match module name)
