### ISSUE TITLE
Support commit signing for homebrew taps (and maybe other platforms too)

### ISSUE THREAD

**Issue by vedantmgoyal9** [goreleaser/goreleaser#4616]
### Is your feature request related to a problem? Please describe.

Support GPG and SSH commit signing where we push to Git repos, like homebrew taps/winget-pkgs.

Pushing commit fails, or PR is not able to merge, where "Require signed commits" is enabled in branch protection rules (see option 9 - https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule#creating-a-branch-protection-rule)

### Describe the solution you'd like

GitHub (google/go-github) SDK provides a way to sign commits.

https://github.com/google/go-github/blob/master/github/git_commits.go

Previous issue:
- https://github.com/goreleaser/goreleaser/issues/1774

> That's a fair assessment. I assume the best way forward would be for GitHub to bring that functionality (signing and deployment keys) into the API/SDK.

_Originally posted by @radeksimko in https://github.com/goreleaser/goreleaser/issues/1774#issuecomment-702646363_

### Describe alternatives you've considered

N/A

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
still don't know if I want to do this, for the same reasons laid of in the original issue.



that said, if you use the [`git` option](https://goreleaser.com/customization/homebrew/) and appropriately setup git to sign (with `git config`) it might work already...

**Comment by caarlos0** [comment]
closing as not possible with github api.

**Comment by caarlos0** [comment]
thats a very big change, not sure if its worth the risk

**Comment by caarlos0** [comment]
if someone PRs it, I'm willing to accept.

Probably would have to be opt-in for now at least, as there's a too many details already taken care of in the current implementation... I wouldn't feel confident to just switch it, I think.

**Comment by caarlos0** [comment]
I would rather make it more explicit, something like:


```yaml
github:
  use_graphql_api: true
```

and we can start with the commit only, but eventually I'd say to reimplement the whole client

**Comment by caarlos0** [comment]
closing due to lack of interest/activity
