### ISSUE TITLE
Separate checksum file for each release artifact

### ISSUE THREAD

**Issue by F21** [goreleaser/goreleaser#4618]
### Is your feature request related to a problem? Please describe.

The checksum feature currently lumps all the checksums for a release into a single `checksums.txt` file. If we're using automation to download and verify our release binaries, some tools may not be able to parse the `checksums.txt` file correctly.

For our use-case, we're using gorelease to build and release a Vault plugin. To register the vault plugin, we need to pass the binary and sha256 has to vault: https://developer.hashicorp.com/vault/docs/plugins/plugin-architecture#plugin-catalog Because the hash is store in `checksums.txt`, rather than in an individual checksum file per file, it is a bit hard to automate.

### Describe the solution you'd like

I would like to be able to produce checksums for each released asset individually in self-contained files.
For example, if my release has 2 artifacts, I'd like to have 2 checksums:
- `my_plugin.exe`
- `my_plugin.exe.sha256`
- `my_plugin_linux`
- `my_plugin_linux.sha256`

### Describe alternatives you've considered

None

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
do you have an idea of what the configuration for it could look like?

**Comment by F21** [comment]
I was thinking to use the existing `checksums` stanza like so:
```yaml
checksum:
  split: true
  name_template: "{{ .filename}}.sha256"
````

**Comment by caarlos0** [comment]
that was what I had in mind as well... will work on it in the coming days and let you know here :) 


thanks
