### ISSUE TITLE
Support buildmode: pie

### ISSUE THREAD

**Issue by jkroepke** [goreleaser/goreleaser#4629]
### Is your feature request related to a problem? Please describe.

Go support building position-independent executable

In goreleaser, `buildmode: pie` works fine, however it is not allowed by JSON schema and in the documentation it's not listed as allowed value.

Anything else just works fine. Aside from building, I use nfpm to create packages.

### Describe the solution you'd like

`buildmode: pie` is a allowed value in schema

### Describe alternatives you've considered

ignore it

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

If possible, add a section about building static PIE binaries (note, it requires CGO_ENABLED=1) and may works for amd54 and arm64 only.

* https://github.com/golang/go/issues/41944#issuecomment-711025202

**Comment by caarlos0** [comment]
so, as far as I understand, the only needed change is allowing it in the schema, correct?

if so: https://github.com/goreleaser/goreleaser/pull/4631
