### ISSUE TITLE
If nfpm outdated in goreleaser?

### ISSUE THREAD

**Issue by jkroepke** [goreleaser/goreleaser#4630]
### What happened?

I would like to enrich the usage of nfpm in my project and I used https://nfpm.goreleaser.com/configuration/ for possibilites.

It seems like some configuration options of nfpm are not available in goreleaser:

* Pass a gpg passphrase via `NFPM_PASSPHRASE` seems not supported. Following the docs, I had to use `NFPM_<ID>_PASSPHRASE`, but this can be problematic, if ID contains hypens and hypens are not allowed in environment variable names. (https://github.com/jkroepke/openvpn-auth-oauth2/actions/runs/7883917697/job/21516478008)
* Some configuration keys like deb.compression are not allowed, while documented at https://nfpm.goreleaser.com/configuration/ (https://github.com/jkroepke/openvpn-auth-oauth2/actions/runs/7883453072/job/21510435016?pr=169)

### How can we reproduce this?

Having a .goreleaser.yml file including a working nfpm configuration, then add `deb.compression` or `NFPM_PASSPHRASE` for gpg keysign.

### goreleaser version

```bash
I guess 1.24.0 - "latest" via `goreleaser/goreleaser-action@v5`

Note: To fulfill this filed, it would helpful if `goreleaser/goreleaser-action@v5` reports the current version
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hmm, it might be that some options were not ported back to goreleaser.

on the id thing, unfortunately, not much we can do... we could maybe fallback to NFPM_PASSPHRASE if NFPM_<ID>PASSPHRASE is empty, but on the hyphens problem, the only thing we can do is document to avoid it I think

**Comment by caarlos0** [comment]
fixed on main

thanks for the repor

**Comment by jkroepke** [comment]
> on the id thing, unfortunately, not much we can do...

Lucky, the hypen in in environment variables is something what has todo with POSIX compliance (if I could remember). However Github Actions (and the `env` command) don't care about that and allowed to define environment variables with hypens.
