### ISSUE TITLE
Add `Partial` to `pkg/config`

### ISSUE THREAD

**Issue by TylerHelmuth** [goreleaser/goreleaser#4635]
### Is your feature request related to a problem? Please describe.

We use the types in https://pkg.go.dev/github.com/goreleaser/goreleaser@v1.24.0/pkg/config to help auto-generate our `.goreleaser.yaml`.  I noticed today that `config` does not expose a `Partial` section, despite `partial.by` being configurable at the root of a `.goreleaser.yaml`.

### Describe the solution you'd like

Add a `Partial` section to `config`.

### Describe alternatives you've considered

Making my own struct, which is what I'll do for now.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Related to https://github.com/open-telemetry/opentelemetry-collector-releases/issues/429

**Comment by caarlos0** [comment]
interesting, yeah, I'll have to make the goreleaser pro's config public.

It'll probably live in github.com/goreleaser/goreleaser-pro/pkg/config

Will work on this sometime this week/weekend.

Thanks for the feedback :D

**Comment by caarlos0** [comment]
You can now:

```sh
go get github.com/goreleaser/goreleaser-pro/pkg/config@main
```

Once we release 1.25, the config will also be tagged there.

Let me know if that works for you 🙏

**Comment by caarlos0** [comment]
closing as done
