### ISSUE TITLE
Sort the changelog by the commit's author date

### ISSUE THREAD

**Issue by 0x1306e6d** [goreleaser/goreleaser#4642]
### Is your feature request related to a problem? Please describe.

No, it's additional feature.

### Describe the solution you'd like

Sort commits in the changelog by the author date so that the release note preserves chronological context.

```
changelog:
  sort: asc
  sort_by: ad # message? by default
```

### Describe alternatives you've considered

None

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I think if you leave `sort` empty, the commits will be in the order given by the `git log`, which usually is chronological... can you try that out?
