### ISSUE TITLE
Support configuring headers for homebrew Taps url's

### ISSUE THREAD

**Issue by thde** [goreleaser/goreleaser#4647]
### Is your feature request related to a problem? Please describe.

I'm using goreleaser to create a homebrew tap where the source repository and its releases are private. Therefore, I currently cannot use the generated tap, as the urls require authentication:
```
==> Downloading https://github.com/thde/..._0.1.1_darwin_arm64.tar.gz
curl: (22) The requested URL returned error: 404
```

### Describe the solution you'd like

Homebrew allows to specify custom headers for download urls as suggested as a solution for this by a Homebrew maintainer. This way, a PAT could be used for the downloads:

```ruby
  url "https://api.github.com/repos/Homebrew/homebrew-portable-ruby/releases/assets/103219629",
      headers: [
        "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
      ]
```
https://github.com/Homebrew/brew/issues/15169#issuecomment-1504229816

### Describe alternatives you've considered

It is possible to use a custom download strategy for this aswell, but it requires more configuration as the `GitHubPrivateRepositoryReleaseDownloadStrategy` has been removed in brew v2:
https://dev.to/justdamilare/create-homebrew-taps-for-private-github-repos-14dm
https://gist.github.com/ZPascal/b21c652b811872b3f56db9d54d61d6c6

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
see #4648

**Comment by gmolau** [comment]
@caarlos0 Is it possible that the headers don't really address the use case here since one cannot use the browser url to download artifacts programmatically, one has to use the API? I.e. the url can't be `https://github.com/user/repo/releases/download/{{ .Tag }}/{{ .ArtifactName }}`, it has to be `https://api.github.com/repos/user/repo/releases/assets/{{ asset id }}`, where the asset id needs to be looked up first? Or does GoRelease have a way to inject it?

**Comment by caarlos0** [comment]
right now it doesn't have a way of doing that, no. 

could you please open a new discussion about this? thanks
