### ISSUE TITLE
where Env is accepted, break if the env is empty

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#467]
Right now there are already some places where the user can inform things like `.Env.FOO` on a template.

Problem is that if that variable is not available, the user might get things like `<no value>` somewhere but the process itself don't fail.

**Comment by cv** [comment]
Took me a bit of head-scratching, so I'm posting here in the hopes that it finds its way in the appropriate corner of the documentation:

If you'd like to print an empty string whenever a variable is not set (for an optional ldflag, for example), use something like:

```
-X github.com/acme/myproject/main.MyOptionalApiKey={{index .Env "MY_OPTIONAL_API_KEY"}}
```
