### ISSUE TITLE
Impossible to release to AUR when more than 2 packages are defined in a single file

### ISSUE THREAD

**Issue by bartekpacia** [goreleaser/goreleaser#4679]
### What happened?

Take a look at this GH Actions run:

https://github.com/bartekpacia/fhome/actions/runs/8224293931/job/22487945611

here's the GoReleaser config file: https://github.com/bartekpacia/fhome/blob/c55710f8db41b758b75fd67a1d8624c3fe503adc/.goreleaser.yaml

I'm really not sure what is happening. First item from `aurs` is released fine, but then second one fails with that error.

### How can we reproduce this?

Unfortunately I'm not sure. It happens only on CI where I have set up credentials. I cannot share the credentials.

But I will appreciate if you just take a look at it.

### goreleaser version

```bash
v1.24.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
def a bug, thanks for reporting

**Comment by caarlos0** [comment]
check #4712
