### ISSUE TITLE
environment variables and secrets

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#468]
right now any env is accepted, meaning that the user can expose values he doesn't want to.

I think the right thing to do is to have a whitelist of envs accepted... maybe even inferred from `.Env.FOO` statements...

**Comment by caarlos0** [comment]
maybe this isn't even worth it BTW

**Comment by magiconair** [comment]
I don't see the attack vector. The user still has to control the `.goreleaser.yml` file and the signing key and there are env vars outside goreleaser which drive the build.

**Comment by caarlos0** [comment]
yeah, I think I was just needing to sleep...

closing
