### ISSUE TITLE
Trigger `ko` target in `snapshot` mode

### ISSUE THREAD

**Issue by grzesuav** [goreleaser/goreleaser#4683]
### Is your feature request related to a problem? Please describe.

Described in https://github.com/orgs/goreleaser/discussions/4678#discussioncomment-8744775

My use case - want to have a uniform way to create docker image locally, as `ko` is creating the container from scratch, and upload to repository directly, it would be nice to extend use case to generate container image in `snapshot` mode. 

### Describe the solution you'd like

Use command like 
```
goreleaser build --single-target --clean --snapshot
```
to generate locally binary and container image, for use latter in kind etc

### Describe alternatives you've considered

Manually maintain separate `Dockerfiles` and build locally, however with more than one binary it can be a nightmare

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
it seems its not as easy as just set `KO_DOCKER_REPO=ko.local`, as we don't actually run the `ko` binary... so we need to investigate what they do there and do the same here.

Not too many matches, so probably it isn't too hard: https://github.com/search?q=repo%3Ako-build%2Fko%20ko.local&type=code

**Comment by caarlos0** [comment]
please see https://github.com/goreleaser/goreleaser/pull/5116

**Comment by grzesuav** [comment]
thanks @caarlos0 ! will take a look
