### ISSUE TITLE
Supports replacing existing draft artifacts

### ISSUE THREAD

**Issue by nekohasekai** [goreleaser/goreleaser#4692]
### Is your feature request related to a problem? Please describe.

I want to update the draft artifacts instead of creating a new draft and re-uploading other files.

### Describe the solution you'd like

Add a `replace_existing_draft_artifacts` flag (Or, I would suggest renaming to `recreate_draft` and `replace_draft_artifacts`).

[ghr](https://github.com/tcnksm/ghr) has a flag like this:

`-replace # Replace artifacts if it is already uploaded`

### Describe alternatives you've considered

Not yet.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
see $4711
