### ISSUE TITLE
nfpm: do not create archlinux packages for architectures other than `amd64` and `arm64`

### ISSUE THREAD

**Issue by nekohasekai** [goreleaser/goreleaser#4693]
### Is your feature request related to a problem? Please describe.

Arch Linux only supports amd64 (there is an Arch Liuux ARM with arm64 support), but goreleaser creates archlinux packages for all architectures.

### Describe the solution you'd like

When creating archlinux pkgs, skip unsupported architectures.

### Describe alternatives you've considered

Not yet.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
see #4695

**Comment by nekohasekai** [comment]
looks great
