### ISSUE TITLE
Support .config/ directory

### ISSUE THREAD

**Issue by bersace** [goreleaser/goreleaser#4716]
### Is your feature request related to a problem? Please describe.

Toolings tends to clutter root directory of project. Goreleaser uses its own `.goreleaser.yml` file, usualy at root directory.

### Describe the solution you'd like

Support https://github.com/pi0/config-dir spec by searching for `.config/goreleaser.yml` file.

### Describe alternatives you've considered

Using an environment variable. Easy on CI but not for mates.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
fwiw in the meantime you can pass `-f .config/goreleaser.yml`

**Comment by bersace** [comment]
@caarlos0 you're awesome. Thanks !

**Comment by ayashjorden** [comment]
> fwiw in the meantime you can pass `-f .config/goreleaser.yml`

How would I supply the config path from either go-semantic-release/action or using environment variable like `GORELEASER_CONFIG`?
