### ISSUE TITLE
Winget: base branch not updated before committing

### ISSUE THREAD

**Issue by Trenly** [goreleaser/goreleaser#4720]
### What happened?

When GoReleaser is used for winget releases, the base branch is not updated. This leads to the branches used for PRs being `1 commit ahead, 28150 commits behind`. This causes automated tooling at winget to fail occasionally when PRs are being reviewed by moderators, as the PR checkout fails due to files being overwritten by checkout.

I expect that either -
1) The base branch is brought up to latest before the commits are added 
\- or -
2) The new branch is created based on a detached head from microsoft/winget-pkgs@master

This way, the branches from PRs will always be `1 commit ahead, 0 commits behind` at the time of creation

### How can we reproduce this?

* https://github.com/microsoft/winget-pkgs/pull/145974
* https://github.com/microsoft/winget-pkgs/pull/145973

### goreleaser version

```bash
¯\_(ツ)_/¯
```

### GoReleaser Check

- [ ] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hey! right, I think this wasn't available in go-github or something, but just created the pr:

https://github.com/goreleaser/goreleaser/pull/4721
