### ISSUE TITLE
GoReleaser edit draft status even for published release

### ISSUE THREAD

**Issue by chapurlatn** [goreleaser/goreleaser#4742]
### What happened?

Using GoReleaser with an existing published Github release make it draft and republish it.
This is painful when using goreleaser for Golang artifact management in addition to another release system like release please or semantic release cause it generates a new github event release published on the repository.

I suspect this behaviour to be related to https://github.com/goreleaser/goreleaser/commit/ef90821ee75ef97d78a125427e6294677b4dd408#diff-5d19445232b5dbd4efabd983155c6802ae1ef1be4370176f6c30cf766d30ec22R362.

### How can we reproduce this?

Manually create a release (a github event release published is triggered)
Run goreleaser (a new github event release published is triggered)

### goreleaser version

```bash
1.25
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
ah, good find, yeah, we should probably only do it on new releases

**Comment by caarlos0** [comment]
see https://github.com/goreleaser/goreleaser/pull/4744
