### ISSUE TITLE
`skip_upload: false` skip not only artifact upload, but also git tag pushing

### ISSUE THREAD

**Issue by micheleorsi** [goreleaser/goreleaser#4743]
### What happened?

With a config file like this:

```
[...]

release:
  skip_upload: true

[...]
```

.. when I run `goreleaser release --clean` it doesn't upload the artifact, but neither the git tag created.

My expectation is that it doesn't upload the artifact, but the tag just created should be pushed!

After I removed `skip_upload: true` everything works again: git tag is pushed, but also the artifact.
I have the feeling this is something changed in the last week or so.

### How can we reproduce this?

`goreleaser release --clean`

with a config file like this:

```
[...]

release:
  skip_upload: true

[...]
```

the tag is not pushed into GitHub

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    v1.25.0
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.22.1
Compiler:      gc
ModuleSum:     h1:OhbdvpB/CvSLjFR872OEamNPwK9J1CYhpnIH6FjfSVA=
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
see https://github.com/goreleaser/goreleaser/pull/4745
