### ISSUE TITLE
v1.25.0 creates draft GitHub releases with the wrong tag name

### ISSUE THREAD

**Issue by wjam** [goreleaser/goreleaser#4755]
### What happened?

Draft releases created using v1.25.0 no longer have the tag name set to the same value as the title and are instead set to `untagged-xxxxxx`. This is different to v1.24.0 where the tag name was set to the same as the title.

### How can we reproduce this?

Example repository can be found at https://github.com/wjam/goreleaser-release-bug.

[This is a run of the workflow using v1.24.0](https://github.com/wjam/goreleaser-release-bug/actions/runs/8553974856/job/23438294132) where the draft release is found by the `gh` CLI.

[This is a run of the workflow using v1.25.0](https://github.com/wjam/goreleaser-release-bug/actions/runs/8553998902/job/23438368229) where the draft release can't be found by the `gh` CLI because, as seen in the `List releases` step, the tag name of the release is `untagged-1928ea148d6c199071a9` rather than `v0.0.4`.

### goreleaser version

```bash
goreleaser not downloaded - purely run from GiHub Actions. Versions defined in the GitHub workflow are v1.24.0 and v1.25.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I tried that on goreleaser v1.25.1 and v1.24.0, and the same thing happened in both.

If I create the tag locally, push it, and then run goreleaser, I get this:

![CleanShot 2024-04-04 at 14 01 01@2x](https://github.com/goreleaser/goreleaser/assets/245435/52c2b819-29d5-451f-801a-ed88a4c4a62b)

If I create the tag locally, don't push it, and run goreleaser, I get this:

![CleanShot 2024-04-04 at 14 01 49@2x](https://github.com/goreleaser/goreleaser/assets/245435/046c9456-f7d5-4a38-aab2-65f1999c3f75)

If I push said tag later, though, it gets properly assigned:

![CleanShot 2024-04-04 at 14 02 10@2x](https://github.com/goreleaser/goreleaser/assets/245435/d0865c4b-df6a-4dc1-815f-e0496a64ad54)

If I edit the release and publish it, it gets the right tag assigned to it as well:

![CleanShot 2024-04-04 at 14 04 43@2x](https://github.com/goreleaser/goreleaser/assets/245435/8e2ee6f0-f78e-4cc6-a3ee-5e00aa1428a6)

also, at least on v1.25.1, it seems to work properly with gh release list:

![CleanShot 2024-04-04 at 14 07 32@2x](https://github.com/goreleaser/goreleaser/assets/245435/a6883085-6505-4e78-9b4c-44bfca4330a9) (v1.1.27 was created by goreleaser v1.25.1)

can you verify if it still happens on v1.25.1? I did fix some bugs related to this, but I can't see how it would affect this use case.

also, FWIW, the "untagged" thing is github's doing, not goreleaser's 🤔

**Comment by wjam** [comment]
I can confirm that v1.25.1 has fixed the issue - https://github.com/wjam/goreleaser-release-bug/actions/runs/8558629903/job/23453619801 - so this can be closed!
