### ISSUE TITLE
Recent update resulted in release asset names changing

### ISSUE THREAD

**Issue by Southclaws** [goreleaser/goreleaser#476]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

The app name seems to have been removed from all the assets on the latest release:

![image](https://user-images.githubusercontent.com/1636971/34189169-2a4deb78-e532-11e7-8f56-ea6c5c56b1fa.png)

### Environment

Please paste the output of:

* `go version` 1.9
* `uname -a` whatever the travis docker container uses
* `goreleaser --debug` haven't had a chance to run that on travis

### Steps to Reproduce

n/a

**Expected behavior:** No change in asset names across releases

**Actual behavior:** `sampctl` was omitted from some asset names

goreleaser file: https://github.com/Southclaws/sampctl/blob/master/.goreleaser.yml

**Comment by caarlos0** [comment]
hi @Southclaws, any chance you are using the long-deprecated `{{ .Binary }}` in your archive name_template?

**Comment by caarlos0** [comment]
either way, I'll make it work again for now..

it never really printed anything saying "Hey I'm deprecated", so...

**Comment by Southclaws** [comment]
Ah, I didn't know it was deprecated, I copied it from the readme a while ago. Thanks for the update!

**Comment by caarlos0** [comment]
NP, I'll re-add it for now anyway... just in case.
