### ISSUE TITLE
Retry Gumroad API on failed network call

### ISSUE THREAD

**Issue by ryancurrah** [goreleaser/goreleaser#4778]
### Is your feature request related to a problem? Please describe.

Sometimes the gumroad license check fails because our HTTP proxy is having temporary issues. It's been more noticeable lately and we are getting errors in our continuous integration like the following.

```
⨯ command failed         error=license: failed check license: invalid character 'e' looking for beginning of value
```

The reason for the error is the proxy responded with an unexpected response body that the license check could not read. Usually a 500 error from the proxy with an HTML response containing a error message like below.

```
Unable to forward this request at this time.
```

### Describe the solution you'd like

Since the issues with the proxy are usually temporary and can be resolved by making another network call I was hoping we could add some retry mechanism to the license check with a backoff. Potentially reducing the number of failed builds due to a license check failure.

### Describe alternatives you've considered

Retrying the entire GoReleaser build.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ryancurrah** [comment]
I think found the library you use for Gumroad, I see that it does not check the http status code. I think it would be beneficial to check the status code and perform a retry on certain conditions like 500 series status code.

https://github.com/caarlos0/go-gumroad/blob/main/main.go#L78

**Comment by caarlos0** [comment]
hey!

yeah, that makes sense.

PR: https://github.com/caarlos0/go-gumroad/pull/37

**Comment by caarlos0** [comment]
it fixed, will be in the next release!

thanks for opening and reviewing this! 🙏
