### ISSUE TITLE
gorelease should output the warnings during builds

### ISSUE THREAD

**Issue by stephane-archer** [goreleaser/goreleaser#4782]
### Is your feature request related to a problem? Please describe.

if I set `CGO_CFLAGS=-mmacosx-version-min=10.10` and `CGO_LDFLAGS=-mmacosx-version-min=10.10` from the command line I get the following message:
```
app_darwin.m:18:25: warning: 'UNUserNotificationCenter' is only available on macOS 10.14 or newer [-Wunguarded-availability-new]
```
This helps me see that something wrong happened during the build.

but if I use `goreleaser build --snapshot --clean` I don't see any warning and I can't see that something is wrong.
`goreleaser build` should output the warnings during builds

### Describe the solution you'd like

`goreleaser build` should output the warnings during builds

### Describe alternatives you've considered

?

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
see #4787
