### ISSUE TITLE
Split does not work with snapshot

### ISSUE THREAD

**Issue by rs** [goreleaser/goreleaser#4811]
### What happened?

I'm using split to cross compile a CGO binary for macOS separately from other platforms (which do not need CGO). I'm testing it with our snapshot target, but I'm getting the following message:

  ⨯ continue failed after 0s                 error=not allowed to run against snapshot builds

Any reason why snapshot wouldn't be supported with the split/merge feature?

### How can we reproduce this?

```
goreleaser release --split --snapshot --rm-dist
goreleaser continue --merge
```

### goreleaser version

```bash
____       ____      _                            ____
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __  |  _ \ _ __ ___
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__| | |_) | '__/ _ \
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |    |  __/| | | (_) |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|    |_|   |_|  \___/
goreleaser-pro: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com/pro

GitVersion:    1.25.1-pro
GitCommit:     a9e11f291536cbf4e91021fea047036d08482807
GitTreeState:  clean
BuildDate:     2024-04-03T17:23:21Z
BuiltBy:       goreleaser
GoVersion:     go1.22.1
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
the main reason is that `continue` will only publish and announce... there isn't anything to publish or announce in a snapshot build, so it exits early.

on a second thought, it should probably exit 0 instead 🤔

**Comment by caarlos0** [comment]
on next version it'll work as you'd expect.

will trigger a new nightly build so you can verify 🙏

**Comment by rs** [comment]
Thanks!
