### ISSUE TITLE
Termux can't access internet because android don't allow to `/etc/resolv.conf`

### ISSUE THREAD

**Issue by aicynide** [goreleaser/goreleaser#4817]
### What happened?

Here's the fix

https://github.com/termux/termux-packages/blob/master/packages/golang/fix-hardcoded-etc-resolv-conf.sh

https://github.com/termux/termux-packages/blob/master/packages/golang/fix-hardcoded-etc-resolv-conf.diff

### How can we reproduce this?

run any termux.deb

### goreleaser version

```bash
1.25.1
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
these are patches to the go programming language... not applicable here.
