### ISSUE TITLE
What is needed for IPK support?

### ISSUE THREAD

**Issue by schmidtw** [goreleaser/goreleaser#4848]
### Is your feature request related to a problem? Please describe.

I'd like to be able to package programs for OpenWRT and Yocto into IPK packages using nfpm.

### Describe the solution you'd like

Extend the existing yaml configuration to support IPK and the features exposed via nfpm.

### Describe alternatives you've considered

External solutions are a bit cumbersome.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I'm more than happy to help with this effort.

**Comment by caarlos0** [comment]
hey!

basically the steps are:

- [ ] release nfpm
- [ ] update the nfpm dep in here
- [ ] add the new needed config bits to config.go
- [ ] map them in nfpm.go
- [ ] add a test that covers that
- [ ] update docs

**Comment by caarlos0** [comment]
merged into main in #4863
