### ISSUE TITLE
Allow inline nfpm to build AIX rpms if/when that gets added

### ISSUE THREAD

**Issue by Dylan-M** [goreleaser/goreleaser#4853]
### Is your feature request related to a problem? Please describe.

I need to support AIX, preferably using rpm files. Currently we only have the option to do it via tar.gz packages.

### Describe the solution you'd like

I would like to use nfpm rpm builds to create aix rpm files.

### Describe alternatives you've considered

None, we use goreleaser exclusively for our builds.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

This would depend on goreleaser/nfpm#821

**Comment by Dylan-M** [comment]
After being educated about how to fix direct builds with NFPM, I attempted to implement the same changes in our .goreleaser.yaml file and received the following errors:

```
  • starting release...
  ⨯ release failed after 0s                  error=yaml: unmarshal errors:
  line 256: field platform not found in type config.NFPM
  line 258: field arch not found in type config.NFPMRPM
```

Looking at the code, I see the relevant structs here:
https://github.com/goreleaser/goreleaser/blob/ec2db4a727d7b90ea8e39f744e1778debdcd31ce/pkg/config/config.go#L759
And:
https://github.com/goreleaser/goreleaser/blob/ec2db4a727d7b90ea8e39f744e1778debdcd31ce/pkg/config/config.go#L806

These structs do not contain the relevant fields that need passed to nfpm.

Here is a snippet from my nfpm.yaml where these are present and working:
```
name: "aix-somefile"
arch: "ppc64"
platform: "aix7.2"
version: "1.0.0"
vendor: Company
maintainer: Company Maintainer Email
description: Package Description
homepage: https://some-url.com
rpm:
  arch: ppc
```

Specifically, the platform and rpm/arch (not standalone arch) lines.

I assume that rpm/arch is being set automagically from arch, however I need the ability to override it for AIX because AIX ppc64 rpms expect rpm arch set to ppc. Linux ppc64 arch rpms expect rpm arch set to ppc64. This means we can't (without major modifications) use the already built in override capabilities in the nfpm code.

I'm not sure if platform is being set anywhere, but if it is I would guess it is set from the os. Again, I need to override this because the os is `aix` and the platform has to follow the pattern of `aix#.#`, such as `aix7.2` in order to work.

**Comment by caarlos0** [comment]
fixed in https://github.com/goreleaser/goreleaser/pull/5075
