### ISSUE TITLE
Draft release config is ignored for github release in latest version

### ISSUE THREAD

**Issue by gotbadger** [goreleaser/goreleaser#4862]
### What happened?

When creating a release in github using split builds the release was marked as latest and the config for this release to be a draft was ignored.

### How can we reproduce this?

Conifg here
https://github.com/Bearer/bearer/blob/main/.goreleaser/canary.yaml

You can see a good run using 1.25.0 here: https://github.com/Bearer/bearer/actions/runs/9081301397/job/24955003662
And a bad run using 1.26.0 here: https://github.com/Bearer/bearer/actions/runs/9080949464/job/24953840354

### goreleaser version

```bash
1.26.0-pro - The release was marked as latest
1.25.0-pro - The release was marked as draft as expected
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I wonder if the changes in https://github.com/goreleaser/goreleaser/pull/4744 are the source of this problem and cause issues for split builds?

**Comment by caarlos0** [comment]
ahh, good catch!

i think its related to the new `--draft` flag... will fix it!

**Comment by caarlos0** [comment]
I think e466507 should fix it!
