### ISSUE TITLE
Recommended to remove annoying thanks

### ISSUE THREAD

**Issue by poneding** [goreleaser/goreleaser#4864]
### Is your feature request related to a problem? Please describe.

First of all, let me state that goreleaser is an amazing programming tool, I have put `source <(goreleaser completion zsh)` was added to my.zshrc file.
But it had a small problem: every time I opened the terminal, goreleaser printed this thanks message directly to me, even though I didn't intend to use it at this point. 
This is a bit annoying, can you remove it?

<img width="567" alt="image" src="https://github.com/goreleaser/goreleaser/assets/33922888/1ea8ebc6-d510-40ae-b3f9-5e0c74cdfb1d">

### Describe the solution you'd like

Remove the annoying thansk message, or reduce the number of prompts.

### Describe alternatives you've considered

none

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hey!

that's a valid issue for sure.

for now, you can workaround it with 

```sh
source <(goreleaser completion zsh 2>/dev/null)
```

**Comment by poneding** [comment]
@caarlos0 Perfect solution to my problem, nice 🥰
