### ISSUE TITLE
Cannot go install v2.0.0

### ISSUE THREAD

**Issue by tico24** [goreleaser/goreleaser#4907]
### What happened?

```bash
go install github.com/goreleaser/goreleaser@v2.0.0
go: github.com/goreleaser/goreleaser@v2.0.0: github.com/goreleaser/goreleaser@v2.0.0: invalid version: go.mod has post-v2 module path "github.com/goreleaser/goreleaser/v2" at revision v2.0.0
```

### How can we reproduce this?

A very simple dockerfile to ease reproduction and to prove a clean environment:

```
FROM golang:1.22-alpine3.20 AS base

RUN apk add --no-cache \
    git \
    && rm -rf /var/cache/apk/*

ARG VERSION_GORELEASER=v2.0.0
RUN go install github.com/goreleaser/goreleaser@${VERSION_GORELEASER}
```

### goreleaser version

```bash
v2.0.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Installing `@latest` works, but only because latest is still pinned to v1.26.2

**Comment by bep** [comment]
Try

```bash
go install github.com/goreleaser/goreleaser/v2@latest
```

**Comment by tico24** [comment]
This works, but is not what the docs suggest. So something needs updating I guess.

**Comment by caarlos0** [comment]
oh, good catch, forgot to fix that part of the docs

thanks for the nudge, fixing it now !
