### ISSUE TITLE
init generates a version 1 config file

### ISSUE THREAD

**Issue by rowanseymour** [goreleaser/goreleaser#4914]
### What happened?

I just installed goreleaser 2.0.0 because I noticed our github CI goreleaser actions are failing with

```
  • only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
```

I was having a hard time figuring out from that what's wrong with our config files, so I thought I'd generate a clean one using `goreleaser init`, but the config file it generates starts with `version: 1`, so `goreleaser check` now says...

```
  • only configurations files on  version: 2  are supported, yours is  version: 1 , please update your configuration
```

### How can we reproduce this?

```
goreleaser init
goreleaser check
```

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    2.0.0
GitCommit:     f35dcda343ddebf9dae706c8a86aa5915501fa84
GitTreeState:  clean
BuildDate:     2024-06-05T00:24:56
BuiltBy:       homebrew
GoVersion:     go1.22.3
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [ ] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
ouch, good catch

#4915 should fix it
