### ISSUE TITLE
Sign goreleaser nfpms

### ISSUE THREAD

**Issue by cnt0** [goreleaser/goreleaser#4923]
### Is your feature request related to a problem? Please describe.

Hello. Goreleaser documentation [suggests](https://goreleaser.com/install/#deb-rpm-and-apk-packages) the way to install this software in some linux distributions:

> Download the .deb, .rpm or .apk packages from the [OSS releases page](https://github.com/goreleaser/goreleaser/releases) and install them with the appropriate tools.

However, this fails on alpine linux:
```bash
$ curl -LJO https://github.com/goreleaser/goreleaser/releases/download/v2.0.0/goreleaser_2.0.0_x86_64.apk
$ doas apk add ./goreleaser_2.0.0_x86_64.apk
ERROR: ./goreleaser_2.0.0_x86_64.apk: UNTRUSTED signature
```
That's because this apk (and all other generated nfpms) doesn't contain the signature

### Describe the solution you'd like

I believe the best way to resolve this problem is to generate signed nfpms on github, i.e. fill `.signature.key_file` fields in appropriate sections in `.goreleaser.yaml`. 

And since nfpm is not using any external tools to sign apk packages, it should be fairly easy to do that at least in this case. I'm not so sure about deb packages though.

### Describe alternatives you've considered

well I can work around this problem by verifying checksums from github release and then calling
```bash
$ doas apk add ./goreleaser_2.0.0_x86_64.apk --allow-untrusted
```
...but there's an automated way to do exactly that :)

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
signing it wouldn't help, as the key used to sign needs to be trusted as well if I recall correctly.

will fix the docs instead!
