### ISSUE TITLE
Add checksum-related overrides for blobs

### ISSUE THREAD

**Issue by brianstrauch** [goreleaser/goreleaser#4934]
### Is your feature request related to a problem? Please describe.

During our release, we upload binaries/archives to three S3 buckets and GitHub. We'd like to upload different subsets of the main checksum file to each of these four locations, and we'd like one of those checksum files to have a different name.

### Describe the solution you'd like

It would be great if each `blob` could have fields for (1) an optional checksum filename override and (2) the option to override the entries in the included checksum. In the next major version, we could consider having the checksum that's released with the blob only include the artifacts uploaded for that blob.

### Describe alternatives you've considered

Our current (sub-optimal) solution is to run Goreleaser and then run `aws s3 mv` to rename one of the checksum files. This results in our checksum files containing entries that don't correspond to the specific bucket.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hmmm that's interesting...

maybe the [checksum.split](https://goreleaser.com/customization/checksum/) option helps? its not exactly the thing you want, though.

I'm also curious: whats the problem in uploading the complete checksum?

**Comment by brianstrauch** [comment]
> whats the problem in uploading the complete checksum?

There's no real problem, it would just be nice to only have the checksums we need.

> It would be great if each blob could have fields for (1) an optional checksum filename override

This is the main ask from this issue!

**Comment by caarlos0** [comment]
OK, this is coming in v2.3 in the follow form:

```yaml
# .goreleaser.yml
checksum:
  split: true

blobs:
  - provider: s3
    # etc ...
    if: '{{ eq .ArtifactID "my-id" }}' # can be any filter you want
```

hopefully that solves for your use case!
