### ISSUE TITLE
GitHub compare 404

### ISSUE THREAD

**Issue by converge** [goreleaser/goreleaser#4960]
### What happened?

Hi, I'm migrating from Jenkins to GitHub Action, everything looks good except that during the `goreleaser release` command, it's failing in this step:

```
• generating changelog
  ⨯ release failed after 12m4s               error=GET https://api.github.com/repos/org-name/app-cli/compare/v4.4.1...v4.4.2?per_page=100: 404 Not Found []
```

I was comparing the URLs, the one request above:

`https://api.github.com/repos/my-org/app-cli/compare/v4.4.1...v4.4.2?per_page=100:` returns 404 as showed above. 

However, if I manually change the request to:
`https://github.com/my-org/app-cli/compare/v4.4.1...v4.4.2` it works.

### How can we reproduce this?

regular .goreleaser.yaml file/config provided in the documentation with minor changes to the changelog format

### goreleaser version

```bash
2.0.1
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hey there!

I would guess that either the tag isn't there yet when the api is called, or the github token being used does not have enough permissions.

**Comment by caarlos0** [comment]
closing as its unlikely to be an issue with goreleaser itself.

**Comment by converge** [comment]
hi @caarlos0 , thank you for the prompt reply! I haven't replied yet since I'm waiting my company provide a new GitHub token following the Goreleaser docs. permissions, will keep the issue posted.

**Comment by converge** [comment]
Hey @caarlos0 , the GH token was updated, and it's all working now, thanks again!
