### ISSUE TITLE
Publish artifacts without release to Githab, Gitlab, Gitea,etc

### ISSUE THREAD

**Issue by krasoffski** [goreleaser/goreleaser#4962]
### Is your feature request related to a problem? Please describe.

I want to upload artifact to ftp/jfrog,s3,etc after building the binaries or creating achieve. Current implementation does not allow to skip steps related to github. It looks like any publish performed after github release, even HTTP or custom publisher. Disabling `publish` during release also disables any other publishers. 

Also docs describe this like 
> After releasing to GitHub, GitLab, or Gitea, GoReleaser can generate and publish a nixpkg to a [Nix User Repository](https://github.com/nix-community/NUR).

This mean that I cannot skip releasing to GitHub.

### Describe the solution you'd like

Add command like `goreleaser publish` which allows to upload artifacts to some were.
Or add inclusive option like `--allow` to allow specific publisher from config file. 

### Describe alternatives you've considered

None

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Nothing

**Comment by caarlos0** [comment]
you can set `release.disable` to `true` in the configuration file

https://goreleaser.com/customization/release/


Please note that you'd have to provide custom URL templates for nix, brew, etc.
