### ISSUE TITLE
Modver and Taggo for automatic semantic versioning

### ISSUE THREAD

**Issue by bobg** [goreleaser/goreleaser#4965]
### Is your feature request related to a problem? Please describe.

Goreleaser checks for a semantic version tag but can't tell whether it's the _right_ semantic version tag.

### Describe the solution you'd like

I have written a couple of tools that could be used to add useful new functionality to goreleaser:

[Modver](https://github.com/bobg/modver#readme) is a tool that can compare two different versions of a Go module to decide what kind of semantic-version increase is needed, if any: major, minor, or patchlevel.

[Taggo](https://github.com/bobg/taggo#readme) is a newer (read: less mature) tool that can identify various kinds of problem in the version tags and Go module paths in a Git repository. It can optionally add the right new version tag in some cases, using Modver to decide what that is.

I humbly suggest using these tools to add new capabilities to goreleaser.

### Describe alternatives you've considered

n/a

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Please let me know how I can help!

**Comment by caarlos0** [comment]
sorry, automatically tagging is not in the (already too big) scope of goreleaser.
