### ISSUE TITLE
GitLab releases broken

### ISSUE THREAD

**Issue by abemedia** [goreleaser/goreleaser#4974]
### What happened?

I believe GitLab changed something with their uploads API as all of a sudden the release assets uploaded to GitLab are returning 404 errors.

### How can we reproduce this?

Here is a test repo which demonstrates the issue: https://gitlab.com/abemedia/test_1720080953016023000

### goreleaser version

```bash
GitVersion:    2.0.1
GitCommit:     684c1805864e5f29acc204e34e1770eb74918d15
GitTreeState:  clean
BuildDate:     2024-06-11T01:45:52
BuiltBy:       homebrew
GoVersion:     go1.22.4
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abemedia** [comment]
Just did some digging and turns out that uploads now no longer have a URL like `https://gitlab.com/{user}/{repo}/uploads/{hash}/file.ext` but instead they are like `https://gitlab.com/-/project/{projectID}/uploads/{hash}/file.ext`.

I've added a PR to `go-gitlab` to get the full path from the API instead of having to build a custom one which might break again: https://github.com/xanzy/go-gitlab/pull/1968

Once that is merged I'll push the fix here.

**Comment by caarlos0** [comment]
ah, good find! thank you!

**Comment by caarlos0** [comment]
cool!

do we need to change anything else on goreleaser's side?

**Comment by abemedia** [comment]
Yes, but fairly simple. Happy to create a PR after work today.

**Comment by elee1766** [comment]
does the aur template need to change?

**Comment by abemedia** [comment]
Sorry but I didn't get around to fixing this before going on holiday. Have created the PR now: https://github.com/goreleaser/goreleaser/pull/5035

**Comment by caarlos0** [comment]
no worries :D thanks for the PR <3
