### ISSUE TITLE
Ignore Git Status

### ISSUE THREAD

**Issue by hacdias** [goreleaser/goreleaser#498]
Hello!

Is there a way to ignore git "dirtiness"? Here is my script:

```bash
#!/bin/bash
set -e

# Clean the dist folder and build the assets.
rm -rf assets/dist
npm run build

# Embed the assets using rice.
rice embed-go

# Replace version
tag=${TRAVIS_TAG:1}
sed -i "s|$tag|(untracked)|g" filemanager.go

# Shut up goreleaser
git add rice-box.go filemanager.go
git commit -m "${tag}"
git tag -d "$TRAVIS_TAG"
git tag "$TRAVIS_TAG"

# Publish
curl -sL https://git.io/goreleaser | bash
```

I'd like to remove the "shut up goreleaser" part.

**Comment by caarlos0** [comment]
The most right way is to add those generated files to .gitignore probably.

**Comment by hacdias** [comment]
Unfortunately I can't add that file to `.gitignore`. I'll keep doing the releasing process as I used to do. 😄 Still we Goreleaser but not the way I pictured it.
