### ISSUE TITLE
Ensure tag has been pushed to github

### ISSUE THREAD

**Issue by wxio** [goreleaser/goreleaser#499]
I've just started playing with goreleaser and managed to push a release to github, but I hadn't pushed the tag to origin. The source zip is therefore out of sync with the release as there were missing commits.

Is this a valid feature request?
i.e. the validation should (optionally) check that the github has the tag and commit being built. 

Or is there something about git I am misunderstanding.

**Comment by caarlos0** [comment]
I remember that there was some discussion about this some time ago... I think the problem is to do this with sane defaults... like.. what should we do if there are multiple remotes and the tag is pushed to just one of them?

Not saying we shouldn't do this... just that I don't know the best way to do it...

**Comment by millergarym** [comment]
I think that In the context of a github release there are some sane default.
That is the source and the release both refer to the same repository.
Github automatically creates a zip and tar of the source related to the release (I assume the source archive is at the same tag). Now if the commit haven't yet been pushed that source archive can't match.  The release change log shows this inconsistency, as there are commits with no link.

Is there even a way to build from one repo and release to another?

**Comment by embano1** [comment]
Good discussion. Having the same mixed feelings here.

@caarlos0 wrt multiple remotes
IIRC, .goreleaser.yaml only accepts one destination repo. So one could check whether remote and src repo (branch) are in sync (i.e. no diff). May be make it a default flag, where one can opt out.

Just brainstorming here...

**Comment by millergarym** [comment]
@caarlos0 we already have a GIT TOKEN else it wouldn't be possible to create a release. It might be that the token needs different access right, but this isn't a big issue.

@embano1 isn't it enough to check that the head hashs are the same?

**Comment by caarlos0** [comment]
> @caarlos0 we already have a GIT TOKEN else it wouldn't be possible to create a release. It might be that the token needs different access right, but this isn't a big issue.

yeah, but the user might not be using github...
