### ISSUE TITLE
Downgrade dockerfile from go1.23rc1 to go1.22.5

### ISSUE THREAD

**Issue by ghost** [goreleaser/goreleaser#4992]
### What happened?

I'm using nightly docker image to use latest go version.
go 1.23 is preview. Its not stable.

### How can we reproduce this?

Downgrade dockerfile from `go1.23rc1` to `go1.22.5`

### goreleaser version

```bash
GitVersion:    2.1.0-nightly
GitCommit:     908dabaf0aa47f1c88418bf756d565081ac72dd3
GitTreeState:  false
BuildDate:     2024-07-03T13:02:47Z
BuiltBy:       goreleaser
GoVersion:     go1.22.5
Compiler:      gc
ModuleSum:     unknown
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
fixed, thanks!
