### ISSUE TITLE
Schema doesn't include nfpms.formats.ipk

### ISSUE THREAD

**Issue by schmidtw** [goreleaser/goreleaser#4997]
### What happened?

Using the schema for yml validation results in an error since ipk is not allowed presently as an `nfpms` `formats` option.

```
nfpms:
  - 
    formats:
      - ipk
```

The schema location this should go in is [here](https://github.com/goreleaser/goreleaser/blob/main/www/docs/static/schema.json#L1816) but I'm not sure if that's the only fix needed.

### How can we reproduce this?

Try to add `ipk` to the `nfpms.formats` section of the goreleaser.yml file.

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    2.1.0
GitCommit:     2a1bcaca534197ba122e76812d842aedf61930fe
GitTreeState:  false
BuildDate:     2024-07-13T17:21:33Z
BuiltBy:       goreleaser
GoVersion:     go1.22.5
Compiler:      gc
ModuleSum:     h1:c2nYTJzCSHmWw5duS+iC/ETYLlyyBTZPesf0ABnTbhw=
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hey, thanks for the heads up! 
fixed!
