### ISSUE TITLE
[build] cleaning via `--clean` should happen before validating Git state

### ISSUE THREAD

**Issue by hhromic** [goreleaser/goreleaser#5023]
### What happened?

When performing a `goreleaser build --clean` without `--snapshot` and there already is a `dist/` directory that is not ignored by Git, then the build falis with a Git dirty state error. See the section below for a reproduction example.

This is because GoReleaser checks for the Git state _before_ performing the clean-up, and therefore untracked files such as `dist/` mark the Git state as dirty, failing the validation.

I know that this can be fixed simply by adding `dist/` (or any other configured dist directory) to `.gitignore`, but I believe that GoReleaser should not depend on ignoring files in Git and therefore I think this is a bug.

### How can we reproduce this?

Consider the following MRE project:
```
$ mkdir test
$ cd test
$ git init
$ git remote add origin https://github.com/user/test
$ go mod init test
$ cat > main.go << '__EOF__'
package main
import "fmt"
func main() { fmt.Println("Hello world!") }
__EOF__
$ cat > .goreleaser.yaml << '__EOF__'
version: 2
before:
  hooks:
    - go mod tidy
__EOF__
$ git add .
$ git commit -m 'First commit'
$ git tag v0.1.0
```

When doing a build for the first time, it works as expected:
```
$ goreleaser build --clean --single-target
  • loading environment variables
  • getting and validating git state
    • couldn't find any tags before "v0.1.0"
    • git state                                      commit=62717029cfd2dcbff357cb8576ae5b5f883308c9 branch=master current_tag=v0.1.0 previous_tag=<unknown> dirty=false
  • parsing tag
  • setting defaults
  • partial
  • running before hooks
    • running                                        hook=go mod tidy
  • checking distribution directory
  • setting up metadata
  • writing release metadata
  • loading go mod information
  • build prerequisites
  • building binaries
    • partial build                                  match=target=linux_amd64
    • building                                       binary=dist/test_linux_amd64_v1/test
  • writing artifacts metadata
  • build succeeded after 0s
  • thanks for using goreleaser!
```

However, if you do another build immediately after, it fails because now the previously existing `dist/` directory marks the Git repository as dirty, despite asking for it be cleaned with `--clean`:
```
$ goreleaser build --clean --single-target
  • loading environment variables
  • getting and validating git state
    • couldn't find any tags before "v0.1.0"
    • git state                                      commit=62717029cfd2dcbff357cb8576ae5b5f883308c9 branch=master current_tag=v0.1.0 previous_tag=<unknown> dirty=true
  ⨯ build failed after 0s                    error=git is in a dirty state
Please check in your pipeline what can be changing the following files:
?? dist/

Learn more at https://goreleaser.com/errors/dirty
```

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    2.1.0
GitCommit:     2a1bcaca534197ba122e76812d842aedf61930fe
GitTreeState:  false
BuildDate:     2024-07-13T17:21:33Z
BuiltBy:       goreleaser
GoVersion:     go1.22.5
Compiler:      gc
ModuleSum:     h1:c2nYTJzCSHmWw5duS+iC/ETYLlyyBTZPesf0ABnTbhw=
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
it is how it worked since forever, but I guess we can change it

**Comment by hhromic** [comment]
If you agree with this feature request, I'm willing to help implementing it. 👍
