### ISSUE TITLE
cannot include pcap -> github.com/google/gopacket/pcap

### ISSUE THREAD

**Issue by gressdave58** [goreleaser/goreleaser#5043]
### What happened?

No mappter the ENV settings or the config is specify for building via :  
args: release --clean --config goRelease.cfg
i cannot git past the errors on the publish-event

repo: git@github.com:gressdave58/goReleaserPacket.git

Thanks

Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/7aa1e085-9224-413f-b8c5-b33502b5e1c6 -f /home/runner/work/_temp/e2841d28-9a17-4480-8fcd-17f5cea00845
GoReleaser 2 installed successfully
/opt/hostedtoolcache/goreleaser-action/2.1.0/x64/goreleaser release --clean
  • could not find a configuration file, using defaults...
  • loading environment variables
    • using token from  $GITHUB_TOKEN 
  • getting and validating git state
    • git state                                      commit=5095c3b9ed1f132ce253bb42230728de6fea6477 branch=main current_tag=v0.0.42 previous_tag=v0.0.41 dirty=false
  • parsing tag
  • setting defaults
  • checking distribution directory
  • setting up metadata
  • writing release metadata
  • loading go mod information
  • build prerequisites
  • building binaries
    • building                                       binary=dist/goReleaserPacket_darwin_amd64_v1/goReleaserPacket
    • building                                       binary=dist/goReleaserPacket_linux_386/goReleaserPacket
    • building                                       binary=dist/goReleaserPacket_linux_amd64_v1/goReleaserPacket
    • building                                       binary=dist/goReleaserPacket_linux_arm64/goReleaserPacket
    • building                                       binary=dist/goReleaserPacket_darwin_arm64/goReleaserPacket
    • building                                       binary=dist/goReleaserPacket_windows_amd64_v1/goReleaserPacket.exe
    • building                                       binary=dist/goReleaserPacket_windows_arm64/goReleaserPacket.exe
    • building                                       binary=dist/goReleaserPacket_windows_386/goReleaserPacket.exe
    • took: 39s
  ⨯ release failed after 39s                 error=failed to build for linux_386: exit status 1: go: downloading github.com/google/gopacket v1.1.19
# github.com/google/gopacket/pcap
Error: ../../../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:30:22: undefined: pcapErrorNotActivated
Error: ../../../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:52:17: undefined: pcapTPtr
Error: ../../../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:64:10: undefined: pcapPkthdr
Error: ../../../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:103:6: undefined: pcapBpfProgram
Error: ../../../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:110:7: undefined: pcapPkthdr
Error: ../../../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:268:33: undefined: pcapErrorActivated
Error: ../../../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:269:33: undefined: pcapWarningPromisc
Error: ../../../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:270:33: undefined: pcapErrorNoSuchDevice
Error: ../../../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:271:33: undefined: pcapErrorDenied
Error: ../../../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:748:14: undefined: pcapTPtr
Error: ../../../go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap.go:271:33: too many errors

### How can we reproduce this?

clone git@github.com:gressdave58/goReleaserPacket.git

### goreleaser version

```bash
Run goreleaser/goreleaser-action@v5
  with:
    version: 2
    args: release --clean
    distribution: goreleaser
    workdir: .
    install-only: false
  env:
    GITHUB_TOKEN: ***
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

this is a stripped down repo that reproduces the issue.  I've tried "every" combination of builds and using my own config file to no avail.

**Comment by caarlos0** [comment]
the library is not fully implemented for some architectures (specifically linux 386 it seems) you're trying to build, nothing we can do here.
