### ISSUE TITLE
using envOrDefault function to setup environment vairable

### ISSUE THREAD

**Issue by sw360cab** [goreleaser/goreleaser#5059]
### What happened?

Just to report an unexpected behaviour, I may be misunderstanding something.

When setting up an env variable within the goreleaser file I expected that the `envOrDefault` native function could be used,
but Goreleaser (action), reports and error

> error=template: failed to apply "TAG_VERSION=\"{{ envOrDefault \"TAG_VERSION\" \"latest\" }}\"": interface {} is map[string]string, not context.Env

### How can we reproduce this?

This is working (as from the doc)

```yaml
env:
  - TAG_VERSION={{ if index .Env "TAG_VERSION"  }}{{ .Env.TAG_VERSION }}{{ else }}latest{{ end }}
```

This is not working

```yaml
env:
  - TAG_VERSION="{{ envOrDefault "TAG_VERSION" "latest" }}"
```

### goreleaser version

```bash
GitVersion:    2.0.1
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
ah, good find, fixed!
