### ISSUE TITLE
Colour (color) in windows cmd.exe - escape chars showing

### ISSUE THREAD

**Issue by wxio** [goreleaser/goreleaser#506]
### Prerequisites
* [x] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?
(sorry if this is a repeat, but if it is I didn't find it)

### Description

Color formatting not working in windows cmd.
Is possible change to 
* github.com/robertgzr/color or 
* github.com/mattn/go-colorable (used by robertgzr) or
* github.com/fatih/color

See example output:

cmd.exe
```
[34m   •[0m [1mreleasing...[0m
[33m   •[0m could not load config, using defaults [33mfile[0m=.goreleaser.yml
[34m   •[0m [1mSETTING DEFAULTS FOR:[0m
[34m      •[0m snapshoting
```

cmd terminal inside vscode
```
?[34m   •?[0m ?[1mreleasing...?[0m
?[33m   •?[0m could not load config, using defaults ?[33mfile?[0m=.goreleaser.yml
?[34m   •?[0m ?[1mSETTING DEFAULTS FOR:?[0m
```

works fine inside mintty
```
   • releasing...
   • could not load config, using defaults file=.goreleaser.yml
   • SETTING DEFAULTS FOR:
```

### Environment

* `go version`
```
go version go1.9.2 windows/amd64
```

* `uname -a`
`
'uname' is not recognized as an internal or external command,
operable program or batch file.
` *as expected*

**Comment by caarlos0** [comment]
I was looking into a good reason for using fatih/color besides the fact that the code looks better... seems like now I have one :)

**Comment by caarlos0** [comment]
oh, problem is bigger than expected... apex/log doesn't use fatih/color it seems...

will talk to @tj and see if he accepts a PR for that :)

**Comment by caarlos0** [comment]
@wxio fixed to use fatih/color. Can you check the latest version, please?

**Comment by caarlos0** [comment]
also thanks @tj for the quick accept on apex/log :)
