### ISSUE TITLE
Build of fresh checkout fails with SECURITY ERROR

### ISSUE THREAD

**Issue by twpayne** [goreleaser/goreleaser#5069]
### What happened?

On a new machine I ran:

```console
$ git clone https://github.com/goreleaser/goreleaser.git
$ cd goreleaser
$ go build ./...
```

and got the error

```
...
go: downloading github.com/go-openapi/jsonreference v0.21.0
go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20190905194746-02993c407bfb
verifying github.com/anchore/quill@v0.4.2: checksum mismatch
        downloaded: h1:nnmgSOsKWuHrvwKFB8EempJhO1A/n5Zkw90VSbHQU2k=
        go.sum:     h1:0w1tDLI9cj37yqjwZ2QiaKTvUd/eL0WHeKJvDbRvT3s=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

This is due to https://github.com/anchore/quill/issues/472.

### How can we reproduce this?

Run the commands above.

### goreleaser version

```bash
Checkout of `master` at f924466a81c74e2047966335b38d176e921fe214.
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

The bug is in a dependency of goreleaser, not in goreleaser itself. However, it affects goreleaser directly.

**Comment by caarlos0** [comment]
ouch, good find... 

seems like we need to wait for a solution upstream, though, no?

**Comment by twpayne** [comment]
Or revert to a version of quill that does not have this problem and use an `exclude` directive in `go.mod` to prevent the buggy versions from being used.

**Comment by caarlos0** [comment]
thing is: I cannot even reproduce this problem here... tried on macOS and linux, multiple machines, cleaning and not cleaning go path, I think we're missing some variable 🤔 

that said, reverting also feels a bit dodgy... i mean, you can do it on your branch to get things going, but i'm not a fan of downgrading dependencies

**Comment by twpayne** [comment]
OK, I am also now very confused because I definitely saw this, verified that it was reported upstream, and now also can't reproduce it. So closing this until it happens again.

**Comment by caarlos0** [comment]
> OK, I am also now very confused because I definitely saw this, verified that it was reported upstream, and now also can't reproduce it. So closing this until it happens again.

it is a weird one, I'll give you that :D
