### ISSUE TITLE
How to customize the packaging command

### ISSUE THREAD

**Issue by zk3151463** [goreleaser/goreleaser#5083]
### Is your feature request related to a problem? Please describe.

I want to use this to package Wails or other types of projects, and I need to customize the packaging command.

### Describe the solution you'd like

I want to use this to package Wails or other types of projects, and I need to customize the packaging command.

### Describe alternatives you've considered

I want to use this to package Wails or other types of projects, and I need to customize the packaging command.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
everything is documented here: https://goreleaser.com/customization/

**Comment by zk3151463** [comment]
没有在文档里找到呀

**Comment by jxs1211** [comment]
Hi, I'm looking for something related to wails in both Discord and discussion, but there seems not much about that. Could you guide me on how to get that?

**Comment by jxs1211** [comment]
> everything is documented here: https://goreleaser.com/customization/
> 
> you can also ask questions in the [discussions](https://github.com/goreleaser/goreleaser/discussions) or [discord](https://goreleaser.com/discord)

Hi, I'm looking for something related to wails in both Discord and discussion, but there seems not much about that. Could you guide me on how to get that?
