### ISSUE TITLE
Generated archives contain a mix of user and root file uids/gids

### ISSUE THREAD

**Issue by twpayne** [goreleaser/goreleaser#5086]
### What happened?

I noticed that the generated archive contained entries with both `root` and local-user owners.

### How can we reproduce this?

Checkout goreleaser at a recent commit, e.g. 17a955458ca085b010a75127d2a0572ea89d22eb, and run goreleaser on itself:

```console
$ git clone https://github.com/goreleaser/goreleaser.git
...
$ cd goreleaser
$ git checkout 17a955458ca085b010a75127d2a0572ea89d22eb
...
$ go run . release --clean --snapshot --skip=chocolatey,sign,publish,sbom,docker
...
```

Then inspect the contents of `dist/goreleaser_Linux_x86_64.tar.gz`:

```console
$ tar tvzf dist/goreleaser_Linux_x86_64.tar.gz                                  
-rw-rw-r-- twp/twp        1085 2024-08-17 09:19 LICENSE.md
-rw-rw-r-- twp/twp       12982 2024-08-17 09:19 README.md
-rw-rw-r-- twp/twp       11975 2024-08-17 18:10 completions/goreleaser.bash
-rw-rw-r-- twp/twp       10061 2024-08-17 18:10 completions/goreleaser.fish
-rw-rw-r-- twp/twp        7892 2024-08-17 18:10 completions/goreleaser.zsh
-rw-rw-r-- twp/twp        1594 2024-08-17 18:10 manpages/goreleaser.1.gz
-rwxrwxr-x root/root  66003096 2024-08-16 19:49 goreleaser
```

Note that the `goreleaser` entry is owned by `root/root`, whereas all other entries are owned by the local user (`twp/twp` in my case).

### goreleaser version

```bash
17a955458ca085b010a75127d2a0572ea89d22eb
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Running `go releaser check` warns about goreleaser's own `.goreleaser.yaml`:

```console
$ go run . check
  • checking                                 path=.goreleaser.yaml
  • DEPRECATED:  snapshot.name_template  should not be used anymore, check https://goreleaser.com/deprecations#snapshotnametemplate for more info
  • .goreleaser.yaml                                 error=configuration is valid, but uses deprecated properties
  ⨯ command failed                                   error=1 out of 1 configuration file(s) have issues
exit status 2
```

However, I had to check the "goreleaser check shows no errors" checkbox to be able to submit this issue.

**Comment by caarlos0** [comment]
by default it uses the file's owner/group/etc info.

these can be overridden with `archives.builds_info` for the binaries or `files.*.info` for the other files -> https://goreleaser.com/customization/archive/

maybe we should do that 🤔, set GID and UID to 0 all the way down

**Comment by twpayne** [comment]
> maybe we should do that 🤔, set GID and UID to 0 all the way down

Yes, I think so. I can't think of any case where you would want a non-root UID/GID in a tar archive for widely-distributed software.

**Comment by caarlos0** [comment]
yeah, me neither!

https://github.com/goreleaser/goreleaser/pull/5088

thanks for bringing this up btw 🙏🏻
