### ISSUE TITLE
Support publishing only container images

### ISSUE THREAD

**Issue by jsirianni** [goreleaser/goreleaser#5096]
### Is your feature request related to a problem? Please describe.

My project has two Goreleaser configurations. One is for building and publishing artifacts intended for users to consume and deploy to their own environment.

The other is for a saas application. Both build the same binaries but different container images. It would be nice if we had the option to publish only container images (skipping binaries and archives).

### Describe the solution you'd like

A flag or configuration option that allows me to skip publishing binaries and archives (or anything else), publish only the container images.

### Describe alternatives you've considered

Right now I build with `--skip=publish` and then handle the image and manifest pushing with a script executed after Goreleaser finishes.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

This is a nice to have. The script I am using works, but is annoying to develop. Goreleaser is functioning perfectly.

**Comment by caarlos0** [comment]
hey!

I think this should work:

```yaml
# .goreleaser.yaml
archives:
  - format: binary
 

docker: 
 - # ...

release:
  skip_upload: true

```

this way it'll still create the release, archive won't do anything, and it'll not add any artifacts to the release itself

**Comment by jsirianni** [comment]
> hey!
> 
> I think this should work:
> 
> ```yaml
> # .goreleaser.yaml
> archives:
>   - format: binary
>  
> docker: 
>  - # your docker configs et al...
> 
> release:
>   skip_upload: true
> ```
> 
> this way it'll still create the release, archive won't do anything, and it'll not add any artifacts to the release itself

Will this solution push the container images? My end goal is to have Goreleaser push the images and manifests.

**Comment by caarlos0** [comment]
yes, it should still push the container images, fury, etc, just won't upload anything to the release on github

**Comment by jsirianni** [comment]
Great, I will try that. I think this issue can be closed.
