### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#510]
I feel like goreleaser needs a new logo. The current gopher is cool but it doesn't remind anything related to what goreleaser does.

I suck at drawing and etc, but, maybe someone wants to contribute?

**Comment by amihaiemil** [comment]
@caarlos0 if you are willing to pay, I can recommend someone. She made my avatar, for instance, and her style seems in the theme of go's logos :)

**Comment by caarlos0** [comment]
@amihaiemil hmm, it depends how much would it cost (BRL is worth nothing idk)

**Comment by caarlos0** [comment]
I'm setting up an opencollective, maybe people donate and then I can use that money to pay for those things 😄 

https://opencollective.com/goreleaser/

**Comment by caarlos0** [comment]
My wife @carinebecker will try to design something again as well :D

**Comment by caarlos0** [comment]
I was thinking on something like a gopher riding a 🚀  or something like that...

**Comment by amihaiemil** [comment]
And with a helmet on its head, you used to play american footbal, right?

**Comment by caarlos0** [comment]
> And with a helmet on its head, you used to play american footbal, right?

that would be neat haha

**Comment by caarlos0** [comment]
![goreleaser](https://user-images.githubusercontent.com/245435/36649004-6a92e4c4-1a78-11e8-8542-74ee849a9e9f.png)

here it is, what do you think?

**Comment by amihaiemil** [comment]
@caarlos0 nice :)

**Comment by caarlos0** [comment]
ok, logo is decided, closing now :D
