### ISSUE TITLE
`git doesn't contain any tags` when using semver sorting

### ISSUE THREAD

**Issue by rootulp** [goreleaser/goreleaser#5110]
### What happened?

When I modify my https://github.com/celestiaorg/celestia-app/blob/main/.goreleaser.yaml to use [semver sorting](https://goreleaser.com/customization/git/#semver-sorting) then GoReleaser fails to create a release because

```
⨯ release failed after 0s                          error=git doesn't contain any tags. Either add a tag or use --snapshot
```

### How can we reproduce this?

1. Check out [this branch](https://github.com/celestiaorg/celestia-app/tree/rp/goreleaser-semver) or fork that repo and modify https://github.com/celestiaorg/celestia-app/blob/main/.goreleaser.yaml to have this diff:

    ```diff
    git:
      prerelease_suffix: "-rc*"
      tag_sort: semver
    ```
1. Run `make  prebuilt-binary`

    ```shell
    $ make prebuilt-binary
    docker run \
		    --rm \
		    -e CGO_ENABLED=1 \
		    --env-file .release-env \
		    -v /var/run/docker.sock:/var/run/docker.sock \
		    -v `pwd`:/go/src/github.com/celestiaorg/celestia-app/v3 \
		    -w /go/src/github.com/celestiaorg/celestia-app/v3 \
		    ghcr.io/goreleaser/goreleaser-cross:v1.22.6 \
		    release --clean
    WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
    Configure a credential helper to remove this warning. See
    https://docs.docker.com/engine/reference/commandline/login/#credential-stores
    
    Login Succeeded
    WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
    Configure a credential helper to remove this warning. See
    https://docs.docker.com/engine/reference/commandline/login/#credential-stores
    
    Login Succeeded
      • loading environment variables
        • using token from  $GITHUB_TOKEN
      • getting and validating git state
      ⨯ release failed after 0s                          error=git doesn't contain any tags. Either add a tag or use --snapshot
    make: *** [prebuilt-binary] Error 1
    ```

### goreleaser version

```bash
$ goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    2.2.0
GitCommit:     111121bbd98df17cc5d81888aa94a8d3694bc157
GitTreeState:  clean
BuildDate:     2024-08-15T01:56:53
BuiltBy:       homebrew
GoVersion:     go1.22.6
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I thought my local git version may have impacted this so I upgraded from git version 2.39.0 => 2.46.0. I don't know what git version is running in the goreleaser-cross Docker container.

Related but I don't expect this to cause the issue, VSCode complains that semver isn't a valid option

![Screenshot 2024-08-30 at 10 16 40 AM](https://github.com/user-attachments/assets/08900192-b592-48b8-8b0b-0447691541d8)

**Comment by caarlos0** [comment]
ahh, semver sorting is only available on goreleaser pro, if you're using the OSS version, that's why it didn't work

docs could probably be clearer about it, though

**Comment by rootulp** [comment]
> docs could probably be clearer about it, though

Agreed. In the screenshot below, this copy change would've helped me: "One or more features are available only with GoReleaser Pro" => "SemVer sorting is only available with GoReleaser Pro".

## Screenshot

![Screenshot 2024-09-03 at 10 07 06 AM](https://github.com/user-attachments/assets/c3fa68f6-3bc0-4de9-97fa-3c334c97b8e0)

**Comment by caarlos0** [comment]
should be more clear now
