### ISSUE TITLE
Brew OS-specific dependency is added for both mac and linux

### ISSUE THREAD

**Issue by jahvon** [goreleaser/goreleaser#5123]
### What happened?

In my goreleaser config I have a Homebrew dependency that is only needed on Linux, however it is also included on mac since the generated formula does not include the conditional for the dependency. I currently have the following block in my `goreleaser.yaml` file:

```
brews:
  - dependencies:
      - name: xclip
         os: linux
```

However, the generated Forumla includes `depends_on "xclip"` instead of `depends_on "xclip" if OS.linux?`

### How can we reproduce this?

This can be reproduced with a config similar to the one I shared above. You can see the full config I have in [here](https://github.com/jahvon/flow/blob/main/.goreleaser.yaml#L52-L54) and the generated formula [here](https://github.com/jahvon/homebrew-flow/blob/main/Formula/flow.rb).

### goreleaser version

```bash
GitVersion:    2.2.0
GitCommit:     111121bbd98df17cc5d81888aa94a8d3694bc157
GitTreeState:  clean
BuildDate:     2024-08-15T01:56:53
BuiltBy:       homebrew
GoVersion:     go1.22.6
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
hey! thanks for reporting this, its fixed on main!
