### ISSUE TITLE
`goreleaser-check` fails on v2.2.0 but not v2.1.0

### ISSUE THREAD

**Issue by rootulp** [goreleaser/goreleaser#5127]
### What happened?

This PR: https://github.com/celestiaorg/celestia-app/pull/3848 fails goreleaser-check because GoReleaser v2.2.0 includes https://github.com/goreleaser/goreleaser/pull/5019 which in my opinion is breaking. It was unexpected for me that bumping to this goreleaser-cross version: https://github.com/goreleaser/goreleaser-cross/pull/77 would require intervention from me as a developer because I'm bumping minor versions.

### How can we reproduce this?

See linked PRs above.

### goreleaser version

```bash
See linked PRs above.
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

My concrete feedback is that I think this deprecation should not fail `goreleaser-check` in a minor release. The rename could've been introduced with a warning in v2.x but should not fail `goreleaser-check` until the next major release. In the release notes for v3.x, it should be called out to users.

**Comment by caarlos0** [comment]
the point of `goreleaser check` is to check for deprecations, goreleaser still works with the previous name though.

the old option will be removed only in goreleaser v3.

https://goreleaser.com/blog/release-cadence/
