### ISSUE TITLE
Content form `go generate ./...` not used in build

### ISSUE THREAD

**Issue by OpenWaygate** [goreleaser/goreleaser#5136]
### What happened?

I use [go-winres](https://github.com/tc-hib/go-winres?tab=readme-ov-file) to generate a `rsrc_windows_amd64.syso`, which contain a icon and version info, this file will be used automatically by `go build`.

But goreleaser failed to use this file.
```shell
// project root, these 2 commands result in left picture
> go generate ./...
> go build
// project root, this result in right picture
> goreleaser build --snapshot --clean --single-target
```

![image](https://github.com/user-attachments/assets/8d635e41-acb2-4537-b305-f27f3372ab1c)

### How can we reproduce this?

This is my project, you can test it locally
https://github.com/eat-pray-ai/yutu

### goreleaser version

```bash
➜ goreleaser --version               
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    v2.2.0
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.23.1
Compiler:      gc
ModuleSum:     h1:IKWOpyx4A9gG/8o2AEN46PlV3qR/HqXVTHT6W+G8Qi0=
Platform:      windows/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
i would guess you probably need to change this `builds.main` to `.` instead of `main.go`
