### ISSUE TITLE
Apparent regression in goreleaser-pro v2.3.0 around docker builds

### ISSUE THREAD

**Issue by tstirrat15** [goreleaser/goreleaser#5138]
### What happened?

On the v2.3.0 release, our security check github action that uses goreleaser to build a snapshot image for test started failing. It appears that it's failing because the produced target is `linux_amd64_v1` but it's failing to associate that target with any of the docker image declarations.

I was unable to reproduce this locally with v2.3.0, which is what makes me think that it's pro-specific.

Downgrading to v2.2.0 fixed the issue, so we have a workaround for the time being.

Let me know if there's other context that would be helpful.

### How can we reproduce this?

Here's the configuration file that was failing: https://github.com/authzed/zed/blob/16b534dc31a2012e9593616440cb86b2f045b857/.goreleaser.yml

Note that that doesn't pass `check`, but modifying it to pass check didn't fix the issue.

Here's a link to the github action configuration: https://github.com/authzed/zed/blob/16b534dc31a2012e9593616440cb86b2f045b857/.github/workflows/lint.yaml#L74-L79

Here's a link to a failing run: https://github.com/authzed/zed/actions/runs/10853416407/job/30121632293

The step that it fails on is the trivy step, but it's because the build is being skipped in goreleaser:
```
   • docker images
    • pipe skipped                                   reason=4 errors occurred:
	* partial build, skipping Docker image that does not match target "linux_amd64_v1"
```

### goreleaser version

```bash
`:latest` on the github action. Presumably v2.3.0.
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
oh, sorry about that, gonna push the fix later today

thanks for reporting

**Comment by caarlos0** [comment]
v2.3.1 is going out right now with the fix!

thanks again for reporting it, and sorry for the trouble!

**Comment by tstirrat15** [comment]
@caarlos0 it's still erroring, albeit a slightly different error:

```
     • pipe skipped                                   reason=2 errors occurred:
	* expected to find 1 artifacts for ids [linux-arm64], found 0
Learn more at https://goreleaser.com/errors/docker-build

	* expected to find 1 artifacts for ids [linux-arm64], found 0
Learn more at https://goreleaser.com/errors/docker-build
```
It seems like it isn't correctly identifying `linux_arm64_v1` as the relevant build folder.

**Comment by caarlos0** [comment]
ooof, sorry about that.

I couldn't repro exactly that issue, but I found another one that might lead to it and I think might be the root cause.

To help debugging, here's a small reproducible with v2.3.1-pro: https://gist.github.com/caarlos0/e15affe4df085cb8eaa5fb845dad9cf9

with 2.3.1, if I run

```console
$ GOOS=linux GOARCH=amd64 goreleaser release --snapshot --single-target --clean
```

it works, but this fails:

```console
$ GOOS=linux GOARCH=arm64 goreleaser release --snapshot --single-target --clean
```

the output in your last comment though is a bit weird... it seems to be trying to build `linux_arm64` but finding no binaries... are you sure it was from a `linux_amd64_v1` build?

---

in either case, this issue I found is fixed on main, will release soon

**Comment by caarlos0** [comment]
I fired up a nightly build with the fix, would be awesome if you can try it out... 

Either way, will probably release it tomorrow

Thanks for reporting this btw, and again, sorry for the trouble

**Comment by tstirrat15** [comment]
Where would I find that nightly build?

**Comment by caarlos0** [comment]
@tstirrat15 sorry, forgot to link it, here: https://github.com/goreleaser/goreleaser-pro/releases/tag/nightly

**Comment by caarlos0** [comment]
> is the step that's failing. I'm assuming it's because it should be looking in `dist/linux_amd_64_v1` instead.

yes, it should be `dist/linux_amd64_v1/`, can probably also just `dist/*/metadata.json` so it works with other goos/goarch too

**Comment by tstirrat15** [comment]
Got it. Thanks!

**Comment by caarlos0** [comment]
cool, gonna push the tag, thanks again for the help!

**Comment by caarlos0** [comment]
its out, closing!

**Comment by jpkrohling** [comment]
We also use pro, and we got into a similar issue while releasing OTel Collector. Here's the build failure we've seen, using 2.3.2-pro: https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/11012954587

And here's a successful one, after reverting to 2.2.0-pro: https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/11015408925

**Comment by caarlos0** [comment]
ah, before it was building `linux_arm*`, which was incorrect, but worked in your case.

default `GOARM` is `6`, so its actually trying to build arm6 bins/pkgs: https://github.com/open-telemetry/opentelemetry-collector-releases/actions/runs/11012954587/job/30580223312#step:13:34

you can set `GOARM=7` and that should fix it
