### ISSUE TITLE
furies top-level key erroneously marked as invalid in goreleaser check

### ISSUE THREAD

**Issue by tstirrat15** [goreleaser/goreleaser#5139]
### What happened?

We use GemFury in our configuration: https://github.com/authzed/zed/blob/main/.goreleaser.yml#L121-L123

`goreleaser check` marks this as an error:
```
➜  zed git:(take-security-patch) ✗ goreleaser check
  ⨯ command failed                                   error=yaml: unmarshal errors:
  line 121: field furies not found in type config.Project
```

### How can we reproduce this?

Run `goreleaser check` on the linked configuration.

### goreleaser version

```bash
GitVersion:    2.3.0
GitCommit:     a9f07ef2eaff1d9172d616cd675af30e702b7a3a
GitTreeState:  false
BuildDate:     2024-09-12T17:26:40Z
BuiltBy:       goreleaser
GoVersion:     go1.23.1
Compiler:      gc
ModuleSum:     h1:yUJcO2E33SNxhVPga3SaZMZIyYC32x85tHP4fPStO98=
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tstirrat15** [comment]
The same is true of the `nightly` key - it appears to be valid according to the https://goreleaser.com/deprecations page, but `check` complains about it.

**Comment by caarlos0** [comment]
those are pro features, goreleaser pro need to be used to check those files

https://goreleaser.com/install/#pro

**Comment by tstirrat15** [comment]
@caarlos0 how do I run goreleaser-pro check?

I installed `goreleaser` via `snap` on ubuntu and when I invoke:

```sh
GORELEASER_KEY=<key> goreleaser check
``

I still get the error. Is this an issue with the distribution?

**Comment by caarlos0** [comment]
GoReleaser pro isn't available as a snap... 

Make sure goreleaser --version says it's goreleaser pro

**Comment by tstirrat15** [comment]
Got it. I downloaded the deb manually from the release page and it worked. Thank you!

**Comment by tstirrat15** [comment]
Is there a place where the yaml schema file for goreleaser-pro is published?

**Comment by caarlos0** [comment]
Hey, you can find them here: https://goreleaser.com/customization/
