### ISSUE TITLE
winget: `PackageVersion` should not be prefixed with `v`

### ISSUE THREAD

**Issue by andreynering** [goreleaser/goreleaser#5142]
### What happened?

For winget, all 3 files are generated with a `PackageVersion` prop prefixed with `v` like:

```yaml
PackageVersion: v1.2.3
```

This is not accepted by winget. It should not include `v`:

```yaml
PackageVersion: 1.2.3
```

### How can we reproduce this?

You can take our repository as an example: https://github.com/go-task/task

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    v2.3.2
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.23.0
Compiler:      gc
ModuleSum:     h1:/fSs+KwmCXCXN4eeI27z/xp1+FwIS4rWisL6aTUeiGw=
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
that's weird, goreleaser should be stripping the `v` prefix, e.g., see latest goreleaser release itself https://github.com/microsoft/winget-pkgs/pull/173953/files

**Comment by caarlos0** [comment]
I'll investigate it later today, thanks for the report!

**Comment by andreynering** [comment]
On Task, I have to fix this every time. In my case I open PRs manually to winget.

There is one detail that I forgot: the directory name also has the `v` prefix when it shouldn't. I also have to manually rename it from `v1.2.3` to `1.2.3`.

**Comment by caarlos0** [comment]
I can only repro that when I run it with `--snapshot`... regular runs get the right version though. 🤔

**Comment by caarlos0** [comment]
improved the docs for this, and opened a PR to task. Hopefully that's it, let me know if it isn't :)

**Comment by andreynering** [comment]
Thanks!
