### ISSUE TITLE
Different default `GOARM` value from Go.

### ISSUE THREAD

**Issue by nekohasekai** [goreleaser/goreleaser#5155]
### What happened?

https://github.com/goreleaser/goreleaser/blob/301b193e6e9b80f69a2bf0fe8b49357f3091521c/www/docs/customization/builds.md?plain=1#L110-L116

Default is 6

https://go.dev/doc/install/source#environment:

`$GOARM (for arm only; default is auto-detected if building on the target processor, 7 if not)`

Default is 7

Maybe the defaults in Go were changed, but it's reasonable to expect that goreleaser's defaults will be the same as Go's, so I recommend that you update the default GOARM value to 7.

### How can we reproduce this?

/

### goreleaser version

```bash
/
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
> Maybe the defaults in Go were changed, but it's reasonable to expect that goreleaser's defaults will be the same as Go's, so I recommend that you update the default GOARM value to 7.

i suspect so, yes, pretty sure it was 6 for a long time

**Comment by caarlos0** [comment]
old wiki fwiw: https://github.com/golang/go/wiki/GoArm/a3d2320b276781506f9b66aa0f2e74d56119b6a4

**Comment by caarlos0** [comment]
```console
$ GOOS=linux GOARCH=arm go env | grep GOARM
GOARM='7,hardfloat'
```

fwiw

**Comment by nekohasekai** [comment]
I doubt the old wiki was even ever correct.

I checked zbootstrap.go:

Until Go 1.20.14: defaultGOARM=5
Go 1.21.0: defaultGOARM=7

**Comment by nekohasekai** [comment]
In addition, goreleaser still has big problems with architecture-specific build parameters. Not only are `GO386`, GOARM64, GOPPC64, and GORISCV64 missing, but optional parameters such as `crypto` for GOARM64 are not handled. These missing parameters may be rarely used, but some of them are now required to build ipk (as a prerequisite for me to fix it).

I think variables such as `Goamd64` should be merged into a unified `Goarcharg`. If you have no objection, I will try to refactor and update my PR.

**Comment by caarlos0** [comment]
ok, gonna change it to 7

that said, some of these envs you mentioned are available, and the others can be set via the `env` option and templates, which may not be ideal, but they are used so rarely that i think its a good compromise.

https://goreleaser.com/customization/builds/

**Comment by caarlos0** [comment]
although, changing the default to 7 is a breaking change... gonna have to think about it

**Comment by nekohasekai** [comment]
Even though they are usually rarely used, this may change now that goreleaser now supports compiling ipk.

For example, my project sing-box has many openwrt users who need an installer that they can use, so I hope you will reconsider.

If I understand correctly, goreleaser uses goos goarch and goarcharg to uniquely identify a build, so I can't actually create what all those users need.

**Comment by caarlos0** [comment]
> If I understand correctly, goreleaser uses goos goarch and goarcharg to uniquely identify a build, so I can't actually create what all those users need.

you do, just would have to create more than one build probably

**Comment by nekohasekai** [comment]
I just regret that the ipk build for nfpm integration doesn't actually work.

Packages other than amd64 have the wrong arch and can't be installed, and since nfpm's Arch is not customizable in goreleaser, I can't build packages that common users need with workarounds, it seems.

**Comment by caarlos0** [comment]
> If goreleaser can build packages that can be used on openwrt out of the box, I think it's exciting and there should be a lot of people who want to use this feature.

well... you're the first one I've seen I think hehe 

but yeah, it doesn't allow it... maybe that could be another feature, something like `arch_overrides` to set the arch you need

**Comment by caarlos0** [comment]
I think this might be a good compromise #5157
