### ISSUE TITLE
Specify folder to include in tar.gz

### ISSUE THREAD

**Issue by deranjer** [goreleaser/goreleaser#517]
### Describe the feature and how you think it should work.

There might be an option for this but can't seem to find it anywhere.  I have a folder structure with a bunch of files that I want to bundle into my tar.gz file for release.  I could add all of them manually under "files:" but I was wondering if there was a way to add a folder there instead of all the files manually.

**Comment by deranjer** [comment]
Nevermind, maybe if I read the documentation closer I would know how to add a folder with /*

**Comment by deranjer** [comment]
Well, this doesn't work for a multiple folder structure, just for the files directly in that folder... might be something to add to the documentation.

**Comment by caarlos0** [comment]
hey @deranjer 

yeah, that's it :D 

maybe we can make the docs somewhat clearer about this?
