### ISSUE TITLE
authors key from Chocolatey configuration doesn't seem to propagate to .nuspec file

### ISSUE THREAD

**Issue by tstirrat15** [goreleaser/goreleaser#5174]
### What happened?

See this PR: https://github.com/authzed/spicedb/pull/2087

And this failing workflow: https://github.com/authzed/spicedb/actions/runs/11184220476/job/31094502246?pr=2087

The error message is:
```
  • chocolatey packages
    • packing                                        nuspec=dist\spicedb.choco\spicedb.nuspec
  ⨯ release failed after 4m34s               error=failed to generate chocolatey package: exit status 1: Chocolatey v2.3.0
ERROR: CHCR0001: authors is a required element in the package nuspec file.
```

I'd expect the `authors` key [here](https://github.com/authzed/spicedb/pull/2087/files#diff-2cfa04a3ce7a514ef6252824be52f84ec6aa7064e58ee79cf596dd4cd369d509R38) would get produced in the generated `.nuspec` file, unless there's something I'm missing about how the build process is supposed to work.

### How can we reproduce this?

See links in previous section.

### goreleaser version

```bash
Pro 2.3.2: https://github.com/authzed/spicedb/pull/2087/files#diff-374bd214cde16ea7ea23373ec846d6465445f3b8981702413ed4b01270cd1ad2R35-R48
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
per my testing, authors seems to be properly set in the nuspec: 

```yaml
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64

chocolateys:
  - use: archive
    authors: "someone"
```

then ran:

```sh
goreleaser release --snapshot --clean
```

and then looked into `./dist/*.choco/*.nuspec`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <id>test</id>
    <version>1.2.12-beta-SNAPSHOT-b86bab8</version>
    <title>test</title>
    <authors>someone</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description></description>
  </metadata>
  <files>
    <file src="tools\**" target="tools" />
  </files>
</package>
```

using goreleaser v2.3.2-pro.

**Comment by caarlos0** [comment]
I also cloned spicedb, made the change on `.goreleaser.windows.yml` and ran it, and `authors` seem to be properly set 🤔 

granted, I haven't tested on a windows machine yet, but the field definitely is in the nuspec file

**Comment by tstirrat15** [comment]
Oh! Can I run this on a non-windows container? I'd made the implicit assumption that I needed a windows container. How did you install `chocolatey` on a non-windows box? The chocolatey docs seem to make the assumption that you're in a windows environment.

**Comment by caffeine-addictt** [comment]
> How did you install `chocolatey` on a non-windows box

[here's](https://github.com/caffeine-addictt/waku/blob/main/.github/workflows/release.yml#L57-L65) how I'm doing it in `ubuntu-latest`.

**Comment by caarlos0** [comment]
you don't need to install chocolatey to run it, it will fail because choco is not available, but at that point it would already be generated the nuspec file

**Comment by caarlos0** [comment]
any new info on this? did you figure it out?

**Comment by tstirrat15** [comment]
@caarlos0 it's gotten bumped down the priority list a bit - I'm hoping to get to it by the end of the week. Thank you for pointing me in the right direction!

**Comment by tstirrat15** [comment]
I'm able to verify that the `.nuspec` file exists and that it has an `authors` key within it, but I'm still getting the error. The next thing I'd want to do is make sure that `choco` is actually looking at that file, but I can't see that particular part of the source. How is goreleaser-pro invoking `choco`?

**Comment by caarlos0** [comment]
hmmm afaik it should be correct, but here you go:

- pack: https://github.com/goreleaser/goreleaser/blob/6a84e401158d4d144bf9c48f83fb4f699f84cab2/internal/pipe/chocolatey/chocolatey.go#L158
- push https://github.com/goreleaser/goreleaser/blob/6a84e401158d4d144bf9c48f83fb4f699f84cab2/internal/pipe/chocolatey/chocolatey.go#L201-L210

**Comment by tstirrat15** [comment]
Okay so:

I've captured the contents of the `nuspec` file in the github action, and the `authors` tag is empty: https://github.com/authzed/spicedb/actions/runs/11487450954/job/31972032420?pr=2087

That behavior isn't the same as running `goreleaser-pro` locally - I was able to run a dry publish locally with this version:
```
➜  spicedb git:(fix-windows-release-process) ✗ goreleaser --version
  ____       ____      _                            ____
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __  |  _ \ _ __ ___
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__| | |_) | '__/ _ \
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |    |  __/| | | (_) |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|    |_|   |_|  \___/
goreleaser-pro: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com/pro

GitVersion:    2.3.2-pro
GitCommit:     7470a5eeee3f6a26734f6cebcbcc1401cb9e8aad
GitTreeState:  clean
BuildDate:     2024-09-17T17:20:07Z
BuiltBy:       goreleaser
GoVersion:     go1.23.1
Compiler:      gc
ModuleSum:     unknown
Platform:      linux/amd64
```

and got this nuspec file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <id>spicedb</id>
    <version>1.37.1-next</version>
    <packageSourceUrl>https://github.com/authzed/spicedb</packageSourceUrl>
    <owners>AuthZed, Inc</owners>
    <title>SpiceDB</title>
    <authors>SpiceDB Contributors</authors>
    <projectUrl>https://github.com/authzed/spicedb</projectUrl>
    <iconUrl>https://authzed.com/favicon.svg</iconUrl>
    <copyright>2024 AuthZed, Inc</copyright>
    <licenseUrl>https://github.com/authzed/spicedb/blob/main/LICENSE</licenseUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <projectSourceUrl>https://github.com/authzed/spicedb</projectSourceUrl>
    <docsUrl>https://authzed.com/docs</docsUrl>
    <bugTrackerUrl>https://github.com/authzed/spicedb/issues</bugTrackerUrl>
    <tags>spicedb zanzibar authz rebac rbac abac fga</tags>
    <summary>SpiceDB is a graph database purpose-built for storing and evaluating access control data.</summary>
    <description>Open Source, Google Zanzibar-inspired permissions database to enable fine-grained access control for customer applications&#xA;</description>
    <releaseNotes>https://github.com/authzed/spicedb/releases/tag/v1.37.1-next</releaseNotes>
  </metadata>
  <files>
    <file src="tools\**" target="tools" />
  </files>
</package>
```

Note the nonempty `authors` tag.

I'm kind of at a loss here. Any thoughts?

**Comment by tstirrat15** [comment]
PBCAK. I had pinned the ref that the ref that the checkout step used, which meant that it was looking at a stale version of the files. I can't remember why I did that.

**Comment by tstirrat15** [comment]
And I had a successful publish. Thank you for your help!
