### ISSUE TITLE
goreleaser doesn't respect time zones

### ISSUE THREAD

**Issue by huhu415** [goreleaser/goreleaser#5206]
### What happened?

when i set time zone like this 
```
# Make sure to check the documentation at https://goreleaser.com
version: 2

env:
  - TZ=Asia/Shanghai
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
```

then i use build ldflags **.Date**
```
    ldflags:
      - -s -w
      - -X uaProxy/bootstrap.Version={{.Version}}
      - -X uaProxy/bootstrap.BuildDate={{.Date}}
```
it time like this `buildDate:2024-10-15T14:40:28Z`, this is not `TZ=Asia/Shanghai`, it is 0 time zone.

### How can we reproduce this?

file is in before.

### goreleaser version

```bash
GitVersion:    2.3.2
GitCommit:     e8c2ef77358b4b1e59b904322824ccbfa3487ab2
GitTreeState:  clean
BuildDate:     2024-09-17T12:30:49
BuiltBy:       homebrew
GoVersion:     go1.23.1
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

If we're going to fix this thing. i think code [is](https://github.com/goreleaser/goreleaser/blob/91525f763cd91275bec41f193f6a3d58170e451b/internal/tmpl/tmpl.go#L119) here, i may can fix it.

**Comment by caarlos0** [comment]
goreleaser always uses UTC. Nowhere it says you can use a custom timezone.

You can though set your own build time in the timezone you wish and pass it down to the ldflags.

that said, this is not something we will fix.
