### ISSUE TITLE
`{{ .Os_userfriedly }}-{{ .Arch_userfriedly }}`

### ISSUE THREAD

**Issue by stephane-archer** [goreleaser/goreleaser#5211]
### Is your feature request related to a problem? Please describe.

`{{ .Os }}` is not great for distributing software to non-technical people, another template variable should be created like `{{ .Os_userfriedly }}`
darwin should be named MacOS
windows should be Windows
linux should be Linux

the same applies for `{{ .Arch }}`
for MacOS it should be "Intel" or "Mseries" because most people have no idea what `darwin-arm64` is and what they should download from there computers

### Describe the solution you'd like

up

### Describe alternatives you've considered

up

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I'm not sure we can all agree on what the user friendly names should be, specially regarding the Arch bit. Also, Apple calls it `macOS` (without the capital M).

Not sure we should do this, honestly.

You can fix it to your liking with templates already, but I agree, it's too repetitive and looks awful. 

Maybe a global `replaces` directive, kinda like we have on archives, but for everything?

**Comment by caarlos0** [comment]
thinking more about it, even a global replaces wouldn't work, as you might want different arch names per OS...

**Comment by stephane-archer** [comment]
When you say i can fix it with templates, do you mean using the ´{{ if }}´ syntax ? Do you have any docs on the exact syntax, I struggled with making it work.
What do you think about been able to choose between 'darwin' to 'macOS'?. And adding a syntax to capitalize the first letter of any template variable would be nice.
Regarding naming architecture for different OS I imagine I can just use template to overwrite arm64 to Mseries for macOS 
What's your thoughts about that?

**Comment by stephane-archer** [comment]
I imagine I can already achieve what I want with template but I just don't get the syntax. Maybe I didn't find the proper doc to make it click for me. Some heater function would be nice

**Comment by caarlos0** [comment]
for instance: https://github.com/goreleaser/goreleaser/blob/248c7fcb5f8a2ec9972f181dbd096a0fa135b059/.goreleaser.yaml#L178-L184

**Comment by caarlos0** [comment]
after giving this more though, I decided against it. It is already possible with templates, and most of the ideas I had around it just made it more complicated...
