### ISSUE TITLE
Feature Request: Add RISC-V 64-bit (riscv64) Build Target

### ISSUE THREAD

**Issue by gounthar** [goreleaser/goreleaser#5213]
## Overview
I would like to request consideration for adding RISC-V 64-bit (riscv64) as a build target to GoReleaser's supported platforms.

## Rationale
- RISC-V is gaining significant momentum in the open-source hardware community
- Major Linux distributions now provide RISC-V support
- Go 1.19+ includes official support for linux/riscv64
- Adding riscv64 support would enable projects to be more inclusive of this emerging architecture

## Technical Details
The Go compiler already supports RISC-V 64-bit via:
- GOOS: linux
- GOARCH: riscv64

## Proposed Implementation
This would involve adding riscv64 to the supported architectures list, similar to existing targets like amd64, arm64, etc.

## Questions
1. Would this addition align with GoReleaser's roadmap?
2. Are there any technical considerations I should be aware of?

I appreciate your taking the time to consider this request and am happy to provide any additional information needed.

### Describe alternatives you've considered

I can see the repo is evolving in accepting `riscv64`, as I have just spotted this: https://github.com/goreleaser/goreleaser/commit/6a84e401158d4d144bf9c48f83fb4f699f84cab2.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I have just built the master branch on my `riscv64` machine:
```
[milkv@fedora-riscv goreleaser-2.3.2]$ go build -o goreleaser .
./goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    devel
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.23.0
Compiler:      gc
ModuleSum:     unknown
Platform:      linux/riscv64
```

**Comment by caarlos0** [comment]
its already on main https://github.com/goreleaser/goreleaser/commit/6a84e401158d4d144bf9c48f83fb4f699f84cab2

see #5196
