### ISSUE TITLE
Issues Using GoReleaser after v2 Update: `version: 2 are supported, yours is version: 0`, `field build not found in type config.Project`, etc.

### ISSUE THREAD

**Issue by pranav-new-relic** [goreleaser/goreleaser#5229]
### What happened?

Hi @caarlos0! 👋 

I am a contributor and maintainer of https://github.com/newrelic/newrelic-client-go, as Go-based SDK, and we use goreleaser to perform our releases in this repo and a bunch of other ones we maintain.

We recently updated a bunch of dependencies in our repo, [including goreleaser](https://github.com/newrelic/newrelic-client-go/blame/36f4c084b26b23510d429e00ead80580e13cf4df/tools/go.mod#L10) (from v1.26.2 -> v2.2.0) and updated all references of goreleaser to goreleaser/v2 in the code.

However, upon triggering a release today, our release workflow which has been working fine, suddenly started to show this error

```
only configurations files on version: 2 are supported, yours is version: 0, please update your configuration
``` 
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/9948b71f-4755-4802-83f1-f7ccbc8efd27">

- It seemed that [this portion](https://github.com/newrelic/newrelic-client-go/blob/36f4c084b26b23510d429e00ead80580e13cf4df/build/release.mk#L22-L24) which was run by `make release`, errored out as seen in the CI when trying to run [this script file](https://github.com/newrelic/newrelic-client-go/blob/main/scripts/release.sh) which comprises the actual code section which gets git diffs and runs goreleaser to complete the release. 

- What's also interesting is, while this error seemed to have surfaced and the CI screenshot I've attached also indicates that the error caused the release to fail, the release actually got picked up out of the repo (such as `go.dev`, where [v2.49.0](https://pkg.go.dev/github.com/newrelic/newrelic-client-go/v2@v2.49.0), the release that failed in the CI did get updated with the right changes, and we were able to use them in a downstream service). While I'm not sure if `go.dev` and similar other sites operate via the artifacts goreleaser publishes or directly from the GitHub repo, it was surprising for me to see this happen, as the releases tab of our repo did not get updated with the artifacts and the latest release either, as you may still see in the repo.

<img width="359" alt="image" src="https://github.com/user-attachments/assets/7b4502d3-de20-481a-b3a7-0b3cd04f3c63">

So, in order to troubleshoot this error, I found [this reference in GoReleaser's docs](https://goreleaser.com/errors/version/), which is when I realised something _probably_ isn't right with the `.goreleaser.yml` in the repository. After having seen a million references in other repositories which seem to have placed `version: 2` in the file, I went ahead and did the same; and [upon merging this change](https://github.com/newrelic/newrelic-client-go/blob/main/.goreleaser.yml#L1) and running the release again, this only ran into more errors:

```
  line 11: field build not found in type config.Project
```
```
  line 16: field skip not found in type config.Changelog
```

<img width="710" alt="image" src="https://github.com/user-attachments/assets/57fd7f80-fa15-4c55-aead-0def60d61f4b">

What's worth noting is that I find one difference between the procedure most others use to operate on GoReleaser: a run goreleaser job is added to the `release.yml` file that runs in the CI using the `gorelease-actions` action, while we use the goreleaser command to perform a build that would subsequently release; I'm not sure how I should be operating with the kind of structure our repo uses with goreleaser to actually set the version to `2`, which is what I need some help with.

I'm not reporting this as a bug, I feel like something mustn't be right with the kind of configuration we're using, it'd be great if you can help us what we should be doing to continue to use `goreleaser/v2` without these errors :) this would greatly help us with clearing obstructions with our release pipeline (which, like I mentioned above, isn't showing the latest release in the repo, though `go.dev` does have the latest release). Thanks!

#### Quick Links

Attaching these _if_ you can take a look at your convenience, to comprehend with the scenario of ours leading to this error :) 

- Our repository's `release.yml`: https://github.com/newrelic/newrelic-client-go/blob/main/.github/workflows/release.yml
- Our repository's `release.mk`: https://github.com/newrelic/newrelic-client-go/blob/main/build/release.mk
- Our repository's `release.sh` that is run by `release.mk`: https://github.com/newrelic/newrelic-client-go/blob/main/scripts/release.sh
- Our repository's [`tools.go`](https://github.com/newrelic/newrelic-client-go/blob/main/scripts/release.sh) that now uses `goreleaser/v2` instead of `goreleaser`, as you may see in [`tools/go.mod`](https://github.com/newrelic/newrelic-client-go/blob/main/tools/go.mod#L10)

#### Additional Context

While the error I've attached above says `only configurations files on version: 2 are supported, yours is version: 0, please update your configuration`, upon trying to run `gorelease check` locally in this repo, I see ` ⨯ command failed                                   error=only configurations files on  version: 1  are supported, yours is  version: 2 , please update your configuration
`, not really sure what's going on. 

Thank you in advance for the help :) 
 

### How can we reproduce this?

~

### goreleaser version

```bash
(this is what I see when I print it when locally using the repo from my IDE)

  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    v1.26.2
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.22.6
Compiler:      gc
ModuleSum:     h1:1iY1HaXtRiMTrwy6KE1sNjkRjsjMi+9l0k6WUX8GpWw=
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
the first error happens only if there are other errors in your configuration.

when you added the `version: 2` bit, it showed what they are:

- `build` no found
- `changelog.skip` not found

those are properties that were deprecated in v1 and removed in v2, see:

- https://goreleaser.com/deprecations/#build
- https://goreleaser.com/deprecations/#changelogskip

you can run `goreleaser check` (using v1) to show all the deprecations, fix them, and then update to v2.

also see the migration guide at: https://goreleaser.com/blog/goreleaser-v2/#upgrading
