### ISSUE TITLE
Pro: NPE when using artifacts/image filter on before_publish hook 

### ISSUE THREAD

**Issue by jonathon-day** [goreleaser/goreleaser#5230]
### What happened?

I am testing container scanning via a before_publish hook. The docker build succeeds but the before_publish hook encounters a null pointer exception.

```
before_publish:
  - cmd: "echo 'command does not matter'"
    artifacts:
      - image
```      

### How can we reproduce this?

This is a private repo. Hopefully since this has a stack trace it will be straight forward to at least get a better error in place of an NPE. If necessary I may be able to work on getting a minimal reproducible example on a public repo.

Update: I found this is reproducible with a very minimal goreleaser config without needing to build a binary or image:
```
version: 2

builds:
  - skip: true
before_publish:
  - cmd: "echo 'command does not matter'"
    artifacts:
      - image
```

### goreleaser version

```bash
____       ____      _                            ____
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __  |  _ \ _ __ ___
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__| | |_) | '__/ _ \
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |    |  __/| | | (_) |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|    |_|   |_|  \___/
goreleaser-pro: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com/pro

GitVersion:    2.3.2-pro
GitCommit:     7470a5eeee3f6a26734f6cebcbcc1401cb9e8aad
GitTreeState:  clean
BuildDate:     2024-09-17T17:20:07Z
BuiltBy:       goreleaser
GoVersion:     go1.23.1
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

 ```
 • running before-publish hooks
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd3f088e]

goroutine 83 [running]:
github.com/goreleaser/goreleaser/v2/internal/pipe/beforepublish.Pipe.Run.And.func12(0xc00093c1b0)
        github.com/goreleaser/goreleaser/v2/internal/artifact/artifact.go:579 +0x4e
github.com/goreleaser/goreleaser/v2/internal/artifact.(*Artifacts).Filter(0xc000984680, 0xc000aedc90)
        github.com/goreleaser/goreleaser/v2/internal/artifact/artifact.go:598 +0xd2
github.com/goreleaser/goreleaser/v2/internal/pipe/beforepublish.Pipe.Run({}, 0xc0007f5308)
        github.com/goreleaser/goreleaser/v2/internal/pipe/beforepublish/beforepublish.go:62 +0x22e
github.com/goreleaser/goreleaser/v2/cmd.releaseProject.func1.Handle.1(0xe685d8e?)
        github.com/goreleaser/goreleaser/v2/internal/middleware/errhandler/error.go:15 +0x1b
github.com/goreleaser/goreleaser/v2/cmd.releaseProject.func1.Log.2(0xc0007f5308)
        github.com/goreleaser/goreleaser/v2/internal/middleware/logging/logging.go:36 +0x97
github.com/goreleaser/goreleaser/v2/internal/middleware/skip.Maybe.func1(0xc0007f5308)
        github.com/goreleaser/goreleaser/v2/internal/middleware/skip/skip.go:42 +0x10c
github.com/goreleaser/goreleaser/v2/cmd.releaseProject.func1()
        github.com/goreleaser/goreleaser/v2/cmd/release.go:149 +0x182
github.com/caarlos0/ctrlc.(*Ctrlc).Run.func1()
        github.com/caarlos0/ctrlc@v1.2.0/ctrlc.go:48 +0x23
created by github.com/caarlos0/ctrlc.(*Ctrlc).Run in goroutine 1
        github.com/caarlos0/ctrlc@v1.2.0/ctrlc.go:47 +0x94

```

**Comment by caarlos0** [comment]
thanks for the report! Going to investigate and fix it!

**Comment by caarlos0** [comment]
fixed it! 

running a nightly build now, if you want to try it out!

if all goes well, gonna release a stable over the weekend.

thanks again for the detailed report and for being a pro user ❤️

**Comment by jonathon-day** [comment]
> fixed it!
> 
> running a nightly build now, if you want to try it out!
> 
> if all goes well, gonna release a stable over the weekend.
> 
> thanks again for the detailed report and for being a pro user ❤️
> 
> EDIT: forgot to link the nightly releases: https://github.com/goreleaser/goreleaser-pro/releases/nightly

Thanks for the quick response! I tested the nightly and verified the crash is fixed. I am now seeing however that the hook is being skipped as it does not recognize any images even though an image artifact was successfully added. I'll put up a new issue later today with details
