### ISSUE TITLE
Allow for skipping the build step

### ISSUE THREAD

**Issue by mowies** [goreleaser/goreleaser#5234]
### Is your feature request related to a problem? Please describe.

My use case:
I want to build a linux service (using nfpm) with goreleaser, but with a binary that was built from main branch in a different GitHub repo.
So I would like to be able to copy the already built binary into the dist folder and then just package it into a linux service.

This use case came up in the OpenTelemetry Collector repos. ([related issue](https://github.com/open-telemetry/opentelemetry-collector-releases/issues/659))

### Describe the solution you'd like

Skipping the build should have the effect that goreleaser expects a prebuilt artifact in the dist folder.

### Describe alternatives you've considered

None

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] ~I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer~
- [X] The OpenTelemetry project is a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
you can already do that:

```yaml
version: 2

project_name: foo

builds:
  - skip: true

nfpms:
  - {}
```

just put the binary in the root folder instead of dist, and it should work I think

**Comment by caarlos0** [comment]
you can also use the prebuilt builder if you're using goreleaser-pro: 

https://goreleaser.com/customization/builds/#import-pre-built-binaries

**Comment by caarlos0** [comment]
oh, if you just want to use nfpm, you can use it directly without goreleaser as well 

https://nfpm.goreleaser.com

**Comment by mowies** [comment]
but can I also invoke that from the CLI or from the GitHub action without changing the goreleaser config file?
Ideally the config can be left as is and I just manipulate the behaviour with CLI or github action.
Something like:
```
goreleaser release --snapshot --skip=build
```

I guess one other option would be to use a template for the `builds.skip` field and use an env variable for it that I can set from the outside.

**Comment by caarlos0** [comment]
yes, you can template `builds.skip`!

**Comment by mowies** [comment]
Ah cool that sounds like a good option, I'll try that out and re-open if I need something more :)

**Comment by mowies** [comment]
@caarlos0 I tried 

> ```yaml
> version: 2
> 
> project_name: foo
> 
> builds:
>   - skip: true
> 
> nfpms:
>   - {}
> ```
> 
> just put the binary in the root folder instead of dist, and it should work I think

I tried that now, but I don't think this works with the prebuilt binary in the root folder...
I also tried copy the prebuilt binary into the dist folder, but GoReleaser wants the folder clean before doing anything.

**Comment by caarlos0** [comment]
ah, true, nfpm expects a build.

okay, so the way to get this working is with prebuilt binaries (requires pro).

```yaml
# .goreleaser.yml
version: 2
builds:
  - builder: prebuilt
    goos: [linux]
    goarch: [amd64, arm64]
    prebuilt:
      path: ./foo_{{.Os}}_{{.Arch}}
nfpms:
  - formats:
      - deb
```

```gitignore
# .gitignore
foo_*
dist/
```

and then you build your binaries to the repo's root, like so:

```sh
GOOS=linux GOARCH=amd64 go build -o foo_linux_amd64 .
GOOS=linux GOARCH=arm64 go build -o foo_linux_arm64 .
```

and run goreleaser:

```sh
goreleaser release --clean --snapshot
```

hope that helps!
