### ISSUE TITLE
release failed when no previous tag detected with version 2.4.1

### ISSUE THREAD

**Issue by piontec** [goreleaser/goreleaser#5240]
### What happened?

`goreleaser` fails as shown on the attached screenshot. This was working with the 2.3.x branch
![Screenshot from 2024-11-04 10-42-29](https://github.com/user-attachments/assets/5401ef66-c23b-4fdb-b9e0-f6acea3f6cb5)

### How can we reproduce this?

Run `goreleaser release` with a configuration that creates a github release with a changelog on a repo that hasn't been released yet and has just 1 tag.

### goreleaser version

```bash
2.4.1
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
is there a previous tag in the repo?

**Comment by caarlos0** [comment]
btw this will only happen when `changelogger: github`

**Comment by caarlos0** [comment]
okay, so #5242 should fix it by using `git` by default when no previous tag
