### ISSUE TITLE
Problem with ARM64 target docker builds

### ISSUE THREAD

**Issue by erikburt** [goreleaser/goreleaser#5245]
### What happened?

Something has changed from v2.3.2 which has broken our pipeline for ARM64 partial builds. It seems as though docker builds are filtering out arm64 targets architectures?

I believe the problem is here, but it's mostly a guess: https://github.com/goreleaser/goreleaser/blob/cc4427f346b811872b2615c4486fc824d5269c6a/internal/pipe/docker/docker.go#L137-L139

Some more information:
- Example successful run: https://github.com/smartcontractkit/chainlink/actions/runs/11674028039/job/32505921261#step:5:731
- Example unsuccessful run: https://github.com/smartcontractkit/chainlink/actions/runs/11673641339/job/32504789396#step:5:727
- Our goreleaser config: https://github.com/smartcontractkit/chainlink/blob/develop/.goreleaser.develop.yaml
- Our action entrypoint for CICD builds: https://github.com/smartcontractkit/chainlink/blob/develop/.github/actions/goreleaser-build-sign-publish/action.yml

### How can we reproduce this?

Unfortunately, I don't have a reproduction outside of CICD. Will post back if I can create one on a linux VM as my MacOS env doesn't match the Github Runners.

### goreleaser version

```bash
Here is my local version, we are using linux/arm64 in CICD.

---

  ____       ____      _                            ____
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __  |  _ \ _ __ ___
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__| | |_) | '__/ _ \
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |    |  __/| | | (_) |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|    |_|   |_|  \___/
goreleaser-pro: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com/pro

GitVersion:    2.4.3-pro
GitCommit:     0a2eeed1b7bcea3d60e1c882c6bdbeca4e25a108
GitTreeState:  clean
BuildDate:     2024-11-04T17:14:25Z
BuiltBy:       goreleaser
GoVersion:     go1.23.2
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
sorry for the issues, and thanks for reporting it.

a fix is on its way!

**Comment by caarlos0** [comment]
2.4.4-pro is out! Per my testing, it should be good now!

Again sorry for the trouble, and thanks for the understanding 💜

**Comment by erikburt** [comment]
That did the trick! Thank you for the quick turnaround.
