### ISSUE TITLE
github dep causes go-get to fail

### ISSUE THREAD

**Issue by lrstanley** [goreleaser/goreleaser#527]
With master, it looks as though goreleaser is no longer `go get`'able.

```console
liam:~$ go get -v -u github.com/goreleaser/goreleaser
[...]
go/src/github.com/goreleaser/goreleaser/internal/client/github.go:120:22: cannot use release.GetID() (type int64) as type int in return argument
go/src/github.com/goreleaser/goreleaser/internal/client/github.go:132:28: cannot use releaseID (type int) as type int64 in argument to c.client.Repositories.UploadReleaseAsset
```

Full output: http://dropb.in/t/kinreh

Looks like this may be due to upstream commit https://github.com/google/go-github/commit/e48060a28fac52d0f1cb758bc8b87c07bac4a87d

**Comment by zcong1993** [comment]
seems to me

**Comment by caarlos0** [comment]
hey 👋

should be good now, thanks for reporting.


ps: you shouldn't use the master to release your projects, as the master can be broken at times... use the release binaries 🍻
