### ISSUE TITLE
Slash in tag not handled correctly for git + homebrew

### ISSUE THREAD

**Issue by alapidas** [goreleaser/goreleaser#5282]
### What happened?

I'm using goreleaser to publish a homebrew tap.  I am also using monorepo support to use tags of the format `spa-explorer/xxxxxxxx`.  Relevant stanza from `.goreleaser.yaml` below:
```
monorepo:
  tag_prefix: spa-explorer/
  dir: .

brews:
  - name: spa-explorer
    repository:
      owner: <myOrg>
      name: spa-tools
      branch: master
```

It appears to work correctly, but after tapping and trying to download the binary, it fails:

```
at 13:09:36 ➜ brew install spa-explorer
==> Fetching <myOrg>/spa-tools/spa-explorer
==> Downloading https://github.com/<myOrg>/spa-tools/releases/download/spa-explorer/v0.72.0/spa-explorer_Darwin_arm64.tar.gz
curl: (56) The requested URL returned error: 404

Error: spa-explorer: Failed to download resource "spa-explorer"
Download failed: https://github.com/<myOrg>/spa-tools/releases/download/spa-explorer/v0.72.0/spa-explorer_Darwin_arm64.tar.gz
```

If I pop over to my releases page, and look for that URL, I see this:
https://github.com/confluentinc/spa-tools/releases/download/spa-explorer%2Fv0.72.0/spa-explorer_Darwin_arm64.tar.gz

NOTE the `%2f` in place of a slash in the URL.  I _think_ github is URL encoding it because it's not part of the path.  From [this doc](https://docs.github.com/en/rest/using-the-rest-api/troubleshooting-the-rest-api?apiVersion=2022-11-28#404-not-found-for-an-existing-resource):
> Additionally, any path parameters must be URL encoded. For example, any slashes in the parameter value must be replaced with %2F. If you don't properly encode any slashes in the parameter name, the endpoint URL will be misinterpreted.

### How can we reproduce this?

I don't have this set up in a public repo, but if you use monorepo support + a tag with a slash in it, and homebrew integration, I _think_ this would be repro

### goreleaser version

```bash
at 14:22:38 ➜ curl -sfL https://goreleaser.com/static/run | VERSION=v2.4.5-pro bash -s -- --version 
Using Pro distribution...
Downloading GoReleaser v2.4.5-pro...
Verifying checksums...
Verifying signatures...
Verified OK
  ____       ____      _                            ____
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __  |  _ \ _ __ ___
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__| | |_) | '__/ _ \
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |    |  __/| | | (_) |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|    |_|   |_|  \___/
goreleaser-pro: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com/pro

GitVersion:    2.4.5-pro
GitCommit:     a1a004551c54bc3253a91f166b71fcc94198e731
GitTreeState:  clean
BuildDate:     2024-11-14T11:28:56Z
BuiltBy:       goreleaser
GoVersion:     go1.23.3
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64

```
```


### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_

**Comment by caarlos0** [comment]
ahh good catch! will fix it, thanks!

**Comment by caarlos0** [comment]
triggered nightly releases with the fix.

point release probably monday morning/sunday night

thanks for reporting this btw @alapidas!
