### ISSUE TITLE
Support multi-platform docker images

### ISSUE THREAD

**Issue by pcarranza** [goreleaser/goreleaser#530]
I would like go-releaser to support releasing [multi-platform docker images](https://blog.docker.com/2017/09/docker-official-images-now-multi-platform/) using something like https://github.com/estesp/manifest-tool

This way, if the project is being built for multiple platforms, we will only use a single docker repository.

**Comment by caarlos0** [comment]
To be honest I don't know this docker feature very well, so I'll have to study and see if/how it fits :) 

but thanks for suggesting it anyway =D

**Comment by pcarranza** [comment]
Hah, neither do I XD

I have to investigate it myself, next month I can yield out what the results of my investigations are as I am already building lots of ARM docker images myself for multiple things, so it would be neat to just have goreleaser dealing with it all automagically, we already have the binaries built anyway.

**Comment by pcarranza** [comment]
@caarlos0 I did some digging, the way this docker feature works is by grouping all the images in one manifest, so there is a single _docker image_ that is grouping them all an providing different archs and/or features, then docker itself picks what it needs.

It is still necessary to push different images, one for each arch, this can be done in the same repo or in different repos, meaning that you can still have, for ex, goreleaser-amd64:latest for linux/amd64 and goreleaser-armv6:latest. Then you can have goreleaser:latest that will be the grouping of both repos, providing different architectures.

This manifest tool is actually quite nice, look at this snippet from the readme:

```
$ ./manifest-tool push from-args \
    --platforms linux/amd64,linux/arm,linux/arm64 \
    --template foo/bar-ARCH:v1 \
    --target foo/bar:v1
```

This means that with minimal changes we could be templating the repo and in a single command build a core repo that has images for different architectures.

Now, probably the question is: given the goreleaser architecture, what would be the right way of inserting this in the current architecture? could you give me some high-level pointers about the project style?

**Comment by caarlos0** [comment]
hey @pcarranza, I haven't look into this yet.

Seems to me that the `manifest-tool push` is already covered by goreleaser in some way...

I was looking into [this](http://callistaenterprise.se/blogg/teknik/2017/12/28/multi-platform-docker-images/), and seems to me that the only thing missing is to create and push the manifest list... 

Not sure yet how's the best way of doing that though

**Comment by pcarranza** [comment]
@caarlos0 I think you're right, all the pieces are in the docker pipeline, particularly in the [publish](https://github.com/goreleaser/goreleaser/blob/master/pipeline/docker/docker.go#L202-L205) function is where we could be getting things in. 

I only wonder (from my complete lack of knowledge) if we can build the manifest here or if we should be building it way before in [process](https://github.com/goreleaser/goreleaser/blob/master/pipeline/docker/docker.go#L144).

**Comment by pcarranza** [comment]
No, wait, after pushing we have a set of docker images in the context, we could simply add another pipeline after docker that will get all these images and build the manifest to then invoke the `manifest-tool` all the data is available right there.

**Comment by pcarranza** [comment]
Ok, I did some testing, and this is actually quite nice

```
macbook meeseeks-box-manifest$ cat meeseeks-box-manifest.yml
image: "registry-1.docker.io/pcarranza/meeseeks-box:0.0.29"
manifests:
  - image: "registry-1.docker.io/pcarranza/meeseeks-box-amd64:0.0.29"
    platform:
      architecture: amd64
      os: linux
  - image: "registry-1.docker.io/pcarranza/meeseeks-box-armv6:0.0.29"
    platform:
      architecture: arm
      variant: v6
      os: linux

macbook meeseeks-box-manifest$ manifest-tool-darwin-amd64 --username=pcarranza --password=$DOCKER_PASSWORD --debug  push from-spec meeseeks-box-manifest.yml
DEBU[0000] endpoints: [{false https://registry-1.docker.io v2 false true 0xc42032e180} {false http://registry-1.docker.io v2 false true 0xc42032e180}] 
DEBU[0000] repoName: pcarranza/meeseeks-box             
INFO[0000] Retrieving digests of images...              
DEBU[0000] endpoints: [{false https://registry-1.docker.io v2 false true 0xc42032e780} {false http://registry-1.docker.io v2 false true 0xc42032e780}] 
DEBU[0000] Trying to fetch image manifest of registry-1.docker.io/pcarranza/meeseeks-box-amd64 repository from https://registry-1.docker.io v2 
INFO[0004] Image "registry-1.docker.io/pcarranza/meeseeks-box-amd64:0.0.29" is digest sha256:1a33cbe2521b6854654fa15b6fb12567d876fe03978a51f2a949c5ef915dcfd3; size: 949 
DEBU[0004] Adding manifest references of "registry-1.docker.io/pcarranza/meeseeks-box-amd64:0.0.29" to blob mount requests 
DEBU[0004] Adding manifest "pcarranza/meeseeks-box-amd64" -> to be pushed to "pcarranza/meeseeks-box" as a manifest reference 
DEBU[0004] endpoints: [{false https://registry-1.docker.io v2 false true 0xc4204d6300} {false http://registry-1.docker.io v2 false true 0xc4204d6300}] 
DEBU[0004] Trying to fetch image manifest of registry-1.docker.io/pcarranza/meeseeks-box-armv6 repository from https://registry-1.docker.io v2 
INFO[0008] Image "registry-1.docker.io/pcarranza/meeseeks-box-armv6:0.0.29" is digest sha256:2cbd147dcb1b14a7dc466d95d7177e4f472158ec0f2b3133c652b3e22c3e8b93; size: 1156 
DEBU[0008] Adding manifest references of "registry-1.docker.io/pcarranza/meeseeks-box-armv6:0.0.29" to blob mount requests 
DEBU[0008] Adding manifest "pcarranza/meeseeks-box-armv6" -> to be pushed to "pcarranza/meeseeks-box" as a manifest reference 
DEBU[0008] Manifest list push url: https://registry-1.docker.io/v2/pcarranza/meeseeks-box/manifests/0.0.29 
DEBU[0008] mediaType of manifestList: application/vnd.docker.distribution.manifest.list.v2+json 
DEBU[0010] Mount of blob sha256:5de6b84a59f3678d3c07f3394018c17d3427fb574adc03dfc417c33c2ef70032 succeeded, location: "https://registry-1.docker.io/v2/pcarranza/meeseeks-box/blobs/sha256:5de6b84a59f3678d3c07f3394018c17d3427fb574adc03dfc417c33c2ef70032" 
DEBU[0011] Mount of blob sha256:2fdfe1cd78c20d05774f0919be19bc1a3e4729bce219968e4188e7e0f1af679d succeeded, location: "https://registry-1.docker.io/v2/pcarranza/meeseeks-box/blobs/sha256:2fdfe1cd78c20d05774f0919be19bc1a3e4729bce219968e4188e7e0f1af679d" 
DEBU[0013] Mount of blob sha256:4370b4ef3a9578048aaa2793661df26b22d8c8ef9a3d5cbd9a0dd753019fe34c succeeded, location: "https://registry-1.docker.io/v2/pcarranza/meeseeks-box/blobs/sha256:4370b4ef3a9578048aaa2793661df26b22d8c8ef9a3d5cbd9a0dd753019fe34c" 
DEBU[0014] Mount of blob sha256:14d189e6e0a680012d01c912f9449e0c43cae331bdb878db5540059ef9425a4e succeeded, location: "https://registry-1.docker.io/v2/pcarranza/meeseeks-box/blobs/sha256:14d189e6e0a680012d01c912f9449e0c43cae331bdb878db5540059ef9425a4e" 
DEBU[0016] Mount of blob sha256:066d41019cc04946f852ba1daea73d530363f3bf48d0f9c45cdd45e73a0f1a32 succeeded, location: "https://registry-1.docker.io/v2/pcarranza/meeseeks-box/blobs/sha256:066d41019cc04946f852ba1daea73d530363f3bf48d0f9c45cdd45e73a0f1a32" 
DEBU[0017] Mount of blob sha256:95d54dd4bdadebb53f9b91b25aa7dc5fcb83c534eb1d196eb0814aa1e16f3db2 succeeded, location: "https://registry-1.docker.io/v2/pcarranza/meeseeks-box/blobs/sha256:95d54dd4bdadebb53f9b91b25aa7dc5fcb83c534eb1d196eb0814aa1e16f3db2" 
DEBU[0019] Mount of blob sha256:72bf7d76c39215a547858ef9260990b9b80c0e679bb2f6ceef942d7b6d0eeec3 succeeded, location: "https://registry-1.docker.io/v2/pcarranza/meeseeks-box/blobs/sha256:72bf7d76c39215a547858ef9260990b9b80c0e679bb2f6ceef942d7b6d0eeec3" 
DEBU[0020] Mount of blob sha256:a815555732e0aa0486fdd67382994c04f305fe03d498c8cf8c690efc266a89e9 succeeded, location: "https://registry-1.docker.io/v2/pcarranza/meeseeks-box/blobs/sha256:a815555732e0aa0486fdd67382994c04f305fe03d498c8cf8c690efc266a89e9" 
DEBU[0021] Mount of blob sha256:a432f56de40b189e6f8b75fdd7aa0ff9566107b999318c9388340271760932fd succeeded, location: "https://registry-1.docker.io/v2/pcarranza/meeseeks-box/blobs/sha256:a432f56de40b189e6f8b75fdd7aa0ff9566107b999318c9388340271760932fd" 
DEBU[0021] manifest reference push URL: https://registry-1.docker.io/v2/pcarranza/meeseeks-box/manifests/sha256:1a33cbe2521b6854654fa15b6fb12567d876fe03978a51f2a949c5ef915dcfd3 
DEBU[0023] referenced manifest "pcarranza/meeseeks-box-amd64" pushed; digest matches: sha256:1a33cbe2521b6854654fa15b6fb12567d876fe03978a51f2a949c5ef915dcfd3 
DEBU[0023] manifest reference push URL: https://registry-1.docker.io/v2/pcarranza/meeseeks-box/manifests/sha256:2cbd147dcb1b14a7dc466d95d7177e4f472158ec0f2b3133c652b3e22c3e8b93 
DEBU[0024] referenced manifest "pcarranza/meeseeks-box-armv6" pushed; digest matches: sha256:2cbd147dcb1b14a7dc466d95d7177e4f472158ec0f2b3133c652b3e22c3e8b93 
Digest: sha256:19fbb669011535e4c95bff5f87c31a6cf69d507e03afad00f8990d8c88fddf8e 769
macbook meeseeks-box-manifest$ manifest-tool-darwin-amd64 inspect registry-1.docker.io/pcarranza/meeseeks-box:0.0.29                                      
Name:   registry-1.docker.io/pcarranza/meeseeks-box:0.0.29 (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:19fbb669011535e4c95bff5f87c31a6cf69d507e03afad00f8990d8c88fddf8e
 * Contains 2 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: sha256:1a33cbe2521b6854654fa15b6fb12567d876fe03978a51f2a949c5ef915dcfd3
1  Mfst Length: 949
1     Platform:
1           -      OS: linux
1           - OS Vers: 
1           - OS Feat: []
1           -    Arch: amd64
1           - Variant: 
1           - Feature: 
1     # Layers: 3
         layer 1: digest = sha256:2fdfe1cd78c20d05774f0919be19bc1a3e4729bce219968e4188e7e0f1af679d
         layer 2: digest = sha256:4370b4ef3a9578048aaa2793661df26b22d8c8ef9a3d5cbd9a0dd753019fe34c
         layer 3: digest = sha256:14d189e6e0a680012d01c912f9449e0c43cae331bdb878db5540059ef9425a4e

2    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
2       Digest: sha256:2cbd147dcb1b14a7dc466d95d7177e4f472158ec0f2b3133c652b3e22c3e8b93
2  Mfst Length: 1156
2     Platform:
2           -      OS: linux
2           - OS Vers: 
2           - OS Feat: []
2           -    Arch: arm
2           - Variant: v6
2           - Feature: 
2     # Layers: 4
         layer 1: digest = sha256:95d54dd4bdadebb53f9b91b25aa7dc5fcb83c534eb1d196eb0814aa1e16f3db2
         layer 2: digest = sha256:72bf7d76c39215a547858ef9260990b9b80c0e679bb2f6ceef942d7b6d0eeec3
         layer 3: digest = sha256:a815555732e0aa0486fdd67382994c04f305fe03d498c8cf8c690efc266a89e9
         layer 4: digest = sha256:a432f56de40b189e6f8b75fdd7aa0ff9566107b999318c9388340271760932fd
```

This means that it's relatively easy to build a manifest and push the multi-arch docker image.

I'll do some testing without using a manifest and only use the command line.

A thing to consider, the manifest tool changes name when running on OSX or Linux, and, OSX requires to set the `--username` and `--password` flags (not on Linux), so maybe it just makes sense to set it all in the environment and make it a requirement for any platform.

**Comment by pcarranza** [comment]
Nop, we can't use `from-args` because https://github.com/estesp/manifest-tool/blob/4ec9baa80b47f791ca442c1d63e5eac310761fe3/push.go#L99

I can't declare the variant for ARM builds, which makes it a deal breaker.

We will need to build a yaml file with the images we have, and then call the manifest-tool.

This means we will need to add a configuration block in which we declare the image that will be multi architecture.

Does this sound like a reasonable approach @caarlos0 ?

**Comment by caarlos0** [comment]
I'm not sure.

I actually not even sure if I want to depend on one more thing (manifest tool in this case).

**Comment by pcarranza** [comment]
would it make sense to bring in the tool code as a dependency instead, then?

**Comment by caarlos0** [comment]
> would it make sense to bring in the tool code as a dependency instead, then?

dunno, can't we do it with plain docker?

**Comment by pcarranza** [comment]
not really, it's not docker itself but the registry http API: https://github.com/estesp/manifest-tool/blob/master/docker/createml.go

that would be the code to use, but I'm not sure how much sense does it make to just pull the whole file in our just use it as a dependency.

**Comment by caarlos0** [comment]
yeah, me neither.... maybe we can wait to see if more people need this?

maybe they add this to the default docker cli at some time, and then things would be easier to implement (and we will depend on less things)...

what do you say?

**Comment by ewoutp** [comment]
Would love to have this feature. Supporting multi-arch images for amd64, arm, arm64 in 1 pass would be great

**Comment by caarlos0** [comment]
> What if we meet in the middle and we allow goreleaser to output the manifest file used to build those multiarch repositories? it would not mean having a dependency and could be used quite easily in any CI/CD pipeline, then we can talk to the docker people to see if the client plans to include any of this, in any case, we will still need the manifest, independently of the tool being docker-cli or the manifest-tool.

i like this idea!

**Comment by pcarranza** [comment]
@caarlos0 👍 , I'll take a look at it later to see how to do it and send a PR along the way.

**Comment by ernoaapa** [comment]
Hi, I'm building multi arch images at the moment but doing it "manually" (building images with goreleaser and then using manifest-tool to push the manifest. Having that part of goreleaser would be awesome!

In the edge version of Docker there's `docker manifest` command, so it's coming up and soon you don't need the `manifest-tool` anymore https://docs.docker.com/edge/engine/reference/commandline/manifest/

**Comment by caarlos0** [comment]
docker 18 already have the `manifest` command :D

**Comment by 1138-4EB** [comment]
Is this already embedded into goreleaser or should be follow the two step approach yet?

**Comment by pcarranza** [comment]
Oh, I've been quite busy myself lately.

I think this should be part of goreleaser itself. It's just one more command already embedded in docker in the end.

**Comment by 1138-4EB** [comment]
I thought that I had already linked this issue with goreleaser/goreleaser#707. Just doing it now because I think that the single missing enhancement there can affect the implementation of this.

Although I'm quite busy too, @pcarranza please do not hesitate to ask for help evaluating/testing any enhancements to this.

**Comment by caarlos0** [comment]
yeah, I think I'll work on that issue maybe today...

**Comment by caarlos0** [comment]
> yeah, I think I'll work on that issue maybe today...

clearly I didn't :(

**Comment by caarlos0** [comment]
I want to finish this before its next anniversary, after experimenting a lot, my idea is to add another config like the following:

```dockerfile
ARG ARCH
FROM ${ARG}/alpine
COPY binary /usr/bin/binary
ENTRYPOINT ["/usr/bin/binary"]
```

```yaml
dockers:
- name_templates: ["foo/bar:{{ .Version }}-amd64"]
  binaries: ["binary"]
- name_templates: ["foo/bar:{{ .Version }}-arm64"]
  binaries: ["binary"]
  goarch: arm64
  build_flag_templates: ["--build-arg=ARCH=arm64v8"]

docker_manifests:
- name_template: foo/bar:{{ .Version }} # TODO: should this be a list? 🤔
  image_name_templates:
  - foo/bar:{{ .Version }}-amd64
  - foo/bar:{{ .Version }}-arm64v8
  skip_push: false
```

This would build and push the images as today (needed to create the manifest anyway), and the new `Docker Manifest` pipe would:

- create the manifest: `docker manifest create` 
- publish the manifest: `docker manifest push`

And then release notes would probably use the manifest names instead of the image names.

## Problems with this approach

Code might get a bit repetitive, but I think its safer for now as it makes things more explicit... otherwise, would have to:

- translate goarch into docker arch (might be easy enough)
- guess which `image_name_templates` goes to which `manifest_name_templates`... and... how?

This way is more verbose, but seems more flexible...

Thoughts?
