### ISSUE TITLE
announce/webhook: Configurable allowed HTTP status codes

### ISSUE THREAD

**Issue by mattrobenolt** [goreleaser/goreleaser#5316]
### Is your feature request related to a problem? Please describe.

I am attempting to use the announce/webhook feature to poke at pkg.go.dev to update it's cache. I did this via `curl -XPOST https://pkg.go.dev/fetch/{mod}@{tag}` before after goreleaser step, but figured this built in step was a bit nicer.

The issue is `pkg.go.dev` returns a `408` status code often with a response such as:

```
< HTTP/2 408
< content-security-policy: object-src 'none'; base-uri 'none'; script-src 'unsafe-inline' 'strict-dynamic' https: http: 'sha256-DVdvl49HC0iGx/YKQq/kVNATnEdzGfExbJVTHqT95l8=' 'sha256-CoGrkqEM1Kjjf5b1bpcnDLl8ZZLAsVX+BoAzZ5+AOmc=' 'sha256-QqhlxKosyquihHG/Jahbski3BB1pDss2/CDgLzKKbmE=' 'sha256-karKh1IrXOF1g+uoSxK+k9BuciCwYY/ytGuQVUiRzcM=' 'sha256-mxm3e8M0u3nPPBmLIBgGuMvGUIL5LGv+HzV3bLAIBgw=' 'sha256-+iS8jRq15Ez/Kzz0/G+SNc0geLNvTyf2NZC7MyJgpRE=' 'sha256-UiVwSVJIK9udADqG5GZe+nRUXWK9wEot2vrxL4D2pQs=' 'sha256-cB+y/oSfWGFf7lHk8KX+ZX2CZQz/dPamIICuPvHcB6w=' 'sha256-7mi5SPcD1cogj2+ju8J/+/qJG99F6Qo+3pO4xQkRf6Q=' 'sha256-rEbn/zvLCsDDvDrVWQuUkKGEQsjQjFvIvJK4NVIMqZ4='
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< x-frame-options: deny
< x-cloud-trace-context: 68447a849da28bf09ac85c76e577c5b7
< date: Thu, 28 Nov 2024 17:13:45 GMT
< server: Google Frontend
< content-length: 103
< via: 1.1 google
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
<
We're still working on “github.com/mattrobenolt/ps-http-sim@v0.0.11”. Check back in a few minutes!
```

I don't think it's particularly suitable or goreleaser's job to know or understand that a 408 is valid, but having a configurable list of acceptable codes rather than the hardcoded list would enable me to say "yes, a 408 is fine."

### Describe the solution you'd like

Add configuration into announce/webhook for allowed http status codes to consider for success.

### Describe alternatives you've considered

Using `curl` instead.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I am willing to author a PR.

**Comment by caarlos0** [comment]
thanks for the issue and PR <3
