### ISSUE TITLE
Ability to skip build sections

### ISSUE THREAD

**Issue by jaxxstorm** [goreleaser/goreleaser#534]
Currently with goreleaser, I have a configuration file which uses fpm and rpmbuild which is a pain to use on OS X.

It'd be nice if I could do something like `goreleaser --snapshot --skip-publish --rm-dist --no-fpm` which would do everything EXCEPT the rpm portion

**Comment by caarlos0** [comment]
so, basically, skip entire sections? 

I'll think about it.

Anyway, the idea is to re-implement the fpm pipe without using fpm - yeah, native go impl.

Unfortunately, probably rpmbuild will still be required, but I don't find it to be a pain to use in macos, I just `brew install rpmbuild` and it works as expected... can you clarify what problems you are experiencing?

thankss

**Comment by caarlos0** [comment]
may ref to #543

**Comment by caarlos0** [comment]
if the problem was fpm, it is been replaced by nfpm, which will not had those issues hopefully.

closing due to lack of further info.
