### ISSUE TITLE
`on_intel` or `on_arm` cannot include `url`

### ISSUE THREAD

**Issue by 5ouma** [goreleaser/goreleaser#5347]
### What happened?

Since #4822, `on_intel` and `on_arm` are used instead of `if Hardware::CPU.intel?` and `if Hardware::CPU.arm?`.
However, they can't include the `url` property.

### How can we reproduce this?

See https://github.com/5ouma/homebrew-formula/pull/32/files

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    2.4.8
GitCommit:     377981ebd76e1bbb0dbe07d5428239ec8c5381a8
GitTreeState:  clean
BuildDate:     2024-11-22T12:56:52
BuiltBy:       homebrew
GoVersion:     go1.23.3
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I ran on GitHub Actions.

Error:
```
FormulaAudit/ComponentsOrder: `on_intel` cannot include `url`. Only `livecheck`, `keg_only`, `disable!`, `deprecate!`, `depends_on`, `conflicts_with`, `fails_with`, `resource`, `patch`, `on_intel`, `on_arm`, `on_macos`, `on_linux`, `on_system`, `on_sequoia`, `on_sonoma`, `on_ventura`, `on_monterey`, `on_big_sur`, `on_catalina`, `on_mojave`, `on_high_sierra`, `on_sierra` and `on_el_capitan` are allowed.
```

**Comment by caarlos0** [comment]
that's weird, as it seems to be working? 

anyway, should be ok to revert that change
