### ISSUE TITLE
Support for reading GitHub token from a file

### ISSUE THREAD

**Issue by elyscape** [goreleaser/goreleaser#535]
Creating a GitHub release currently requires the `GITHUB_TOKEN` environment variable to be set. This is great for CI environments, but less so on a development machine; it means that I either need to set `GITHUB_TOKEN` in my shell profile, in which case it's trivially exposed to every process I run, or use some external system like [direnv] to load it on-demand. By contrast, GitHub's hub tool [stores the OAuth token in `~/.config/hub`][hub], which is a YAML file with mode `0600`. It would be nice if GoReleaser supported something similar.

[direnv]: https://github.com/direnv/direnv
[hub]: https://hub.github.com/hub.1.html#GitHub-OAuth-authentication

**Comment by caarlos0** [comment]
I think this is a valid feature!

Thanks for the suggestion!

**Comment by caarlos0** [comment]
@elyscape can I have your thoughts on #539?
