### ISSUE TITLE
Add `repositories` key to `kos` configuration

### ISSUE THREAD

**Issue by tstirrat15** [goreleaser/goreleaser#5351]
### Is your feature request related to a problem? Please describe.

I've got a project I want to use `kos` on, and the project needs to publish to three different docker repositories. This shouldn't require building the image three times.

### Describe the solution you'd like

It'd be nice if there was a `repositories` key on `kos` rather than a `repository` and let it be a list.

### Describe alternatives you've considered

In the meantime I can work around just by duplicating the `kos` configuration.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
yes, that makes sense. I'm not sure if Ko supports it, though, but I'm gonna check.

**Comment by caarlos0** [comment]
seems like its indeed not supported.[^1]

but, we can use [crane.Copy](https://github.com/google/go-containerregistry/blob/6bce25ecf0297c1aa9072bc665b5cf58d53e1c54/pkg/crane/copy.go#L30) to do it. It's already a dependency anyway, so it should be fine, I think.


[^1]: https://github.com/ko-build/ko/issues/1423

**Comment by caarlos0** [comment]
https://github.com/goreleaser/goreleaser/pull/5353
