### ISSUE TITLE
ERROR: invalid tag ... repository name must be lowercase

### ISSUE THREAD

**Issue by kuritka** [goreleaser/goreleaser#5365]
### What happened?

Me orgname is camelcase and latest goreleaser started reporting an error about uppercase. It didn't return this error before.

```shell
  ⨯ release failed after 1m25s               error=docker build failed: failed to build ghcr.io/AbsaOSS/external-dns-infoblox-webhook:latest-amd64: exit status 1: ERROR: invalid tag "ghcr.io/AbsaOSS/external-dns-infoblox-webhook:latest-amd64": repository name must be lowercase
```

### How can we reproduce this?

See my pipeline: https://github.com/AbsaOSS/external-dns-infoblox-webhook/actions/runs/12294943844/job/34311229219#step:9:1667

### goreleaser version

```bash
version: latest, goreleaser-action @v6
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
that error is coming from docker, not goreleaser...

I believe you'll need to set the repo name to lowercase...
