### ISSUE TITLE
Build package for loongson[loong64]

### ISSUE THREAD

**Issue by Evsio0n** [goreleaser/goreleaser#5374]
## Hello!

Loong64 is the 64-bit version of LoongArch. It's a RISC-style ISA developed by [Loongson](https://www.loongson.cn/). 
The architecture can be found here (https://wiki.debian.org/Ports/loong64)

Pre-built packages can resolve goreleaser upstream issues when using releases as downloads for the latest architecture.

### Describe the solution you'd like

add `loong64` to .gorelease.yml

### Describe alternatives you've considered

I can use `go install` to install manually, but for upstream code, adaptation may be required

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
now sure how common loong64 is, and given that we are already running out of space on the builders, I rather not add this.

also, to clarify, goreleaser don't require any changes to allow their users to build their projects to loong64.

thanks for the suggestion though.
