### ISSUE TITLE
Add a flag to override Github release artefacts

### ISSUE THREAD

**Issue by basgys** [goreleaser/goreleaser#557]
Using `goreleaser --skip-validate` allows to have rolling releases and publish a new binary or docker container under the last tag version. However, when `goreleaser` attempts to publish the artefacts on Github, it throws this error:

```
⨯ release failed after 49.31s error=POST https://uploads.github.com/repos/foo/bar/releases/9691476/assets?name=bar_0.0.0_checksums.txt: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
```

Whether it is a good idea or not to override an existing release is debatable, but for people who have rolling releases it would be really useful. Or perhaps there would be a better idea? Maybe releasing an artefact with `--snapshot` called `latest`, `snapshot`, `nightly-build`, ...

**Comment by caarlos0** [comment]
I think that in this case `skip-validate` behavior is wrong, actually. 

It should not be possible to override the release artifacts, that's the whole point of having a tag and all that.

I'll look into this later today.

/remind me check this issue in 8 hours

**Comment by basgys** [comment]
@caarlos0 I agree, I also prefer releases to remain unchanged. Moreover, I think the name `skip-validate` does not reveal correctly the intention behind the command. 

So maybe to put it differently, I would love to see two separate flows on goreleaser. One for tagged releases and another one for nightly builds/snapshots. 

I am not sure whether this feature is out of the goreleaser scope though.

**Comment by caarlos0** [comment]
> So maybe to put it differently, I would love to see two separate flows on goreleaser. One for tagged releases and another one for nightly builds/snapshots.

yes, I agree, this is rather confusing right now...

there is --skip-validate, --skip-publish and --snapshot, we should probably improve all thatx

**Comment by caarlos0** [comment]
/remind me this issue in 26 hours

no time for this today :/

**Comment by caarlos0** [comment]
check #575

**Comment by caarlos0** [comment]
snapshot now replaces --skip-validation and --skip-publish, so there is no way of doing the "skip validation and publish" thing anymore (it should never have been possible to do that to be honest).

closing!

**Comment by requilence** [comment]
@caarlos0 We are using CircleCI with goreleaser, and sometimes it has network problems when uploading artefacts to Github. So goreleaser uploaded only part of files and exits, [here is an example](https://circleci.com/gh/cloudradar-monitoring/cagent/189)
Then I can't use the **Rerun** button in the CIrcleCI, because of gorelease returns  `already_exist`

I understand that it is a bad practice to overwrite the release's files, but in case of CI, it will be useful to **SKIP** already exists files
