### ISSUE TITLE
Changelog output has git colorizing control characters

### ISSUE THREAD

**Issue by pmichali** [goreleaser/goreleaser#571]
### Prerequisites

* [ ] Are you running the latest version? Yes
* [ ] Did you perform a search to see if this problem was already reported? No, but looked through all of docs.

For more information, see the `CONTRIBUTING` guide.

### Description

When pushing up a release, goreleaser is including the "git log" info for the changelog info. By default, git has colorizing on, and this is seen in the changelog as control characters.

Can work-around the issue, by turning off all coloring for git (.git/config):
```
[color]
    log = false
    ui = false
    branch = false
    diff = false
    interactive = false
    status = false
```

### Environment

Please paste the output of:

* `go version` 1.9.2
* `uname -a` Linux bxb-c2-77 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* `goreleaser --debug`  N/A as release process works as expected.

### Steps to Reproduce

* Have several commits for a release.
* Do the release generation
* Look at the changelog

**Expected behavior:** [What you expected to happen]
 Change log like this:
```
4b2ec19 Fixing route add/delete syntax for pod network, where wrong interface name was used
```
 and not have to alter git configuration to disable coloring.

**Actual behavior:** [What actually happened]
```
�[33m3eed9fc�[m Trying to get release to work
�[33m9f14b02�[m Trying sign option
�[33mb0842ca�[m Preparing for release and setting version to 1.0.0
```

**Comment by caarlos0** [comment]
fixed on latest, thanks!
