### ISSUE TITLE
Support short Git commit hashes

### ISSUE THREAD

**Issue by dnaka91** [goreleaser/goreleaser#578]
### Describe the feature and how you think it should work.

Currently the full length commit hash is used everywhere. For file names (if `--snapshot` is used) as well as during the build process for later use at runtime.

In general the short hash is enough to identify a commit and thus a user should be able to configure to optionally use the short commit hash instead:
```yaml
git:
  short_hash: true
```

I already prepared the changes in my fork for personal use cases and can open a pull request if this feature request becomes accepted.

**Comment by caarlos0** [comment]
Hi,

that's great, feel free to open the PR :)

**Comment by caarlos0** [comment]
closed on #581
