### ISSUE TITLE
Readd the skip-publish flag

### ISSUE THREAD

**Issue by jaxxstorm** [goreleaser/goreleaser#582]
I use goreleaser extensively for internal builds. Because a lot of our internal tools aren't features in goreleaser, I generally use the following workflow:

- Tag a releaser
- Use the `--skip-publish` flag to build artifacts
- Use a different git pipeline to upload those artifacts to different repos etc.

It seems in fdc032ec153c992aeea9be349da4c64579fbfae7 this was removed. I understand the reason behind this change, because in theory snapshots should be enough, but if I'm actually releasing a tagged build, I'd rather not use the snapshot feature.

Would there be any consideration to adding this option back?

**Comment by caarlos0** [comment]
hmm, I haven't think about that before, and I think this makes sense...

will add it back, yes.

**Comment by caarlos0** [comment]
v0.58.0 will have this feat back :)
