### ISSUE TITLE
`go get github.com/goreleaser/goreleaser` fails

### ISSUE THREAD

**Issue by cwpearson** [goreleaser/goreleaser#585]
### Prerequisites

* [ ] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

`go get github.com/goreleaser/goreleaser` fails with `unknown field 'Format' in tar.Header`

### Environment

Please paste the output of:

* `go version`

    go version go1.9.1 linux/amd64

* `uname -a`

    Linux aleph 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* `goreleaser --debug`

### Steps to Reproduce

1. run `go get github.com/goreleaser/goreleaser`

**Expected behavior:** [What you expected to happen]

goreleaser is installed

**Actual behavior:** [What actually happened]

~~~
# github.com/goreleaser/nfpm/deb
../../goreleaser/nfpm/deb/deb.go:132:9: unknown field 'Format' in struct literal of type tar.Header
../../goreleaser/nfpm/deb/deb.go:191:9: unknown field 'Format' in struct literal of type tar.Header
../../goreleaser/nfpm/deb/deb.go:215:10: unknown field 'Format' in struct literal of type tar.Header
~~~

**Comment by caarlos0** [comment]
Hi @cwpearson !

So, if you intend to run goreleaser, you should probably use a pre-compile binary.

GoReleaser now compiles only with go 1.10+ (and contributing.md is also wrong, will fix that).

On the other hand, I see now that the docs are misleading in this sense, will have that fixed.

**Comment by cwpearson** [comment]
Thank you, this was very helpful! I will change our use of goreleaser to use a pre-compiled binary.

**Comment by caarlos0** [comment]
No problem, sorry for the misleading docs :P
