### ISSUE TITLE
Bug: Zip archive is flat; has no directory structure.

### ISSUE THREAD

**Issue by jhillyerd** [goreleaser/goreleaser#586]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?

### Description

https://github.com/goreleaser/goreleaser/releases/download/v0.57.1/goreleaser
_Linux_x86_64.tar.gz (current for `https://git.io/goreleaser | bash`) is building flat Zip archives.  This appears to be a regression, and changes depending on how I install goreleaser.

### Environment

Please paste the output of:

* go version go1.9.3 linux/amd64 (and 1.9.4 on travis-ci.org)
* Linux cubi 4.14.0-3-amd64 #1 SMP Debian 4.14.17-1 (2018-02-14) x86_64 GNU/Linux
* The --debug output is very very long due to javascript dependencies, but I can attach if absolutely necessary.

Config: https://github.com/jhillyerd/inbucket/blob/v1.3.0/.goreleaser.yml

### Steps to Reproduce

1.  git clone https://github.com/jhillyerd/inbucket
2.  cd inbucket
3.  goreleaser --snapshot

**Expected behavior:**

inbucket_SNAPSHOT-f58e51d9218cabe7c389d98d8f0a37d57939734a_windows_amd64.zip contains top-level directories: etc, themes (and many subdirs)

**Actual behavior:**

All 600+ files are in the root of the Zip archive.

When I install via `go get github.com/goreleaser/goreleaser`, this does not happen.  But my travis build is using the `|bash` setup.

**Comment by caarlos0** [comment]
thanks for reporting this.

that's weird though, as this wasn't changed in a while...

will take a look into it anyway!

**Comment by jhillyerd** [comment]
Thanks.  I see your binaries are `Built with go version go1.10 linux/amd64` - maybe it has a bug.  I'll try go get with 1.1.0 when I have a few minutes.

**Comment by caarlos0** [comment]
After taking a look, I think this never worked actually...

definitely a bug  👍

**Comment by caarlos0** [comment]
I think that moving the archiving thing to another project was a bad idea, and it is a bad abstraction actually.

will move it back to make this easier to fix

**Comment by caarlos0** [comment]
Fix is on the way :)

**Comment by caarlos0** [comment]
v0.57.2 is being released with the fix!

hope it works out now and sorry for the trouble!

**Comment by jhillyerd** [comment]
Thanks for the quick turn around.  I tried it at home and travis-ci, both worked great.
