### ISSUE TITLE
Goreleaser + Docker builder + Snapshots + no tag == :sadpanda:

### ISSUE THREAD

**Issue by flyinprogrammer** [goreleaser/goreleaser#589]
As an application developer
I want to build snapshots (and Docker containers) of new applications that have no tags
So that I can have CI working, with possible integration tests, before I cut my first release.

---

In actuality this doesn't work at the moment because the code that makes Docker tags crashes when it can't use git to obtain tag information.

```
   • CREATING DOCKER IMAGES
   ⨯ release failed after 16.05s error=failed to execute tag template '{{ .Tag }}': Invalid Semantic Version
```

The same thing happens with the semver tags we offer folks.

IMO if a tag cannot be found we should assume a default version of `0.0.0`, but that's just me. If you agree with this @caarlos0 I want to also make this a default in [svu](https://github.com/caarlos0/svu) as well.

Just wanted to get some feedback before doing the PR(s).

**Comment by caarlos0** [comment]
Hi @flyinprogrammer 

Yes, this is an issue, I believe #580 fixes this!

I just need to do some more testing before merging it in.

svu is another project, PRs accepted of course, but goreleaser does not use it internally...

**Comment by flyinprogrammer** [comment]
ah - you're two steps ahead of me. I'll close this issue as the work should just be tracked in #580. And I'll submit a PR to svu once I see what you decided on in that PR.

**Comment by caarlos0** [comment]
should be fixed on latest :)
