### ISSUE TITLE
goreleaser init produces an empty file

### ISSUE THREAD

**Issue by elyscape** [goreleaser/goreleaser#591]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?

### Description

Since #577 was merged, `goreleaser init` produces an empty `.goreleaser.yml` file.

### Environment

Please paste the output of:

* `go version`
```
go version go1.10 darwin/amd64
```
* `uname -a`
```
Darwin WF001331.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```
* ~`goreleaser --debug`~ (not relevant)

### Steps to Reproduce

1.  Run `goreleaser init`.
2.  Look at `.goreleaser.yml`.
3.  There isn't really a third step.

**Expected behavior:**
The contents of `example.goreleaser.yml` should be in the generated `.goreleaser.yml`.

**Old behavior:**
```shellsession
oops:az-dns elyscape$ rm .goreleaser.yml
oops:az-dns elyscape$ ./goreleaser -v

goreleaser version 0.55.1, commit 3fb18f6408cd34ff17ee203db6829f5d33ba0520, built at 2018-02-25T21:02:43Z

oops:az-dns elyscape$ ./goreleaser init

   • SETTING DEFAULTS FOR:
      • loading environment variables
      • snapshoting              
      • releasing to GitHub      
      • creating archives        
      • building binaries        
      • creating Linux packages with fpm
      • creating Linux packages with nfpm
      • creating Linux packages with snapcraft
      • calculating checksums    
      • signing artifacts        
      • creating Docker images   
      • releasing to Artifactory 
      • creating homebrew formula
      • creating Scoop Manifest  
   • config created; please edit accordingly to your needs file=.goreleaser.yml

oops:az-dns elyscape$ ls -l .goreleaser.yml
-rw-r--r--  1 eliyoung  staff  1636 Mar  1 16:16 .goreleaser.yml
```

**Actual behavior:**
```shellsession
oops:az-dns elyscape$ rm .goreleaser.yml 
oops:az-dns elyscape$ goreleaser -v

goreleaser version 0.58.1, commit ac7800699fd9ab2fd3b2e947cc8eef223b524451, built at 2018-03-01T23:53:33Z

oops:az-dns elyscape$ goreleaser init

   • Generating .goreleaser.yml file
   • config created; please edit accordingly to your needs file=.goreleaser.yml

oops:az-dns elyscape$ ls -l .goreleaser.yml
-rw-r--r--  1 eliyoung  staff  0 Mar  1 16:16 .goreleaser.yml
```

**Comment by elyscape** [comment]
I should note that I have `goreleaser` installed using Homebrew. As a side note, it seems to me that relying on packr would result in the `main-packr.go` file not being built when installed via `go get`, which is probably suboptimal.

**Comment by caarlos0** [comment]
hey @elyscape 

thanks for reporting this.

the empty init is indeed a bug.

as per the go get, you should probably use the pre-compiled binary to release your projects... if you want to hack on goreleaser, then the contributing.md covers the needed steps :) 

pushing the fix right now :)

**Comment by elyscape** [comment]
That didn't fix it, unfortunately. Most likely on your system packr is defaulting to development mode and pulling the file from your GOPATH.

**Comment by caarlos0** [comment]
yeah, weird. The release was actually generated on travis. It works on my machine (tm) .

Will have anther look

**Comment by caarlos0** [comment]
fuck this, it's just one file, gonna inline it.

**Comment by caarlos0** [comment]
fixed
