### ISSUE TITLE
Scoop download link misses "v" from the version-folder

### ISSUE THREAD

**Issue by gexclaude** [goreleaser/goreleaser#593]
### Prerequisites

* [x] Are you running the latest version? - v0.59.0
* [x] Did you perform a search to see if this problem was already reported?

### Description

I published version v0.2.5, it got tagged and released and scoop manifesto published.
The only thing that is not correct is the download link

(0.2.5 -> v0.2.5)

### Environment

go version go1.9.2 darwin/amd64
Darwin xyz-MBP-5.fritz.box 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

### Steps to Reproduce

perform release

**Expected behavior:** 

https://github.com/gexclaude/scoop-bucket/commit/1bbfbc5f498a6d1e64995256ee95da013610d6d1#diff-93d13d81bb29c2d7d7733c7126b0ec31
points to https://github.com/gexclaude/aaregurucli/releases/download/0.2.5/aareguru_0.2.5_windows_amd64.zip

**Actual behavior:** 

but should point to
https://github.com/gexclaude/aaregurucli/releases/download/v0.2.5/aareguru_0.2.5_windows_amd64.zip

**Comment by gexclaude** [comment]
updated link to json file to a specific commit, as I fixed the link manually

**Comment by caarlos0** [comment]
thanks for reporting this!

**Comment by gexclaude** [comment]
Thank you - will re-test it soon :+1:
