### ISSUE TITLE
Custom name for brew tap

### ISSUE THREAD

**Issue by ernoaapa** [goreleaser/goreleaser#595]
It would be nice if you could give custom name for the generated brew tap `.rb` file.

By default `goreleaser` [uses project name](https://github.com/goreleaser/goreleaser/blob/master/pipeline/brew/brew.go#L115) as the brew tab name.
But for example in my project [eliot](https://github.com/ernoaapa/eliot) I would like to name it as `eli`.
As an example, now user needs to `brew install ernoaapa/eliot/eliot` but I would like to use brew install `ernoaapa/eliot/eli`.

I can create a PR of this.

**Comment by caarlos0** [comment]
seems like a nice feature to have... I'll be glad to accept a PR =D

**Comment by caarlos0** [comment]
will release next asap

**Comment by caarlos0** [comment]
releasing v0.60.0
