### ISSUE TITLE
Feedback on the UX and the remove of --skip-validate

### ISSUE THREAD

**Issue by andreynering** [goreleaser/goreleaser#599]
Hello,

First, thanks for GoReleaser, it's a true useful and time saver tool. 😄 

Something I find a bit frustrating and counter-intuitive about it is that it refuses to publish when Git is in a dirty state or the current commit is not exactly that tagged one. This sometimes get in my way:

- I want to release;
- I create a Git tag and push it;
- I call `goreleaser`;
- Some error happen like, say, `rpmbuild` not installed;
- I think "Oh, let's release without RPM for today, I'll fix that tomorrow";
- I comment the RPM line on `.goreleaser`;
- Then I can't release because Git is in a dirty state. Also, not nice to delete and recreate a tag with a temporarely change.

`--skip-validate` is now gone. `--snapshot` is useful for testing the release process locally, but in a situation like I have to upload the files manually. Also, the Go build tag is then not `v1.2.3`, but something like `SNAPSHOT-<checksum>`.

So, I miss a way to force the release when, as example, I can't generate DEB or RPM or other technical reason. Maybe add option to skip RPM when it's not available?

**Comment by caarlos0** [comment]
Hi, thanks @andreynering !

So, the problem with allowing a release that doesn't match the tag is that the end user of your app can't know for sure if the code represented by that is what the binaries are... not sure how much of a problem this is nor if its goreleaser responsibility to care about it.

Anyway, more people asked `--skip-validate` back, so I guess I'll just re-add it...

**Comment by andreynering** [comment]
You're fast! Thank you!
