### ISSUE TITLE
Homebrew formular pushed an empty file

### ISSUE THREAD

**Issue by jaxxstorm** [goreleaser/goreleaser#601]
### Prerequisites

Using latest version, can't see this reported

### Description

The last pushed version of a tool I own seems to have pushed a homebrew formula with an empty filename:

https://travis-ci.org/jaxxstorm/hookpick/builds/350987265

When using an older version of goreleaser, this didn't happen

### Environment

Adding the `--debug` flag isn't easy due to using the bash script, I can try if it's hard to track down

**Comment by caarlos0** [comment]
in fact, goreleaser itself was realeased with a wrong filename https://github.com/goreleaser/homebrew-tap/blob/master/Formula/.rb

**Comment by caarlos0** [comment]
thanks for reporting this, will take a look asap

**Comment by caarlos0** [comment]
will release the next version
