### ISSUE TITLE
Brew formula update commit message

### ISSUE THREAD

**Issue by mingrammer** [goreleaser/goreleaser#604]
The auto generated commit message for brew formula update looks like `<package name> version <version>` now. But I think it is better to add a prefix to commit message so that someone know that commit was auto generated for formula update.

Here are some candidates:
- `Brew formula update for <package name> version <version>`
- `Formula update for <package name> version <version>`
- `[Brew Formula Update] <package name> version <version>`
- `[Formula Update] <package name> version <version>`
- `[Brew Formula] <package name> version <version>`
- `[Formula] <package name> version <version>`

**Comment by caarlos0** [comment]
good idea!
