### ISSUE TITLE
create useful docker images

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#606]
right now our images are kind of useless: they don't have any of the deps that goreleaser needs to run successfully.

if we didn't had git as a dep #500, it might work, but until then, it's useless.

I think we should have an image that has:

- goreleaser
- git
- gnupg2
- snapcraft
- rpm
- docker
- latest go version

this might as well help us on #350

**Comment by jaxxstorm** [comment]
@caarlos0 I was going to build my own images, but I'm happy to work on this. A few questions:

- I'd probably base this on the official golang image - any objections?
- How do you want the binary included? After the travis build steps, or do you want it built from source each time?
- Can this be placed in `/docker` in the repo?

**Comment by caarlos0** [comment]
@jaxxstorm I think we can release the docker image with goreleaser itself.

I was working on this some weeks ago, but couldn't get snapcraft to work.

If you want to see my WIP https://github.com/goreleaser/goreleaser/compare/docker?expand=1

**Comment by jaxxstorm** [comment]
@caarlos0 it seems getting snapd running inside a container isn't really that easy.

There's an example build script here: https://github.com/ogra1/snapd-docker/blob/master/build.sh

But it requires CAP_SYS_ADMIN to work. Is it worth omitting that?

**Comment by caarlos0** [comment]
> @caarlos0 it seems getting snapd running inside a container isn't really that easy.
> 
> There's an example build script here: ogra1/snapd-docker:build.sh@master
> 
> But it requires CAP_SYS_ADMIN to work. Is it worth omitting that?

yeah, dunno. 

maybe initially we can omit snapcraft (and document) and get back to this later?

**Comment by caarlos0** [comment]
The general idea is that the current image is kind of useless, so anything more useful than that is a win 🤔

**Comment by jaxxstorm** [comment]
Sounds reasonable to me!
