### ISSUE TITLE
docker: make push optional

### ISSUE THREAD

**Issue by buchanae** [goreleaser/goreleaser#608]
I prefer to make draft releases, and publish them after I've reviewed the automatically generated artifacts. This works well enough for GitHub releases, but does not seem to be well supported by Docker.

A simple `nopush` config flag would be helpful, which would allow me to build the docker images via goreleaser, and then manually run `docker push` when I'm ready.

**Comment by caarlos0** [comment]
check https://github.com/goreleaser/goreleaser/pull/613
