### ISSUE TITLE
Add target fields to Docker config for multi-stage builds

### ISSUE THREAD

**Issue by rwlincoln** [goreleaser/goreleaser#609]
### Describe the feature and how you think it should work.

I would like to have a single Dockerfile with multiple `FROM` statements and to build multiple images. However, I can't see how the `target` argument to `docker build` can be set in the config:

https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage

Perhaps a field could be added to the Docker configuration settings.

**Comment by caarlos0** [comment]
Not sure this makes sense.

GoReleaser is already building the binaries, why would you use multi-stage builds?

**Comment by rwlincoln** [comment]
Perhaps I have misunderstood how this works. I was thinking of having one stage based on a Debian image that would link the binary to `glibc` and one based on Alpine that would link to `musl`.

**Comment by caarlos0** [comment]
yeah, that's currently not possible...

**Comment by caarlos0** [comment]
closing based on previous comments.

**Comment by leopku** [comment]
> Perhaps I have misunderstood how this works. I was thinking of having one stage based on a Debian image that would link the binary to `glibc` and one based on Alpine that would link to `musl`.

I meet same thing. 

My binaries were build with gox, and they can work with `glibc` based OS.
My docker image was based on Alpine. It cannot using binary generated by goreleaser.
I am now confusing about how to do multi-stage building from goreleaser.

Is here anyone can give me some help?

**Comment by caarlos0** [comment]
as stated on the comment above, you shouldn't use multi-staged builds with goreleaser, as it already builds the binaries...

you can have several build configs and several docker configs and use specific builds with specific docker configs, check docs for details :)

anyway, goreleaser and gox do not work together.

**Comment by leopku** [comment]
Thanks a lot. @caalberts 
Finally I using another way to get goreleaser and gox to work `together`.
