### ISSUE TITLE
Have a way to customize the url in a brew formula

### ISSUE THREAD

**Issue by robinjoseph08** [goreleaser/goreleaser#610]
When using the `GitHubPrivateRepositoryReleaseDownloadStrategy` download strategy for Homebrew, it requires the `HOMEBREW_GITHUB_API_TOKEN` environment variable to be set when installing the formula. We prefer using `:git` as the download strategy instead, since we already have our SSH keys configured. But with the current `url` that is set (i.e. the link to the tarball) doesn't work with `:git`.

It would be nice if the `url` would either convert automatically to the git URL, or at least provide a way to override it.

**Comment by robinjoseph08** [comment]
Normally when we download private repos, we do so with the git URL (e.g. `git@github.com:test/example.git`), and since we've all set up our SSH keys, we don't have to enter any password or token.

So if we push up a release/tag to a private repo, we can clone it down using the git URL and we won't have to export a GitHub token. So the formula would have this line:

```rb
url "git@github.com:test/example.git", :using => :git, :tag => "0.0.1"
```

Ideally, there's a way to get this configuration with `goreleaser`.

**Comment by caarlos0** [comment]
yeah, but this will download the sources, not the tar.gz with the compiled binaries.

The current formula doesn't work that way...

**Comment by caarlos0** [comment]
I'll close this one as this is not as homebrew integration works right now.

Maybe when/if #342 is done we can get back to this one.
