### ISSUE TITLE
Using go releiser for command line tool

### ISSUE THREAD

**Issue by RaynDol** [goreleaser/goreleaser#626]
HI,

Looks like great tool :) Some general question.

Lets assume that i've create simple command line tool with go that prints hello world.
Now I use goreleaser to provide first release on github.

How the user can use this command line tool

1. in case he have go installed he can use go get and get this tool and provide the commands to run it like 'mytool print message'
2. in case he **dont** have go installed he can download the binary which provided by go releaser 
and run 'mytool print message'  which work either

Is my both above assumptions correct ?

Thanks!

**Comment by caarlos0** [comment]
Thanks :)

yes, `go get` should still work, as it will be still a valid repo.

and the user can download the binaries from the release as well.
