### ISSUE TITLE
Support not using github releases

### ISSUE THREAD

**Issue by jhuntoo** [goreleaser/goreleaser#627]
### Prerequisites

* [x ] Are you running the latest version?
* [ x] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

Support for not using github releases at all, isn't quite there. Goreleaser fails if you don't set GITHUB_TOKEN, and then will fail later even though the artifactory upload succeeded.

### Environment

Please paste the output of:

* `go version`: go1.9.4 darwin/amd64
* `uname -a`: Darwin MC02V94YEHTD5 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
* `goreleaser --debug`

 ```• RELEASING TO ARTIFACTORY
      • uploaded successful       instance=devlocal mode=archive uri=https://redacted:443/artifactory/binary/cgscli/1.0.16/cgscli-1.0.16-darwin-amd64.tar.gz
      • uploaded successful       instance=devlocal mode=archive uri=https://redacted:443/artifactory/binary/cgscli/1.0.16/cgscli-1.0.16-linux-amd64.tar.gz
      • uploaded successful       instance=devlocal mode=archive uri=https://redacted:443/artifactory/binary/cgscli/1.0.16/cgscli-1.0.16-windows-amd64.tar.gz
   • RELEASING TO GITHUB
      • creating or updating release repo=platform/cgscli tag=1.0.16
      • release updated           url=
   ⨯ release failed after 48.50s error=POST https://api.github.com/repos/platform/cgscli/releases: 401 Bad credentials
```

### Steps to Reproduce

1.  Create a config like this
```yaml
release:
  draft: true
artifactories:
  - name: devlocal
    target: https://redacted/artifactory/binary/{{ .ProjectName }}/{{ .Version }}/
    username: goreleaser
```
2.  Run the command like this `ARTIFACTORY_DEVLOCAL_SECRET=goreleaser  GITHUB_TOKEN=dummy goreleaser --debug --rm-dist`

**Expected behavior:** [What you expected to happen]
To only perform a artifactory upload.

**Actual behavior:** [What actually happened]
GArtifactory upload occurs, then something fails trying to hit the github API endpoint for the repos releases, which doesn't exist.

**Comment by caarlos0** [comment]
hm

The problem is that goreleaser "guess" the github repository based on the git remote, so it's never empty.

maybe something like:

```yaml
release:
  github: false
```

fixes the issue?

**Comment by jhuntoo** [comment]
So with the config...
```yaml
release:
  github: false
```
I get an unmarshal error...
```bash
• releasing using goreleaser 0.63.1...
   • loading config file       file=.goreleaser.yml
   • loaded config file        config={cgscli { %!s(bool=false) %!s(bool=false) } {  { }     []  []   %!s(bool=false) } { { }   } [{[windows darwin linux] [amd64] [] [] [] main.go -X cgscli/util.Version={{.Version}}  cgs {make go-bind } [CGO_ENABLED=0] }] {{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }} map[]  [] %!s(bool=false) []} { map[] [] [] [] [] []       map[] map[]} { map[] [] [] [] [] []       map[] map[]} { map[]      map[]} {{{ .Tag }}} {} [] [{https://artifactory.illinois.camelot.global/artifactory/binary/{{ .ProjectName }}/{{ .Version }}/ devlocal goreleaser }] {{[]} }  { []  } {} {%!s(bool=false)} {[] [] [] [] []     { } [] } {  }}
   ⨯ release failed after 0.00s error=yaml: unmarshal errors:
  line 26: cannot unmarshal !!bool `false` into config.Repo
```

I've also tried the following but I get the original error

```yaml
release:
  github:
```

**Comment by caarlos0** [comment]
> So with the config...

yes, this is the a proposed feature, it is not implemented yet, sorry for not making that clear :)

**Comment by jhuntoo** [comment]
I see now!  That config would work, though IMO making the `release` section optional would be better as it's more concise.


This also relates to #110. 

For my 2 cents, having the github section as optional would be advantageous as it would support  the addition of gitlab, and others. So all these "release providers" would in fact be optional.

```yaml
release:
    github: #optional
        ...all GH specific properties
    gitlab: #optional
        ...all GL specific properties
```

Some of the properties may be common to all release providers, like `name_template ` etc. But for example i don't think gitlab supports  `prerelease`

**Comment by caarlos0** [comment]
> I see now! That config would work, though IMO making the release section optional would be better as it's more concise.

yeah, but since right now it defaults a lot of things, making it optional would break almost everyone's workflow :/

**Comment by caarlos0** [comment]
the idea of the actual syntax would be to do:

```
release:
  github:
    owner: user
    name: repo
  gitlab:
    owner: user
    name: repo
```

but artifactory is so different that it got a special `artifactory` config section.

so, my idea of `github: false` is also wrong 🤔

Anyway, I have this idea of "freezing" the current config format for a proper 1.0 release.

For 2.0, I'll probably do a whole new config based on previous learnings (in which your idea makes a lot of sense).

To fix this problem right now, maybe the easiest way is to do a

```yaml
release:
  disable: true
```

or `skip: true` or something like that.

Thoughts?

**Comment by jhuntoo** [comment]
That seems like a sensible thing to do, rather than trying to change the format too much here, wait for 2.0 and a "blank canvas" approach.

Ok, unless you think it's too complicated, I can make an attempt at the PR ?

**Comment by caarlos0** [comment]
> Ok, unless you think it's too complicated, I can make an attempt at the PR ?

sure, it should be easy :)
