### ISSUE TITLE
How to automate the release

### ISSUE THREAD

**Issue by RaynDol** [goreleaser/goreleaser#628]
Hi,

while you need to provide new release you need to do the following:

1. git add
2. git commit
3. git push master
4. git tag -a v0.0.1 -m "new release"
5. git push origin v0.1.0
6. goreleaser 
Please correct me if im wrong :) 

is there a way to automate it via go releaser that with one command or two it will run all the 6 steps above ?

Thanks &Best Regards,
Rayn

**Comment by caarlos0** [comment]
for questions please use slack (as stated in the issue template).

the process is documented on: https://goreleaser.com/#quick_start

about the tag auto push, check #499
