### ISSUE TITLE
create a website

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#63]
I already started something at https://github.com/goreleaser/goreleaser.github.io, but it's ugly.

If someone wants to do this, let me know =)

**Comment by medhoover** [comment]
Hey Carlos,
Would love to help.

**Comment by caarlos0** [comment]
Hi @medhoover !

Glad to hear that!

Feel free to open a PR to  https://github.com/goreleaser/goreleaser.github.io and let me know if you need any help :)

**Comment by medhoover** [comment]
Thank you @caarlos0 
Do you prefer static or Jekyll?

**Comment by caarlos0** [comment]
@medhoover feel free to do what you think it's best =D

**Comment by medhoover** [comment]
https://github.com/goreleaser/goreleaser.github.io/pull/1
:+1:

**Comment by caarlos0** [comment]
Looks great, thanks!

**Comment by medhoover** [comment]
Welcome :)
btw, since you're currently working on enhancing the docs, why not creating a single docs folder the will be used for both of the website and the repo.  
This way, we wont need to update the website whenever the documentation is changed.
More on this [here](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages)

**Comment by caarlos0** [comment]
Maybe #81 will make this easier?

**Comment by medhoover** [comment]
Definitly, Thanks!
I'll start working on it.

**Comment by medhoover** [comment]
@caarlos0 
What do you guys think about this docs structure:
1. Introduction
2. Quick start
3. Environment setup
4. Release customization with goreleaser.yml
5. Integration with CI
6. Publishing _"Homebrew and future others"_

**Comment by caarlos0** [comment]
@medhoover seems good to me...

Maybe publishing to homebrew makes more sense inside release customization item... what do you think?

**Comment by medhoover** [comment]
Yes indeed, both shares the same topic.
Update:
1. Introduction
2. Quick start
3. Environment setup
4. Release customization
5. Integration with CI

Maybe we should tag others to check what do they think.

**Comment by caarlos0** [comment]
Sure!

Looks good!

cc/ @jorinvo @jspc

**Comment by sagikazarmark** [comment]
I would love to see a complete config example for reference somewhere. Not sure though if the website/docs is the perfect place for that as it can easily get outdated.

**Comment by caarlos0** [comment]
I'll probably do that in some kind of unit test 👍
