### ISSUE TITLE
Support using tag annotation in changelog

### ISSUE THREAD

**Issue by nicpottier** [goreleaser/goreleaser#631]
### Describe the feature and how you think it should work.

We use git annotations when tagging releases to create a "formatted changelog" of sorts in markdown. This makes sure we have one truth as to the changelog for a release and leverages git's store to track those.

Would be really nice to have the option to include the tag's annotation in the generated changelog goreleaser creates for new releases. I like the current inclusion of all the commits from the perspective of being totally complete, but it would be nice to have the human summary that is in our annotations leading off the release. (above `Assets`)

Example annotation (look at v1.2.75) in markdown: (hit the ...)
  https://github.com/nyaruka/courier/tags

Seems this could be an option in the `changelog` section. Perhaps just an `include_annotation: true`?

Happy to do the work and open a PR if it would be accepted.

**Comment by caarlos0** [comment]
so, basically, add whatever is on the annotation to the release body, if any, right?

**Comment by nicpottier** [comment]
Right, preferably above the commit history.

**Comment by caarlos0** [comment]
OK, I did some initial code for this. AFAIK there is no way to tell if a given tag is annotated or not, right?

**Comment by nicpottier** [comment]
Hrmm, not sure. Seems a light parsing of `git show` for the tag would provide it.

**Comment by caarlos0** [comment]
yeah, so, experimenting:

```console
$ git for-each-ref refs/tags/v7.0.22 --format '%(contents)'
asdasd

$ git for-each-ref refs/tags/v7.0.23 --format '%(contents)'
uidshiaudhiuasd
adasdaada

- adsasd
- asdasd
- sd33d3
```

all the ways I found to get the annotation, return the commit msg when there is annotation...

any ideas?

**Comment by caarlos0** [comment]
hmm, seems like we just need to ignore the first line...

either way it has a tab in the beginning of each line, will try to find other ways, probably there is something on the "low level" git commands

**Comment by caarlos0** [comment]
I couldn't find a way of doing this in a reliable way, so I'll close this.

If you find a way of doing that, please let us know.

Maybe when fixing #500 we can do this as well?
