### ISSUE TITLE
rpmbuild fails when tag contains hyphen

### ISSUE THREAD

**Issue by twhiston** [goreleaser/goreleaser#632]
### Description

When using rpm build with a semver compatible tag such as `2.5.0-beta1` rpmbuild will currently fail because hyphens are not allowed in version numbers. It would be great if goreleaser either sanitized these automatically or offered us the option to override the version in package builds so we could keep semver compatible tags.

See https://github.com/semver/semver/issues/145 for context

### Steps to Reproduce

1.  tag a release with a hypen in the name
2.  run goreleaser with rpm builds configured
3.  build fails

**Expected behavior:** 
Tag is sanitized and build passes

**Actual behavior:** 
 `⨯ release failed after 76.86s error=nfpm failed: rpmbuild failed: error: line 10: Illegal char '-' in: Version: 2.5.0-test9`

**Comment by caarlos0** [comment]
which version of goreleaser are you using?

this should be fixed on https://github.com/goreleaser/nfpm/releases/tag/v0.6.2 which is included on https://github.com/goreleaser/goreleaser/releases/tag/v0.64.0 .

**Comment by twhiston** [comment]
my bad, didnt realize we had an old version cached on the ci. Update to newest works. Sorry!

**Comment by caarlos0** [comment]
no problem :)
