### ISSUE TITLE
Support self-hosted build artifacts

### ISSUE THREAD

**Issue by brocaar** [goreleaser/goreleaser#633]
First of all thanks for all the great work on goreleaser!

It seems that goreleaser will always upload all the artifacts to GitHub on a release. Related to this, when generating download links (e.g. for homebrew) it is assumed that the files are hosted on GitHub.

Would it be possible to have (optional) support for self-hosted artifacts? For example, I have my own downloads server so that I can keep track of download statistics (per package name, version, GEO location etc..). When configured, goreleaser would not push the artifacts to GitHub and for the download URL (e.g. brew) it would use a customizable URL template.

I think what would be needed for this:

- Add a flag to the `release` section to disable the push of artifacts when creating a release.
- Add a configuration option to define a download-url template, e.g. so that this can be set to `https://myserver.com/{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.tar.gz`. Maybe this would be a config option specific to the `brew` section or maybe a global option so that it can be (re)used by brew, ...? 

Looking forward to your thoughts and feedback on this.

**Comment by brocaar** [comment]
@caarlos0 I'm looking to your feedback / thoughts on this :-)

**Comment by brocaar** [comment]
Thanks for your response. I understand that from your side this might not have the highest priority. I just wanted to open the discussion around this feature to see if there would be interest in such feature.

I know that you can get the download counter per released file on GitHub through the API, but what I'm interested in is parsing the full access-logs as it also gives me the IP which I then can use to map the download to a city and / or country. 

This could also be interesting when pushing artifacts to Artifactory and then let Homebrew download from Artifactory instead of GitHub. I believe Artifactory also provides download stats.

**Comment by caarlos0** [comment]
> I believe Artifactory also provides download stats.

that's interesting... didn't know about this feature...

anyway, let me think for a while, or if you want to propose a PR for this, we can see how it looks :)

**Comment by caarlos0** [comment]
I think #583 fixes this, no?

**Comment by brocaar** [comment]
I think potentially it could, but I'm not 100% sure if this only reflects the upload part, or also the URL generation part to the artifact (e.g. used by the Homebrew recipe).

**Comment by caarlos0** [comment]
Only the upload part.

I can't think on a good way of telling brew to use one upload or another... any ideas?

**Comment by caarlos0** [comment]
homebrew now has a `url_template`, so this can be supported.

https://goreleaser.com/homebrew/

Closing!
