### ISSUE TITLE
Discuss: Allow writing changelog to a file

### ISSUE THREAD

**Issue by msabramo** [goreleaser/goreleaser#655]
I mentioned this to @caarlos0 on Slack and he asked to open an issue.

### Describe the feature and how you think it should work.

I wonder if it makes sense to have the ability to write a `CHANGELOG.md` file out, in case people want to do something with that like commit it to version control or include it in a Docker image.

**Comment by caarlos0** [comment]
you mean, the changelog of the current release only?

if yes, that's kind of easy to do, otherwise it isn't...

**Comment by caarlos0** [comment]
ping @msabramo
