### ISSUE TITLE
422 Validation Failed error on release

### ISSUE THREAD

**Issue by cv** [goreleaser/goreleaser#656]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?

### Description

See full log here: https://circleci.com/gh/cv/sd/53

**Comment by caarlos0** [comment]
seems to be related with #643

will revert it for now

**Comment by caarlos0** [comment]
should be fixed on https://github.com/goreleaser/goreleaser/releases/tag/v0.71.1

can you validate?

**Comment by cv** [comment]
Yup, this seems to have made the issue go away: https://circleci.com/gh/cv/sd/56

**Comment by caarlos0** [comment]
thanks @cv!

**Comment by caarlos0** [comment]
cc/ @holladay-io
