### ISSUE TITLE
undefined: yaml.NewDecoder

### ISSUE THREAD

**Issue by goodforever** [goreleaser/goreleaser#663]
When I go get github.com/goreleaser/goreleaser
I got
# github.com/goreleaser/nfpm
../../../../../github.com/goreleaser/nfpm/nfpm.go:40: undefined: yaml.NewDecoder

**Comment by caarlos0** [comment]
several issues about this already

https://github.com/goreleaser/goreleaser/issues?q=is%3Aissue+go+get+is%3Aclosed+label%3Ainvalid

please follow https://goreleaser.com/
