### ISSUE TITLE
Typo in Makefile

### ISSUE THREAD

**Issue by ntrrg** [goreleaser/goreleaser#665]
Hi, this looks like a typo for me, but I am just a beginner, sorry if I filled this issue unnecessarily :sweat_smile:

https://github.com/goreleaser/goreleaser/blob/c3988a30fc96b211432d289e0bf7c6fb3b24885b/Makefile#L29-L32

**Comment by caarlos0** [comment]
Hi @ntrrg, sorry, which part specifically you think is a typo?

**Comment by ntrrg** [comment]
`.PHONY: cover`, I was thinking that this should be `.PHONY: test`.

**Comment by caarlos0** [comment]
oh, indeed! Thanks!

**Comment by ntrrg** [comment]
Great! :smiley:
