### ISSUE TITLE
GitHub pre-releases on alpha, beta, rc versions

### ISSUE THREAD

**Issue by tympanix** [goreleaser/goreleaser#667]
**Is your feature request related to a problem? Please describe.**
When the version tag is not stable; e.g. `1.0.0-alpha`, ` 1.0.0-beta` or `1.0.0-rc` (see [https://semver.org/#spec-item-11](https://semver.org/#spec-item-11)) I would like the github release to be a `pre-release`.

**Describe the solution you'd like**
In the github API set the `prerelease: true` option (see [https://developer.github.com/v3/repos/releases/#create-a-release](https://developer.github.com/v3/repos/releases/#create-a-release))

**Describe alternatives you've considered**
 * Always use prereleases for `beta`, `alpha`, `rc`
 * Let the user choose whether to use prereleases or not in the configuration file

**Additional context**
Example:
![image](https://user-images.githubusercontent.com/9674814/39759236-72132384-52d2-11e8-8427-5d5c76ae5b82.png)

**Comment by caarlos0** [comment]
thats a neat idea!

thanks!

**Comment by maxcnunes** [comment]
Anyone working on this? I could try to implement it.

**Comment by caarlos0** [comment]
we probably could yeah, but I'm not there yet :/

**Comment by soupdiver** [comment]
I'm interested in helping out here as well. I'm currently in need of this feature.
At the moment we can define `prerelease` `true` or `false`. An option like `auto` could be used to tell `goreleaser` should determine this by itself and check if there is `rc`, `alpha` or whatever appended to the tag.

This should also be quite easy to implement and not break older versions. 
Opinions on that?

**Comment by soupdiver** [comment]
ping @caarlos0

**Comment by caarlos0** [comment]
this was done on #871 


closing...
