### ISSUE TITLE
List formats for flags, ldflags, asmflags, and gcflags

### ISSUE THREAD

**Issue by elyscape** [goreleaser/goreleaser#668]
**Is your feature request related to a problem? Please describe.**
[As of Go 1.10][go1.10]:
>The `go build` `-asmflags`, `-gcflags`, `-gccgoflags`, and `-ldflags` options now apply by default only to the packages listed directly on the command line. For example, `go build -gcflags=-m mypkg` passes the compiler the `-m` flag when building `mypkg` but not its dependencies. The new, more general form `-asmflags=pattern=flags` (and similarly for the others) applies the flags only to the packages matching the pattern.

In other words, you can pass different flag sets to the compiler based on the package you're passing. Unfortunately, this has to be done with multiple uses of `-gcflags` et al. For example, given the following code:
```shellsession
elyscape:flagdemo eliyoung$ pwd
/Users/eliyoung/go/src/github.com/elyscape/flagdemo
elyscape:flagdemo eliyoung$ cat main.go
package main

import (
	"fmt"

	"github.com/elyscape/flagdemo/sub"
)

var (
	one = ""
)

func main() {
	fmt.Println("one:", one)
	sub.Print()
}
elyscape:flagdemo eliyoung$ cat sub/sub.go
package sub

import (
	"fmt"
)

var (
	two = ""
)

func Print() {
	fmt.Println("two:", two)
}
```
Here are the source file paths included in the resulting binary:
```shellsession
elyscape:flagdemo eliyoung$ go build -a .
elyscape:flagdemo eliyoung$ strings flagdemo | grep 'elyscape.*go$'
/Users/eliyoung/go/src/github.com/elyscape/flagdemo/main.go
/Users/eliyoung/go/src/github.com/elyscape/flagdemo/sub/sub.go
/Users/eliyoung/go/src/github.com/elyscape/flagdemo/sub/sub.go
/Users/eliyoung/go/src/github.com/elyscape/flagdemo/main.go
```
Suppose that, for some reason, I want to set different trimpaths for different subpackages. Trying to put both in a single `-gcflags` value doesn't work:
```shellsession
elyscape:flagdemo eliyoung$ go build -a -gcflags '.=-trimpath=/Users/eliyoung/go/src ./sub=-trimpath=/Users/eliyoung/go/src/github.com' .
# github.com/elyscape/flagdemo
./sub=-trimpath=/Users/eliyoung/go/src/github.com:0:0: open ./sub=-trimpath=/Users/eliyoung/go/src/github.com: no such file or directory
```
By contrast, using `-gcflags` multiple times does work:
```shellsession
elyscape:flagdemo eliyoung$ go build -a -gcflags '.=-trimpath=/Users/eliyoung/go/src' -gcflags './sub=-trimpath=/Users/eliyoung/go/src/github.com' .
elyscape:flagdemo eliyoung$ strings flagdemo | grep 'elyscape.*go$'
github.com/elyscape/flagdemo/main.go
elyscape/flagdemo/sub/sub.go
elyscape/flagdemo/sub/sub.go
github.com/elyscape/flagdemo/main.go
```
Additionally, some of the flags one might want to specify in the `flags` field, such as `-tags` (which is given in the example), take space-separated arguments, and there's currently no way to represent that.

**Describe the solution you'd like**
It would be nice if the `ldflags` et al. took arrays, each of which was then processed as a template and then passed individually to the compiler. To demonstrate with a slightly modified version of example above, this:
```yaml
flags:
- -a
- tags
- tagone tagtwo
gcflags:
- .=-trimpath={{.Env.GOPATH}}
- ./sub=-trimpath=/Users/eliyoung/go/src/github.com
```
Would be turned into something like this (with a bunch of extraneous quotes and newlines for clarity):
```shell
go build \
	'-a' \
	'-tags' \
	'tagone tagtwo' \
	'-gcflags=.=-trimpath=/Users/eliyoung/go/src' \
	'-gcflags=./sub=-trimpath=/Users/eliyoung/go/src/github.com' \
	.
```
Of course, making a field in the YAML be either a string or an array is complicated in Go. Probably the best way to do this is to use the approach provided [in this comment][StringArray]; that is, mark those fields as a new type called `StringArray`, which is basically just an alias for `[]string` but which has a custom YAML unmarshalling method that converts bare strings into one-element arrays.

For `ldflags`, `gcflags`, and `asmflags`, this would be a drop-in fix with no further ramifications, but `flags` is complicated by the fact that it currently runs the value through `strings.Fields()`, and we'd probably want to preserve that behavior to avoid breaking anything. The best way to deal with that would probably be to have it have its own custom type (`FlagsArray`?) and YAML unmarshaller that, when provided with a bare string, runs it through `strings.Fields()` and returns the result of that, instead of just wrapping the bare string in an array.

**Describe alternatives you've considered**
Instead of making the various fields automatically upconvert into arrays, we could instead deprecate them and add new fields like `ldflags_list` which are natively arrays. Alternatively, we could do that only for `flags`, which is the only problematic field.

[go1.10]: https://golang.org/doc/go1.10#build
[StringArray]: https://github.com/go-yaml/yaml/issues/100#issuecomment-324964723

**Comment by elyscape** [comment]
Okay, we're good to go. @caarlos0, I can write up a pull request for this if you let me know which approach to take. For clarity, those are:
1. Change `ldflags`, `gcflags`, and `asmflags` to type `StringArray`, which has an `UnmarshalYAML` method that upconverts bare strings into one-element arrays, and `flags` to type `FlagsArray`, which has an `UnmarshalYAML` method that upconverts bare strings into arrays by running them through `strings.Fields()`
1. Change `ldflags`, `gcflags`, and `asmflags` to type `StringArray` and deprecate `flags` in favor of a new field called `flags_list` (or something)
1. Deprecate `flags`, `ldflags`, `gcflags`, and `asmflags` in favor of new `*_list` fields

**Comment by elyscape** [comment]
Alternatively, a fourth approach:

4. Handle `flags` as in one of the preceding approaches and deprecate `ldflags`, `gcflags`, and `asmflags` in favor of some new fields that look like this:
    ```yaml
    gcflags_list:
    - pattern: ./sub
      args: -trimpath=/Users/eliyoung/go/src/github.com
    - args: -trimpath={{.Env.GOPATH}}
      # pattern isn't necessary here because no pattern is equivalent to '.'
    ```

**Comment by caarlos0** [comment]
I think that not breaking compatibility is the ideal... you can for sure open a PR, I would be glad 😄

**Comment by elyscape** [comment]
To be clear, all of the approaches I listed preserve compatibility. Which do you think I should implement?

**Comment by caarlos0** [comment]
sorry, the `StringArray` one seems better IMO :)

**Comment by elyscape** [comment]
I’ll make it happen!

**Comment by caarlos0** [comment]
thanks @elyscape 🎉
