### ISSUE TITLE
snapcraft: invalid arch armel

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#683]
**Describe the bug**

The snapcraft package for amrv6 is generated with the `armel` arch - which I think is for rhel.

Anyway, snapcraft does not think that's valid, so we gotta fix this.

**To Reproduce**

Try to push a armv6 goreleaser-generated snap package.

**Comment by caarlos0** [comment]
@elopio any pointers here?

**Comment by elopio** [comment]
Hello @caarlos0. Snapcraft doesn't support armel. Just armhf and arm64.
