### ISSUE TITLE
Wrong sha256 used in Brew Forumula generation

### ISSUE THREAD

**Issue by TylerBrock** [goreleaser/goreleaser#686]
**Describe the bug**

goreleaser is using the `darwin_amd64.tar.gz` sha256 instead of the one for the source.

**To Reproduce**

```yaml
builds:
  - binary: saw
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archive:
  format: tar.gz
  files:
    - LICENSE

brew:
  name: saw

  github:
    owner: TylerBrock
    name: homebrew-saw

  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

  commit_author:
    name: TylerBrock
    email: <redacted>

  folder: Formula
  homepage: "https://github.com/TylerBrock/saw"
  description: "Fast, multipurpose tool for AWS CloudWatch Logs"

  build_dependencies:
    - go
    - dep

git:
  short_hash: true
```

I'm generating a formula for my project called Saw. It works fine then I add the tap and install the formula but then it says it expects the sha256 to be the darwin one instead of the one for the source tarball.

```sh
$ brew tap TylerBrock/saw
...
$ brew install saw
==> Installing saw from tylerbrock/saw
==> Downloading https://github.com/TylerBrock/saw/archive/v0.1.2.tar.gz
==> Downloading from https://codeload.github.com/TylerBrock/saw/tar.gz/v0.1.2
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: f7398ea54c80befe994f898010c21ef9a62c880c2f25a9ac2bf84765a09b5313
Actual: bfdf5988554276327544eb8fea3943792ac63bfbe0d558bc1ef65d105b6764f3
Archive: /Users/tbrock/Library/Caches/Homebrew/saw-0.1.2.tar.gz
To retry an incomplete download, remove the file above.
```

This is what the generated formula looks like:

```rb
class Saw < Formula
  desc "Fast, multipurpose tool for AWS CloudWatch Logs"
  homepage "https://github.com/TylerBrock/saw"
  url "https://github.com/TylerBrock/saw/archive/v0.1.2.tar.gz"
  head "https://github.com/TylerBrock/saw.git"
  version "0.1.2"
  sha256 "f7398ea54c80befe994f898010c21ef9a62c880c2f25a9ac2bf84765a09b5313"
  depends_on "go" => :build
  depends_on "dep" => :build

  def install
    bin.install "saw"
  end
end
```

So of course this is not-working because it's writing the formula with the darwin_amd64 sha256 rather than the one for the source tar.gz (which is the file it requests via `url`).

```sh
$ gsha256sum saw_0.1.2_darwin_amd64.tar.gz
f7398ea54c80befe994f898010c21ef9a62c880c2f25a9ac2bf84765a09b5313  saw_0.1.2_darwin_amd64.tar.gz
$ gsha256sum saw-0.1.2.tar.gz
bfdf5988554276327544eb8fea3943792ac63bfbe0d558bc1ef65d105b6764f3  saw-0.1.2.tar.gz
```

**Expected behavior**

I'd expect for it to use the sha starting with `bfdf59...` in the formula.

**Environment (please complete the following information):**

- OS: Mac OS X
- OS version: Sierra 10.13.4
- GoReleaser Version 0.77.0

**Additional context**

**Comment by errordeveloper** [comment]
I am seeing this also.

**Comment by caarlos0** [comment]
Hi!

If you remove the `build_depencencies` it should work. The formula doesn't really need that if you will provide it as a tap.

The build_depencies are a first step into the direction of generating a brew formular that can be accepted on the homebrew core, but right now there it is buggy, and I couln't think of a good way of fixing it so far.

You can check #687 for more info :)

**Comment by errordeveloper** [comment]
Ok, I see - will try that.

**Comment by errordeveloper** [comment]
Yes, it worked! 🎉 

I would recommend updating the docs and removing `build_dependencies` until it becomes a usable option.

**Comment by caarlos0** [comment]
Agree, I'm actually thinking about removing this entire feature.

Thinking about the usability of it: AFAIK, most core formulas are created once and updated by a bot, eg: https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+sort%3Aupdated-desc+goreleaser+is%3Aclosed

Also, this feature just don't work for now. I'll remove it and see if someone else asks for it.
