### ISSUE TITLE
It should be easier to use a floating release tag

### ISSUE THREAD

**Issue by errordeveloper** [goreleaser/goreleaser#690]
I've spent all day trying to make `goreleaser` work with a floating tag.

Github doesn't make it easy to provide a short command to download a release artefact. You have to either find release number (e.g. using `jq`), or do something else. We've been using `latest_release` tag with some success in e.g. [Weave Net](https://github.com/weaveworks/weave/blob/master/docs/release-process.md),  however we use a fork for `github-release` there and a shell script to drive `github-release`.

I've been trying to use `goreleaser` and it worked nicely for most part, however there is no option to re-create a release, and when I try to use it with a floating tag it fails while trying to re-upload artefacts. A 
option to re-create release on the same tag but with a new name, description and artefacts would be very nice.

**Comment by caarlos0** [comment]
Hi @errordeveloper, thanks for opening the issue!

I've used weavenet in the past, great piece of software, thanks :D 

---

Regarding your issue, what you do is just create two tags right, one e.g. `v1.2.3` and another `latest_release`, both pointing to the same commit, and then upload the same artifacts on both of them, right?

Have you tried:

````
git tag v1.2.3
goreleaser
git tag latest_release
goreleaser
```

?

It will rebuild everything, but the output should be the same...

Anyway, I don't know what a good UI for this would be... what do you have in mind?

**Comment by errordeveloper** [comment]
Yes, I have tried this first! What happens is that goreleaser catches only
the first tag, it is how `git describe --tags` behaves, I am afraid... And
what you end up with two CI jobs competing which one will upload the
release for semver tag and which will fail uploading the release for the
same thing :(

**Comment by caarlos0** [comment]
hmm, any suggestions on the desired UI?

adding a config `floating_tag` or something maybe?

**Comment by errordeveloper** [comment]
Yes, that would make sense, but to me seemed like this would be mostly
about forcing releases to be recreated, or, in other words, updating an
existing release... See for yourself whatever makes sense. I suppose it
would be either about naming a particular tag with a string parameter
(`floating_tag: latest_release`) or a bolean (`allow_recreate: true`).

The project where I had to deal with this is now open-source, feel free to
take a look - https://github.com/weaveworks/eksctl.

There is `tag_release.sh`, which updates two somewhat redundant goreleaser
config files (thanks for fixing #691, it should eliminate the need for
that!), and there is `do_release` target defined in `Makefile`, which
ensures `latest_release` tag gets removed before goreleaser runs.

**Comment by caarlos0** [comment]
I still don't know a good way of implementing this :/
