### ISSUE TITLE
ADD failed: stat /var/lib/docker/tmp/docker-builder287293416/main.go: no such file or directory

### ISSUE THREAD

**Issue by kaihendry** [goreleaser/goreleaser#694]
**Describe the bug**

https://s.natalian.org/2018-06-06/goreleaser-docker.mp4

**To Reproduce**

https://github.com/unee-t/apienroll/blob/master/goreleaser.yml

**Expected behavior**

Builds and publishes Docker image

**Environment (please complete the following information):**

On Archlinux

```
[hendry@t480s apienroll]$ git --git-dir=$HOME/go/src/github.com/goreleaser/goreleaser/.git  describe --always
5629759
```

**Additional context**

```
   • CREATING DOCKER IMAGES
      • building docker image     image=uneet/apienroll:v0.0.3
   ⨯ release failed after 1.30s error=failed to build docker image:
Sending build context to Docker daemon  6.333MB
Step 1/12 : FROM golang:alpine
 ---> 05fe62871090
Step 2/12 : RUN apk --no-cache add git
 ---> Using cache
 ---> df555555143e
Step 3/12 : ADD main.go /go/src/app/main.go
ADD failed: stat /var/lib/docker/tmp/docker-builder287293416/main.go: no such file or directory
: exit status 1
```

**Comment by caarlos0** [comment]
Your dockerfile should't try to rebuild the app, look at the dockerfile at the root of this repo for example.

Nevertheless, we can probably improve documentation on that.

**Comment by caarlos0** [comment]
actually the [Docker](https://goreleaser.com/docker) section on goreleaser's docs already have a dockerfile example.

Anyway, I made the docs a little bit better.

**Comment by kaihendry** [comment]
Oh... so instead of what I had here: https://github.com/unee-t/apienroll/blob/master/Dockerfile ... i use your template:

```
FROM scratch
COPY mybin /
ENTRYPOINT ["/mybin"]
```

Now I am understanding :sweat_smile:

**Comment by kaihendry** [comment]
Oddly it's not finding my binary in my [test project](http://github.com/kaihendry/lk2)..


```
[hendry@t480s lk2]$ docker run -p 9000:9000 -v /home/hendry/media/out/2018-06-05:/media hendry/lk2
standard_init_linux.go:190: exec user process caused "no such file or directory"

```

**Comment by caarlos0** [comment]
yes, now it's a matter of how your app is compiled.

this error seems to be because your app was compiled with CGO enabled, if you want to use scratch as base, you'll need to disable CGO. You can do that adding:

```yaml
build:
  env:
    - CGO_ENABLED=0
```

to your `goreleaser.yml` file `build` section.

Another option is to use another image as base, for example debian or ubuntu...

**Comment by caarlos0** [comment]
no, it shouldn't be default.

https://golang.org/cmd/cgo/

**Comment by kaihendry** [comment]
If it's not enabled by default, why do I need to specify that in my https://github.com/kaihendry/lk2/blob/master/goreleaser.yml env ?

**Comment by caarlos0** [comment]
it is enabled by default in the Go compiler, so it is enabled by default on goreleaser as well.

`CGO_ENABLED=0` disables it, actually.
