### ISSUE TITLE
Support a workflow that doesn't depend on git tags

### ISSUE THREAD

**Issue by buchanae** [goreleaser/goreleaser#701]
We've been using goreleaser to create draft releases on GitHub, which are then manually published after review. During this process, we create a git tag locally for goreleaser to determine the version. We never push this tag, since a tag will be created when the draft release is published. We also keep the release version in other parts of the code, for things outside the scope of goreleaser.

goreleaser is trying to make things easier by autodetecting the version from the git tag, but for me it adds overhead that doesn't outweigh the benefit.

Is it possible, and would you consider, allowing this automatic version detection to be disabled? In this case, I would provide the version via an environment variable and/or goreleaser yaml config.

**Comment by caarlos0** [comment]
I think that can be done, yes.

**Comment by caarlos0** [comment]
is this still a thing @buchanae ?

if yes, we can re-open it... not sure when/if I'll work on it though

**Comment by buchanae** [comment]
I still think it would be nice, but I too am not sure when/if I'll work on it.

**Comment by caarlos0** [comment]
will leave the issue closed then, we can reopen at any time, ok?

**Comment by buchanae** [comment]
roger that
