### ISSUE TITLE
thank you for this project!

### ISSUE THREAD

**Issue by deepthawtz** [goreleaser/goreleaser#702]
I really appreciate your work and use this project a lot. sorry to spam your issues but Thanks!

@GitCash send 0.008 BCH to @caarlos0

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/128/image.png)](https://gitcash.io/claim/caarlos0)
@caarlos0

**Comment by deepthawtz** [comment]
glad you received this, i'll shut this issue down now 🍻

**Comment by caarlos0** [comment]
Thanks @deepthawtz =D
