### ISSUE TITLE
--skip-publish=true fails

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#718]
see bug report at https://github.com/gohugoio/hugo/issues/4918

**Comment by caarlos0** [comment]
I think this is a bug on kingpin.

**Comment by mekegi** [comment]
@caarlos0 
https://github.com/alecthomas/kingpin/#boolean-values
kingpin work with bool like
```
go run main.go --skip-publish
```
or for negative
```
go run main.go --no-skip-publish
```
without `=true` or `=false`
looks like not a bug

**Comment by caarlos0** [comment]
yes, I think so... 

will close it, thanks @mekegi !
