### ISSUE TITLE
Clarify usage of Git tags

### ISSUE THREAD

**Issue by jorinvo** [goreleaser/goreleaser#72]
The main use case for GoReleaser seems to be running it via CI for Git tags only.
However, nothing stops you from running it on any other branch.

By running it on another branch GoReleaser still uses the latest Git tag to name the release, 
but for building it actually uses the source of the current active branch (if I don't miss anything here?).
Also, it's not possible to create a release that doesn't depend on a Git tag.

I would suggest to either always use the source of the latest tag
or to allow releasing without a relation to Git tags.

The first solution would require to get the source from the tag for building or to only allow building when the current branch is the latest tag.

The second solution would need more thinking about other scenarios for releasing Go projects.

**Comment by caarlos0** [comment]
Yeah, right now it only releases tags...

I don't know what is best here... maybe this is a v2 thing...

**Comment by jorinvo** [comment]
@caarlos0 I think releasing tags is definitely the most useful thing and I don't think we even need to support other use cases.

However, currently you can only correctly release a tag when you switch to the tagged branch before running GoReleaser.
If I'm on my `master` branch, for example, and I have one commit more there than my latest tag, The binary will be built including this one new commit. 
It should use the source of the tag instead of the current branch.

**Comment by caarlos0** [comment]
Hmmm, that makes a lot of sense... If not that, at least exiting 1 to let the user know...

`git checkout` the tag may not be so simple, since there can be unchanged files, etc...

**Comment by caarlos0** [comment]
I'll move it to v1

**Comment by jorinvo** [comment]
I will look into this.
