### ISSUE TITLE
Before hooks are not parsed correctly

### ISSUE THREAD

**Issue by liftM** [goreleaser/goreleaser#741]
Before hooks are run using `exec.Command` after parsing with `strings.Fields`:

https://github.com/goreleaser/goreleaser/blob/d701179975d13add685038109c0d0507a614a153/pipeline/before/before.go#L24-L33

This makes it impossible to run arbitrary shell commands, because running e.g. `bash -c "foo bar"` is executed as `exec.Command("bash", "-c", "\"foo", "bar\"")` when it should be `exec.Command("bash", "-c", "foo bar")`.

In order to run arbitrary shell commands, hooks should either invoke the shell or have smarter, quotation-aware parsing.

**Comment by caarlos0** [comment]
Hi @ilikebits 

yes, it only supports simple scripts, you can wrap your complex scripts in a file and add a hook to call the file.
