### ISSUE TITLE
Add support for macOS Installer Packages

### ISSUE THREAD

**Issue by jorng** [goreleaser/goreleaser#744]
GoReleaser currently can output Linux installers (`rpm` and `deb` formats), but not macOS installers. It would be nice if it could output installer packages for macOS as well.

This can be achieved, at least when running on macOS, by using the `pkgbuild` and `productbuild` commands. An example:

```sh
pkgbuild --quiet \
    --root "darwin_amd64" \
    --identifier "private.myname.myexecutable" \
    --version "1.0.2" \
    --install-location "/usr/local/bin" "myexecutable.pkg"
productbuild --quiet --package myexecutable.pkg myexecutable-v1.0.2.pkg
rm myexecutable.pkg
```

- `--root` is the path to the darwin binary folder.
- `--identifier` could be set in the config.  It is normally a reverse-dns style with the executable name at the end, so there could be a default of something like `private.$(whoami).{{ .ProjectName }}`
- `--install-location` could be set in the config with a default of `/usr/local/bin`

**Comment by caarlos0** [comment]
I think it'll be confusing, since AFAIK we can only generate those on a macOS machine right?

**Comment by jorng** [comment]
Yes, but it could be detected like other external dependencies. The downside is that, unlike the other dependencies, it is _only_ available on macOS. 

The pkg format is just XML files and cpio archives, bundled into a xar file, so it could be re-implemented in go, but that’s a much more significant amount of work.

**Comment by caarlos0** [comment]
yes, I don't think it's worth it.

Also not sure I want to maintain any of that - I never really created these kinds of packages...

**Comment by caarlos0** [comment]
Following the ["yes is forever" rule](https://twitter.com/solomonstre/status/715277134978113536), I rather not do this - or at least not right now.

Thanks for the suggestion either way.
