### ISSUE TITLE
Is config "dist"  support templating?

### ISSUE THREAD

**Issue by foolin** [goreleaser/goreleaser#747]
I want to set like this, build every time in new version folder:

```yaml
dist: dist/{{.ProjectName}}_{{.Version}}
```

Is it  support?

**Comment by caarlos0** [comment]
Hi @foolin, no, it does not support templates.

What is the use case for that?

**Comment by foolin** [comment]
I want to archive the folder without “—rm-dist”

**Comment by caarlos0** [comment]
yeah, but why?

**Comment by foolin** [comment]
I wan't to push every version package for self-host git repository， use “—rm-dist” option will remove the .git info. So I must change .goreleaser every time, it's very tedious.

**Comment by foolin** [comment]
Thanks!

**Comment by caarlos0** [comment]
I rather not do this for now, as at the time dist folder is defined other info required for templating are not yet available.

You can workaround using envsubtst or something like that. Pushing artifacts to a git repo is not a common usecase AFAIK. You could also copy the artifacts to another folder on each release...
