### ISSUE TITLE
Checksum header for Artifactory artifacts

### ISSUE THREAD

**Issue by wburningham** [goreleaser/goreleaser#752]
**Is your feature request related to a problem? Please describe.**
When configuring goreleaser to upload artifacts to Artifactory I noticed that the `checksum: true` option uploads a file with all the checksums, but does not send a `X-Checksum-SHA256` header. Without this header the following warning/error appears in Artifactory:

![image](https://user-images.githubusercontent.com/712078/43909208-ff6643a6-9bb6-11e8-90f9-597b2214cc1c.png)

**Describe the solution you'd like**
Be able to send the `X-Checksum-SHA256` header with the checksum when uploading to Artifactory to show that it is a trusted upload.

**Describe alternatives you've considered**
Step one: Figure out the schema of the `.goreleaser.yml` in order to enable sending a checksum header

Option A: use the existing `checksum: true` option for an artifactory config
Option B: and a new specific option (like `send_checksum_header`)
Option C: and a new generic option that works with HTTP Puts (like `checksum_header: "X-Checksum-SHA256"`)
Option D: something else

Step two: figure out how in code to calculate and send the header

Option A: update `artifact.Artifacts` to have some sort of `Update` method so in the checksum pipe we can add the checksum to the artifact's `Extra` map which we can then later pull out when doing the actual HTTP Put
Option B: recalculate the SHA256 checksum in `http.newUploadRequest`
Option C: something else

**Comment by caarlos0** [comment]
maybe we could change the `artifacts.Add` method to calculate the sha256sum and set it to a field... that would require a lot of refactor though.

other option would be to add a `SHA256Sum` method to the `Artifact` struct, and make it lazy (or not).

Still not sure how's the best way to do the header part though.

**Comment by wburningham** [comment]
Just checking in on this. Is there anything wrong with the PR?

**Comment by wayneashleyberry** [comment]
not quite sure why I was tagged in this issue, perhaps a typo?

**Comment by caarlos0** [comment]
> Just checking in on this. Is there anything wrong with the PR?

just wanted feedback if that was what you needed...

**Comment by caarlos0** [comment]
> not quite sure why I was tagged in this issue, perhaps a typo?

sorry, probably yes :/

**Comment by caarlos0** [comment]
merged, will be on next release.
