### ISSUE TITLE
prepare for vgo

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#764]
we should test if everything works fine under vgo, and possibly migrate to it, so users could `go get` under go 1.11 :)

**Comment by jbaruch** [comment]
Sorry for the dumb question, but do you use user's `go` distribution to run? If so, from what I see, once the user has the mod file in their project, Go 1.11 will just do the right thing.

**Comment by caarlos0** [comment]
> Sorry for the dumb question, but do you use user's go distribution to run? If so, from what I see, once the user has the go.mod file in their project, Go 1.11 will just do the right thing.

yes, I just wan't to make sure everything works as expected... also maybe use vgo in goreleaser it self, so users can `go get` it without `dep` and etc.. :)

**Comment by mxk** [comment]
A `go mod download` step may be required before running multiple concurrent builds: https://groups.google.com/forum/#!topic/golang-nuts/HNP3Ry16oVI

I updated my CI/CD configs to do this before running goreleaser, but more people will probably be encountering this problem and it would be nice if goreleaser did this automatically.

I would also suggest adding `-mod=readonly` to the default set of build flags.

**Comment by caarlos0** [comment]
that makes sense... documentation will probably require some changes...

**Comment by caarlos0** [comment]
everything works fine.

let's also migrate goreleaser to use vgo in its own build.
