### ISSUE TITLE
Add build information to JFrog Artifactory

### ISSUE THREAD

**Issue by jbaruch** [goreleaser/goreleaser#773]
When deploying to JFrog Artifactory it is beneficial to add the deployed artifacts to [build info metadata](https://www.jfrog.com/confluence/display/RTF/Build+Integration). 
It provides information about the build right where the artifacts are. Here's an example of how Java build-info looks like: 
![Java Build Info](https://monosnap.com/image/7zmx0d2WLDjRiQzyqzflG9yLhm3X5P.png)

From the user perspective, all they need to do is specify build name and build number in goreleaser.yml `artifactory` section.

**Comment by jbaruch** [comment]
@caarlos0 we (@jfrog) will try and do a PR for this one.

**Comment by caarlos0** [comment]
> @caarlos0 we (@jfrog) will try and do a PR for this one.

great 🗡 

let me know if I can help!
