### ISSUE TITLE
run configuration missing / single project out of multiple go files

### ISSUE THREAD

**Issue by mwiora** [goreleaser/goreleaser#775]
**Describe the bug**

I want to release software that consists out of multiple go files of the same package.
native "go build" can handle this
in GoLand I had to configure the "run kind" from "file" to "directory"

**To Reproduce**

please have a look here on the failure of the build
https://travis-ci.org/mwiora/NAMEinator/builds/419904194

```
...
⨯ release failed after 38.79s error=failed to build for linux_amd64: # command-line-arguments
./main.go:62:29: undefined: nsInfoMap
./main.go:66:16: undefined: nsStoreGetMeasurement
./main.go:75:27: undefined: nsInfoMap
./main.go:83:16: undefined: nsStoreGetRecord
./main.go:95:31: undefined: nsInfoMap
./main.go:95:49: undefined: dInfoMap
./main.go:99:3: undefined: loadNameserver
./main.go:101:2: undefined: prepareBenchmarkNameservers
./main.go:105:31: undefined: nsInfoMap
./main.go:105:49: undefined: dInfoMap
./main.go:101:2: too many errors
Script failed with status 1
```

**Expected behavior**

The build should complete successfully on my code
https://github.com/mwiora/NAMEinator

**Comment by caarlos0** [comment]
Hi :D 

If you set the `build.main` property to the directory, it should work. https://goreleaser.com/build/
If `go build` works, goreleaser should work as well, as it just calls `go build` underneath.

If that doesn't work, please run goreleaser with `--debug` and paste here both the full output and the contents of `dist/config.yaml` as well.

**Comment by mwiora** [comment]
hi man ;)

actually the magic was to remove the build-main part.
After removing it, obviously the whole directory was taken under inspection...

I just implemented the full version - delegating the whole process out to travis-ci.

It currently seems very complicated (I still do not understand why one of my test-repos which should build a windows-release-package was only building for linux and darwin...) - maybe there is a possibility to simplify the travis-ci inclusion and add an error output by default (maybe after enabling debug by environment variable) as this should be the most often implementation.

As soon as you've seen my suggestion regarding the debug-enabled-by-env-var feel free to close that issue for now.

Cheers,
Matthias

**Comment by caarlos0** [comment]
to run in debug, you can change the script to `curl -sL https://git.io/goreleaser | bash -s -- --debug` :)
