### ISSUE TITLE
Consistent project name

### ISSUE THREAD

**Issue by jorinvo** [goreleaser/goreleaser#79]
Is it *releaser*, *release*, *Goreleaser*, *goreleaser*, *GoReleaser*,... ?

Also, the released binary is called `release` and the binary I get via `go get` is called `releaser`.
(Personally, I would prefer a `goreleaser` binary)

What do you think?

**Comment by caarlos0** [comment]
I agree!

Let's rename the binary to goreleaser and in other places let's let it be GoReleaser.

What do you think?

**Comment by jorinvo** [comment]
As long as it is consistent I think its a good choice :)

To get binary to be `goreleaser` in the `go get` way you would need to rename the whole repository though.

**Comment by caarlos0** [comment]
indeed, I need to go AFK now, I'll do it later =)

**Comment by jorinvo** [comment]
No hurry :)

**Comment by caarlos0** [comment]
Done, let's wait for what will break 😆
