### ISSUE TITLE
Disable "release" pipeline by default

### ISSUE THREAD

**Issue by lalloni** [goreleaser/goreleaser#799]
For goreleaser users which doesn't publish releases to github its against the tool that we need to disable the "release" pipeline in all projects. To make things worst the pipeline is named "release" and in the config file you end up reading "disable releases" which is not intuitive at all.

It would be nice if the release pipeline would be disabled by default as other pipelines are and get enabled when some required configuration is set (name_template?).

I understand this is a rather disruptive change that would break a lot of builds in the wild so some compromises could be in order. 

The first one that comes to mind would be to use behavior versioning so if the config file has a version (e.g.) "1" (or no version) goreleaser could keep current behavior and if version is (e.g.) "2" it could behave in the new way.

A second alternative could be that when goreleaser detects a git remote with a github URL then it could keep the current behavior, otherwise it would default to disable the release pipeline.

Colaterally it would be nice if the release pipeline gets renamed to "github" or something that makes it clear that it affects only github repositories.

I could help with the coding if there's some kind of consensus on this.

**Comment by caarlos0** [comment]
I understand the motivation, but most people use releases, and.. at this point, changing that would be confusing.

Versioning could be a good idea, but it also requires us to keep several documentation versions...

I rather not do this now.

Once v1 is out, we can re-think on a lot of things for v2 (already have some ideas).

Will close for now :)

Thanks!
