### ISSUE TITLE
send metrics somewhere?

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#8]
just to know how many people are actually using it 👍

**Comment by caarlos0** [comment]
I think this is also important, so we can better measure the impact of changing things.

Do any of you guys know something free were we can send stuff like:

- project name
- goreleaser version
- goreleaser.yml info (goos, goarch, ... ?)

I was thinking about setup a free redis somewhere... but feels like a overkill...

**Comment by jorinvo** [comment]
Personally, I would prefer to keep the binary free of additional HTTP calls.
Also, we should never fetch private information like the project name or even the goreleaser.yml configuration. 

The star count and https://github.com/goreleaser/goreleaser/graphs/traffic already give some insights in the popularity of the projects 😉

**Comment by caarlos0** [comment]
@jorinvo well, makes sense... I hadn't thought about this as a privacy invasion, but, yeah, makes sense.

Let's just close this.
