### ISSUE TITLE
Any tags that are non-semantic break goreleaser

### ISSUE THREAD

**Issue by theganyo** [goreleaser/goreleaser#806]
I see this error when I add any tag that is not a semantic version:

```
release failed after 0.06s error=failed to generate snapshot name: tmpl: Invalid Semantic Version
```

This happens even if I'm using the `--snapshot` or `--skip-publish` options.

**Comment by caarlos0** [comment]
yes, this is in the docs: https://goreleaser.com/semver/

**Comment by caarlos0** [comment]
hmm, this happens if your last tag is not semver. The snapshot name template supports `.Minor`, `.Major` and other fields, that's why it breaks.

This will probably be rework on #782. 

Feedback wellcome on that issue BTW.
