### ISSUE TITLE
How to correct pass build flags (-tags)?

### ISSUE THREAD

**Issue by kamilsk** [goreleaser/goreleaser#810]
**Describe the bug**

I see the documentation https://github.com/goreleaser/goreleaser/blob/master/www/content/build.md related to flags

```
    flags:
      - -tags
```

But I take an error: `flag provided but not defined: -tags ctl
usage: go build [-o output] [-i] [build flags] [packages]` when I use it.

**To Reproduce**

Job: https://travis-ci.org/kamilsk/guard/jobs/431173245
Build definition: https://github.com/kamilsk/guard/blob/master/.goreleaser.yml#L41-L54
`go build` what I use locally: https://github.com/kamilsk/guard/blob/master/env/make/cmd.mk#L15

**Expected behavior**

Build successful.

**Environment (please complete the following information):**

- OS: Ubuntu
- OS version: 14.04
- GoReleaser Version [goreleaser --version]: 0.87.0

**Comment by kamilsk** [comment]
ok, I got it

```go
// +build test

package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	var cmd *exec.Cmd

	cmd = exec.Command("go", "build", "-tags", "ctl", "-o", "test", "-i", ".")
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	fmt.Println(cmd.Run())

	cmd = exec.Command("go", "build", "-tags=ctl", "-o=test", "-i", ".")
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	fmt.Println(cmd.Run())

	cmd = exec.Command("go", "build", "-tags ctl", "-o test", "-i", ".")
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	fmt.Println(cmd.Run())
}
```

```bash
$ go run -tags test build.go
```

Possible solutions:
- split by space
- add better example to the docs: `- -tags='your awesome tag'`

**Comment by caarlos0** [comment]
yeah, I think we need to fix the docs :D 

Thanks for reporting!

**Comment by kamilsk** [comment]
Wow! So fast! 🥇

Thank you @caarlos0
