### ISSUE TITLE
Sort changelog by commit timestamp

### ISSUE THREAD

**Issue by caalberts** [goreleaser/goreleaser#812]
**Is your feature request related to a problem? Please describe.**
Currently the changelog is sorted alphabetically, in either direction based on the option.
Given that each row of the changelog starts with the commit hash, it's a learned behaviour to expect the commit hashes to be chronological, either newest first or oldest first.

**Describe the solution you'd like**
A changelog sort option to sort chronologically, `newest-first` and `oldest-first`.

**Describe alternatives you've considered**
Some alternatives on the option values:
- `newest-first` vs `oldest-first`
- `time-asc` vs `time-desc`

**Additional context**
No change to existing sort options and default value `empty`

**Comment by tomascaslo** [comment]
I'd like to work on this.

**Comment by caarlos0** [comment]
> I'd like to work on this.

awesome, let me know if you need anything =D

**Comment by caarlos0** [comment]
yeah, also not sure... IMHO, we can just don't do anything for now...

**Comment by mpchadwick** [comment]
Considering that GitHub sorts commits in ascending chronological order (oldest first) I think it would be nice to be able to have the commit changelog commits sorted that way. IMHO that would actually be the most sane default.
