### ISSUE TITLE
Docker build + multiple registries.

### ISSUE THREAD

**Issue by flyinprogrammer** [goreleaser/goreleaser#832]
**Is your feature request related to a problem? Please describe.**

We build 1 container with the same content, and tags, but we have to publish it to more than 1 registry. Today that involves creating more than 1 docker block, and then that means I loose sane defaults:  https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/docker/docker.go#L47

**Describe the solution you'd like**

I'd like to specify more than 1 registry in a docker block, just as an additional tagging/processing step within a single docker block.

**Describe alternatives you've considered**
I could do this processing outside of goreleaser.
We could just best-effort our sane defaults for all docker blocks.

**Additional context**
I work for a bigger company that has insane processes for builds, so I full appreciate that I'm probably alone in having this problem. I'm also more than willing to write the PR, I just wanted community input first.

**Comment by caalberts** [comment]
I could give this a shot, taking #834 approach to test it.

**Comment by caarlos0** [comment]
fixed on #840!
