### ISSUE TITLE
Test docker using docker in docker

### ISSUE THREAD

**Issue by caalberts** [goreleaser/goreleaser#834]
The docker tests currently push to the local Docker registry. When some tests fail, the images might remain in the registry, instead of being cleaned up.

Having test registries running locally, using something like [Docker in Docker](https://hub.docker.com/_/docker/), that would be removed after tests, might be a better approach.

This will also help in testing #832.

If you think this is a good idea, I could try to do this and work on #832 at the same time

**Comment by caarlos0** [comment]
hmm, doesnt seem to be a bad idea... but maybe its simpler to just kill and start the registry again for every test? (or just wipe it clean)
