### ISSUE TITLE
macOS codesign step

### ISSUE THREAD

**Issue by blacktop** [goreleaser/goreleaser#835]
I know you have a **signing** step for PGP signing, but Littlesnitch is becoming really annoying with non-codesigned binaries.  So I thought it would be cool to have a step or config for the signing step to using the `codesign` binary and sign go binaries with your identity etc etc

I suppose I could just use the **signing** `cmd` to do it, but thought there might be a more elegant smoothe implimentation you could come up with.

Just a thought.  

I ❤️ goreleaser

**Comment by caarlos0** [comment]
Hi! 

> I ❤️ goreleaser

Thanks for the kind word 😬

So, the sign pipe is supposed to be generic enough so it could be used with different signing mecanisms (and versions of them)... if you pull that off, though, it would be great if we could add examples to the documentation :D 

I never used `codesign`, so no idea how to make it work haha
