### ISSUE TITLE
Dry-run /non publishing run.

### ISSUE THREAD

**Issue by FredrikFolkesson** [goreleaser/goreleaser#839]
Hi!

Maybe I am just missing it in the docs, but I would like to try and run goreleaser as a "dry run" to just create the archives but not actually upload them to GitHub.

(I would like to run the tool and check that the output is how I want it before running it live as part of our CI pipeline)

**Comment by caarlos0** [comment]
`--skip-validate --skip-publish`  should do the trick..

**Comment by caarlos0** [comment]
possibly, yes! haha
