### ISSUE TITLE
improve log output

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#845]
When the publish pipe runs, some of the publishers descriptions start with `creating `, which makes the output weird.

We should probably drop those `creating ` prefixes.

We should also find a way to make it clearer that some logs are part of one step, eg:

```
   • PUBLISHING ARTIFACTS
      • releasing to s3
      • skipped                   reason=s3 section is not configured
      • releasing with HTTP PUT
      • skipped                   reason=put section is not configured
      • releasing to Artifactory
      • skipped                   reason=artifactory section is not configured
      • releasing to GitHub
      • creating or updating release repo=caarlos0/couchbase-exporter tag=v0.0.2
      • release updated           url=https://github.com/caarlos0/couchbase-exporter/releases/tag/v0.0.2
      • uploading to release      file=dist/couchbase-exporter_0.0.2_checksums.txt name=couchbase-exporter_0.0.2_checksums.txt
      • uploading to release      file=dist/couchbase-exporter_0.0.2_darwin_amd64.tar.gz name=couchbase-exporter_0.0.2_darwin_amd64.tar.gz
      • uploading to release      file=dist/couchbase-exporter_0.0.2_linux_amd64.tar.gz name=couchbase-exporter_0.0.2_linux_amd64.tar.gz
      • creating homebrew formula
      • skipped                   reason=brew section is not configured
      • creating scoop manifest
      • skipped                   reason=scoop section is not configured
      • creating Docker images
      • pushing docker image      image=caarlos0/couchbase-exporter:latest
      • pushing docker image      image=caarlos0/couchbase-exporter:v0.0.2
      • Snapcraft Packages
   • release succeeded after 31.34s
```

its clear that `releasing to s3` and etc are under `publishing artifacts`, but it may not be clear that where on publisher starts or ends and also what logs are part of what publisher... maybe add another indentation level?

**Comment by V1shvesh** [comment]
Can I help out?

**Comment by caarlos0** [comment]
sore, at least the `creating` prefix is a low hanging fruit :) 

the other part I'm not sure how to solve yet... ideas appreciated! :D

**Comment by julio-garcia-fc** [comment]
I would like to help here, but I have a few questions:

1. I am seeing problems on mac when run `make ci` or `make test`
2. Do you mean that `creating Docker images` should change to `Docker images`?
3. It seems like `creating or updating ...` should not change?

Can you clarify?

**Comment by caarlos0** [comment]
Hi, `make test` may fail, yes, it depends on several tools right now (gpg, docker, etc). You can run `make test -e SOURCE_FILES=./foo/bar/...` if you want to test only the package `foo/bar` for example. `make lint` should work though.

About the logs, yes, for now we can just remove the `creating` prefixes and leave only things like `Docker Images`, `S3`, etc..
