### ISSUE TITLE
docker images are not listed in the release notes anymore

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#846]
**Describe the bug**

Once upon a time we listed the published docker images within changelog:
![image](https://user-images.githubusercontent.com/245435/47436875-c45b4600-d77d-11e8-9d1d-52bf83a57d78.png)

Since v0.90.0 it stopped working, probably due to the publishing (#827) refactory.

**To Reproduce**

Just release a project with docker images.

**Expected behavior**

Same as before

**Comment by jonathanlloyd** [comment]
I'd like to take a look at this :slightly_smiling_face:

**Comment by caarlos0** [comment]
Great, please go ahead! :D
