### ISSUE TITLE
Installation fails due to dep ensure

### ISSUE THREAD

**Issue by izgeri** [goreleaser/goreleaser#877]
**Describe the bug**

In the [documentation](https://goreleaser.com/), under "Using go get", you advise
```
$ go get -d github.com/goreleaser/goreleaser
$ cd $GOPATH/src/github.com/goreleaser/goreleaser
$ dep ensure -vendor-only
$ make setup build
```
However, it appears that goreleaser has been updated to use go modules, and when I try to do this I get the error:
`could not find project Gopkg.toml, use dep init to initiate a manifest
The command '/bin/sh -c go get -d github.com/goreleaser/goreleaser &&     cd $GOPATH/src/github.com/goreleaser/goreleaser &&     dep ensure -vendor-only &&     make setup build' returned a non-zero code: 1`

**To Reproduce**

See above.

**Expected behavior**

The documentation should be updated to provide instructions for using goreleaser with `go get` now that the project uses Go modules.

**Environment (please complete the following information):**

Attempted to build in `golang:1.11-alpine` Docker image.

**Additional context**

**Comment by caarlos0** [comment]
sorry, will fix that...

for now, you can just ignore this step, it is no longer necessary :) 

thanks for reporting!

**Comment by izgeri** [comment]
Thanks @caarlos0. To clarify, it should now just be
```
go get -d github.com/goreleaser/goreleaser
cd $GOPATH/src/github.com/goreleaser/goreleaser
make setup build
```
right?

**Comment by caarlos0** [comment]
yeap, that should work!

**Comment by caarlos0** [comment]
you can also check https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md
