### ISSUE TITLE
Use Alpine as Docker image base

### ISSUE THREAD

**Issue by sgnn7** [goreleaser/goreleaser#882]
Current use of `golang:1.11` creates a _very_ bulky Debian version of the final image (1.15GB) vs what could be a smaller image if they were swapped to use Alpine.

**Comment by caarlos0** [comment]
just a note: alpine does not use gcc, so, on the cgo image, this may cause other issues I think...

**Comment by sgnn7** [comment]
Hmm... I think gcc is easily installable though (we use it for internal CGO builds) but if I end up working on this, I'll keep it in mind 👍

**Comment by sgnn7** [comment]
@caarlos0 I'm playing around with implementation of this issue but I'm curious why docker is needed within the container? Is the user expected to mount the host's working Docker socket (`unix:///var/run/docker.soc`) into the container before running it?
