### ISSUE TITLE
Option to skip writing changelog to Github release

### ISSUE THREAD

**Issue by hbagdi** [goreleaser/goreleaser#888]
**Is your feature request related to a problem? Please describe.**
I don't want to upload the changelog with all commit messages since the last release.

**Describe the solution you'd like**
An option inside .goreleaser.yml to skip creating and upload the changelog.

**Describe alternatives you've considered**
I'm manually updating the release and deleting the changelog section.

**Comment by hbagdi** [comment]
Since this was closed by the bot, where can we track such feature requests?

**Comment by bmuschko** [comment]
I'd appreciate this feature as well. An automatically generated changelog is useful, however, as a user I prefer more concise and tailored information. Commit message are usually too fine-grained.

**Comment by caarlos0** [comment]
@bmuschko while not much obvious, you can try `goreleaser --release-notes /dev/null`... I think it should work...

**Comment by bmuschko** [comment]
@caarlos0 Thanks for the tip. I tried that but i doesn't seem to work. It still publishes the changelog.

**Comment by caarlos0** [comment]
hmm yeah, I wasn't sure it would work.. .thanks for testing... I'll try to take a look at this soon :)
