### ISSUE TITLE
Creating RPMs for different EL linux versions

### ISSUE THREAD

**Issue by jaxxstorm** [goreleaser/goreleaser#891]
**Is your feature request related to a problem? Please describe.**

When I build RPM packages, I generally build them for CentOS 6 and CentOS 7. Currently goreleaser assumes you make a single RPM, with an array of files you can include.

If I include an systemd script, it won't work on CentOS 6. I can write an init script and use it on both, but then I miss out on the power of systemd.

**Describe the solution you'd like**

I'd like to be able to create an array of packages, with configurable options for the files include.

**Describe alternatives you've considered**
As above, using an init script

**Comment by jaxxstorm** [comment]
Is there any way I can stop this from being closed?

**Comment by caarlos0** [comment]
now we can already add multiple rpm configs... does it already fix this issue @jaxxstorm? 

Do we need to add more things?

**Comment by jaxxstorm** [comment]
yep
