### ISSUE TITLE
Support for multiple formats for archives eg zip & tar.gz

### ISSUE THREAD

**Issue by tiger5226** [goreleaser/goreleaser#902]
**Is your feature request related to a problem? Please describe.**

It would be great if we could release in more than 1 format. I have a use case where different areas of the business want each for different but good reasons. 

**Describe the solution you'd like**

I would like to define multiple formats for the archives of a build. Currently this only accepts one. We can different ones for each platform but I would like to have archives uploaded as .zip and .tar.gz. Docker only supports tar.gz natively, otherwise you must use an additional container as an image build stage to get zip to unzip a binary as part of the image build. 

Current devops, uses zip files for their uses. So we could use both. 

**Describe alternatives you've considered**

The only alternative is to manually create these and upload. My whole release workflow is done with goreleaser/travis.

**Comment by caarlos0** [comment]
this will probably be handled in #705
