### ISSUE TITLE
Add ability to include third-party licenses for dependencies

### ISSUE THREAD

**Issue by bmuschko** [goreleaser/goreleaser#903]
**Is your feature request related to a problem? Please describe.**

Sometimes a user might want to know about the licenses used by the released licenses. This includes the licenses of its dependencies packaged with the binary. Avoid the manual and potentially error-prone process of listing licenses as part of the documentation.

**Describe the solution you'd like**

 The solution should automate the parsing, extraction and inclusion process of all licenses of dependencies used by a released binary. For example the release process could look at the `vendor` directory, identify all files called `LICENSE` or `LICENSE.txt` and then include them when building the binary in a predetermined directory of the archive.

**Describe alternatives you've considered**

Alternatively, goreleaser could provide some sort of "hook"/extension point that can call other functionality e.g. a bash script or an executable to implements the functionality. As a result, the intricate implementation details can be offloaded and/or customized.

**Comment by caarlos0** [comment]
you could do it using `before.hook`

create a shell script that does what you need and outputs the file somewhere, and then add the file on `archive.extra_files`... that should do the trick

- https://goreleaser.com/archive/
- https://goreleaser.com/hooks

**Comment by bmuschko** [comment]
Perfect, thanks for the pointer.

**Comment by caarlos0** [comment]
No problem :) glad to help
