### ISSUE TITLE
Feature: maintain apt repository

### ISSUE THREAD

**Issue by aidansteele** [goreleaser/goreleaser#912]
`goreleaser` does a phenomenal job of building the distributable packages for each platform. What would make it insanely useful is if it could also manage an apt repository -- much like it currently does for Homebrew taps and Scoop. 

Right now I'm achieving this using [`deb-s3`](https://github.com/krobertson/deb-s3), but this is suboptimal as:

* It's a second tool
* Requires a Ruby toolchain installed

What do you think? Is this something you would find valuable being added to goreleaser?

**Comment by caarlos0** [comment]
I'm sorry, I think that would be out of the scope of goreleaser...

**Comment by aidansteele** [comment]
Fair enough! I don’t mean to question your judgment (as you’ve obviously done a good job of maintaining the project!), but isn’t this pretty similar to the Homebrew Formula file, i.e. metadata that describes the built artifact for a package manager?

**Comment by caarlos0** [comment]
np, hope you succeed on that =)

**Comment by wakatara** [comment]
> `goreleaser` does a phenomenal job of building the distributable packages for each platform. What would make it insanely useful is if it could also manage an apt repository -- much like it currently does for Homebrew taps and Scoop.
> 
> Right now I'm achieving this using [`deb-s3`](https://github.com/krobertson/deb-s3), but this is suboptimal as:
> 
>     * It's a second tool
> 
>     * Requires a Ruby toolchain installed
> 
> 
> What do you think? Is this something you would find valuable being added to goreleaser?

Care to share a write up of how you're doing this? I also am using goreleaser for homebrew and snaps releases and wanted to provide an apt repository as well. 

Daryl.
