### ISSUE TITLE
Full integration of snapcraft

### ISSUE THREAD

**Issue by igorljubuncic** [goreleaser/goreleaser#914]
Snapcraft 3.0 introduces new functionality that is currently not supported in goreleaser. It would be really useful to reflect these changes in goreleaser and allow full compatibility with snapcraft.

Example: base:core18

The base keyword specifies a special kind of snap that provides a minimal set of libraries common to most applications, and it is mounted as the root filesystem for application.

**Proposed enhancement**

Allow developers to import entire snapcraft.yaml into .goreleaser.yml as is, and then selectively replace specific fields, e.g. name, description using variables (to allow integration and automatic builds), but then pass other declarations to snapcraft without additional syntactic checks (in these are not explicitly supported in goreleaser).

**Comment by caarlos0** [comment]
which fields are missing? (besides `base`)?

**Comment by caarlos0** [comment]
If you have a documentation link it will also be helpful. 

I tried looking into https://docs.snapcraft.io/snapcraft-yaml-reference/4276, but couldn't find anything related to `core18` and the `base` and `core` links does not work...

Another question I have is: can I declare dependencies? For example, if I have an app that depends on git... how can I make it work?

**Comment by igorljubuncic** [comment]
Hi Carlos,

So here's what I was thinking (apart from the fields you already support):

**Parts**

For example, this include:

parts:
  appname:
    plugin: go
    source: https://github.com/something.git
    go-importpath: github.com/something

But this could look different for other languages, like python for instance - this isn't the scope of go, but the idea is that there are keywords you might not necessarily use in a given scenario, but they could exist, and someone may try them.

parts:
  appname:
    plugin: python
    python-version: python2
    source: https://github.com/something.git

Anyway, these are two examples where you also use plugins to build, with language-specific overrides.

There could also be stage packages and build packages:

parts:
  something:
    plugin: go
    source: https://github.com/something/something.git
    go-importpath: github.com/something
    build-packages:
      - build-essential
      - libpcap-dev
      - libnetfilter-queue-dev
    stage-packages:
      - libpcap0.8
      - libnfnetlink0
      - libnetfilter-queue1

BTW, we have language guide wizards here: https://snapcraft.io/first-snap

This is the more relevant documentation:
https://docs.snapcraft.io/the-snapcraft-format/8337
https://docs.snapcraft.io/snapcraft-parts-metadata/8336
https://docs.snapcraft.io/snapcraft-app-and-service-metadata/8335

**Hooks**

Conditional triggers:
https://docs.snapcraft.io/supported-snap-hooks/3795

I agree that the current documentation can be improved, and I'll take your feedback as another pointer on this.

My suggestion would be - if there's a declaration that you don't support it at the moment, ignore it and pass it on to snapcraft as is, and worse case, there will be an error in snapcraft but the build won't be blocked by goreleaser.

Hopefully, this makes sense.

Thanks.

**Comment by guilhem** [comment]
Since https://github.com/snapcore/snapd/pull/5845 is solved, we can set files permitted to be edited by software. (without having to be `native` confinement)
```yaml
plugs:
  personal-files:
    read:
      - $HOME/.kube/config
      - $HOME/.minikube/client.key
      - $HOME/.minikube/client.crt
      - $HOME/.minikube/ca.crt
```
This is not in `apps.plugs`

`aliases` is also really important when your repository have multiple binaries.

Here is a complete list of yaml parameters: https://github.com/snapcore/snapd/blob/master/snap/info_snap_yaml.go#L35

**Comment by caarlos0** [comment]
if I understand correctly, the `parts` thing is used to build the snap, right? If so, it doesn't make sense for goreleaser, as the binary will be already compiled...

**Comment by igorljubuncic** [comment]
You can use parts with the dump plugin - so you don't compile, you just grab the source. But then, if you compiled with different libraries than snapcraft has (in its base), you will need to specify them as stage packages.

https://docs.snapcraft.io/the-dump-plugin/8007

But if you support all parts/plugins, developers have the options to choose what they need.

Thanks!

**Comment by jimafisk** [comment]
This feature would be really great to have! We're building a static site generator with a Go CLI that requires running npm and node to compile svelte components. Unfortunately we aren't able to execute npm/node outside of our snap: https://github.com/plentico/plenti/issues/31

I was able to add `home` and `network-bind` plugs to allow writing to the filesystem and serving a local website while still using `strict` confinement. However, it would require `classic` confinement to execute the user's system npm/node, which under manual review it was suggested to use `stage-packages`/`stage-snaps` instead: https://forum.snapcraft.io/t/classic-confinement-request-for-plenti/17803/9?u=jimafisk

**Comment by caarlos0** [comment]
happy to review a PR on that. :)

FWIW there is one opened that adds some stuff #1553

**Comment by jimafisk** [comment]
Thanks and sorry if I came across as demanding. Goreleaser is amazing, I def appreciate all the hard work the team is doing :).

**Comment by caarlos0** [comment]
No problem at all, just that I don't have time to work on this right now, so if someone can work on a PR it would be awesome :)
