### ISSUE TITLE
Add submodules logs to Changelog

### ISSUE THREAD

**Issue by 1138-4EB** [goreleaser/goreleaser#915]
**Is your feature request related to a problem? Please describe.**
Project File Browser is composed of a backend, [filebrowser/filebrowser](https://github.com/filebrowser/filebrowser), and a frontend, [filebrowser/frontend](https://github.com/filebrowser/frontend). The frontend is a git submodule of the backend.

Right now, goreleaser generates a Changelog containing the git commits since the previous release: https://github.com/filebrowser/filebrowser/releases/tag/v1.11.0 But changes in the frontend are not listed there.

**Describe the solution you'd like**
It'd be great if goreleaser added the list of commits that changed in the submodule, maybe in a subsection of the changelog.

**Describe alternatives you've considered**
Manually editing the changelog after it is created by goreleaser.

**Additional context**
Every tag in the backend exists in the frontend too.

**Comment by caarlos0** [comment]
you can use a custom changelog generator and pass its output to goreleaser:

```sh
goreleaser --release-notes=<( ./my-changelog-generator.sh )
```

will not change how this works, at least not for now.

thanks for the suggestion though!
