### ISSUE TITLE
Update docs on how to avoid deploying multiple times

### ISSUE THREAD

**Issue by jorinvo** [goreleaser/goreleaser#92]
When running Travis CI I like to test multiple OSes and maybe even different Go version.
However, only one of them should deploy the binaries.
My current solution is a test like this:
https://github.com/qvl/sleepto/blob/master/.travis.yml#L9

I don't know if we should mention this in the docs.

Also, what I don't like about this solution is, that it deploys as soon as this particular CI run was successful. As far as I know there is no way of running code only after all OS-version combination have been completed?

**Comment by caarlos0** [comment]
I think there is no much alternative besides doing an `if` like you did...

You can make it more readable, though:

```yaml
test "$TRAVIS_OS_NAME" = "linux" -a -n "$TRAVIS_TAG" && blah
```

It can be indeed a good idea to add it to the README...

**Comment by jspc** [comment]
I've got a machine somewhere doing builds and releases for a project. The machine listens to CI builds (via callback mechanism) and, when all expected builds have completed, releases.

You could do that.

Outside of that there's nothing in the travis docs that suggests a better way.

**Comment by medhoover** [comment]
How about a separate release branch?

**Comment by caarlos0** [comment]
> How about a separate release branch?

what do you mean?

**Comment by medhoover** [comment]
Set the Travis config to release the build on a specific branch other than master. This branch will be used only for releases.
```sh
 if [ "$TRAVIS_BRANCH" == "release" ]; then ...
```
Not sure how this can be wired to be executed at the end of other tests, but it can limit the release to a single build.

**Comment by caarlos0** [comment]
But the problem here seems to be the OS matrix, I don't see how having a branch for releases would help in that case...

**Comment by medhoover** [comment]
Sorry, I thought this was about limiting deployment to a single build rather than doing the same release it to all OS :)
