### ISSUE TITLE
linuxbrew support

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#927]
Now homebrew also supports linux, so we may add this to goreleaser as well.

**Additional context**
- https://github.com/getantibody/antibody/issues/277
- https://discourse.brew.sh/t/how-to-create-a-tap-that-works-on-linux-and-macos/3902/2

**Comment by caarlos0** [comment]
it seems that this will require a rewrite of how the brew pipe works... and some extra settings even to support multiple builds and archives

**Comment by caarlos0** [comment]
would also be goo to add a `This file is generated, do not edit` header or something...

**Comment by JuPlutonic** [comment]
Some concerns:
https://discourse.brew.sh/t/how-to-create-a-tap-that-works-on-linux-and-macos/3902/10
https://discourse.brew.sh/t/how-to-create-a-tap-that-works-on-linux-and-macos/3902/11

**Comment by tobimensch** [comment]
https://github.com/browsh-org/browsh/issues/254

This feature is getting requested by Browsh's users, too.

**Comment by twpayne** [comment]
Also requested by [`chezmoi`](https://github.com/twpayne/chezmoi) users: https://github.com/twpayne/homebrew-taps/issues/1

**Comment by sethkor** [comment]
+1 for this feature please

**Comment by mgrachev** [comment]
I'm just working on it now 😃

**Comment by sethkor** [comment]
@mgrachev good stuff!  Can you also try to support arm64.  The formula may need to be something like:
```
  if OS.mac?
    url "https://github.com/sethkor/blah/mac.tar.gz"
    sha256 "b99ffed098ebb1411f04abbea5da46274e2bcf5f821b3670240e30ecc89e5ffa"
  elsif OS.linux?
  
    case RbConfig::CONFIG["host_cpu"]
    when "aarch64"
      url "https://github.com/sethkor/blah/arm.tar.gz"
      sha256 "1c4fb160b741ebefbf35fedff8f569c494ddfdae52e0f9f454618891f7ed7183"   
    when "x86_64" 
      url "https://github.com/sethkor/blah/amd.tar.gz"
      sha256 "0910b4419f9739457552bb567774bcf3c89c5c9c5060ceec74d28af55a54092d"
    else
      ohdie "Architecture not supported by this forumla"
    end
  end
```

**Comment by caarlos0** [comment]
sorry @mgrachev kind of steal the issue while doing other thing...

this last part about multiple archs is still missing though...

**Comment by sethkor** [comment]
So new issue for arm support or just leave this one?

**Comment by caarlos0** [comment]
> So new issue for arm support or just leave this one?

sounds good!
