### ISSUE TITLE
Keep existing release notes

### ISSUE THREAD

**Issue by estahn** [goreleaser/goreleaser#929]
**Is your feature request related to a problem? Please describe.**
semantic-release creates a GitHub release + tag including a changelog. Goreleaser is triggered upon tag creation and will override the GitHub release notes.

Another alternative is manually created release notes (draft) which then get overridden.

**Describe the solution you'd like**
If a release has existing release notes goreleaser should attach and not override additional information. A possible solution might be to wrap goreleaser notes with `<!-- goreleaser_start -->` and `<!-- goreleaser_stop -->`.

**Comment by caarlos0** [comment]
I rather just don't override the existing notes. 

dupe #856

**Comment by estahn** [comment]
@caarlos0 How are artefacts (docker, homebrew formula, etc) handled? Will these be regenerated and overridden?

The linked issue would work with my proposed solution.

Usually the release notes are prepared (draft) before goreleaser ist triggered. A solution that would manage this use-case would be beneficial imo.
