### ISSUE TITLE
get/latest could be better

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#94]
We can put `https://github.com/goreleaser/get/blob/master/latest` as a asset on our jekyll site, so the url become cleaner, e.g.: `http://goreleaser.github.io/get` (instead of `https://raw.githubusercontent.com/goreleaser/get/master/latest`)

**Comment by jorinvo** [comment]
Also see https://github.com/goreleaser/goreleaser/issues/93#issuecomment-273438717, we should not only offer the `latest` version. Should give users the choice to keep using one stable version.

**Comment by caarlos0** [comment]
@jorinvo that makes sense, maybe we should update docs then.

Using `go get` indeed makes more sense...

**Comment by caarlos0** [comment]
About getting an specific version, I guess `gopkg.in` kind of solves that, no?

**Comment by jorinvo** [comment]
@caarlos0 Nice! I didn't know about `gopkg.in` before :)
Should we reference it as the goto way of using GoReleaser? 
Or should we stick with the `latest` option as default? As soon as we are stable on 1.0 I think we should commit to a stable API in any case...

**Comment by caarlos0** [comment]
@jorinvo I think that for now we can use `go get ` or leave as is.

As soon as v1 is released, we can change docs to use `http://gopkg.in/goreleaser/goreleaser.v1`, that way people using `go get` will still get the latest version, but can change it to v1 if needed.

**Comment by medhoover** [comment]
About the version link, a solution for the version issue is currently being prepared.
[The Saga of Go Dependency Management](https://blog.gopheracademy.com/advent-2016/saga-go-dependency-management/)

**Comment by caarlos0** [comment]
@medhoover yeah, but that could take a while...

**Comment by caarlos0** [comment]
I guess we can close this one...
