### ISSUE TITLE
bug/unexpected - build envs not being shared with hooks:before

### ISSUE THREAD

**Issue by syntaqx** [goreleaser/goreleaser#940]
The order of execution for `before:hooks` and `build:env` feels strange. Here's an example scenario to illustrate what I'm experiencing:

On a host system with `GO111MODULE=auto`

```yaml
before:
  hooks:
    - go mod download
builds:
- env:
    - GO111MODULE=on
```

You would get the following output:

```sh
$ goreleaser --snapshot

   • releasing using goreleaser dev...
   • loading config file       file=.goreleaser.yml
   • RUNNING BEFORE HOOKS
      • running go mod download
   ⨯ release failed after 0.08s error=hook failed: go mod download
go: modules disabled inside GOPATH/src by GO111MODULE=auto; see 'go help modules'
```

> __Note:__ This was masked by the fact that Travis sets the environment variable up for me, and I didn't realize this issue until I started trying to publish a pre-release locally.

Now I understand the intent of `hooks:before` occurring before any other blocks are evaluated, so in my given scenario the  `builds:env` hasn't been set. I don't think that should change. However, there doesn't seem to be another way of setting environment variables intended for the project, not just the `builds` step.

There's a plenty of ways for going about this, but perhaps a better implementation would be something like the following:

```yaml
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
```

Allowing users to set environment variables for all steps, not just `builds`.

Idk, but I do feel like this is a fairly big concern, given as it stands, `go mod download` cannot be trusted to succeed by the efforts of goreleaser alone.

**Comment by lesovsky** [comment]
@syntaqx Is there any workarounds that allow to pass `GO111MODULE=on` and execute `go mod download` with no errors?

**Comment by caarlos0** [comment]
you could run `GO111MODULE=on goreleaser`

**Comment by lesovsky** [comment]
@caarlos0 
yep, thx... I'm using Travis and I've made it in the following way:
```
script: curl -sL https://git.io/goreleaser |GO111MODULE=on bash
```

**Comment by caarlos0** [comment]
you can add to your `env` on travis too, eg: https://github.com/goreleaser/goreleaser/blob/master/.travis.yml#L13

<blockquote><img src="https://avatars2.githubusercontent.com/u/24697112?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/goreleaser/goreleaser">goreleaser/goreleaser</a></strong></div><div>Deliver Go binaries as fast and easily as possible - goreleaser/goreleaser</div></blockquote>

**Comment by moisespsena** [comment]
Global envs doesn't works on builds PRE and POST hooks:

```yaml
builds:
  - hooks:
      pre: pre-script.sh
      post: post-script.sh
```
