### ISSUE TITLE
Is it possible to select which archive/binary gets PUTsed?

### ISSUE THREAD

**Issue by vlymar** [goreleaser/goreleaser#945]
**Is your feature request related to a problem? Please describe.**
I'm trying to figure out how I can use goreleaser to publish debian packages to bintray. I can use the nfpm integration to generate debian packages, and I can use `puts` to publish _every_ artifact to bintray via bintray's API, but i'm not sure how I can combine these features to effectively publish debian releases. E.g. I don't want our darwin artifacts getting sent to our debian package on bintray.

**Describe the solution you'd like**
A filter parameter for the `puts` section that lets you specify one or more artifacts. A first class configurable bintray destination would also be nice (discussed in https://github.com/goreleaser/goreleaser/issues/15), particularly if it would be smart enough to correctly package and publish debian/rpm packages.

**Describe alternatives you've considered**
I'm considering just using goreleaser + nfpm to generate all the packages, then run a script to PUT just the debian package to bintray's API.

We're effectively using goreleaser for github releases, homebrew and docker and love it. Thanks for the work. Its very possible i've missed something in the docs that makes my request already work, please let me know.

**Comment by caarlos0** [comment]
this is been working on #705, or, at least, will be a byproduct of it...

**Comment by caarlos0** [comment]
this should be fixed now.

please verify and reopen if not.

thanks!

**Comment by caarlos0** [comment]
refs https://github.com/goreleaser/goreleaser/pull/1016
