### ISSUE TITLE
An additional parameter not to compress bundled files in archive. Just archive the binaries as it is.

### ISSUE THREAD

**Issue by warrensbox** [goreleaser/goreleaser#946]
**Is your feature request related to a problem? Please describe.**
I am trying to just publish the binaries, 
appbin_0.1.438_darwin_amd64.tar.gz 
appbin_0.1.438_linux_amd64.tar.gz 
appbin_0.1.438_darwin_386.tar.gz 
appbin_0.1.438_linux_386.tar.gz 

**Describe the solution you'd like**
appbin_0.1.438_darwin_amd64 
appbin_0.1.438_linux_amd64
appbin_0.1.438_darwin_386 
appbin_0.1.438_linux_386 
appbin_0.1.438_checksums.txt

I do not want to compress it, I just need the binary in archives

**Describe alternatives you've considered**
Manually building and pushing it.

**Additional context**
An additional parameter not to compress bundled files in archive. Just archive the binaries as it is.

**Comment by IdanAdar** [comment]
Can be done by specifying: 

```
archive:
  format: binary
  name_template: "certificate-manager-{{.Os}}-{{.Arch}}-{{.Version}}"
```

**Comment by caarlos0** [comment]
that's true, I thought the user wanted to have an archive in "archive mode" (without compression).

I was probably drunk when I read this.

**Comment by caarlos0** [comment]
thanks for the help @IdanAdar !

**Comment by warrensbox** [comment]
@IdanAdar  @caarlos0  In the documentation it say the following:
```
 # Archive format. Valid options are `tar.gz`, `zip` and `binary`.
  # If format is `binary`, no archives are created and the binaries are instead uploaded directly.
  # In that case name_template and the below specified files are ignored.
  # Default is `tar.gz`.
  format: zip
```

but in the `name_template` section of the archieve, it says:
```
  # Archive name template.
  # Defaults:
  # - if format is `tar.gz` or `zip`:
  #   - `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
  # - if format is `binary`:
  #   - `{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
```

I thought `name_template` are ignored when the format is `binary`?
Please correct me if I'm wrong...

**Comment by caarlos0** [comment]
hmm, documentation is wrong... will fix it

**Comment by WheresAlice** [comment]
This config will create releases in the format I was using prior to switching to GoReleaser, so this works for me:
```
archive:
  format: binary
  name_template: "{{ .ProjectName }}.{{ .Os }}.{{ .Arch }}"
```

Thanks
