### ISSUE TITLE
#goreleaser Slack channel

### ISSUE THREAD

**Issue by jorinvo** [goreleaser/goreleaser#95]
I create a Channel on https://gophers.slack.com/.
If you don't have an account you can join at https://invite.slack.golangbridge.org/.

This might be helpful for discussions and questions not fit for issues.

Maybe we can link to it in the readme?

**Comment by caarlos0** [comment]
Yes, nice, please do 🗡

**Comment by jorinvo** [comment]
I'll add it after #91 :)
