### ISSUE TITLE
Multiple brew formulae

### ISSUE THREAD

**Issue by rvolosatovs** [goreleaser/goreleaser#956]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to generate multiple brew formulas.
The use case is to build 2 binaries and have a formula per-binary.

**Describe the solution you'd like**
`brews` option, e.g. same as it's done for `dockers` and `builds`.
In fact, I think it makes sense to add the "plural" option for all outputs(e.g. `snaps`, `nfpms` etc).

**Comment by frapposelli** [comment]
I was about to press "Submit new issue" with the same exact request 😄

**Comment by caarlos0** [comment]
refs #705
