### ISSUE TITLE
Support for nixpkgs

### ISSUE THREAD

**Issue by rvolosatovs** [goreleaser/goreleaser#957]
**Is your feature request related to a problem? Please describe.**
It would be great to have a pipe for generating a Nix expression usable by https://github.com/nixos/nixpkgs .
See https://github.com/NixOS/nixpkgs/blob/d499b7d821106964581cbb6eab5354fbdf7a6847/pkgs/development/tools/richgo/default.nix#L1-L21 for example.
https://nixos.org/nixpkgs/manual/#sec-language-go for Go-specific documentation.

**Describe the solution you'd like**
Integrate tool like https://github.com/adisbladis/vgo2nix for generating the expression and `deps.nix` file.

**Additional context**
I'll be happy to work on/help with this feature

**Comment by caarlos0** [comment]
the idea of goreleaser is to build the binary and release that pre-built binary... seems like nix will want to build the binary itself... if so, I rather not add this.

**Comment by rvolosatovs** [comment]
Some packages use prebuilt binaries(usually from Github releases), but indeed, the source builds are preferrable. Let's not do this.

**Comment by caarlos0** [comment]
investigating this again in #3537
