### ISSUE TITLE
Support compressed binaries

### ISSUE THREAD

**Issue by frapposelli** [goreleaser/goreleaser#958]
**Is your feature request related to a problem? Please describe.**
One of the projects I'm working on ([vmware/govmomi](https://github.com/vmware/govmomi)) has a release model where the binaries are just gzipped and not wrapped in a tar. There are multiple users that are relying on that distribution format for their automation, we tried to introduce that breaking change but we had to revert (ref: vmware/govmomi#1143).

**Describe the solution you'd like**
Introduce support for another Archive format: `zipped_binary` or something similar.

**Describe alternatives you've considered**
Tried to work my way around the problem using Hooks, but the file name is changed during the compression process, and that makes the rest of the release fail.

**Comment by caarlos0** [comment]
so, basically another archive format, which is just gzip, right?

**Comment by frapposelli** [comment]
yes, exactly

**Comment by caarlos0** [comment]
check #959

**Comment by frapposelli** [comment]
I guess #959 fixes this issue, what is the way to track progress towards supporting multiple binaries? #787 ?

**Comment by caarlos0** [comment]
yes, its done.

you can track https://github.com/goreleaser/goreleaser/pull/942 , should be there, probably
