### ISSUE TITLE
Unexpected behavior of --release-notes flag while skipping changelog generation

### ISSUE THREAD

**Issue by pkosiec** [goreleaser/goreleaser#961]
**Describe the bug**

Hello,

First of all: awesome project! That's exactly I was looking for.

Today I wanted to integrate custom changelog generation during a deploy with goreleaser. I used `--release-notes` flag with path to a file. I thought I need to add `skip: true`

Multiple times I ended with GitHub release with content equal to the path for provided file with release notes.

To be honest, I wasted plenty of time to look for possible mistakes. Finally I came up with an idea to remove `skip: true` on `changelog`. That was it! 

I think the behavior is confusing.

**To Reproduce**

```yaml
changelog:
  skip: true
```

Run `goreleaser --release-notes /path/to/some/file.md`

Result:

Github Release with the following content:
```
/path/to/some/file.md
```

**Expected behavior**

Github Release with the content of the `/path/to/some/file.md` file

Alternatively: empty GitHub release body (user probably will connect dots and will know, that he needs to remove `skip: true` property)

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin 18.2.0
- GoReleaser Version 0.101.0, commit d2fa6d58211569acedb6c63303477e129da8f32f, built at 2019-02-07T16:29:42Z

**Comment by caarlos0** [comment]
thanks for reporting this!

**Comment by pkosiec** [comment]
Still valid. Bumping
