### ISSUE TITLE
problem installing Go Releaser

### ISSUE THREAD

**Issue by emmanuel-florent** [goreleaser/goreleaser#969]
**Describe the bug**

Unable to install with `go get -u github.com/goreleaser/goreleaser`

**To Reproduce**

`go get -u github.com/goreleaser/goreleaser`

`# github.com/goreleaser/goreleaser/internal/pipe/release
../../../../go/src/github.com/goreleaser/goreleaser/internal/pipe/release/release.go:106:39: 
cannot use ctx.Context.Done() (type <-chan struct {}) as type retry.BreakCloser in argument to retry.Retry:
	<-chan struct {} does not implement retry.BreakCloser (missing Close method)
../../../../go/src/github.com/goreleaser/goreleaser/internal/pipe/release/release.go:106:39: 
cannot use strategies (type []strategy.Strategy) as type []func(uint, error) bool in argument to retry.Retry
`

**Expected behavior**

command exit with no error.

**Environment (please complete the following information):**

- Go version: `go version go1.11.5 darwin/amd64`
- OS version: Darwin MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
- GoReleaser Version N/A

**Additional context**

 reproductible in golang:1.11.2-alpine container

**Comment by emmanuel-florent** [comment]
I can reproduce on  golang:1.12-alpine

**Comment by caarlos0** [comment]
are you following https://goreleaser.com/install/ ?

**Comment by emmanuel-florent** [comment]
I am not following https://goreleaser.com/install/ I am building a third-party app that has the command `go get -u github.com/goreleaser/goreleaser` in it's `makefile` and that now fail with a POSIX error.
My understanding is that `github.com/goreleaser/goreleaser` depends on `github.com/kamilsk/retry/` that has changed API, but I am quite new to Go ecosystem and dependency management so I am not sure if I try to force a previous `goreleaser` version or else ?

**Comment by caarlos0** [comment]
the makefile shouldn't install goreleaser like that... talk to the maintainer of that project...

cheers!
