### ISSUE TITLE
goreleaser linting my project?

### ISSUE THREAD

**Issue by llorllale** [goreleaser/goreleaser#973]
**Describe the bug**
Release failed due reason: `myproject/myfile.go: constant 4294967295 overflows int`. See [here](https://travis-ci.org/llorllale/go-gitlint/builds/501111308).

**To Reproduce**
Leave `math.MaxUint32` as the default value in [this](https://github.com/llorllale/go-gitlint/blob/c4374b4d911fd5c579369e58fa1c2e0088f3dbf1/cmd/go-gitlint/main.go#L35) line.

Release using this [`.goreleaser.yml`](https://github.com/llorllale/go-gitlint/blob/master/.goreleaser.yml)

**Expected behavior**

goreleaser should've performed the release flawlessly without linting my project.

**Environment (please complete the following information):**
See [travis build](https://travis-ci.org/llorllale/go-gitlint/builds/501111308) for environment variables and OS.

- GoReleaser Version [goreleaser --version]: docker image `goreleaser/goreleaser:v0.101`

**Additional context**
Workaround is to simply avoid using numeric values that can potentially overflow.

**Comment by caarlos0** [comment]
goreleaser does not lint anything, it just runs go build... can you try running go build with the failing code?

**Comment by kamilsk** [comment]
You tried to build binary at windows_386, so, you have limitation for int primitive. You can't use uint32 for int (int32 for windows_386) cause 1 bit overflow (sign bit).

**Comment by llorllale** [comment]
@kamilsk oh I see. I got same error with linux_386.

Thanks!
