### ISSUE TITLE
howbrew-tap doesn't work with github actions

### ISSUE THREAD

**Issue by smaftoul** [goreleaser/goreleaser#982]
**Describe the bug**

Using github actions, you cannot publish to homebrew-tap as the tap is another repository and the scope of the GITHUB_TOKEN within actions allows only to write to current repo.

**To Reproduce**

Try publishing to a homebrew-tap within github actions.

**Expected behavior**

Tap published

**Additional context**

I wonder if it's possible wihtin another action to only publish the tap with previous latest release and another GITHUB_TOKEN.

**Comment by caarlos0** [comment]
have you tried adding a custom `GITHUB_TOKEN` secret? 

if that doesn't work, maybe we can change goreleaser to preffer `GORELEASER_GITHUB_TOKEN` or something like that (maybe even on the entrypoint only)...

**Comment by smaftoul** [comment]
You can add the GITHUB_TOKEN secret, but you cannot configure its value. You cannot create a custom secret named GITHUB_TOKEN.
It seems overriding an already specified GITHUB_TOKEN with GORELEASER_GITHUB_TOKEN is the way to go !

**Comment by caarlos0** [comment]
awesome, thanks @smaftoul .

**Comment by caarlos0** [comment]
fixed on #983
