### ISSUE TITLE
 "github.com/aws/aws-sdk-go/aws": zip: not a valid zip file

### ISSUE THREAD

**Issue by liup1211** [goreleaser/goreleaser#991]
go install github.com/goreleaser/goreleaser
go: downloading github.com/aws/aws-sdk-go v1.19.2
/home/go_run_require/pkg/mod/github.com/goreleaser/goreleaser@v0.104.0/internal/pipe/s3/awssession.go:4:2: unknown import path "github.com/aws/aws-sdk-go/aws": zip: not a valid zip file
/home/go_run_require/pkg/mod/github.com/goreleaser/goreleaser@v0.104.0/internal/pipe/s3/awssession.go:5:2: unknown import path "github.com/aws/aws-sdk-go/aws/credentials": zip: not a valid zip file
/home/go_run_require/pkg/mod/github.com/goreleaser/goreleaser@v0.104.0/internal/pipe/s3/awssession.go:6:2: unknown import path "github.com/aws/aws-sdk-go/aws/credentials/stscreds": zip: not a valid zip file
/home/go_run_require/pkg/mod/github.com/goreleaser/goreleaser@v0.104.0/internal/pipe/s3/awssession.go:7:2: unknown import path "github.com/aws/aws-sdk-go/aws/session": zip: not a valid zip file
/home/go_run_require/pkg/mod/github.com/goreleaser/goreleaser@v0.104.0/internal/pipe/s3/s3.go:10:2: unknown import path "github.com/aws/aws-sdk-go/service/s3": zip: not a valid zip file
make: *** [dev-requirements] 错误 1

**Comment by caarlos0** [comment]
please follow https://goreleaser.com/install/

**Comment by liup1211** [comment]
Thanks for your reply.After install the GoReleaser,It still has that problem

**Comment by liup1211** [comment]
> 
> 
> please follow https://goreleaser.com/install/
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/4e061c7edb86e18ea0387efdbcac63a90d658e2a/68747470733a2f2f676f72656c65617365722e636f6d2f66617669636f6e2e69636f">**[Install · GoReleaser](https://goreleaser.com/install/)**

Sir,After install the GoReleaser,It still has that problem。
-----------------------------------------------------------------------------------
go install github.com/goreleaser/goreleaser
go: downloading github.com/aws/aws-sdk-go v1.15.64
build github.com/goreleaser/goreleaser: cannot load github.com/aws/aws-sdk-go/aws: zip: not a valid zip file
Makefile:35: recipe for target 'dev-requirements' failed
make: *** [dev-requirements] Error 1
------------------------------------------------------------------------------------------

**Comment by caarlos0** [comment]
> go install github.com/goreleaser/goreleaser

it does not seem your are following the provided installation guide...

**Comment by caarlos0** [comment]
also: ` 'dev-requirements'` this is not from goreleaser...

**Comment by liup1211** [comment]
> 
> 
> also: ` 'dev-requirements'` this is not from goreleaser...

well,'https://github.com/brocaar/lora-gateway-bridge',this project use goreleaser and nfpm(go.mod,Makefile).
I am a rookie of golang,could you help me.

**Comment by caarlos0** [comment]
that project is installing goreleaser in a non-recommended way, you should open an issue there...
